UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>AnnouncementType__c</fullName>
        <description>Announcement Type</description>
        <inlineHelpText>Type of Announcement</inlineHelpText>
        <label>Announcement Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Competitive</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Sole Source/Directed</fullName>
                </value>
                <value>
                    <fullName>Formula Grants</fullName>
                </value>
                <value>
                    <fullName>Sole Source/Formula</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>- In Progress - The information within the annoucement is incomplete. Such records shall not be avaiable for other users to view or edit.
- Review In Progress - Annoucements that are currently in the process of undergoing review shall have this status. Such records shall not be avaiable for other users to view or edit.
- Inactive - Approved annoucements whose Posting Date is in the future shall have this status. Such annoucements shall not be made available to recipient users.
- Active - Approved annoucements whose Posting Date is equal to the current date or is in the past and the Closing Date is in the future shall have this status. System shall make such annoucements available to recipients.
- Expired - Approved annoucements whose closing date is the current date or is in the past shall have this status. When an annoucement status changes from Active to Expired, it should no longer be made available to the recipient users.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Converted to Application</fullName>
                </value>
                <value>
                    <fullName>Converted to Pre-Application</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Approved</fullName>
                </value>
                <value>
                    <fullName>RFA Published</fullName>
                </value>
                <value>
                    <fullName>RFA Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/SoleSourceAwardRecipient__c.object
<CustomObject>
    <description>[Business] Need to revisit this object (It may not be required and can be DOH specific)</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>External Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sole Source Award Recipients</relationshipLabel>
        <relationshipName>Sole_Source_Award_Recipients</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FundingOpportunity__c</fullName>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Sole Source Award Recipients</relationshipLabel>
        <relationshipName>Sole_Source_Award_Recipients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sole Source Award Recipient</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sole Source Award Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>IsApplicant__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>TRUE ==&gt; Applicant
FALSE ==&gt; Reviewer</inlineHelpText>
        <label>Is Applicant</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/InviteOrgForSoleSourceAwardHelper.cls
global with sharing class InviteOrgForSoleSourceAwardHelper extends GNT.FlexTableActionHandler {
    
    global override Map<String,Object> clickHandler(){
        List<Id> orgIdList = new List<Id>();
        Map<Id, Set<Id>> foIdToContactIdMap = new Map<Id, Set<Id>>();
        String ns = GNT.AppUtils.getNamespacePrefix();
        Map<String,Object> resultMap = new Map<String,Object>();
        List<SoleSourceAwardRecipient__c> lstSar = new List<SoleSourceAwardRecipient__c>();
        Id foId = urlParams.get('id');  
        List<Account> lstAcc = [Select id from Account where id IN :selectedRecordIds];
        for(Account acc : lstAcc){
            SoleSourceAwardRecipient__c sar = new SoleSourceAwardRecipient__c();
            sar.Account__c = acc.Id;
            sar.FundingOpportunity__c = foId;
            lstSar.add(sar);
        }
        if(lstSar.size() > 0){
            insert lstSar;
            List<Announcement__c> annList = [Select Id, AnnouncementType__c, Status__c From Announcement__c Where Id = :foId LIMIT 1];
            if(annList.size() > 0 && !String.isempty(annList[0].AnnouncementType__c) && String.valueOf(annList[0].AnnouncementType__c).equalsIgnoreCase('sole source') && !String.isempty(annList[0].Status__c) && String.valueOf(annList[0].Status__c).equalsIgnoreCase('active') ){
                for(SoleSourceAwardRecipient__c sar : lstSar){
                    orgIdList.add(sar.Account__c);
                }
                List<User> applicantList = [Select id, ContactId from User Where IsActive = true AND IsApplicant__c = true AND AccountId IN :orgIdList];
                Set<Id> contId = new Set<Id>();
                for(User usr : applicantList){
                    contId.add(usr.ContactId);
                }
                foIdToContactIdMap.put(foId, contId);
                List<EmailTemplate> emailTemplate = [select Id From EmailTemplate Where DeveloperName = 'NotifyApplicantsOnSoleSourceFOPublish' Limit 1];
                if(emailTemplate.size() > 0){
                    GNT.AppUtils.sendEmailUsingTemplate(emailTemplate[0].Id, foIdToContactIdMap, false);
                }
            }
            
            resultMap.put('PageReference', '/apex/InviteOrgForSoleSourceAward?id='+foId);
        }
        return resultMap;
    }
    
    public string getKeyValueMap(){
        Map<String,String> keyValueMap = new Map<String,String>();
        String announcementid = ApexPages.currentPage().getParameters().get('id');
        keyValueMap.put('announcementId',announcementid); 
        return JSON.serialize(keyValueMap);
    }
    
    public string getListParams(){
        Map<String,List<String>> listParams = new Map<String,List<String>>();
        String announcementid = ApexPages.currentPage().getParameters().get('id');
        // Sole source award
        List<Id> orgIdList = new List<Id>();
        List<SoleSourceAwardRecipient__c> lst = [Select FundingOpportunity__c, Account__c 
            from SoleSourceAwardRecipient__c Where FundingOpportunity__c = :announcementId];
        for(SoleSourceAwardRecipient__c sar : lst){
            orgIdList.add(sar.Account__c);
        }
        system.debug('orgIdList ---'+orgIdList);
        listParams.put('externalOrgIds',orgIdList);

        return JSON.serialize(listParams);
    }
}