UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UserRegistration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization/User Registration</label>
        <referenceTo>UserRegistration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>External</fullName>
        <active>true</active>
        <description>This is an External Account such as Federal Grants</description>
        <label>External</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <formula>GNT__OrganizationId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization Account Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/UserRegistration__c.object
<CustomObject>
    <description>[Business] Need more Detailed info from Swati Singh</description>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>EINo__c</fullName>
        <inlineHelpText>An Employee Identification Number (EIN) is a nine-digit number provided by  Internal Revenue Service (IRS) which is often used by a business to open bank accounts, applying for business licenses, filing tax reports, filing electronic returns and taxes.</inlineHelpText>
        <label>Ob_Employee Identification Number (EIN)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <inlineHelpText>Enter valid email address.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryRepAddress2__c</fullName>
        <label>Primary Rep Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryRepCity__c</fullName>
        <label>Primary Rep City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryRepCountry__c</fullName>
        <defaultValue>&apos;USA&apos;</defaultValue>
        <description>Country name</description>
        <label>Primary Rep Country</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryRepEmail__c</fullName>
        <inlineHelpText>Enter Point of Contact’s E-mail address. For example xyz@abc.com</inlineHelpText>
        <label>Primary Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PrimaryRepPhone__c</fullName>
        <inlineHelpText>Point of Contact’s Official Phone number. Format is XXX-XXX-XXXX.</inlineHelpText>
        <label>Primary Rep Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PrimaryRepState__c</fullName>
        <label>Primary Rep State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>Virginia</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrimaryRepTitle__c</fullName>
        <label>Primary Rep Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryRepZipCode__c</fullName>
        <inlineHelpText>Format for zip code xxxxx-xxxx</inlineHelpText>
        <label>Primary Rep Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecondaryRepEmail__c</fullName>
        <inlineHelpText>Enter Point of Contact’s E-mail address. For example xyz@abc.com</inlineHelpText>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SecondaryRepFirstName__c</fullName>
        <label>Secondary Rep First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecondaryRepPrefix__c</fullName>
        <label>Secondary Rep Prefix</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mr.</fullName>
                </value>
                <value>
                    <fullName>Ms.</fullName>
                </value>
                <value>
                    <fullName>Mrs.</fullName>
                </value>
                <value>
                    <fullName>Dr.</fullName>
                </value>
                <value>
                    <fullName>Prof.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <inlineHelpText>The Username must be in email format but the email format does not need to be a valid email address. For example xyz@abc.com</inlineHelpText>
        <label>User Name</label>
        <type>Email</type>
    </fields>
    <label>External Registration</label>
    <nameField>
        <displayFormat>RG-{000000}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Registration</pluralLabel>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <label>Applicant</label>
    </recordTypes>
    <recordTypes>
        <fullName>Reviewer</fullName>
        <active>true</active>
        <label>Reviewer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestUserRegistrationHelper.cls
/**
 
    **********************************************************
    Audit History
    **********************************************************
    4/27/2014   swati singh    Created
 
    **********************************************************  
*/
@isTest
private with sharing class TestUserRegistrationHelper {


    @IsTest(OnInstall=false)
    public static void test_ctrl() {
      UserTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(true);
        accountTriggerHelper.SkipTrigger = true;
        System.runAs(u) {
        TestHelper.CreateCustomSettings(true);
        UserRegistrationTriggerHelper.skipAfterUpdate = true;
        UserRegistration__c uReg = new UserRegistration__c();
        uReg.PrimaryRepAddress2__c='abc';
        uReg.PrimaryRepCity__c='abc';
        uReg.PrimaryRepState__c='Virginia';
        uReg.PrimaryRepZipCode__c='22202-1234';
        uReg.PrimaryRepCountry__c='abc';
        uReg.PrimaryRepPhone__c='1234567890';
        uReg.Comments__c='approved';
        uReg.PrimaryRepTitle__c='abc';
        uReg.PrimaryRepEmail__c='abc@gmail.com';
        uReg.SecondaryRepPrefix__c='abc';
        uReg.SecondaryRepFirstName__c='abc';
        uReg.Organization__c ='TestORG';
        uReg.LastName__c = 'Betty';
        uReg.username__c = System.now().millisecond() + 'test@123test.com';
        uReg.EINo__c = Math.Random();
        uReg.Email__c = 'test15@test.com';
        uReg.SecondaryRepEmail__c ='test15@test.com';
        //uReg.RecordType.DeveloperName = 'Reviewer';
        uReg.Status__c = 'In Progress';
        uReg.RecordTypeId = Schema.SObjectType.UserRegistration__c.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();
        insert uReg;
       Schema.SObjectType.Account.getRecordTypeInfosByName().get('External').getRecordTypeId();
       User u1 = TestHelper.getAdminUser(true);
         /*GNT__PageLayoutConfig__c pagelayoutConfig= null;
         pagelayoutConfig = TestHelper.getPageLayoutConfig(true,'UserRegistration__c ');
         GNT.DynamicLayoutHolder layoutHolder = new GNT.DynamicLayoutHolder(pageLayoutConfig.id, uReg.Id,true);*/
            ApexPages.currentPage().getParameters().put('Id',uReg.Id);
        Test.startTest();
        UserRegistrationHelper ctrl = new UserRegistrationHelper();
            ctrl.whenClicked();
        
        Test.stopTest();

        //assert
        System.assertEquals(uReg.Id, uReg.Id);
        
        
        }
    }
    
   
     
    
  }