UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EINText__c</fullName>
        <label>EIN Text</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>This is an Internal Organization which purchases GovGrants</description>
        <label>Internal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Recipient</fullName>
        <active>true</active>
        <description>This is a Partner Account</description>
        <label>Recipient</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>GNT__OrganizationId__c</fullName>
        <description>Organization to which a user is tied to. It is applicable for both internal and external users</description>
        <label>Organization Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationAccountName__c</fullName>
        <inlineHelpText>To which organization the user belongs to?</inlineHelpText>
        <label>Organization Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/OrganizationViewCtrl.cls
/*
  <Purpose of this class>    
    *******************************************************************************************************************
    Audit History
    ********************************************************************************************************************
    2017-04-01  Shah Kadirmohideen  Code Reviewed
    **********************************************************************************************************************  
*/ 
public with sharing class OrganizationViewCtrl {

    public ID recordId {get;set;}
    public ID accountid {get;set;}
    public String type {get;set;}
    public String recordType {get;set;}
    public String ein {get;set;}
    public String templateName{get;set;} 
    public Document doc{get;set;}
    public ID docID{get;set;}
    
    public OrganizationViewCtrl(ApexPages.StandardController stdController) {
        recordId = ApexPages.CurrentPage().getParameters().get('id');
        if(recordId == null) {
            User loggedInUser = [Select AccountId,OrganizationAccountName__c,GNT__OrganizationId__c From User Where id = :UserInfo.getUserId()];
            recordId = loggedInUser.AccountId;
        }
        //Shah CRF: Duplicate SOQL statements on account object. These could be combined with the above user object SOQL
          List<Account> accnt = [select id,name,EINText__c from Account where id=:recordId limit 1];
          system.debug('debug here'+accnt);
          System.debug('recordId '+recordId);
        recordType = [SELECT RecordType.Name FROM Account WHERE Id=:recordId].RecordType.Name;
        ein = accnt[0].EINText__c;
        String appName = GNT.UserPreferenceHelper.getStringValue('ActiveAppName__c');
        doc=[Select id,developername from Document where developername = 'FederalAssurances' LIMIT 1];
        docID=doc.ID;
        if(recordType == 'Internal') {
            templateName = 'GranteeOrganizationInternal';
        } else if(recordType == 'Recipient') {
            templateName = 'GranteeOrganizationRecipient';
        } else {
            templateName = 'GranteeOrganizationExternal';    
        }
    }
    
    public string getKeyValueMap() {
        Map<String,String> keyValueMap = new Map<String,String>();
        System.debug(' >>>the Debug Log is <<<< '+recordId);
        keyValueMap.put('orgId', recordId);
        keyValueMap.put('ein', ein);
        keyValueMap.put('docID',docID);
        return JSON.serialize(keyValueMap);
    }
}