UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/SubmissionTracking__c.object
<CustomObject>
    <description>[Business] Tracks Application submission to Grants.gov</description>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <label>IST: Submission Tracking</label>
    <nameField>
        <displayFormat>TRK-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestsubmissionTrackingCtrl.cls
@isTest
private with sharing class TestsubmissionTrackingCtrl{
    static testMethod void testController() {
          Account acct = null;
          User u = TestHelper.getAdminUser(true);
          
          System.runAs(u){
            GrantTriggerHelper.skipTrigger = true;
            
            SubmissionTracking__c subTrack = new SubmissionTracking__c(Comments__c='Test Case');
            insert subTrack;
           
            Test.startTest();
            ApexPages.StandardController sc = new ApexPages.standardController(subTrack);
            ApexPages.currentPage().getParameters().put('id',subTrack.id);
            SubmissionTrackingCtrl ctrl = new SubmissionTrackingCtrl(sc);
            ctrl.deleteURL = new PageReference('myPage.TestPage');
            ctrl.pageTemplateName = 'Test Template';
            ctrl.getKeyValueMap();
            Test.stopTest();
        
     }
        
    }
}