UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <formula>Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>AttachmentsRequired__c</fullName>
        <label>Required Attachments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GranteeMatch__c</fullName>
        <description>Percentage of Sub Recipient  Match Required</description>
        <inlineHelpText>Percentage of Sub Recipient  Match Required</inlineHelpText>
        <label>Sub Recipient Match %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MatchRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The checkbox is checked if match is required for funding.</description>
        <label>Match Required?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <formula>Organization__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PointofContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Key POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Announcement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A unique id to relate the announcement to the program.</description>
        <label>Program ID</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>- In Progress - The information within the annoucement is incomplete. Such records shall not be avaiable for other users to view or edit.
- Review In Progress - Annoucements that are currently in the process of undergoing review shall have this status. Such records shall not be avaiable for other users to view or edit.
- Inactive - Approved annoucements whose Posting Date is in the future shall have this status. Such annoucements shall not be made available to recipient users.
- Active - Approved annoucements whose Posting Date is equal to the current date or is in the past and the Closing Date is in the future shall have this status. System shall make such annoucements available to recipients.
- Expired - Approved annoucements whose closing date is the current date or is in the past shall have this status. When an annoucement status changes from Active to Expired, it should no longer be made available to the recipient users.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Converted to Application</fullName>
                </value>
                <value>
                    <fullName>Converted to Pre-Application</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Approved</fullName>
                </value>
                <value>
                    <fullName>RFA Published</fullName>
                </value>
                <value>
                    <fullName>RFA Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <description>Announcement type is based on Application that user is logged in</description>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AnnouncementFundingAccount__c.object
<CustomObject>
    <description>[Business]  Funding Accounts associated with the opportunity</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>Announcement</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Opportunity Funding Account</label>
    <nameField>
        <displayFormat>AFA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Opportunity Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The internal approver for the application</description>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applicationsap2u</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IndirectCostPicklist__c</fullName>
        <label>Indirect Cost Picklist</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrimaryApplicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is to store the primary Applicant user details. This is used to control Submit Application Button</description>
        <label>Primary Applicant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applicationstpqm</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Review Initiated</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Submitted For Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Sent for Review</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision Completed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Rejection Initiated</fullName>
                </value>
                <value>
                    <fullName>Internally Reviewed</fullName>
                </value>
                <value>
                    <fullName>Converted to Award</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Converted to Grant</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Revision Initiated</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Approved Internally</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalCashMatch__c</fullName>
        <label>Total Cash Match</label>
        <summarizedField>ApplicationBudgetCategory2__c.CashMatch__c</summarizedField>
        <summaryForeignKey>ApplicationBudgetCategory2__c.Application__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalFederalMatch__c</fullName>
        <label>Total Federal Match</label>
        <summarizedField>ApplicationBudgetCategory2__c.Federal__c</summarizedField>
        <summaryForeignKey>ApplicationBudgetCategory2__c.Application__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalGrantCost__c</fullName>
        <label>Total Grant Cost</label>
        <summarizedField>ApplicationBudgetCategory2__c.TotalGrantCost__c</summarizedField>
        <summaryForeignKey>ApplicationBudgetCategory2__c.Application__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalInKindMatch__c</fullName>
        <label>Total In-Kind Match</label>
        <summarizedField>ApplicationBudgetCategory2__c.InKind__c</summarizedField>
        <summaryForeignKey>ApplicationBudgetCategory2__c.Application__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <description>Application Created by the user in State as Grantor App</description>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>AttachmentsRequired__c</fullName>
        <inlineHelpText>Please enter list of required attachments separated by semicolons; include &apos;optional&apos; with the file type if it is not mandatory.</inlineHelpText>
        <label>AttachmentsRequired</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <formula>Account__r.Name</formula>
        <label>Organization Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ApplicationApproval.cls
global class ApplicationApproval extends GNT.ApprovalDecisionActionHandler {
    Map<String,Object> resultMap = new Map<String,Object>();
    PageReference pageRef = null;
    global override String execute(){
            system.debug('Connecting...!');
            if(selectedAction == 'Approve'){
            
            Id appId = selectedRecordId;
            system.debug('id is' +appId);
            Application__c app = [Select Id, Name,Approver__c, IndirectCostPicklist__c,
            Announcement__r.OrganizationName__c,Announcement__r.Program__r.AttachmentsRequired__c,
            TotalFederalMatch__c, Announcement__r.GranteeMatch__c,Announcement__r.MatchRequired__c,
            TotalCashMatch__c,TotalInKindMatch__c,TotalGrantCost__c ,PrimaryApplicant__r.Id,Status__c,
            Announcement__r.DaysLeft__c,Announcement__r.Name ,ExternalOrganization__c,
            ExternalOrganization__r.ApplicantType__c, Announcement__c,FormsValidated__c,
            Announcement__r.MaxApplicationsAllowed__c,Announcement__r.ApplicationsReviewStatus__c,
            NumberOfReviews__c,InitialRequestedAmount__c,RequestedAmount__c,AwardCeiling__c, AwardFloor__c,
             ProgramBudgetTypeUSBE__c, GrantorOrganizationName__c  from Application__c where id = :appId Limit 1];

             System.debug('Application ID'+app.id);

             app.Status__c = 'Submitted to Grantor';
              app.SubmittedOn__c=System.Now();
              app.InitialRequestedAmount__c=app.RequestedAmount__c;
              app.SubmittedBy__c=UserInfo.getUserId();
              update app;
              List<Task> taskList = [Select Id, Status, WhatId from Task where 
                                       WhatId = :app.Id AND OwnerId=:app.PrimaryApplicant__r.Id AND Status='In Progress'];
               if(taskList != null && taskList.size()>0){

                  for(Task task: taskList){
                     task.Status='Completed';
                  }                   
                  update taskList;
               }
               /*
              if(app.Announcement__r.ApplicationsReviewStatus__c!='Not Started' && app.Announcement__r.ApplicationsReviewStatus__c!='Ready for Review'){
                SystemContextMethodsHelper helper = new SystemContextMethodsHelper();
                helper.insertSingleApplicationToReview(app);
              }
              */
              ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Approval Process Action class works.')); 
              

                return ('Submitting to Grantor.');
            }
            return ('Not submitted to Grantor.');
          }
}