UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <formula>Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>This is an Internal Organization which purchases GovGrants</description>
        <label>Internal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>GranteeMatch__c</fullName>
        <description>Percentage of Sub Recipient  Match Required</description>
        <inlineHelpText>Percentage of Sub Recipient  Match Required</inlineHelpText>
        <label>Sub Recipient Match %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MatchRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The checkbox is checked if match is required for funding.</description>
        <label>Match Required?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <formula>Organization__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PointofContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Key POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Announcement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>- In Progress - The information within the annoucement is incomplete. Such records shall not be avaiable for other users to view or edit.
- Review In Progress - Annoucements that are currently in the process of undergoing review shall have this status. Such records shall not be avaiable for other users to view or edit.
- Inactive - Approved annoucements whose Posting Date is in the future shall have this status. Such annoucements shall not be made available to recipient users.
- Active - Approved annoucements whose Posting Date is equal to the current date or is in the past and the Closing Date is in the future shall have this status. System shall make such annoucements available to recipients.
- Expired - Approved annoucements whose closing date is the current date or is in the past shall have this status. When an annoucement status changes from Active to Expired, it should no longer be made available to the recipient users.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Converted to Application</fullName>
                </value>
                <value>
                    <fullName>Converted to Pre-Application</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Approved</fullName>
                </value>
                <value>
                    <fullName>RFA Published</fullName>
                </value>
                <value>
                    <fullName>RFA Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Grantee</fullName>
                </value>
                <value>
                    <fullName>Grantor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AnnouncementFundingAccount__c.object
<CustomObject>
    <description>[Business]  Funding Accounts associated with the opportunity</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>Announcement</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Opportunity Funding Account</label>
    <nameField>
        <displayFormat>AFA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Opportunity Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChangeRequestStatus__c</fullName>
        <label>Change Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Revision Request Assigned</fullName>
                </value>
                <value>
                    <fullName>Revision Request Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalOrganization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Orgnanization which owns the Application This field is also used on the Forms as well</description>
        <inlineHelpText>Which organization owns the application?</inlineHelpText>
        <label>Applicant Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Review Initiated</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Submitted For Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Sent for Review</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision Completed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Rejection Initiated</fullName>
                </value>
                <value>
                    <fullName>Internally Reviewed</fullName>
                </value>
                <value>
                    <fullName>Converted to Award</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Converted to Grant</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Revision Initiated</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Approved Internally</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubmittedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitted By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ChangeRequest__c.object
<CustomObject>
    <description>[Business]  Currently used to track pre-award negotiation requests for application only. In the future this can be enhanced for other objects like award or something else.</description>
    <fields>
        <fullName>ApplicantComments__c</fullName>
        <description>Comments by the Applicant</description>
        <label>Applicant Comments</label>
        <length>130000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Negotiation Requests</relationshipLabel>
        <relationshipName>Change_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Change request comment are captured here.</description>
        <inlineHelpText>Change request comment are captured here.</inlineHelpText>
        <label>Description</label>
        <length>131070</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExternalOrganization__c</fullName>
        <formula>Application__r.ExternalOrganization__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>External Organization</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                    <default>true</default>
                    <label>Not Initiated</label>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Change</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Negotiation Request</label>
    <nameField>
        <displayFormat>CR-{000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Negotiation Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FormBudgetInformation__c.object
<CustomObject>
    <description>[Business] This object is used for Budget Information forms.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Overflow Budget Information</label>
    <nameField>
        <displayFormat>BI-{00000}</displayFormat>
        <label>Budget Information</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Overflow Budget Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/SubmissionRequestCloseTask.cls
global class SubmissionRequestCloseTask extends GNT.DynamicLayoutActionRedirect {
    private static Id recordId;
    private static Sobject sobj;
    global override Pagereference whenClicked() {
        String namespace = AppUtils.getNamespacePrefix();
        Boolean isError = false;
        Decimal match;
        Id appId;
        Id userId;
        ChangeRequest__c oldReq;
        List<Application__c> appList;
        Application__c app;
        Task task;
        recordId = layoutHolder.getPrimarySObject().Id;
        sobj = layoutHolder.getPrimarySObject();
        Savepoint sp = Database.setSavepoint();
        ChangeRequest__c changeReq = (ChangeRequest__c)layoutHolder.recordMap.get(namespace + 'ChangeRequest__c');
        oldReq = [Select Id, Status__c, Name, Type__c, DueDate__c, Comments__c, ApplicantComments__c,
                  Application__r.Id, Application__r.SubmittedBy__c
                  from ChangeRequest__c where id = :recordId Limit 1];
        System.debug('oldReq '+oldReq);
        try {
            if (oldReq.Status__c == 'In Progress' || oldReq.Status__c == 'Initiated') {
                appId = oldReq.Application__r.Id;
                appList = [Select ChangeRequestStatus__c, Announcement__r.MatchRequired__c, Announcement__r.GranteeMatch__c, Announcement__r.OrganizationName__c, ExternalOrganization__r.ApplicantType__c, FinalGrantAmountNegotiated__c, TotalFederalMatch__c, TotalCashMatch__c, TotalInKindMatch__c, TotalGrantCost__c, FormsValidated__c From Application__c Where id = :appId Limit 1];
                System.debug('applist '+applist);
                app = appList[0];
                if (app.TotalGrantCost__c == 0 && app.Announcement__r.OrganizationName__c == 'UOVC') {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please input the application budget in the Budget Tab '));
                    isError = true;
                } else if (app.TotalGrantCost__c != 0) {
                    match = (app.TotalCashMatch__c + app.TotalInKindMatch__c) / app.TotalGrantCost__c * 100;
                }
                if (match != null && app.Announcement__r.MatchRequired__c == true && match.setScale(2) < app.Announcement__r.GranteeMatch__c && app.ExternalOrganization__r.ApplicantType__c != 'Non Profit Victim Services' && app.Announcement__r.OrganizationName__c == 'UOVC') {
                    //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please make sure that the value of ((Total Cash Match+Total In-Kind Match)*100/Grant including indirect cost) is greater than ' + app.Announcement__r.GranteeMatch__c + '%. The present cash match percentage is ' + match.setScale(2) + '%.'));
                    //isError = true;
                    throw new MyException(GNT.ErrorMessageHelper.fetchMessage('Please make sure that the value of ((Total Cash Match+Total In-Kind Match)*100/Grant including indirect cost) is greater than ' + app.Announcement__r.GranteeMatch__c + '%. The present cash match percentage is '));
                }

                //    if ( app.Announcement__r.OrganizationName__c.equalsIgnoreCase('UOVC')){
                //    if(app.TotalFederalMatch__c!=app.FinalGrantAmountNegotiated__c){
                //        throw new MyException(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-61202'));
                //    }
                //}

                //Update the field. TotalFederalmatch is for UOVC.
                //Budgets_Requested__c
                //if ( app.Announcement__r.OrganizationName__c.equalsIgnoreCase('USBE')){
                //    //if(app.TotalFederalMatch__c!=app.FinalGrantAmountNegotiated__c){
                //    //    throw new MyException(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-61202'));
                //    //}
                //}
                //if ( app.Announcement__r.OrganizationName__c.equalsIgnoreCase('UOVC')) {
                    if (oldReq.ApplicantComments__c == null) {
                        throw new MyException(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-61205'));
                    }
                //}
                if (!app.FormsValidated__c) {
                    // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Forms needs to be validated before the application can be submitted.'));
                    throw new ApplicantCommentsMissingException(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-61201'));
                }
                
                if (app.Announcement__r.OrganizationName__c == 'UOVC'){
	                app.ChangeRequestStatus__c = 'Revision Request Completed';
	                update app;
	                String[] toAddresses = new String[] {};
	                List<User> userList = [SELECT Id, Email FROM User WHERE IsActive = true AND Id = : oldReq.Application__r.SubmittedBy__c LIMIT 1 ];
	                toAddresses.add(userList[0].Email);
	                Map<Id, String[]> recIdToAddressMap = new Map<Id, String[]> ();
	                recIdToAddressMap.put(changeReq.Id, toAddresses);
	                List<EmailTemplate> emailTemplate = [Select id From EmailTemplate Where DeveloperName = 'PreAwardRequestEvaluationCompleted' Limit 1];
	                Contact cont = [select id, Email from Contact where email <> null limit 1];
	                //AppUtils.sendEmailUsingTemplate(emailTemplate[0].Id, recIdToAddressMap, cont.Id, false);//
                	oldReq.Status__c = 'Submitted';
	                update oldReq;
	                updateTasks(UserInfo.getUserId(), oldReq.Id);
                } else{
                	GNT.TaskCreationHandler.createApprovalProcessTasks(oldReq.Id, 'USBE Approval', oldReq.Name, null, System.TODAY() + 7, 'This negotiation request has been submitted for internal approval',  true);
                }
            }
        } catch (Exception e) {
            Database.rollback(sp);
            System.debug('Error Occured -- ' + e);
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage());
            //ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-34727'));
            ApexPages.addMessage(myMsg);
            return null;
            //return new PageReference('/apex/'+namespace+'SubmissionRequestEdit?id='+appId);
        }

        return new PageReference('/apex/' + namespace + 'ApplicationView?id=' + appId);
    }


    public class MyException extends Exception {}
    public class ApplicantCommentsMissingException extends Exception {}
    /* Pranjali: This method is not used in this class and hence commenting it */

    private void updateTasks(String userId, String crId) {
        recordId = layoutHolder.getPrimarySObject().Id;
        system.debug('record Id is ' + recordId);
        ChangeRequest__c changeRequest = [Select Id, Status__c, CreatedById, ApplicationTitle__c, Application__c, Name, Type__c, DueDate__c, Comments__c,
                                          Application__r.Id, Application__r.SubmittedBy__c, Application__r.OwnerId
                                          from ChangeRequest__c where id = :recordId Limit 1];
        system.debug('tej debug' + changeRequest.createdbyId + ' Id' + changeRequest.Id + 'Name' + changeRequest.Name + 'Title' + changeRequest.ApplicationTitle__c);
        List<Task> taskList = [Select Id, Status, WhatId from Task where
                               OwnerId = :userId AND WhatId = :crId];
        for (Task t : taskList) {
            t.Status = 'Completed';
        }
        update taskList;
        GNT.TaskCreationHandler.createTasks(changeRequest.Application__r.OwnerId, changeRequest.Id, 'RevisionRequestSubmission', changeRequest.Name, null, false, System.TODAY() + 7, null, changeRequest.ApplicationTitle__c, true);

    }
}