UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DisplayOrder__c</fullName>
        <label>DisplayOrder</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LEA_Id__c</fullName>
        <label>LEA_Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NumberofAwards__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Grants</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>AwardAmount__c</fullName>
        <label>Award Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LEAComment__c</fullName>
        <label>LEA Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProgramCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Code</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramComment__c</fullName>
        <label>Program Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>USBEPathway__c</fullName>
        <label>USBEPathway</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AwardFINETCode__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award FINET Codes</relationshipLabel>
        <relationshipName>Award_FINET_Codes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DeltaAmount__c</fullName>
        <label>Delta Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DisplayOrder__c</fullName>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MSPUniqueKeyFormula__c</fullName>
        <formula>Award__r.Grant__r.Program__c + Award__r.Grant__r.InternalOrganization__c + ProgramCode__r.PROG_CD__c + ObjectCode__r.OBJ_CD__c + Award__r.Grant__r.FiscalYear__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MSPUniqueKeyFormula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Object Code</label>
        <referenceTo>r_obj__c</referenceTo>
        <relationshipLabel>Award FINET Codes</relationshipLabel>
        <relationshipName>Award_FINET_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramCode__c</fullName>
        <label>Program Code</label>
        <referenceTo>r_prog__c</referenceTo>
        <relationshipLabel>Award FINET Codes</relationshipLabel>
        <relationshipName>Award_FINET_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Award FINET Code</label>
    <nameField>
        <label>Award FINET Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award FINET Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FiscalYear__c.object
<CustomObject>
    <description>[Business] Stores the Fiscal Year information (Need to revisit)</description>
    <fields>
        <fullName>InternalOrganization__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Internal Organization?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>State</fullName>
                    <default>true</default>
                    <label>State</label>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MST: Fiscal Year</label>
    <nameField>
        <label>Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>InternalOrganization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Grants (Internal Organization)</relationshipLabel>
        <relationshipName>Grants1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LEAComment__c</fullName>
        <label>LEA Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MSPUniqueKeyFormula__c</fullName>
        <formula>Program__c + InternalOrganization__c + ProgramCode__c + ObjectCode__c + FiscalYear__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MSPUniqueKeyFormula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberofAwards__c</fullName>
        <label>Number of Awards</label>
        <summaryForeignKey>Award__c.Grant__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ObjectCode__c</fullName>
        <label>Object Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramCode__c</fullName>
        <label>Program Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramComment__c</fullName>
        <label>Program Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProgramCode</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>USBEPathway__c</fullName>
        <label>USBEPathway</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/MSPFinancialStage__c.object
<CustomObject>
    <fields>
        <fullName>AwardAmountFormula__c</fullName>
        <formula>VALUE(AwardAmount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Award Amount Formula</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AwardAmount__c</fullName>
        <label>Award Amount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeltaAmount__c</fullName>
        <label>Delta Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DisplayOrder__c</fullName>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FileBatch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>File Batch</label>
        <referenceTo>FileBatch__c</referenceTo>
        <relationshipLabel>MSP Financial Stages</relationshipLabel>
        <relationshipName>MSP_Financial_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LEAComment__c</fullName>
        <label>LEA Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ObjectCode__c</fullName>
        <label>Object Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramCode__c</fullName>
        <label>Program Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramComment__c</fullName>
        <label>Program Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>MSP Financial Stages</relationshipLabel>
        <relationshipName>MSP_Financial_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubRecipient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubRecipient</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MSP Financial Stages</relationshipLabel>
        <relationshipName>MSP_Financial_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UniqueKeyFormula__c</fullName>
        <formula>Program__c + SubRecipient__c + ProgramCode__c + ObjectCode__c + TEXT(FileBatch__r.FiscalYear__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UniqueKeyFormula</label>
        <type>Text</type>
    </fields>
    <label>MSP Financial Stage</label>
    <nameField>
        <label>MSP Financial Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MSP Financial Stages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>DisplayOrder__c</fullName>
        <label>DisplayOrder</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>InternalOrganization__c</fullName>
        <description>Created to show up on the portal</description>
        <label>Internal Organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramCode__c</fullName>
        <formula>ProgramName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramKey__c</fullName>
        <description>This is the unique key that can be mapped from the excel to Gov Grants.</description>
        <label>Program Key</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/r_prog__c.object
<CustomObject>
    <description>This is the object for the FINET program creation</description>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>r_prog</label>
    <nameField>
        <label>r_prog</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>r_progs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <formula>GNT__OrganizationId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization Account Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/MSPGrantCreateAndAmendValidateBatch.cls
global class MSPGrantCreateAndAmendValidateBatch implements Database.Batchable<sObject>, Database.Stateful {

    public String query;
    public List<String> errors;
    public FileBatch__c fb;
    public Set<String> amendGrantIdSet;
    public List<String> finetCodeSet;
    public Integer index;

    global MSPGrantCreateAndAmendValidateBatch(FileBatch__c fb, List<String> finetCodeSet, Integer index) {
        this.fb = fb;
        this.finetCodeSet = finetCodeSet;
        this.index = index;
        errors = new List<String>();
        amendGrantIdSet = new Set<String>();
    }

    global MSPGrantCreateAndAmendValidateBatch(FileBatch__c fb, List<String> finetCodeSet, Integer index, List<String> errors, Set<String> amendGrantIdSet) {
        this.fb = fb;
        this.finetCodeSet = finetCodeSet;
        this.index = index;
        this.errors = errors;
        this.amendGrantIdSet = amendGrantIdSet;
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        try {
            query = 'SELECT Id, SubRecipient__r.LEA_Id__c, Program__r.ProgramKey__c, AwardAmount__c, DisplayOrder__c, ObjectCode__c, Program__c, ProgramCode__c, SubRecipient__c, UniqueKeyFormula__c, AwardAmountFormula__c, ProgramComment__c, LEAComment__c, DeltaAmount__c FROM MSPFinancialStage__c WHERE FileBatch__c = \'' + fb.Id + '\' AND ProgramCode__c = \'' + finetCodeSet[index] + '\' ORDER BY SubRecipient__r.LEA_Id__c';
            return Database.getQueryLocator(query);
        } catch (Exception e) {
            errors.add(e.getMessage());
            return null;
        }
    }
    
    global void execute(Database.BatchableContext BC, List<MSPFinancialStage__c> scope) {
        Savepoint sp = Database.setSavepoint();
        if (scope == null) {
            return;
        }

        Map<String, AwardFINETCode__c> afcMap = new Map<String, AwardFINETCode__c>();
        try {
            List<Award__c> awardList = [SELECT Id, Grant__r.InternalOrganization__c, Grant__r.Program__c, Grant__c, Grant__r.NumberofAwards__c, (SELECT Id, MSPUniqueKeyFormula__c, Amount__c, Award__r.Grant__c, Award__r.Grant__r.NumberofAwards__c FROM Award_FINET_Codes__r) FROM Award__c WHERE Grant__r.USBEPathway__c = :fb.RecordType.Name AND Grant__r.FiscalYear__c = :fb.FiscalYear__c AND Status__c = 'Activated'];
            Map<String, Award__c> awardMap = new Map<String, Award__c>();
            for (Award__c award : awardList) {
                awardMap.put(award.Grant__r.InternalOrganization__c + '_' + award.Grant__r.Program__c, award);
                for (AwardFINETCode__c afc : award.Award_FINET_Codes__r) {
                    afcMap.put(afc.MSPUniqueKeyFormula__c, afc);
                }
            }

            Map<String, List<MSPFinancialStage__c>> mfmMap = new Map<String, List<MSPFinancialStage__c>>();
            for (MSPFinancialStage__c mfm : scope) {
                if (mfmMap.get(mfm.SubRecipient__c + '_' + mfm.Program__c) == null) {
                    List<MSPFinancialStage__c> tempList = new List<MSPFinancialStage__c>();
                    mfmMap.put(mfm.SubRecipient__c + '_' + mfm.Program__c, tempList);
                }
                mfmMap.get(mfm.SubRecipient__c + '_' + mfm.Program__c).add(mfm);
            }

            User currentUser = [SELECT Id, Organization__c FROM User WHERE Id = :UserInfo.getUserId()];
            List<String> newKeyList = new List<String>();
            List<Award__c> newMSPAwards = new List<Award__c>();
            List<Grant__c> newMSPGrants = new List<Grant__c>();
            for (String key : mfmMap.keySet()) {
                if (!awardMap.containsKey(key)) {
                    newKeyList.add(key);
                } else {
                    List<AwardFINETCode__c> oldAfcList = awardMap.get(key).Award_FINET_Codes__r;
                    Map<String, AwardFINETCode__c> oldAfcKeyMap = new Map<String, AwardFINETCode__c>();
                    for (AwardFINETCode__c afc : oldAfcList) {
                        oldAfcKeyMap.put(afc.MSPUniqueKeyFormula__c, afc);
                    }

                    for (MSPFinancialStage__c mfm : mfmMap.get(key)) {
                        if ((!oldAfcKeyMap.containsKey(mfm.UniqueKeyFormula__c) || oldAfcKeyMap.get(mfm.UniqueKeyFormula__c).Amount__c != mfm.AwardAmountFormula__c) && !amendGrantIdSet.contains(awardMap.get(key).Grant__c)) {
                            amendGrantIdSet.add(awardMap.get(key).Grant__c);
                            Award__c temp = new Award__c(
                                Grant__c = awardMap.get(key).Grant__c,
                                VersionNumber__c = awardMap.get(key).Grant__r.NumberofAwards__c + 1,
                                USBEPathway__c = fb.RecordType.Name,
                                Status__c = 'Activated'
                            );
                            newMSPAwards.add(temp);
                        }
                    }
                }
            }

            Map<Id, Program__c> pMap = new Map<Id, Program__c>([SELECT Id, ProgramKey__c FROM Program__c]);
            Map<Id, Account> aMap = new Map<Id, Account>([SELECT Id, LEA_Id__c FROM Account]);
            for (String newKey : newKeyList) {
                String[] str = newKey.split('_');
                Grant__c temp = new Grant__c(
                    Name = fb.RecordType.Name + ' GT-' + pMap.get(str[1]).ProgramKey__c + '-' + aMap.get(str[0]).LEA_Id__c + '-' + fb.FiscalYear__c,
                    FiscalYear__c = fb.FiscalYear__c,
                    InternalOrganization__c = str[0],
                    Program__c = str[1],
                    ExternalOrganization__c = currentUser.Organization__c,
                    USBEPathway__c = fb.RecordType.Name,
                    Status__c = 'Active'
                );
                newMSPGrants.add(temp);
            }

            insert newMSPGrants;
            for (Grant__c newGrant : newMSPGrants) {
                amendGrantIdSet.add(newGrant.Id);
            }

            List<Grant__c> mgs = [SELECT Id, Name, NumberofAwards__c, USBEPathway__c FROM Grant__c WHERE Id IN :newMSPGrants];
            for (Grant__c mg : mgs) {
                Award__c temp = new Award__c(
                    Name = fb.RecordType.Name + ' AD-' + mg.Name.substring(6) + '-' + String.valueOf(mg.NumberofAwards__c + 1),
                    Grant__c = mg.Id,
                    VersionNumber__c = mg.NumberofAwards__c + 1,
                    USBEPathway__c = mg.USBEPathway__c,
                    Status__c = 'Activated'
                );
                newMSPAwards.add(temp);
            }

            insert newMSPAwards;
            List<Id> programIdList = new List<Id>();
            List<Id> subIdList = new List<Id>();
            List<Award__c> newAwardList = [SELECT Id, Grant__r.InternalOrganization__c, Grant__r.Program__c, ObligatedAwardAmount__c FROM Award__c WHERE Id IN :newMSPAwards];
            for (Award__c a : newAwardList) {
                programIdList.add(a.Grant__r.Program__c);
                subIdList.add(a.Grant__r.InternalOrganization__c);
            }

            List<MSPFinancialStage__c> amendMfmList = [SELECT Id, ProgramCode__c, ObjectCode__c, AwardAmountFormula__c, SubRecipient__c, Program__c, DeltaAmount__c, UniqueKeyFormula__c FROM MSPFinancialStage__c WHERE Program__c IN : programIdList AND SubRecipient__c IN : subIdList AND FileBatch__c = :fb.Id];
            List<String> programCodeList = new List<String>();
            List<String> objectCodeList = new List<String>();
            Map<String, List<MSPFinancialStage__c>> amendMfmMap = new Map<String, List<MSPFinancialStage__c>>();
            for (MSPFinancialStage__c mfm : amendMfmList) {
                if (amendMfmMap.get(mfm.SubRecipient__c + '_' + mfm.Program__c) == null) {
                    List<MSPFinancialStage__c> tempList = new List<MSPFinancialStage__c>();
                    amendMfmMap.put(mfm.SubRecipient__c + '_' + mfm.Program__c, tempList);
                }
                amendMfmMap.get(mfm.SubRecipient__c + '_' + mfm.Program__c).add(mfm);
                programCodeList.add(mfm.ProgramCode__c);
                objectCodeList.add(mfm.ObjectCode__c);
            }

            Map<String, Award__c> amendAwardMap = new Map<String, Award__c>();
            for (Award__c award : newAwardList) {
                amendAwardMap.put(award.Grant__r.InternalOrganization__c + '_' + award.Grant__r.Program__c, award);
            }

            List<r_prog__c> programCode = [SELECT Id, PROG_CD__c FROM r_prog__c WHERE PROG_CD__c IN :programCodeList];
            List<r_obj__c> objectCode = [SELECT Id, OBJ_CD__c FROM r_obj__c WHERE OBJ_CD__c IN :objectCodeList];
            Map<String, Id> programCodeMap = new Map<String, Id>();
            Map<String, Id> objectCodeMap = new Map<String, Id>();

            for (r_prog__c pc : programCode) {
                programCodeMap.put(pc.PROG_CD__c, pc.Id);
            }

            for (r_obj__c oc : objectCode) {
                objectCodeMap.put(oc.OBJ_CD__c, oc.Id);
            }

            Map<String, Double> amountMap = new Map<String, Double>();
            List<AwardFINETCode__c> newAfcList = new List<AwardFINETCode__c>();
            for (String key : amendMfmMap.keySet()) {
                if (amendAwardMap.get(key) == null) {
                    continue;
                }
                Double total = 0.00;
                for (MSPFinancialStage__c mfm : amendMfmMap.get(key)) {
                    AwardFINETCode__c temp = new AwardFINETCode__c(
                        ProgramCode__c = programCodeMap.get(mfm.ProgramCode__c),
                        ObjectCode__c = objectCodeMap.get(mfm.ObjectCode__c),
                        Amount__c = mfm.AwardAmountFormula__c,
                        Award__c = amendAwardMap.get(key).Id,
                        DeltaAmount__c = afcMap.get(mfm.UniqueKeyFormula__c) == null ? mfm.AwardAmountFormula__c : mfm.AwardAmountFormula__c - afcMap.get(mfm.UniqueKeyFormula__c).Amount__c,
                        OldAmount__c = afcMap.get(mfm.UniqueKeyFormula__c) == null ? 0 : afcMap.get(mfm.UniqueKeyFormula__c).Amount__c
                    );
                    newAfcList.add(temp);
                    total = total + temp.Amount__c;
                }
                amountMap.put(key, total);
            }

            insert newAfcList;
            for (String key : amountMap.keySet()) {
                amendAwardMap.get(key).ObligatedAwardAmount__c = amountMap.get(key);
            }

            update amendAwardMap.values();

        } catch (Exception e) {
            errors.add(e.getMessage() + ':::' + e.getStackTraceString() + ':::' + e.getLineNumber() + ':::' + e.getCause());
        }
        Database.rollback(sp);
        for (MSPFinancialStage__c mfs : scope) {
            mfs.DeltaAmount__c = afcMap.get(mfs.UniqueKeyFormula__c) == null ? mfs.AwardAmountFormula__c : mfs.AwardAmountFormula__c - afcMap.get(mfs.UniqueKeyFormula__c).Amount__c;
            mfs.OldAwardedAmount__c = mfs.AwardAmountFormula__c - mfs.DeltaAmount__c;
        }
        update scope;
    }

    global void finish(Database.BatchableContext BC) {
        if(index == finetCodeSet.size() - 1){
            if (errors.size() == 0) {
                Database.executeBatch(new GCAMProgramPhaseCreationBatch(fb, finetCodeSet), 1);
                //Database.executeBatch(new MSPGrantAndAwardCreateAndAmendBatch(fb, finetCodeSet, 0), 200);
            } else {
                for (String err : errors) {
                    fb.ErrorLog__c =  fb.ErrorLog__c + ';' + err;
                }

                fb.Status__c = 'Error';
                update fb;
            }
        }else{
            index++;
            Database.executeBatch(new MSPGrantCreateAndAmendValidateBatch(fb, finetCodeSet, index, errors, amendGrantIdSet), 200);
        }
    }
}