UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProgramCode</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed/Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RiskAssessment__c.object
<CustomObject>
    <description>[Business] This will be part of Grant Making Module.</description>
    <fields>
        <fullName>AssessmentDate__c</fullName>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Risk Assessment</relationshipLabel>
        <relationshipName>Risk_Assessment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Risk Assessment</relationshipLabel>
        <relationshipName>Risk_Assessment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Risk Assessment</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk Assessment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RiskItem__c.object
<CustomObject>
    <description>[Business] Individual Risk Item based on which the Risk Assessment is done</description>
    <fields>
        <fullName>DueDate__c</fullName>
        <inlineHelpText>Due Date for Closing Risk Item</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipName>Risks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PlanofAction__c</fullName>
        <label>Plan of Action</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>RiskItems</relationshipLabel>
        <relationshipName>RiskItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RiskAssessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk Assessment</label>
        <referenceTo>RiskAssessment__c</referenceTo>
        <relationshipLabel>RiskItems</relationshipLabel>
        <relationshipName>Risks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RiskIdentifiedDate__c</fullName>
        <description>Risk Identified Date</description>
        <label>Risk Identified Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Risk Item</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RiskItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestRiskItemEditCtrl.cls
@isTest(Seealldata=false)
private with sharing class TestRiskItemEditCtrl {
    
     static testMethod void testRiskItemEdit() {
        RiskItem__c ri = null;
        RiskAssessment__c ra = null;
        Program__c program = null;
        UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true); 
             
        System.runAs(u){
            GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
            GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c','StateAsGrantor');
            AppUtils.skipAccountTrigger=true;
            ProgramTriggerHelper.skipTrigger=true;
            Account acc = new Account();
            acc.Name = 'test'+system.currentTimeMillis();
            acc.status__c = 'Active';   
            insert acc;  
           
            program = TestHelper.getProgram(acc.id,false);
            program.status__c = 'Active';
            insert program;  
            
            ra = new RiskAssessment__c();
            ra.Program__c=program.Id;
            ra.AssessmentDate__c=System.today();
            insert ra;
            
            ri = new RiskItem__c();
            ri.RiskIdentifiedDate__c=System.today();
            ri.DueDate__c=System.today()+7;
            ri.PlanofAction__c='Sample Text';
            insert ri;
            
        }        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.standardController(ri);
        ApexPages.currentPage().getParameters().put('id',ri.Id);
        ApexPages.currentPage().getParameters().put('riskAssessmentID',ra.Id);
        ApexPages.currentPage().getParameters().put('programId',program.Id);
        RiskItemEditCtrl ann = new RiskItemEditCtrl(sc);
        ann.getKeyValueMap();        
        Test.stopTest();
    }
    
    static testMethod void testRiskItemEdit2() {
        RiskItem__c ri = null;
        Grant__c grant = null;
        UserTriggerHelper.skipTrigger = true;
        GrantTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(true); 
          grant = TestHelper.getGrant(true);
           
             
        System.runAs(u){
          //  TestHelper.getServiceArea(true);
            GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
            GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c','StateAsGrantor');
            AppUtils.skipAccountTrigger=true;
            ri = new RiskItem__c();
            ri.RiskIdentifiedDate__c=System.today();
            ri.DueDate__c=System.today()+7;
            ri.PlanofAction__c='Sample Text';
            insert ri;
            
        }        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.standardController(ri);
        ApexPages.currentPage().getParameters().put('id',ri.Id);
        ApexPages.currentPage().getParameters().put('grantId',grant.Id);
        RiskItemEditCtrl ann = new RiskItemEditCtrl(sc);
        ann.getKeyValueMap();        
        Test.stopTest();
    }
}