UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <formula>Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>AwardedAmountthisAction__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Awarded Amount this Action</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2000</fullName>
                </value>
                <value>
                    <fullName>2001</fullName>
                </value>
                <value>
                    <fullName>2002</fullName>
                </value>
                <value>
                    <fullName>2003</fullName>
                </value>
                <value>
                    <fullName>2004</fullName>
                </value>
                <value>
                    <fullName>2005</fullName>
                </value>
                <value>
                    <fullName>2006</fullName>
                </value>
                <value>
                    <fullName>2007</fullName>
                </value>
                <value>
                    <fullName>2008</fullName>
                </value>
                <value>
                    <fullName>2009</fullName>
                </value>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OrganizationAddress__c</fullName>
        <inlineHelpText>Auto populate field. Copy this from the application in cases of awards being created as a result of approved applications, progress reports or ammedment requests. For awards initiated by State, copy this information from the last award. Editable. Required</inlineHelpText>
        <label>Organization Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <label>Organization Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent to Grantee Review</fullName>
                </value>
                <value>
                    <fullName>Grantee Accepted</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>FINOPS Completed</fullName>
                </value>
                <value>
                    <fullName>Sent to FINOPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SupportYear__c</fullName>
        <description>Auto populated. Support year for the award.</description>
        <label>Support Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FiscalYear__c.object
<CustomObject>
    <description>[Business] Stores the Fiscal Year information (Need to revisit)</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Passive</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MST: Fiscal Year</label>
    <nameField>
        <label>Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/GoalObjective__c.object
<CustomObject>
    <description>Goals and Objectives object for Performance management</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Award to which the Goal is associated</description>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Goals_and_Objectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Goals Objectives</relationshipLabel>
        <relationshipName>Goals_Objectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Met</fullName>
                </value>
                <value>
                    <fullName>Partially Met</fullName>
                </value>
                <value>
                    <fullName>Not Met</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Goal Objective</label>
    <nameField>
        <displayFormat>GOB-{0000}</displayFormat>
        <label>Goals and Objectives Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals Objectives</pluralLabel>
    <recordTypes>
        <fullName>Award</fullName>
        <active>true</active>
        <description>Award RecordType for Goal and Objective</description>
        <label>Award</label>
    </recordTypes>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <description>Program RecordType for Goal and Objective</description>
        <label>Program</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>AwardedAmountthisAction__c</fullName>
        <label>Awarded Amount this Action</label>
        <summarizedField>Award__c.AwardedAmountthisAction__c</summarizedField>
        <summaryForeignKey>Award__c.Grant__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <label>Organization Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProgramCode</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed/Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Year</label>
        <referenceTo>FiscalYear__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <formula>Account__r.Name</formula>
        <label>Organization Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestGoalEditCtrl.cls
@isTest
private class TestGoalEditCtrl {
    
    @isTest static void test_method_one() {
    /*
        Test.startTest();
        PageReference pageRef = Page.GoalEdit;
        Test.setCurrentPage(pageRef);

        
        GrantTriggerHelper.skipTrigger = true;
        AwardTriggerHelper.skipTrigger = true;
        AccountTriggerHelper.skipTrigger = true;
        ProgramTriggerHelper.skipTrigger = true;
        GoalObjectiveTriggerHelper.skipTrigger = true;

        Account account = TestHelper.getAccount(true);
        Program__c program = TestHelper.getProgram(account.Id, true);

        Grant__c grant = TestHelper.getGrant(true);
        Award__c award = new Award__c();
        award.grant__c = grant.Id;
        award.Name = Math.Random()+'AW12';
        award.OrganizationName__c = 'Test Org';
        award.OrganizationAddress__c = 'Test Address';
        award.FiscalYear__c = '2013';
        award.SupportYear__c = Decimal.valueOf('2013');
        award.Status__c = 'Issued';
        award.AwardedAmountthisAction__c = 156.15;
        award.PriorAwardedAmount__c = 465.46;
        insert award;
        GoalObjective__c gParent = new GoalObjective__c(isParent__c = true,Award__r = award,ExpenditureAmount__c = 12315.12,AllocatedAmount__c = 1231561.12, Allocated__c = 50.32);
        insert gParent;
        GoalObjective__c gChild = new GoalObjective__c(ParentGoal__r = gParent, isParent__c = false,Award__r = award,ExpenditureAmount__c = 16515156.12,AllocatedAmount__c = 123123.12, Allocated__c = 50.32);
        //insert gChild;
        //gParent.Allocated__c = 12.15;
        //gChild.Allocated__c = 12.12;
        //update gParent;
        //update gChild;
        ApexPages.currentPage().getParameters().put('id', null);
        ApexPages.currentPage().getParameters().put('awardId',award.Id);

        ApexPages.currentPage().getParameters().put('programid', program.Id);
        ApexPages.currentPage().getParameters().put('isParent', 'Yes');
        ApexPages.currentPage().getParameters().put('goalId', gParent.Id);
        ApexPages.currentPage().getParameters().put('type', 'AwardGoal');

        ApexPages.StandardController stdController = new ApexPages.StandardController(gChild);

        GoalEditCtrl g = new GoalEditCtrl(stdController);
        g.getKeyValueMap();
        Test.stopTest();
*/
    }
    
    @isTest static void test_method_two() {
    /*
        Test.startTest();
        PageReference pageRef = Page.GoalEdit;
        Test.setCurrentPage(pageRef);

        
        GrantTriggerHelper.skipTrigger = true;
        AwardTriggerHelper.skipTrigger = true;
        AccountTriggerHelper.skipTrigger = true;
        ProgramTriggerHelper.skipTrigger = true;
        GoalObjectiveTriggerHelper.skipTrigger = true;

        Account account = TestHelper.getAccount(true);
        Program__c program = TestHelper.getProgram(account.Id, true);

        Grant__c grant = TestHelper.getGrant(true);
        Award__c award = new Award__c();
        award.grant__c = grant.Id;
        award.Name = Math.Random()+'AW12';
        award.OrganizationName__c = 'Test Org';
        award.OrganizationAddress__c = 'Test Address';
        award.FiscalYear__c = '2013';
        award.SupportYear__c = Decimal.valueOf('2013');
        award.Status__c = 'Issued';
        award.AwardedAmountthisAction__c = 156.15;
        award.PriorAwardedAmount__c = 465.46;
        insert award;
        GoalObjective__c gParent = new GoalObjective__c(isParent__c = true,Award__r = award,ExpenditureAmount__c = 12315.12,AllocatedAmount__c = 1231561.12, Allocated__c = 50.32);
        insert gParent;
        GoalObjective__c gChild = new GoalObjective__c(ParentGoal__r = gParent, isParent__c = false,Award__r = award,ExpenditureAmount__c = 16515156.12,AllocatedAmount__c = 123123.12, Allocated__c = 50.32);
        //insert gChild;
        //gParent.Allocated__c = 12.15;
        //gChild.Allocated__c = 12.12;
        //update gParent;
        //update gChild;
        ApexPages.currentPage().getParameters().put('id', null);
        ApexPages.currentPage().getParameters().put('awardId',null);

        ApexPages.currentPage().getParameters().put('programid', program.Id);
        ApexPages.currentPage().getParameters().put('isParent', 'Yes');
        ApexPages.currentPage().getParameters().put('goalId', gParent.Id);
        ApexPages.currentPage().getParameters().put('type', 'AwardObjective');

        ApexPages.StandardController stdController = new ApexPages.StandardController(gChild);
        GoalEditCtrl g = new GoalEditCtrl(stdController);
        g.getKeyValueMap();
        Test.stopTest();
        */
    }
    @isTest static void test_method_three() {
    /*
        Test.startTest();
        PageReference pageRef = Page.GoalEdit;
        Test.setCurrentPage(pageRef);

        
        GrantTriggerHelper.skipTrigger = true;
        AwardTriggerHelper.skipTrigger = true;
        AccountTriggerHelper.skipTrigger = true;
        ProgramTriggerHelper.skipTrigger = true;
        GoalObjectiveTriggerHelper.skipTrigger = true;

        Account account = TestHelper.getAccount(true);
        Program__c program = TestHelper.getProgram(account.Id, true);

        Grant__c grant = TestHelper.getGrant(true);
        Award__c award = new Award__c();
        award.grant__c = grant.Id;
        award.Name = Math.Random()+'AW12';
        award.OrganizationName__c = 'Test Org';
        award.OrganizationAddress__c = 'Test Address';
        award.FiscalYear__c = '2013';
        award.SupportYear__c = Decimal.valueOf('2013');
        award.Status__c = 'Issued';
        award.AwardedAmountthisAction__c = 156.15;
        award.PriorAwardedAmount__c = 465.46;
        insert award;
        GoalObjective__c gParent = new GoalObjective__c(isParent__c = true,Award__r = award,ExpenditureAmount__c = 12315.12,AllocatedAmount__c = 1231561.12, Allocated__c = 50.32);
        insert gParent;
        GoalObjective__c gChild = new GoalObjective__c(ParentGoal__r = gParent, isParent__c = false,Award__r = award,ExpenditureAmount__c = 16515156.12,AllocatedAmount__c = 123123.12, Allocated__c = 50.32);
        //insert gChild;
        //gParent.Allocated__c = 12.15;
        //gChild.Allocated__c = 12.12;
        //update gParent;
        //update gChild;
        ApexPages.currentPage().getParameters().put('id', gParent.Id);
        ApexPages.currentPage().getParameters().put('awardId',null);

        ApexPages.currentPage().getParameters().put('programid', program.Id);
        ApexPages.currentPage().getParameters().put('isParent', 'Yes');
        ApexPages.currentPage().getParameters().put('goalId', gParent.Id);
        ApexPages.currentPage().getParameters().put('type', 'ProgramGoal');

        ApexPages.StandardController stdController = new ApexPages.StandardController(gChild);
        GoalEditCtrl g = new GoalEditCtrl(stdController);
        g.getKeyValueMap();
        Test.stopTest();
        */
    }
    @isTest static void test_method_four() {
    /*
        Test.startTest();
        PageReference pageRef = Page.GoalEdit;
        Test.setCurrentPage(pageRef);

        
        GrantTriggerHelper.skipTrigger = true;
        AwardTriggerHelper.skipTrigger = true;
        AccountTriggerHelper.skipTrigger = true;
        ProgramTriggerHelper.skipTrigger = true;
        GoalObjectiveTriggerHelper.skipTrigger = true;

        Account account = TestHelper.getAccount(true);
        Program__c program = TestHelper.getProgram(account.Id, true);

        Grant__c grant = TestHelper.getGrant(true);
        Award__c award = new Award__c();
        award.grant__c = grant.Id;
        award.Name = Math.Random()+'AW12';
        award.OrganizationName__c = 'Test Org';
        award.OrganizationAddress__c = 'Test Address';
        award.FiscalYear__c = '2013';
        award.SupportYear__c = Decimal.valueOf('2013');
        award.Status__c = 'Issued';
        award.AwardedAmountthisAction__c = 156.15;
        award.PriorAwardedAmount__c = 465.46;
        insert award;
        GoalObjective__c gParent = new GoalObjective__c(isParent__c = true,Award__r = award,ExpenditureAmount__c = 12315.12,AllocatedAmount__c = 1231561.12, Allocated__c = 50.32);
        insert gParent;
        GoalObjective__c gChild = new GoalObjective__c(ParentGoal__r = gParent, isParent__c = false,Award__r = award,ExpenditureAmount__c = 16515156.12,AllocatedAmount__c = 123123.12, Allocated__c = 50.32);
        //insert gChild;
        //gParent.Allocated__c = 12.15;
        //gChild.Allocated__c = 12.12;
        //update gParent;
        //update gChild;
        ApexPages.currentPage().getParameters().put('id', null);
        ApexPages.currentPage().getParameters().put('awardId',null);

        ApexPages.currentPage().getParameters().put('programid', program.Id);
        ApexPages.currentPage().getParameters().put('isParent', 'Yes');
        ApexPages.currentPage().getParameters().put('goalId', gParent.Id);
        ApexPages.currentPage().getParameters().put('type', 'ProgramObjective');

        ApexPages.StandardController stdController = new ApexPages.StandardController(gChild);
       
        GoalEditCtrl g = new GoalEditCtrl(stdController);
        g.getKeyValueMap();
        Test.stopTest();
        */
    }
    
}