UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BudgetPeriod__c.object
<CustomObject>
    <description>[Business] This object stores all Budget Period Details.</description>
    <fields>
        <fullName>BudgetEndDate__c</fullName>
        <description>This stores Budget End date</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BudgetPeriod__c</fullName>
        <formula>IF(AND(NOT(ISBLANK(BudgetStartDate__c )),NOT(ISBLANK(BudgetEndDate__c))),TEXT(MONTH( BudgetStartDate__c ))+&quot;/&quot; +TEXT(DAY(BudgetStartDate__c))+&quot;/&quot; +TEXT(YEAR(BudgetStartDate__c))+&quot;--&quot;+ TEXT(MONTH( BudgetEndDate__c ))+&quot;/&quot; +TEXT(DAY(BudgetEndDate__c))+&quot;/&quot; +TEXT(YEAR(BudgetEndDate__c)),&apos;&apos;)</formula>
        <label>Budget Period</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BudgetStartDate__c</fullName>
        <description>This stores Budget Start Date</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Budget Periods</relationshipLabel>
        <relationshipName>Budget_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Passive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Budget Period</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Budget Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BusinessPackage__c.object
<CustomObject>
    <description>[Business]  This object associates the Package with the Program or Opportunity</description>
    <fields>
        <fullName>ProgramName__c</fullName>
        <description>This formula field is used in Grantee Package 2 flex table</description>
        <formula>IF( ISBLANK(FundingOpportunity__c) , 
      IF( ISBLANK(Grant__c) , 
          &quot;&quot;, 
           IF( ISBLANK(Grant__r.FederalProgram__c) , 
				&quot;&quot;, 
                HYPERLINK((&apos;/&apos; + Grant__r.FederalProgram__c), Grant__r.FederalProgram__r.FederalProgramTitle__c ,&apos;_self&apos;) 
			)
		),
      IF( ISBLANK(FundingOpportunity__r.Program__c) , 
           IF( ISBLANK(Grant__c) , 
				&quot;&quot;, 
				IF( ISBLANK(Grant__r.FederalProgram__c) , 
						&quot;&quot;, 
						HYPERLINK((&apos;/&apos; + Grant__r.FederalProgram__c), Grant__r.FederalProgram__r.FederalProgramTitle__c ,&apos;_self&apos;) 
				)
            ) ,
           FundingOpportunity__r.FederalProgram__c
		) 
)</formula>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Package</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/JXPrograms__c.object
<CustomObject>
    <description>[Business] Used for mapping the Federal/State Announcements with the program</description>
    <fields>
        <fullName>StateProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Junction_For_Programs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Junction</label>
    <nameField>
        <displayFormat>JXPROG-{0000}</displayFormat>
        <label>Junction For Programs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Division of the organization to which the User Belongs</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AttachmentsRequired__c</fullName>
        <inlineHelpText>Please enter list of required attachments separated by semicolons; include &apos;optional&apos; with the file type if it is not mandatory.</inlineHelpText>
        <label>AttachmentsRequired</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>End date of the program, to determine if it is a single or a multi year program</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FunderType__c</fullName>
        <label>Funder Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Federal</fullName>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>NGO</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsNoReviewStepProgram__c</fullName>
        <formula>IF(ISPICKVAL(ReviewProcess__c, &apos;No Review&apos;), TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsNoReviewStepProgram</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsProjectServiceAreaneeded__c</fullName>
        <description>This directs user to whether user Project/Service Area or not use it.</description>
        <label>Is Project/Service Area Needed?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProgramBudgetTypeUSBE__c</fullName>
        <label>ProgramBudgetTypeUSBE</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ProgramPathway__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Regular</fullName>
                </value>
                <value>
                    <fullName>CTE</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProgramName__c</fullName>
        <description>This stores the Title of Program</description>
        <label>Program Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Start date of the program</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ProgramBudgetCategory__c.object
<CustomObject>
    <description>Junction Object for Program and Budget Category</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Budget Categories</relationshipLabel>
        <relationshipName>ProgramBudgetCategories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Budget Category</label>
    <nameField>
        <displayFormat>PB-{0000}</displayFormat>
        <label>Program Budget Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Budget Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ProgramContacts__c.object
<CustomObject>
    <description>[Business] Contacts associated with a Program</description>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>ProgramContacts</relationshipLabel>
        <relationshipName>ProgramContacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Contact</label>
    <nameField>
        <displayFormat>ProgCont-{0000}</displayFormat>
        <label>Program Contacts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProgramContacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ProgramFundingAccount__c.object
<CustomObject>
    <description>[Business] Junction object between Funding Account and Program</description>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Funding Accounts</relationshipLabel>
        <relationshipName>Program_Funding_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Funding Account</label>
    <nameField>
        <displayFormat>PFA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ProgramServiceArea__c.object
<CustomObject>
    <description>[Business] Junction object of a Program with the Service Area</description>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>ServiceAreas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Project Area</label>
    <nameField>
        <displayFormat>PSA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Project Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStepTemplate__c.object
<CustomObject>
    <description>[Business] Template defined for a Step Review , Previous Name (Review Step Template)</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to program record.</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>ReviewStepTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Review Step Template</label>
    <nameField>
        <label>Review Step Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Step Templates</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RolesAndResponsibilities__c.object
<CustomObject>
    <description>[Business] Roles and Responsibilities defined for all the objects like Opportunity ,Application etc</description>
    <fields>
        <fullName>BusinessRole__c</fullName>
        <description>This is a picklist which will be displayed in RR table in all phases.</description>
        <label>Business Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BusinessRole</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to populate the Program to which this Role and and Responsibility belongs</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Roles and Responsibilities</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles and Responsibilities</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Application.</description>
        <label>Application</label>
    </recordTypes>
    <recordTypes>
        <fullName>Closeout</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Closeout.</description>
        <label>Closeout</label>
    </recordTypes>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Program.</description>
        <label>Program</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ProgramSubmissionHelper.cls
//Leon 

global with sharing class ProgramSubmissionHelper extends GNT.DynamicLayoutActionRedirect { 

    global override PageReference whenClicked(){
    Savepoint sp = Database.setSavepoint();
    List<String> errors = new List<String>();  
    try{
        Id recordId = apexpages.currentpage().getparameters().get('id');
        List<RolesAndResponsibilities__c> lstRolesResposiblities = [Select Id,BusinessRole__c from RolesAndResponsibilities__c where Program__c =:recordId ];
        Program__c program = [Select Id,Name,RecordType.Name,AttachmentsRequired__c,FunderType__c,StartDate__c,EndDate__c,IsProjectServiceAreaneeded__c,ProgramName__c, Account__r.Name, ProgramBudgetTypeUSBE__c, IsNoReviewStepProgram__c from Program__c where Id =:recordId ];
        List<ProgramServiceArea__c> programService = [Select Id from ProgramServiceArea__c where Program__c =:recordId];
        //List<JXPrograms__c> FederalPrograms = [Select Id from JXPrograms__c where StateProgram__c =:recordId];
        List<BudgetPeriod__c> budPeriod = [Select Id,BudgetStartDate__c,BudgetEndDate__c, Status__c,Program__c from BudgetPeriod__c where Program__c =: recordId order by BudgetStartDate__c asc];
        List<ProgramBudgetCategory__c> programBudgetCategory = [Select Name from ProgramBudgetCategory__c where Program__c = :recordId];
        List<ProgramFundingAccount__c> programFundingAccount = [Select Name from ProgramFundingAccount__c where Program__c = :recordId];
        List<ProgramContacts__c> programContactList = [Select Id, Name from ProgramContacts__c where Program__c=: recordId];
        Integer count = 0;
        boolean approverExists = false;
        boolean keypocExists = false;
        boolean fiscalAppoverExists = false;
        boolean executiveApproverExists = false;
 
 
        for(RolesAndResponsibilities__c role : lstRolesResposiblities){
            if(role.BusinessRole__c!= null && role.BusinessRole__c.equals('Program Approver')){
                approverExists = true;
            }
            if(role.BusinessRole__c!= null && role.BusinessRole__c.equals('Fiscal Approver')){
                fiscalAppoverExists = true;
            }
            if(role.BusinessRole__c!= null && role.BusinessRole__c.equals('Key POC')){  
                keypocExists = true;
            }
            if(role.BusinessRole__c!=null && role.BusinessRole__c.equals('Executive Approver')){
              executiveApproverExists=true;
            }
            // Leon: added Executive approver for both USBE AND UOVC programs
        }

        if(budPeriod.size()>0){
          for(BudgetPeriod__c bud: budPeriod){
            if(bud.Status__c == 'Active'){
              count++;
            }
          }
        }
        //Check to make sure 'Other' is a type of attachment; and adding it, if it is not there. 
        String listOfAttachments=program.AttachmentsRequired__c;
        if (listOfAttachments!=null){
        if (!listOfAttachments.containsIgnoreCase('other'))
          //errors.add ('Must have attachment type ' +'other'); 
          program.AttachmentsRequired__c+=';Other';
          update program;
        }
        else{
          program.AttachmentsRequired__c='Other';
          update program;
        }


        //Checking for financial and programmatic contacts. 

        
        // Check Review Process
        List<ReviewStepTemplate__c> reviewStepList = [Select Id,IsStepMandatory__c from ReviewStepTemplate__c where Program__c =:recordId and IsStepMandatory__c='Mandatory'];
       
         // Check App-Review Packages 
        //List<BusinessPackage__c> pkgList = [Select Id,PackageType__c from BusinessPackage__c where Program__c =:recordId and PackageType__c='Application'];
        
        AggregateResult[] aggs = [SELECT PackageType__c packageType FROM BusinessPackage__c WHERE Program__c =:recordId GROUP BY PackageType__c];
        Set<String> packageTypeSet = new Set<String>();
        for(AggregateResult agg : aggs){
          packageTypeSet.add(String.valueOf(agg.get('packageType')));
        }

        if(!packageTypeSet.contains('Risk Assessment')){
          errors.add ('Please associate a Package with Risk Assessment under attachments.');
        }

        if(!packageTypeSet.contains('Progress Report')){
          errors.add ('Please associate a Package with Progress Report under attachments.');
        }

        if(!packageTypeSet.contains('Site Visit')){
          errors.add ('Please associate a Package with Site Visit under attachments.');
        }

        if(!packageTypeSet.contains('Closeout')){
          errors.add ('Please associate a Package with Closeout under attachments.');
        }

        if(programBudgetCategory == null || programBudgetCategory.size() == 0){
            //errors.add ('Program must have at least one budget category');
            errors.add (GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-31605'));
        }
        //Shivankar: Commented this validation out based on BA's request. 
      //  if(programFundingAccount == null || programFundingAccount.size() == 0){ 
      //    //errors.add ('Program must have at least one funding account associated'); 
      //  errors.add (GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTE-16024')); 
      //}
    
        if(!AppUtils.validateBudgetPeriods(program.StartDate__c,program.EndDate__c,budPeriod)){
          errors.add (GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-79576'));
        }
        if(keypocExists == false){
            //errors.add ('A Key POC (under Roles & Responsibilities section of Review Tab) is a required field for a program');
            errors.add (GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-54930'));
        }
        if(approverExists == false){
            //errors.add( ' An Approver (under Roles & Responsibilities section of Review Tab) is a required field for a program');
            errors.add(GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-99971'));
        }
        if(fiscalAppoverExists == false){
            errors.add('A Fiscal Approver (under Roles & Responsibilities section of Roles Tab) is a required field for a program');
        }
        if(executiveApproverExists == false){
          errors.add('A Executive Approver (under Roles & Responsibilities section of Roles Tab) is a required field for a program');
        }        

        if(programContactList.isEmpty()){
        //errors.add('Please add atleast one Program Contact');
        errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTE-75625'));     
        }
    
        //if(pkgList == null || pkgList.size()==0){
             //errors.add(' Please associate a Package with Application Package Type with the Program.');
            //errors.add(GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-52018'));
        //}
        if((program.IsProjectServiceAreaneeded__c =='Yes') && (programService == null || programService.size()==0)){
            //errors.add('Please associate atleast one Service Area with the Program.');
            errors.add(GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-83669'));
        }
        if((program.IsProjectServiceAreaneeded__c =='No') && (programService.size() > 0)){
            //errors.add('Please do not associate Service Area, if Project Service Area is not needed');
            errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-39325'));
            //errors.add(GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-83669'));
        }
        //if((program.FunderType__c == 'Federal') && (FederalPrograms == null || FederalPrograms.size()==0)){
        //    //errors.add('Please associate atleast one Federal Program with the Program.');
        //    errors.add(GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-65888'));
        //}
        
       /* if (program.Account__r.Name == 'USBE' && program.ProgramBudgetTypeUSBE__c == null) {
            errors.add('USBE programs must specify their program type');
        } */
        
        if(count == 0){
          errors.add(GNT.ErrorMessageHelper.fetchMessage('P17-GRNTE-39059'));
        }
        if(count>1){
          errors.add(GNT.ErrorMessageHelper.fetchMessage('P17-GRNTE-52534'));
        }
        if(errors.size() > 0){
                 for(String error: errors){
                   ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, error));
                 }
              }
        
        else if(keypocExists == true && approverExists == true){
             ProgramTriggerHelper.skipTrigger = true;
             System.debug('***entered here *** ');
             GNT.TaskCreationHandler.createApprovalProcessTasks(program.Id, 'Approve Program', program.Name, null, System.TODAY() + 7, program.ProgramName__c, true);
             //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'The Program has been submitted successfully.'));
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-12057')));
             PageReference p = Page.ProgramView;
             p.getParameters().put('Id', program.Id);
             p.setRedirect(true);
             return p; 
        }
           return null; 
       } catch(Exception e){
            Database.rollback(sp);
            System.debug('***exception caught' + e.getCause());
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            return null;
        }
    }

    
}