UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>InternalUniqueID__c</fullName>
        <externalId>true</externalId>
        <label>InternalUniqueID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsExtensionAllowed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This filed is being used on grantor ---&gt; planning --&gt;  manage recipient</description>
        <label>Is Extension Allowed</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>ApplicationDeadlineWithDateTime__c</fullName>
        <label>Application Deadline</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ExtensionDays__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Defines extension days for application deadline</description>
        <inlineHelpText>Defines extension days for application deadline</inlineHelpText>
        <label>ExtensionDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>InternalUniqueID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Uniquely identifies each record for data migration purpose only. It is auto populated by trigger in before insert context.</description>
        <externalId>true</externalId>
        <label>Internal Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MaxApplicationsAllowed__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Maximum # Applications Allowed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PointofContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Key POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Announcement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TimeExtensionAllowed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Time Extension allowed for announcement to eligible applications?</description>
        <inlineHelpText>Is Time Extension allowed for announcement to eligible applications?</inlineHelpText>
        <label>Time Extension Allowed</label>
        <type>Checkbox</type>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AnnouncementFundingAccount__c.object
<CustomObject>
    <description>[Business]  Funding Accounts associated with the opportunity</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>Announcement</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>InternalUniqueID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Uniquely identifies each record for data migration purpose only. It is auto populated by trigger in before insert context.</description>
        <externalId>true</externalId>
        <label>Internal Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Funding Opportunity Funding Account</label>
    <nameField>
        <displayFormat>AFA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Opportunity Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApplicationDeadlineWithDateTime__c</fullName>
        <description>This field is created because the current field is a Formula fild , Need to delete one of them later on</description>
        <label>Application Deadline</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ExternalOrganization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Orgnanization which owns the Application This field is also used on the Forms as well</description>
        <inlineHelpText>Which organization owns the application?</inlineHelpText>
        <label>Applicant Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InternalUniqueID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Uniquely identifies each record for data migration purpose only. It is auto populated by trigger in before insert context.</description>
        <externalId>true</externalId>
        <label>Internal Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>InternalUniqueID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Uniquely identifies each record for data migration purpose only. It is auto populated by trigger in before insert context.</description>
        <externalId>true</externalId>
        <label>Internal Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>InternalUniqueID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>InternalUniqueID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/CloneApplicationHelper.cls
global with sharing class CloneApplicationHelper extends GNT.DynamicLayoutActionRedirect{
    Application__c currentRecord;
    public CloneApplicationHelper(ApexPages.StandardController controller) {
     currentRecord = (Application__c)controller.getRecord();
    }
    public CloneApplicationHelper(GNT.DynamicLayoutHolder layoutHolder) {
        this.layoutHolder = layoutHolder;
    }
    public CloneApplicationHelper( ) {
        }
    global override PageReference whenClicked(){
        Application__c newRecord;
        Savepoint sp = Database.setSavepoint();
        Integer appCount,maxAppCount;
        Boolean HideSubmit = true;
        Id recordId = layoutHolder.getPrimarySObject().Id;
        String newId = '';
    	Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
    	String uniqueIdAPIName = 'InternalUniqueID__c';
    	String SobjectApiName = 'Application__c';
        Map<String, Schema.SObjectField> fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();
        String commaSeparatedFields = '';
        for(String fieldName : fieldMap.keyset()){
            if(!fieldName.equalsIgnorecase(uniqueIdAPIName)){
                if(commaSeparatedFields == null || commaSeparatedFields == ''){
                    commaSeparatedFields = fieldName;
                }else{
                    commaSeparatedFields = commaSeparatedFields + ', ' + fieldName;
                }
            }
        }
        String query = 'select Announcement__r.MaxApplicationsAllowed__c, Announcement__r.Name, ' + commaSeparatedFields + ' from ' + SobjectApiName + ' where Id = \'' + recordId + '\'';
        
        currentRecord = Database.query(query);
        List<Application__c> appList = [Select Id, Name from Application__c where Announcement__c=:currentRecord.Announcement__c and ExternalOrganization__c =:currentRecord.ExternalOrganization__c];
        if(appList!=null &&  appList.size()>0){
            appCount = appList.size();
       } else{
            appCount = 0;
        }
        if(currentRecord.Announcement__r.MaxApplicationsAllowed__c!=null&&currentRecord.Announcement__r.MaxApplicationsAllowed__c>0){
            maxAppCount=(Integer)currentRecord.Announcement__r.MaxApplicationsAllowed__c;
        }
        else{
            maxAppCount=1;
        }
        Announcement__c announcementObj = [Select ApplicationDeadlineWithDateTime__c, ExtensionDays__c, TimeExtensionAllowed__c from Announcement__c where Id = :currentRecord.Announcement__c limit 1];
        Date d = Date.newInstance(announcementObj.ApplicationDeadlineWithDateTime__c.year(), announcementObj.ApplicationDeadlineWithDateTime__c.month(), announcementObj.ApplicationDeadlineWithDateTime__c.day());
        User u = [Select Contact.Account.IsExtensionAllowed__c from User where Id = :UserInfo.getUserId()];
        if(u.Contact.Account.IsExtensionAllowed__c == true && announcementObj.TimeExtensionAllowed__c == true){          
          if(d + Integer.valueOf(announcementObj.ExtensionDays__c )> Date.today()){
              HideSubmit = false;
          }
        }else{
          if(d > Date.today()){
              HideSubmit = false;
          }
        }
        if(HideSubmit){
            // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Cannot clone application after application deadline'));
          ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, GNT.ErrorMessageHelper.fetchMessage('P32-RPT-15414')));
          return null;
        }
        if(maxAppCount<=appCount){
            // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Application can not be cloned as you have reached the maximum limit for allowed applications for '+currentRecord.Announcement__r.Name));
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-17603')+' ' +currentRecord.Announcement__r.Name));
            return null;                 
        }
        ApplicationCloneHelper cloneHelper = new ApplicationCloneHelper();
		newId = cloneHelper.cloneApplication(recordId, null);
       return new PageReference('/'+newId);
    }
       
}