UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>BudgetPeriodEndDate__c</fullName>
        <description>Budget Period End Date for the award.</description>
        <label>Budget Period End Date(obsolete)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BudgetPeriodStartDate__c</fullName>
        <description>Budget Period Start Date for the award.</description>
        <label>Budget Period Start Date (Obsolete)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExternalOrganization__c</fullName>
        <formula>Grant__r.ExternalOrganization__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>External Organization</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodEndDate__c</fullName>
        <description>Project Period End Date for the award.</description>
        <label>Project Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodStartDate__c</fullName>
        <description>Project Period Start Date for the award.</description>
        <label>Project Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent to Grantee Review</fullName>
                </value>
                <value>
                    <fullName>Grantee Accepted</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>FINOPS Completed</fullName>
                </value>
                <value>
                    <fullName>Sent to FINOPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>BudgetPeriodEndDate__c</fullName>
        <label>Current Budget Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BudgetPeriodStartDate__c</fullName>
        <label>Current Budget Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExternalOrganization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProgramCode</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodEndDate__c</fullName>
        <label>Project Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodStartDate__c</fullName>
        <label>Project Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed/Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/TermCondition__c.object
<CustomObject>
    <description>[Business] Terms and Conditions for Grants ,Awards (The lookup to Package may not be required in this case )</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CalReportingStartDate__c</fullName>
        <label>Reporting Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DueDateDays__c</fullName>
        <inlineHelpText>How many days after the end of the reporting period?</inlineHelpText>
        <label>Due Date Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FixedEndDate__c</fullName>
        <description>The date starting when the term becomes inactive.</description>
        <inlineHelpText>The date starting when the term becomes inactive. This field gets populated only if &apos;Report End Date&apos; is &apos;Fixed&apos;</inlineHelpText>
        <label>Fixed End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FixedStartDate__c</fullName>
        <description>The date starting when the term becomes active.</description>
        <inlineHelpText>The date starting when the term becomes active. This field gets populated only if &apos;Report Start Date&apos; is &apos;Fixed&apos;.</inlineHelpText>
        <label>Fixed Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                    <default>true</default>
                    <label>Fixed</label>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReportEndDate__c</fullName>
        <description>Date on which the report&apos;s frequency should end</description>
        <inlineHelpText>Budget Period Start Date - The reporting cycle should end on current Budget Period End Date 
Fixed Date - end on a fixed date</inlineHelpText>
        <label>Ending Date</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget Period End Date</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReportStartDate__c</fullName>
        <description>Used for Post Award Submission Report creation</description>
        <inlineHelpText>Budget Period Start Date - The reporting cycle should start from current Budget Period Start Date
Fixed Date - start from a fixed date</inlineHelpText>
        <label>Beginning Date</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget Period Start Date</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Active, Inactive. If the Effective Date is current or in the past and if the Inactive On date is in the future, the Term is Active. If the Inactive Date is in the past, the term is Inactive. Prepopulated. Read Only.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubmissionRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether a submission (task) is to be created for the external user?</description>
        <label>Submission Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TaskAvailability__c</fullName>
        <description>The task will be made available to the grantee &apos;X&apos; number of days before the due date, based on the number entered here.</description>
        <inlineHelpText>Enter number of days prior to Due Date</inlineHelpText>
        <label>Task Availability</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UpcomingReportSubmissionDate__c</fullName>
        <label>Upcoming Report Submission Date</label>
        <type>Date</type>
    </fields>
    <label>MST:Term and Condition</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <recordTypes>
        <fullName>Condition</fullName>
        <active>true</active>
        <label>Condition</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestTermConditionTrigger.cls
@isTest
private with sharing class TestTermConditionTrigger{

    @isTest
    static void testAll(){ 
    /*
        UserTriggerHelper.skipTrigger=true;
        user u = TestHelper.getAdminUser(true);
        AccounttriggerHelper.skipTrigger= true;
        AwardTriggerHelper.skipTrigger= true;
        GrantTriggerHelper.skipTrigger= true;
        system.runAs(u){   
        test.StartTest();  
          
            Account acc=TestHelper.getAccount(false);
            acc.Name='REI ORGANIZATION1';
            insert acc;
            UserRole userrole=new UserRole(Name='new userrole',DeveloperName='REIORGANIZATION1PartnerExecutive');
            insert userrole;    
            
           
           
            //Grant__c grant = testHelper.getGrant(false);                    
            //grant.ExternalOrganization__c = acc.id;
            Grant__c grant = TestHelper.getGrant(false);
            //grant.Program__c = program.id;
            grant.Status__c = 'Active';
            grant.ProjectPeriodStartDate__c=Date.today();
            
            grant.ExternalOrganization__c = acc.id;
            insert grant;
            //insert grant;
            
            TermCondition__c tnc = TestHelper.getTermCondition(false,'Condition');
            tnc.Frequency__c = 'Monthly';
            tnc.SubmissionRequired__c = true;
            
            tnc.DueDateDays__c = 3;
            tnc.TaskAvailability__c = 4;
            
            tnc.Grant__c = grant.id;
            tnc.ReportStartDate__c = 'Fixed';
            tnc.ReportEndDate__c = 'Fixed';
            tnc.FixedStartDate__c = system.today();
            tnc.FixedEndDate__c = system.today()+233;
            tnc.UpcomingReportSubmissionDate__c = null;
            insert tnc;
            
            tnc.RecordTypeId = Schema.SObjectType.TermCondition__c.getRecordTypeInfosByName().get('Payment Request').getRecordTypeId();
            
            update tnc;  
            Award__c award = TestHelper.getAwards(grant.id,true);
          
            TermCondition__c tnc_2 = TestHelper.getTermCondition(false,'Condition');
            tnc_2.Frequency__c = 'Quarterly';
            tnc_2.SubmissionRequired__c = true;
            
            tnc_2.DueDateDays__c = 3;
            tnc_2.TaskAvailability__c = 4;
            
            tnc_2.Award__c = award.id;
            tnc_2.ReportStartDate__c = 'Fixed';
            tnc_2.ReportEndDate__c = 'Fixed';
            tnc_2.FixedStartDate__c = system.today();
            tnc_2.FixedEndDate__c = system.today()+233;
            tnc_2.UpcomingReportSubmissionDate__c = null;
            insert tnc_2;
            tnc_2.RecordTypeId = Schema.SObjectType.TermCondition__c.getRecordTypeInfosByName().get('Payment Request').getRecordTypeId();
            
            update tnc_2;  

            
            TermCondition__c tnc_3 = TestHelper.getTermCondition(false,'Condition');
            tnc_3.Frequency__c = 'Annually';
            tnc_3.SubmissionRequired__c = true;
            
            tnc_3.DueDateDays__c = 3;
            tnc_3.TaskAvailability__c = 4;
            
            tnc_3.Award__c = award.id;
            tnc_3.ReportStartDate__c = 'Fixed';
            tnc_3.ReportEndDate__c = 'Fixed';
            tnc_3.FixedStartDate__c = system.today();
            tnc_3.FixedEndDate__c = system.today()+378;
            tnc_3.UpcomingReportSubmissionDate__c = null;
            insert tnc_3;            
            tnc_3.RecordTypeId = Schema.SObjectType.TermCondition__c.getRecordTypeInfosByName().get('Payment Request').getRecordTypeId();
            
            update tnc_3; 
          
            
            TermCondition__c tnc_4 = TestHelper.getTermCondition(false,'Condition');
            tnc_4.Frequency__c = 'Semi-Annually';
            tnc_4.SubmissionRequired__c = true;
            
            tnc_4.DueDateDays__c = 3;
            tnc_4.TaskAvailability__c = 4;
            
            tnc_4.Award__c = award.id;
            tnc_4.ReportStartDate__c = 'Fixed';
            tnc_4.ReportEndDate__c = 'Fixed';
            tnc_4.FixedStartDate__c = system.today();
            tnc_4.FixedEndDate__c = system.today()+378;
            tnc_4.UpcomingReportSubmissionDate__c = null;
            insert tnc_4;            
            test.StopTest();
            system.assertEquals(tnc_4.FixedEndDate__c,system.today()+378);
            
        }       
        */
    }
    
    @isTest
    static void testDateDiffGrant(){ 
        UserTriggerHelper.skipTrigger=true;
        user u = TestHelper.getAdminUser(true);
        system.runAs(u){   
        test.StartTest(); 
            TermCondition__c tnc_2; 
            try{  
                Account acc=TestHelper.getAccount(false);
                acc.Name='REI ORGANIZATION1';
                insert acc;
                UserRole userrole=new UserRole(Name='new userrole',DeveloperName='REIORGANIZATION1PartnerExecutive');
                insert userrole;    
                
            
                Grant__c grant = testHelper.getGrant(false);                    
                grant.ExternalOrganization__c = acc.id;
                grant.BudgetPeriodStartDate__c = system.today();
                grant.BudgetPeriodEndDate__c = system.today()+10;
                grant.ProjectPeriodStartDate__c = system.today();
                grant.ProjectPeriodEndDate__c = system.today()+10;
                insert grant;
                TermCondition__c tnc = TestHelper.getTermCondition(false,'Condition');
                tnc.Frequency__c = 'Monthly';
                tnc.SubmissionRequired__c = true;
                
                tnc.DueDateDays__c = 3;
                tnc.TaskAvailability__c = 4;
               
                tnc.Grant__c = grant.id;
                tnc.ReportStartDate__c = 'Budget Period Start Date';
                tnc.ReportEndDate__c = 'Budget Period End Date';
                tnc.CalReportingStartDate__c = system.today();
                tnc.CalReportingEndDate__c = system.today()+10;
                insert tnc;
                update tnc;  
                
                Award__c award = TestHelper.getAwards(grant.id,false);
                award.BudgetPeriodStartDate__c = system.today();
                award.BudgetPeriodEndDate__c = system.today()+10;
                insert award;
                
                tnc_2 = TestHelper.getTermCondition(false,'Condition');
                tnc_2.Frequency__c = 'Quarterly';
                tnc_2.SubmissionRequired__c = true;
               
                tnc_2.DueDateDays__c = 3;
                tnc_2.TaskAvailability__c = 4;
                
                tnc_2.grant__c= grant.id;
                tnc_2.ReportStartDate__c = 'Project Period Start Date';
                tnc_2.ReportEndDate__c = 'Project Period End Date';
                tnc_2.CalReportingStartDate__c = system.today();
                tnc_2.CalReportingEndDate__c = system.today()+60;
                insert tnc_2;
            }catch(Exception e){
                Boolean expectedExceptionThrown1 =  e.getMessage().contains('Beginning Date and Ending Date are too close to each other and the gap between them is shorter than the frequency') ? true : false;
                System.AssertEquals(expectedExceptionThrown1, false);
                
               
            }
            test.StopTest();
            //system.assertEquals(tnc_2.CalReportingEndDate__c,system.today()+60);
        }       
    }
    
    
    @isTest
    static void testDateDiffGrantNegative(){ 
        UserTriggerHelper.skipTrigger=true;
        user u = TestHelper.getAdminUser(true);
        system.runAs(u){   
        test.StartTest(); 
            TermCondition__c tnc; 
            try{  
                Account acc=TestHelper.getAccount(false);
                acc.Name='REI ORGANIZATION1';
                insert acc;
                UserRole userrole=new UserRole(Name='new userrole',DeveloperName='REIORGANIZATION1PartnerExecutive');
                insert userrole;    
                
  
                         
                Grant__c grant = testHelper.getGrant(false);                    
                grant.ExternalOrganization__c = acc.id;
                grant.BudgetPeriodStartDate__c = system.today();
                grant.BudgetPeriodEndDate__c = system.today()+10;
                insert grant;
                
                tnc = TestHelper.getTermCondition(false,'Condition');
                tnc.Frequency__c = 'Monthly';
                tnc.SubmissionRequired__c = true;
               
                tnc.DueDateDays__c = null;
                tnc.TaskAvailability__c = 4;
                
                tnc.Grant__c = grant.id;
                tnc.ReportStartDate__c = 'Budget Period Start Date';
                tnc.ReportEndDate__c = 'Budget Period End Date';
                tnc.CalReportingStartDate__c = system.today();
                tnc.CalReportingEndDate__c = system.today()+60;
                insert tnc;
                update tnc;  
                
            }catch(Exception e){
                Boolean expectedExceptionThrown2 =  e.getMessage().contains('If Submission Required is checked, please make sure you have populated') ? true : false;
                System.AssertEquals(expectedExceptionThrown2, false);
            }
            
            test.StopTest();
            //system.assertEquals(tnc.CalReportingEndDate__c,system.today()+60);
        }       
    }
}