UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LEA_Id__c</fullName>
        <label>LEA_Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2000</fullName>
                </value>
                <value>
                    <fullName>2001</fullName>
                </value>
                <value>
                    <fullName>2002</fullName>
                </value>
                <value>
                    <fullName>2003</fullName>
                </value>
                <value>
                    <fullName>2004</fullName>
                </value>
                <value>
                    <fullName>2005</fullName>
                </value>
                <value>
                    <fullName>2006</fullName>
                </value>
                <value>
                    <fullName>2007</fullName>
                </value>
                <value>
                    <fullName>2008</fullName>
                </value>
                <value>
                    <fullName>2009</fullName>
                </value>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProgramCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Code</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramName__c</fullName>
        <formula>Grant__r.Program__r.ProgramName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>USBEPathway__c</fullName>
        <label>USBEPathway</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AwardFINETCode__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award FINET Codes</relationshipLabel>
        <relationshipName>Award_FINET_Codes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MSPUniqueKeyFormula__c</fullName>
        <formula>Award__r.Grant__r.Program__c + Award__r.Grant__r.InternalOrganization__c + ProgramCode__r.PROG_CD__c + ObjectCode__r.OBJ_CD__c + Award__r.Grant__r.FiscalYear__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MSPUniqueKeyFormula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Object Code</label>
        <referenceTo>r_obj__c</referenceTo>
        <relationshipLabel>Award FINET Codes</relationshipLabel>
        <relationshipName>Award_FINET_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramCode__c</fullName>
        <label>Program Code</label>
        <referenceTo>r_prog__c</referenceTo>
        <relationshipLabel>Award FINET Codes</relationshipLabel>
        <relationshipName>Award_FINET_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Award FINET Code</label>
    <nameField>
        <label>Award FINET Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award FINET Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FileBatch__c.object
<CustomObject>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
                <value>
                    <fullName>2036</fullName>
                </value>
                <value>
                    <fullName>2037</fullName>
                </value>
                <value>
                    <fullName>2038</fullName>
                </value>
                <value>
                    <fullName>2039</fullName>
                </value>
                <value>
                    <fullName>2040</fullName>
                </value>
                <value>
                    <fullName>2041</fullName>
                </value>
                <value>
                    <fullName>2042</fullName>
                </value>
                <value>
                    <fullName>2043</fullName>
                </value>
                <value>
                    <fullName>2044</fullName>
                </value>
                <value>
                    <fullName>2045</fullName>
                </value>
                <value>
                    <fullName>2046</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>File Batch</label>
    <nameField>
        <label>File Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>File Batches</pluralLabel>
    <recordTypes>
        <fullName>MSP</fullName>
        <active>true</active>
        <label>MSP</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FiscalYear__c.object
<CustomObject>
    <description>[Business] Stores the Fiscal Year information (Need to revisit)</description>
    <fields>
        <fullName>InternalOrganization__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Internal Organization?</label>
        <type>Checkbox</type>
    </fields>
    <label>MST: Fiscal Year</label>
    <nameField>
        <label>Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/MSPFinancialStage__c.object
<CustomObject>
    <fields>
        <fullName>FileBatch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>File Batch</label>
        <referenceTo>FileBatch__c</referenceTo>
        <relationshipLabel>MSP Financial Stages</relationshipLabel>
        <relationshipName>MSP_Financial_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ObjectCode__c</fullName>
        <label>Object Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramCode__c</fullName>
        <label>Program Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>MSP Financial Stages</relationshipLabel>
        <relationshipName>MSP_Financial_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UniqueKeyFormula__c</fullName>
        <formula>Program__c + SubRecipient__c + ProgramCode__c + ObjectCode__c + TEXT(FileBatch__r.FiscalYear__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UniqueKeyFormula</label>
        <type>Text</type>
    </fields>
    <label>MSP Financial Stage</label>
    <nameField>
        <label>MSP Financial Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MSP Financial Stages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Year</label>
        <referenceTo>FiscalYear__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InternalOrganization__c</fullName>
        <description>Created to show up on the portal</description>
        <label>Internal Organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramCode__c</fullName>
        <formula>ProgramName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramName__c</fullName>
        <description>This stores the Title of Program</description>
        <label>Program Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/MSPFileBatchProcess.cls
public with sharing class MSPFileBatchProcess implements FileBatchProcess{
    public Map<String, String> getData(FileBatch__c fb){
        Map<String, String> results = new Map<String, String>();
        List<AwardFINETCode__c> fms = [SELECT Award__r.Grant__r.Program__r.ProgramName__c, Award__r.Grant__r.InternalOrganization__r.Name, Award__r.Grant__r.InternalOrganization__r.LEA_Id__c, Amount__c, MSPUniqueKeyFormula__c, ProgramCode__c, ObjectCode__c FROM AwardFINETCode__c WHERE Award__r.Grant__r.FiscalYear__c =:fb.FiscalYear__c AND Award__r.Grant__r.USBEPathway__c = :fb.recordType.Name AND Award__r.Status__c = 'Activated' ORDER BY DisplayOrder__c];
        List<MSPFinancialStage__c> fs = [SELECT Program__r.ProgramName__c, SubRecipient__r.Name, SubRecipient__r.LEA_Id__c, AwardAmount__c, UniqueKeyFormula__c, ProgramCode__c, ObjectCode__c FROM MSPFinancialStage__c WHERE FileBatch__c =:fb.Id ORDER BY DisplayOrder__c];
        Map<String, String> keyAmountMap = new Map<String, String>();
        for(AwardFINETCode__c fm : fms){
            keyAmountMap.put(fm.MSPUniqueKeyFormula__c, String.valueOf(fm.Amount__c));
        }

        List<AwardWrapper> stageWrapper = new List<AwardWrapper>();
        for(MSPFinancialStage__c f : fs){
            AwardWrapper temp = new AwardWrapper();
            temp.programName = f.Program__r.ProgramName__c;
            temp.subRecipientName = f.SubRecipient__r.Name;
            temp.awardAmount = f.AwardAmount__c;
            temp.uniqueKeyFormula = f.UniqueKeyFormula__c;
            temp.programCode = f.ProgramCode__c;
            temp.objectCode = f.ObjectCode__c;
            temp.leaId = f.SubRecipient__r.LEA_Id__c;
            temp.oldAwardAmount = keyAmountMap.get(f.UniqueKeyFormula__c) == null ? '0' : keyAmountMap.get(f.UniqueKeyFormula__c);
            stageWrapper.add(temp);
        }
        
        List<AwardWrapper> mainWrapper = new List<AwardWrapper>();
        /*
        for(AwardFINETCode__c fm : fms){
                AwardWrapper temp = new AwardWrapper();
                temp.programName = fm.Award__r.Grant__r.Program__r.ProgramName__c;
                temp.subRecipientName = fm.Award__r.Grant__r.InternalOrganization__r.Name;
                temp.awardAmount = String.valueOf(fm.Amount__c);
                temp.uniqueKeyFormula = fm.MSPUniqueKeyFormula__c;
                temp.programCode = fm.ProgramCode__c;
                temp.objectCode = fm.ObjectCode__c;
                temp.leaId = fm.Award__r.Grant__r.InternalOrganization__r.LEA_Id__c;
                mainWrapper.add(temp);
        }
        */
        System.debug('----------------->' + stageWrapper.size());
        System.debug('----------------->' + mainWrapper.size());
        results.put('stageJSON', JSON.serialize(stageWrapper));
        results.put('mainJSON', JSON.serialize(mainWrapper));
        return results;
    }

    public Map<String, List<String>> approve(FileBatch__c fbOld){
        Map<String, List<String>> results = new Map<String, List<String>>();
        results.put('Error', new List<String>());
        FileBatch__c fb = [SELECT Id, ActionType__c, FirstApprover__c, SecondApprover__c, FiscalYear__c, Status__c, RecordType.Name, ErrorLog__c FROM FileBatch__c WHERE Id = :fbOld.Id];
        if(fb.FirstApprover__c == UserInfo.getUserId() && fb.Status__c == 'Processed'){
            List<FileBatch__c> fbsSameYear = [SELECT Id FROM FileBatch__c WHERE FiscalYear__c = :fb.FiscalYear__c AND Id != :fb.Id AND Status__c IN ('Active') AND RecordType.Name = :fb.RecordType.Name];
            if(fbsSameYear.size() > 0 && fb.ActionType__c == 'Create'){
                results.get('Error').add('One create batch already active for this year');
                return results;
            }

            List<FileBatch__c> fbsApprovedSameYear = [SELECT Id FROM FileBatch__c WHERE FiscalYear__c = :fb.FiscalYear__c AND Id != :fb.Id AND Status__c IN ('Sent for Activation') AND RecordType.Name = :fb.RecordType.Name];
            if(fbsApprovedSameYear.size() > 0 && fb.ActionType__c == 'Amend'){
                results.get('Error').add('One amend batch already approved for this year');
                return results;
            }

            List<MSPFinancialStage__c> mfss = [SELECT Id, UniqueKeyFormula__c FROM MSPFinancialStage__c WHERE FileBatch__c = :fb.Id];
            List<AwardFINETCode__c> mfms = [SELECT Id, MSPUniqueKeyFormula__c FROM AwardFINETCode__c WHERE Award__r.Grant__r.FiscalYear__c =:fb.FiscalYear__c AND Award__r.Grant__r.USBEPathway__c = :fb.recordType.Name AND Award__r.Status__c = 'Activated'];
            List<String> validateStagingDataResult = validateStagingData(mfss);
            if(validateStagingDataResult.size() > 0){
                for(String str : validateStagingDataResult){    
                    results.get('Error').add('Duplicate unique key in Excel: ' + str);
                }
                return results;
            }

            if(!validateStaingMainMap(mfss, mfms) && fb.ActionType__c == 'Amend'){
                results.get('Error').add('Award is missing in Excel');
                return results;
            }

            //Database.executeBatch(new MSPMainCreateAndAmendBatch(fb), 200);
            updateBatchApprovalTask(fb);
            createAwardCreationTask(fb);
            fb.Status__c = 'Sent for Activation';
            update fb;
        }else if(fb.SecondApprover__c == UserInfo.getUserId() && fb.Status__c == 'Sent for Activation' && fb.ActionType__c != null){
            List<MSPFinancialStage__c> mfss = [SELECT Id, ProgramCode__c FROM MSPFinancialStage__c WHERE FileBatch__c = :fb.Id];
            List<String> finetCodeList = new List<String>();
            for(MSPFinancialStage__c mfs : mfss){
                if(!finetCodeList.contains(mfs.ProgramCode__c)){
                    finetCodeList.add(mfs.ProgramCode__c);
                }
            }
            finetCodeList.sort();
            Database.executeBatch(new MSPGrantCreateAndAmendValidateBatch(fb, finetCodeList, 0), 200);
            updateAwardCreationTask(fb);
            fb.Status__c = 'Processing';
            update fb;
        }else{
            results.get('Error').add('Please refresh page');
        }
        return results;
    }

    public Map<String, List<String>> reject(FileBatch__c fbOld){
        Map<String, List<String>> results = new Map<String, List<String>>();
        results.put('Error', new List<String>());
        FileBatch__c fb = [SELECT Id, ActionType__c, FirstApprover__c, SecondApprover__c, FiscalYear__c, Status__c, RecordType.Name FROM FileBatch__c WHERE Id = :fbOld.Id];
        if(fb.FirstApprover__c == UserInfo.getUserId() && fb.Status__c == 'Processed'){
            updateBatchApprovalTask(fb);
            fb.Status__c = 'Rejected';
        }else if(fb.SecondApprover__c == UserInfo.getUserId() && fb.Status__c == 'Sent for Activation'){
            updateAwardCreationTask(fb);
            fb.Status__c = 'Rejected';
        }else{
            results.get('Error').add('Please refresh page');
        }
        update fb;
        return results;
    }


    private void createAwardCreationTask(FileBatch__c fb){
        List<Task> awardCreationApprovalTask = GNT.TaskCreationHandler.createTasks(fb.SecondApprover__c,
            fb.Id,'MSP Award Creation Approval',
            fb.FiscalYear__c + ' ' + fb.ActionType__c, null, false, null,
            'Approval', fb.FiscalYear__c + ' ' + fb.ActionType__c, false
        );

        if(awardCreationApprovalTask != null && awardCreationApprovalTask.size() > 0) {
            insert awardCreationApprovalTask[0];
        }
    }

    private void updateBatchApprovalTask(FileBatch__c fb){
        List<Task> approvalTaskList = [SELECT Id, Status FROM Task WHERE WhatId = :fb.Id AND OwnerId = :UserInfo.getUserId() AND GNT__TaskAction__c = 'MSP Batch Approval'];
        if(approvalTaskList != null && approvalTaskList.size() > 0){
            for(Task t : approvalTaskList){
                t.Status = 'Completed';
            }
        }else{
            return;
        }
        update approvalTaskList;
    }

    private void updateAwardCreationTask(FileBatch__c fb){
        List<Task> creationTaskList = [SELECT Id, Status FROM Task WHERE WhatId = :fb.Id AND OwnerId = :UserInfo.getUserId() AND GNT__TaskAction__c = 'MSP Award Creation Approval'];
        if(creationTaskList != null && creationTaskList.size() > 0){
            for(Task t : creationTaskList){
                t.Status = 'Completed';
            }
        }else{
            return;
        }
        update creationTaskList;        
    }


    private List<String> validateStagingData(List<MSPFinancialStage__c> mfss){
        Boolean isValid = true;
        Set<String> keySets = new Set<String>();
        List<String> result = new List<String>();
        for(MSPFinancialStage__c mfs : mfss){
            if(!keySets.contains(mfs.UniqueKeyFormula__c)){
                keySets.add(mfs.UniqueKeyFormula__c);
            }else{
                isValid = false;
                result.add(mfs.UniqueKeyFormula__c);
            }
        }
        return result;
    }

    private Boolean validateStaingMainMap(List<MSPFinancialStage__c> mfss, List<AwardFINETCode__c> mfms){
        Boolean isValid = true;
        Set<String> mfsKeys = new Set<String>();
        for(MSPFinancialStage__c mfs : mfss){
            mfsKeys.add(mfs.UniqueKeyFormula__c);
        }

        for(AwardFINETCode__c mfm : mfms){
            if(!mfsKeys.contains(mfm.MSPUniqueKeyFormula__c)){
                isValid = false;
                break;
            }
        }
        return isValid;
    }


    class AwardWrapper{
        public String programName{get;set;}
        public String subRecipientName{get;set;}
        public String awardAmount{get;set;}
        public String uniqueKeyFormula{get;set;}
        public String programCode{get;set;}
        public String objectCode{get;set;}
        public String leaId{get;set;}
        public String oldAwardAmount{get;set;}
    }
}