UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <formula>Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UserRegistration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization/User Registration</label>
        <referenceTo>UserRegistration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/CommunityProfileConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ExternalRegistrationRecordType__c</fullName>
        <label>External Registration Record Type</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProfileName__c</fullName>
        <label>Profile Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Community Profile Config</label>
</CustomObject>

UtahLiveDataTest/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>UserName__c</fullName>
        <label>User Name</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>UserRegistration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Registration</label>
        <referenceTo>UserRegistration__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserRole__c</fullName>
        <description>This fields need to get updated as per the Formula Values  Vinayak 11/20/2015</description>
        <label>User Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>LEA BA</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>IsApplicant__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>TRUE ==&gt; Applicant
FALSE ==&gt; Reviewer</inlineHelpText>
        <label>Is Applicant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProfileName__c</fullName>
        <inlineHelpText>Logged in user profile name</inlineHelpText>
        <label>Profile Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/UserRegistration__c.object
<CustomObject>
    <description>[Business] Need more Detailed info from Swati Singh</description>
    <fields>
        <fullName>EINo__c</fullName>
        <inlineHelpText>An Employee Identification Number (EIN) is a nine-digit number provided by  Internal Revenue Service (IRS) which is often used by a business to open bank accounts, applying for business licenses, filing tax reports, filing electronic returns and taxes.</inlineHelpText>
        <label>Ob_Employee Identification Number (EIN)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <inlineHelpText>Enter valid email address.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ExternalReviewerAddress1__c</fullName>
        <label>External Reviewer Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalReviewerAddress2__c</fullName>
        <label>External Reviewer Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalReviewerCity__c</fullName>
        <label>External Reviewer City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalReviewerCountry__c</fullName>
        <defaultValue>&apos;USA&apos;</defaultValue>
        <description>Country name</description>
        <label>External Reviewer Country</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalReviewerEmail__c</fullName>
        <description>Enter reviewers&apos;s E-mail address. For example xyz@abc.com</description>
        <label>External Reviewer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ExternalReviewerFirstName__c</fullName>
        <label>External ReviewerFirst Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalReviewerLastName__c</fullName>
        <label>External Reviewer Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalReviewerPhone__c</fullName>
        <inlineHelpText>Reviewer&apos;s Official Phone number. Format is XXX-XXX-XXXX or XXX-XXX-XXXX ext XX</inlineHelpText>
        <label>External Reviewer Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ExternalReviewerPrefix__c</fullName>
        <label>External Reviewer Prefix</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mr.</fullName>
                </value>
                <value>
                    <fullName>Ms.</fullName>
                </value>
                <value>
                    <fullName>Mrs.</fullName>
                </value>
                <value>
                    <fullName>Dr.</fullName>
                </value>
                <value>
                    <fullName>Prof.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalReviewerState__c</fullName>
        <label>Physical State (Obsolete)</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalReviewerZipCode__c</fullName>
        <inlineHelpText>Format for zip code XXXXX or XXXXX - XXXX</inlineHelpText>
        <label>External Reviewer Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsApplicant__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Are you an Applicant?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <inlineHelpText>Registered Name as listed in DUN and BradStreet</inlineHelpText>
        <label>Organization Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryRepAddress1__c</fullName>
        <inlineHelpText>Applicant&apos;s Address</inlineHelpText>
        <label>Primary Rep Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryRepAddress2__c</fullName>
        <label>Primary Rep Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryRepCity__c</fullName>
        <label>Primary Rep City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryRepFirstName__c</fullName>
        <label>Primary Rep First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryRepLastName__c</fullName>
        <label>Primary Rep Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryRepPrefix__c</fullName>
        <label>Primary Rep Prefix</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mr.</fullName>
                </value>
                <value>
                    <fullName>Ms.</fullName>
                </value>
                <value>
                    <fullName>Mrs.</fullName>
                </value>
                <value>
                    <fullName>Dr.</fullName>
                </value>
                <value>
                    <fullName>Prof.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrimaryRepState__c</fullName>
        <label>Primary Rep State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <inlineHelpText>The Username must be in email format but the email format does not need to be a valid email address. For example xyz@abc.com</inlineHelpText>
        <label>User Name</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>UserRole__c</fullName>
        <label>User Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Project Admin</fullName>
                </value>
                <value>
                    <fullName>Project Director</fullName>
                </value>
                <value>
                    <fullName>Project Staff</fullName>
                </value>
                <value>
                    <fullName>Reviewer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>External Registration</label>
    <nameField>
        <displayFormat>RG-{000000}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Registration</pluralLabel>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <label>Applicant</label>
    </recordTypes>
    <recordTypes>
        <fullName>Reviewer</fullName>
        <active>true</active>
        <label>Reviewer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestUserRegistrationTriggerHelper.cls
/**
 
    **********************************************************
    Audit History
    **********************************************************
    4/27/2014   swati singh    Created
 
    **********************************************************  
*/
@isTest
private with sharing class TestUserRegistrationTriggerHelper {


    @IsTest(OnInstall=false)
    public static void test_ctrl() {
    
      UserTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
        TestHelper.CreateCustomSettings(true);
        UserRegistrationTriggerHelper.skipAfterUpdate = true;
        UserRegistration__c uReg = new UserRegistration__c();
        uReg.OrganizationName__c ='TestORG';
        uReg.LastName__c = 'Betty';
        uReg.username__c = System.now().millisecond() + 'test@123test.com';
        uReg.EINo__c = Math.Random();
        uReg.Email__c = 'test15@test.com';
        //uReg.RecordType.DeveloperName = 'Reviewer';
        uReg.Status__c = 'In Progress';
        uReg.RecordTypeId = Schema.SObjectType.UserRegistration__c.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();
        insert uReg;
        Test.startTest();
        uReg.Status__c = 'Approved';
        update uReg;
        Test.stopTest();

        //assert
        System.assertEquals(uReg.Id, uReg.Id);
        
        
        }
        
    }
    @IsTest(OnInstall=false)
    public static void test_ctrl108() {
      UserTriggerHelper.skipTrigger=false;
      UserRegistrationTriggerHelper.skipAfterUpdate=false;
      UserRegistrationTriggerHelper.skipBeforeUpdate=false;

        User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
        TestHelper.CreateCustomSettings(true);
        UserRegistrationTriggerHelper.skipAfterUpdate = true;
        UserRegistration__c uReg = new UserRegistration__c();
        uReg.OrganizationName__c ='TestORG';
        uReg.LastName__c = 'Betty';
        uReg.username__c = System.now().millisecond() + 'test@123test.com';
        uReg.EINo__c = Math.Random();
        uReg.Email__c = 'test15@test.com';
        //uReg.RecordType.DeveloperName = 'Reviewer';
        uReg.Status__c = 'In Progress';
        uReg.RecordTypeId = Schema.SObjectType.UserRegistration__c.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();
        insert uReg;
        Test.startTest();
        uReg.Status__c = 'Approved';
        update uReg;
        Test.stopTest();

        //assert
        System.assertEquals(uReg.Id, uReg.Id);
        
        
        }
    }
    
    @IsTest(OnInstall=false)
    public static void test_ctrl1() {
    /*
     UserRole portalRole = new UserRole();
     portalRole.PortalType ='None';
     portalRole.name ='abc';
     insert portalRole ;
     
        User u = TestHelper.getAdminUser(false);
        u.UserRoleId = portalRole.id;
        
        insert u;
        System.runAs(u) {
        TestHelper.CreateCustomSettings(true);
        UserRegistrationTriggerHelper.skipBeforeUpdate = true;
        UserRegistrationTriggerHelper.skipAfterUpdate= true;

        AccountTriggerHelper.skipTrigger = true;

        CommunityProfileConfig__c communityProfileConfig = new CommunityProfileConfig__c();
        communityProfileConfig.Name = 'Reviewer';
        communityProfileConfig.ExternalRegistrationRecordType__c = 'Reviewer';
        communityProfileConfig.ProfileName__c = 'SME';
        insert communityProfileConfig;

        UserRegistration__c uReg = new UserRegistration__c();
        uReg.OrganizationName__c ='TestORG';
        uReg.ExternalReviewerPrefix__c = 'Mr';
        uReg.ExternalReviewerFirstName__c = 'Betty';
        uReg.ExternalReviewerLastName__c = 'Ander';
        uReg.ExternalReviewerAddress1__c = '23 main street';
        uReg.ExternalReviewerAddress2__c = 'abc';
        uReg.ExternalReviewerCity__c = 'sterling';
        uReg.ExternalReviewerState__c = 'VA';
        uReg.ExternalReviewerZipCode__c ='23456-1546';
        uReg.ExternalReviewerCountry__c  = 'USA';
        uReg.ExternalReviewerPhone__c = '1234567890';
        uReg.ExternalReviewerEmail__c = 'swa@gmail.com';
        uReg.LastName__c = 'Betty';
        uReg.isApplicant__c = true;
        //uReg.UserRole__c = 'Project Director';
        uReg.username__c = System.now().millisecond() + 'test@123test.com';
        uReg.EINo__c = Math.Random();
        uReg.Email__c = 'test15@test.com';
        uReg.Status__c = 'In Progress';
        uReg.RecordTypeId = Schema.SObjectType.UserRegistration__c.getRecordTypeInfosByName().get('Reviewer').getRecordTypeId();
        insert uReg;

        

        Account acc = TestHelper.getAccount(false);
        acc.name = 'SME Reviewer System Account';
        insert acc;
        Account acc1 = TestHelper.getAccount(false);
        acc1.name = 'Individuals System Account';
        insert acc1;
        GNT__KeyValueStore__c key1= new GNT__KeyValueStore__c(Name='UniqueUsername',
                                                GNT__IntegerValue__c=1153,
                                                GNT__BooleanValue__c=true,
                                                GNT__Admin_Question__c = 'Loren Ipsum',
                                                GNT__Description__c='Email address to send feedback of the customer in real time');
        insert key1; 

        Test.startTest();
        uReg.Status__c = 'Approved';
        update uReg;
        Test.stopTest();

        //assert
        System.assertEquals(uReg.Id, uReg.Id);
        
        
        }
        */
    }
    
     @IsTest(OnInstall=false)
    public static void test_ctrl2() {
    /*
     UserRole portalRole = new UserRole();
     portalRole.PortalType ='None';
     portalRole.name ='abc';
     insert portalRole ;
     
        User u = TestHelper.getAdminUser(false);
        u.UserRoleId = portalRole.id;
        
        insert u;
        System.runAs(u) {
        TestHelper.CreateCustomSettings(true);
        UserRegistrationTriggerHelper.skipBeforeUpdate = true;
        UserRegistrationTriggerHelper.skipAfterUpdate= true;
        AccountTriggerHelper.skipTrigger = true;

        CommunityProfileConfig__c communityProfileConfig = new CommunityProfileConfig__c();
        communityProfileConfig.Name = 'Ind Applicant';
        communityProfileConfig.ExternalRegistrationRecordType__c = 'Ind Applicant';
        communityProfileConfig.ProfileName__c = 'SPI';
        insert communityProfileConfig;
        

        UserRegistration__c uReg = new UserRegistration__c();
        uReg.OrganizationName__c ='TestORG';
        uReg.PrimaryRepPrefix__c= 'Mr';
        uReg.PrimaryRepFirstName__c= 'Betty';
        uReg.PrimaryRepLastName__c= 'Ander';
        uReg.PrimaryRepAddress1__c= '23 main street';
        uReg.PrimaryRepAddress2__c= 'abc';
        uReg.PrimaryRepCity__c= 'sterling';
        //uReg.PrimaryRepState__c= 'VA';
        uReg.PrimaryRepZipCode__c='23456-1546';
        uReg.PrimaryRepCountry__c= 'USA';
        uReg.PrimaryRepPhone__c= '1234567890';
        uReg.PrimaryRepEmail__c= 'swati@gmail.com';
        uReg.LastName__c = 'Betty';
        uReg.isApplicant__c = true;
       
        //uReg.UserRole__c = 'Project Director';
        uReg.username__c = System.now().millisecond() + 'test@123test.com';
        uReg.EINo__c = Math.Random();
        uReg.Email__c = 'test15@test.com';
        uReg.Status__c = 'In Progress';
        uReg.RecordTypeId = Schema.SObjectType.UserRegistration__c.getRecordTypeInfosByName().get('Ind Applicant').getRecordTypeId();
        insert uReg;
        Account acc = TestHelper.getAccount(false);
        acc.name = 'SME Reviewer System Account';
        insert acc;
        Account acc1 = TestHelper.getAccount(false);
        acc1.name = 'Individuals System Account';
        insert acc1;
        GNT__KeyValueStore__c key1= new GNT__KeyValueStore__c(Name='UniqueUsername',
                                                GNT__IntegerValue__c=1153,
                                                GNT__BooleanValue__c=true,
                                                GNT__Admin_Question__c = 'Loren Ipsum',
                                                GNT__Description__c='Email address to send feedback of the customer in real time');
        insert key1; 

        Test.startTest();
        uReg.Status__c = 'Approved';
        update uReg;
        Test.stopTest();

        //assert
        System.assertEquals(uReg.Id, uReg.Id);
        
        
        }
        */
    }
    
    @IsTest(OnInstall=false)
    public static void test_ctrl3() {
    /*
     UserRole portalRole = new UserRole();
     portalRole.PortalType ='None';
     portalRole.name ='abc';
     insert portalRole ;
     
        User u = TestHelper.getAdminUser(false);
        u.UserRoleId = portalRole.id;
        
        insert u;
        System.runAs(u) {
        TestHelper.CreateCustomSettings(true);
        UserRegistrationTriggerHelper.skipBeforeUpdate = true;
        AccountTriggerHelper.skipTrigger = true;
        UserRegistrationTriggerHelper.skipAfterUpdate= true;

        CommunityProfileConfig__c communityProfileConfig = new CommunityProfileConfig__c();
        communityProfileConfig.Name = 'Reviewer';
        communityProfileConfig.ExternalRegistrationRecordType__c = 'Reviewer';
        communityProfileConfig.ProfileName__c = 'SME';
        insert communityProfileConfig;
        contact con = TestHelper.getContact(true);
        UserRegistration__c uReg = new UserRegistration__c();
        uReg.OrganizationName__c ='TestORG';
        uReg.ExternalReviewerPrefix__c = 'Mr';
        uReg.ExternalReviewerFirstName__c = 'Betty';
        uReg.ExternalReviewerLastName__c = 'Ander';
        uReg.ExternalReviewerAddress1__c = '23 main street';
        uReg.ExternalReviewerAddress2__c = 'abc';
        uReg.ExternalReviewerCity__c = 'sterling';
        uReg.ExternalReviewerState__c = 'VA';
        uReg.ExternalReviewerZipCode__c ='23456-1546';
        uReg.ExternalReviewerCountry__c  = 'USA';
        uReg.ExternalReviewerPhone__c = '1234567890';
        uReg.ExternalReviewerEmail__c = 'swa@gmail.com';
        uReg.LastName__c = 'Betty';
        uReg.isApplicant__c = true;
        //uReg.UserRole__c = 'Project Director';
        uReg.username__c = System.now().millisecond() + 'test@123test.com';
        uReg.EINo__c = Math.Random();
        uReg.Email__c = 'test15@test.com';
        uReg.Status__c = 'In Progress';
        uReg.contact__c = con.Id;
        uReg.RecordTypeId = Schema.SObjectType.UserRegistration__c.getRecordTypeInfosByName().get('Reviewer').getRecordTypeId();
        insert uReg;
        con.UserRegistration__c = uReg.Id;
        Update con;
        

        Account acc = TestHelper.getAccount(false);
        acc.name = 'SME Reviewer System Account';
        insert acc;
        Account acc1 = TestHelper.getAccount(false);
        acc1.name = 'Individuals System Account';
        insert acc1;
        GNT__KeyValueStore__c key1= new GNT__KeyValueStore__c(Name='UniqueUsername',
                                                GNT__IntegerValue__c=1153,
                                                GNT__BooleanValue__c=true,
                                                GNT__Admin_Question__c = 'Loren Ipsum',
                                                GNT__Description__c='Email address to send feedback of the customer in real time');
        insert key1; 

        Test.startTest();
        uReg.Status__c = 'Approved';
        update uReg;
        Test.stopTest();

        //assert
        System.assertEquals(uReg.Id, uReg.Id);
        }
        */
    }
    
    @IsTest(OnInstall=false)
    public static void test_ctrl4() {
    /*
     UserRole portalRole = new UserRole();
     portalRole.PortalType ='None';
     portalRole.name ='abc';
     insert portalRole ;
     
        User u = TestHelper.getAdminUser(false);
        u.UserRoleId = portalRole.id;
        
        insert u;
        System.runAs(u) {
        TestHelper.CreateCustomSettings(true);
        UserRegistrationTriggerHelper.skipBeforeUpdate = true;
        UserRegistrationTriggerHelper.skipAfterUpdate= true;
        AccountTriggerHelper.skipTrigger = true;

        CommunityProfileConfig__c communityProfileConfig = new CommunityProfileConfig__c();
        communityProfileConfig.Name = 'Reviewer';
        communityProfileConfig.ExternalRegistrationRecordType__c = 'Reviewer';
        communityProfileConfig.ProfileName__c = 'SPI';
        insert communityProfileConfig;
        Account acc2 = TestHelper.getAccount(true);

        contact con = TestHelper.getContact(false);
           con.accountId = acc2.Id;
           insert con;
        UserRegistration__c uReg = new UserRegistration__c();
        uReg.OrganizationName__c ='TestORG';
        uReg.PrimaryRepPrefix__c= 'Mr';
        uReg.PrimaryRepFirstName__c= 'Betty';
        uReg.PrimaryRepLastName__c= 'Ander';
        uReg.PrimaryRepAddress1__c= '23 main street';
        uReg.PrimaryRepAddress2__c= 'abc';
        uReg.PrimaryRepCity__c= 'sterling';
       // uReg.PrimaryRepState__c= 'VA';
        uReg.PrimaryRepZipCode__c='23456-1546';
        uReg.PrimaryRepCountry__c= 'USA';
        uReg.PrimaryRepPhone__c= '1234567890';
        uReg.PrimaryRepEmail__c= 'swati@gmail.com';
        uReg.LastName__c = 'Betty';
        uReg.isApplicant__c = true;
        uReg.Contact__c = con.Id;
        //uReg.UserRole__c = 'Project Director';
        uReg.username__c = System.now().millisecond() + 'test@123test.com';
        uReg.EINo__c = Math.Random();
        uReg.Email__c = 'test15@test.com';
        uReg.Status__c = 'In Progress';
        uReg.RecordTypeId = Schema.SObjectType.UserRegistration__c.getRecordTypeInfosByName().get('Additional Applicant').getRecordTypeId();
        insert uReg;
        con.UserRegistration__c = uReg.Id;
        Update con;
        Account acc = TestHelper.getAccount(false);
        acc.name = 'SME Reviewer System Account';
        insert acc;
        Account acc1 = TestHelper.getAccount(false);
        acc1.name = 'Individuals System Account';
        insert acc1;
        GNT__KeyValueStore__c key1= new GNT__KeyValueStore__c(Name='UniqueUsername',
                                                GNT__IntegerValue__c=1153,
                                                GNT__BooleanValue__c=true,
                                                GNT__Admin_Question__c = 'Loren Ipsum',
                                                GNT__Description__c='Email address to send feedback of the customer in real time');
        insert key1; 

        Test.startTest();
        uReg.Status__c = 'Approved';
        update uReg;
        Test.stopTest();

        //assert
        System.assertEquals(uReg.Id, uReg.Id);
        
        
        }
        */
    }
     /* @IsTest(OnInstall=false)
    public static void test_ctrl5() {
     UserRole portalRole = new UserRole();
     portalRole.PortalType ='None';
     portalRole.name ='abc';
     insert portalRole ;
     
        User u = TestHelper.getAdminUser(false);
        u.UserRoleId = portalRole.id;
        
        insert u;
        System.runAs(u) {
        TestHelper.CreateCustomSettings(true);
        UserRegistrationTriggerHelper.skipBeforeUpdate = true;
        UserRegistrationTriggerHelper.skipAfterUpdate= true;
        AccountTriggerHelper.skipTrigger = true;

        CommunityProfileConfig__c communityProfileConfig = new CommunityProfileConfig__c();
        communityProfileConfig.ProfileName__c = 'SPI';
        communityProfileConfig.ExternalRegistrationRecordType__c = 'Additional Applicant';
        communityProfileConfig.Name = 'Additional Applicant';
        insert communityProfileConfig;
        Account acc2 = TestHelper.getAccount(true);

        contact con = TestHelper.getContact(false);
           con.accountId = acc2.Id;
           insert con;
        UserRegistration__c uReg = new UserRegistration__c();
        uReg.OrganizationName__c ='TestORG';
        uReg.OrganizationStreetAddress__c= '23 main street';
        uReg.OrganizationStreet2Address__c= 'abc';
        uReg.OrganizationZipCode__c= '23456-1546';
        uReg.OrganizationCityAddress__c= 'abc';
        uReg.OrganizationState__c= 'sterling';
        uReg.LastName__c = 'Betty';
        uReg.isApplicant__c = true;
        uReg.Contact__c = con.Id;
        //uReg.UserRole__c = 'Project Director';
        uReg.username__c = System.now().millisecond() + 'test@123test.com';
        uReg.EINo__c = Math.Random();
        uReg.Email__c = 'test15@test.com';
        uReg.Status__c = 'In Progress';
        uReg.RecordTypeId = Schema.SObjectType.UserRegistration__c.getRecordTypeInfosByName().get('Additional Applicant').getRecordTypeId();

        insert uReg;
        con.UserRegistration__c = uReg.Id;
        Update con;
        Account acc = TestHelper.getAccount(false);
        acc.name = 'SME Reviewer System Account';
        insert acc;
        Account acc1 = TestHelper.getAccount(false);
        acc1.name = 'Individuals System Account';
        insert acc1;
        GNT__KeyValueStore__c key1= new GNT__KeyValueStore__c(Name='UniqueUsername',
                                                GNT__IntegerValue__c=1153,
                                                GNT__BooleanValue__c=true,
                                                GNT__Admin_Question__c = 'Loren Ipsum',
                                                GNT__Description__c='Email address to send feedback of the customer in real time');
        insert key1; 
        Test.startTest();
        uReg.Status__c = 'Approved';
        update uReg;
        Test.stopTest();
        System.assertEquals(uReg.Id, uReg.Id);
        }
    }*/
  }