UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A unique id to relate the announcement to the program.</description>
        <label>Program ID</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>- In Progress - The information within the annoucement is incomplete. Such records shall not be avaiable for other users to view or edit.
- Review In Progress - Annoucements that are currently in the process of undergoing review shall have this status. Such records shall not be avaiable for other users to view or edit.
- Inactive - Approved annoucements whose Posting Date is in the future shall have this status. Such annoucements shall not be made available to recipient users.
- Active - Approved annoucements whose Posting Date is equal to the current date or is in the past and the Closing Date is in the future shall have this status. System shall make such annoucements available to recipients.
- Expired - Approved annoucements whose closing date is the current date or is in the past shall have this status. When an annoucement status changes from Active to Expired, it should no longer be made available to the recipient users.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Converted to Application</fullName>
                </value>
                <value>
                    <fullName>Converted to Pre-Application</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Approved</fullName>
                </value>
                <value>
                    <fullName>RFA Published</fullName>
                </value>
                <value>
                    <fullName>RFA Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Review Initiated</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Submitted For Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Sent for Review</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision Completed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Rejection Initiated</fullName>
                </value>
                <value>
                    <fullName>Internally Reviewed</fullName>
                </value>
                <value>
                    <fullName>Converted to Award</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Converted to Grant</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Revision Initiated</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Approved Internally</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>End date of the program, to determine if it is a single or a multi year program</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Start date of the program</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/WBSTaskSchedule__c.object
<CustomObject>
    <description>[Business] Used to Store the Schedule of of Task in WBS Grid</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>WBS Task Schedule</relationshipLabel>
        <relationshipName>WBS_Task_Schedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>WBS Task Schedule</relationshipLabel>
        <relationshipName>WBS_Task_Schedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>WBS Task Schedule</label>
    <nameField>
        <label>WBSTaskSchedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WBS Task Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestApplicationWBSHelperClass.cls
@isTest
private class TestApplicationWBSHelperClass {
    
    @isTest static void testOnAfterTaskUpdateHandler() {
        Test.startTest();
        UserTriggerHelper.skiptrigger = true;
        Map<String, Object> temp = new Map<String, Object>();
        Map<String, Object> temp2 = new Map<String, Object>();
        WBSTaskSchedule__c ts = new WBSTaskSchedule__c();
        ApplicationWBSHelperClass programHelper = new ApplicationWBSHelperClass();
        UserTriggerHelper.skiptrigger = true;
        insert ts;
        temp2.put('id', ts.Id);
        temp2.put('text', 'test');
        User u = TestHelper.getAdminUser(true);
        temp2.put('owner', u.Id);
        temp2.put('description', 'test');
        temp2.put('milestone', true);
        temp2.put('progress', 5);
        temp2.put('status', 'Assigned');
        temp2.put('start_date', String.valueOf(Date.today() - 5));
        temp2.put('end_date', String.valueOf(Date.today()));
        temp2.put('duration', 5);
        temp.put('item', temp2);
        
        programHelper.keyValueMap = temp;

        temp.put('eventMethodname', 'onAfterTaskUpdate');
        Map<String, Object> result = programHelper.handleEvent();
        System.debug(result.get('Message'));
        Test.stopTest();

    }
    
    @isTest static void testOnAfterTaskDelete() {
        Test.startTest();
        UserTriggerHelper.skiptrigger = true;
        Map<String, Object> temp = new Map<String, Object>();
        Map<String, Object> temp2 = new Map<String, Object>();
        WBSTaskSchedule__c ts = new WBSTaskSchedule__c();
        ApplicationWBSHelperClass programHelper = new ApplicationWBSHelperClass();
        UserTriggerHelper.skiptrigger = true;
        insert ts;
        temp2.put('id', ts.Id);
        temp2.put('text', 'test');
        User u = TestHelper.getAdminUser(true);
        temp2.put('owner', u.Id);
        temp2.put('description', 'test');
        temp2.put('milestone', true);
        temp2.put('progress', 5);
        temp2.put('status', 'Assigned');
        temp2.put('start_date', String.valueOf(Date.today() - 5));
        temp2.put('end_date', String.valueOf(Date.today()));
        temp2.put('duration', 5);
        temp.put('item', temp2);
        
        programHelper.keyValueMap = temp;

        temp.put('eventMethodname', 'onAfterTaskDelete');
        Map<String, Object> result = programHelper.handleEvent();
        System.debug(result.get('Message'));
        Test.stopTest();

    }
    @isTest static void testOnAfterTaskAdd() {
    /*
        Test.startTest();
        AccountTriggerHelper.skiptrigger = true;
        ProgramTriggerHelper.skiptrigger = true;
        ApplicationTriggerHelper.skiptrigger = true;
        Account account = TestHelper.getAccount(true);
        Program__c program = TestHelper.getProgram(account.Id, true);
        Announcement__c announcement = TestHelper.getAnnouncement(true);
        Application__c application = TestHelper.getApplication(announcement.Id, true);
        UserTriggerHelper.skiptrigger = true;
        Map<String, Object> temp = new Map<String, Object>();
        Map<String, Object> temp2 = new Map<String, Object>();
        Map<String, Object> temp3 = new Map<String, Object>();
        Map<String, Object> temp4 = new Map<String, Object>();
        WBSTaskSchedule__c ts = new WBSTaskSchedule__c();
        WBSTaskSchedule__c ts1 = new WBSTaskSchedule__c();
        ApplicationWBSHelperClass programHelper = new ApplicationWBSHelperClass();
        UserTriggerHelper.skiptrigger = true;
        insert ts;
        insert ts1;
        String str = '{"programid" :"' + application.Id + '"}';
        temp2.put('parent', ts1.Id);
        temp2.put('id', ts.Id);
        temp2.put('text', 'test');
        User u = TestHelper.getAdminUser(true);
        temp2.put('owner', u.Id);
        temp2.put('description', 'test');
        temp2.put('milestone', true);
        temp2.put('progress', 5);
        temp2.put('status', 'Assigned');
        temp2.put('start_date', String.valueOf(Date.today() - 5));
        temp2.put('end_date', String.valueOf(Date.today()));
        temp2.put('duration', 5);
        temp2.put('wbsno', 'test');
        temp.put('item', temp2);
        temp.put('paramtersMap', str);
        temp.put('idMapper', temp4);
        
        programHelper.keyValueMap = temp;

        temp.put('eventMethodname', 'onAfterTaskAdd');
        Map<String, Object> result = programHelper.handleEvent();
        System.debug(result.get('Message'));
        Test.stopTest();
*/
    }
    @isTest static void testAfterLinkAddHandler() {
    /*
        Test.startTest();
        AccountTriggerHelper.skiptrigger = true;
        ProgramTriggerHelper.skiptrigger = true;
        Account account = TestHelper.getAccount(true);
        Program__c program = TestHelper.getProgram(account.Id, true);
        UserTriggerHelper.skiptrigger = true;
        Map<String, Object> temp = new Map<String, Object>();
        Map<String, Object> temp2 = new Map<String, Object>();
        Map<String, Object> temp3 = new Map<String, Object>();
        Map<String, Object> temp4 = new Map<String, Object>();
        WBSTaskSchedule__c ts = new WBSTaskSchedule__c();
        WBSTaskSchedule__c ts1 = new WBSTaskSchedule__c();
        ApplicationWBSHelperClass programHelper = new ApplicationWBSHelperClass();
        UserTriggerHelper.skiptrigger = true;
        insert ts;
        insert ts1;
        String str = '{"programid" :"' + program.Id + '"}';
        temp2.put('parent', ts1.Id);
        temp2.put('id', ts.Id);
        temp2.put('text', 'test');
        User u = TestHelper.getAdminUser(true);
        temp2.put('owner', u.Id);
        temp2.put('description', 'test');
        temp2.put('milestone', true);
        temp2.put('progress', 5);
        temp2.put('status', 'Assigned');
        temp2.put('start_date', String.valueOf(Date.today() - 5));
        temp2.put('end_date', String.valueOf(Date.today()));
        temp2.put('duration', 5);
        temp2.put('wbsno', 'test');
        
        temp2.put('source', ts.Id);
        temp2.put('target', ts1.Id);
        temp4.put('source', ts.Id);
        temp4.put('target', ts1.Id);

        temp.put('item', temp2);
        temp.put('paramtersMap', str);
        temp.put('idMapper', temp4);
        
        programHelper.keyValueMap = temp;

        temp.put('eventMethodname', 'onAfterLinkAdd');
        Map<String, Object> result = programHelper.handleEvent();
        System.debug(result.get('Message'));
        Test.stopTest();
*/
    }
    @isTest static void testPublishTasks() {
    /*
        Test.startTest();
        User u = TestHelper.getAdminUser(true);
        System.runAs(u){
        AccountTriggerHelper.skiptrigger = true;
        ProgramTriggerHelper.skiptrigger = true;
        Account account = TestHelper.getAccount(true);
        Program__c program = TestHelper.getProgram(account.Id, true);
        UserTriggerHelper.skiptrigger = true;
        Map<String, Object> temp = new Map<String, Object>();
        Map<String, Object> temp2 = new Map<String, Object>();
        Map<String, Object> temp3 = new Map<String, Object>();
        Map<String, Object> temp4 = new Map<String, Object>();
        
        WBSTaskSchedule__c ts = new WBSTaskSchedule__c(Name = 'test', Status__c = 'Created', OwnerId = u.Id, 
            StartDate__c = Date.today() - 5, EndDate__c = Date.today()
            );
        WBSTaskSchedule__c ts1 = new WBSTaskSchedule__c();
        ApplicationWBSHelperClass programHelper = new ApplicationWBSHelperClass();
        UserTriggerHelper.skiptrigger = true;
        insert ts;
        insert ts1;
        String str = '{"programid" :"' + program.Id + '"}';
        temp2.put('parent', ts1.Id);
        temp2.put('id', ts.Id);
        temp2.put('text', 'test');
        
        temp2.put('owner', u.Id);
        temp2.put('description', 'test');
        temp2.put('milestone', true);
        temp2.put('progress', 5);
        temp2.put('status', 'Assigned');
        temp2.put('start_date', String.valueOf(Date.today() - 5));
        temp2.put('end_date', String.valueOf(Date.today()));
        temp2.put('duration', 5);
        temp2.put('wbsno', 'test');
        
        temp2.put('source', ts.Id);
        temp2.put('target', ts1.Id);
        temp4.put('source', ts.Id);
        temp4.put('target', ts1.Id);

        temp.put('item', temp2);
        temp.put('paramtersMap', str);
        temp.put('idMapper', temp4);
        
        programHelper.keyValueMap = temp;

        temp.put('eventMethodname', 'publishTasks');
        
            Map<String, Object> result = programHelper.handleEvent();
            System.debug(result.get('Message'));
        }
        Test.stopTest();
*/
    }
    @isTest static void testException() {
        Test.startTest();
        ApplicationWBSHelperClass programHelper = new ApplicationWBSHelperClass();
        Map<String, Object> temp = new Map<String, Object>();
        programHelper.keyValueMap = temp;
        temp.put('eventMethodname', 'onAfterTaskAdd');
        Map<String, Object> result = programHelper.handleEvent();
        System.debug(result.get('Message'));
        Test.stopTest();

    }
    @isTest static void testException2() {
        Test.startTest();
        ApplicationWBSHelperClass programHelper = new ApplicationWBSHelperClass();
        Map<String, Object> temp = new Map<String, Object>();
        programHelper.keyValueMap = temp;
        temp.put('eventMethodname', 'onAfterTaskUpdate');
        Map<String, Object> result = programHelper.handleEvent();
        System.debug(result.get('Message'));
        Test.stopTest();

    }
    @isTest static void testException3() {
        Test.startTest();
        ApplicationWBSHelperClass programHelper = new ApplicationWBSHelperClass();
        Map<String, Object> temp = new Map<String, Object>();
        programHelper.keyValueMap = temp;
        temp.put('eventMethodname', 'onAfterTaskDelete');
        Map<String, Object> result = programHelper.handleEvent();
        System.debug(result.get('Message'));
        Test.stopTest();

    }

    @isTest static void testException5() {
        Test.startTest();
        ApplicationWBSHelperClass programHelper = new ApplicationWBSHelperClass();
        Map<String, Object> temp = new Map<String, Object>();
        programHelper.keyValueMap = temp;
        temp.put('eventMethodname', 'publishTasks');
        Map<String, Object> result = programHelper.handleEvent();
        System.debug(result.get('Message'));
        Test.stopTest();

    }
    
}