UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IsExtensionAllowed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This filed is being used on grantor ---&gt; planning --&gt;  manage recipient</description>
        <label>Is Extension Allowed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <formula>Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Recipient</fullName>
        <active>true</active>
        <description>This is a Partner Account</description>
        <label>Recipient</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>ApplicationCreated__c</fullName>
        <formula>NOT(NumberOfApplications__c &gt; 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Application Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplicationDeadlineWithDateTime__c</fullName>
        <label>Application Deadline</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ExtensionDays__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Defines extension days for application deadline</description>
        <inlineHelpText>Defines extension days for application deadline</inlineHelpText>
        <label>ExtensionDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FunderType__c</fullName>
        <label>Funder Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Federal</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>NGO</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MaxApplicationsAllowed__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Maximum # Applications Allowed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <formula>Organization__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A unique id to relate the announcement to the program.</description>
        <label>Program ID</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RFARequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RFA Required?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>- In Progress - The information within the annoucement is incomplete. Such records shall not be avaiable for other users to view or edit.
- Review In Progress - Annoucements that are currently in the process of undergoing review shall have this status. Such records shall not be avaiable for other users to view or edit.
- Inactive - Approved annoucements whose Posting Date is in the future shall have this status. Such annoucements shall not be made available to recipient users.
- Active - Approved annoucements whose Posting Date is equal to the current date or is in the past and the Closing Date is in the future shall have this status. System shall make such annoucements available to recipients.
- Expired - Approved annoucements whose closing date is the current date or is in the past shall have this status. When an annoucement status changes from Active to Expired, it should no longer be made available to the recipient users.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Converted to Application</fullName>
                </value>
                <value>
                    <fullName>Converted to Pre-Application</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Approved</fullName>
                </value>
                <value>
                    <fullName>RFA Published</fullName>
                </value>
                <value>
                    <fullName>RFA Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TimeExtensionAllowed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Time Extension allowed for announcement to eligible applications?</description>
        <inlineHelpText>Is Time Extension allowed for announcement to eligible applications?</inlineHelpText>
        <label>Time Extension Allowed</label>
        <type>Checkbox</type>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <description>Announcement type is based on Application that user is logged in</description>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApplicationDeadlineWithDateTime__c</fullName>
        <description>This field is created because the current field is a Formula fild , Need to delete one of them later on</description>
        <label>Application Deadline</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Review Initiated</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Submitted For Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Sent for Review</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision Completed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Rejection Initiated</fullName>
                </value>
                <value>
                    <fullName>Internally Reviewed</fullName>
                </value>
                <value>
                    <fullName>Converted to Award</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Converted to Grant</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Revision Initiated</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Approved Internally</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <description>Application Created by the user in State as Grantor App</description>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/OpportunityQualification__c.object
<CustomObject>
    <description>[Business] This is for a Sub Recipient to Mark an Announcement so that after some days he or she can create an application for the same announcement. This is created because there might be lots of announcement but sub recipient might be interested with only few announcement so he/she can mark it as qualified and later convert into an application</description>
    <fields>
        <fullName>FundingOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>Opportunity_Sub_Recipient_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(FundingOpportunity__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Qualified Announcements</label>
    <nameField>
        <displayFormat>FO-{0000}</displayFormat>
        <label>Qualified Announcement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualified Announcements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>FunderType__c</fullName>
        <label>Funder Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Federal</fullName>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>NGO</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <formula>Account__r.Name</formula>
        <label>Organization Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>GNT__OrganizationId__c</fullName>
        <description>Organization to which a user is tied to. It is applicable for both internal and external users</description>
        <label>Organization Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/CreateApplicationHelper.cls
global with sharing class CreateApplicationHelper extends GNT.DynamicLayoutActionRedirect {

  Id announcementId;

  global override PageReference whenClicked() {


    Id recordId = layoutHolder.getPrimarySObject().Id;
    //  String hostVal  = ApexPages.currentPage().getHeaders().get('Host');
    //  System.debug('hostVal  ' +hostVal  );
    //  String urlvalue = Apexpages.currentPage().getUrl();
    // System.debug('urlvalue1' +urlvalue);
    String ns = AppUtils.getNamespacePrefix();
    //Id applicationId = apexpages.currentpage().getparameters().get('id');
    Integer appCount, maxAppCount;
    System.debug('The record Id is ' + recordId);
    String appName = GNT.UserPreferenceHelper.getStringValue('ActiveAppName__c');
    User u = [select AccountId, GNT__OrganizationId__c, Contact.Account.IsExtensionAllowed__c from User where id = :Userinfo.getUserId()];
    if (appName == 'Recipient') {
      announcementId = apexpages.currentpage().getparameters().get('announcementid');
      //*************************Leons code

      Announcement__c announcementObj = [Select Program__c from Announcement__c where Id = :announcementId limit 1];
      //Id programId=announcementObj.Program__c;
      //System.debug('*****************PROGID'+programId);
      //List<Program__c> program=new List<Program__c>();
      SystemContextMethodsHelper sysCnt = new SystemContextMethodsHelper();
      List<Program__c> program = sysCnt.getProgramIds(announcementObj.Program__c);
      //List<Program__c> program= [Select id from Program__c where id =:announcementObj.Program__c LIMIT 1];
      Program__c prog = sysCnt.getProgramfields(program);
      //Program__c prog=[Select FunderType__c,OrganizationName__c from Program__c where id IN:program LIMIT 1];
      Id account = u.AccountId;
      //system.debug('account id is ' +account);
      
      /*
      System.debug('program has organization name ' + prog.OrganizationName__c );
      if ( (prog.OrganizationName__c == 'USBE')) {
        if (prog.FunderType__c == 'Federal') {
          checkFederalAssurances(account);

        }

        else if (prog.FunderType__c == 'State') {
          checkStateAssurances(account);
        }
      }

      */

      //*********************************Leons code
    }

    else if (appName == 'StateasGrantee') {
      announcementId = apexpages.currentpage().getparameters().get('id');
    }
    Boolean HideSubmit = true;
    Announcement__c announcementObj = [Select Program__c, RFARequired__c, Status__c, ApplicationDeadlineWithDateTime__c, ExtensionDays__c, TimeExtensionAllowed__c from Announcement__c where Id = :announcementId limit 1];

    DateTime d = DateTime.newInstance(announcementObj.ApplicationDeadlineWithDateTime__c.year(), announcementObj.ApplicationDeadlineWithDateTime__c.month(), announcementObj.ApplicationDeadlineWithDateTime__c.day(), announcementObj.ApplicationDeadlineWithDateTime__c.hour(), announcementObj.ApplicationDeadlineWithDateTime__c.minute(), announcementObj.ApplicationDeadlineWithDateTime__c.second());
    if (u.Contact.Account.IsExtensionAllowed__c == true && announcementObj.TimeExtensionAllowed__c == true) {
      if (d + Integer.valueOf(announcementObj.ExtensionDays__c ) > DateTime.parse(System.now().format())) {
        HideSubmit = false;
      }
    } else {
      if (d > DateTime.parse(System.now().format())) {
        HideSubmit = false;
      }
    }

    if (HideSubmit) {
      // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Application cannot be created after deadline'));
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-31596')));
      return null;
    }

    if (announcementObj.RFARequired__c == True) {
      if (announcementObj.Status__c != 'RFA Published') {
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Cannot create an Application without the publication of RFA'));
        return null;
      }
    }

    if (appName == 'Recipient') {
      OpportunityQualification__c qualifiedAnnouncement = [Select Id, FundingOpportunity__r.Name, FundingOpportunity__c, FundingOpportunity__r.MaxApplicationsAllowed__c, ApplicationCreated__c, PreApplicationCreated__c, IsPreapplicationSubmitted__c , IsPreApplicationRequired__c, FundingOpportunity__r.AllowMultipleApplicationsFromOrg__c from OpportunityQualification__c where id = :recordId limit 1];
      if (qualifiedAnnouncement.IsPreApplicationRequired__c == true && qualifiedAnnouncement.IsPreapplicationSubmitted__c == false) {
        // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Pre-Application needs to be submitted before creating an application'));
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-46251')));
        return null;
      }
      GNT__UserPreferences__c userPrefs = GNT__UserPreferences__c.getValues(UserInfo.getUserId());
      List<Application__c> appList = [Select Id, Name from Application__c where Announcement__c = :qualifiedAnnouncement.FundingOpportunity__c and ExternalOrganization__c = :userPrefs.GNT__OrganizationAccountId__c];
      if (appList != null &&  appList.size() > 0) {
        appCount = appList.size();
      } else {
        appCount = 0;
      }
      if (qualifiedAnnouncement.FundingOpportunity__r.MaxApplicationsAllowed__c != null && qualifiedAnnouncement.FundingOpportunity__r.MaxApplicationsAllowed__c > 0) {
        maxAppCount = (Integer)qualifiedAnnouncement.FundingOpportunity__r.MaxApplicationsAllowed__c;
      } else {
        maxAppCount = 1;
      }

      if (maxAppCount <= appCount) {
        // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Application cannot be created as you have reached the maximum limit for allowed applications for '+qualifiedAnnouncement.FundingOpportunity__r.Name));
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-74572') + ' ' + qualifiedAnnouncement.FundingOpportunity__r.Name));
        return null;
      }
      if ((qualifiedAnnouncement.FundingOpportunity__r.AllowMultipleApplicationsFromOrg__c == true) || (qualifiedAnnouncement.FundingOpportunity__r.AllowMultipleApplicationsFromOrg__c == false && qualifiedAnnouncement.ApplicationCreated__c == false)) {
        String hostval =  EncodingUtil.urlEncode('/apex/QualifiedOpportunityView?announcementid=' + qualifiedAnnouncement.FundingOpportunity__c + '&id=' + qualifiedAnnouncement.Id, 'UTF-8');

        /* qualifiedAnnouncement.ApplicationCreated__c =true;
         qualifiedAnnouncement.OpportunityStatus__c='Converted to Application';
         update qualifiedAnnouncement; */
        return new PageReference('/apex/' + ns + 'ApplicationEdit?announcementId=' + qualifiedAnnouncement.FundingOpportunity__c + '&retURL=' + hostVal);
      } else {
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, GNT.ErrorMessageHelper.fetchMessage('P02-GRNTR-70031')));
        return null;
      }
    }
    if (appName == 'StateasGrantee') {
      List<Application__c> applicationList = [SELECT Id, Status__c FROM Application__c WHERE Announcement__c = : recordId AND CreatedBy.GNT__OrganizationId__c = :u.GNT__OrganizationId__c ]; //CreatedById =: Userinfo.getUserId()];
      if (applicationList.size() == 0) {
        return new PageReference('/apex/' + ns + 'ApplicationEdit?announcementId=' + recordId + '&t=GranteeApplication' );
      }
      //List<Application__c> applst = [SELECT Id,Status__c FROM Application__c WHERE Id =: applicationId AND CreatedBy.GNT__OrganizationId__c =:u.GNT__OrganizationId__c ];
      //if(applst.size()>0){
      //    if(applst[0].Status__c =='Approved'){
      //        applst[0].Status__c ='Submitted to Grantor';
      //        update applst[0];
      //    }
      //    if(applst[0].Status__c =='Submitted to Grantor'){
      //        applst[0].Status__c ='Accepted';
      //        update applst[0];
      //    }
      //     PageReference page = new PageReference('/apex/'+ns+'ApplicationView?id=' + applst[0].id);
      //     page.setRedirect(true);
      //     return page;
      //}
    }
    return null;
  }

  private void checkFederalAssurances(Id account) {
    List<GNT__AttachmentExtension__c> attachements = [SELECT id, GNT__Classification__c, Year__c FROM GNT__AttachmentExtension__c where GNT__ParentId__c = :account];
    Integer currentYear = System.Today().year();
    Integer count = 0;
    String a = String.ValueOf(currentYear);
    for (GNT__AttachmentExtension__c b : attachements) {
      if (b.Year__c != a && b.GNT__Classification__c != 'Federal Assurance') {
        continue;
      } else {
        count++;
      }

    }

    if (count != 1) {
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Cannot create an Application as there needs to be exactly one Federal Assurance Form uploaded for the current year. Please refer to the hyperlink displayed in the attachements tab of your organization profile to download the form and attach a single copy'));

    }

  }

  private void checkStateAssurances(Id account) {
    List<GNT__AttachmentExtension__c> attachements = [SELECT id, GNT__Classification__c, Year__c FROM GNT__AttachmentExtension__c where GNT__ParentId__c = :account];
    Integer currentYear = System.Today().year();
    Integer count = 0;
    String a = String.ValueOf(currentYear);
    for (GNT__AttachmentExtension__c b : attachements) {
      if (b.Year__c != a && b.GNT__Classification__c != 'State Assurance') {
        continue;
      } else {
        count++;
      }

    }

    if (count != 1) {
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Cannot create an Application as there needs to be exactly one State Assurance Form uploaded for the current year. Please refer to the hyperlink displayed in the attachements tab of your organization profile to download the form and attach a single copy'));

    }

  }

}