UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>BudgetCategory__c</fullName>
        <description>Is Budget Category needed at Individual or Total Level?</description>
        <label>Budget Category Required?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget Category Level</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Overall Level</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <description>Announcement type is based on Application that user is logged in</description>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AnnouncementServiceArea__c.object
<CustomObject>
    <description>[Business]  Service Area associated with an Annoucement</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>RelatedServiceAreas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BudgetPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Period</label>
        <referenceTo>BudgetPeriod__c</referenceTo>
        <relationshipLabel>Funding Opportunity Project Areas</relationshipLabel>
        <relationshipName>Funding_Opportunity_Project_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Area</label>
        <referenceTo>ServiceArea__c</referenceTo>
        <relationshipName>AnnouncementServiceAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <formula>ServiceArea__r.Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Title</label>
        <type>Text</type>
    </fields>
    <label>Funding Opportunity Project Area</label>
    <nameField>
        <displayFormat>ASA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Opportunity Project Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApplicationType__c</fullName>
        <description>The type of application.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Continuation</fullName>
                </value>
                <value>
                    <fullName>Revision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalOrganization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Orgnanization which owns the Application This field is also used on the Forms as well</description>
        <inlineHelpText>Which organization owns the application?</inlineHelpText>
        <label>Applicant Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FedBizOps__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fed Biz Ops</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications12</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectDirector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the external user who is directing the project</inlineHelpText>
        <label>Project Director/Principle Investigator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The grantee entered title for the application.</description>
        <label>Project Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <description>Application Created by the user in State as Grantor App</description>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BudgetCategory__c.object
<CustomObject>
    <description>[Business] This object stores the Master List of all the Budget categories</description>
    <fields>
        <fullName>CategoryDescription__c</fullName>
        <label>Category Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RowNumber__c</fullName>
        <label>Row Number</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RowsNumber__c</fullName>
        <label>Row Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>MST: Budget Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Category</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BudgetPeriod__c.object
<CustomObject>
    <description>[Business] This object stores all Budget Period Details.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Budget Periods</relationshipLabel>
        <relationshipName>Budget_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BudgetPeriod__c</fullName>
        <formula>IF(AND(NOT(ISBLANK(BudgetStartDate__c )),NOT(ISBLANK(BudgetEndDate__c))),TEXT(MONTH( BudgetStartDate__c ))+&quot;/&quot; +TEXT(DAY(BudgetStartDate__c))+&quot;/&quot; +TEXT(YEAR(BudgetStartDate__c))+&quot;--&quot;+ TEXT(MONTH( BudgetEndDate__c ))+&quot;/&quot; +TEXT(DAY(BudgetEndDate__c))+&quot;/&quot; +TEXT(YEAR(BudgetEndDate__c)),&apos;&apos;)</formula>
        <label>Budget Period</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FundingOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Budget Periods</relationshipLabel>
        <relationshipName>Budget_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget Period</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Budget Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingOpportunityBudgetCategory__c.object
<CustomObject>
    <description>[Business]  This is for capturing Budget Category for FO.</description>
    <fields>
        <fullName>BudgetCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Category</label>
        <referenceTo>BudgetCategory__c</referenceTo>
        <relationshipLabel>Funding Opportunity Budget Categories</relationshipLabel>
        <relationshipName>Funding_Opportunity_Budget_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BudgetPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Period</label>
        <referenceTo>BudgetPeriod__c</referenceTo>
        <relationshipLabel>Funding Opportunity Budget Categories</relationshipLabel>
        <relationshipName>Funding_Opportunity_Budget_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FundingOpportunity__c</fullName>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Funding Opportunity Budget Categories</relationshipLabel>
        <relationshipName>Funding_Opportunity_Budget_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RowNumber__c</fullName>
        <formula>BudgetCategory__r.RowsNumber__c</formula>
        <label>Row Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Funding Opportunity Budget Category</label>
    <nameField>
        <displayFormat>FOBC-{000}</displayFormat>
        <label>Funding Opportunity Budget Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Opportunity Budget Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RolesAndResponsibilities__c.object
<CustomObject>
    <description>[Business] Roles and Responsibilities defined for all the objects like Opportunity ,Application etc</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Area</label>
        <referenceTo>ServiceArea__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>RolesandResponsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Roles and Responsibilities</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles and Responsibilities</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Application.</description>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ServiceArea__c.object
<CustomObject>
    <description>[Business] Master list of all the Service Area information is stored in this object , Service areas are also applicable to the Announcements ,Programs,Application via Junction objects</description>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a default service Area for any entity</description>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project/Service Area</label>
    <nameField>
        <displayFormat>PSA-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestApplicationTriggerHelper.cls
/**
* @author: Sarat Mahavratayajula 2016-21-07
*/
@isTest
public class TestApplicationTriggerHelper {
    
        static testMethod void testApplicationTrigger2(){
        
         UserTriggerHelper.skipTrigger = true;
         User u3 = TestHelper.getAdminUser(true); 
         ServiceArea__c serviceArea = null;
        // AnnouncementServiceArea__c annServiceArea=null;
         BudgetPeriod__c budPeriod = null;
         Application__c app = null;
      
         System.runAs(u3){   
            Test.startTest();
            ProgramTriggerHelper.skipTrigger=true;
            //GNT.TriggerHelper.skipTrigger=true;
            RolesAndResponsibilitiesTriggerHelper.skipTrigger=true;
            AnnouncementTriggerHelper.skipTrigger = true;
            TaskTriggerHelper.skipTrigger = true;
            ReviewPanelTriggerHelper.skipTrigger = true;
            Announcement__c ann = TestHelper.getAnnouncement(true);

            BudgetCategory__c bc = new BudgetCategory__c(Name = 'Indirect Costs', CategoryDescription__c = 'Indirect Costs', RowNumber__c = '213', RowsNumber__c = 213);
            insert bc;

            AnnouncementServiceArea__c annServiceArea = new AnnouncementServiceArea__c(Announcement__c = ann.Id);
            insert annServiceArea;

            serviceArea = new ServiceArea__c(Title__c='Application Project Area',Default__c = true);
            insert serviceArea;

            BudgetPeriod__c budgetPeriod = new BudgetPeriod__c(FundingOpportunity__c=ann.Id);
            insert budgetperiod;

            FundingOpportunityBudgetCategory__c funOporBudCat = new FundingOpportunityBudgetCategory__c(FundingOpportunity__c=ann.Id);
            insert funOporBudCat;

            //Application__c app = TestHelper.getApplication(ann.Id,true);
            GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c','StateasGrantor');
            Account acct=TestHelper.getAccount(true);
            app = new Application__c();
            app.Announcement__c = ann.Id;
            app.Name = 'APP-001';
            app.ApplicationType__c = 'TBD';
            app.ExternalOrganization__c=acct.id;
            app.ProjectDirector__c = u3.Id;
            app.FedBizOps__c=u3.id;
            GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c','StateasGrantor');
            List<Application__c> lst=new List<Application__c>();
            lst.add(app);
            insert lst;

            app.Status__c='Submitted';
            app.ChangeRequestStatus__c='Change Request Accepted';
            GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c','StateasGrantor');
            update app;

            budPeriod = new BudgetPeriod__c(FundingOpportunity__c=app.Announcement__c);
            budPeriod.SupportYear__c='1992';
            budPeriod.BudgetEndDate__c= Date.newInstance(2018,05,18);
            budPeriod.BudgetStartDate__c=Date.newInstance(1992,05,16);
            budPeriod.Status__c='Open';
            budPeriod.SequenceNumber__c=1.0;
            insert budPeriod;

            }
             
             GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c','StateasGrantor');
             GNT.UserPreferenceHelper.setStringValue('ProfileName__c','Applicant');
             ApplicationTriggerHelper appTrigHelp = new ApplicationTriggerHelper();
             Test.stopTest();                
    }

    @isTest
    static void sometest2() {
    /*
        // Skip unwanted triggers
        ProgramTriggerHelper.skipTrigger=true;
        AnnouncementTriggerHelper.skipTrigger = true;
        TaskTriggerHelper.skipTrigger=true;
        AccountTriggerHelper.skipTrigger=true;
        RolesandResponsibilitiesTriggerHelper.skipTrigger = true;
        UserTriggerHelper.skipTrigger = true;
        User u3 = TestHelper.getAdminUser(true);

        System.runAs(u3){
            
            Account account=TestHelper.getAccount(true);
            Contact contact = new Contact(Firstname='FirstName1', Lastname='LastNam1e',Email='email1@email.com', 
                                            Title='Title',Phone ='123-123-1234',Account=account);
            insert contact;
            Announcement__c ann = TestHelper.getAnnouncement(true);
            //ann.ApplicationDeadlineWithDateTime__c = datetime.newInstance(2018,06,15,20,00,00);
           
            
           //  update ann;

            AnnouncementServiceArea__c annServiceArea = new AnnouncementServiceArea__c(Announcement__c = ann.Id);
            insert annServiceArea;


            ServiceArea__c serviceArea = new ServiceArea__c(Default__c=true);
            insert serviceArea;

            RolesAndResponsibilities__c rolesAndResponsibilities = new RolesAndResponsibilities__c();
            rolesAndResponsibilities.BusinessRole__c= 'Owner';
            rolesAndResponsibilities.Announcement__c = ann.Id;
            insert rolesAndResponsibilities;

            BudgetPeriod__c budgetPeriod = new BudgetPeriod__c(FundingOpportunity__c=ann.Id);
            insert budgetperiod;
            //Shivankar: Putting the start test here to deal with SOQL query limit being hit. 
            Test.startTest();
            FundingOpportunityBudgetCategory__c funOporBudCat = new FundingOpportunityBudgetCategory__c(FundingOpportunity__c=ann.Id);
            insert funOporBudCat;

            Application__c app = new Application__c(Announcement__c = ann.Id, Name = 'APP-001',ApplicationType__c = 'Continuation',
                                     ExternalOrganization__c = account.Id,Status__c='Submitted', ApplicationDeadlineWithDateTime__c = DateTime.now() +  30);
            List<Application__c> lst=new List<Application__c>();
            lst.add(app);
            insert lst;

            app.Status__c='Submitted to Grantor';
            app.ChangeRequestStatus__c='Change Request Accepted';
            GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c','StateasGrantee');
            GNT.UserPreferenceHelper.setStringValue('ProfileName__c','Applicant');
            update app;

            
                GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c','StateasGrantee');
                GNT.UserPreferenceHelper.setStringValue('ProfileName__c','Applicant');
                ApplicationTriggerHelper applicationTriggerHelper = new ApplicationTriggerHelper();
                //Announcement__c ann=TestHelper.getAnnouncement(true);
            Application__c app2=TestHelper.getApplication(ann.id,true);
                
                //insert lst;
                Test.stopTest();
                delete lst;
            
            GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c','StateasGrantee');
            delete app2;
        }
        */
    } 

}