UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Final Approver for the Award</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awards4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GrantAwardName__c</fullName>
        <label>Award Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GranteePOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grantee POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awards_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent to Grantee Review</fullName>
                </value>
                <value>
                    <fullName>Grantee Accepted</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>FINOPS Completed</fullName>
                </value>
                <value>
                    <fullName>Sent to FINOPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <recordTypes>
        <fullName>Grantee</fullName>
        <active>true</active>
        <description>This Classifies whether it is Grantor or Grantee</description>
        <label>Grantee</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>GranteePOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grantee POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Grants1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProgramCode</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed/Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <recordTypes>
        <fullName>Grantee</fullName>
        <active>true</active>
        <label>Grantee</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RolesAndResponsibilities__c.object
<CustomObject>
    <description>[Business] Roles and Responsibilities defined for all the objects like Opportunity ,Application etc</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>RolesandResponsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to populate the Program to which this Role and and Responsibility belongs</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Sent For Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StrategicPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Strategic Plan</label>
        <referenceTo>StrategicPlan__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Roles and Responsibilities</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles and Responsibilities</pluralLabel>
    <recordTypes>
        <fullName>Award</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Award.</description>
        <label>Award</label>
    </recordTypes>
    <recordTypes>
        <fullName>Grant</fullName>
        <active>true</active>
        <label>Grant</label>
    </recordTypes>
    <recordTypes>
        <fullName>StrategicPlan</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Strategic Plan and Service Area.</description>
        <label>Strategic Plan</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/StrategicPlan__c.object
<CustomObject>
    <description>[Business] Defines the Strategic plan for an Organization which owns the Application</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Strategic Plan</label>
    <nameField>
        <displayFormat>SPN-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestSubAwardeeReviewHelper.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestSubAwardeeReviewHelper {

   static testMethod void myUnitTest() {
   /*
       UserTriggerHelper.skipTrigger=true;
       User u = TestHelper.getAdminUser(true);
       Account acct = null;
       Program__c pgm = null;
        
       System.runAs(u) {
           GrantTriggerHelper.skipTrigger = true;
           AwardTriggerHelper.skipTrigger = true;
           RolesAndResponsibilitiesTriggerHelper.skipTrigger = true;
           AccountTriggerHelper.skipTrigger = true;
           TaskTriggerHelper.skipTrigger=true;
           GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
           system.debug('-------------Entering Grant creation-------------');
            
           Grant__c grant = TestHelper.getGrant(true);
           grant.GranteePOC__c = u.Id;
           update grant;
            
           system.debug('Grant ID is : ' + grant.Id);
           //StrategicPlan__c strategicPlan = TestHelper.getStrategicPlan(true);  
           acct=TestHelper.getAccount(true);    
           pgm = TestHelper.getProgram(acct.Id,true);     
            
           Award__c award = TestHelper.getAwards(grant.Id,true);
           award.GrantAwardName__c= 'Sample Award Name';
           award.Approver__c = u.Id;
           award.Status__c='Sent to Grantee Review';
           update award;
            
           RolesAndResponsibilities__c rolesAndResponsibilities = TestHelper.getRolesAndResponsibilities(true,pgm.Id);           
           //award.Status__c = 'Sent to Grantee Review';
           //update award;
           system.debug('Award ID is : ' + award.id);
           
           Test.startTest(); 
           ApexPages.currentPage().getParameters().put('Id', award.Id); 
           SubAwardeeReviewHelper subAwardeeReviewHelper = new SubAwardeeReviewHelper();
           subAwardeeReviewHelper.whenClicked();
           Test.stopTest();
        }
        */
    }
        

    
    static testMethod void myUnitTest2() {
    /*
        UserTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(true);
        Account acct = null;
        Program__c pgm = null;
        
        System.runAs(u) {
            GrantTriggerHelper.skipTrigger = true;
            AwardTriggerHelper.skipTrigger = true;
            RolesAndResponsibilitiesTriggerHelper.skipTrigger = true;
            AccountTriggerHelper.skipTrigger = true;
            TaskTriggerHelper.skipTrigger=true;
            GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
            system.debug('-------------Entering Grant creation-------------');
            
            Grant__c grant = TestHelper.getGrant(true);
            grant.GranteePOC__c = u.Id;
            update grant;
            
            system.debug('Grant ID is : ' + grant.Id);
            //StrategicPlan__c strategicPlan = TestHelper.getStrategicPlan(true);  
            acct=TestHelper.getAccount(true);    
            pgm = TestHelper.getProgram(acct.Id,true);     
            
            Award__c award = TestHelper.getAwards(grant.Id,true);
            award.GrantAwardName__c= 'Sample Award Name';
            award.Approver__c = u.Id;
            award.Status__c='Approved';
            update award;
            
            RolesAndResponsibilities__c rolesAndResponsibilities = TestHelper.getRolesAndResponsibilities(true,pgm.Id);           
            //award.Status__c = 'Sent to Grantee Review';
            //update award;
            system.debug('Award ID is : ' + award.id);
            
            ApexPages.currentPage().getParameters().put('Id', award.Id);
            
            SubAwardeeReviewHelper subAwardeeReviewHelper = new SubAwardeeReviewHelper();
            subAwardeeReviewHelper.whenClicked();
        }
        */
    }
    
       static testMethod void myUnitTest3() {
       /*
           UserTriggerHelper.skipTrigger=true;
           User u = TestHelper.getAdminUser(true);
           Account acct = null;
           Program__c pgm = null;
        
           System.runAs(u) {
               GrantTriggerHelper.skipTrigger = true;
               AwardTriggerHelper.skipTrigger = true;
               RolesAndResponsibilitiesTriggerHelper.skipTrigger = true;
               AccountTriggerHelper.skipTrigger = true;
               TaskTriggerHelper.skipTrigger=true;
               GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
               system.debug('-------------Entering Grant creation-------------');
            
               Grant__c grant = TestHelper.getGrant(true);
               grant.GranteePOC__c = u.Id;
               update grant;
            
               system.debug('Grant ID is : ' + grant.Id);
               //StrategicPlan__c strategicPlan = TestHelper.getStrategicPlan(true);  
               acct=TestHelper.getAccount(true);    
               pgm = TestHelper.getProgram(acct.Id,true);     
            
               Award__c award = TestHelper.getAwards(grant.Id,true);
               award.GrantAwardName__c= 'Sample Award Name';
               award.Approver__c = u.Id;
               award.Status__c='Grantee Accepted';
               update award;
            
               RolesAndResponsibilities__c rolesAndResponsibilities = TestHelper.getRolesAndResponsibilities(true,pgm.Id);           
               //award.Status__c = 'Sent to Grantee Review';
               //update award;
               system.debug('Award ID is : ' + award.id);
            
               Test.startTest();
               ApexPages.currentPage().getParameters().put('Id', award.Id);
               SubAwardeeReviewHelper subAwardeeReviewHelper = new SubAwardeeReviewHelper();
               subAwardeeReviewHelper.whenClicked();
               Test.stopTest();
        }
        */
    }
    
        static testMethod void myUnitTest4() {
        /*
            UserTriggerHelper.skipTrigger=true;
            User u = TestHelper.getAdminUser(true);
            Account acct = null;
            Program__c pgm = null;
        
            System.runAs(u) {
                GrantTriggerHelper.skipTrigger = true;
                AwardTriggerHelper.skipTrigger = true;
                RolesAndResponsibilitiesTriggerHelper.skipTrigger = true;
                AccountTriggerHelper.skipTrigger = true;
                TaskTriggerHelper.skipTrigger=true;
                GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
                system.debug('-------------Entering Grant creation-------------');
            
                Grant__c grant = TestHelper.getGrant(true);
                grant.GranteePOC__c = u.Id;
                update grant;
            
                system.debug('Grant ID is : ' + grant.Id);
                //StrategicPlan__c strategicPlan = TestHelper.getStrategicPlan(true);  
                acct=TestHelper.getAccount(true);    
                pgm = TestHelper.getProgram(acct.Id,true);     
                Award__c award = TestHelper.getAwards(grant.Id,true);
                RolesAndResponsibilities__c rolesAndResponsibilities = TestHelper.getRolesAndResponsibilities(true,pgm.Id);           

                Test.startTest();
                ApexPages.currentPage().getParameters().put('Id', award.Id);
                SubAwardeeReviewHelper subAwardeeReviewHelper = new SubAwardeeReviewHelper();
                subAwardeeReviewHelper.whenClicked();
                Test.stopTest();
        }
        */
    }
}