UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <formula>Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>External</fullName>
        <active>true</active>
        <description>This is an External Account such as Federal Grants</description>
        <label>External</label>
    </recordTypes>
    <recordTypes>
        <fullName>Recipient</fullName>
        <active>true</active>
        <description>This is a Partner Account</description>
        <label>Recipient</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>AnnouncementType__c</fullName>
        <description>Announcement Type</description>
        <inlineHelpText>Type of Announcement</inlineHelpText>
        <label>Announcement Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Competitive</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Sole Source/Directed</fullName>
                </value>
                <value>
                    <fullName>Formula Grants</fullName>
                </value>
                <value>
                    <fullName>Sole Source/Formula</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FOAPublicationDate__c</fullName>
        <label>FOA Publication Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FOAStatus__c</fullName>
        <label>FOA Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FundingOppURL__c</fullName>
        <label>External Announcement URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <formula>Organization__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreApplicationNeeded__c</fullName>
        <label>PreApplication Needed</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Required</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Required</fullName>
                </value>
                <value>
                    <fullName>Recommended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFAStatus__c</fullName>
        <label>RFA Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>- In Progress - The information within the annoucement is incomplete. Such records shall not be avaiable for other users to view or edit.
- Review In Progress - Annoucements that are currently in the process of undergoing review shall have this status. Such records shall not be avaiable for other users to view or edit.
- Inactive - Approved annoucements whose Posting Date is in the future shall have this status. Such annoucements shall not be made available to recipient users.
- Active - Approved annoucements whose Posting Date is equal to the current date or is in the past and the Closing Date is in the future shall have this status. System shall make such annoucements available to recipients.
- Expired - Approved annoucements whose closing date is the current date or is in the past shall have this status. When an annoucement status changes from Active to Expired, it should no longer be made available to the recipient users.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Converted to Application</fullName>
                </value>
                <value>
                    <fullName>Converted to Pre-Application</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Approved</fullName>
                </value>
                <value>
                    <fullName>RFA Published</fullName>
                </value>
                <value>
                    <fullName>RFA Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BusinessPackage__c.object
<CustomObject>
    <description>[Business]  This object associates the Package with the Program or Opportunity</description>
    <fields>
        <fullName>FundingOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PackageType__c</fullName>
        <label>Package Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Pre-Application</fullName>
                </value>
                <value>
                    <fullName>App-Review</fullName>
                </value>
                <value>
                    <fullName>Award</fullName>
                </value>
                <value>
                    <fullName>Amendment Request</fullName>
                </value>
                <value>
                    <fullName>Progress Report</fullName>
                </value>
                <value>
                    <fullName>Site Visit</fullName>
                </value>
                <value>
                    <fullName>Payment Request</fullName>
                </value>
                <value>
                    <fullName>Closeout</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Risk Assessment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Business Package</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>KeyContact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is the check box created to identify the key primary contact for an organization</description>
        <label>KeyContact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReviewerStatus__c</fullName>
        <description>Status field for all types of contacts. Discussed with Shiva and have not created a new status field re using reviewerStatus__c as status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invitation Sent</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UserRole__c</fullName>
        <description>This fields need to get updated as per the Formula Values  Vinayak 11/20/2015</description>
        <label>User Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>LEA BA</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RolesAndResponsibilities__c.object
<CustomObject>
    <description>[Business] Roles and Responsibilities defined for all the objects like Opportunity ,Application etc</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BusinessRole__c</fullName>
        <description>This is a picklist which will be displayed in RR table in all phases.</description>
        <label>Business Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BusinessRole</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Sent For Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Roles and Responsibilities</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles and Responsibilities</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Application.</description>
        <label>Application</label>
    </recordTypes>
    <recordTypes>
        <fullName>PreApplication</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Pre-Application.</description>
        <label>PreApplication</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/SoleSourceAwardRecipient__c.object
<CustomObject>
    <description>[Business] Need to revisit this object (It may not be required and can be DOH specific)</description>
    <fields>
        <fullName>FundingOpportunity__c</fullName>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Sole Source Award Recipients</relationshipLabel>
        <relationshipName>Sole_Source_Award_Recipients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sole Source Award Recipient</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sole Source Award Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <formula>FirstName + &quot; &quot; + LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileName__c</fullName>
        <inlineHelpText>Logged in user profile name</inlineHelpText>
        <label>Profile Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/PublishFOA.cls
global with sharing class PublishFOA extends GNT.DynamicLayoutActionRedirect {

    global override PageReference whenClicked() {

        Id recordId = apexpages.currentpage().getparameters().get('id');
        List<String> errors = new List<String>();
        try {
            Savepoint sp = Database.setSavepoint();
            Announcement__c ann = [Select Id, Name, OrganizationName__c, FundingOppURL__c, AnnouncementType__c, FOAPublicationDate__c, PreApplicationNeeded__c, FOAStatus__c, RFAStatus__c, Status__c from Announcement__c where id = : recordId Limit 1];
            List<RolesAndResponsibilities__c> rrList = new List<RolesAndResponsibilities__c>();
            if (ann.OrganizationName__c == 'UOVC') {
                rrList = [Select Id, Name__c from RolesAndResponsibilities__c where Announcement__c = :ann.Id and (BusinessRole__c LIKE '%Approver%' OR BusinessRole__c IN ('Owner')) and Name__c = :UserInfo.getUserId()];
            }


            else if (ann.OrganizationName__c == 'USBE') {
                Id user = UserInfo.getUserId();
                User u = [Select id, ProfileName__c from User where id = : user];
                rrList = [Select Id, Name__c from RolesAndResponsibilities__c where Announcement__c = :ann.Id and (BusinessRole__c = 'Grants Manager'  OR BusinessRole__c IN ('Owner')) AND Name__c != null and Name__c = :UserInfo.getUserId() and Name__r.ProfileName__c='GMO'];
            }

            Date foaPublishDate = Date.valueOf(ann.FOAPublicationDate__c);
            boolean checkRequiredDoc = checkFOAPresent(recordId);

            if (rrList != null && rrList.size() == 0) {
                errors.add('You do not have sufficient access to Publish the Announcement');
                //errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-89651'));
            }
            if (ann.FundingOppURL__c == null) {
                // errors.add('Please Enter External Announcement URL before publishing FOA');
                // errors.add(GNT.ErrorMessageHelper.fetchMessage('P51-GRNTR-40263'));
            }

            // Check App-Review Packages
            List<BusinessPackage__c> pkgList = [Select Id, PackageType__c from BusinessPackage__c where FundingOpportunity__c = :recordId and PackageType__c = 'Pre-Application'];

            if ( (ann.PreApplicationNeeded__c == 'Required' ||  ann.PreApplicationNeeded__c == 'Recommended') && (pkgList == null || pkgList.size() == 0)) {
                //errors.add('Please associate a Package with PreApplication Package Type for the Announcement.');
                errors.add(GNT.ErrorMessageHelper.fetchMessage('P51-GRNTR-65384'));
            }

            if (System.today() < foaPublishDate) {
                errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-41945') + ' ' + foaPublishDate.format());
            }
            if (errors.size() > 0) {
                for (String error : errors) {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, error));
                }
            } else {
                ann.FOAStatus__c = 'Published';
                ann.Status__c = 'Published';
                ann.RFAStatus__c = 'Created';
                if (ann.RFAStatus__c == 'Published') {
                    ann.Status__c = 'Active';
                } else {
                    ann.Status__c = 'Published';
                }
                update ann ;

                // Send email notiications to all users
                notifyUsers(ann);

                //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Announcement published successfully.'));
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('P51-GRNTR-93993')));
                PageReference  pageref = Page.AnnouncementView;
                pageref.getParameters().put('Id', recordId);
                pageref.setRedirect(true);
                return pageref;
            }

        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }
        return null;
    }

    private boolean checkFOAPresent(Id parentId) {
        List<GNT__AttachmentExtension__c> attachmentExt = [select GNT__Classification__c from GNT__AttachmentExtension__c where GNT__ParentId__c  like :parentId];
        Set<String> classifications = new Set<String>();
        for (GNT__AttachmentExtension__c attachmetExtn : attachmentExt) {
            classifications.add(attachmetExtn.GNT__Classification__c.toLowerCase().trim());
        }
        if (!classifications.contains('foa')) {
            return false;
        }
        return true;
    }

    private Boolean notifyUsers(Announcement__c announcement) {
        String[] toAddresses = new String[] {};
        List<Contact> contactList = new List<Contact>();
        if (announcement.AnnouncementType__c == 'Competitive') {
            // For Competitive Announcements
            contactList = [select Id, name, Email from Contact where Account.RecordType.DeveloperName = 'Recipient' and KeyContact__c = true and UserRole__c = 'Primary' and ReviewerStatus__c = 'Active'];
        } else if (announcement.AnnouncementType__c == 'Sole Source/Directed') {
            // For Sole Source/Directed Annoucements
            List<SoleSourceAwardRecipient__c> ssAwardRecipientList = [Select Id, Account__c from SoleSourceAwardRecipient__c where FundingOpportunity__c = : announcement.id];
            Set<Id> recipientIdSet = new Set<Id>();
            for (SoleSourceAwardRecipient__c ss : ssAwardRecipientList) {
                recipientIdSet.add(ss.Account__c);
            }
            contactList = [select Id, name, Email from Contact where Account.RecordType.DeveloperName = 'Recipient' and KeyContact__c = true and UserRole__c = 'Primary' and ReviewerStatus__c = 'Active' and Account.Id in :recipientIdSet ];
        } else {
            return false;
        }

        for (Contact ct : contactList) {
            toAddresses.add(ct.email);
        }
        EmailTemplate templateId = [Select id from EmailTemplate where developername = 'AnnouncementPublished'];
        Contact cont = [select id, Email from Contact where email <> null limit 1];
        Map<Id, String[]> recIdToAddressMap = new Map<Id, String[]> ();
        recIdToAddressMap.put(announcement.Id, toAddresses);
        try {
            // AppUtils.sendEmailUsingTemplate(templateId.Id, recIdToAddressMap, cont.Id, false);
        } catch (Exception exc) {
            system.debug(exc);
            //throw new CustomExceptions.RequiredException('An Error occured in notifying the Applicants');
            throw new CustomExceptions.RequiredException(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-38725'));
        }
        return false;
    }
}