UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FOALead__c.object
<CustomObject>
    <description>[Business] Opportunities imported from Grants.gov in to this object for Grantee Functionality</description>
    <fields>
        <fullName>FundingOppURL__c</fullName>
        <label>Link to Additional Information</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <inlineHelpText>1 - NA
2 - Low
3 - Medium
4 - High
5 - Very High</inlineHelpText>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - NA</fullName>
                </value>
                <value>
                    <fullName>2 - Low</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>3 - Medium</fullName>
                </value>
                <value>
                    <fullName>4 - High</fullName>
                </value>
                <value>
                    <fullName>5 - Very High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Justification__c</fullName>
        <label>Justification</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RecipientAgency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recipient Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>FOA Leads (Recipient Agency)</relationshipLabel>
        <relationshipName>RecipientAgency</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relevance__c</fullName>
        <inlineHelpText>1 - NA 
2 - Low 
3 - Medium 
4 - High 
5 - Very High</inlineHelpText>
        <label>Relevance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - NA</fullName>
                </value>
                <value>
                    <fullName>2 - Low</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>3 - Medium</fullName>
                </value>
                <value>
                    <fullName>4 - High</fullName>
                </value>
                <value>
                    <fullName>5 - Very High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SourceStatus__c</fullName>
        <label>Source Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Lead</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Qualified Lead</fullName>
                </value>
                <value>
                    <fullName>Rejected Lead</fullName>
                </value>
                <value>
                    <fullName>Converted to Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StrategicPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Strategic Plan</label>
        <referenceTo>StrategicPlan__c</referenceTo>
        <relationshipLabel>FOA Leads</relationshipLabel>
        <relationshipName>FOA_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FOA Lead</label>
    <nameField>
        <displayFormat>LD-{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FOA Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/StrategicPlan__c.object
<CustomObject>
    <description>[Business] Defines the Strategic plan for an Organization which owns the Application</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Strategic Plan</label>
    <nameField>
        <displayFormat>SPN-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestConvertToAnnouncementHelper.cls
@isTest(seealldata=true)
private class TestConvertToAnnouncementHelper {
   static testMethod void whenClicked() {
     /*
       FOALead__c fOALead = null;
       User u = new User(Id=UserInfo.getUserId());
        
        System.runAs(u){
            GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
             AccountTriggerHelper.skipTrigger=true;
             AnnouncementTriggerHelper.skipTrigger=true;
            fOALead = TestHelper.getFOALead(true);
        }
        
        Test.startTest();
        ConvertToAnnouncementHelper convertToAnnouncementHelper = new ConvertToAnnouncementHelper();
        ApexPages.currentPage().getParameters().put('Id', fOALead.Id);
        convertToAnnouncementHelper.whenClicked();
        Test.stopTest();
        */
    }
    
    static testMethod void whenClicked2() {
    /*
     
       FOALead__c fOALead = null;
       Account acct = null;
       User u = new User(Id=UserInfo.getUserId());
        
        System.runAs(u){
            GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
             AccountTriggerHelper.skipTrigger=true;
             AnnouncementTriggerHelper.skipTrigger=true;
            acct = TestHelper.getAccount(true);
            fOALead = new FOALead__c(FundingOppURL__c='/apex/testPageUrl',SourceStatus__c='Open',
                                            Status__c='New Lead',StrategicPlan__c=TestHelper.getStrategicPlan(true).id,
                                            Justification__c='Sample Justification',
                                            RecipientAgency__c=acct.Id,Impact__c='5 - Very High',Relevance__c='5 - Very High');
            insert fOALead;
            
            
        }
        
        Test.startTest();
        ConvertToAnnouncementHelper convertToAnnouncementHelper = new ConvertToAnnouncementHelper();
        ApexPages.currentPage().getParameters().put('Id', fOALead.Id);   
        convertToAnnouncementHelper.whenClicked();
        Test.stopTest();
        */
    }
    
  /*  static testMethod void createAnnouncement(){
        FOALead__c fOALead = null;
        User u = new User(Id=UserInfo.getUserId());
        
        System.runAs(u){
            GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
            AccountTriggerHelper.skipTrigger=true;
            AnnouncementTriggerHelper.skipTrigger=true;
            fOALead = TestHelper.getFOALead(true);
        }
        
        Test.startTest();
        ConvertToAnnouncementHelper convertToAnnouncementHelper = new ConvertToAnnouncementHelper();
        ApexPages.currentPage().getParameters().put('Id', fOALead.Id);
        convertToAnnouncementHelper.createAnnouncement(fOALead);
        Test.stopTest();
    
    }*/
  
}