UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Reviewers</fullName>
        <active>true</active>
        <description>All the reviewers will be belong to this account</description>
        <label>Reviewers</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ReviewerStatus__c</fullName>
        <description>Status field for all types of contacts. Discussed with Shiva and have not created a new status field re using reviewerStatus__c as status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invitation Sent</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SecurityToken__c</fullName>
        <label>Security Token</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ReviewerInvitationCtrl.cls
/*  This class is to send an Invitation Email to Person Account SME Reviewers
    **********************************************************
    Audit History
    **********************************************************
    08/12/2015           Shrawan Rain              Created
    **********************************************************  
*/
public without sharing class ReviewerInvitationCtrl implements GNT.invokeEmailActionInterface {
    public Id recordId {get;set;}
    public String email {get; set;}
    public String emailTemplateName {get; set;}
    
    public Id targetId {get;set;}
    public String isBulkMode {get;set;}
    public Boolean isUser {get;set;}
    public ReviewerInvitationCtrl() {
        recordId = ApexPages.currentPage().getParameters().get('id');
        isBulkMode = ApexPages.currentPage().getParameters().get('bulkMode');
        System.debug('recordId--->>>'+recordId);
        fetchEmailCtrlData(recordId);   
    }
    
    public ReviewerInvitationCtrl getThis() {
        if(isBulkMode != 'true'){
            return this;    
        }else {
            return null;
        }
    }
    
    public void fetchEmailCtrlData(Id recordId){
        if(recordId != null && isBulkMode != 'true'){
            List<Contact> con = [SELECT Id, Email,accountid,account.parentId FROM Contact where Id =: recordId];
            if(con[0].account.parentId == null){
            emailTemplateName = 'AdditionalUserEmail';
            } else if(con[0].account.parentId != null) {
            emailTemplateName = 'ChildOrgUserEmail';
            }
            
            System.debug('con---->>>>'+con);
            if(con.size() > 0){
                email = con[0].Email;
                targetId = con[0].Id;
            }
        }
    }
    
    public String actionToInvokeBefore() {
        String message = '';
        String soql = 'SELECT Id, SecurityToken__c FROM Contact WHERE Id =: recordId LIMIT 1';
        Contact con = Database.query(soql);        
        System.debug('con---->>>'+con);        
        if(con != null){
            if(con.SecurityToken__c == null || con.SecurityToken__c == ''){
                con.SecurityToken__c = GNT.AppUtils.generateToken(32);
                System.debug('con.SecurityToken__c--->>>'+con.SecurityToken__c);
            }
            try{
                //update con;
                message = 'success';
            }
            catch(DMLException e){
                message = 'error';
                System.debug('The following exception has occured : ' + e.getMessage());
            }
        }
        return message;        
    }
    
    public String actionToInvokeAfter() {            
        String message = '';
        String soql = 'SELECT Id, ReviewerStatus__c FROM Contact WHERE Id =: recordId LIMIT 1';
        Contact con = Database.query(soql);        
        if(con != null){
            con.ReviewerStatus__c = 'Invitation Sent';
            try{
                update con;
                message = 'success';
            }
            catch(DMLException e){
                message = 'error';
                System.debug('The following exception has occured : ' + e.getMessage());
            }
        }
        return message;           
    }   
}