UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodEndDate__c</fullName>
        <description>Project Period End Date for the award.</description>
        <label>Project Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodStartDate__c</fullName>
        <description>Project Period Start Date for the award.</description>
        <label>Project Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent to Grantee Review</fullName>
                </value>
                <value>
                    <fullName>Grantee Accepted</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>FINOPS Completed</fullName>
                </value>
                <value>
                    <fullName>Sent to FINOPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Stores the award amendment</description>
        <formula>if (AmendmentSequence__c==0,&apos;NEW&apos;,&apos;Amendment&apos;+TEXT(AmendmentSequence__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProgramCode</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodEndDate__c</fullName>
        <label>Project Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodStartDate__c</fullName>
        <label>Project Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed/Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/TermCondition__c.object
<CustomObject>
    <description>[Business] Terms and Conditions for Grants ,Awards (The lookup to Package may not be required in this case )</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DueDateDays__c</fullName>
        <inlineHelpText>How many days after the end of the reporting period?</inlineHelpText>
        <label>Due Date Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FixedEndDate__c</fullName>
        <description>The date starting when the term becomes inactive.</description>
        <inlineHelpText>The date starting when the term becomes inactive. This field gets populated only if &apos;Report End Date&apos; is &apos;Fixed&apos;</inlineHelpText>
        <label>Fixed End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FixedStartDate__c</fullName>
        <description>The date starting when the term becomes active.</description>
        <inlineHelpText>The date starting when the term becomes active. This field gets populated only if &apos;Report Start Date&apos; is &apos;Fixed&apos;.</inlineHelpText>
        <label>Fixed Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                    <default>true</default>
                    <label>Fixed</label>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReportStartDate__c</fullName>
        <description>Used for Post Award Submission Report creation</description>
        <inlineHelpText>Budget Period Start Date - The reporting cycle should start from current Budget Period Start Date
Fixed Date - start from a fixed date</inlineHelpText>
        <label>Beginning Date</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget Period Start Date</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Active, Inactive. If the Effective Date is current or in the past and if the Inactive On date is in the future, the Term is Active. If the Inactive Date is in the past, the term is Inactive. Prepopulated. Read Only.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TaskAvailability__c</fullName>
        <description>The task will be made available to the grantee &apos;X&apos; number of days before the due date, based on the number entered here.</description>
        <inlineHelpText>Enter number of days prior to Due Date</inlineHelpText>
        <label>Task Availability</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>State</fullName>
                    <default>true</default>
                    <label>State</label>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Grant</fullName>
                </value>
                <value>
                    <fullName>Award</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MST:Term and Condition</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <recordTypes>
        <fullName>Condition</fullName>
        <active>true</active>
        <label>Condition</label>
    </recordTypes>
    <recordTypes>
        <fullName>Term</fullName>
        <active>true</active>
        <description>Related to Awards ( Ramu to rename this object appropriately)</description>
        <label>Term</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestTermConditionEditCtrl.cls
@isTest
private class  TestTermConditionEditCtrl{
    
    static TermCondition__c obj; 
    static TermConditionEditCtrl tcEditCtrl;
    static Grant__c grant; 
    static Award__c award; 
    static Program__c program; 
    
    private static void setupData(boolean create, String recordType){
        UserTriggerHelper.skipTrigger=true;
        AccountTriggerHelper.skipTrigger = true;
        AwardTriggerHelper.skipTrigger = true;
        GrantTriggerHelper.skipTrigger = true;
       obj = TestHelper.getTermCondition(create, recordType);
       //grant = TestHelper.getGrant(false);
       //grant.ProjectPeriodStartDate__c=date.today();
       //grant.ProjectPeriodEndDate__c=date.today()+360;
      // insert grant;
        grant = TestHelper.getGrant(false);        
        grant.Status__c = 'Active';
        grant.ProjectPeriodStartDate__c=Date.today();
        
        insert grant;
       award = TestHelper.getAwards(grant.Id, true);
       Account acc = TestHelper.getAccount(true);
       program = TestHelper.getProgram(acc.Id, true);
       Test.setCurrentPageReference(new PageReference('Page.BlankPage')); 
       System.currentPageReference().getParameters().put('recordType', recordType);
       System.currentPageReference().getParameters().put('Id',obj.Id);
       System.currentPageReference().getParameters().put('isProgram','true');
       System.currentPageReference().getParameters().put('grantId',grant.Id);
       System.currentPageReference().getParameters().put('awardId',award.Id);
       System.currentPageReference().getParameters().put('programId',program.Id);
       System.currentPageReference().getParameters().put('isNew','true');
       ApexPages.Standardcontroller sc123 = New ApexPages.StandardController(obj);
       tcEditCtrl = new TermConditionEditCtrl (sc123);
    }
    
    @isTest
    public static void test1 () {
    /*
        UserTriggerHelper.skipTrigger=true;
        AccountTriggerHelper.skipTrigger = true;
        AwardTriggerHelper.skipTrigger = true;
        GrantTriggerHelper.skipTrigger = true;
        ProgramTriggerHelper.skipTrigger = true;
        obj = TestHelper.getTermCondition(false, 'Payment Request');
        obj.ReportStartDate__c = 'Fixed';
        obj.Frequency__c = 'Monthly';
        obj.FixedStartDate__c = Date.newInstance(1960, 2, 17);
        obj.FixedEndDate__c = Date.newInstance(1961, 2, 17);
      //  obj.DueDateType__c = 'Before';
        obj.DueDateDays__c = 10;
        obj.TaskAvailability__c = 3;
        insert obj;
       grant = TestHelper.getGrant(false);        
        grant.Status__c = 'Active';
        grant.ProjectPeriodStartDate__c=Date.today();
        
        insert grant;
        award = TestHelper.getAwards(grant.Id, true);
        Account acc = TestHelper.getAccount(true);
        program = TestHelper.getProgram(acc.Id, true);
        Test.setCurrentPageReference(new PageReference('Page.BlankPage')); 
        // System.currentPageReference().getParameters().put('recordType', recordType);
        System.currentPageReference().getParameters().put('Id',obj.Id);
        System.currentPageReference().getParameters().put('isProgram','true');
        System.currentPageReference().getParameters().put('grantId',grant.Id);
        System.currentPageReference().getParameters().put('awardId',award.Id);
        System.currentPageReference().getParameters().put('programId',program.Id);
        ApexPages.Standardcontroller sc123 = New ApexPages.StandardController(obj);
        tcEditCtrl = new TermConditionEditCtrl (sc123);
        
        */
    }
    
    @isTest
    public static void testGetterSetter(){
    /*
        UserTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
        AccountTriggerHelper.skipTrigger = true;
        AwardTriggerHelper.skipTrigger = true;
        GrantTriggerHelper.skipTrigger = true;
        ProgramTriggerHelper.skipTrigger= true;
        setupData(false,'Term');
        Test.startTest();
        
       // system.assert(tcEditCtrl.savePage == null);
        //system.assert(tcEditCtrl.cancelPage == null);  
        Test.stopTest();
        }
         */
    }
    
    @isTest
    public static void testTerm(){
    /*
        UserTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
        AccountTriggerHelper.skipTrigger = true;
        AwardTriggerHelper.skipTrigger = true;
        GrantTriggerHelper.skipTrigger = true;
        ProgramTriggerHelper.skipTrigger= true;
        Test.startTest();
        setupData(true, 'Term');
        Test.stopTest();
        system.assertNotEquals(tcEditCtrl,null);
        }
         */
    }
    
     @isTest
    public static void testElse(){
    /*
        UserTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
        AccountTriggerHelper.skipTrigger = true;
        AwardTriggerHelper.skipTrigger = true;
        GrantTriggerHelper.skipTrigger = true;
        ProgramTriggerHelper.skipTrigger= true;
        
        obj = TestHelper.getTermCondition(true, 'Condition');
        grant = TestHelper.getGrant(false);        
        grant.Status__c = 'Active';
        grant.ProjectPeriodStartDate__c=Date.today();
        insert grant;
        award = TestHelper.getAwards(grant.Id, true);
        Account acc = TestHelper.getAccount(true);
        program = TestHelper.getProgram(acc.Id, true);
        
        Test.startTest();      
        System.currentPageReference().getParameters().put('recordType', 'Condition');
        System.currentPageReference().getParameters().put('Id',obj.Id);
        System.currentPageReference().getParameters().put('isProgram','true');
        System.currentPageReference().getParameters().put('grantId',grant.Id);
        System.currentPageReference().getParameters().put('awardId',award.Id);
        System.currentPageReference().getParameters().put('programId',program.Id);
        System.currentPageReference().getParameters().put('isNew','true');
        ApexPages.Standardcontroller sc123 = New ApexPages.StandardController(obj);
        tcEditCtrl = new TermConditionEditCtrl (sc123);
        Test.stopTest();
       }
        */
    }
    
    
    
    @isTest
    public static void testCondition(){
    /*
        UserTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
        AccountTriggerHelper.skipTrigger = true;
        AwardTriggerHelper.skipTrigger = true;
        GrantTriggerHelper.skipTrigger = true;
        ProgramTriggerHelper.skipTrigger= true;
        Test.startTest();
        setupData(true, 'Condition');
        Test.stopTest();
        system.assertNotEquals(tcEditCtrl,null);
        }
    }
    
    @isTest
    public static void testReportingReq(){
        UserTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
        AccountTriggerHelper.skipTrigger = true;
        AwardTriggerHelper.skipTrigger = true;
        GrantTriggerHelper.skipTrigger = true;
        ProgramTriggerHelper.skipTrigger= true;
        setupData(true, 'Reporting Requirement');
        Test.startTest();
        System.currentPageReference().getParameters().put('isProgram','false');
        ApexPages.Standardcontroller sc1 = New ApexPages.StandardController(obj);
        tcEditCtrl = new TermConditionEditCtrl (sc1);
        Test.stopTest();
        system.assertNotEquals(tcEditCtrl,null);
        }
         */
    }
    
    @isTest
    public static void testisProgram(){
    /*
        UserTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
        AccountTriggerHelper.skipTrigger = true;
        AwardTriggerHelper.skipTrigger = true;
        GrantTriggerHelper.skipTrigger = true;
        ProgramTriggerHelper.skipTrigger= true;
        setupData(true, 'Reporting Requirement');
        Test.startTest();
        obj = TestHelper.getTermCondition(false, 'Payment Request');
        obj.type__c='Program';
        insert obj;
        System.currentPageReference().getParameters().put('isProgram',null);
        ApexPages.Standardcontroller sc1 = New ApexPages.StandardController(obj);
        tcEditCtrl = new TermConditionEditCtrl (sc1);
        Test.stopTest();
        system.assertNotEquals(tcEditCtrl,null);
        }
         */
    }
    
    @isTest
    public static void testNullController(){
    /*
        UserTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
        AccountTriggerHelper.skipTrigger = true;
        AwardTriggerHelper.skipTrigger = true;
        GrantTriggerHelper.skipTrigger = true;
        ProgramTriggerHelper.skipTrigger= true;
        setupData(true, 'Reporting Requirement');
        Test.startTest();
        System.currentPageReference().getParameters().put('isProgram',null);
        
        ApexPages.Standardcontroller sc1 = new ApexPages.StandardController(obj);
        
        tcEditCtrl = new TermConditionEditCtrl (sc1);
        Test.stopTest();
        system.assertNotEquals(tcEditCtrl,null);
        }
         */
    }
}