UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LEA_Id__c</fullName>
        <label>LEA_Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FiscalYear__c.object
<CustomObject>
    <description>[Business] Stores the Fiscal Year information (Need to revisit)</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Passive</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MST: Fiscal Year</label>
    <nameField>
        <label>Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/POC_Financial__c.object
<CustomObject>
    <fields>
        <fullName>AwardAmount__c</fullName>
        <label>AwardAmount</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POC_FinancialBatch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>POC_FinancialBatch</label>
        <referenceTo>POC_FinancialBatch__c</referenceTo>
        <relationshipLabel>POC_Financials</relationshipLabel>
        <relationshipName>POC_Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Financial__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>POC_Financial</label>
        <referenceTo>POC_Financial__c</referenceTo>
        <relationshipLabel>POC_Financials</relationshipLabel>
        <relationshipName>POC_Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>POC_Financials</relationshipLabel>
        <relationshipName>POC_Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubRecipient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>POC_Financials</relationshipLabel>
        <relationshipName>POC_Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UniqueKeyFormula__c</fullName>
        <formula>Program__c + SubRecipient__c + TEXT(POC_FinancialBatch__r.FiscalYear__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UniqueKeyFormula</label>
        <type>Text</type>
    </fields>
    <label>POC_Financial</label>
    <nameField>
        <label>POC_Financials Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POC_Financials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/POC_FinancialBatch__c.object
<CustomObject>
    <fields>
        <fullName>EffectiveMonth__c</fullName>
        <label>Effective Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Jan</fullName>
                </value>
                <value>
                    <fullName>Feb</fullName>
                </value>
                <value>
                    <fullName>Mar</fullName>
                </value>
                <value>
                    <fullName>Apr</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>Jun</fullName>
                </value>
                <value>
                    <fullName>Jul</fullName>
                </value>
                <value>
                    <fullName>Aug</fullName>
                </value>
                <value>
                    <fullName>Sep</fullName>
                </value>
                <value>
                    <fullName>Oct</fullName>
                </value>
                <value>
                    <fullName>Nov</fullName>
                </value>
                <value>
                    <fullName>Dec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Uploaded</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Create</fullName>
                </value>
                <value>
                    <fullName>Amend</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>POC_FinancialBatch</label>
    <nameField>
        <label>POC_FinancialBatch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POC_FinancialBatchs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/POC_FinancialMain__c.object
<CustomObject>
    <fields>
        <fullName>AwardAmount__c</fullName>
        <label>AwardAmount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EffectiveMonth__c</fullName>
        <label>EffectiveMonth</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>FiscalYear</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POC_FinancialBatch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>POC_FinancialBatch</label>
        <referenceTo>POC_FinancialBatch__c</referenceTo>
        <relationshipLabel>POC_FinancialMains</relationshipLabel>
        <relationshipName>POC_FinancialMains</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>POC_FinancialMains</relationshipLabel>
        <relationshipName>POC_FinancialMains</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubRecipient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>POC_FinancialMains</relationshipLabel>
        <relationshipName>POC_FinancialMains</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UniqueKeyFormula__c</fullName>
        <formula>Program__c + SubRecipient__c + FiscalYear__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UniqueKeyFormula</label>
        <type>Text</type>
    </fields>
    <label>POC_FinancialMain</label>
    <nameField>
        <label>POC_FinancialMain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POC_FinancialMains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Year</label>
        <referenceTo>FiscalYear__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramName__c</fullName>
        <description>This stores the Title of Program</description>
        <label>Program Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/POC_FinancialCtrl.cls
public with sharing class POC_FinancialCtrl {
    
	public String recordId{get;set;}
	public String packageId{get;set;}
	public PageReference deleteURL{get;set;}
	public String stageJSON{get;set;}
    public String fbStatus{get;set;}
    public String mainJSON{get;set;}

    public POC_FinancialCtrl(ApexPages.StandardController stdController) {
        recordId = ApexPages.CurrentPage().getParameters().get('id');
        packageId = null;
        deleteURL = null;
        POC_FinancialBatch__c fb = [SELECT Id, Status__c, FiscalYear__c FROM POC_FinancialBatch__c WHERE Id = :recordId];
        fbStatus = fb.Status__c;
        List<POC_FinancialMain__c> fms = [SELECT Program__r.ProgramName__c, SubRecipient__r.Name, AwardAmount__c, UniqueKeyFormula__c FROM POC_FinancialMain__c WHERE FiscalYear__c =:fb.FiscalYear__c ORDER BY SubRecipient__r.LEA_Id__c, Program__r.Name];
        List<POC_Financial__c> fs = [SELECT Program__r.ProgramName__c, SubRecipient__r.Name, AwardAmount__c, UniqueKeyFormula__c FROM POC_Financial__c WHERE POC_FinancialBatch__c =:recordId ORDER BY SubRecipient__r.LEA_Id__c, Program__r.Name];
        
        //mainJSON = JSON.serialize(fms);
        //if(fbStatus == 'Approved'){    
        //    stageJSON = JSON.serialize(fms);
        //}else{
        //    stageJSON = JSON.serialize(fs);
        //}

        List<AwardWrapper> stageWrapper = new List<AwardWrapper>();
        for(POC_Financial__c f : fs){
            AwardWrapper temp = new AwardWrapper();
            temp.programName = f.Program__r.ProgramName__c;
            temp.subRecipientName = f.SubRecipient__r.Name;
            temp.awardAmount = f.AwardAmount__c;
            temp.uniqueKeyFormula = f.UniqueKeyFormula__c;
            stageWrapper.add(temp);
        }
        List<AwardWrapper> mainWrapper = new List<AwardWrapper>();
        for(POC_FinancialMain__c fm : fms){
            AwardWrapper temp = new AwardWrapper();
            temp.programName = fm.Program__r.ProgramName__c;
            temp.subRecipientName = fm.SubRecipient__r.Name;
            temp.awardAmount = fm.AwardAmount__c;
            temp.uniqueKeyFormula = fm.UniqueKeyFormula__c;
            mainWrapper.add(temp);
        }
        mainJSON = JSON.serialize(mainWrapper);
        if(fbStatus == 'Approved'){    
            stageJSON = JSON.serialize(mainWrapper);
        }else{
            stageJSON = JSON.serialize(stageWrapper);
        }

    } 

    public String getKeyValueMap(){
        Map<String,String> keyValueMap = new Map<String,String>();
        keyValueMap.put('batchId', recordId);
        return JSON.serialize(keyValueMap);
    }
    
    public String getListParameters(){
	    Map<String,Set<String>> listParams = new Map<String,Set<String>>();
	    return JSON.serialize(listParams);
    }

    public PageReference approve(){
    	POC_FinancialBatch__c pf = [SELECT FiscalYear__c, Type__c, Status__c FROM POC_FinancialBatch__c WHERE Id = :recordId];
        Savepoint sp = Database.setSavepoint();
		try{
            if(pf.Type__c == 'Create'){
                List<POC_FinancialBatch__c> fbsSameYear = [SELECT Status__c FROM POC_FinancialBatch__c WHERE FiscalYear__c = :pf.FiscalYear__c AND Id != :pf.Id];
                Boolean flag = false;
                
                for(POC_FinancialBatch__c fb : fbsSameYear ){
                    if(fb.Status__c == 'Approved'){
                        flag = true;
                    }
                }

                if(flag){
                     ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'One create batch already approved for this year'));
                     return null;
                }else{
                    List<POC_Financial__c> fs = [SELECT Id, Program__c, SubRecipient__c, AwardAmount__c, POC_FinancialBatch__r.FiscalYear__c, POC_FinancialBatch__r.EffectiveMonth__c FROM POC_Financial__c WHERE POC_FinancialBatch__c = :recordId];
                    List<POC_FinancialMain__c> fms = new List<POC_FinancialMain__c>();
                    for(POC_Financial__c f : fs){
                        POC_FinancialMain__c temp = new POC_FinancialMain__c(
                            Program__c = f.Program__c,
                            SubRecipient__c = f.SubRecipient__c,
                            AwardAmount__c = f.AwardAmount__c,
                            FiscalYear__c = f.POC_FinancialBatch__r.FiscalYear__c,
                            EffectiveMonth__c = f.POC_FinancialBatch__r.EffectiveMonth__c
                        );
                        fms.add(temp);
                    }
                    if(fms.size() > 0){
                        insert fms;
                    }
                    pf.Status__c = 'Approved';
                }
            }else if(pf.Type__c == 'Amend'){
                List<POC_Financial__c> fs = [SELECT Id, Program__c, SubRecipient__c, AwardAmount__c, POC_FinancialBatch__c, UniqueKeyFormula__c FROM POC_Financial__c WHERE POC_FinancialBatch__c = :recordId];
                Map<String, POC_Financial__c> stageMap = new Map<String, POC_Financial__c>();
                for(POC_Financial__c f : fs){
                    stageMap.put(f.UniqueKeyFormula__c, f);
                }
                List<POC_FinancialMain__c> fms = [SELECT Id, AwardAmount__c, UniqueKeyFormula__c FROM POC_FinancialMain__c WHERE UniqueKeyFormula__c IN :stageMap.keySet()];
                List<POC_FinancialMain__c> updatefms = new List<POC_FinancialMain__c>();
                for(POC_FinancialMain__c fm : fms){
                    POC_Financial__c f = stageMap.get(fm.UniqueKeyFormula__c);
                    if(fm.AwardAmount__c != f.AwardAmount__c){
                        fm.AwardAmount__c = f.AwardAmount__c;
                        updatefms.add(fm);
                    }
                }

                if(updatefms.size() > 0){
                    update updatefms;
                }
                pf.Status__c = 'Approved';
            }
            update pf;
    		PageReference pageref = Page.PhaseView;
            pageref.getParameters().put('t','GrantorPlanning');
            pageref.setRedirect(true);
            return pageref;
        }catch(Exception e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
            Database.rollback(sp);
            return null;
        }
    }
    public PageReference reject(){
    	POC_FinancialBatch__c pf = [SELECT Status__c FROM POC_FinancialBatch__c WHERE Id = :recordId];
		pf.Status__c = 'Rejected';
		update pf;
		PageReference pageref = Page.PhaseView;
        pageref.getParameters().put('t','GrantorPlanning');
        pageref.setRedirect(true);
        return pageref;
	}

    public PageReference cancel(){
        PageReference pageref = Page.PhaseView;
        pageref.getParameters().put('t','GrantorPlanning');
        pageref.setRedirect(true);
        return pageref;
    }

    class AwardWrapper{
        public String programName{get;set;}
        public String subRecipientName{get;set;}
        public String awardAmount{get;set;}
        public String uniqueKeyFormula{get;set;}
    }

}