UtahLiveDataTest/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EINText__c</fullName>
        <label>EIN Text</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <formula>Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Disapproved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Debarred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UserRegistration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization/User Registration</label>
        <referenceTo>UserRegistration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>UserRegistration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Registration</label>
        <referenceTo>UserRegistration__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/UserRegistration__c.object
<CustomObject>
    <description>[Business] Need more Detailed info from Swati Singh</description>
    <fields>
        <fullName>AccountCreateFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AccountCreateFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EINText__c</fullName>
        <inlineHelpText>This is the EIN text entered.</inlineHelpText>
        <label>Employee Identification Number (EIN)</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <inlineHelpText>Registered Name as listed in DUN and BradStreet</inlineHelpText>
        <label>Organization Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationTypeSInglePicklist__c</fullName>
        <label>Organization Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>State governments</fullName>
                </value>
                <value>
                    <fullName>County governments</fullName>
                </value>
                <value>
                    <fullName>City or township governments</fullName>
                </value>
                <value>
                    <fullName>Special district governments</fullName>
                </value>
                <value>
                    <fullName>Independent school districts</fullName>
                </value>
                <value>
                    <fullName>State institutions for higher education</fullName>
                </value>
                <value>
                    <fullName>Public housing authorities</fullName>
                </value>
                <value>
                    <fullName>Nonprofits having a 501 (C)(3)</fullName>
                </value>
                <value>
                    <fullName>Private institutions of higher education</fullName>
                </value>
                <value>
                    <fullName>Individuals</fullName>
                </value>
                <value>
                    <fullName>Non Profit Victim Services</fullName>
                </value>
                <value>
                    <fullName>Indian Tribe</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrgnizationPhoneNumber__c</fullName>
        <inlineHelpText>This is Organization’s recognized Phone Number.  Format is XXX-XXX-XXXX</inlineHelpText>
        <label>Organization Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PrimaryRepCity__c</fullName>
        <label>Primary Rep City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryRepFirstName__c</fullName>
        <label>Primary Rep First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryRepLastName__c</fullName>
        <label>Primary Rep Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryRepPrefix__c</fullName>
        <label>Primary Rep Prefix</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mr.</fullName>
                </value>
                <value>
                    <fullName>Ms.</fullName>
                </value>
                <value>
                    <fullName>Mrs.</fullName>
                </value>
                <value>
                    <fullName>Dr.</fullName>
                </value>
                <value>
                    <fullName>Prof.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrimaryRepState__c</fullName>
        <label>Primary Rep State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>Virginia</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SecondaryRepCity__c</fullName>
        <label>Secondary Rep City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecondaryRepEmail__c</fullName>
        <inlineHelpText>Enter Point of Contact’s E-mail address. For example xyz@abc.com</inlineHelpText>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SecondaryRepFirstName__c</fullName>
        <label>Secondary Rep First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecondaryRepLastName__c</fullName>
        <label>Secondary Rep Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecondaryRepPrefix__c</fullName>
        <label>Secondary Rep Prefix</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mr.</fullName>
                </value>
                <value>
                    <fullName>Ms.</fullName>
                </value>
                <value>
                    <fullName>Mrs.</fullName>
                </value>
                <value>
                    <fullName>Dr.</fullName>
                </value>
                <value>
                    <fullName>Prof.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SecondaryRepState__c</fullName>
        <label>Secondary Rep State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>Virginia</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>External Registration</label>
    <nameField>
        <displayFormat>RG-{000000}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Registration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestUserRegAccountCreationHandler.cls
@isTest
private class TestUserRegAccountCreationHandler {

    static testMethod void myUnitTest() {
        
        User u = TestHelper.getAdminUser(true);
        system.runAs(u) {
            // skip unwanted triggers
            AccountTriggerHelper.skipAll = true;
            ContactTriggerHelper.skiptrigger = true;
            UserRegistrationTriggerHelper.skipTrigger = true;
            UserTriggerHelper.skipTrigger = true;
            
            UserRegistration__c userreg = new UserRegistration__c(AccountCreateFlag__c=true,Status__c='Approved');
            userreg.OrganizationName__c = 'REI Systems Test';
            userreg.OrgnizationPhoneNumber__c = '1234567890';
            userreg.EINText__c='123456789';
            userreg.OrganizationTypeSInglePicklist__c='State governments';
            userreg.PrimaryRepPrefix__c='Miss.';
            userreg.PrimaryRepFirstName__c = 'Sample';
            userreg.PrimaryRepLastName__c = 'Test';
            userreg.PrimaryRepCity__c = 'Sterling';
            userreg.PrimaryRepState__c = 'Virginia';
            userreg.SecondaryRepEmail__c = 'abc@test.com';
            userreg.SecondaryRepPrefix__c = 'Mr.';
            userreg.SecondaryRepFirstName__c='REI';
            userreg.SecondaryRepLastName__c='Systems';
            userreg.SecondaryRepCity__c='Fairfax';
            userreg.SecondaryRepState__c='Virginia';
            insert userreg;
            
            Account acc = TestHelper.getAccount(false);
            acc.UserRegistration__c = userreg.id;
            insert acc;
            Contact con =TestHelper.getContact(false);
            con.Accountid = acc.id;
            insert con;
            //User user = TestHelper.getPortalUser(true);
            Test.startTest();
            UserRegAccountUserCreationHandler userregcreationhandler = new UserRegAccountUserCreationHandler();
            Database.executeBatch(userregcreationhandler);
           
            Test.stopTest();
        }
    
    }
}