UtahLiveDataTest/src/objects/AmendmentRequest__c.object
<CustomObject>
    <description>[Business] Stores all the change requests information</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Amendment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipName>Amendment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Amendment Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Change Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>FiscalYear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this is used on NoGA froms</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2000</fullName>
                </value>
                <value>
                    <fullName>2001</fullName>
                </value>
                <value>
                    <fullName>2002</fullName>
                </value>
                <value>
                    <fullName>2003</fullName>
                </value>
                <value>
                    <fullName>2004</fullName>
                </value>
                <value>
                    <fullName>2005</fullName>
                </value>
                <value>
                    <fullName>2006</fullName>
                </value>
                <value>
                    <fullName>2007</fullName>
                </value>
                <value>
                    <fullName>2008</fullName>
                </value>
                <value>
                    <fullName>2009</fullName>
                </value>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GrantorOrganization__c</fullName>
        <formula>Grant__r.ExternalOrganization__r.Name</formula>
        <label>Grantor Organization</label>
        <type>Text</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FiscalYear__c.object
<CustomObject>
    <description>[Business] Stores the Fiscal Year information (Need to revisit)</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InternalOrganization__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Internal Organization?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>MST: Fiscal Year</label>
    <nameField>
        <label>Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FormBudgetInformation__c.object
<CustomObject>
    <description>[Business] This object is used for Budget Information forms.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Overflow Budget Information</label>
    <nameField>
        <displayFormat>BI-{00000}</displayFormat>
        <label>Budget Information</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Overflow Budget Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InternalOrganization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Grants (Internal Organization)</relationshipLabel>
        <relationshipName>Grants1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProgramCode</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Division of the organization to which the User Belongs</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>End date of the program, to determine if it is a single or a multi year program</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Year</label>
        <referenceTo>FiscalYear__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InternalOrganization__c</fullName>
        <description>Created to show up on the portal</description>
        <label>Internal Organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramPathway__c</fullName>
        <label>Program Pathway</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MSP</fullName>
                </value>
                <value>
                    <fullName>Fed-Formula</fullName>
                </value>
                <value>
                    <fullName>Application 1/12th</fullName>
                </value>
                <value>
                    <fullName>State-Competitive</fullName>
                </value>
                <value>
                    <fullName>Fed-Competitive</fullName>
                </value>
                <value>
                    <fullName>Lump-Sum-App</fullName>
                </value>
                <value>
                    <fullName>Lump-Sum-No-App</fullName>
                </value>
                <value>
                    <fullName>State-Formula</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Start date of the program</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>USBEIndirectCostRate__c</fullName>
        <label>USBE Indirect Cost Rate</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ProgramPathway__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Restricted</fullName>
                </value>
                <value>
                    <fullName>Unrestricted</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Restricted </fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/USBELEACostRate__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>LEACostRate</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <formula>Year__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fiscal Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RestrictedIndirectRate__c</fullName>
        <label>Restricted Indirect Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>UnrestrictedIndirectRate__c</fullName>
        <label>Unrestricted Indirect Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MST: Fiscal Year</label>
        <referenceTo>FiscalYear__c</referenceTo>
        <relationshipName>USBELEAFiscalYear</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>USBELEACostRate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>USBELEACostRates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/USBELEACostRateTriggerHelper.cls
global with sharing class USBELEACostRateTriggerHelper extends GNT.TriggerHelper{
    
    global static boolean skipTrigger = false;
    
    global override void processBeforeInsert(){
        if (skipTrigger != true){
            populateName(Trigger.new);
        }
    }
    global override void processAfterInsert(){
        //Trigger.new holds all the indirects that are being updated, so these are the only ones you care about
        //USBELEACostRate__c: Account__c (LEA), FiscalYear__c (Fiscal Year), RestrictedIndirectRate__c (Restricted %), UnrestrictedIndirectRate__c (Unrestricted %)
        if (skipTrigger != true){
            reviseBudgetForUpdatedIndirect((List<USBELEACostRate__c>) Trigger.new);
        }
    }
    global override void processAfterUpdate(){
        if (skipTrigger != true){
            reviseBudgetForUpdatedIndirect((List<USBELEACostRate__c>) Trigger.new);
        }
    }
    
    private void populateName(List<USBELEACostRate__c> costrates){
        String delims = '-+';
        for (USBELEACostRate__c costrate : costrates){
            String[] tokens = costrate.FiscalYear__c.split(delims);
            costrate.Name = tokens[1];
        }
    }
    
    private void reviseBudgetForUpdatedIndirect(List<USBELEACostRate__c> leaCostRateList) {
        Savepoint savestate = Database.setSavepoint();
        try {
            //Create a list of LEAs that are contained in the trigger list
            Map<Id, USBELEACostRate__c> leaMapIndirectObject = new Map<Id, USBELEACostRate__c>();
            List<Id> uploadFiscalYearIdlist = new List<Id>();
            for (USBELEACostRate__c usbeCostRateIterator : leaCostRateList) {
                uploadFiscalYearIdlist.add(usbeCostRateIterator.Year__c); //Check the fiscal year of the upload, 
                leaMapIndirectObject.put(usbeCostRateIterator.Account__c, usbeCostRateIterator);
            }
            List<FiscalYear__c> uploadFiscalYear = [SELECT Id, StartDate__c, EndDate__c FROM FiscalYear__c WHERE Id IN: uploadFiscalYearIdlist];
            System.debug('MANUALDEBUG >>> fiscalYears:' + uploadFiscalYear);
            System.debug('MANUALDEBUG >>> map LEA ID to cost rate obj: ' + leaMapIndirectObject);
    
            //Each upload for indirect change will be applied for the same fiscal year for them all. There will never be an upload for more than one fiscal year's indirect at a time
            //Find and store the list of whatever grants/awards that are active fiscal year we're doing the indirect cost update for where the LEA is in the list of LEAs
            //E.g. If it's currently the 2018 fiscal year and we're doing the upload for the 2019 fiscal year: DON'T check whatever grants are active for the 2018 fiscal year, DO check whatever grants are active during the 2019 fiscal year.    
            List<Award__c> awardList = 
                [SELECT Id, Name, GrantorOrganization__c, Grant__c, Grant__r.InternalOrganization__c, Grant__r.Program__c, Grant__r.Program__r.USBEIndirectCostRate__c, Grant__r.Program__r.StartDate__c, Grant__r.Program__r.EndDate__c, Grant__r.Program__r.ProgramPathway__c, Application__c, Application__r.IndirectCostPercentage__c, BudgetPeriodStartDates__c, BudgetPeriodEndDates__c, IndirectCostPercentage__c 
                FROM Award__c 
                WHERE GrantorOrganization__c = 'USBE' AND Status__c != 'Amended' AND Grant__r.Program__r.ProgramPathway__c IN('Fed-Formula', 'Fed-Competitive') AND Grant__r.InternalOrganization__c IN: leaMapIndirectObject.keySet() AND (Grant__r.Program__r.EndDate__c >: uploadFiscalYear[0].StartDate__c)]; 
            System.debug('MANUALDEBUG >>> awardListSize: ' + awardList.size());
            System.debug('MANUALDEBUG >>> awardList: ' + awardList);    
       
            List<User> leaUserList = [
                SELECT Id, Email, ProfileName__c, AccountId, ContactId 
                FROM User 
                WHERE AccountId IN: leaMapIndirectObject.keySet() AND (ProfileName__c = 'SPA' OR ProfileName__c = 'SPI')];
            Map<Id, List<User>> leaIdMapUserIdList = new Map<Id, List<User>>();
            Map<Id,User> userIdMapUserObj = new Map<Id,User>();
            for (User userIterator : leaUserList) {
                List<User> userList = leaIdMapUserIdList.get(userIterator.AccountId);
                if(userList == null){
                    userList = new List<User>();
                    leaIdMapUserIdList.put(userIterator.AccountId, userList);
                }
                userList.add(userIterator);
                userIdMapUserObj.put(userIterator.Id, userIterator);
            }
            System.debug('MANUALDEBUG >>> leaUserList: ' + leaUserList);    
            System.debug('MANUALDEBUG >>> leaIdMapUserIdList: ' + leaIdMapUserIdList); //Maps the LEA account Id to the list of Recipient Users who are associated with that LEA
            System.debug('MANUALDEBUG >>> userIdMapUserObj: ' + userIdMapUserObj);
    
            if (!awardList.isEmpty()) { //If there are awards that fit this criteria
                //If there are current LEA initiated budget revisions on those awards, reject them and reset the award so that the USBE budget revision takes precidence
                Set<String> revisionNotInProgressStatusList = new Set<String>{'Not Started', 'Change Requested', 'Rejected', 'Active'};
                List<Id> awardIdsList = new List<Id>();
                for (Award__c awardIterator : awardList) {
                    awardIdsList.add(awardIterator.Id);
                }
                //Find all AmendmentRequest__c whose Award__c are in the list of edited Awards and their Status__c is not in Active/Change Requested/Rejected/Revised
                List<AmendmentRequest__c> budgetRevisionList = [
                    SELECT Id, Award__r.BudgetRevisionInitiatedByUSBE__c, Status__c
                    FROM AmendmentRequest__c 
                    WHERE Award__c IN: awardIdsList AND Award__r.BudgetRevisionInitiatedByUSBE__c = 'Not Initiated By USBE' AND Status__c NOT IN: revisionNotInProgressStatusList];
                if (!budgetRevisionList.isEmpty()) {
                    //If any of the budget revisions are locked due to an approval process
                    List<AmendmentRequest__c> lockedBudgetRevisions = new List<AmendmentRequest__c>();
                    List<Id> budgetRevisionIdList = new List<Id>();
                    for (AmendmentRequest__c amendmentRequestIterator : budgetRevisionList) {
                        if(Approval.isLocked(amendmentRequestIterator)) {
                            lockedBudgetRevisions.add(amendmentRequestIterator);
                        }
                        budgetRevisionIdList.add(amendmentRequestIterator.Id);
                    }
                    if (lockedBudgetRevisions.size() > 0) { //If there are any who are locked, unlock them
                        Approval.UnlockResult[] unlockResultList = Approval.unlock(lockedBudgetRevisions, false);
                        for(Approval.UnlockResult unlockResultIterator : unlockResultList) { // Iterate through each returned result
                            if (unlockResultIterator.isSuccess()) { // Operation was successful, so get the ID of the record that was processed
                                System.debug('Successfully unlocked record with ID: ' + unlockResultIterator.getId());
                            }
                            else { // Operation failed, so get all errors                       
                                for(Database.Error err : unlockResultIterator.getErrors()) {                 
                                    System.debug('Error has occured with: ' + err.getFields() + ' : ' + err.getStatusCode() + ' : ' + err.getMessage());
                                }
                            }
                        }   
                    }
                    //Get approval processes for those LEA budget revision records
                    List<ProcessInstanceWorkItem> approvalItemList = [SELECT Id FROM ProcessInstanceWorkItem WHERE ProcessInstance.TargetObjectId IN: budgetRevisionIdList AND ProcessInstance.Status = 'Pending'];
                    for (ProcessInstanceWorkItem approvalItem : approvalItemList) {
                        Approval.ProcessWorkItemRequest request = new Approval.ProcessWorkItemRequest();
                        request.setComments('Rejected Due Change In Indirect Rate');
                        request.setAction('Reject');
                        request.setWorkItemId(approvalItem.Id);
                        Approval.ProcessResult result = Approval.process(request);
                    }
                    //Get tasks for those LEA budget revision records
                    List<Task> taskList = [SELECT Id FROM Task WHERE WhatId IN: budgetRevisionIdList AND Status != 'Completed']; 
                    for (Task taskIterator : taskList) {
                        taskIterator.Status = 'Completed';
                    }
                    update taskList;
                    //The AmendmentRequestTriggerHelper automatically handles resetting the Award in preparation for a new budget revision
                    for (AmendmentRequest__c budgetRevisionIterator : budgetRevisionList) { //All records are unlocked and are available for modification
                        //Close all approval processes and tasks for those LEA budget revision records
                        budgetRevisionIterator.Status__c = 'Rejected'; //Set those LEA budget revisions as rejected. 
                    }
                    update budgetRevisionList; 
                }
                //Now that those LEA budget revisions are rejected, we can modify the awards to initiate the USBE budget revisions (continue with the workflow)
    
    
                //List<Task> budgetRevisionTaskList = new List<Task>();
                List<GNT.TaskCreationHandler.TaskBulkClass> tasksList = new List<GNT.TaskCreationHandler.TaskBulkClass>();
                /*INDIRECT ---------- */EmailTemplate emailTemplate = [SELECT Id FROM EmailTemplate WHERE Name = 'Award ready for subrecipient approval' LIMIT 1];
                //For each award/grant in the activeInUpcomingFiscalYear list       
                for (Award__c awardIterator : awardList) {
                    //Check which LEA the grant/awards are for
                    Id leaId = awardIterator.Grant__r.InternalOrganization__c;
                    //Get the list of users in said LEA
                    List<User> currentAwardLeaUserList = leaIdMapUserIdList.get(leaId);
                    List<String> mailTo = new List<String>();
                    Map<Id, String[]> recIdMapEmail = new Map<Id, String[]>();
                    Map<Id, Map<Id, String[]>> awardIdMapRecIdMapEmail = new Map<Id,Map<Id, String[]>>();
                    //Check the award/grant's program's indirect cost rate type (restricted or unrestricted)
                    String costRateType = awardIterator.Grant__r.Program__r.USBEIndirectCostRate__c;
                    System.debug('MANUALDEBUG >>> costRateType: ' + costRateType);
                    //Get the triggerList indirect object corresponding to the Award's LEA
                    USBELEACostRate__c costRateObjForLEA = leaMapIndirectObject.get(leaId);
                    //Pull the indirect cost % of the program's indirect cost rate type for the LEA
                    if (costRateType == 'Restricted') {
                        if (awardIterator.IndirectCostPercentage__c != costRateObjForLEA.RestrictedIndirectRate__c) { //If the uploaded indirect cost is different from the new one
                            //awardIterator.IndirectCostPercentage__c = costRateObjForLEA.RestrictedIndirectRate__c; //Update indirect                
                            awardIterator.IndirectCostPercentageProposed__c = costRateObjForLEA.RestrictedIndirectRate__c; //Update indirect  
                            awardIterator.BudgetRevisionInitiated__c = 'In Progress';//Automatically initiate revision for the awards
                            awardIterator.BudgetRevisionInitiatedByUSBE__c = 'Indirect Change';
                            //Create task and email to the LEA to do the revision                        
                            for (User userIterator : currentAwardLeaUserList) {
                                //List<Task> budgetRevisionTask = GNT.TaskCreationHandler.createTasks(userIterator.Id, awardIterator.Id, 'Complete Budget Revision', awardIterator.Name, null, false, System.TODAY() + 7, 'Other', awardIterator.Name, false);
                                //budgetRevisionTaskList.addAll(budgetRevisionTask);
                                //mailTo.add(userIterator.Email);
                                GNT.TaskCreationHandler.TaskBulkClass task = new GNT.TaskCreationHandler.TaskBulkClass();
                                task.ownerUserId = userIterator.Id;
                                task.recordId = awardIterator.Id;
                                task.action = 'Complete Budget Revision';
                                task.recordName = awardIterator.Name;
                                task.startDate = System.TODAY();
                                task.dueDate = System.TODAY() + 7;
                                task.subject ='Complete Budget Revision';                
                                tasksList.add(task);
                            }
                        }
                    }
                    else if (costRateType == 'Unrestricted') {
                        if (awardIterator.IndirectCostPercentage__c != costRateObjForLEA.UnrestrictedIndirectRate__c) {
                            //awardIterator.IndirectCostPercentage__c = costRateObjForLEA.UnrestrictedIndirectRate__c;
                            awardIterator.IndirectCostPercentageProposed__c = costRateObjForLEA.UnrestrictedIndirectRate__c;
                            awardIterator.BudgetRevisionInitiated__c = 'In Progress';
                            awardIterator.BudgetRevisionInitiatedByUSBE__c = 'Indirect Change';
                            awardIterator.CurrentRevisionStatus__c = 'Created';
                            //Create task and email to the LEA to do the revision
                            //Create task and email to the LEA to do the revision                        
                            for (User userIterator : currentAwardLeaUserList) {
                                //List<Task> budgetRevisionTask = GNT.TaskCreationHandler.createTasks(userIterator.Id, awardIterator.Id, 'Complete Budget Revision', awardIterator.Name, null, false, System.TODAY() + 7, 'Other', awardIterator.Name, false);
                                //budgetRevisionTaskList.addAll(budgetRevisionTask);
                                //mailTo.add(userIterator.Email);
                                GNT.TaskCreationHandler.TaskBulkClass task = new GNT.TaskCreationHandler.TaskBulkClass();
                                task.ownerUserId = userIterator.Id;
                                task.recordId = awardIterator.Id;
                                task.action = 'Complete Budget Revision';
                                task.recordName = awardIterator.Name;
                                task.startDate = System.TODAY();
                                task.dueDate = System.TODAY() + 7;
                                task.subject ='Complete Budget Revision';                 
                                tasksList.add(task);
                            }
                        }
                    }
                    //recIdMapEmail.put(awardIterator.Id, mailTo);
                    //awardIdMapRecIdMapEmail.put(awardIterator.Id, recIdMapEmail);
                    //Id currentContact = currentAwardLeaUserList[0].ContactId;//Dummy contact id used by the AppUtils method
                    //AppUtils.sendEmailUsingTemplate(emailTemplate.Id, awardIdMapRecIdMapEmail.get(awardIterator.Id), currentContact, false);
                    //System.debug('MANUALDEBUG >>> emailTemplateId, awardIdMapRecIdMapEmail, currentContactId: ' + emailTemplate.Id + ', ' + awardIdMapRecIdMapEmail.get(awardIterator.Id) + ', ' + currentContact);
                }
                if (!awardList.isEmpty()) { 
                    USBEAwardTriggerHelper.skipTrigger = true;
                    USBEAwardTriggerHelper.skipTriggers = true;
                    USBEAwardTriggerHelper.skipfromAmendment = true;
                    update awardList; 
                    USBEAwardTriggerHelper.skipTrigger = false;
                    USBEAwardTriggerHelper.skipTriggers = true;
                    USBEAwardTriggerHelper.skipfromAmendment = true;
                }
                if(tasksList.size() > 0){
                    List<Task> insertedTaskList = GNT.TaskCreationHandler.createBulkTasks(tasksList,true); 
                    
                    Map<Id, String[]> recIdToAddressMap = new Map<Id, String[]> ();
                    for(Task taskIterator : insertedTaskList){
                        System.debug('MANUALDEBUG >>> taskIterator: ' + taskIterator);
                        List<String> toAddress = recIdToAddressMap.get(taskIterator.WhatId); 
                        if (toAddress == null) {
                            toAddress = new List<String>();
                            recIdToAddressMap.put(taskIterator.WhatId,toAddress);
                        }
                        User u = userIdMapUserObj.get(taskIterator.OwnerId);
                        toAddress.add(u.Email);
                        System.debug('MANUALDEBUG >>> toAddress: ' + toAddress);
                        recIdToAddressMap.put(taskIterator.WhatId,toAddress);
                    }
                    GNT.AppUtils.sendEmailUsingTemplate(emailTemplate.Id, recIdToAddressMap, leaUserList[0].ContactId, false);
                }
                //if (!budgetRevisionTaskList.isEmpty()) { insert budgetRevisionTaskList; } 
            }         
        }
        catch (Exception E) {
            Database.rollback(savestate);
            System.debug('ERROR: ' + e.getMessage());
            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }                
    }
    
}