UtahLiveDataTest/src/objects/AmendmentRequest__c.object
<CustomObject>
    <description>[Business] Stores all the change requests information</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Amendment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Amendment Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Change Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A unique id to relate the announcement to the program.</description>
        <label>Program ID</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Agency__c</fullName>
        <description>Name of the Awarding Federal Agency which is a Granting this grant</description>
        <formula>Announcement__r.AwardingFedAgency__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreApplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre Application</label>
        <referenceTo>PreApplication__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Closeout__c.object
<CustomObject>
    <description>[Business] All the close out information is stored on this object</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Closeouts</relationshipLabel>
        <relationshipName>Closeouts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Closeout</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closeouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PreApplication__c.object
<CustomObject>
    <description>[Business] Pre-Application is a trimmed version of the Application with limited information</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>PreApplications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Pre-Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pre-Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RiskAssessment__c.object
<CustomObject>
    <description>[Business] This will be part of Grant Making Module.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Risk Assessment</relationshipLabel>
        <relationshipName>Risk_Assessment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Risk Assessment</relationshipLabel>
        <relationshipName>Risk_Assessment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgressReport__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Progress Report</label>
        <referenceTo>ProgressReports__c</referenceTo>
        <relationshipLabel>Risk Assessment</relationshipLabel>
        <relationshipName>Risk_Assessment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Risk Assessment</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk Assessment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RolesAndResponsibilities__c.object
<CustomObject>
    <description>[Business] Roles and Responsibilities defined for all the objects like Opportunity ,Application etc</description>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AmendmentRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Amendment Request</label>
        <referenceTo>AmendmentRequest__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closeout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closeout</label>
        <referenceTo>Closeout__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreApplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Pre-Application to which this Role and Responsibility belongs</description>
        <label>Pre-Application</label>
        <referenceTo>PreApplication__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to populate the Program to which this Role and and Responsibility belongs</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgressReport__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Progress Report</label>
        <referenceTo>ProgressReports__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities (Progress Report)</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RiskAssessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk Assessment</label>
        <referenceTo>RiskAssessment__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StrategicPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Strategic Plan</label>
        <referenceTo>StrategicPlan__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Roles and Responsibilities</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles and Responsibilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/SiteVisit__c.object
<CustomObject>
    <description>[Business] This object is used to store all the information related to the Site Visits which is a Post Award Activity.</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Site Visits</relationshipLabel>
        <relationshipName>SiteVisits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/StrategicPlan__c.object
<CustomObject>
    <description>[Business] Defines the Strategic plan for an Organization which owns the Application</description>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Strategic Plans</relationshipLabel>
        <relationshipName>Strategic_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Strategic Plan</label>
    <nameField>
        <displayFormat>SPN-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/RolesAndResponsibilityRecordSharingBatch.cls
global class RolesAndResponsibilityRecordSharingBatch extends GNT.BatchApexHandler{ /*implements Database.Batchable<sObject>{*/

     
     //global Database.QueryLocator start(Database.BatchableContext BC){
    global override String getQuery(){
      String query = 'select Id,Name__c,Agency__c,Program__c,StrategicPlan__c,Announcement__c,Application__c,PreApplication__c,AmendmentRequest__c,Award__c,ProgressReport__c' +
       ',RiskAssessment__c ,Closeout__c, SiteVisit__c,BusinessRole__c from RolesAndResponsibilities__c where BatchSharing__c = true';
       
       System.debug('==== <<<<<<  BATCH JOB START METHOD  >>>>>> ====');
      //return Database.getQueryLocator(query); 
      return query;
    }
    
    //global void execute(Database.BatchableContext BC, List<sObject> scope){
         global override void execute(List<SObject> scope){
        System.debug('==== <<<<<<  BATCH JOB EXECUTE METHOD  >>>>>> ====');
         List<RolesAndResponsibilities__c> rolesAndReponsibilities = scope;
         
         List<Id> applicationID = new List<Id>();
         List<RolesAndResponsibilities__c> lstRoleResp = new List<RolesAndResponsibilities__c>();
         Map<Id,Id> appOwnerId = new Map<Id,Id>();
         
         List<AccountShare> accountShare = new List<AccountShare>();        
         List<Program__Share> progShare = new List<Program__Share>();
         List<Application__Share> lstApplicationShare= new List<Application__Share>();

         for(RolesAndResponsibilities__c role : rolesAndReponsibilities ){
            if(role.Application__c!=null && role.BusinessRole__c !='Owner'){
                Application__Share appShare = new Application__Share();
                appShare.ParentId = role.Application__c;
                appShare.UserOrGroupId = role.Name__c;
                appShare.AccessLevel = 'Edit';
                appShare.RowCause = Schema.Application__Share.RowCause.SharingforReviewandApproval__c;
                lstApplicationShare.add(appShare);  
                role.BatchSharing__c = false;  
            } 
            if(role.Application__c!=null && role.BusinessRole__c =='Owner'){
              appOwnerId.put(role.Application__c,role.Name__c);
            } 
            
         }
         
         List<Application__c> lstApp = [Select OwnerId from Application__c where Id in: appOwnerId.keyset()]; 
         
             for(Application__c app: lstApp){     
                System.debug('==== <<<<<< OWNER IS UPDATE >>>>>> ===='+appOwnerId.get(app.Id));     
                app.OwnerId =  appOwnerId.get(app.Id);
             }            
             
             try{
                 update lstApp;
              }Catch(Exception e){ 
                System.debug('==== <<<<<< OWNER IS UPDATE >>>>>> ===='+e);
              }
         
         if(lstApplicationShare != null && lstApplicationShare.size() > 0){
             SystemContextMethodsHelper SystemContextMethodsHelper = new SystemContextMethodsHelper();
             SystemContextMethodsHelper.upsertApplicationShare(lstApplicationShare); 
         }
         if(!rolesAndReponsibilities.isEmpty()){
             update rolesAndReponsibilities;
         } 
           System.debug('==== <<<<<<  BATCH JOB IS FINSHED  >>>>>> ====');
     }
     
     // global void finish(Database.BatchableContext BC){
         global override void finish(){
          System.debug('==== <<<<<<  BATCH JOB IS FINSHED  >>>>>> ====');
          scheduleMe();
       }
       
       global static void scheduleMe() {
        RolesAndResponsibilityRecordSharingBatch batch = new RolesAndResponsibilityRecordSharingBatch();
        
        Integer scheduleTime = GNT.KeyValueStoreHelper.getIntegerValue('OwnerChangeTime',true); 
        String cronExpression = GNT.BatchApexJobScheduler.prepareJobsSchTime(System.now(), 2); 
        String jobName = GNT.BatchApexJobScheduler.getUniqueJobName('RolesAndResponsibilityRecordSharingBatch');  

        if (!Test.isRunningTest()) {
            System.schedule(jobName, cronExpression, new GNT.BatchApexJobScheduler(batch, 1));
        }
    }
      
 }