UtahLiveDataTest/src/objects/AmendmentRequest__c.object
<CustomObject>
    <description>[Business] Stores all the change requests information</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Amendment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BudgetPeriod__c</fullName>
        <formula>TEXT(MONTH(AwardedBudgetPeriodStartDate__c)) + &apos;/&apos; + TEXT(DAY(AwardedBudgetPeriodStartDate__c)) + &apos;/&apos; + TEXT(YEAR(AwardedBudgetPeriodStartDate__c)) + &apos; To &apos; + TEXT(MONTH(AwardedBudgetPeriodEndDate__c)) + &apos;/&apos; + TEXT(DAY(AwardedBudgetPeriodEndDate__c)) + &apos;/&apos; + TEXT(YEAR(AwardedBudgetPeriodEndDate__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Budget Period</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipName>Amendment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Submitted to Applicant</fullName>
                </value>
                <value>
                    <fullName>Review by Grant Monitor</fullName>
                </value>
                <value>
                    <fullName>Review by Project Officer</fullName>
                </value>
                <value>
                    <fullName>Review by Program Manager</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Revised</fullName>
                </value>
                <value>
                    <fullName>Submitted for Internal Approval</fullName>
                </value>
                <value>
                    <fullName>Approved Internally</fullName>
                </value>
                <value>
                    <fullName>Approved by Grantor</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Amendment Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Change Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>BudgetPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Period</label>
        <referenceTo>BudgetPeriod__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent to Grantee Review</fullName>
                </value>
                <value>
                    <fullName>Grantee Accepted</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>FINOPS Completed</fullName>
                </value>
                <value>
                    <fullName>Sent to FINOPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BudgetPeriod__c.object
<CustomObject>
    <description>[Business] This object stores all Budget Period Details.</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Budget Periods</relationshipLabel>
        <relationshipName>Budget_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BudgetPeriod__c</fullName>
        <formula>IF(AND(NOT(ISBLANK(BudgetStartDate__c )),NOT(ISBLANK(BudgetEndDate__c))),TEXT(MONTH( BudgetStartDate__c ))+&quot;/&quot; +TEXT(DAY(BudgetStartDate__c))+&quot;/&quot; +TEXT(YEAR(BudgetStartDate__c))+&quot;--&quot;+ TEXT(MONTH( BudgetEndDate__c ))+&quot;/&quot; +TEXT(DAY(BudgetEndDate__c))+&quot;/&quot; +TEXT(YEAR(BudgetEndDate__c)),&apos;&apos;)</formula>
        <label>Budget Period</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Budget Periods</relationshipLabel>
        <relationshipName>Budget_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this lookup is created to get the budget periods on the payment request budget grid.</description>
        <label>Payment Request</label>
        <referenceTo>PaymentRequest__c</referenceTo>
        <relationshipLabel>Budget Periods</relationshipLabel>
        <relationshipName>Budget_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Passive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Budget Period</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Budget Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Closeout__c.object
<CustomObject>
    <description>[Business] All the close out information is stored on this object</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Closeouts</relationshipLabel>
        <relationshipName>Closeouts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FOApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FO Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Closeouts6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Closeouts</relationshipLabel>
        <relationshipName>Closeouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>POApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PO Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Closeouts5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Closeout</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closeouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingSource__c.object
<CustomObject>
    <description>[Business] Details of the Funding sources which further creates Funding accounts</description>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Funding Sources</relationshipLabel>
        <relationshipName>Funding_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>BudgetPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Period</label>
        <referenceTo>BudgetPeriod__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PaymentRequest__c.object
<CustomObject>
    <description>[Business] Defines the details of for the Payment request.Payment request is done when award is already awarded and the Grantee wants to make use of the funds</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>PaymentRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BudgetPeriod__c</fullName>
        <formula>Award__r.BudgetStartEndDate__c</formula>
        <label>Budget Period</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Payment Request</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ProgressReports__c.object
<CustomObject>
    <description>[Business] Progress Report on the Grant/Award</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Progress Report</relationshipLabel>
        <relationshipName>Progress_Report</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Progress Report</relationshipLabel>
        <relationshipName>Progress_Report</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Progress Report</label>
    <nameField>
        <label>Progress Report ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Report</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/CloseoutRequestSubmissionHelper.cls
global with sharing class CloseoutRequestSubmissionHelper extends GNT.DynamicLayoutActionRedirect{ 
    public CloseoutRequestSubmissionHelper() {}
    List<String> errors = new List<String>(); 
    public CloseoutRequestSubmissionHelper(GNT.DynamicLayoutHolder layoutHolder) {
        this.layoutHolder = layoutHolder;
    }
    //global override PageReference whenClicked(){
    global override PageReference whenClicked(){

    	    system.debug('Inside CloseoutRequestSubmissionHelper '); 

        List<BudgetPeriod__c> budgetPeriodList;
        List<BudgetPeriod__c> allBudgetPeriodList = new List<BudgetPeriod__c>();
        List<Award__c> allAwardList = new List<Award__c>();
        List<Grant__c> allGrantList = new List<Grant__c>();
        List<AmendmentRequest__c> amendmentList = new List<AmendmentRequest__c>();
        List<PaymentRequest__c> paymentList = new List<PaymentRequest__c>();
        List<FundingSource__c> fundingSrcList = new List<FundingSource__c>();
        List<ProgressReports__c> reportList = new List<ProgressReports__c>();
        String msg;
        Set<Id> awardIds = new Set<Id>();
        Set<Id> grantIds = new Set<Id>(); 
        Map<Id,Closeout__c> grantCloseOut = new Map<Id,Closeout__c>();
        Map<Id,Closeout__c> awardCloseOut = new Map<Id,Closeout__c>();
        Closeout__c tempCloseout;
        try{
                String recordId = layoutHolder.recordId;
                Closeout__c req = [Select Id, Name, Title__c, Award__c, Grant__c,FOApprover__c, POApprover__c from Closeout__c where Id=:recordId limit 1];
                awardIds.add(req.Award__c);
                grantIds.add(req.Grant__c);
                grantCloseOut.put(req.Grant__c, req);
                awardCloseOut.put(req.Award__c, req);
                budgetPeriodList = [Select id, Status__c, Grant__c, Grant__r.Name, Name from BudgetPeriod__c where Grant__c in :grantIds and Status__c <> 'Closed'];
                allAwardList = [Select id, Status__c, Grant__r.Name, Name from Award__c where id in :awardIds];
                allGrantList = [Select id, Status__c, Name from Grant__c where id in :grantIds];
                amendmentList = [Select id,Name, Grant__c, Grant__r.Name from AmendmentRequest__c where Grant__c in :grantIds and Status__c <> 'Accepted'];
                paymentList = [Select id,Name, Grant__c, Grant__r.Name from PaymentRequest__c where Grant__c in :grantIds and Status__c <> 'Approved by Program Manager'];
                fundingSrcList = [Select id, Status__c, Grant__c, Grant__r.Name, Name from FundingSource__c where Grant__c in :grantIds and Status__c <> 'Closed'];
                reportList = [Select id, Status__c, Grant__r.Name, Name from ProgressReports__c where Award__c in :awardIds];
                
              /*  for(ProgressReports__c temp:reportList){
                    tempCloseout=grantCloseOut.get(temp.Grant__c);
                    //tempCloseout.addError('There is a pending Amendment Request '+temp.Name+' for the Closeout Request '+tempCloseout.Name);
                      errors.add('There is a pending Progress Report '+temp.Name+' for the Closeout Request '+tempCloseout.Name+' and for the Grant '+temp.Grant__r.Name);
                }
                
                for(AmendmentRequest__c temp:amendmentList){
                    tempCloseout=grantCloseOut.get(temp.Grant__c);
                    //tempCloseout.addError('There is a pending Amendment Request '+temp.Name+' for the Closeout Request '+tempCloseout.Name);
                         errors.add('There is a pending Amendment Request '+temp.Name+' for the Closeout Request '+tempCloseout.Name+' and for the Grant '+temp.Grant__r.Name);
                 }
                for(PaymentRequest__c temp:paymentList){
                    tempCloseout=grantCloseOut.get(temp.Grant__c);
                   
                        errors.add('There is a pending Payment Request '+temp.Name+' for the Closeout Request '+tempCloseout.Name+' and for the Grant '+temp.Grant__r.Name);
                    }
                for(BudgetPeriod__c temp:budgetPeriodList){
                     tempCloseout=grantCloseOut.get(temp.Grant__c);
                        errors.add('Please Close the Budget Period '+temp.Name+' for the Closeout Request '+tempCloseout.Name+' and for the Grant '+temp.Grant__r.Name);
                     }
                
                 for(FundingSource__c temp:fundingSrcList){
                   tempCloseout=grantCloseOut.get(temp.Grant__c);
                         errors.add('Please Close the Funding Source '+temp.Name+' for the Closeout Request '+tempCloseout.Name+' and for the Grant '+temp.Grant__r.Name);
                   }*/
                
                       if(req.POApprover__c == null){
                           // errors.add(' Please assign the Program Approver in the Roles and Responsibilities Section');
                           errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-90696'));
                        }
                      if(req.FOApprover__c == null){
                           // errors.add(' Please assign the Fiscal Approver in the Roles and Responsibilities Section');
                           errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-55723'));
                        }
                   
                if(errors.size() > 0){
                    for(String error: errors){
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, error));
                    }
                 return null;
                 }else{
                    GNT.TaskCreationHandler.createApprovalProcessTasks(req.Id, 'Approve Closeout Request', req.Name, null, System.TODAY() + 7, req.Title__c, true);
                    // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Closeout has been successfully submitted for Approval'));
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-83597')));
                    PageReference pf = Page.CloseoutRequestView;
                    pf.getParameters().put('id', req.Id);
                    pf.setRedirect(true);
                    return pf;
                }
                    
             
        } catch(Exception e){
           // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error in submitting closeout for approval'));
           ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-20509')));  
           system.debug('error seen '+e);      
            return null;
        }
    }
}