UtahLiveDataTest/src/objects/AmendmentRequest__c.object
<CustomObject>
    <description>[Business] Stores all the change requests information</description>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>Purpose</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Amendment Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Change Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestBudgetRevisionApproval.cls
@isTest
private with sharing class TestBudgetRevisionApproval{

    static testMethod void testExecute() {

        AmendmentRequestTriggerHelper.skipTrigger=true;
        USBEAnnouncementTriggerHelper.skipTrigger=true;
        ApplicationTriggerHelperUSBE.skipTrigger=true;
        ApplicationTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(true);
        
        AmendmentRequest__c amendreq=new AmendmentRequest__c();
        amendreq.impact__c='test';
        amendreq.purpose__c='test';
        insert amendreq;

        BudgetRevisionApproval budrevapproval=new BudgetRevisionApproval();  
       budrevapproval.selectedRecordId=amendreq.ID;
        budrevapproval.selectedAction='Approve';
       

        System.runAs(u){
            Test.startTest();  
            budrevapproval.execute();
            budrevapproval.selectedAction='Reject';
            budrevapproval.execute();
            Test.stopTest();
        }

    }
    
  }