UtahLiveDataTest/src/objects/AmendmentRequest__c.object
<CustomObject>
    <description>[Business] Stores all the change requests information</description>
    <fields>
        <fullName>AwardName__c</fullName>
        <formula>Award__r.GrantAwardName__c</formula>
        <label>Award Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Amendment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipName>Amendment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PercentVarianceOverTen__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If percent variance &gt; 10%, return true</description>
        <label>PercentVarianceOverTen</label>
        <type>Checkbox</type>
    </fields>
    <label>Amendment Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Change Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendment Requests</pluralLabel>
    <recordTypes>
        <fullName>BudgetRevision</fullName>
        <active>true</active>
        <label>Budget Revision</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>ApprovedInternally__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the budget revision is approved internally, return true so that if external approval is needed it can run</description>
        <label>ApprovedInternally</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Final Approver for the Award</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awards4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AwardedAmount__c</fullName>
        <formula>ObligatedAwardAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Awarded Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BudgetNarrativeRead__c</fullName>
        <description>Running explanation/justification of budget. Read only.</description>
        <label>BudgetNarrativeRead</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>BudgetNarrativeWrite__c</fullName>
        <description>Running explanation/justification of Budget. Read/Write.</description>
        <label>BudgetNarrativeWrite</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>BudgetRevisionInitiatedByUSBE__c</fullName>
        <label>BudgetRevisionInitiatedByUSBE</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated By USBE</fullName>
                    <default>true</default>
                    <label>Not Initiated By USBE</label>
                </value>
                <value>
                    <fullName>Indirect Change</fullName>
                </value>
                <value>
                    <fullName>Allocation Change</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BudgetRevisionInitiated__c</fullName>
        <label>BudgetRevisionInitiated</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CurrentApprovedBudgetSum__c</fullName>
        <label>CurrentApprovedBudgetSum</label>
        <summarizedField>AwardBudgetCategory__c.CurrentApprovedBudgetAmount__c</summarizedField>
        <summaryForeignKey>AwardBudgetCategory__c.Award__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CurrentBudgetRevisionId__c</fullName>
        <label>CurrentBudgetRevisionId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrentRevisionStatus__c</fullName>
        <defaultValue>&quot;Not Started&quot;</defaultValue>
        <label>CurrentRevisionStatus</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GrantAwardName__c</fullName>
        <label>Award Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PercentVarianceOverTen__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If percent variance &gt; 10%, return true</description>
        <label>PercentVarianceOverTen</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProposedBudgetRevisionSum__c</fullName>
        <label>ProposedBudgetRevisionSum</label>
        <summarizedField>AwardBudgetCategory__c.ProposedBudgetRevision__c</summarizedField>
        <summaryForeignKey>AwardBudgetCategory__c.Award__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <description>This Classifies whether it is Grantor or Grantee</description>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>InternalOrganization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Grants (Internal Organization)</relationshipLabel>
        <relationshipName>Grants1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RolesAndResponsibilities__c.object
<CustomObject>
    <description>[Business] Roles and Responsibilities defined for all the objects like Opportunity ,Application etc</description>
    <fields>
        <fullName>AmendmentRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Amendment Request</label>
        <referenceTo>AmendmentRequest__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BusinessRole__c</fullName>
        <description>This is a picklist which will be displayed in RR table in all phases.</description>
        <label>Business Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BusinessRole</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>RolesandResponsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Roles and Responsibilities</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles and Responsibilities</pluralLabel>
    <recordTypes>
        <fullName>Award</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Award.</description>
        <label>Award</label>
    </recordTypes>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Program.</description>
        <label>Program</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/SubmitBudgetRevisionToGrantor.cls
global with sharing class SubmitBudgetRevisionToGrantor extends GNT.FlexTableActionHandler{
    
    public class ReviewerExistanceException extends Exception {}
    public class BudgetNarrativeException extends Exception {}
    public class ProposedBudgetNotEqualApprovedBudgetException extends Exception {}

    
    global override Map<String,Object> clickHandler(){
        Savepoint savestate = Database.setSavepoint();
        Map<String,Object> retVal = new Map<String,Object>();
        String recordId = urlParams.get('id'); //Current award's Id
        
        try{
            Award__c currentAward = [SELECT Id, CreatedDate, CurrentApprovedBudgetSum__c, ProposedBudgetRevisionSum__c, BudgetRevisionInitiated__c, BudgetNarrativeRead__c, BudgetNarrativeWrite__c, Name, GrantAwardName__c, ApprovedInternally__c , PercentVarianceOverTen__c, CurrentBudgetRevisionId__c, Grant__r.InternalOrganization__c, BudgetRevisionInitiatedByUSBE__c, AwardedAmount__c, Approver__c  FROM Award__c WHERE Id =: recordId]; //Gets the current award, which submitted this budget revision
            System.debug('MANUALDEBUG >>> currentAward: ' + currentAward);
            DateTime revisionDate = DateTime.now();
            Boolean percentVarianceOverTen = false;
            Boolean equipmentTotalOver5k = false;
            
            /*
            //Need to have a written budget narrative in order to submit the revision
            if (currentAward.BudgetNarrativeWrite__c == '' || currentAward.BudgetNarrativeWrite__c == null) {
                throw new BudgetNarrativeException('In order to submit the budget revision, a budget narrative explaining and/or justifying the revision must be provided.');
            }
            //Approvers must be assigned in order to send for approver
            List<RolesAndResponsibilities__c> programRandR = new List<RolesAndResponsibilities__c>([
                SELECT Award__r.Id, BusinessRole__c, Name__c 
                FROM RolesAndResponsibilities__c 
                WHERE Award__r.Id =: recordId AND (BusinessRole__c =: 'Program Approver' OR BusinessRole__c =: 'Owner' OR BusinessRole__c =: 'Fiscal Approver' OR BusinessRole__c =: 'Legal Approver' OR BusinessRole__c =: 'Executive Approver') LIMIT 5]);
            if (programRandR.size() < 5) {
                throw new ReviewerExistanceException('In order to submit the budget revision for approval, you must have the Program Approver, Fiscal Approver, Legal Approver, Executive Approver, and Owner roles in the Roles tab'); 
            }
            else if (currentAward.Approver__c == null) {
                throw new ReviewerExistanceException('In order to submit the budget revision for approval, you must have an Internal Approver assigned to the award.'); 
            }
            //You cannot have the proposed budget not equal the current approved budget UNLESS USBE changed the allocation amount
            if (currentAward.BudgetRevisionInitiatedByUSBE__c == 'Allocation Change' && currentAward.ProposedBudgetRevisionSum__c != currentAward.AwardedAmount__c) {
                throw new ProposedBudgetNotEqualApprovedBudgetException('This revision has been initated by a USBE allocation amount change. You cannot submit a budget revision unless your proposed budget grand total is equal to the new allocated (awarded) amount.'); 
            }
            else if (currentAward.BudgetRevisionInitiatedByUSBE__c != 'Allocation Change' && currentAward.ProposedBudgetRevisionSum__c != currentAward.CurrentApprovedBudgetSum__c) {
                throw new ProposedBudgetNotEqualApprovedBudgetException('You cannot submit a revision if the proposed budget grand total does not equal the currently approved budget grand total');
            }
            */
            //We have already sent it for and got internal approval and it falls under the USBE approval validation
            if (currentAward.ApprovedInternally__c == true && currentAward.PercentVarianceOverTen__c == true) {
                //Send it off for USBE (external) approval
                AmendmentRequest__c budgetRevision = [SELECT Id, Name, AwardName__c FROM AmendmentRequest__c WHERE Id =: currentAward.CurrentBudgetRevisionId__c];
                GNT.TaskCreationHandler.createApprovalProcessTasks(budgetRevision.Id, 'Budget Revision Approval Request', budgetRevision.Name, null, System.TODAY() + 7, budgetRevision.AwardName__c, true);
                currentAward.CurrentRevisionStatus__c = 'Submitted to Grantor';
                update currentAward;
                retVal.put('Message','Budget revision successfully submitted for USBE approval');
                return retVal;
            }
        }
        /*
        catch(ReviewerExistanceException e) {
            Database.rollback(savestate);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            retVal.put('Message', e.getMessage());
            return retVal;
        }
        catch(BudgetNarrativeException e) {
            Database.rollback(savestate);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            retVal.put('Message', e.getMessage());
            return retVal;
        }
        catch (ProposedBudgetNotEqualApprovedBudgetException e) {
            Database.rollback(savestate);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            retVal.put('Message', e.getMessage());
            return retVal;
        }
        */
        catch(Exception e){
            Database.rollback(savestate);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            retVal.put('Message', e.getMessage());
            return retVal;
        }
        
        retVal.put('PageReference','/apex/awardview?id=' + recordId);
        retVal.put('Message','Budget revision successfully submitted');
        return retVal;
    }
}