UtahLiveDataTest/src/objects/AmendmentRequest__c.object
<CustomObject>
    <description>[Business] Stores all the change requests information</description>
    <fields>
        <fullName>AmendmentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Amendment Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Amendment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AwardName__c</fullName>
        <formula>Award__r.GrantAwardName__c</formula>
        <label>Award Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Amendment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BudgetPeriodChange__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Budget Period Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BudgetPeriodExtension__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Budget Period Extension</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContactChangeDescription__c</fullName>
        <description>Explanation for Change of contact</description>
        <label>Contact Change Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipName>Amendment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Justification__c</fullName>
        <label>Justification</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>KeyContactChange__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Key Contact Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KeyPOC__c</fullName>
        <formula>Award__r.Grant__r.GranteePOC__r.FirstName + &apos; &apos; +  Award__r.Grant__r.GranteePOC__r.LastName</formula>
        <label>Key POC</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewBudgetPeriodEndDate__c</fullName>
        <label>New Budget Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewGranteePOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Amendment_Requestsi42b</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewKeyPOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Key POC</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountRecordType__c</field>
                <operation>equals</operation>
                <value>Recipient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Amendment Requests (New Key POC)</relationshipLabel>
        <relationshipName>Change_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewKeyPersonnel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NewKeyPersonnel</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Amendment_Requests6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NoCostExtension__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No Cost Extension</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OtherChangeDescription__c</fullName>
        <description>Description of the Change</description>
        <label>Other Change Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OtherChange__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Description of the Change</description>
        <label>Other Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>Purpose</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <formula>RecordType.Name</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalFederalAmountDifference__c</fullName>
        <label>TotalFederalAmountDifference</label>
        <summarizedField>AmendmentRequestBudgetCategory__c.AwardedAmountDifference__c</summarizedField>
        <summaryForeignKey>AmendmentRequestBudgetCategory__c.AmendmentRequest__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalMatchAmountDifference__c</fullName>
        <label>TotalMatchAmountDifference</label>
        <summarizedField>AmendmentRequestBudgetCategory__c.MatchAmountDifference__c</summarizedField>
        <summaryForeignKey>AmendmentRequestBudgetCategory__c.AmendmentRequest__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Amendment Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Change Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendment Requests</pluralLabel>
    <recordTypes>
        <fullName>BudgetRevision</fullName>
        <active>true</active>
        <label>Budget Revision</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AmendmentRequestBudgetCategory__c.object
<CustomObject>
    <description>[Business] Object used to store all the requests for the Budget category Amendments ,(Need to revisit)</description>
    <fields>
        <fullName>AmendmentRequest__c</fullName>
        <label>Amendment Request</label>
        <referenceTo>AmendmentRequest__c</referenceTo>
        <relationshipLabel>AmendmentRequest Budget Categories</relationshipLabel>
        <relationshipName>AmendmentRequestBudget_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CurrentAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Awarded Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GrantorAmount__c</fullName>
        <label>GrantorAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Amendment Request Budget Category</label>
    <nameField>
        <label>AmendmentRequestBudgetCategory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AmendmentRequest Budget Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AmendmentRequestPriorApproval__c.object
<CustomObject>
    <description>[Business] Junction object between Amendment Request and Amendment Type</description>
    <fields>
        <fullName>AmendmentRequest__c</fullName>
        <label>Amendment Request</label>
        <referenceTo>AmendmentRequest__c</referenceTo>
        <relationshipLabel>Amendment Request Prior Approvals</relationshipLabel>
        <relationshipName>Amendment_Request_Prior_Approvals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AmendmentType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Amendment Type</label>
        <referenceTo>AmendmentType__c</referenceTo>
        <relationshipLabel>Amendment Request Prior Approvals</relationshipLabel>
        <relationshipName>Amendment_Request_Prior_Approvals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Justification__c</fullName>
        <label>Justification</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Amendment Request Prior Approval</label>
    <nameField>
        <displayFormat>ARPA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendment Request Prior Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AmendmentType__c.object
<CustomObject>
    <description>[Business]This object is a place holder for Approval Amendment Type which will follow the convention followed by HRSA. HRSA does not have classification when grouping types and currently follows only one type &apos;Prior Approval&apos;. GovGrants Amendment type classify types into three different types namely  
Prior Approval - Small change to the amendment which does not allow changes to Budget Period and Budget Cost
Formal Approval - Significant changes to Budget Time and/or Cost and results in new AWARD
Periodic/Continuous Renewals -</description>
    <label>MST: AmendmentType</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AmendmentTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>AmendmentType__c</fullName>
        <label>Amendment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Supplemental</fullName>
                </value>
                <value>
                    <fullName>Extension Without Funds</fullName>
                </value>
                <value>
                    <fullName>Admin Changes</fullName>
                </value>
                <value>
                    <fullName>Transfer of Award</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CurrentAmount__c</fullName>
        <formula>DirectAmount__c + IndirectAmount__c + TotalBudgetAdjustment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Awarded This Budget Period</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>KeyPOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Key POC</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodEndDate__c</fullName>
        <description>Project Period End Date for the award.</description>
        <label>Project Period End Date</label>
        <type>Date</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <recordTypes>
        <fullName>Grantee</fullName>
        <active>true</active>
        <description>This Classifies whether it is Grantor or Grantee</description>
        <label>Grantee</label>
    </recordTypes>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <description>This Classifies whether it is Grantor or Grantee</description>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>ProjectPeriodEndDate__c</fullName>
        <label>Project Period End Date</label>
        <type>Date</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <recordTypes>
        <fullName>Grantee</fullName>
        <active>true</active>
        <label>Grantee</label>
    </recordTypes>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RolesAndResponsibilities__c.object
<CustomObject>
    <description>[Business] Roles and Responsibilities defined for all the objects like Opportunity ,Application etc</description>
    <fields>
        <fullName>AmendmentRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Amendment Request</label>
        <referenceTo>AmendmentRequest__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BusinessRole__c</fullName>
        <description>This is a picklist which will be displayed in RR table in all phases.</description>
        <label>Business Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BusinessRole</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>RolesandResponsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Roles and Responsibilities</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles and Responsibilities</pluralLabel>
    <recordTypes>
        <fullName>AmendmentRequest</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Amendment Request.</description>
        <label>Amendment Request</label>
    </recordTypes>
    <recordTypes>
        <fullName>Grant</fullName>
        <active>true</active>
        <label>Grant</label>
    </recordTypes>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Program.</description>
        <label>Program</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/AmendmentRequestSubmissionHelper.cls
/*
* This action submission helper class validates the required fields supplied by the user
* before submitting AmendmentRequest
*
* @author: Sarat Mahavratayajula
*/
global with sharing class AmendmentRequestSubmissionHelper extends GNT.DynamicLayoutActionRedirect {
    private String appName = GNT.UserPreferenceHelper.getStringValue('ActiveAppName__c');
    List<String> errors = new List<String>();

    global override PageReference whenClicked() {

        system.debug('***App Name : ' + appName);
        Savepoint sp = Database.setSavepoint();
        AmendmentRequest__c amendmentRequest;
        Grant__c grantForAmendmentRequest;
        List<AmendmentRequestPriorApproval__c> amendmentRequestPriorApprovals;
        try {
            Id recordId = ApexPages.currentpage().getParameters().get('id');

            Map<Id, String> recordTypeMap = new Map<Id, String>();

            List<RecordType> amendmentRecordTypes = [select Id, Name, DeveloperName
                                                    FROM RecordType
                                                    where SobjectType = :AppUtils.getNamespacePrefix() + 'AmendmentRequest__c'];

            for (RecordType recordType : amendmentRecordTypes) {
                recordTypeMap.put(recordType.Id, recordType.DeveloperName);
            }

            List<RolesAndResponsibilities__c> amendRlsAndResps = [select Id, BusinessRole__c
                                                                    from RolesAndResponsibilities__c
                                                                    where AmendmentRequest__c = :recordId];

            boolean programApproverExists = false;
            boolean fiscalApproverExists = false;

            if (amendRlsAndResps.size() == 0) {
                //errors.add('Please add atleast one Roles and Responsibilities before submission');
                errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-40826'));
            }

            for (RolesAndResponsibilities__c role : amendRlsAndResps) {

                if (role.BusinessRole__c.equals('Program Approver')) {
                    programApproverExists = true;
                }

                if (role.BusinessRole__c.equals('Fiscal Approver')) {
                    fiscalApproverExists = true;
                }
            }

            //if (!programApproverExists) errors.add('Please add Program Approver');
            if (!programApproverExists) errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-46802'));

            //if (!fiscalApproverExists) errors.add('Please add Fiscal Approver');
            if (!fiscalApproverExists) errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-12195'));

            //if (appName == 'StateasGrantee' || appName == 'Recipient') {
            amendmentRequest = [select Id, Name,Award__c, AwardName__c, RecordType__c,NewGranteePOC__c,TotalFederalAmountDifference__c,TotalMatchAmountDifference__c, Purpose__c, Impact__c, AmendmentContact__c,
                                NoCostExtension__c, BudgetPeriodExtension__c, KeyContactChange__c, OtherChange__c,
                                NewBudgetPeriodEndDate__c, ContactChangeDescription__c, Award__r.Grant__c,
                                OtherChangeDescription__c, BudgetPeriodChange__c, Justification__c, KeyPOC__c,
                                NewKeyPOC__c, NewKeyPersonnel__c, RecordTypeId
                                from AmendmentRequest__c
                                where Id = :recordId];
            amendmentRequestPriorApprovals = [select Justification__c, AmendmentType__c
                                              from AmendmentRequestPriorApproval__c
                                              where AmendmentRequest__c = :recordId];
            

            //Id grantId = amendmentRequest.Award__r.Grant__c;

            

            //}

            //List<Attachment> attachments = [SELECT Id
            //                                FROM Attachment
            //                                WHERE ParentId = :recordId];

            //if (attachments.size() == 0) {
            //    // errors.add('Please add atleast one Attachment');
            //    errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTE-54874'));
            //}

            if (appName == 'StateasGrantee' && amendmentRequest.AmendmentContact__c == null) {
                // errors.add('Please add Amendment Contact before submission of the amendment request');
                errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-77866'));
            }

            if (recordTypeMap.get(amendmentRequest.RecordTypeId).equals('BudgetRevision')) {
                verifyAmendmentBudgetCategoriesTotal(amendmentRequest);
            }


            if (amendmentRequest.RecordType__c == 'Prior Approval') {
                for (AmendmentRequestPriorApproval__c amendmentRequestPriorApproval : amendmentRequestPriorApprovals) {

                    if (amendmentRequestPriorApproval.Justification__c == '' ||
                            amendmentRequestPriorApproval.Justification__c == null) {
                        //errors.add('Please add Justification before submission of the amendment request');
                        errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-72299'));
                    }
                }

                if (amendmentRequest.Purpose__c == null) {
                    //errors.add('Please add Purpose before submission of the amendment request');
                    errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-11075'));
                }

                if (amendmentRequest.Impact__c == null) {
                    //errors.add('Please add Impact before submission of the amendment request');
                    errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-04841'));
                }

                if (amendmentRequestPriorApprovals.size() == 0) {
                    //errors.add('Please add missing Prior Approval Type before submission');
                    errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTE-14373'));
                }
            }

            if (amendmentRequest.RecordType__c == 'Formal Amendments') {

                grantForAmendmentRequest = [select ProjectPeriodEndDate__c
                                        from Grant__c
                                        where Id = :amendmentRequest.Award__r.Grant__c];

                Date grantProjectEndDate = grantForAmendmentRequest.ProjectPeriodEndDate__c;

                boolean testValue = (amendmentRequest.NewBudgetPeriodEndDate__c > grantProjectEndDate);

                //if (amendmentRequest.NewBudgetPeriodEndDate__c != null &&
                //        amendmentRequest.NewBudgetPeriodEndDate__c > grantProjectEndDate) {
                //    //errors.add('You are attempting to change the budget period end date. Please see your' +
                //    //   ' System Administrator to change the Project End Date in the Grant before you can continue');
                //    errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-49126'));
                //}

                if (!amendmentRequest.NoCostExtension__c && !amendmentRequest.BudgetPeriodExtension__c
                        && !amendmentRequest.KeyContactChange__c && !amendmentRequest.OtherChange__c && !amendmentRequest.BudgetPeriodChange__c) {
                    //errors.add('Please check atleast one : No Cost extension, BudgetPeriodExtension,' +
                    //          'Key contact change or Other change');
                    errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-16578'));
                }

                //if((amendmentRequest.BudgetPeriodExtension__c || amendmentRequest.BudgetPeriodChange__c) && (amendmentRequest.TotalMatchAmountDifference__c ==0 && amendmentRequest.TotalFederalAmountDifference__c == 0)){
                //    errors.add('Please add the new budget.');
                //}

                //if (amendmentRequest.NoCostExtension__c && amendmentRequest.NewBudgetPeriodEndDate__c == null ||
                //        amendmentRequest.NewBudgetPeriodEndDate__c <> null && (!amendmentRequest.NoCostExtension__c &&
                //                !amendmentRequest.BudgetPeriodChange__c)) {
                //    //errors.add('Please Verify No Cost Extension budget period details');
                //    errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-26902'));
                //}

                if (amendmentRequest.OtherChange__c && amendmentRequest.OtherChangeDescription__c == null ||
                        amendmentRequest.OtherChangeDescription__c <> null && !amendmentRequest.OtherChange__c) {
                    //errors.add('Please verify Other information. ');
                    errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-43934'));

                }

                if ((amendmentRequest.NoCostExtension__c || amendmentRequest.BudgetPeriodExtension__c ||
                        amendmentRequest.BudgetPeriodChange__c) && (amendmentRequest.Justification__c == null)) {
                    //errors.add('Please add Justification for Budget and/or Cost changes');
                    errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-44443'));
                }

                if (appName == 'StateasGrantor') {
                    if (amendmentRequest.KeyContactChange__c && amendmentRequest.NewGranteePOC__c == null) {
                        errors.add('Please add New Key POC');
                        //errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTE-54874'));
                    }
                }
                if(amendmentRequest.BudgetPeriodExtension__c && amendmentRequest.NewBudgetPeriodEndDate__c !=null){
                    errors.add('Please choose Cost and Budget Period Change if you are changing Budget Period dates.');
                }

                if (appName == 'StateasGrantee') {
                    if (amendmentRequest.KeyContactChange__c && amendmentRequest.NewKeyPersonnel__c == null) {
                        //errors.add('Please add New Key POC');
                        errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-32923'));
                    }
                }
            }

            if (errors.size() > 0) {
                for (String error : errors) {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, error));
                }
            }

            else if (programApproverExists && fiscalApproverExists) {
                //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,
                //                                          'The Amendment request has been submitted successfully.'));
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-36393')));
                system.debug('*** sarat testing' + amendmentRequest.Id + ' --- ' + amendmentRequest.Name
                             + ' --- ' + amendmentRequest.AwardName__c);
                // To Recall the payment approval process in action and removing their pending tasks. ----- YST
                SystemContextMethodsHelper contexthelper = new SystemContextMethodsHelper();
                contexthelper.rejectProcess(amendmentRequest.Award__c);




                //--------------YST
                if (appName.contains('StateasGrantee')) {
                    system.debug('Grantee task creation');
                    GNT.TaskCreationHandler.createApprovalProcessTasks
                    (amendmentRequest.Id, 'Review Amendment Request', amendmentRequest.Name, null,
                     System.TODAY() + 7, amendmentRequest.AwardName__c, true);
                    system.debug('***Task successfully sent ***');
                } else {
                    system.debug('Grantor task creation');
                    GNT.TaskCreationHandler.createApprovalProcessTasks
                    (amendmentRequest.Id, 'Approval Amendment Request', amendmentRequest.Name, null,
                     System.TODAY() + 7, amendmentRequest.AwardName__c, true);
                    system.debug('***Task successfully sent ***');
                }



                PageReference p = Page.amendmentrequestview;
                p.getParameters().put('Id', amendmentRequest.Id);
                p.setRedirect(true);
                return p;

            }
            return null;
        } catch (Exception e) {
            Database.rollback(sp);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            return null;
        }
    }
    public void verifyAmendmentBudgetCategoriesTotal(AmendmentRequest__c amendmentRequest) {
        Decimal totalAwardedAmount = 0.0;
        Decimal totalGrantorAmount = 0.0;
        List<AmendmentRequestBudgetCategory__c> amdRequestBudgetCategories =
                                                            [select Id, Name, CurrentAmount__c, GrantorAmount__c
                                                             from AmendmentRequestBudgetCategory__c
                                                             where AmendmentRequest__c = :amendmentRequest.Id];

        for(AmendmentRequestBudgetCategory__c amdRequestBudgetCategory: amdRequestBudgetCategories) {
            totalAwardedAmount = totalAwardedAmount + (amdRequestBudgetCategory.CurrentAmount__c == null ? 0.0 : amdRequestBudgetCategory.CurrentAmount__c);
            totalGrantorAmount = totalGrantorAmount + (amdRequestBudgetCategory.GrantorAmount__c == null ? 0.0 : amdRequestBudgetCategory.GrantorAmount__c);
        }

        if (totalAwardedAmount != totalGrantorAmount) {
             errors.add('Total awarded amount and Total Grantor amount must match');
        }
    }
}