UtahLiveDataTest/src/objects/AmendmentRequest__c.object
<CustomObject>
    <description>[Business] Stores all the change requests information</description>
    <fields>
        <fullName>AmendmentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Amendment Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Amendment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Amendment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipName>Amendment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NewBudgetPeriodEndDate__c</fullName>
        <label>New Budget Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NoCostExtension__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No Cost Extension</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>Purpose</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Amendment Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Change Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestAmdRequestPriorApprovalEditCtrl.cls
@isTest
private class TestAmdRequestPriorApprovalEditCtrl {

    @isTest static void test() {
     
     UserTriggerHelper.skipTrigger = true;
     User u = TestHelper.getAdminUser(true);
        GranttriggerHelper.skipTrigger = true;
        UserTriggerHelper.skipTrigger = true;
        AmendmentRequestTriggerHelper.skipTrigger = true;
        Contact c = TestHelper.getcontact(true);
        Grant__c grant = TestHelper.getGrant(true);
        AwardTriggerHelper.skipTrigger = true;
        Award__c awd = TestHelper.getAwards(grant.Id,true);

        Id recordTypeId1 = TestHelper.getRecordType(Schema.Sobjecttype.AmendmentRequest__c,'Formal Amendments');
        AmendmentRequest__c amendmentRequest1 = new AmendmentRequest__c(RecordTypeId = recordTypeId1,
                                                                        Award__c=awd.Id,
                                                                        Purpose__c='Test Purpose',
                                                                        Impact__c='Test Impact',AmendmentContact__c=c.Id,
                                                                        NoCostExtension__c=true,
                                                                        NewBudgetPeriodEndDate__c=date.newInstance(2016,12,26));
        insert amendmentRequest1;

        Test.startTest();
            ApexPages.currentPage().getParameters().put('Id',amendmentRequest1.Id);
            ApexPages.currentPage().getParameters().put('amendmentId',amendmentRequest1.Id);
            ApexPages.StandardController stdController = new ApexPages.StandardController(amendmentRequest1);
            AmendmentRequestPriorApprovalEditCtrl amendmentRequestPriorApprovalEditCtrl = 
                                                        new AmendmentRequestPriorApprovalEditCtrl(stdController);
            amendmentRequestPriorApprovalEditCtrl.getKeyValueMap();
        Test.stopTest();
    }   
}