UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ApplicationRejectionHelperTest.cls
@isTest
public class ApplicationRejectionHelperTest {
    static testMethod void someTest() {
        AnnouncementTriggerHelper.skipTrigger = true;
        ApplicationTriggerHelper.skipTrigger = true;
        
        Announcement__c ann = TestHelper.getAnnouncement(true);
        Application__c a = TestHelper.getSubmittedApplication(ann.Id,true);
        ApexPages.currentPage().getParameters().put('id',a.id);
        ApplicationRejectionHelper e = new ApplicationRejectionHelper();
        e.whenClicked();
    }
}