UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/TermCondition__c.object
<CustomObject>
    <description>[Business] Terms and Conditions for Grants ,Awards (The lookup to Package may not be required in this case )</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Terms and Conditions</relationshipLabel>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubmissionType__c</fullName>
        <label>Submission Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Progress Report</fullName>
                </value>
                <value>
                    <fullName>Financial Report</fullName>
                </value>
                <value>
                    <fullName>Payment Request</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MST:Term and Condition</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/TermConditionSchedule__c.object
<CustomObject>
    <description>[Business] Schedule for the Terms and Conditions</description>
    <fields>
        <fullName>TermAndCondition__c</fullName>
        <label>Term and Condition</label>
        <referenceTo>TermCondition__c</referenceTo>
        <relationshipLabel>Term Condition Schedules</relationshipLabel>
        <relationshipName>Term_Condition_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Term Condition Schedule</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Term Condition Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Term Condition Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestExpenseReportScheduleViewCtrl.cls
@isTest
private with sharing class TestExpenseReportScheduleViewCtrl{
    static testMethod void testKeyValueMap() {
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          System.runAs(u){
          
              AnnouncementTriggerHelper.skipTrigger = true;
              Announcement__c ann = TestHelper.getAnnouncement(true);
              
              TermCondition__c termCond = TestHelper.getTermCondition(false,'Payment Request');
              termCond.SubmissionType__c='Payment Request';
              insert termCond;
              
              TermConditionSchedule__c termCondSch = new TermConditionSchedule__c();
              termCondSch.TermAndCondition__c = termCond.Id;
              insert termCondSch;

               
              Test.startTest();
              ExpenseReportScheduleViewCtrl ctrl = new ExpenseReportScheduleViewCtrl();
              ctrl.getKeyValueMap();
              Test.stopTest();
          }
        
    }
    
}