UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewGroup__c.object
<CustomObject>
    <description>[Business] This object summarizes number of Applications/Pre-Applications and number of Review Steps. As discussed with Shiva, Shah, Davinder , this object can not removed sometime later when possible.</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity ID</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Review Groups</relationshipLabel>
        <relationshipName>Review_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Review Group</label>
    <nameField>
        <displayFormat>RG-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>IsExternalUser__c</fullName>
        <formula>IF (ContactId != null, TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is External User</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/QualifiedOpportunityViewCtrl.cls
public with sharing class QualifiedOpportunityViewCtrl {
    
    //Properties Please configure template.
    public  ID recordId{get;set;}
    public  ID programId {get;set;}
    private Boolean rfaParameter;
    public  string templateName {get;set;}
    public  string packageName {get;set;}
    public boolean isExternal {get;set;}
    private String annType ;
    boolean isInternal;
    public QualifiedOpportunityViewCtrl(ApexPages.StandardController stdController){
          system.debug('-----------------------------------------------QualifiedOpportunityViewCtrl -------------------------------');
        recordId = ApexPages.CurrentPage().getParameters().get('id');
        String tmplName = ApexPages.CurrentPage().getParameters().get('templateName');
        User u = [SELECT id,Name,IsExternalUser__c FROM User WHERE Id=:UserInfo.getUserId()];
        
       templateName = 'QualifiedAnnoucementExternalGrantor';
     
        
    }
    
    public string getKeyValueMap(){
        Map<String,String> keyValueMap = new Map<String,String>();

        String announcementId= ApexPages.currentPage().getParameters().get('announcementId');
     
        
        keyValueMap.put('announcementId',announcementId); 
        keyValueMap.put('programId',programId); 


        return JSON.serialize(keyValueMap);
    }
    public string getListParams(){
        Map<String,List<String>> listParams = new Map<String,List<String>>();
        String announcementid = ApexPages.currentPage().getParameters().get('id');
        if(announcementid != null && announcementid != ''){
            Map<Id,ReviewGroup__c> reviewGroupsMap = new Map<Id,ReviewGroup__c>([SELECT Id FROM ReviewGroup__c WHERE Announcement__c =:announcementid]);
            List<String> reviewGroupIdsList = new List<String>();
            for(Id rgId:reviewGroupsMap.keySet()){
                reviewGroupIdsList.add((String)rgId);    
            }
            listParams.put('reviewGroupIdsList',reviewGroupIdsList);
        }

        return JSON.serialize(listParams);
    }
    
}