UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>AnnouncementName__c</fullName>
        <description>Title of the announcement.</description>
        <label>Announcement Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConstructionPackageValue__c</fullName>
        <formula>IF(ISPICKVAL(Budget_Category_Package__c , &apos;Construction&apos;) , &apos;Construction&apos;, &apos;Non construction&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Construction Package Value</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EstimatedFundedAmount__c</fullName>
        <label>Estimated Request Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EstimatedProjectPeriodEndDate__c</fullName>
        <description>Estimated project period end date for the prospective awards.</description>
        <label>Estimated Project Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EstimatedProjectPeriodStartDate__c</fullName>
        <description>Estimated project period start date for the prospective awards.</description>
        <label>Estimated Project Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExpectedTotalAwardAmount__c</fullName>
        <label>Expected Total Award Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FOAReviews__c</fullName>
        <defaultValue>0</defaultValue>
        <label>FOA Reviews</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FinancialApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Funding_Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HaveWeReceivedAwardFromProgram__c</fullName>
        <label>HaveWeReceivedAwardFromProgram</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PreApplicationRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre-Application Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProbabilityofWinningreceivingaGrant__c</fullName>
        <label>Probability of winning/receiving a grant</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0%</fullName>
                </value>
                <value>
                    <fullName>10%</fullName>
                </value>
                <value>
                    <fullName>20%</fullName>
                </value>
                <value>
                    <fullName>30%</fullName>
                </value>
                <value>
                    <fullName>40%</fullName>
                </value>
                <value>
                    <fullName>50%</fullName>
                </value>
                <value>
                    <fullName>60%</fullName>
                </value>
                <value>
                    <fullName>70%</fullName>
                </value>
                <value>
                    <fullName>80%</fullName>
                </value>
                <value>
                    <fullName>90%</fullName>
                </value>
                <value>
                    <fullName>100%</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProgramApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Funding_Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StateProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Opportunities (State Program)</relationshipLabel>
        <relationshipName>Announcements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>- In Progress - The information within the annoucement is incomplete. Such records shall not be avaiable for other users to view or edit.
- Review In Progress - Annoucements that are currently in the process of undergoing review shall have this status. Such records shall not be avaiable for other users to view or edit.
- Inactive - Approved annoucements whose Posting Date is in the future shall have this status. Such annoucements shall not be made available to recipient users.
- Active - Approved annoucements whose Posting Date is equal to the current date or is in the past and the Closing Date is in the future shall have this status. System shall make such annoucements available to recipients.
- Expired - Approved annoucements whose closing date is the current date or is in the past shall have this status. When an annoucement status changes from Active to Expired, it should no longer be made available to the recipient users.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Converted to Application</fullName>
                </value>
                <value>
                    <fullName>Converted to Pre-Application</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Approved</fullName>
                </value>
                <value>
                    <fullName>RFA Published</fullName>
                </value>
                <value>
                    <fullName>RFA Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BudgetPeriod__c.object
<CustomObject>
    <description>[Business] This object stores all Budget Period Details.</description>
    <fields>
        <fullName>BudgetPeriod__c</fullName>
        <formula>IF(AND(NOT(ISBLANK(BudgetStartDate__c )),NOT(ISBLANK(BudgetEndDate__c))),TEXT(MONTH( BudgetStartDate__c ))+&quot;/&quot; +TEXT(DAY(BudgetStartDate__c))+&quot;/&quot; +TEXT(YEAR(BudgetStartDate__c))+&quot;--&quot;+ TEXT(MONTH( BudgetEndDate__c ))+&quot;/&quot; +TEXT(DAY(BudgetEndDate__c))+&quot;/&quot; +TEXT(YEAR(BudgetEndDate__c)),&apos;&apos;)</formula>
        <label>Budget Period</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FundingOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Budget Periods</relationshipLabel>
        <relationshipName>Budget_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Passive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Budget Period</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Budget Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BusinessPackage__c.object
<CustomObject>
    <description>[Business]  This object associates the Package with the Program or Opportunity</description>
    <fields>
        <fullName>FundingOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PackageConfig__c</fullName>
        <label>Package Config</label>
        <referenceTo>GNT__Package__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PackageType__c</fullName>
        <label>Package Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Pre-Application</fullName>
                </value>
                <value>
                    <fullName>App-Review</fullName>
                </value>
                <value>
                    <fullName>Award</fullName>
                </value>
                <value>
                    <fullName>Amendment Request</fullName>
                </value>
                <value>
                    <fullName>Progress Report</fullName>
                </value>
                <value>
                    <fullName>Site Visit</fullName>
                </value>
                <value>
                    <fullName>Payment Request</fullName>
                </value>
                <value>
                    <fullName>Closeout</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Risk Assessment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Business Package</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RolesAndResponsibilities__c.object
<CustomObject>
    <description>[Business] Roles and Responsibilities defined for all the objects like Opportunity ,Application etc</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BusinessRole__c</fullName>
        <description>This is a picklist which will be displayed in RR table in all phases.</description>
        <label>Business Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BusinessRole</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Sent For Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Roles and Responsibilities</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles and Responsibilities</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Application.</description>
        <label>Application</label>
    </recordTypes>
    <recordTypes>
        <fullName>Award</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Award.</description>
        <label>Award</label>
    </recordTypes>
    <recordTypes>
        <fullName>Grant</fullName>
        <active>true</active>
        <label>Grant</label>
    </recordTypes>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Opportunity.</description>
        <label>Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Program.</description>
        <label>Program</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/FundingOpportunitySubmissionHelper.cls
global with sharing class FundingOpportunitySubmissionHelper extends GNT.DynamicLayoutActionRedirect{
    
    global override PageReference whenClicked(){
    Savepoint sp = Database.setSavepoint(); 
    List<String> errors = new List<String>();   
    List<BusinessPackage__c> preapplicationpackage;
    try{
            Id recordId = apexpages.currentpage().getparameters().get('id');
            List<RolesAndResponsibilities__c> lstRolesResposiblities = [Select Id,BusinessRole__c from RolesAndResponsibilities__c where Announcement__c =:recordId ];
            Announcement__c announcement = [Select Id,name,AnnouncementName__c,ConstructionPackageValue__c ,ProgramApprover__c,FinancialApprover__c,EstimatedFundedAmount__c,StateProgram__c,FOAReviews__c,Status__c,HaveWeReceivedAwardFromProgram__c,PreApplicationRequired__c,
                                             EstimatedProjectPeriodStartDate__c,EstimatedProjectPeriodEndDate__c ,ProbabilityofWinningreceivingaGrant__c,ExpectedTotalAwardAmount__c from Announcement__c where Id =:recordId];
            List<BudgetPeriod__c> budPeriod = [Select Id, Status__c,FundingOpportunity__c  from BudgetPeriod__c where FundingOpportunity__c  =: recordId];
            system.debug('**announcement'+announcement.AnnouncementName__c);
            if(announcement.PreApplicationRequired__c){
                 preapplicationpackage = [Select Id,FundingOpportunity__c,PackageType__c from BusinessPackage__c where 
                                                               FundingOpportunity__c =:recordId and PackageType__c = 'Pre-Application' ];
            }
           
            List<BusinessPackage__c> applicationpackage = [Select Id,FundingOpportunity__c,PackageType__c,PackageConfig__c  from BusinessPackage__c where 
                                                               FundingOpportunity__c =:recordId and PackageType__c = 'Application' ];
        
           
            boolean programApproverExists = false;
            Boolean submitRecord = false;  
            Boolean stateProgramExists = false;   
            Boolean numberOfReviews = false;
            Boolean financialApproverExists = false;  
            Integer count = 0;
            
            if(announcement.ProgramApprover__c != null){
                programApproverExists = true;
            }
            if(announcement.FinancialApprover__c != null){
                financialApproverExists = true;
            }
            if(announcement.StateProgram__c != null){
                stateProgramExists = true;
            }
            if(announcement.FOAReviews__c != 0 ){
                numberOfReviews = true;
            }
            if(budPeriod.size()>0){
              for(BudgetPeriod__c bud: budPeriod){
                if(bud.Status__c == 'Active'){
                  count++;
                }
              }
            }

            if(announcement.Status__c == 'Reviewed' && 
                                  (announcement.HaveWeReceivedAwardFromProgram__c == null || announcement.ProbabilityofWinningreceivingaGrant__c == null || 
                                   announcement.ExpectedTotalAwardAmount__c == null) ){
                //errors.add('Evaluation tab: Please Enter Have we previously received an award from this sponsoring agency/program?,Probability of winning/receiving a Grant Award,Expected total Award Amount' );
                errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTE-51730'));
            }
            if(announcement.EstimatedProjectPeriodStartDate__c == null ){
                errors.add(GNT.ErrorMessageHelper.fetchMessage('P17-GRNTE-78302'));
            }
            if(announcement.EstimatedFundedAmount__c == null || announcement.EstimatedFundedAmount__c == 0){
                // errors.add('Financial Tab:Please Enter Estimated Requested Amount Greater than 0');
                errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-64157'));
            }
             if(announcement.EstimatedProjectPeriodEndDate__c == null ){
                errors.add(GNT.ErrorMessageHelper.fetchMessage('P17-GRNTE-52851'));
            }
            if(announcement.EstimatedProjectPeriodStartDate__c > announcement.EstimatedProjectPeriodEndDate__c ){
                errors.add(GNT.ErrorMessageHelper.fetchMessage('P17-GRNTE-60652'));
            }
            
            if(programApproverExists == false){
                  //errors.add('A Program Approver must exist for the Opportunity.');
                  errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTE-24500'));
            }
            if(financialApproverExists == false){
                  //errors.add('A Financial Approver must exist for the Opportunity.');
                  errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-63213'));
            } 
            if(stateProgramExists == false){
                  //errors.add('A State Program must exist for the Opportunity.');
                  errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTE-51162'));
            }
            if(applicationpackage.size() < 1){
                  //errors.add('Application Package is needed for the Opportunity.');
                  errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTE-32223'));
            }
             if(announcement.PreApplicationRequired__c == true && preapplicationpackage.size()<1 ){
                errors.add(GNT.ErrorMessageHelper.fetchMessage('P32-GRNTE-19146'));
             } 
            
            if(numberOfReviews == false){
                 //errors.add('At least one Review is required for Opportunity before it is submitted for Approval.');
                 errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTE-31805'));
            }
            if(count == 0){
              errors.add(GNT.ErrorMessageHelper.fetchMessage('P17-GRNTE-39059'));
            }
            if(count>1){
              errors.add(GNT.ErrorMessageHelper.fetchMessage('P17-GRNTE-52534'));
            }
            if(applicationpackage.size()>0){
              List<GNT__PackageFormConfig__c > packForms = [Select Id,GNT__FormConfig__r.GNT__DisplayName__c from GNT__PackageFormConfig__c where GNT__PackageConfig__c =:applicationpackage[0].PackageConfig__c];
              for(GNT__PackageFormConfig__c pack:packForms){
                //System.debug('Package Name --->'+pack.GNT__FormConfig__r.Name);
                if(announcement.ConstructionPackageValue__c == 'Construction' && pack.GNT__FormConfig__r.GNT__DisplayName__c == 'SF 424: Budget Information Non Construction Form'){      
                  errors.add(GNT.ErrorMessageHelper.fetchMessage('P51-GRNTE-67159'));
                }
                else if(announcement.ConstructionPackageValue__c == 'Non construction' && pack.GNT__FormConfig__r.GNT__DisplayName__c == 'SF 424: Budget Information Construction Form'){        
                  errors.add(GNT.ErrorMessageHelper.fetchMessage('P31-GRNTE-86347'));
                }
              }
            }

            if(errors.size() > 0){
                for(String error: errors){
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, error));
                } 
            }
            else{
                //GNT.TaskCreationHandler.createApprovalProcessTasks(announcement.Id, 'Approve the Opportunity', announcement.AnnouncementName__c, null, System.TODAY() + 7,  true); 
                GNT.TaskCreationHandler.createApprovalProcessTasks(announcement.Id, 'Approve the Opportunity', announcement.Name, null, System.TODAY() + 7, announcement.AnnouncementName__c,true);         
                // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Funding Opportunity has been submitted successfully.'));
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-61979')));
                PageReference  pageref = Page.AnnouncementView;   
                pageref.getParameters().put('Id',recordId);
                pageref.setRedirect(true);  
                return pageref;
            }
            return null;
        }catch(Exception e){
         Database.rollback(sp);
         ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
         return null;   
        }
    }   
}