UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestApplicationServiceAreaEditCtrl.cls
/**
  
    **********************************************************
    Audit History
    **********************************************************
    9/22/2015              swati singh    created
    **********************************************************  
*/
@IsTest
private with sharing class TestApplicationServiceAreaEditCtrl {
    @IsTest
    private static void testInsert() {
         UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
        TestHelper.createCustomSettings(true);
        ApplicationTriggerHelper.skipTrigger = true;
              
       
        
        System.runAs(u) { 
         
                //Prepare test data
                Announcement__c ann = testHelper.getAnnouncement(true); 
                Application__c app = testHelper.getApplication(ann.id,true);
                ApexPages.CurrentPage().getParameters().put('id', app.Id);  
                ApexPages.StandardController stdController = new ApexPages.StandardController(app);
                //Execute test
                Test.startTest();
                ApplicationServiceAreaEditCtrl asaec = new ApplicationServiceAreaEditCtrl(stdController);
                asaec.getKeyValueMap();
                Test.stopTest();
        
                  //Assert test data

                 System.assertEquals(asaec, asaec);
        }
    }
}