UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>ProgramApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Funding_Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BusinessPackage__c.object
<CustomObject>
    <description>[Business]  This object associates the Package with the Program or Opportunity</description>
    <label>Business Package</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStepTemplate__c.object
<CustomObject>
    <description>[Business] Template defined for a Step Review , Previous Name (Review Step Template)</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link the announcement record.</description>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>ReviewStepTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review Step Template</label>
    <nameField>
        <label>Review Step Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Step Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RolesAndResponsibilities__c.object
<CustomObject>
    <description>[Business] Roles and Responsibilities defined for all the objects like Opportunity ,Application etc</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BusinessRole__c</fullName>
        <description>This is a picklist which will be displayed in RR table in all phases.</description>
        <label>Business Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BusinessRole</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Area</label>
        <referenceTo>ServiceArea__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>RolesandResponsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Roles and Responsibilities</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles and Responsibilities</pluralLabel>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Program.</description>
        <label>Program</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ServiceArea__c.object
<CustomObject>
    <description>[Business] Master list of all the Service Area information is stored in this object , Service areas are also applicable to the Announcements ,Programs,Application via Junction objects</description>
    <label>Project/Service Area</label>
    <nameField>
        <displayFormat>PSA-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <formula>FirstName + &quot; &quot; + LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestAnnouncementSubmissionHelper.cls
/**
 * Copyright REI Systems 2014 - 2016 
 * Test class for AnnouncementSubmissionHelper
 * Test the functionality that the given Announcement can be submitted successfully for approval
 * Positive Test case -
 * Negative Test case -   
 */
@isTest(seealldata =  false)
private with sharing class TestAnnouncementSubmissionHelper {

      static testMethod void testWhenClicked() {  
       Announcement__c ann=null;
       ReviewStepTemplate__c review = null;
       BusinessPackage__c businessPack = null;
       UserTriggerHelper.skipTrigger = true;
       User u = new User(Id=UserInfo.getUserId());
        
        System.runAs(u){
            GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
            AnnouncementTriggerHelper.skipTrigger=true;
            ann=TestHelper.getGrantorAnnouncement(true);
           
            
            GNT.TriggerHelper.skipTrigger=true;
            RolesAndResponsibilitiesTriggerHelper.skipTrigger=true;
            
            ServiceArea__c serviceArea = TestHelper.getServiceArea(true);
 
            List<RolesAndResponsibilities__c> rolesAndResp = new List<RolesAndResponsibilities__c>();          
              
            RolesAndResponsibilities__c rolesAndResponsibilities2 = new RolesAndResponsibilities__c(Announcement__c = ann.Id,
                                                                            BusinessRole__c='Key POC',Name__c = ann.ProgramApprover__c);  
            RolesAndResponsibilities__c rolesAndResponsibilities3 = new RolesAndResponsibilities__c(Announcement__c = ann.Id,
                                                                            BusinessRole__c='Program Approver',Name__c = ann.ProgramApprover__c);
                                                                            

            rolesAndResp.add(rolesAndResponsibilities2);
            rolesAndResp.add(rolesAndResponsibilities3);
            insert rolesAndResp;
      
            Test.setCurrentPageReference(new PageReference('Page.AnnouncementView'));        
        }
        
        Test.startTest();
        AnnouncementSubmissionHelper annHelper = new AnnouncementSubmissionHelper();
        ApexPages.currentPage().getParameters().put('id', ann.Id);
        annHelper.whenClicked();
        Test.stopTest();
        
    }  
        
    
    static testMethod void testWhenClicked2() {  
       Account acct = null;
       Announcement__c ann=null;
       UserTriggerHelper.skipTrigger = true;
       User u = new User(Id=UserInfo.getUserId());
        
        System.runAs(u){
            GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
                   
            AnnouncementTriggerHelper.skipTrigger=true;
            GNT.TriggerHelper.skipTrigger=true;
            RolesAndResponsibilitiesTriggerHelper.skipTrigger=true; 
            ann=TestHelper.getGrantorAnnouncement(true);
        }
        
        Test.startTest();
        AnnouncementSubmissionHelper annHelper = new AnnouncementSubmissionHelper();
        ApexPages.currentPage().getParameters().put('id', ann.Id);
        annHelper.whenClicked();
        Test.stopTest();
        
    }  
}