UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewGroup__c.object
<CustomObject>
    <description>[Business] This object summarizes number of Applications/Pre-Applications and number of Review Steps. As discussed with Shiva, Shah, Davinder , this object can not removed sometime later when possible.</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity ID</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Review Groups</relationshipLabel>
        <relationshipName>Review_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NumberOfReviewSteps__c</fullName>
        <defaultValue>4</defaultValue>
        <inlineHelpText>User defined - total number of review steps for an application or pre-application based on record type.</inlineHelpText>
        <label>Number of Review Steps Allowed</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Review Group</label>
    <nameField>
        <displayFormat>RG-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStep__c.object
<CustomObject>
    <description>[Business] Defines all the details of Review Step defined in the Review of Application/Pre-Application</description>
    <fields>
        <fullName>ReviewGroup__c</fullName>
        <label>Review Group</label>
        <referenceTo>ReviewGroup__c</referenceTo>
        <relationshipLabel>Review Steps</relationshipLabel>
        <relationshipName>Review_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StepNumber__c</fullName>
        <label>Step Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Review Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestReviewAppSendtoFinalConfirmHelper.cls
@isTest
private with sharing class TestReviewAppSendtoFinalConfirmHelper{
    static testMethod void testclickHandler() {
        User u = TestHelper.getAdminUser(true);
        System.runAs(u){
            AnnouncementTriggerHelper.skipTrigger = true;
            ReviewStepTriggerHelper.skipTrigger = true;
            PanelUserTriggerHelper.skipAll = true;
            GNT.TriggerHelper.skipTrigger = true;
            List<String> IdSet = new List<String>();
            
            Announcement__c ann = TestHelper.getAnnouncement(true);
            ReviewGroup__c reviewGroup = new ReviewGroup__c();
            reviewGroup.Announcement__c = ann.id;
            reviewGroup.NumberOfReviewSteps__c= Decimal.valueOf('2.0');
            insert reviewGroup;

            ReviewStep__c reviewStep = new ReviewStep__c();
            reviewStep.ReviewGroup__c = reviewGroup.id;
            reviewStep.Name = 'Step 1';
            reviewStep.StepNumber__c = 1;
            insert reviewStep;
        
            
            IdSet.add(reviewStep.Id);
            
            Test.startTest();
            ReviewAppSendtoFinalConfirmHelper ctrl = new ReviewAppSendtoFinalConfirmHelper();
            ctrl.urlParams.put('id',reviewStep.Id);
            ctrl.selectedRecordIds = IdSet;
            ctrl.clickHandler();
            Test.stopTest();
        
         }
    }
}