UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AnnouncementFundingAccount__c.object
<CustomObject>
    <description>[Business]  Funding Accounts associated with the opportunity</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>Announcement</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FundingAccount__c</fullName>
        <label>Funding Account</label>
        <referenceTo>FundingAccount__c</referenceTo>
        <relationshipLabel>Funding Opportunity Funding Accounts</relationshipLabel>
        <relationshipName>Announcement_Funding_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Opportunity Funding Account</label>
    <nameField>
        <displayFormat>AFA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Opportunity Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingAccount__c.object
<CustomObject>
    <description>[Business] Funding account details Funding accounts are created from Funding sources</description>
    <fields>
        <fullName>FundingSource__c</fullName>
        <label>Funding Source</label>
        <referenceTo>FundingSource__c</referenceTo>
        <relationshipLabel>Funding Accounts</relationshipLabel>
        <relationshipName>Funding_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingSource__c.object
<CustomObject>
    <description>[Business] Details of the Funding sources which further creates Funding accounts</description>
    <label>Funding Source</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestAnnouncementFundingAccountsHelper.cls
@isTest
private with sharing class TestAnnouncementFundingAccountsHelper{
    static testMethod void testClickHandler() {
          
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          
          System.runAs(u){
          AnnouncementTriggerHelper.skipTrigger = true;
          UserTriggerHelper.skipTrigger = true;
          List<String> IdSet = new List<String>();
          List<Id> newSet = new List<Id>();
          
          Announcement__c ann = TestHelper.getAnnouncement(true);
          FundingSource__c fundSrc = TestHelper.getFundingSource(true);
          FundingAccount__c fundAcc = TestHelper.getFundingAccount(true,fundSrc.Id);
          IdSet.add(fundAcc.Id);
          AnnouncementFundingAccount__c annfundAcc = new AnnouncementFundingAccount__c(Announcement__c=ann.Id,FundingAccount__c=fundAcc.Id); 
         
          Test.startTest();
          AnnouncementFundingAccountsHelper ctrl = new AnnouncementFundingAccountsHelper();
          ctrl.urlparams.put('announcementId',ann.Id);
          ctrl.selectedIds = newSet;
          ctrl.selectedRecordIds=IdSet;
          ctrl.clickHandler();
          Test.stopTest();
        
      }
        
    }
    
        static testMethod void testClickHandler2() {
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          
          System.runAs(u){
          AnnouncementTriggerHelper.skipTrigger = true;
          UserTriggerHelper.skipTrigger = true;
          
          List<String> IdSet = new List<String>();
          List<Id> newSet = new List<Id>();
          
          Announcement__c ann = TestHelper.getAnnouncement(true);
          FundingSource__c fundSrc = TestHelper.getFundingSource(true);
          FundingAccount__c fundAcc = TestHelper.getFundingAccount(true,fundSrc.Id);
          AnnouncementFundingAccount__c annfundAcc = new AnnouncementFundingAccount__c(Announcement__c=ann.Id,FundingAccount__c=fundAcc.Id); 
         
          Test.startTest();
          AnnouncementFundingAccountsHelper ctrl = new AnnouncementFundingAccountsHelper();
          ctrl.urlparams.put('announcementId',ann.Id);
          ctrl.selectedIds = newSet;
          ctrl.selectedRecordIds=IdSet;
          ctrl.clickHandler();
          Test.stopTest();
        
      }
        
    }

          static testMethod void testClickHandler3() {
          
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          
          System.runAs(u){
          AnnouncementTriggerHelper.skipTrigger = true;
          UserTriggerHelper.skipTrigger = true;
          
          List<String> IdSet = new List<String>();
          List<Id> newSet = new List<Id>();
          
          Test.startTest();
          AnnouncementFundingAccountsHelper ctrl = new AnnouncementFundingAccountsHelper();
          ctrl.selectedRecordIds=IdSet;
          ctrl.clickHandler();
          Test.stopTest();
        
      }
        
    }
    
}