UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A unique id to relate the announcement to the program.</description>
        <label>Program ID</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestAddAnnouncementDocumentCtrl.cls
@isTest
private with sharing class TestAddAnnouncementDocumentCtrl{
    static testMethod void testController() {
/*
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          Account acct = null;
          
          System.runAs(u){
            AnnouncementTriggerHelper.skipTrigger = true;
            ProgramTriggerHelper.skipTrigger = true;
            UserTriggerHelper.skipTrigger = true;
            GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
            AccountTriggerHelper.skipTrigger=true;
            
            acct = TestHelper.getAccount(true);
            Announcement__c ann = TestHelper.getAnnouncement(true);
            Program__c pgm = TestHelper.getProgram(acct.Id,true);
          
         
            Test.startTest();
            ApexPages.currentPage().getParameters().put('announcementId',ann.id);
            ApexPages.currentPage().getParameters().put('programId',pgm.id);
            ApexPages.CurrentPage().getParameters().put('required','No');
            AddAnnouncementDocumentCtrl ctrl = new AddAnnouncementDocumentCtrl();
            ctrl.getKeyValueMap();
            ctrl.getListParams();
            ApexPages.CurrentPage().getParameters().put('required','true');
            AddAnnouncementDocumentCtrl ctrl1 = new AddAnnouncementDocumentCtrl();
            ctrl1.getKeyValueMap();
            Test.stopTest();
        }
    */    
    }
}