UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>AnnouncementType__c</fullName>
        <description>Announcement Type</description>
        <inlineHelpText>Type of Announcement</inlineHelpText>
        <label>Announcement Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Competitive</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Sole Source/Directed</fullName>
                </value>
                <value>
                    <fullName>Formula Grants</fullName>
                </value>
                <value>
                    <fullName>Sole Source/Formula</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>- In Progress - The information within the annoucement is incomplete. Such records shall not be avaiable for other users to view or edit.
- Review In Progress - Annoucements that are currently in the process of undergoing review shall have this status. Such records shall not be avaiable for other users to view or edit.
- Inactive - Approved annoucements whose Posting Date is in the future shall have this status. Such annoucements shall not be made available to recipient users.
- Active - Approved annoucements whose Posting Date is equal to the current date or is in the past and the Closing Date is in the future shall have this status. System shall make such annoucements available to recipients.
- Expired - Approved annoucements whose closing date is the current date or is in the past shall have this status. When an annoucement status changes from Active to Expired, it should no longer be made available to the recipient users.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Converted to Application</fullName>
                </value>
                <value>
                    <fullName>Converted to Pre-Application</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Approved</fullName>
                </value>
                <value>
                    <fullName>RFA Published</fullName>
                </value>
                <value>
                    <fullName>RFA Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AnnouncementServiceArea__c.object
<CustomObject>
    <description>[Business]  Service Area associated with an Annoucement</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>RelatedServiceAreas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Opportunity Project Area</label>
    <nameField>
        <displayFormat>ASA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Opportunity Project Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/AnnouncementServiceAreaTriggerHelper.cls
global with sharing class AnnouncementServiceAreaTriggerHelper extends GNT.TriggerHelper{
    global override void processBeforeDelete(){
        preventDelete();
    }
    
    private void preventDelete(){
        List<Id> annIdList = new List<Id>();
        Set<Id> annIdSet = new Set<Id>();
        Map<Id, Set<id>> anndIdToSAIdMap = new Map<Id, Set<id>>();
        for(AnnouncementServiceArea__c annSA : (List<AnnouncementServiceArea__c>)trigger.old){
            annIdSet.add(annSA.Announcement__c);
            Set<Id> annSAIdSet = anndIdToSAIdMap.get(annSA.Announcement__c);
            if(annSAIdSet == null){
                annSAIdSet = new Set<Id>();
            }
            annSAIdSet.add(annSA.Id);
            anndIdToSAIdMap.put(annSA.Announcement__c, annSAIdSet);
        }
        annIdList.addAll(annIdSet);
        List<Announcement__c> annList = [Select Id, Status__c, AnnouncementType__c From Announcement__c Where Id IN : annIdList AND AnnouncementType__c = 'Sole Source' AND Status__c = 'Active'];
        for(Announcement__c ann : annList){
            Set<Id> annSASet = anndIdToSAIdMap.get(ann.Id);
            if(annSASet != null){
                for(Id annSA : annSASet){
                    //trigger.oldMap.get(annSA).addError('Can not remove Service area as the Funding Opportunity is Published.');
                    trigger.oldMap.get(annSA).addError(GNT.ErrorMessageHelper.fetchMessage('P51-GRNTR-07571'));
                }
            }
        }
    }
}