UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A unique id to relate the announcement to the program.</description>
        <label>Program ID</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BusinessPackage__c.object
<CustomObject>
    <description>[Business]  This object associates the Package with the Program or Opportunity</description>
    <fields>
        <fullName>PackageConfig__c</fullName>
        <label>Package Config</label>
        <referenceTo>GNT__Package__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PackageType__c</fullName>
        <label>Package Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Pre-Application</fullName>
                </value>
                <value>
                    <fullName>App-Review</fullName>
                </value>
                <value>
                    <fullName>Award</fullName>
                </value>
                <value>
                    <fullName>Amendment Request</fullName>
                </value>
                <value>
                    <fullName>Progress Report</fullName>
                </value>
                <value>
                    <fullName>Site Visit</fullName>
                </value>
                <value>
                    <fullName>Payment Request</fullName>
                </value>
                <value>
                    <fullName>Closeout</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Risk Assessment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Package</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStepTemplate__c.object
<CustomObject>
    <description>[Business] Template defined for a Step Review , Previous Name (Review Step Template)</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link the announcement record.</description>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>ReviewStepTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to program record.</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>ReviewStepTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StepNumber__c</fullName>
        <label>Step Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Review Step Template</label>
    <nameField>
        <label>Review Step Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Step Templates</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ReviewStepTemplateEditCtrl.cls
public with sharing class ReviewStepTemplateEditCtrl {
    
    //Properties
    public ID recordId{get;set;}
    public PageReference savePage {get;set;}
    public PageReference cancelPage {get;set;}
    public String recordType {get;set;}
    public String packageId {get;set;}
    public String pageTemplateName {get;set;}
    public List<GNT.DynamicLayoutDefaultValueHelper> listDefaultValues {get;set;}
    
    public ReviewStepTemplateEditCtrl(ApexPages.StandardController stdController){
        recordId = ApexPages.CurrentPage().getParameters().get('id');   
        savePage = Page.ReviewStepTemplateView;
        savePage.getParameters().put('id', recordId);
        string programId = ApexPages.CurrentPage().getParameters().get('programid');
        string announcementId = ApexPages.CurrentPage().getParameters().get('announcementId');                  
        List<BusinessPackage__c> bizPkg = [Select Id,Name,PackageConfig__c from BusinessPackage__c where PackageType__c ='App-Review' limit 1];
        if(bizPkg!=null && bizPkg.size()>0){
                packageId=bizPkg[0].PackageConfig__c;
            }            
        pageTemplateName='ReviewStepTemplate';        
        ReviewStepTemplate__c reviewStepTemplate = (ReviewStepTemplate__c)stdController.getRecord();                        
        if(stdController.getId() != null){ // Edit existing
            recordType =  Schema.SObjectType.reviewStepTemplate__c.getRecordTypeInfosById().get(reviewStepTemplate.RecordTypeId).getName().toLowercase();
            listDefaultValues = new List<GNT.DynamicLayoutDefaultValueHelper>();
            cancelPage = Page.ReviewStepTemplateView;
            cancelPage.getParameters().put('id', recordId);
        }else{    // create New
            recordType = ApexPages.CurrentPage().getParameters().get('recordType').toLowercase();
            if(recordType != null){
                if(recordType == 'pre-application'){
                    reviewStepTemplate.RecordTypeId = Schema.SObjectType.ReviewStepTemplate__c.getRecordTypeInfosByName().get('Pre-Application').getRecordTypeId();
                }else if(recordType == 'application'){
                    reviewStepTemplate.RecordTypeId = Schema.SObjectType.ReviewStepTemplate__c.getRecordTypeInfosByName().get('Application').getRecordTypeId();
                }                
                listDefaultValues = new List<GNT.DynamicLayoutDefaultValueHelper>();
                GNT.DynamicLayoutDefaultValueHelper dv = new GNT.DynamicLayoutDefaultValueHelper('RecordTypeId',reviewStepTemplate.RecordTypeId,true);
                listDefaultValues.add(dv);
                if(programId != null){
                    GNT.DynamicLayoutDefaultValueHelper dv1 = new GNT.DynamicLayoutDefaultValueHelper(AppUtils.getNamespacePrefix()+'Program__c',programId,true);
                    listDefaultValues.add(dv1); 
                    List<AggregateResult> aggResultList = [SELECT COUNT(Id) cnt FROM ReviewStepTemplate__c WHERE Program__c =:programId AND RecordTypeId =:reviewStepTemplate.RecordTypeId GROUP BY Program__c];
	                Integer stepNumber = 1;
	                if(aggResultList != null && aggResultList.size() > 0){
	                    stepNumber = (Integer)aggResultList[0].get('cnt');
	                    stepNumber = stepNumber + 1;
	                }
	                GNT.DynamicLayoutDefaultValueHelper dv2 = new GNT.DynamicLayoutDefaultValueHelper(AppUtils.getNamespacePrefix()+'StepNumber__c',stepNumber,true);
	                listDefaultValues.add(dv2);
                    pageTemplateName='ReviewStepTemplate';
                }                  
                if(announcementId != null){
                    GNT.DynamicLayoutDefaultValueHelper dv1 = new GNT.DynamicLayoutDefaultValueHelper(AppUtils.getNamespacePrefix()+'Announcement__c',announcementId,true);
                    listDefaultValues.add(dv1); 
                    List<AggregateResult> aggResultList = [SELECT COUNT(Id) cnt FROM ReviewStepTemplate__c WHERE Announcement__c =:announcementId AND RecordTypeId =:reviewStepTemplate.RecordTypeId GROUP BY Announcement__c];	               
	                Integer stepNumber = 1;
	                if(aggResultList != null && aggResultList.size() > 0){
	                    stepNumber = (Integer)aggResultList[0].get('cnt');
	                    stepNumber = stepNumber + 1;
	                }
	                GNT.DynamicLayoutDefaultValueHelper dv2 = new GNT.DynamicLayoutDefaultValueHelper(AppUtils.getNamespacePrefix()+'StepNumber__c',stepNumber,true);
	                listDefaultValues.add(dv2);
                    pageTemplateName='ReviewStepTemplateAnn';
                }  
            }
            cancelPage = Page.ProgramView;
            cancelPage.getParameters().put('id', 'recordId');
        }      
           if(programId != null){
                 pageTemplateName='ReviewStepTemplate';
                }
           if(announcementId!=null){
                 pageTemplateName='ReviewStepTemplateAnn';
                }
          savePage.getParameters().put('programId', programId);
          savePage.getParameters().put('announcementId', announcementId);
    }
    
    public string getKeyValueMap(){
        Map<String,String> keyValueMap = new Map<String,String>();
        keyValueMap.put('reviewStepId',ApexPages.currentPage().getParameters().get('id'));       
        return JSON.serialize(keyValueMap);
    }        
}