UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>ApplicationDeadlineWithDateTime__c</fullName>
        <label>Application Deadline</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>AwardCeiling__c</fullName>
        <description>The lowest amount an applicant can request.</description>
        <label>Award Ceiling</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ClonedFrom__c</fullName>
        <label>Cloned From</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cloned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cloned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>InternalUniqueID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Uniquely identifies each record for data migration purpose only. It is auto populated by trigger in before insert context.</description>
        <externalId>true</externalId>
        <label>Internal Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>- In Progress - The information within the annoucement is incomplete. Such records shall not be avaiable for other users to view or edit.
- Review In Progress - Annoucements that are currently in the process of undergoing review shall have this status. Such records shall not be avaiable for other users to view or edit.
- Inactive - Approved annoucements whose Posting Date is in the future shall have this status. Such annoucements shall not be made available to recipient users.
- Active - Approved annoucements whose Posting Date is equal to the current date or is in the past and the Closing Date is in the future shall have this status. System shall make such annoucements available to recipients.
- Expired - Approved annoucements whose closing date is the current date or is in the past shall have this status. When an annoucement status changes from Active to Expired, it should no longer be made available to the recipient users.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Converted to Application</fullName>
                </value>
                <value>
                    <fullName>Converted to Pre-Application</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Approved</fullName>
                </value>
                <value>
                    <fullName>RFA Published</fullName>
                </value>
                <value>
                    <fullName>RFA Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>AwardCeiling__c</fullName>
        <label>AwardCeiling</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ClonedFrom__c</fullName>
        <description>Name of Application from where the record is cloned from?</description>
        <label>Cloned From</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cloned__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this record cloned?</description>
        <label>Cloned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FormsValidated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for validation of form depends upon percentage of form filled.</description>
        <label>Forms Validated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>InternalUniqueID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Uniquely identifies each record for data migration purpose only. It is auto populated by trigger in before insert context.</description>
        <externalId>true</externalId>
        <label>Internal Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProjectPeriodEndDate__c</fullName>
        <label>Project Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodStartDate__c</fullName>
        <description>Project Period Start Date as entered by the applicant.</description>
        <label>Project Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Review Initiated</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Submitted For Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Sent for Review</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision Completed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Rejection Initiated</fullName>
                </value>
                <value>
                    <fullName>Internally Reviewed</fullName>
                </value>
                <value>
                    <fullName>Converted to Award</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Converted to Grant</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Revision Initiated</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Approved Internally</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubmittedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitted By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubmittedOn__c</fullName>
        <description>Date when the application was submitted.</description>
        <label>Submitted On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The grantee entered title for the application.</description>
        <label>Project Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ApplicationBudgetCategory2__c.object
<CustomObject>
    <description>[Business] Stores the Budget related information associated with an Application</description>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application_Budget_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FormsValidated__c</fullName>
        <formula>Application__r.FormsValidated__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FormsValidated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>InternalUniqueID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Uniquely identifies each record for data migration purpose only. It is auto populated by trigger in before insert context.</description>
        <externalId>true</externalId>
        <label>Internal Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>text(Application__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Application Budget Category</label>
    <nameField>
        <displayFormat>AC-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Budget Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BudgetPeriod__c.object
<CustomObject>
    <description>[Business] This object stores all Budget Period Details.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Budget Periods</relationshipLabel>
        <relationshipName>Budget_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FundingOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Budget Periods</relationshipLabel>
        <relationshipName>Budget_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InternalUniqueID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Uniquely identifies each record for data migration purpose only. It is auto populated by trigger in before insert context.</description>
        <externalId>true</externalId>
        <label>Internal Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Passive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Budget Period</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Budget Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/OpportunityQualification__c.object
<CustomObject>
    <description>[Business] This is for a Sub Recipient to Mark an Announcement so that after some days he or she can create an application for the same announcement. This is created because there might be lots of announcement but sub recipient might be interested with only few announcement so he/she can mark it as qualified and later convert into an application</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Qualified Announcements</relationshipLabel>
        <relationshipName>Qualified_Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FundingOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>Opportunity_Sub_Recipient_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InternalUniqueID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Uniquely identifies each record for data migration purpose only. It is auto populated by trigger in before insert context.</description>
        <externalId>true</externalId>
        <label>Internal Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(FundingOpportunity__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Qualified Announcements</label>
    <nameField>
        <displayFormat>FO-{0000}</displayFormat>
        <label>Qualified Announcement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualified Announcements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ApplicationCloneHelper.cls
global without sharing class ApplicationCloneHelper {

    public ApplicationCloneHelper( ) {
    }

    global String cloneApplication(String recordId, Id annId) {
        ApplicationTriggerHelper.skipTrigger = true;
        ApplicationTriggerHelperUSBE.skipTrigger = true;
        ApplicationTriggerHelperUOVC.skipTrigger = true;
        ApplicationBudgetCategoryTriggerHelper.skipTrigger = true;
        Application__c currentRecord;
        Application__c newRecord;
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        String SobjectApiName = 'Application__c';
        String uniqueIdAPIName = 'InternalUniqueID__c';
        Map<String, Schema.SObjectField> fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();
        String commaSeparatedFields = '';
        for (String fieldName : fieldMap.keyset()) {
            if (!fieldName.equalsIgnorecase(uniqueIdAPIName) && !fieldName.equalsIgnoreCase('FormsValidated__c')) {
                if (commaSeparatedFields == null || commaSeparatedFields == '') {
                    commaSeparatedFields = fieldName;
                } else {
                    commaSeparatedFields = commaSeparatedFields + ', ' + fieldName;
                }
            }
        }
        String query = 'select ' + commaSeparatedFields + ' from ' + SobjectApiName + ' where Id = \'' + recordId + '\'';
        currentRecord = Database.query(query);



        currentRecord.Cloned__c = true;
        update currentRecord;
        newRecord = currentRecord.clone();
        newRecord.ClonedFrom__c = currentRecord.Name;
        newRecord.Status__c = 'Created';
        newRecord.Title__c = newRecord.Title__c + ' (Copy)';
        newRecord.ProjectPeriodStartDate__c = null;
        newRecord.ProjectPeriodEndDate__c = null;
        newRecord.OwnerId = UserInfo.getUserId();
        newRecord.SubmittedOn__c = null;
        newRecord.SubmittedBy__c = null;
        if (annId != null) {
            OpportunityQualification__c selectedOpp = [select id , name, FundingOpportunity__c, FundingOpportunity__r.AwardCeiling__c, FundingOpportunity__r.ApplicationDeadlineWithDateTime__c,
                                        FundingOpportunity__r.AwardFloor__c from OpportunityQualification__c where id = : annId limit 1];
            newRecord.Announcement__c = selectedOpp.FundingOpportunity__c;
            newRecord.AwardCeiling__c = selectedOpp.FundingOpportunity__r.AwardCeiling__c;
            newRecord.AwardFloor__c = selectedOpp.FundingOpportunity__r.AwardFloor__c;
            newRecord.ApplicationDeadlineWithDateTime__c = selectedOpp.FundingOpportunity__r.ApplicationDeadlineWithDateTime__c;
        }
        insert newRecord;

        SobjectApiName = 'BudgetPeriod__c';
        fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();
        commaSeparatedFields = '';
        for (String fieldName : fieldMap.keyset()) {
            if (!fieldName.equalsIgnorecase(uniqueIdAPIName)) {
                if (commaSeparatedFields == null || commaSeparatedFields == '') {
                    commaSeparatedFields = fieldName;
                } else {
                    commaSeparatedFields = commaSeparatedFields + ', ' + fieldName;
                }
            }
        }
        query = 'select ' + commaSeparatedFields + ' from ' + SobjectApiName + ' where Application__c = \'' + recordId + '\'';
        List<BudgetPeriod__c> bplist = Database.query(query);

        SobjectApiName = 'ApplicationBudgetCategory2__c';
        fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();
        commaSeparatedFields = '';
        for (String fieldName : fieldMap.keyset()) {
            if (!fieldName.equalsIgnorecase(uniqueIdAPIName) && !fieldName.equalsIgnoreCase('Federal__c') && !fieldName.equalsIgnoreCase('InKind__c') && !fieldName.equalsIgnoreCase('CashMatch__c') && !fieldName.equalsIgnoreCase('Amount__c')) {
                if (commaSeparatedFields == null || commaSeparatedFields == '') {
                    commaSeparatedFields = fieldName;
                } else {
                    commaSeparatedFields = commaSeparatedFields + ', ' + fieldName;
                }
            }
        }
        query = 'select ' + commaSeparatedFields + ' from ' + SobjectApiName + ' where Application__c = \'' + recordId + '\'';
        List<ApplicationBudgetCategory2__c> abclist = Database.query(query);

        Map<Id, List<ApplicationBudgetCategory2__c>> abcmap = new Map<Id, List<ApplicationBudgetCategory2__c>>();
        for (ApplicationBudgetCategory2__c abc : abclist) {
            List<ApplicationBudgetCategory2__c> tmp = abcmap.get(abc.BudgetPeriod__c);
            if (tmp == null) {
                tmp = new List<ApplicationBudgetCategory2__c>();
            }
            tmp.add(abc);
            abcmap.put(abc.BudgetPeriod__c, tmp);
        }

        List<GNT__AttachmentExtension__c> newattachmentlist = new List<GNT__AttachmentExtension__c>();
        List<BudgetPeriod__c> newbplist = new List<BudgetPeriod__c>();
        List<ApplicationBudgetCategory2__c> newabclist = new List<ApplicationBudgetCategory2__c>();

        for (GNT__AttachmentExtension__c attachment : [SELECT Name, GNT__Attachment__c, GNT__Classification__c,
                GNT__HistoryReason__c, GNT__ParentId__c FROM GNT__AttachmentExtension__c where GNT__ParentId__c = :recordId]) {
            GNT__AttachmentExtension__c newawdatt = attachment.clone();
            newawdatt.GNT__ParentId__c = newRecord.id;
            newattachmentlist.add(newawdatt);
        }

        for (BudgetPeriod__c bp : bplist) {
            BudgetPeriod__c newbp = bp.clone();
            newbp.Application__c = newRecord.Id;
            newbplist.add(newbp);
        }
        insert newattachmentlist;
        insert newbplist;

        Map<Id, BudgetPeriod__c> bptobpmap = new Map<Id, BudgetPeriod__c>();
        for (BudgetPeriod__c bp : bplist) {
            for (BudgetPeriod__c newbp : newbplist) {
                if (bp.BudgetPeriod__c == newbp.BudgetPeriod__c) {
                    bptobpmap.put(bp.Id, newbp);
                }
            }
        }

        for (BudgetPeriod__c bp : bplist) {
            BudgetPeriod__c newbp = bptobpmap.get(bp.Id);
            List<ApplicationBudgetCategory2__c> abcs = abcmap.get(bp.Id);
            for (ApplicationBudgetCategory2__c abc : abcs) {
                ApplicationBudgetCategory2__c newabc = abc.clone();
                newabc.Application__c = newbp.Application__c;
                newabc.BudgetPeriod__c = newbp.Id;
                newabc.BudgetAmountUSBE__c = 0;
                newabc.AdminCostValue__c = 0;
                newabclist.add(newabc);
            }
        }
        insert newabclist;

        return newRecord.Id;
    }
}