UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>AnnouncementName__c</fullName>
        <description>Title of the announcement.</description>
        <label>Announcement Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PointofContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Key POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Announcement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>- In Progress - The information within the annoucement is incomplete. Such records shall not be avaiable for other users to view or edit.
- Review In Progress - Annoucements that are currently in the process of undergoing review shall have this status. Such records shall not be avaiable for other users to view or edit.
- Inactive - Approved annoucements whose Posting Date is in the future shall have this status. Such annoucements shall not be made available to recipient users.
- Active - Approved annoucements whose Posting Date is equal to the current date or is in the past and the Closing Date is in the future shall have this status. System shall make such annoucements available to recipients.
- Expired - Approved annoucements whose closing date is the current date or is in the past shall have this status. When an annoucement status changes from Active to Expired, it should no longer be made available to the recipient users.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Converted to Application</fullName>
                </value>
                <value>
                    <fullName>Converted to Pre-Application</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Approved</fullName>
                </value>
                <value>
                    <fullName>RFA Published</fullName>
                </value>
                <value>
                    <fullName>RFA Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Grantee</fullName>
                </value>
                <value>
                    <fullName>Grantor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AnnouncementFundingAccount__c.object
<CustomObject>
    <description>[Business]  Funding Accounts associated with the opportunity</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>Announcement</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Opportunity Funding Account</label>
    <nameField>
        <displayFormat>AFA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Opportunity Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The internal approver for the application</description>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applicationsap2u</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChangeRequestStatus__c</fullName>
        <label>Change Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Revision Request Assigned</fullName>
                </value>
                <value>
                    <fullName>Revision Request Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DataEvaluator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DataEvaluator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalOrganization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Orgnanization which owns the Application This field is also used on the Forms as well</description>
        <inlineHelpText>Which organization owns the application?</inlineHelpText>
        <label>Applicant Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FormsValidated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for validation of form depends upon percentage of form filled.</description>
        <label>Forms Validated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GrantMonitor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GrantMonitor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectOfficer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Review Initiated</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Submitted For Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Sent for Review</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision Completed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Rejection Initiated</fullName>
                </value>
                <value>
                    <fullName>Internally Reviewed</fullName>
                </value>
                <value>
                    <fullName>Converted to Award</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Converted to Grant</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Revision Initiated</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Approved Internally</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ChangeRequest__c.object
<CustomObject>
    <description>[Business]  Currently used to track pre-award negotiation requests for application only. In the future this can be enhanced for other objects like award or something else.</description>
    <fields>
        <fullName>ApplicationTitle__c</fullName>
        <formula>Application__r.Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Application Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Negotiation Requests</relationshipLabel>
        <relationshipName>Change_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Negotiation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Change request comment are captured here.</description>
        <inlineHelpText>Change request comment are captured here.</inlineHelpText>
        <label>Description</label>
        <length>131070</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExternalOrganization__c</fullName>
        <formula>Application__r.ExternalOrganization__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>External Organization</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                    <default>true</default>
                    <label>Not Initiated</label>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Change</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Negotiation Request</label>
    <nameField>
        <displayFormat>CR-{000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Negotiation Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/InitiateSubmissionRequestFlexTable.cls
global class InitiateSubmissionRequestFlexTable extends GNT.FlexTableActionHandler{
    private Map<String,Object> resultMap;
    global override Map<String,Object> clickHandler(){
        List<Application__c> appList;
        List<ChangeRequest__c> changeReqList ;
        Application__c app;
        ChangeRequest__c changeReq;
        String displayMsg;
        resultMap = new Map<String,Object>();
        changeReqList = [Select Id,Status__c, Name, Type__c, DueDate__c,Comments__c, Application__c, ApplicationTitle__c
                          from ChangeRequest__c where id=:selectedRecordIds Limit 1];
        
        if(changeReqList.size() > 0 && changeReqList[0].Status__c == 'Not Initiated'){
            changeReq = changeReqList[0];            
            changeReq.Status__c='Initiated';            
            update changeReq; 
            appList = [Select id,Status__c, ChangeRequestStatus__c , DataEvaluator__c, GrantMonitor__c, 
                       ProjectOfficer__c, Announcement__r.AnnouncementName__c,ExternalOrganization__c,Approver__c,OwnerId
                       from Application__c Where id = :changeReq.Application__c Limit 1];
            if(appList.size()>0){
                app = appList[0];
                app.ChangeRequestStatus__c= 'Revision Request Assigned';
                app.FormsValidated__c = false;
                update app;
                List<User> userList = [SELECT Id,Email FROM User WHERE IsActive = true AND AccountId =: app.ExternalOrganization__c LIMIT 2 ];
                for(User u: userList){
                    GNT.TaskCreationHandler.createTasks(u.Id, changeReq.Id, 'Revision Request', app.Announcement__r.AnnouncementName__c, null, false, changeReq.DueDate__c, null, changeReq.ApplicationTitle__c, true);
                }
                User appUser = [SELECT Id, Email, AccountId, ContactId FROM User WHERE Id =: app.OwnerId];
                Map<Id, List<User>> accountIdMapUserList = new Map<Id, List<User>>();
                accountIdMapUserList.put(app.ExternalOrganization__c, new List<User>{appUser});
                AppUtils.TaskEmailWrapper taskEmailer = new AppUtils.TaskEmailWrapper();
                taskEmailer.setObjectList(changeReq.Id);
                taskEmailer.setUserList(appUser);
                taskEmailer.setAccountIdMapUserList(accountIdMapUserList);
                taskEmailer.setEmailTemplateDevName('Negotiation_Initiated');
                String resultMessage = taskEmailer.massSendEmail();
                ApplicationSnapshotHelper snapshot = new ApplicationSnapshotHelper();
                snapshot.createSnapshot(new List<Id>{app.id});
            }
            displayMsg='The Submission Request '+changeReq.Name+ ' is Initiated.';
        }
        resultMap.put('Message',displayMsg);
        return resultMap;
    }
}