UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestAnnouncementRelatedAppViewCtrl.cls
@isTest
private with sharing class TestAnnouncementRelatedAppViewCtrl{
    static testMethod void testController() {

          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          
          Account acct = null;
          
          System.runAs(u){
            AnnouncementTriggerHelper.skipTrigger = true;
            UserTriggerHelper.skipTrigger = true;
            Announcement__c ann = TestHelper.getAnnouncement(true);
            
            ApplicationTriggerHelper.skipTrigger = true;
            Application__c app = TestHelper.getApplication(ann.Id,true);
            
          
         
            Test.startTest();
            ApexPages.currentPage().getParameters().put('announcementId',ann.id);
            AnnouncementRelatedApplicationsViewCtrl ctrl = new AnnouncementRelatedApplicationsViewCtrl();
            ctrl.getListParameters();
            ctrl.flexTableHeader = 'Test Table';
            delete app;
            //AnnouncementRelatedApplicationsViewCtrl ctrl1 = new AnnouncementRelatedApplicationsViewCtrl();
            Test.stopTest();
        }
        
    }
}