UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>BudgetCategory__c</fullName>
        <description>Is Budget Category needed at Individual or Total Level?</description>
        <label>Budget Category Required?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget Category Level</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Overall Level</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Grantee</fullName>
                </value>
                <value>
                    <fullName>Grantor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The grantee entered title for the application.</description>
        <label>Project Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ApplicationBudgetCategory2__c.object
<CustomObject>
    <description>[Business] Stores the Budget related information associated with an Application</description>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application_Budget_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BudgetCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Category</label>
        <referenceTo>BudgetCategory__c</referenceTo>
        <relationshipName>Application_Budget_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT(BudgetCategory__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Application Budget Category</label>
    <nameField>
        <displayFormat>AC-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Budget Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BudgetCategory__c.object
<CustomObject>
    <description>[Business] This object stores the Master List of all the Budget categories</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Personnel</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Occupancy</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Supplies</fullName>
                </value>
                <value>
                    <fullName>Publication</fullName>
                </value>
                <value>
                    <fullName>IDC</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Fringe Benefits</fullName>
                </value>
                <value>
                    <fullName>Contracted Fees</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MST: Budget Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Category</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BuildUpItem__c.object
<CustomObject>
    <description>List of child records that add up to a Budget Category</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ApplicationBudgetCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Application Budget Category</description>
        <label>Application Budget Category</label>
        <referenceTo>ApplicationBudgetCategory2__c</referenceTo>
        <relationshipLabel>BuildUpItems</relationshipLabel>
        <relationshipName>BuildUpItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>TEXT(ApplicationBudgetCategory__r.BudgetCategory__r.Type__c)</description>
        <formula>IF(ApplicationBudgetCategory__c!=null,TEXT(ApplicationBudgetCategory__r.BudgetCategory__r.Type__c),IF(AmendmentRequestBudgetCategory__c!=null,TEXT(AmendmentRequestBudgetCategory__r.BudgetCategory__r.Type__c),Null))</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>Unit Price</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BuildUp Item</label>
    <nameField>
        <displayFormat>Item-{000}</displayFormat>
        <label>Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BuildUpItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestBuildupItemTriggerHelper.cls
@isTest(SeeAllData = true)
public class TestBuildupItemTriggerHelper {

    public static testMethod void myUnitTest() {
        UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
        AnnouncementTriggerHelper.skipTrigger = true;
        RolesandResponsibilitiesTriggerHelper.skipTrigger = true;
        ApplicationTriggerHelper.skipTrigger = true;
        Announcement__c ann = TestHelper.getAnnouncement(true);
        Application__c app = TestHelper.getApplication(ann.id,true);
        BudgetCategory__c bc = [Select id from BudgetCategory__c where Type__c = 'Personnel' limit 1];
        BudgetCategory__c bc1 = [Select id from BudgetCategory__c where Type__c = 'Training' limit 1];
        BudgetCategory__c bc2 = [Select id from BudgetCategory__c where Type__c = 'Travel' limit 1];
        ApplicationBudgetCategory2__c appbc = new ApplicationBudgetCategory2__c(Amount__c=1000000000,Application__c=app.id, BudgetCategory__c = bc.Id);
        insert appbc;
        ApplicationBudgetCategory2__c appbc1 = new ApplicationBudgetCategory2__c(Amount__c=1000000000,Application__c=app.id, BudgetCategory__c = bc1.Id);
        insert appbc1;
        ApplicationBudgetCategory2__c appbc2 = new ApplicationBudgetCategory2__c(Amount__c=1000000000,Application__c=app.id, BudgetCategory__c = bc2.Id);
        insert appbc2;
        System.runAs(u){
            BuildUpItem__c buildupitem = new BuildUpItem__c(ApplicationBudgetCategory__c=appbc.id,Quantity__c=2,Title__c='buidupitem1',UnitPrice__c=2);
            insert buildupitem;
            buildupitem.Quantity__c=3;
            update buildupitem; 
            delete buildupitem;
            BuildUpItem__c buildupitem1 = new BuildUpItem__c(ApplicationBudgetCategory__c=appbc1.id,Quantity__c=2,Title__c='buidupitem1',UnitPrice__c=2);
            BuildUpItem__c buildupitem2 = new BuildUpItem__c(ApplicationBudgetCategory__c=appbc2.id,Quantity__c=2,Title__c='buidupitem1',UnitPrice__c=2);
            Test.startTest();
            insert buildupitem1;
            insert buildupitem2;
            Test.stopTest();
        }
    }
}