UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/OpportunityQualification__c.object
<CustomObject>
    <description>[Business] This is for a Sub Recipient to Mark an Announcement so that after some days he or she can create an application for the same announcement. This is created because there might be lots of announcement but sub recipient might be interested with only few announcement so he/she can mark it as qualified and later convert into an application</description>
    <fields>
        <fullName>FundingOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>Opportunity_Sub_Recipient_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Qualified Announcements</label>
    <nameField>
        <displayFormat>FO-{0000}</displayFormat>
        <label>Qualified Announcement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualified Announcements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/StrategicPlan__c.object
<CustomObject>
    <description>[Business] Defines the Strategic plan for an Organization which owns the Application</description>
    <label>Strategic Plan</label>
    <nameField>
        <displayFormat>SPN-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestQualifyAnnouncementViewHelper.cls
@isTest
private class TestQualifyAnnouncementViewHelper {

    static testMethod void myUnitTest() {
    /*
        AnnouncementTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
            Announcement__c ann = TestHelper.getAnnouncement(true);
            List<String> selectedRecordIds = new List<String>();
            selectedRecordIds.add(ann.id);
            StrategicPlan__c obj = TestHelper.getStrategicPlan(true);
            OpportunityQualification__c oppqual = new OpportunityQualification__c(FundingOpportunity__c = ann.id);
            insert oppqual;
            
            QualifyAnnouncementViewHelper qualifyannhelper = new QualifyAnnouncementViewHelper();
            qualifyannhelper.selectedRecordIds = selectedRecordIds;
            qualifyannhelper.clickHandler(); 
            qualifyannhelper.qualifyAnnouncements(selectedRecordIds);           
        }
    */
    }
}