UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A unique id to relate the announcement to the program.</description>
        <label>Program ID</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>- In Progress - The information within the annoucement is incomplete. Such records shall not be avaiable for other users to view or edit.
- Review In Progress - Annoucements that are currently in the process of undergoing review shall have this status. Such records shall not be avaiable for other users to view or edit.
- Inactive - Approved annoucements whose Posting Date is in the future shall have this status. Such annoucements shall not be made available to recipient users.
- Active - Approved annoucements whose Posting Date is equal to the current date or is in the past and the Closing Date is in the future shall have this status. System shall make such annoucements available to recipients.
- Expired - Approved annoucements whose closing date is the current date or is in the past shall have this status. When an annoucement status changes from Active to Expired, it should no longer be made available to the recipient users.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Converted to Application</fullName>
                </value>
                <value>
                    <fullName>Converted to Pre-Application</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Approved</fullName>
                </value>
                <value>
                    <fullName>RFA Published</fullName>
                </value>
                <value>
                    <fullName>RFA Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodStartDate__c</fullName>
        <description>Project Period Start Date for the award.</description>
        <label>Project Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent to Grantee Review</fullName>
                </value>
                <value>
                    <fullName>Grantee Accepted</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>FINOPS Completed</fullName>
                </value>
                <value>
                    <fullName>Sent to FINOPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>GrantsAnn</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GrantAbbreviation__c</fullName>
        <description>Unique Abbreviation used for internal Financial System integration</description>
        <inlineHelpText>Unique Abbreviation used for internal Financial System integration</inlineHelpText>
        <label>Grant Abbreviation</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProgramCode</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodStartDate__c</fullName>
        <label>Project Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed/Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/SiteVisit__c.object
<CustomObject>
    <description>[Business] This object is used to store all the information related to the Site Visits which is a Post Award Activity.</description>
    <fields>
        <fullName>ActivityQuestion2__c</fullName>
        <label>ActivityQuestion2</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Site Visits</relationshipLabel>
        <relationshipName>SiteVisits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Site Visits</relationshipLabel>
        <relationshipName>Site_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Report Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Planned and Submitted to Subrecipient</fullName>
                </value>
                <value>
                    <fullName>Visited</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Report Submitted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Reviewed by Grantor</fullName>
                </value>
                <value>
                    <fullName>Sent to Subrecipient</fullName>
                </value>
                <value>
                    <fullName>Feedback from Subrecipient</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VisitEndDateTime__c</fullName>
        <description>Visit End Date and Time</description>
        <inlineHelpText>Visit End Date and Time</inlineHelpText>
        <label>Visit End Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/SiteVisitSchedule__c.object
<CustomObject>
    <description>[Business] Site Visit Schedule is stored on this specific object</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Site Visit Schedule</label>
    <nameField>
        <displayFormat>S-{YYYY}-{0000}</displayFormat>
        <label>Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visit Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestSiteVisitReportSubmissionHelper.cls
@isTest
private with sharing class  TestSiteVisitReportSubmissionHelper {
      
     @isTest(seealldata =  true)
    public static void testExternalLinksConfigLayoutEditCtrl(){
        UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
           AnnouncementTriggerHelper.skipTrigger=true;
           RolesAndResponsibilitiesTriggerHelper.skipTrigger=true;
           GrantTriggerHelper.skipTrigger=true;
           AwardTriggerHelper.skipTrigger=true;
           SiteVisitTriggerHelper.skipTrigger=true;

        System.runAs(u){
            Test.startTest();
            Announcement__c ann = TestHelper.getAnnouncement(true); 
            SiteVisitSchedule__c sitesch= TestHelper.getSiteVisitSchedule(true); 
             
           
            Grant__c grant = TestHelper.getGrant(false);
           grant.Status__c = 'Active';
           grant.ProjectPeriodStartDate__c=Date.today();
            grant.GrantAbbreviation__c='12345';
            
            
            //Grant__c grant = TestHelper.getGrant(false);
        //grant.Program__c = program.id;
        //grant.Status__c = 'Active';
       // grant.ProjectPeriodStartDate__c=Date.today();
      //  grant.NumberofProjectsFunded__c='1';
        insert grant;
            //insert grant;  
        Award__c award = TestHelper.getAwards(grant.Id,true);    
            SiteVisit__c site =TestHelper.getSiteVisit(false);
            site.Grant__c=grant.Id;
            site.VisitEndDateTime__c=DateTime.now();
           
            insert site;
            GNT__PageLayoutConfig__c pagelayoutConfig= null;
            pagelayoutConfig = TestHelper.getPageLayoutConfig(true,'SiteVisit__c');
            GNT.DynamicLayoutHolder layoutHolder = new GNT.DynamicLayoutHolder(pageLayoutConfig.id, site.Id,true);
            //ApexPages.CurrentPage().getParameters().put('id', site.Id);
        
            SiteVisitReportSubmissionHelper ctrl = new SiteVisitReportSubmissionHelper(layoutHolder );
            ctrl.whenClicked();
            Test.stopTest();
        }
    }
     @isTest(seealldata =  true)
    public static void testExternalLinksConfigLayoutEditCtrl1(){
        UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
           AnnouncementTriggerHelper.skipTrigger=true;
           RolesAndResponsibilitiesTriggerHelper.skipTrigger=true;
           GrantTriggerHelper.skipTrigger=true;
           AwardTriggerHelper.skipTrigger=true;
           SiteVisitTriggerHelper.skipTrigger=true;

        System.runAs(u){
            Test.startTest();
            Announcement__c ann = TestHelper.getAnnouncement(true); 
            SiteVisitSchedule__c sitesch= TestHelper.getSiteVisitSchedule(true); 
             
           
            Grant__c grant = TestHelper.getGrant(false);
           grant.Status__c = 'Active';
           grant.ProjectPeriodStartDate__c=Date.today();
            grant.GrantAbbreviation__c='12345';
            
            
            //Grant__c grant = TestHelper.getGrant(false);
        //grant.Program__c = program.id;
        //grant.Status__c = 'Active';
       // grant.ProjectPeriodStartDate__c=Date.today();
      //  grant.NumberofProjectsFunded__c='1';
        insert grant;
            //insert grant;  
        Award__c award = TestHelper.getAwards(grant.Id,true);    
            SiteVisit__c site =TestHelper.getSiteVisit(false);
            site.Grant__c=grant.Id;
            site.VisitEndDateTime__c=DateTime.now();
            site.ActivityQuestion2__c ='abc';
            insert site;
            GNT__PageLayoutConfig__c pagelayoutConfig= null;
            pagelayoutConfig = TestHelper.getPageLayoutConfig(true,'SiteVisit__c');
            GNT.DynamicLayoutHolder layoutHolder = new GNT.DynamicLayoutHolder(pageLayoutConfig.id, site.Id,true);
            //ApexPages.CurrentPage().getParameters().put('id', site.Id);
        
            SiteVisitReportSubmissionHelper ctrl = new SiteVisitReportSubmissionHelper(layoutHolder );
            ctrl.whenClicked();
            Test.stopTest();
        }
    }
}