UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2000</fullName>
                </value>
                <value>
                    <fullName>2001</fullName>
                </value>
                <value>
                    <fullName>2002</fullName>
                </value>
                <value>
                    <fullName>2003</fullName>
                </value>
                <value>
                    <fullName>2004</fullName>
                </value>
                <value>
                    <fullName>2005</fullName>
                </value>
                <value>
                    <fullName>2006</fullName>
                </value>
                <value>
                    <fullName>2007</fullName>
                </value>
                <value>
                    <fullName>2008</fullName>
                </value>
                <value>
                    <fullName>2009</fullName>
                </value>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <formula>Organization__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization Name</label>
        <type>Text</type>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>FiscalYear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodEndDate__c</fullName>
        <label>Project Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodStartDate__c</fullName>
        <description>Project Period Start Date as entered by the applicant.</description>
        <label>Project Period Start Date</label>
        <type>Date</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2000</fullName>
                </value>
                <value>
                    <fullName>2001</fullName>
                </value>
                <value>
                    <fullName>2002</fullName>
                </value>
                <value>
                    <fullName>2003</fullName>
                </value>
                <value>
                    <fullName>2004</fullName>
                </value>
                <value>
                    <fullName>2005</fullName>
                </value>
                <value>
                    <fullName>2006</fullName>
                </value>
                <value>
                    <fullName>2007</fullName>
                </value>
                <value>
                    <fullName>2008</fullName>
                </value>
                <value>
                    <fullName>2009</fullName>
                </value>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OrganizationAddress__c</fullName>
        <inlineHelpText>Auto populate field. Copy this from the application in cases of awards being created as a result of approved applications, progress reports or ammedment requests. For awards initiated by State, copy this information from the last award. Editable. Required</inlineHelpText>
        <label>Organization Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <label>Organization Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodEndDate__c</fullName>
        <description>Project Period End Date for the award.</description>
        <label>Project Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodStartDate__c</fullName>
        <description>Project Period Start Date for the award.</description>
        <label>Project Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SupportYear__c</fullName>
        <description>Auto populated. Support year for the award.</description>
        <label>Support Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>GrantsAnn</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GrantAbbreviation__c</fullName>
        <description>Unique Abbreviation used for internal Financial System integration</description>
        <inlineHelpText>Unique Abbreviation used for internal Financial System integration</inlineHelpText>
        <label>Grant Abbreviation</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IssueDate__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <label>Organization Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodEndDate__c</fullName>
        <label>Project Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodStartDate__c</fullName>
        <label>Project Period Start Date</label>
        <type>Date</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/TermCondition__c.object
<CustomObject>
    <description>[Business] Terms and Conditions for Grants ,Awards (The lookup to Package may not be required in this case )</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Terms and Conditions</relationshipLabel>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MST:Term and Condition</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/AwardViewCtrlTest.cls
@isTest
public class AwardViewCtrlTest {
    static testMethod void someTest() {
        //Grant__c gr = TestHelper.getGrant(true);
         AnnouncementTriggerHelper.skipTrigger = true;
         ApplicationtriggerHelper.skiptrigger = true;
         RolesandResponsibilitiesTriggerHelper.skipTrigger = true;
         GranttriggerHelper.skipTrigger = true;
         AwardTriggerhelper.skipTrigger = true;
         Grant__c gr = new Grant__c();
         gr.ProjectPeriodStartDate__c=Date.newInstance(2015,3,14);
         gr.ProjectPeriodEndDate__c=Date.newInstance(2016,3,14);
         gr.GrantAbbreviation__c='12345';
         gr.IssueDate__c = Date.newInstance(2014,3,14);
         insert gr;
     
        Announcement__c ann = TestHelper.getAnnouncement(true);
        Application__c app = TestHelper.getApplication(ann.Id,true);
         
        //Award__c aw = TestHelper.getAwards(gr.Id,true);
        Award__c aw  = new Award__c();
        aw.grant__c = gr.Id;
        aw.Name = Math.Random()+'AW12';
        aw.OrganizationName__c = 'Test Org';
        aw.OrganizationAddress__c = 'Test Address';
        aw.FiscalYear__c = '2013';
        aw.SupportYear__c = Decimal.valueOf('2013');
        aw.Status__c = 'Issued';
        aw.Application__c=app.Id;
        insert aw;
                
        TermCondition__c termCond = new TermCondition__c();
        termCond.Award__c= aw.Id;
        termCond.SubmissionType__c='Payment Request';
        insert termCond;
              
        
        ApexPages.StandardController sc = new ApexPages.standardController(gr);        
        ApexPages.currentPage().getParameters().put('Id',aw.id);
        //ApexPages.currentPage().getParameters().put('applicationId',app.Id);
        ApexPages.currentPage().getParameters().put('applicationId',null);
        AwardViewCtrl e = new AwardViewCtrl(sc);
        e.getKeyValueMap();
    }
    
    static testMethod void someTest2() {
        //Grant__c gr = TestHelper.getGrant(true);
         AnnouncementTriggerHelper.skipTrigger = true;
         ApplicationtriggerHelper.skiptrigger = true;
         RolesandResponsibilitiesTriggerHelper.skipTrigger = true;
         GranttriggerHelper.skipTrigger = true;
         AwardTriggerhelper.skipTrigger = true;
         Grant__c gr = new Grant__c();
         gr.ProjectPeriodStartDate__c=Date.newInstance(2015,3,14);
         gr.ProjectPeriodEndDate__c=Date.newInstance(2016,3,14);
         gr.GrantAbbreviation__c='12345';
         gr.IssueDate__c = Date.newInstance(2014,3,14);
         insert gr;
     
        Announcement__c ann = TestHelper.getAnnouncement(true);
        Application__c app = TestHelper.getApplication(ann.Id,true);
         
        //Award__c aw = TestHelper.getAwards(gr.Id,true);
        Award__c aw  = new Award__c();
        aw.grant__c = gr.Id;
        aw.Name = Math.Random()+'AW12';
        aw.OrganizationName__c = 'Test Org';
        aw.OrganizationAddress__c = 'Test Address';
        aw.FiscalYear__c = '2013';
        aw.SupportYear__c = Decimal.valueOf('2013');
        aw.Status__c = 'Issued';
        aw.Application__c=app.Id;
        insert aw;
             
        
        ApexPages.StandardController sc = new ApexPages.standardController(gr);        
        ApexPages.currentPage().getParameters().put('Id',aw.id);
        //ApexPages.currentPage().getParameters().put('applicationId',app.Id);
        ApexPages.currentPage().getParameters().put('applicationId',app.Id);
        AwardViewCtrl e = new AwardViewCtrl(sc);
    }
    
     static testMethod void someTest3() {
        //Grant__c gr = TestHelper.getGrant(true);
         AnnouncementTriggerHelper.skipTrigger = true;
         ApplicationtriggerHelper.skiptrigger = true;
         RolesandResponsibilitiesTriggerHelper.skipTrigger = true;
         GranttriggerHelper.skipTrigger = true;
         AwardTriggerhelper.skipTrigger = true;
         Grant__c gr = new Grant__c();
         gr.ProjectPeriodStartDate__c=Date.newInstance(2015,3,14);
         gr.ProjectPeriodEndDate__c=Date.newInstance(2016,3,14);
         gr.GrantAbbreviation__c='12345';
         gr.IssueDate__c = Date.newInstance(2014,3,14);
         insert gr;
     
        Announcement__c ann = TestHelper.getAnnouncement(true);
        Application__c app = TestHelper.getApplication(ann.Id,true);
         
        //Award__c aw = TestHelper.getAwards(gr.Id,true);
        Award__c aw  = new Award__c();
        aw.grant__c = gr.Id;
        aw.Name = Math.Random()+'AW12';
        aw.OrganizationName__c = 'Test Org';
        aw.OrganizationAddress__c = 'Test Address';
        aw.FiscalYear__c = '2013';
        aw.SupportYear__c = Decimal.valueOf('2013');
        aw.Status__c = 'Issued';
        aw.Application__c=app.Id;
        insert aw;
                
        TermCondition__c termCond = new TermCondition__c();
        termCond.Award__c= aw.Id;
        termCond.SubmissionType__c='Progress Report';
        insert termCond;
              
        
        ApexPages.StandardController sc = new ApexPages.standardController(gr);        
        ApexPages.currentPage().getParameters().put('Id',aw.id);
        ApexPages.currentPage().getParameters().put('applicationId',null);
        AwardViewCtrl e = new AwardViewCtrl(sc);
    }
    
    static testMethod void someTest4() {
        //Grant__c gr = TestHelper.getGrant(true);
         AnnouncementTriggerHelper.skipTrigger = true;
         ApplicationtriggerHelper.skiptrigger = true;
         RolesandResponsibilitiesTriggerHelper.skipTrigger = true;
         GranttriggerHelper.skipTrigger = true;
         AwardTriggerhelper.skipTrigger = true;
         Grant__c gr = new Grant__c();
         gr.ProjectPeriodStartDate__c=Date.newInstance(2015,3,14);
         gr.ProjectPeriodEndDate__c=Date.newInstance(2016,3,14);
         gr.GrantAbbreviation__c='12345';
         gr.IssueDate__c = Date.newInstance(2014,3,14);
         insert gr;
     
        Announcement__c ann = TestHelper.getAnnouncement(true);
        Application__c app = TestHelper.getApplication(ann.Id,true);
         
        //Award__c aw = TestHelper.getAwards(gr.Id,true);
        Award__c aw  = new Award__c();
        aw.grant__c = gr.Id;
        aw.Name = Math.Random()+'AW12';
        aw.OrganizationName__c = 'Test Org';
        aw.OrganizationAddress__c = 'Test Address';
        aw.FiscalYear__c = '2013';
        aw.SupportYear__c = Decimal.valueOf('2013');
        aw.Status__c = 'Issued';
        aw.Application__c=app.Id;
        insert aw;
                
        TermCondition__c termCond = new TermCondition__c();
        termCond.Award__c= aw.Id;
        termCond.SubmissionType__c='Site Visit';
        insert termCond;
              
        
        ApexPages.StandardController sc = new ApexPages.standardController(gr);        
        ApexPages.currentPage().getParameters().put('Id',aw.id);
        ApexPages.currentPage().getParameters().put('applicationId',null);
        AwardViewCtrl e = new AwardViewCtrl(sc);
    }
    
}