UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A unique id to relate the announcement to the program.</description>
        <label>Program ID</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BusinessPackage__c.object
<CustomObject>
    <description>[Business]  This object associates the Package with the Program or Opportunity</description>
    <fields>
        <fullName>FundingOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Grants</description>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PackageConfig__c</fullName>
        <label>Package Config</label>
        <referenceTo>GNT__Package__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PackageType__c</fullName>
        <label>Package Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Pre-Application</fullName>
                </value>
                <value>
                    <fullName>App-Review</fullName>
                </value>
                <value>
                    <fullName>Award</fullName>
                </value>
                <value>
                    <fullName>Amendment Request</fullName>
                </value>
                <value>
                    <fullName>Progress Report</fullName>
                </value>
                <value>
                    <fullName>Site Visit</fullName>
                </value>
                <value>
                    <fullName>Payment Request</fullName>
                </value>
                <value>
                    <fullName>Closeout</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Risk Assessment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Package</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>GrantsAnn</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InternalOrganization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Grants (Internal Organization)</relationshipLabel>
        <relationshipName>Grants1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProgramCode</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodEndDate__c</fullName>
        <label>Project Period End Date</label>
        <type>Date</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>InternalOrganization__c</fullName>
        <description>Created to show up on the portal</description>
        <label>Internal Organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramSubType__c</fullName>
        <description>Dependent picklist for program Type</description>
        <label>Program Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ProgramType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Project Grants</fullName>
                    <default>true</default>
                    <label>Project Grants</label>
                </value>
                <value>
                    <fullName>Research Grants</fullName>
                </value>
                <value>
                    <fullName>Formula Grants</fullName>
                </value>
                <value>
                    <fullName>Block Grant</fullName>
                </value>
                <value>
                    <fullName>Earmark Grant</fullName>
                </value>
                <value>
                    <fullName>Formula Loans</fullName>
                </value>
                <value>
                    <fullName>Investment Loans</fullName>
                </value>
                <value>
                    <fullName>Sub Contract</fullName>
                </value>
                <value>
                    <fullName>Joint Agreements</fullName>
                </value>
                <value>
                    <fullName>Formula Based Agreements</fullName>
                </value>
                <value>
                    <fullName>Angel Investment Credits</fullName>
                </value>
                <value>
                    <fullName>Other Investment Credits</fullName>
                </value>
                <value>
                    <fullName>Emergency Grants</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestGrantTriggerHelper.cls
@isTest
public with sharing class TestGrantTriggerHelper {

    @isTest
    static void grantorTest() {
    /*
        UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
        

        System.runAs(u) {
            AccountTriggerHelper.skipTrigger = true;
            ProgramTriggerHelper.skipTrigger = true;
            AnnouncementTriggerHelper.skipTrigger = true;
            AwardTriggerHelper.skipTrigger = true;

            Account acc = TestHelper.getAccount(true);
            
            Grant__c grant = TestHelper.getGrant(false);
            grant.InternalOrganization__c = acc.Id;

            Program__c program = TestHelper.getProgram(acc.Id, false);
            program.programsubtype__c = 'Project Grants';
            insert program;

            grant.Program__c = program.Id;


            BusinessPackage__c bp=new BusinessPackage__c();
            GNT__PageTemplate__c pt = TestHelper.getPageTemplateConfig(true);
            GNT__Package__c pack = TestHelper.getPackage(false, pt);
            pack.name='test';
            pack.GNT__SubmissionType__c = 'Application';
            pack.GNT__LatestVersion__c = true;
            pack.GNT__Status__c = 'Active';
            insert pack;
            bp.PackageConfig__c=pack.Id;
            //bp.PackageType__c = 'Closeout';
            bp.Grant__c = grant.Id;
            bp.Program__c = program.Id;
            insert bp; 
            
            Announcement__c announcement = TestHelper.getAnnouncement(true);
            grant.Announcement__c = announcement.Id;
            
            BusinessPackage__c bp2=new BusinessPackage__c();
            GNT__PageTemplate__c pt2 = TestHelper.getPageTemplateConfig(true);
            GNT__Package__c pack2 = TestHelper.getPackage(false, pt2);
            pack2.name='test';
            //pack2.GNT__SubmissionType__c = 'Application';
            pack2.GNT__LatestVersion__c = true;
            pack2.GNT__Status__c = 'Active';
            insert pack2;
            bp2.PackageConfig__c=pack2.Id;
            //bp.PackageType__c = 'Closeout';
            bp2.Grant__c = grant.Id;
            bp2.FundingOpportunity__c = announcement.Id;

            insert bp2;

            Test.startTest();
            
            GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c', 'StateasGrantor');
            insert grant;
            Test.stopTest();


        }
        */
    }

    @isTest
    static void granteeTest() {
    /*
        UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
        GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c', 'StateasGrantee');

        System.runAs(u) {
            AccountTriggerHelper.skipTrigger = true;
            ProgramTriggerHelper.skipTrigger = true;
            AnnouncementTriggerHelper.skipTrigger = true;
            
            Account acc = TestHelper.getAccount(false);
            acc.Name = 'USBE';
            insert acc;

            Grant__c grant = TestHelper.getGrant(false);
            grant.InternalOrganization__c = acc.Id;
            grant.ProjectPeriodEndDate__c = Date.TODAY() + 365;

            Program__c program = TestHelper.getProgram(acc.Id, false);
            program.programsubtype__c = 'Project Grants';
            insert program;


            BusinessPackage__c bp=new BusinessPackage__c();
            GNT__PageTemplate__c pt = TestHelper.getPageTemplateConfig(true);
            GNT__Package__c pack = TestHelper.getPackage(false, pt);
            pack.name='test';
            pack.GNT__SubmissionType__c = 'Application';
            pack.GNT__LatestVersion__c = true;
            pack.GNT__Status__c = 'Active';
            insert pack;
            bp.PackageConfig__c=pack.Id;
            //bp.PackageType__c = 'Closeout';
            bp.Grant__c = grant.Id;
            bp.Program__c = program.Id;
            insert bp; 
            
            Announcement__c announcement = TestHelper.getAnnouncement(true);
            grant.Announcement__c = announcement.Id;
            
            BusinessPackage__c bp2=new BusinessPackage__c();
            GNT__PageTemplate__c pt2 = TestHelper.getPageTemplateConfig(true);
            GNT__Package__c pack2 = TestHelper.getPackage(false, pt2);
            pack2.name='test';
            //pack2.GNT__SubmissionType__c = 'Application';
            pack2.GNT__LatestVersion__c = true;
            pack2.GNT__Status__c = 'Active';
            insert pack2;
            bp2.PackageConfig__c=pack2.Id;
            //bp.PackageType__c = 'Closeout';
            bp2.Grant__c = grant.Id;
            bp2.FundingOpportunity__c = announcement.Id;

            insert bp2;

            Test.startTest();
            insert grant;
            Test.stopTest();


        }
        */
    }
}