UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ProjectCostByFundingSource__c.object
<CustomObject>
    <description>Project Cost By Funding Source : Details of Funding Sources</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Project Cost By Funding Sources</relationshipLabel>
        <relationshipName>AppProjectCostByFundingSources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SecuredAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Secured Amount</description>
        <label>Secured Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnsecuredAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Unsecured Amount</description>
        <inlineHelpText>Unsecured Amount</inlineHelpText>
        <label>Unsecured Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project Cost By Funding Source</label>
    <nameField>
        <label>Project Cost Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Cost By Funding Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ProjectCostsTriggerHelperTest.cls
@isTest
private class ProjectCostsTriggerHelperTest {

    static testMethod void testWhenClicked() {
        User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
        Test.startTest();
        PreapplicationTriggerHelper.skipTrigger = true;
        ApplicationTriggerHelper.skipTrigger = true;
        AnnouncementTriggerHelper.skipTrigger = true;
        PanelUserTriggerHelper.skipAll= true;
        UserTriggerHelper.skipTrigger = true;
        ProjectCostByFundingSource__c  pcfs = new ProjectCostByFundingSource__c();
        pcfs.UnsecuredAmount__c = 100;
        pcfs.SecuredAmount__c = 100;
        pcfs.Sequence__c = 1;
        pcfs.name= 'tets';
        insert pcfs;
        pcfs.UnsecuredAmount__c = 200;
        update pcfs;
        Test.stopTest();    
    }
}
    @isTest
     static void testWhenClicked1() {
        User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
        Test.startTest();
        PreapplicationTriggerHelper.skipTrigger = true;
        ApplicationTriggerHelper.skipTrigger = true;
        AnnouncementTriggerHelper.skipTrigger = true;
        PanelUserTriggerHelper.skipAll= true;
        UserTriggerHelper.skipTrigger = true;
        Announcement__c ann = TestHelper.getAnnouncement(true);
        Application__c app =TestHelper.getApplication(ann.Id,true);
        ProjectCostByFundingSource__c  pcfs = new ProjectCostByFundingSource__c();
        pcfs.UnsecuredAmount__c = 100;
        pcfs.SecuredAmount__c = 100;
        pcfs.Sequence__c = 1;
        pcfs.name= 'tets';
        pcfs.Application__c = app.Id;
        insert pcfs;
        pcfs.UnsecuredAmount__c = 200;
        update pcfs;
        Test.stopTest();    
    }    
}
}