UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2000</fullName>
                </value>
                <value>
                    <fullName>2001</fullName>
                </value>
                <value>
                    <fullName>2002</fullName>
                </value>
                <value>
                    <fullName>2003</fullName>
                </value>
                <value>
                    <fullName>2004</fullName>
                </value>
                <value>
                    <fullName>2005</fullName>
                </value>
                <value>
                    <fullName>2006</fullName>
                </value>
                <value>
                    <fullName>2007</fullName>
                </value>
                <value>
                    <fullName>2008</fullName>
                </value>
                <value>
                    <fullName>2009</fullName>
                </value>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A unique id to relate the announcement to the program.</description>
        <label>Program ID</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AnnouncementFundingAccount__c.object
<CustomObject>
    <description>[Business]  Funding Accounts associated with the opportunity</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>Announcement</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FundingAccount__c</fullName>
        <label>Funding Account</label>
        <referenceTo>FundingAccount__c</referenceTo>
        <relationshipLabel>Funding Opportunity Funding Accounts</relationshipLabel>
        <relationshipName>Announcement_Funding_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Opportunity Funding Account</label>
    <nameField>
        <displayFormat>AFA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Opportunity Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>FiscalYear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AwardFundingAccount__c.object
<CustomObject>
    <description>[Business] Associates all the Funding accounts with the Grant/Award</description>
    <fields>
        <fullName>Award__c</fullName>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award Funding Accounts</relationshipLabel>
        <relationshipName>Award_Funding_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FundingAccount__c</fullName>
        <label>Funding Account</label>
        <referenceTo>FundingAccount__c</referenceTo>
        <relationshipLabel>Award Funding Accounts</relationshipLabel>
        <relationshipName>Award_Funding_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award Funding Account</label>
    <nameField>
        <displayFormat>AFA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Award Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FormBudgetInformation__c.object
<CustomObject>
    <description>[Business] This object is used for Budget Information forms.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Overflow Budget Information</label>
    <nameField>
        <displayFormat>BI-{00000}</displayFormat>
        <label>Budget Information</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Overflow Budget Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingAccount__c.object
<CustomObject>
    <description>[Business] Funding account details Funding accounts are created from Funding sources</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Funding Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>GrantsAnn</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProgramCode</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ProgramFundingAccount__c.object
<CustomObject>
    <description>[Business] Junction object between Funding Account and Program</description>
    <fields>
        <fullName>FundingAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Account</label>
        <referenceTo>FundingAccount__c</referenceTo>
        <relationshipLabel>Program Funding Accounts</relationshipLabel>
        <relationshipName>Program_Funding_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Funding Accounts</relationshipLabel>
        <relationshipName>Program_Funding_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Funding Account</label>
    <nameField>
        <displayFormat>PFA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/AwardFundingAccountAddCtrl.cls
/**
* Edit/Add page controller for the AwardFundingAccount__c object
* 
* CHANGE HISTORY
* =============================================================================
* Date          Name            Description
* 05/16/2014    Kunal Shah      Created
* =============================================================================
*/

public with sharing class AwardFundingAccountAddCtrl {
    //Shah 5/22/2015 Commenting out the below logic due to revised data model
    /*
    public Id awardId {get;set;}
    public Award__c awardInstance {get;set;}
    public List<AwardFundingAccountWrapper> lstAwardFundingAccountWrapper {get;set;}
    public AwardFundingAccount__c awardFundingAccount {get;set;}
    
    public AwardFundingAccountAddCtrl(){
        awardId = ApexPages.CurrentPage().getParameters().get('awardId');   
        awardInstance = [SELECT Grant__r.Program__c,Application__c,Application__r.Announcement__c,FiscalYear__c FROM Award__c WHERE Id = : awardId];
        lstAwardFundingAccountWrapper = new List<AwardFundingAccountWrapper>();
        List<Id> addedFundingAccounts = findAddedFundingAccounts();
        
        //IF THE AWARD IS CREATED FOR A PROGRAM, GET THE PROGRAM FUNDING ACCOUNTS
        if(awardInstance.Grant__r.Program__c != null){
            List<ProgramFundingAccount__c> progFundAcct = [SELECT FundingAccount__c FROM ProgramFundingAccount__c 
                                                            WHERE Program__c = : awardInstance.Grant__r.Program__c];
            List<Id> fundAcctIds = new List<Id>();
            for(ProgramFundingAccount__c pfa : progFundAcct){
                fundAcctIds.add(pfa.FundingAccount__c);
            }   
                                                        
            List<FundingAccountYear__c> fundingAcctYear = [SELECT Id,FundingAccount__r.Name,FundsAvailable__c,FundsAwardedByState__c,ObligationInProgress__c,TotalFunds__c,FiscalYear__c
                                                            FROM FundingAccountYear__c 
                                                            WHERE FundingAccount__c IN : fundAcctIds 
                                                            AND FiscalYear__c = : awardInstance.FiscalYear__c
                                                            AND Id NOT IN : addedFundingAccounts];
                                                            
            for(FundingAccountYear__c fay: fundingAcctYear){
                lstAwardFundingAccountWrapper.add(new AwardFundingAccountWrapper(fay));     
            }                                               
        }
        //IF THE AWARD IS CREATED FOR AN APPLICATION, GET THE ANNOUNCEMENT FUNDING ACCOUNTS
        else{
            List<AnnouncementFundingAccount__c> annFundAcct = [SELECT FundingAccountYear__c FROM AnnouncementFundingAccount__c 
                                                                WHERE Announcement__c = : awardInstance.Application__r.Announcement__c];
            List<Id> fundAcctIds = new List<Id>();
            for(AnnouncementFundingAccount__c afa : annFundAcct){
                fundAcctIds.add(afa.FundingAccountYear__c);
            }   
            List<FundingAccountYear__c> fundingAcctYear = [SELECT Id,FundingAccount__r.Name,FundsAvailable__c,FundsAwardedByState__c,ObligationInProgress__c,TotalFunds__c,FiscalYear__c 
                                                            FROM FundingAccountYear__c 
                                                            WHERE ID IN : fundAcctIds 
                                                            AND FiscalYear__c = : awardInstance.FiscalYear__c
                                                            AND Id NOT IN :addedFundingAccounts];       
            for(FundingAccountYear__c fay: fundingAcctYear){
                lstAwardFundingAccountWrapper.add(new AwardFundingAccountWrapper(fay));     
            }                           
        }
    }
    
    public void addFundingAccount(){
        try{
            List<AwardFundingAccount__c> lstAwardFundingAccounts = new List<AwardFundingAccount__c>();
            for(AwardFundingAccountWrapper afa: lstAwardFundingAccountWrapper) {
                if(afa.selected == true) {
                    AwardFundingAccount__c awardFundingAccount = new AwardFundingAccount__c();
                    awardFundingAccount.Award__c = awardId;
                    awardFundingAccount.FundingAccountYear__c = afa.fundAccYear.Id;
                    awardFundingAccount.FinancialAssistanceAmount__c = afa.financialAmount;
                    lstAwardFundingAccounts.add(awardFundingAccount);
                }   
            } 
            if(Schema.sObjectType.AwardFundingAccount__c.isCreateable()){
                insert lstAwardFundingAccounts;
            }
        }catch (Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, e.getMessage());
            ApexPages.addMessage(myMsg);
        }
    }
    
    public List<Id> findAddedFundingAccounts(){
        List<Id> faIds = new List<Id>();
        for(AwardFundingAccount__c afa: [SELECT FundingAccountYear__c FROM AwardFundingAccount__c WHERE Award__c =: awardId]){
            faIds.add(afa.FundingAccountYear__c);
        }
        return faIds;
    }
    
    private class AwardFundingAccountWrapper{
        public FundingAccountYear__c fundAccYear {get;set;}
        public Boolean selected {get;set;}
        public decimal financialAmount {get;set;}
        
        public AwardFundingAccountWrapper(FundingAccountYear__c fay){
            fundAccYear = fay; 
            selected = false;   
        }   
    }
    */
}