UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>ApplicationCreatedOutside__c</fullName>
        <description>This field</description>
        <label>Application created outside this System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AwardCeiling__c</fullName>
        <description>The lowest amount an applicant can request.</description>
        <label>Award Ceiling</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AwardFloor__c</fullName>
        <description>The highest amount an applicant can request.</description>
        <label>Award Floor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BudgetCategory__c</fullName>
        <description>Is Budget Category needed at Individual or Total Level?</description>
        <label>Budget Category Required?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget Category Level</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Overall Level</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProgramApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Funding_Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>- In Progress - The information within the annoucement is incomplete. Such records shall not be avaiable for other users to view or edit.
- Review In Progress - Annoucements that are currently in the process of undergoing review shall have this status. Such records shall not be avaiable for other users to view or edit.
- Inactive - Approved annoucements whose Posting Date is in the future shall have this status. Such annoucements shall not be made available to recipient users.
- Active - Approved annoucements whose Posting Date is equal to the current date or is in the past and the Closing Date is in the future shall have this status. System shall make such annoucements available to recipients.
- Expired - Approved annoucements whose closing date is the current date or is in the past shall have this status. When an annoucement status changes from Active to Expired, it should no longer be made available to the recipient users.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Converted to Application</fullName>
                </value>
                <value>
                    <fullName>Converted to Pre-Application</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Approved</fullName>
                </value>
                <value>
                    <fullName>RFA Published</fullName>
                </value>
                <value>
                    <fullName>RFA Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApplicationCreatedOutside__c</fullName>
        <description>This is a field that Captures the field from the opportunity which shows that the Application is created outside of the current System</description>
        <formula>Text(Announcement__r.ApplicationCreatedOutside__c)== &apos;Yes&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Application Created Outside the System</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AwardCeiling__c</fullName>
        <label>AwardCeiling</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AwardFloor__c</fullName>
        <label>AwardFloor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FiscalApproval__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Approval</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications11</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FormsValidated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for validation of form depends upon percentage of form filled.</description>
        <label>Forms Validated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NumberOfReviews__c</fullName>
        <label>Number Of Reviews</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProgramApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications10</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Review Initiated</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Submitted For Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Sent for Review</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision Completed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Rejection Initiated</fullName>
                </value>
                <value>
                    <fullName>Internally Reviewed</fullName>
                </value>
                <value>
                    <fullName>Converted to Award</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Converted to Grant</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Revision Initiated</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Approved Internally</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ApplicationBudgetCategory2__c.object
<CustomObject>
    <description>[Business] Stores the Budget related information associated with an Application</description>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application_Budget_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BudgetCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Category</label>
        <referenceTo>BudgetCategory__c</referenceTo>
        <relationshipName>Application_Budget_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FormsValidated__c</fullName>
        <formula>Application__r.FormsValidated__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FormsValidated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>text(Application__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Application Budget Category</label>
    <nameField>
        <displayFormat>AC-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Budget Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BudgetCategory__c.object
<CustomObject>
    <description>[Business] This object stores the Master List of all the Budget categories</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MST: Budget Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Category</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestAppSubmissionHelper.cls
@isTest
private with sharing class TestAppSubmissionHelper {
    static testMethod void testWhenClicked() {
    
        UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
        Application__c app = null;
        Announcement__c ann = null;
        List<BudgetCategory__c> budCat = null;
        ApplicationBudgetCategory2__c appbudCat = null;
        
        System.runAs(u){
            ApplicationTriggerHelper.skipTrigger = true;
            AnnouncementTriggerHelper.skipTrigger = true;
            UserTriggerHelper.skipTrigger = true;
            
            GNT__CustomAppConfig__c cac = TestHelper.getCustomAppConfig(true);
            
            ann = TestHelper.getAnnouncement(true);
            ann.ApplicationCreatedOutside__c='Yes';
            update ann;
            
            app = TestHelper.getApplication(ann.Id,true);
            app.AwardFloor__c=2000;
            app.AwardCeiling__c=1;
            update app;
            
            budCat = TestHelper.getBudgetCategory(true);
            appbudCat = new ApplicationBudgetCategory2__c(Application__c = app.Id, BudgetCategory__c=budCat[0].Id);
            insert appbudCat;
            appbudCat.Amount__c=2;
            update appbudCat;
            
            String ns = AppUtils.getNamespacePrefix();
            GNT__PageLayoutConfig__c pageLayoutConfig =  TestHelper.getPageLayoutConfig(true,ns + 'Application__c');
            GNT__TabConfig__c tabConfig =  TestHelper.getTabConfig(pageLayoutConfig.Id,true);
            GNT__PageBlockConfig__c pageBlockConfig =  TestHelper.getPageBlockConfig(tabConfig.Id, true);
            GNT__PageBlockDetailConfig__c pageBlockDetailConfigList = TestHelper.getPageBlockDetailConfig(pageBlockConfig.Id,false); 
            
           if(pageBlockDetailConfigList.GNT__FieldAPIName__c == 'Name') {
                    insert pageBlockDetailConfigList;
            }
            
            GNT__PageLayoutActionConfig__c pageAction = TestHelper.getPageLayoutActionConfig(true,pageLayoutConfig.Id);
            GNT.DynamicLayoutHolder layoutHolder = new GNT.DynamicLayoutHolder(pageLayoutConfig.id, app.Id,true);
            Test.startTest();
            AppSubmissionHelper ctrl = new AppSubmissionHelper();
            ctrl.layoutHolder = layoutHolder;
            ctrl.whenClicked();
            Test.stopTest();
        }
    }
    
    static testMethod void testWhenClicked2() {
    
        UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
       
        Application__c app = null;
        Announcement__c ann = null;
        
        System.runAs(u){
            ApplicationTriggerHelper.skipTrigger = true;
            AnnouncementTriggerHelper.skipTrigger = true;
            UserTriggerHelper.skipTrigger = true;
            GNT__CustomAppConfig__c cac = TestHelper.getCustomAppConfig(true);
            
            User u2 = TestHelper.getAdminUser(true);
            ann = TestHelper.getAnnouncement(true);
         
            app = TestHelper.getApplication(ann.Id,true);
            app.FormsValidated__c=true;
            app.NumberOfReviews__c = 2;
            app.ProgramApprover__c=u.Id;
            app.FiscalApproval__c=u2.Id;
            app.Status__c='Reviewed';
            update app;
          
            String ns = AppUtils.getNamespacePrefix();
            GNT__PageLayoutConfig__c pageLayoutConfig =  TestHelper.getPageLayoutConfig(true,ns + 'Application__c');
            GNT__TabConfig__c tabConfig =  TestHelper.getTabConfig(pageLayoutConfig.Id,true);
            GNT__PageBlockConfig__c pageBlockConfig =  TestHelper.getPageBlockConfig(tabConfig.Id, true);
            GNT__PageBlockDetailConfig__c pageBlockDetailConfigList = TestHelper.getPageBlockDetailConfig(pageBlockConfig.Id,false); 
            
           if(pageBlockDetailConfigList.GNT__FieldAPIName__c == 'Name') {
                    insert pageBlockDetailConfigList;
            }
            
            GNT__PageLayoutActionConfig__c pageAction = TestHelper.getPageLayoutActionConfig(true,pageLayoutConfig.Id);
            GNT.DynamicLayoutHolder layoutHolder = new GNT.DynamicLayoutHolder(pageLayoutConfig.id, app.Id,true);          
            
            Test.startTest();          
            AppSubmissionHelper ctrl = new AppSubmissionHelper();
            ctrl.layoutHolder = layoutHolder;
            ctrl.whenClicked();
            Test.stopTest();
        }
    }
}