UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AnnouncementServiceArea__c.object
<CustomObject>
    <description>[Business]  Service Area associated with an Annoucement</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>RelatedServiceAreas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Area</label>
        <referenceTo>ServiceArea__c</referenceTo>
        <relationshipName>AnnouncementServiceAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Opportunity Project Area</label>
    <nameField>
        <displayFormat>ASA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Opportunity Project Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ApplicationServiceArea__c.object
<CustomObject>
    <description>[Business] Associates a Service area with an Application</description>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application_Service_Areas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity Project Area</label>
        <referenceTo>AnnouncementServiceArea__c</referenceTo>
        <relationshipLabel>Application Project Areas</relationshipLabel>
        <relationshipName>Application_Service_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Project Area</label>
    <nameField>
        <displayFormat>ASA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Project Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ServiceArea__c.object
<CustomObject>
    <description>[Business] Master list of all the Service Area information is stored in this object , Service areas are also applicable to the Announcements ,Programs,Application via Junction objects</description>
    <label>Project/Service Area</label>
    <nameField>
        <displayFormat>PSA-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestApplicationServiceAreaViewCtrl.cls
@isTest
private with sharing class TestApplicationServiceAreaViewCtrl{
    static testMethod void testController() {
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          Account acct = null;
          
          System.runAs(u){
            AnnouncementTriggerHelper.skipTrigger = true;
            Announcement__c ann = TestHelper.getAnnouncement(true);
            
            ApplicationTriggerHelper.skipTrigger = true;
            Application__c app = TestHelper.getApplication(ann.Id,true);
            ServiceArea__c servArea = TestHelper.getServiceArea(true);
            AnnouncementServiceArea__c annServArea = new AnnouncementServiceArea__c(Announcement__c=ann.Id, ServiceArea__c=servArea.ID);
            ApplicationServiceArea__c appServArea = new ApplicationServiceArea__c(Application__c=app.Id,ServiceArea__c=annServArea.Id);
            insert appServArea;
            
          
         
            Test.startTest();
            ApexPages.StandardController sc = new ApexPages.standardController(appServArea);
            ApexPages.currentPage().getParameters().put('id',appServArea.id);
            ApplicationServiceAreaViewCtrl ctrl = new ApplicationServiceAreaViewCtrl(sc);
            ctrl.getKeyValueMap();         
            Test.stopTest();
        }
        
    }
    
}