UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ChangeRequest__c.object
<CustomObject>
    <description>[Business]  Currently used to track pre-award negotiation requests for application only. In the future this can be enhanced for other objects like award or something else.</description>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Negotiation Requests</relationshipLabel>
        <relationshipName>Change_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Negotiation Request</label>
    <nameField>
        <displayFormat>CR-{000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Negotiation Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestChangeRequestReviewHelper.cls
@isTest
private with sharing class TestChangeRequestReviewHelper{
    static testMethod void testclickHandler() {
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          System.runAs(u){
          
              GrantTriggerHelper.skipTrigger = true;
              ApplicationTriggerHelper.skipTrigger = true;
              AnnouncementTriggerHelper.skipTrigger = true;
              List<String> IdSet = new List<String>();
              
              Announcement__c ann = TestHelper.getAnnouncement(true);
              Application__c app = TestHelper.getApplication(ann.Id,true);
              ChangeRequest__c changeReq = new ChangeRequest__c(Application__c=app.Id);
              insert changeReq;
              IdSet.add(changeReq.Id);
              
              Test.startTest();
              ChangeRequestReviewHelper ctrl = new ChangeRequestReviewHelper();
              ctrl.urlParams.put('id',changeReq.Id);
              ctrl.selectedRecordIds = IdSet;
              ctrl.clickHandler();
              Test.stopTest();
          }
        
    }
    
}