UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewGroup__c.object
<CustomObject>
    <description>[Business] This object summarizes number of Applications/Pre-Applications and number of Review Steps. As discussed with Shiva, Shah, Davinder , this object can not removed sometime later when possible.</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity ID</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Review Groups</relationshipLabel>
        <relationshipName>Review_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NumberOfReviewSteps__c</fullName>
        <defaultValue>4</defaultValue>
        <inlineHelpText>User defined - total number of review steps for an application or pre-application based on record type.</inlineHelpText>
        <label>Number of Review Steps Allowed</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Review Group</label>
    <nameField>
        <displayFormat>RG-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestCaseViewCtrl.cls
@isTest
private with sharing class TestCaseViewCtrl{
    static testMethod void testController() {
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          System.runAs(u){
          
              /*Case tempCase = new Case();
              insert tempCase;
              
              AnnouncementTriggerHelper.skipTrigger = true;
              ReviewTriggerHelper.skipTrigger = true;
              Announcement__c ann = TestHelper.getAnnouncement(true);
              
              ReviewGroup__c reviewGroup = new ReviewGroup__c();
              reviewGroup.Announcement__c = ann.id;
              reviewGroup.NumberOfReviewSteps__c= Decimal.valueOf('2.0');
              insert reviewGroup;
              
              Test.startTest();
              ApexPages.StandardController sc = new ApexPages.standardController(tempCase);
              ApexPages.CurrentPage().getParameters().put('id',tempCase.Id);
              ApexPages.CurrentPage().getParameters().put('isClose','true');
              CaseViewCtrl ctrl = new CaseViewCtrl(sc);
              ctrl.reviewGrp = reviewGroup;
              ctrl.recordType='Review';
              ctrl.getKeyValueMap();
              ctrl.closeIssue();
              Test.stopTest();*/
          }
        
    }
    
}