UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>ApplicationsReviewStatus__c</fullName>
        <label>Applications Review Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A unique id to relate the announcement to the program.</description>
        <label>Program ID</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewPanelTemplate__c.object
<CustomObject>
    <description>[Business] Template defined for the Review</description>
    <fields>
        <fullName>ReviewStepTemplate__c</fullName>
        <label>Review Step Template</label>
        <referenceTo>ReviewStepTemplate__c</referenceTo>
        <relationshipName>Review_Panel_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReviewersCount__c</fullName>
        <label>ReviewersCount</label>
        <summaryForeignKey>PanelUserTemplate__c.ReviewPanelTemplate__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Review Panel</label>
    <nameField>
        <label>Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Panels</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStepTemplate__c.object
<CustomObject>
    <description>[Business] Template defined for a Step Review , Previous Name (Review Step Template)</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link the announcement record.</description>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>ReviewStepTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MultiplePanelsRequired__c</fullName>
        <inlineHelpText>Does it Require more than 1 Panels for this Review Step? 1 Panel is added by default</inlineHelpText>
        <label>Does it Require Multiple Review Panels</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NumberOfReviewPanels__c</fullName>
        <label>Number of Review Panels</label>
        <summaryForeignKey>ReviewPanelTemplate__c.ReviewStepTemplate__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to program record.</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>ReviewStepTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StepNumber__c</fullName>
        <label>Step Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Review Step Template</label>
    <nameField>
        <label>Review Step Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Step Templates</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ApplicationReviewCheckHelper.cls
/*
     
    **********************************************************
            1/11/2016  Davinder Singh       Created
    **********************************************************  
*/

//Handles application review readyness
global with sharing class ApplicationReviewCheckHelper extends GNT.DynamicLayoutActionRedirect{    
    global ApplicationReviewCheckHelper() {}
      Map<String,Object> resultMap = new Map<String,Object>(); 

      global override PageReference whenClicked(){
        Boolean revPanelFlag=false;
        Savepoint sp = Database.setSavePoint();  
        try {  
        Id announcementId=ApexPages.CurrentPage().getParameters().get('id');   
        Announcement__c ann = [Select Id, Name, ApplicationsReviewStatus__c,Program__c from Announcement__c where Id =:announcementId Limit 1 ];
        List<ReviewStepTemplate__c> rstList = [SELECT Id,Name,StepNumber__c,NumberOfReviewPanels__c,MultiplePanelsRequired__c FROM ReviewStepTemplate__c WHERE Announcement__c=: ann.id order by StepNumber__c asc];
        if(rstList!=null || rstList.size() > 0){                                    
           ReviewStepTemplate__c firstRST = rstList[0];
           List<ReviewPanelTemplate__c> rptList = [SELECT Id,Name,ReviewersCount__c FROM ReviewPanelTemplate__c WHERE ReviewStepTemplate__c=: firstRST.Id ];
           for(ReviewPanelTemplate__c revPanel : rptList)
              {
              if(revPanel.ReviewersCount__c<1){
                  revPanelFlag=true;
                  break;
                }
              }
              if(revPanelFlag){
              // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Roles Tab -' + firstRST.Name +' does not have Reviewers in all the associated Panels in Application Review Steps.'));
              ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-24073') +' '+ firstRST.Name +' '+GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-78480')));
             return null;
              }
              else{
              ann.ApplicationsReviewStatus__c='Ready for Review';
              update ann;   
              }
         } 
         else{
              // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'The announcement does not have required Application Review Steps.'));
              ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-83356')));
              return null;
         }         
        } catch(Exception e) {
            Database.rollBack(sp);               
        }        
         // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Announcement is Ready for Review.'));    
         ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-16413')));       
         return null;
    }
}