UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>- In Progress - The information within the annoucement is incomplete. Such records shall not be avaiable for other users to view or edit.
- Review In Progress - Annoucements that are currently in the process of undergoing review shall have this status. Such records shall not be avaiable for other users to view or edit.
- Inactive - Approved annoucements whose Posting Date is in the future shall have this status. Such annoucements shall not be made available to recipient users.
- Active - Approved annoucements whose Posting Date is equal to the current date or is in the past and the Closing Date is in the future shall have this status. System shall make such annoucements available to recipients.
- Expired - Approved annoucements whose closing date is the current date or is in the past shall have this status. When an annoucement status changes from Active to Expired, it should no longer be made available to the recipient users.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Converted to Application</fullName>
                </value>
                <value>
                    <fullName>Converted to Pre-Application</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Approved</fullName>
                </value>
                <value>
                    <fullName>RFA Published</fullName>
                </value>
                <value>
                    <fullName>RFA Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <description>Announcement type is based on Application that user is logged in</description>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/OpportunityQualification__c.object
<CustomObject>
    <description>[Business] This is for a Sub Recipient to Mark an Announcement so that after some days he or she can create an application for the same announcement. This is created because there might be lots of announcement but sub recipient might be interested with only few announcement so he/she can mark it as qualified and later convert into an application</description>
    <fields>
        <fullName>FundingOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>Opportunity_Sub_Recipient_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreApplicationCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre Application Created?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(FundingOpportunity__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Qualified Announcements</label>
    <nameField>
        <displayFormat>FO-{0000}</displayFormat>
        <label>Qualified Announcement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualified Announcements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PreApplication__c.object
<CustomObject>
    <description>[Business] Pre-Application is a trimmed version of the Application with limited information</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>PreApplications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Awarded</fullName>
                </value>
                <value>
                    <fullName>Not Awarded</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pre-Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pre-Applications</pluralLabel>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <description>This Record Type is Used by the Grantor Applicaion/Module</description>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>GNT__OrganizationId__c</fullName>
        <description>Organization to which a user is tied to. It is applicable for both internal and external users</description>
        <label>Organization Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/CreatePreApplicationHelper.cls
global with sharing class CreatePreApplicationHelper extends GNT.DynamicLayoutActionRedirect{
    
    global override PageReference whenClicked(){      
        Id recordId = layoutHolder.getPrimarySObject().Id;
        String ns = AppUtils.getNamespacePrefix(); 
        Id preapplicationId = apexpages.currentpage().getparameters().get('id');
        String appName = GNT.UserPreferenceHelper.getStringValue('ActiveAppName__c');
        User u = [select GNT__OrganizationId__c from User where id =:Userinfo.getUserId()];
        if(appName == 'Recipient'){
            OpportunityQualification__c qualifiedAnnouncement = [Select Id, FundingOpportunity__c,PreApplicationCreated__c from OpportunityQualification__c where id=:recordId limit 1];
            if(qualifiedAnnouncement.PreApplicationCreated__c==false){
                //qualifiedAnnouncement.PreApplicationCreated__c =true;
                update qualifiedAnnouncement;
                return new PageReference('/apex/'+ns+'PreApplicationEdit?announcementId=' + qualifiedAnnouncement.FundingOpportunity__c);
             }else{
               ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, GNT.ErrorMessageHelper.fetchMessage('P02-GRNTR-77373')));   
                return null;
            }
        }
        if(appName == 'StateasGrantee'){
          List<PreApplication__c> preapplicationList = [SELECT Id,Status__c FROM PreApplication__c WHERE Announcement__c =: recordId AND CreatedBy.GNT__OrganizationId__c =:u.GNT__OrganizationId__c];//CreatedById =: Userinfo.getUserId()];
          System.debug('The preapplicationList is '+preapplicationList);
            if(preapplicationList.size() == 0){
                return new PageReference('/apex/'+ns+'PreApplicationEdit?announcementId=' + recordId+'&t=GranteeApplication' ); 
            }            
            List<PreApplication__c> applst = [SELECT Id,Status__c FROM PreApplication__c WHERE Id =: preapplicationId AND CreatedBy.GNT__OrganizationId__c =:u.GNT__OrganizationId__c];
            if(applst.size()>0){
                System.debug('THE APPLICATION LIST IS '+applst); 
                if(applst[0].Status__c =='Approved'){
                    applst[0].Status__c ='Submitted to Grantor';
                    update applst[0];
                }
                if(applst[0].Status__c =='Submitted to Grantor'){
                    applst[0].Status__c ='Accepted';
                    update applst[0];
                } 
                 PageReference page = new PageReference('/apex/'+ns+'PreApplicationView?id=' + applst[0].id);   
                 page.setRedirect(true); 
                 return page;
            } 
        }  
            return null;
    }
}