UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A unique id to relate the announcement to the program.</description>
        <label>Program ID</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BusinessPackage__c.object
<CustomObject>
    <description>[Business]  This object associates the Package with the Program or Opportunity</description>
    <fields>
        <fullName>FundingOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Grants</description>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PackageConfig__c</fullName>
        <label>Package Config</label>
        <referenceTo>GNT__Package__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PackageName__c</fullName>
        <formula>PackageConfig__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Package Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PackageType__c</fullName>
        <label>Package Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Pre-Application</fullName>
                </value>
                <value>
                    <fullName>App-Review</fullName>
                </value>
                <value>
                    <fullName>Award</fullName>
                </value>
                <value>
                    <fullName>Amendment Request</fullName>
                </value>
                <value>
                    <fullName>Progress Report</fullName>
                </value>
                <value>
                    <fullName>Site Visit</fullName>
                </value>
                <value>
                    <fullName>Payment Request</fullName>
                </value>
                <value>
                    <fullName>Closeout</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Risk Assessment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UniquePackageName__c</fullName>
        <description>This field is used to display Unique Package Name</description>
        <label>Unique Package Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Business Package</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>GrantsAnn</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProgramCode</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStepTemplate__c.object
<CustomObject>
    <description>[Business] Template defined for a Step Review , Previous Name (Review Step Template)</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link the announcement record.</description>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>ReviewStepTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreviewForm__c</fullName>
        <label>Preview Form</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>PreviewId__c</fullName>
        <label>PreviewId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to program record.</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>ReviewStepTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewFormConfig__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review Form Config</label>
        <referenceTo>GNT__PageTemplate__c</referenceTo>
        <relationshipName>Review_Step_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StepNumber__c</fullName>
        <label>Step Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Review Step Template</label>
    <nameField>
        <label>Review Step Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Step Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/BusinessPackageTriggerHelper.cls
/*
    All code for Trigger on BusinessPackage Object
    ***********************************************************
    Audit History
    ***********************************************************
    12/14/2015         Davinder Singh           Created 
   
    *********************************************************** 
*/
public with sharing class BusinessPackageTriggerHelper extends GNT.TriggerHelper{
    public static Boolean skipTrigger= false;
    

    public override void processAfterInsert() {
        String appName = GNT.UserPreferenceHelper.getStringValue('ActiveAppName__c');
         updatePackageName();
      	if(appName == 'StateasGrantor') {
			updateReviewStepTemplate(); 
        }
  	}     
    
     private void updateReviewStepTemplate(){
        Savepoint sp = Database.setSavepoint();
        Map<String, String> bizPackIdByRecordId = new Map<String, String>();
        String type;
        List<ReviewStepTemplate__c> rstList= new List<ReviewStepTemplate__c>();
        List<GNT__Package__c> lst= new List<GNT__Package__c>();
        Map<String, ReviewStepTemplate__c> rstObjList = new Map<String, ReviewStepTemplate__c>();            
		for(BusinessPackage__c businessPkg : (List<BusinessPackage__c>) Trigger.New){
			if(businessPkg.Program__c!=null){
       			bizPackIdByRecordId.put( businessPkg.Id, businessPkg.Program__c);
				type='Program';
          	} else if(businessPkg.FundingOpportunity__c!=null){
               bizPackIdByRecordId.put( businessPkg.Id, businessPkg.FundingOpportunity__c);
               type='Announcement';
            } else {
            	return;
            }    
        }
        system.debug('-inside BusinessPackageTriggerHelper--bizPackIdByRecordId--'+bizPackIdByRecordId);
       	if(type=='Program') {
			rstList = [Select Id,Program__c,PreviewForm__c,StepNumber__c from ReviewStepTemplate__c where Program__c =:bizPackIdByRecordId.values() ];
       	} else if(type=='Announcement') {
	         rstList = [Select Id,Program__c,PreviewForm__c,StepNumber__c from ReviewStepTemplate__c where Announcement__c =:bizPackIdByRecordId.values() ];
       	}
       	system.debug('---rstList-1--'+rstList);
       	if(type=='Program') {
			lst =  [Select (SELECT Id,GNT__FormConfig__c,GNT__FormConfig__r.GNT__FormType__c FROM  GNT__PackageFormsConfig__r order By GNT__Order__c ) FROM GNT__Package__c where id IN (Select PackageConfig__c from BusinessPackage__c where Program__c IN :bizPackIdByRecordId.values() and PackageType__c='App-Review') Limit 1];
       	} else if(type=='Announcement') {
			lst =  [Select (SELECT Id,GNT__FormConfig__c,GNT__FormConfig__r.GNT__FormType__c FROM  GNT__PackageFormsConfig__r order By GNT__Order__c ) FROM GNT__Package__c where id IN (Select PackageConfig__c from BusinessPackage__c where FundingOpportunity__c IN :bizPackIdByRecordId.values() and PackageType__c='App-Review') Limit 1];
       	}

        // For showing the Form Preview link
        // Pankaj : We need to refactor below logic.
        String baseUrl =URL.getSalesforceBaseUrl().toExternalForm();            
        if(lst!=null && lst.size()>0) { 
            List<GNT__PackageFormConfig__c> pkgForm = lst[0].GNT__PackageFormsConfig__r;
            for(GNT__PackageFormConfig__c pkg : pkgForm) {
				for(ReviewStepTemplate__c rst : rstList) {
					System.debug('rst--' + rst);
               		if(rst.StepNumber__c==1 && pkg.GNT__FormConfig__r.GNT__FormType__c=='Pre-Screening') {
              			rst.PreviewForm__c=baseUrl+'/apex/DynamicViewLayout?isPreviewLayout=true&formPackageId='+pkg.Id;
                  		rst.ReviewFormConfig__c=pkg.GNT__FormConfig__c;
                  		rst.previewId__c=pkg.Id;
                  		rstObjList.put(rst.Id, rst);
                  	} else if(rst.StepNumber__c==2 && pkg.GNT__FormConfig__r.GNT__FormType__c=='SME Review') {
                  		rst.PreviewForm__c=baseUrl+'/apex/DynamicViewLayout?isPreviewLayout=true&formPackageId='+pkg.Id;
                  		rst.ReviewFormConfig__c=pkg.GNT__FormConfig__c;
                  		rst.previewId__c=pkg.Id;
                  		rstObjList.put(rst.Id, rst);
                  	} else if(rst.StepNumber__c==3 && pkg.GNT__FormConfig__r.GNT__FormType__c=='Management Review') {
                  		rst.PreviewForm__c=baseUrl+'/apex/DynamicViewLayout?isPreviewLayout=true&formPackageId='+pkg.Id;
                  		rst.ReviewFormConfig__c=pkg.GNT__FormConfig__c;
                  		rst.previewId__c=pkg.Id;
                  		rstObjList.put(rst.Id, rst);
                  	}
        		}
          	}
        }
        try{
      		update rstObjList.values();
        }
        catch(Exception e){
        	Database.rollback(sp);
        	ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'Select a Proper Review Package');
            ApexPages.addMessage(errorMessage);
        }
	}

  /* This method creates a unique package name for a package associated with Grant/Program/Announcement 
    It prepends the Id of associated parent to the Package name provided by the user */
  private void updatePackageName(){

      List<BusinessPackage__c> businessLst = new List<BusinessPackage__c>();
      List<BusinessPackage__c> businessLst2 = [Select Id, UniquePackageName__c, FundingOpportunity__r.Name ,Grant__r.Name,Program__r.Name, PackageName__c from BusinessPackage__c where id =:Trigger.New ];
      for(BusinessPackage__c businessPkg : businessLst2){
          if(businessPkg.FundingOpportunity__c !=null){
            String uniqueName = businessPkg.FundingOpportunity__r.Name+' '+ '-'+' '+ businessPkg.PackageName__c;
            businessPkg.UniquePackageName__c = uniqueName;
            businessLst.add(businessPkg);
          }
          else if(businessPkg.Grant__c!=null){
            String uniqueName = businessPkg.Grant__r.Name+' '+ '-'+' '+ businessPkg.PackageName__c;
            businessPkg.UniquePackageName__c = uniqueName;
            businessLst.add(businessPkg);
          }
          else if(businessPkg.Program__c!=null){
            String uniqueName = businessPkg.Program__r.Name+' '+ '-'+' '+ businessPkg.PackageName__c;
            businessPkg.UniquePackageName__c = uniqueName;
            businessLst.add(businessPkg);
            System.debug(businessLst);
          }
          else{
               businessPkg.UniquePackageName__c = businessPkg.PackageName__c;
          }
      }

      update businessLst;
  }
}