UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Funding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A unique id to relate the announcement to the program.</description>
        <label>Program ID</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <description>Announcement type is based on Application that user is logged in</description>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodEndDate__c</fullName>
        <label>Project Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodStartDate__c</fullName>
        <description>Project Period Start Date as entered by the applicant.</description>
        <label>Project Period Start Date</label>
        <type>Date</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <description>Application Created by the user in State as Grantor App</description>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GranteePOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grantee POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awards_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodEndDate__c</fullName>
        <description>Project Period End Date for the award.</description>
        <label>Project Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodStartDate__c</fullName>
        <description>Project Period Start Date for the award.</description>
        <label>Project Period Start Date</label>
        <type>Date</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <description>This Classifies whether it is Grantor or Grantee</description>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>GrantsAnn</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GranteePOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grantee POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Grants1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IssueDate__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProgramCode</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodEndDate__c</fullName>
        <label>Project Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodStartDate__c</fullName>
        <label>Project Period Start Date</label>
        <type>Date</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RolesAndResponsibilities__c.object
<CustomObject>
    <description>[Business] Roles and Responsibilities defined for all the objects like Opportunity ,Application etc</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BusinessRole__c</fullName>
        <description>This is a picklist which will be displayed in RR table in all phases.</description>
        <label>Business Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BusinessRole</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>RolesandResponsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to populate the Program to which this Role and and Responsibility belongs</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SiteVisit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Visit</label>
        <referenceTo>SiteVisit__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Roles and Responsibilities</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles and Responsibilities</pluralLabel>
    <recordTypes>
        <fullName>Award</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Award.</description>
        <label>Award</label>
    </recordTypes>
    <recordTypes>
        <fullName>Grant</fullName>
        <active>true</active>
        <label>Grant</label>
    </recordTypes>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Program.</description>
        <label>Program</label>
    </recordTypes>
    <recordTypes>
        <fullName>SiteVisit</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee SiteVisit.</description>
        <label>Site Visit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/SiteVisit__c.object
<CustomObject>
    <description>[Business] This object is used to store all the information related to the Site Visits which is a Post Award Activity.</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Site Visits</relationshipLabel>
        <relationshipName>SiteVisits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Site Visits</relationshipLabel>
        <relationshipName>Site_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GranteePOC__c</fullName>
        <formula>Grant__r.GranteePOC__r.FirstName &amp; &apos;&apos; &amp;  Grant__r.GranteePOC__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Grantee POC</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramRating__c</fullName>
        <label>Program Rating</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Satisfactory Progress</fullName>
                </value>
                <value>
                    <fullName>Unsatifactory Progress</fullName>
                </value>
                <value>
                    <fullName>Follow up needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recommendation__c</fullName>
        <label>Recommendation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Continue to Monitor</fullName>
                </value>
                <value>
                    <fullName>Reprogramming Required</fullName>
                </value>
                <value>
                    <fullName>Follow up Visit Scheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VisitDateandTime__c</fullName>
        <description>Visit Start Date and Time</description>
        <inlineHelpText>Visit Start Date and Time</inlineHelpText>
        <label>Visit Start Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>VisitEndDateTime__c</fullName>
        <description>Visit End Date and Time</description>
        <inlineHelpText>Visit End Date and Time</inlineHelpText>
        <label>Visit End Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <description>Grantor</description>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <formula>FirstName + &quot; &quot; + LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestSiteVisitTriggerHelper.cls
/**
* SiteVisitTriggerHelper
* @author: Sarat Mahavratayajula
*/
@isTest
private with sharing class TestSiteVisitTriggerHelper {
                        
    @isTest static void someTest()
      {
        UserTriggerHelper.skipTrigger=true;
        user u = TestHelper.getAdminUser(true);
        system.runAs(u) {
            // skip unwanted triggers
            AnnouncementTriggerHelper.skipTrigger = true;
            ApplicationtriggerHelper.skiptrigger = true;
            RolesandResponsibilitiesTriggerHelper.skipTrigger = true;
            GranttriggerHelper.skipTrigger = true;
            AwardTriggerHelper.skipTrigger = true;

            Announcement__c ann = TestHelper.getAnnouncement(true);
            Application__c app = TestHelper.getApplication(ann.Id,true);

            Grant__c grant = new Grant__c(ProjectPeriodStartDate__c=Date.newInstance(2015,3,14),
                                          ProjectPeriodEndDate__c=Date.newInstance(2016,3,14),
                                          IssueDate__c=Date.newInstance(2015,2,14),
                                          Program__c=ann.Program__c,GranteePOC__c = u.id);
            insert grant;

            Award__c awd = TestHelper.getAwards(grant.Id,true);

            Id recTypeId = TestHelper.getRecordType(Schema.SObjectType.RolesAndResponsibilities__c,'Award');

            List<RolesAndResponsibilities__c> rolesandResponsibilities = new List<RolesAndResponsibilities__c>();

            RolesAndResponsibilities__c rolesAndResponsibility1 = new RolesAndResponsibilities__c(RecordTypeId=recTypeId,
                                                                    Award__c=awd.Id,
                                                                    Name__c=u.Id,
                                                                    BusinessRole__c='Program Approver');
            RolesAndResponsibilities__c rolesAndResponsibility2 = new RolesAndResponsibilities__c(RecordTypeId=recTypeId,
                                                                    Award__c=awd.Id,
                                                                    Name__c=u.Id,
                                                                    BusinessRole__c='Fiscal Approver');

            rolesandResponsibilities.add(rolesAndResponsibility1);
            rolesandResponsibilities.add(rolesAndResponsibility2);

            insert rolesandResponsibilities;

            //Id recordTypeId = TestHelper.getRecordType(Schema.SObjectType.ActiveAppName__c,'StateasGrantor');
            GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c', 'StateasGrantor');
            SiteVisit__c siteVisit = new SiteVisit__c(VisitDateandTime__c=System.today() + 1,   
                                    VisitEndDateTime__c = system.today() + 60,Recommendation__c = 'test',
                                    ProgramRating__c = 'test',Status__c='Planned',Award__c=awd.Id);
            insert siteVisit;

            siteVisit.ProgramRating__c = 'test 1';
            update siteVisit;

            Test.startTest();
                SiteVisitTriggerHelper SiteVisitTriggerHelper = new SiteVisitTriggerHelper();
            Test.stopTest();
        }                    
    }  
    @isTest static void someTest1()
      {
        UserTriggerHelper.skipTrigger=true;
        user u = TestHelper.getAdminUser(true);
        system.runAs(u) {
            // skip unwanted triggers
            AnnouncementTriggerHelper.skipTrigger = true;
            ApplicationtriggerHelper.skiptrigger = true;
            RolesandResponsibilitiesTriggerHelper.skipTrigger = true;
            GranttriggerHelper.skipTrigger = true;
            AwardTriggerHelper.skipTrigger = true;

            Announcement__c ann = TestHelper.getAnnouncement(true);
            Application__c app = TestHelper.getApplication(ann.Id,true);

            Grant__c grant = new Grant__c(ProjectPeriodStartDate__c=Date.newInstance(2015,3,14),
                                          ProjectPeriodEndDate__c=Date.newInstance(2016,3,14),
                                          IssueDate__c=Date.newInstance(2015,2,14),
                                          Program__c=ann.Program__c,GranteePOC__c = u.id);
            insert grant;

            Award__c awd = TestHelper.getAwards(grant.Id,true);

            Id recTypeId = TestHelper.getRecordType(Schema.SObjectType.RolesAndResponsibilities__c,'Award');

            List<RolesAndResponsibilities__c> rolesandResponsibilities = new List<RolesAndResponsibilities__c>();

            RolesAndResponsibilities__c rolesAndResponsibility1 = new RolesAndResponsibilities__c(RecordTypeId=recTypeId,
                                                                    Award__c=awd.Id,
                                                                    Name__c=u.Id,
                                                                    BusinessRole__c='Program Approver');
            RolesAndResponsibilities__c rolesAndResponsibility2 = new RolesAndResponsibilities__c(RecordTypeId=recTypeId,
                                                                    Award__c=awd.Id,
                                                                    Name__c=u.Id,
                                                                    BusinessRole__c='Fiscal Approver');

            rolesandResponsibilities.add(rolesAndResponsibility1);
            rolesandResponsibilities.add(rolesAndResponsibility2);

            insert rolesandResponsibilities;

            //Id recordTypeId = TestHelper.getRecordType(Schema.SObjectType.ActiveAppName__c,'StateasGrantor');
            GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c', 'StateasGrantee');
            SiteVisit__c siteVisit = new SiteVisit__c(VisitDateandTime__c=System.today() + 1,   
                                    VisitEndDateTime__c = system.today() + 60,Recommendation__c = 'test',
                                    ProgramRating__c = 'test',Status__c='Planned',Award__c=awd.Id);
            insert siteVisit;

            siteVisit.ProgramRating__c = 'test 1';
            siteVisit.Status__c = 'Submitted to Grantor';
            update siteVisit;

            Test.startTest();
                SiteVisitTriggerHelper SiteVisitTriggerHelper = new SiteVisitTriggerHelper();
            Test.stopTest();
        }                    
    }                      
}