UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A unique id to relate the announcement to the program.</description>
        <label>Program ID</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The internal approver for the application</description>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applicationsap2u</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryApplicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is to store the primary Applicant user details. This is used to control Submit Application Button</description>
        <label>Primary Applicant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applicationstpqm</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WaiveWithdraw__c</fullName>
        <label>WaiveWithdraw</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Waive</fullName>
                </value>
                <value>
                    <fullName>Withdraw</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestApplicationWaiver.cls
@isTest
private with sharing class TestApplicationWaiver{

    static testMethod void testExecute1() {
    /*
        AnnouncementTriggerHelper.skipTrigger=true;
        AccountTriggerHelper.skipTrigger=true;
        USBEAnnouncementTriggerHelper.skipTrigger=true;
        ApplicationTriggerHelperUSBE.skipTrigger=true;
        ApplicationTriggerHelper.skipTrigger=true;

        Account acc=TestHelper.getAccount(true);
        User u = TestHelper.getAdminUser(true);

        Program__c prog=TestHelper.getProgram(acc.id,true);

        Announcement__c ann=TestHelper.getAnnouncement(prog.id,true);
        
        Application__c app=TestHelper.getApplication(ann.id,false);
        app.PrimaryApplicant__c=u.id;
        app.WaiveWithdraw__c = 'Waive';
        app.Approver__c=u.id;
        insert app;
        
        Task tsk=TestHelper.getTask(false);
        tsk.WhatId=app.id;
        tsk.OwnerId=u.Id;
        tsk.Status='In Progress';
        insert tsk;

        ApplicationWaiver appwaiver=new ApplicationWaiver();  
        appwaiver.selectedRecordId=app.ID;
        appwaiver.selectedAction='Approve';
       
        
    
        System.runAs(u){
            Test.startTest();  
            appwaiver.execute();
            appwaiver.selectedAction='Reject';
            appwaiver.execute();

            Test.stopTest();
        }
*/
    }


    static testMethod void testExecute2() {
    /*
        AnnouncementTriggerHelper.skipTrigger=true;
        AccountTriggerHelper.skipTrigger=true;
        USBEAnnouncementTriggerHelper.skipTrigger=true;
        ApplicationTriggerHelperUSBE.skipTrigger=true;
        ApplicationTriggerHelper.skipTrigger=true;

        Account acc=TestHelper.getAccount(true);
        User u = TestHelper.getAdminUser(true);

        Program__c prog=TestHelper.getProgram(acc.id,true);

        Announcement__c ann=TestHelper.getAnnouncement(prog.id,true);
        
        Application__c app=TestHelper.getApplication(ann.id,false);
        app.PrimaryApplicant__c=u.id;
        app.WaiveWithdraw__c = 'Withdraw';
        app.Approver__c=u.id;
        insert app;
        
        Task tsk=TestHelper.getTask(false);
        tsk.WhatId=app.id;
        tsk.OwnerId=u.Id;
        tsk.Status='In Progress';
        insert tsk;

        ApplicationWaiver appwaiver=new ApplicationWaiver();  
        appwaiver.selectedRecordId=app.ID;
        appwaiver.selectedAction='Approve';
       
        
    
        System.runAs(u){
            Test.startTest();  
            appwaiver.execute();
            appwaiver.selectedAction='Reject';
            appwaiver.execute();

            Test.stopTest();
        }
*/
    }
    
  }