UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>AnnouncementLink__c</fullName>
        <formula>HYPERLINK(&apos;/&apos;+Id, Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Announcement Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ApplicationDeadlineWithDateTime__c</fullName>
        <label>Application Deadline</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ApplicationsReviewStatus__c</fullName>
        <label>Applications Review Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NumberOfApplications__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Applications</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A unique id to relate the announcement to the program.</description>
        <label>Program ID</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>End date of the program, to determine if it is a single or a multi year program</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewProcess__c</fullName>
        <label>ReviewProcess</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ProgramPathway__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>One step review</fullName>
                    <label>One Step Review</label>
                </value>
                <value>
                    <fullName>No Review</fullName>
                </value>
                <value>
                    <fullName>Three step review</fullName>
                    <isActive>false</isActive>
                    <label>Three Step Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewGroup__c.object
<CustomObject>
    <description>[Business] This object summarizes number of Applications/Pre-Applications and number of Review Steps. As discussed with Shiva, Shah, Davinder , this object can not removed sometime later when possible.</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity ID</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Review Groups</relationshipLabel>
        <relationshipName>Review_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NumberOfApplications__c</fullName>
        <formula>IF((Announcement__r.OrganizationName__c == &apos;USBE&apos;), Announcement__r.NumberOfApplicationsInReview__c, Announcement__r.NumberOfApplications__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of Applications</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Review Groups</relationshipLabel>
        <relationshipName>Review_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review Group</label>
    <nameField>
        <displayFormat>RG-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Groups</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewPanelTemplate__c.object
<CustomObject>
    <description>[Business] Template defined for the Review</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ReviewStepTemplate__c</fullName>
        <label>Review Step Template</label>
        <referenceTo>ReviewStepTemplate__c</referenceTo>
        <relationshipName>Review_Panel_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReviewersCount__c</fullName>
        <label>ReviewersCount</label>
        <summaryForeignKey>PanelUserTemplate__c.ReviewPanelTemplate__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Review Panel</label>
    <nameField>
        <label>Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Panels</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStep__c.object
<CustomObject>
    <description>[Business] Defines all the details of Review Step defined in the Review of Application/Pre-Application</description>
    <fields>
        <fullName>ApplicationAssignment__c</fullName>
        <label>Application Assignment</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NumberOfApplications__c</fullName>
        <inlineHelpText>Number of Applications in a step</inlineHelpText>
        <label>Applications Available Per Review</label>
        <summaryFilterItems>
            <field>ReviewStepApplication__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Application</value>
        </summaryFilterItems>
        <summaryForeignKey>ReviewStepApplication__c.ReviewStep__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ReviewGroup__c</fullName>
        <label>Review Group</label>
        <referenceTo>ReviewGroup__c</referenceTo>
        <relationshipLabel>Review Steps</relationshipLabel>
        <relationshipName>Review_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReviewStepTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review Step Template</label>
        <referenceTo>ReviewStepTemplate__c</referenceTo>
        <relationshipLabel>Review Steps</relationshipLabel>
        <relationshipName>Review_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewersCount__c</fullName>
        <label>No. Of Reviewers</label>
        <summarizedField>ReviewPanel__c.ReviewersCount__c</summarizedField>
        <summaryForeignKey>ReviewPanel__c.ReviewStep__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>StepNumber__c</fullName>
        <label>Step Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Review Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Steps</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStepTemplate__c.object
<CustomObject>
    <description>[Business] Template defined for a Step Review , Previous Name (Review Step Template)</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link the announcement record.</description>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>ReviewStepTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApplicationAssignment__c</fullName>
        <inlineHelpText>How the Applications needs to be divided between Panels/Reviewers</inlineHelpText>
        <label>Application Assignment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auto-Assign to All</fullName>
                    <default>true</default>
                    <label>Auto-Assign to All</label>
                </value>
                <value>
                    <fullName>Auto-Divide Equally</fullName>
                </value>
                <value>
                    <fullName>Manual Assignment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MultiplePanelsRequired__c</fullName>
        <inlineHelpText>Does it Require more than 1 Panels for this Review Step? 1 Panel is added by default</inlineHelpText>
        <label>Does it Require Multiple Review Panels</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NumberOfReviewPanels__c</fullName>
        <label>Number of Review Panels</label>
        <summaryForeignKey>ReviewPanelTemplate__c.ReviewStepTemplate__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to program record.</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>ReviewStepTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequiredStep__c</fullName>
        <formula>NOT(ISPICKVAL( IsStepOptional__c,&apos;Optional&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Optional Step</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StepNumber__c</fullName>
        <label>Step Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Review Step Template</label>
    <nameField>
        <label>Review Step Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Step Templates</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ApplicationReviewHandler.cls
global with sharing class ApplicationReviewHandler extends GNT.FlexTableActionHandler {

 public ApplicationReviewHandler() {}


 global override Map < String, Object > clickHandler() {
  Map < String, Object > resultMap = new Map < String, Object > ();
  
  Savepoint sp = Database.setSavepoint();

  try {
   if (selectedRecordIds == null || selectedRecordIds.isEmpty()) {
    //resultMap.put('Message','Please select the Announcements to Initiate Review Process');
    resultMap.put('Message', GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-63597'));
    resultMap.put('Type', 'danger');
    return resultMap;
   } else if (selectedRecordIds.size() > 1) {
    //resultMap.put('Message','Please select only 1 Record');
    resultMap.put('Message', GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-59783'));
    resultMap.put('Type', 'danger');
    return resultMap;
   } else {
    Id announcementId = selectedRecordIds[0];
    Boolean revPanelFlag = false;
    Boolean revPanelDateFlag = false;
    List < Announcement__c > annList = [Select Id, Name, AnnouncementLink__c, ApplicationsReviewStatus__c, NumberOfApplications__c, ApplicationDeadlineWithDateTime__c, Program__r.ReviewProcess__c from Announcement__c where Id = : announcementId];
    Announcement__c ann = annList[0];
    if (ann.ApplicationsReviewStatus__c == 'In Progress') {
     //resultMap.put('Message','The applications for selected Announcement are already under Review');
     resultMap.put('Message', GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-50353'));
     resultMap.put('Type', 'danger');
     return resultMap;
    }
    if (ann.NumberOfApplications__c < 1 && ann.Program__r.ReviewProcess__c != 'One step review') {
     //resultMap.put('Message','No applications has been submitted for selected Announcement');
     resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-97891'));
     resultMap.put('Type', 'danger');
     //resultMap.put('Type', 'success');
     return resultMap;
    }
    List < ReviewStepTemplate__c > rstList = [SELECT Id, Name, StepNumber__c, NumberOfReviewPanels__c, MultiplePanelsRequired__c, ApplicationAssignment__c, RequiredStep__c FROM ReviewStepTemplate__c WHERE Announcement__c = : announcementId order by StepNumber__c asc];
    System.debug('--rstList--' + rstList);
    if (rstList != null || rstList.size() > 0) {
     ReviewStepTemplate__c firstRST = rstList[0];
     List < ReviewPanelTemplate__c > rptList = [SELECT Id, Name, ReviewersCount__c, EndDate__c FROM ReviewPanelTemplate__c WHERE ReviewStepTemplate__c = : firstRST.Id];
     if (rptList.size() < 1) {
      //resultMap.put('Message','Review Panels are not present in First Review Step, please add panel, update Review Due Date and add Reviewers before continuing');
      resultMap.put('Message', GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-21865'));
      resultMap.put('Type', 'danger');
      return resultMap;
     }
     for (ReviewPanelTemplate__c revPanel: rptList) {
      system.debug('--revPanel--' + revPanel);
      if (revPanel.ReviewersCount__c < 1) {
       revPanelFlag = true;
       break;
      }
      if (revPanel.EndDate__c == null || revPanel.EndDate__c < System.Today()) {
       revPanelDateFlag = true;
       break;
      }
     }
     if (revPanelFlag) {
      //resultMap.put('Message',firstRST.Name+' does not have Reviewers in all the associated Panels. Please add Reviewer in Announcement');
      resultMap.put('Message', firstRST.Name + ' ' + GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-28229'));
      resultMap.put('Type', 'danger');
      return resultMap;
     }
     If(revPanelDateFlag) {
      //resultMap.put('Message',firstRST.Name+' does not have Valid Review Due Date in all the associated Panels.');
      resultMap.put('Message', firstRST.Name + ' ' + GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-59170'));
      resultMap.put('Type', 'danger');
      return resultMap;
     }
     if (ann.ApplicationDeadlineWithDateTime__c > System.now() && ann.Program__r.ReviewProcess__c != 'One step review') {
      //resultMap.put('Message','Application Review can not be started before Application Deadline');
      resultMap.put('Message', GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-84986'));
      resultMap.put('Type', 'danger');
      return resultMap;
     }


     // Find the announcement Id.
     // Check the first step in RSATemplate object and see its application assignment
     // If auto -> call InitiateApplicationReviewHandler class
     //otherwise call ReviewTasksHandler and let user do it manually

     ReviewStepTemplate__c rst = rstList[0];
     system.debug('--rst--' + rst);
     String appAssignment;
     if (rst != null && rst.ApplicationAssignment__c != null) {
      appAssignment = rst.ApplicationAssignment__c;
     } else {
      appAssignment = 'Auto-Assign to All';
     }
     system.debug('**appAssignment --' + appAssignment);
     //  appAssignment='Auto-Assign to All';      
     if (appAssignment == 'Auto-Assign to All') {
      ReviewTasksHandler rth = new ReviewTasksHandler(announcementId);
      rth.insertReviewTasks();
      //ReviewGroup__c rg = [Select Id, Name, Announcement__c from ReviewGroup__c where Announcement__c = : announcementId limit 1];
      //system.debug('**rg --' + rg);
      system.debug('**announcementId--' + announcementId);
      ReviewStep__c revStep = [Select Id from ReviewStep__c where ReviewGroup__r.Announcement__c = : announcementId and stepNumber__c = 1 limit 1];
      system.debug('--revStep --' + revStep);
      ApplicationReviewHelper arh = new ApplicationReviewHelper();
      arh.createReviewTasks(revStep.Id);
     } else if (appAssignment == 'Equal Distribution') {
      ReviewTasksHandler rth = new ReviewTasksHandler(announcementId);
      rth.insertReviewTasks();
      ReviewStep__c revStep = [Select Id from ReviewStep__c where ReviewGroup__r.Announcement__c = : announcementId and stepNumber__c = 1 limit 1];
      System.debug('--revStep --' + revStep);
      ApplicationReviewHelper arh = new ApplicationReviewHelper();
      arh.createReviewTasks(revStep.Id);
     } else if (appAssignment == 'Manual Assignment') { // Do not create reviews, just start the review and let PM take it forward
      ReviewTasksHandler rth = new ReviewTasksHandler(selectedRecordIds);
      rth.insertReviewTasks();
     }
    } else {
     //resultMap.put('Message','Application Review can not be started for the selected announcement');
     resultMap.put('Message', GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-31863'));
     resultMap.put('Type', 'danger');
     return resultMap;
    }
   }
  } catch (Exception e) {
   Database.rollback(sp);
   system.debug(e.getMessage());
   resultMap.put('Message', 'Error message: ' + e.getMessage());
   resultMap.put('Type', 'danger');
   return resultMap;
  }
  //resultMap.put('Message','Review process has been initiated');
  resultMap.put('Message', GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-50344'));
  resultMap.put('Type', 'success');
  return resultMap;
 }
}