UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>BudgetCategory__c</fullName>
        <description>Is Budget Category needed at Individual or Total Level?</description>
        <label>Budget Category Required?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget Category Level</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Overall Level</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AnnouncementServiceArea__c.object
<CustomObject>
    <description>[Business]  Service Area associated with an Annoucement</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>RelatedServiceAreas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Area</label>
        <referenceTo>ServiceArea__c</referenceTo>
        <relationshipName>AnnouncementServiceAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Opportunity Project Area</label>
    <nameField>
        <displayFormat>ASA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Opportunity Project Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ApplicationBudgetCategory2__c.object
<CustomObject>
    <description>[Business] Stores the Budget related information associated with an Application</description>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application_Budget_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BudgetCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Category</label>
        <referenceTo>BudgetCategory__c</referenceTo>
        <relationshipName>Application_Budget_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Area</label>
        <referenceTo>ApplicationServiceArea__c</referenceTo>
        <relationshipName>Application_Budget_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Budget Category</label>
    <nameField>
        <displayFormat>AC-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Budget Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ApplicationServiceArea__c.object
<CustomObject>
    <description>[Business] Associates a Service area with an Application</description>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application_Service_Areas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity Project Area</label>
        <referenceTo>AnnouncementServiceArea__c</referenceTo>
        <relationshipLabel>Application Project Areas</relationshipLabel>
        <relationshipName>Application_Service_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Project Area</label>
    <nameField>
        <displayFormat>ASA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Project Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BudgetCategory__c.object
<CustomObject>
    <description>[Business] This object stores the Master List of all the Budget categories</description>
    <label>MST: Budget Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Category</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ServiceArea__c.object
<CustomObject>
    <description>[Business] Master list of all the Service Area information is stored in this object , Service areas are also applicable to the Announcements ,Programs,Application via Junction objects</description>
    <label>Project/Service Area</label>
    <nameField>
        <displayFormat>PSA-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestApplicationServiceAreaTriggerHelper.cls
@isTest
private with sharing class TestApplicationServiceAreaTriggerHelper{
    static testMethod void testController() {
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          System.runAs(u){
              AnnouncementTriggerHelper.skipTrigger=true;
              ApplicationTriggerHelper.skipTrigger = true;
              Announcement__c ann = TestHelper.getAnnouncement(true);
              Application__c app = Testhelper.getApplication(ann.Id,true);
              ServiceArea__c servArea = TestHelper.getServiceArea(true);
              AnnouncementServiceArea__c annServArea = new AnnouncementServiceArea__c();
              annServArea .Announcement__c = ann.Id;
              annServArea .ServiceArea__c = servArea.Id;
              insert annServArea;
              List<BudgetCategory__c> budCat = TestHelper.getBudgetCategory(true);
              ApplicationBudgetCategory2__c appBudCat = new ApplicationBudgetCategory2__c(Application__c=app.Id,BudgetCategory__c=budCat[0].Id);
              List<ApplicationBudgetCategory2__c> newLst=new List<ApplicationBudgetCategory2__c>();
              newLst.add(appBudCat);
              insert newLst;
              //insert appBudCat;
              ApplicationServiceArea__c appServArea= new ApplicationServiceArea__c ();
              appServArea .Application__c= app.Id;
              appServArea .ServiceArea__c = annServArea.Id;
              List<ApplicationServiceArea__c> newLst1=new List<ApplicationServiceArea__c>();
              newLst1.add(appServArea);
              insert newLst1;
              delete newLst1;
              
             
              
         }
        
    }
}