UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreApplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre Application</label>
        <referenceTo>PreApplication__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PanelApplication__c.object
<CustomObject>
    <description>[Business] Defines a review Panel for an Application /Pre-Application</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Panel Applications</relationshipLabel>
        <relationshipName>Panel_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreApplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Application</label>
        <referenceTo>PreApplication__c</referenceTo>
        <relationshipLabel>Panel Applications</relationshipLabel>
        <relationshipName>Panel_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewPanel__c</fullName>
        <label>Review Panel</label>
        <referenceTo>ReviewPanel__c</referenceTo>
        <relationshipLabel>Panel Applications</relationshipLabel>
        <relationshipName>Panel_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Panel Application</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Panel Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panel Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PanelUser__c.object
<CustomObject>
    <description>[Business]  Association of a User to a Review panel</description>
    <fields>
        <fullName>ReviewPanel__c</fullName>
        <label>Review Panel</label>
        <referenceTo>ReviewPanel__c</referenceTo>
        <relationshipName>Review_Panel_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Review_Panel_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Panel User</label>
    <nameField>
        <displayFormat>PU-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panel Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PreApplication__c.object
<CustomObject>
    <description>[Business] Pre-Application is a trimmed version of the Application with limited information</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>PreApplications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Pre-Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pre-Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Review__c.object
<CustomObject>
    <description>[Business] Defines the Review object (Need more Details / Need to revisit for the Description)</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PanelApplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Panel Application</label>
        <referenceTo>PanelApplication__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PanelUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Panel User</label>
        <referenceTo>PanelUser__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreApplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Application</label>
        <referenceTo>PreApplication__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewPanel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review Panel</label>
        <referenceTo>ReviewPanel__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review Step</label>
        <referenceTo>ReviewStep__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewer(Obsolete)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewPanel__c.object
<CustomObject>
    <description>[Business] Defines the Review Panel to review the Applications</description>
    <fields>
        <fullName>ReviewStep__c</fullName>
        <label>Review Step</label>
        <referenceTo>ReviewStep__c</referenceTo>
        <relationshipLabel>Review Panels</relationshipLabel>
        <relationshipName>Review_Panels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Review Panel</label>
    <nameField>
        <displayFormat>Panel-{000}</displayFormat>
        <label>Review Panel ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStep__c.object
<CustomObject>
    <description>[Business] Defines all the details of Review Step defined in the Review of Application/Pre-Application</description>
    <label>Review Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestAssignReviewerToApplicationsHelper.cls
@isTest
private class TestAssignReviewerToApplicationsHelper{
   
      static testMethod void testclickHandler() {
          UserTriggerHelper.skipTrigger = true;   
          User u = TestHelper.getAdminUser(true); 
        
          System.runAs(u){
              AppUtils.skipStepReviewTrigger = true;
              ApplicationTriggerHelper.skipTrigger = true;
              AnnouncementTriggerHelper.skipTrigger = true;
              PanelUserTriggerHelper.skipAll = true;
              ReviewTriggerHelper.skipTrigger = true;
              List<String> IdSet = new List<String>();
              
              Announcement__c ann = TestHelper.getAnnouncement(true);
              Application__c app = TestHelper.getApplication(ann.Id,true);
              PreApplication__c preApp = Testhelper.getPreApplication(true);
              
           
              ReviewStep__c revStep = TestHelper.getReviewStep(true);
              ReviewPanel__c revPanel = new ReviewPanel__c(ReviewStep__c=revStep.Id);
              insert revPanel;
              
              PanelUser__c panelUser = new Paneluser__c(ReviewPanel__c=revPanel.Id,Reviewer__c=u.Id);
              insert panelUser;
              
              PanelApplication__c panelApp= new PanelApplication__c(ReviewPanel__c=revPanel.Id,Application__c=app.Id, PreApplication__c=preApp.Id);
              insert panelApp;
              IdSet.add(panelApp.Id);
              
              Review__c rev = new Review__c(Application__c = app.Id,PanelApplication__c=panelApp.Id,PanelUser__c=panelUser.Id,ReviewPanel__c=revPanel.Id);
              insert rev;
              
              Test.startTest();
              AssignReviewerToApplicationsHelper ctrl = new AssignReviewerToApplicationsHelper();
              ctrl.selectedRecordIds = IdSet;
              ctrl.urlparams.put('id',panelUser.Id); 
              ctrl.urlparams.put('panelId',revPanel.Id); 
              ctrl.urlparams.put('tabName','Test');
              ctrl.ClickHandler();  
              delete panelUser;
              ctrl.ClickHandler();      
              Test.stopTest();
        }
    
   }
}