UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PreApplication__c.object
<CustomObject>
    <description>[Business] Pre-Application is a trimmed version of the Application with limited information</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>PreApplications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Pre-Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pre-Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestPreApplicationApprovalHelper.cls
@isTest
private class TestPreApplicationApprovalHelper{
    static Map<String,Object> testResult;
    @isTest
    private static void testPreApplicationApprovalHelper(){
        User u = TestHelper.getAdminUser(true);
        System.runAs(u){
            Test.startTest();
            TestHelper.createCustomSettings(true);
            PreApplication__c preapp = TestHelper.getPreApplication(true);
            ApexPages.CurrentPage().getParameters().put('id',preapp.Announcement__c);
            PreApplicationApprovalHelper paah = new PreApplicationApprovalHelper();
            paah.selectedRecordIds = new List<String>();
            paah.selectedRecordIds.add(preapp.id);  
            testResult = paah.clickHandler();
            Test.stopTest();
            System.assert(testResult != null);
        }
    } 
}