UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A unique id to relate the announcement to the program.</description>
        <label>Program ID</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/OpportunityQualification__c.object
<CustomObject>
    <description>[Business] This is for a Sub Recipient to Mark an Announcement so that after some days he or she can create an application for the same announcement. This is created because there might be lots of announcement but sub recipient might be interested with only few announcement so he/she can mark it as qualified and later convert into an application</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Qualified Announcements</relationshipLabel>
        <relationshipName>Qualified_Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FundingOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>Opportunity_Sub_Recipient_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Qualified Announcements</label>
    <nameField>
        <displayFormat>FO-{0000}</displayFormat>
        <label>Qualified Announcement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualified Announcements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ProgramServiceArea__c.object
<CustomObject>
    <description>[Business] Junction object of a Program with the Service Area</description>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>ServiceAreas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceArea__c</fullName>
        <label>Service Area</label>
        <referenceTo>ServiceArea__c</referenceTo>
        <relationshipName>ProgramServiceAreas</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Project Area</label>
    <nameField>
        <displayFormat>PSA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Project Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ServiceArea__c.object
<CustomObject>
    <description>[Business] Master list of all the Service Area information is stored in this object , Service areas are also applicable to the Announcements ,Programs,Application via Junction objects</description>
    <fields>
        <fullName>CoreServiceArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Core Service Area</label>
        <referenceTo>ServiceArea__c</referenceTo>
        <relationshipName>Service_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project/Service Area</label>
    <nameField>
        <displayFormat>PSA-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestSelectApplicationCtrl.cls
@isTest(SeeAllData=false)
private class TestSelectApplicationCtrl {
    
    @isTest static void testAll() {
    /*
        UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
        AccountTriggerHelper.skipTrigger = true;
        ApplicationTriggerHelper.skipTrigger = true;
        RolesandResponsibilitiesTriggerHelper.skipTrigger = true;
        System.runAs(u){
            GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c','StateasGrantor');
            UserRole ur=new UserRole();
            ur.Name= 'ENTERPRISE';
            insert ur;
            u.UserRoleId = [Select Id From UserRole Where Name = 'ENTERPRISE' Limit 1].Id;
            update u;
            SelectApplicationCtrl sap = new SelectApplicationCtrl();
            sap.clickHandler();
            SelectApplicationCtrl.getFoType();
            SelectApplicationCtrl.getBudgetPeriodType();
            SelectApplicationCtrl.getBudgetCatType();
            Account child = TestHelper.getAccount(true);
            Account parent = TestHelper.getAccount(true);
            child.Parent = parent;
            update child;
            SelectApplicationCtrl.getBureaus(child.Parent.id);
            Program__c program = TestHelper.getProgram(child.Id, true);
            SelectApplicationCtrl.getOrganization(program.Id);

            ServiceArea__c sa = TestHelper.getServiceArea(true);
            ServiceArea__c csa = TestHelper.getServiceArea(true);
            
            sa.CoreServiceArea__c = csa.Id;
            sa.CoreServiceArea__r = csa;
            update sa;
            ProgramServiceArea__c psa = TestHelper.getProgramServiceArea(true, program.Id, sa.Id);
            psa.ServiceArea__r = sa;
            update psa;
            SelectApplicationCtrl.getCoreServiceArea(program.Id);
            SelectApplicationCtrl.getServiceArea(program.Id, csa.Name);

            Announcement__c ann = TestHelper.getAnnouncement(true);
            Application__c app = TestHelper.getApplication(ann.Id, true);
            Announcement__c fo = TestHelper.getAnnouncement(true);
            OpportunityQualification__c oq = new OpportunityQualification__c();
            oq.FundingOpportunity__c = fo.Id;
            insert oq;
            SelectApplicationCtrl.saveAndContinue(app.Id, oq.Id);
            SelectApplicationCtrl.getAllPrograms();


        }
        */
    }
    
    @isTest static void testGetServiceArea() {
    /*
        UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
        AccountTriggerHelper.skipTrigger = true;
        ApplicationTriggerHelper.skipTrigger = true;
        RolesandResponsibilitiesTriggerHelper.skipTrigger = true;
        System.runAs(u){
                Account child = TestHelper.getAccount(true);
                Program__c program = TestHelper.getProgram(child.Id, true);

                ServiceArea__c sa = TestHelper.getServiceArea(true);
                ServiceArea__c csa = TestHelper.getServiceArea(true);
                sa.CoreServiceArea__r = csa;
               // sa.CoreServiceArea__c = csa;
                update sa;
                ProgramServiceArea__c psa = TestHelper.getProgramServiceArea(true, program.Id, sa.Id);
                psa.ServiceArea__r = sa;
                update psa;
                SelectApplicationCtrl.getServiceArea(program.Id, csa.Name);
        }
        */
    }
    
}