UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ApplicationReview__c.object
<CustomObject>
    <description>[Business] This object is used for the Review of the Grantee Application in the State as a Grantee Application</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>Reviews1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Application for which the review is being done</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>ApplicationReviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Review</label>
    <nameField>
        <displayFormat>Rev-{000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ApplicationReviewViewCtrlTest.cls
@isTest
public class ApplicationReviewViewCtrlTest {
    static testMethod void someTest() {
        ApplicationReview__c appReview= null;
        Application__c app= null;
        Announcement__c ann= null;
        UserTriggerHelper.skipTrigger = true;
        
        User u = TestHelper.getAdminUser(true);
        
        System.runAs(u){
        
            GrantTriggerHelper.skipTrigger=true;
            
            RolesandResponsibilitiesTriggerHelper.skipTrigger=true;
            AnnouncementTriggerHelper.skipTrigger=true;
            PreApplicationTriggerHelper.skipTrigger = true;
            ApplicationTriggerHelper.skipTrigger= true;
            AwardTriggerHelper.skipTrigger = true;
            
            appReview = new ApplicationReview__c();
            insert appReview;
            
            ann = TestHelper.getAnnouncement(true);
            app = TestHelper.getApplication(ann.Id,true);
        }
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.standardController(appReview);
        ApexPages.currentPage().getParameters().put('id',appReview.id);
        ApexPages.CurrentPage().getParameters().put('applicationid',app.id);
        ApplicationReviewViewCtrl e = new ApplicationReviewViewCtrl(sc);
        e.getKeyValueMap();
        Test.stopTest();
    }
}