UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The grantee entered title for the application.</description>
        <label>Project Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Form__c.object
<CustomObject>
    <description>[Business] object represents forms on grants.gov1</description>
    <fields>
        <fullName>ApplicantsOrganization__c</fullName>
        <description>This field is used in Certification Regarding Lobbying Form as Applicant&apos;s Organization, Assurances for Non-Construction form as Applicant Organization, Assurances for Construction form as Applicant&apos;s Organization, Key Contacts form as Applicant Organization&apos;s Name, Project/Performance Site Location form as Organization Name, Application for Federal Assistance form as Legal name</description>
        <label>Applicant&apos;s Organization</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used in Certification Regarding Lobbying form as Date, Assurances for Non Construction form as Date, Assurances for Construction form as Date, Application for Federal Assistance form as Date Received, SF-424 R&amp;R Multi-project Cover form as Date Submitted,  Research &amp; Related Other Project Information form.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Signature__c</fullName>
        <description>This field is used in Certification Regarding Lobbying form as Signature, Assurances for Non Construction form as Signature, Assurances for Construction form as Signature.</description>
        <label>Signature</label>
        <length>144</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>This field is used in Certification Regarding Lobbying form as Title, Assurances for Non Construction form as Title, Assurances for Construction form as Title, Key Contacts form as Title, Application for Federal Assistance form as Title under Name and Contact Information of person block, SF-424 RR Multi-Project Cover form.</description>
        <label>Authorized Representative Title</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Application Detail (FORMS)</label>
    <nameField>
        <displayFormat>FN-{00000}</displayFormat>
        <label>Form</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/IntegrationFormConfig__c.object
<CustomObject>
    <description>[Business] This object is used to Store the Integration Details information</description>
    <fields>
        <fullName>FormConfig__c</fullName>
        <inlineHelpText>Provide Form Configuration</inlineHelpText>
        <label>Form Config</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>CFG: Integration Form</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Form Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestGrantsGovApplicationForm.cls
/**
* @author: Sarat Mahavratayajula - 2016-08-02
*/
@isTest
private class TestGrantsGovApplicationForm {
/*    public static void setup(){
        // Skip unwanted triggers
        AnnouncementTriggerHelper.skipTrigger = true;
        ApplicationtriggerHelper.skiptrigger = true;
    }
    
    
    @isTest static void test1() {
        setup();
        Announcement__c ann = TestHelper.getAnnouncement(true);
        Application__c application = TestHelper.getApplication(ann.Id, true);
        Form__c form1 = new Form__c();
        form1.Title__c = 'Test title';
        form1.ApplicantsOrganization__c = 'Some test organization';
        form1.Date__c = system.today() + 100;
        form1.Application__c = application.Id;      
        insert form1;

        String formName = 'TestForm1';
        String xmlDoc = '<?xml version="1.0"?><ResultSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:yahoo:maps" xsi:schemaLocation="urn:yahoo:maps http://api.local.yahoo.com/MapsService/V1/GeocodeResponse.xsd"><Result precision="address"><Latitude>37.416397</Latitude><Longitude>-122.025055</Longitude><Address>701 1st Ave</Address><City>Sunnyvale</City><State>CA</State><Zip>94089-1019</Zip><Country>US</Country></Result></ResultSet>';
        
        Dom.Document doc = new Dom.Document();
        doc.load(xmlDoc);
        Dom.XMLNode root = doc.getRootElement();

        IntegrationFormConfig__c integrationFormConfig = new IntegrationFormConfig__c();
        integrationFormConfig.Name = formName;
        integrationFormConfig.IsActive__c = true;
        /*integrationFormConfig.FormConfig__c   = '{ "name": "GG_V1_1_Assurances_for_Non-Construction_Programs(SF-424B)", ' +
                                                '"structure": ' + 
                                                '{ "objectName": "Form__c",' +  
                                                '"namespaces":[ ' + 
                                                '{"name" : "SF424B", "value":"http://apply.grants.gov/forms/SF424B-V1.1"},' +
                                                '{"name" : "glob", "value":"http://apply.grants.gov/system/Global-V1.0"} ],' +
                                                '"root":' +
                                                '{ "name":"Assurances", "namespacePrefix":"SF424B", "regNamespaces":["SF424B", "glob"],' +
                                                '"attributes": ['+
                                                '{ "name": "coreSchemaVersion", "value": "1.1", "type":"fixed", "namespacePrefix":"glob" },'+ 
                                                '{ "name": "programType", "value": "Non-Construction", "type":"fixed",' +
                                                '"namespacePrefix":"SF424B" } ] }, "children": ['+
                                                '{ "name": "FormVersionIdentifier", "namespacePrefix":"glob",' +
                                                '"dataconfig": { "dataType": "fixed", "value": "4040-0007"} },' +
                                                '{ "name": "AuthorizedRepresentative", "namespacePrefix":"SF424B", "children": [' +
                                                '{ "name": "RepresentativeName", "namespacePrefix":"SF424B",' +
                                                '"dataconfig": { "field": "Signature__c"} },' +
                                                '{ "name": "RepresentativeTitle", "namespacePrefix":"SF424B",' +
                                                '"dataconfig": { "field": "Title__c"} } ] },' +
                                                '{ "name": "ApplicantOrganizationName", "namespacePrefix":"SF424B",' +
                                                '"dataconfig": { "field": "ApplicantsOrganization__c"} },'+
                                                '{ "name": "SubmittedDate", "namespacePrefix":"SF424B",' +
                                                '"dataconfig": { "field": "Date__c", "dataType": "date"} } ] } }';*/
    
        
     /**   insert integrationFormConfig;

        List<GrantsGovApplicationForm.FormNameSpace> formNameSpaces = new List<GrantsGovApplicationForm.FormNameSpace>();

        GrantsGovApplicationForm.FormNameSpace formNameSpace1 = new GrantsGovApplicationForm.FormNameSpace();
        formNameSpace1.name = 'Some name';
        formNameSpace1.value = 'Some Value';

        GrantsGovApplicationForm.FormNameSpace formNameSpace2 = new GrantsGovApplicationForm.FormNameSpace();
        formNameSpace2.name = 'Some name';
        formNameSpace2.value = 'Some Value';

        formNameSpaces.add(formNameSpace1);
        formNameSpaces.add(formNameSpace2);

        List<GrantsGovApplicationForm.FormField> formFields = new List<GrantsGovApplicationForm.FormField>();

        GrantsGovApplicationForm.FormField formFld1 = new GrantsGovApplicationForm.FormField();
        formFld1.Name = 'Some Name';
        formFld1.namespacePrefix = 'Some namespacePrefix';

        GrantsGovApplicationForm.FormField formFld2 = new GrantsGovApplicationForm.FormField();
        formFld2.Name = 'Some Name';
        formFld2.namespacePrefix = 'Some namespacePrefix';

        formFields.add(formFld1);
        formFields.add(formFld2);

        GrantsGovApplicationForm.FormRoot formRoot = new GrantsGovApplicationForm.FormRoot();
        formRoot.name = 'Some Name';
        formRoot.namespacePrefix = 'Some Name Prefix';

        GrantsGovApplicationForm.Structure strut = new GrantsGovApplicationForm.Structure();
        strut.objectName = 'Some Name';
        strut.namespaces = formNameSpaces;
        strut.children = formFields;
        strut.root = formRoot;

        GrantsGovApplicationForm.FormConfig formConfig1 = new GrantsGovApplicationForm.FormConfig();
        formConfig1.Name = 'Some Name';
        formConfig1.structure = strut;
        
        Test.startTest();
            GrantsGovApplicationForm grantsGovApplForm = new GrantsGovApplicationForm(application.Id,form1.Id,formName);
            grantsGovApplForm.formConfig = formConfig1;
            grantsGovApplForm.buildForm(root,doc);
        Test.stopTest();
    }*/
    
    /*@isTest static void test2() {

        // Skip unwanted triggers
        AnnouncementTriggerHelper.skipTrigger = true;
        ApplicationtriggerHelper.skiptrigger = true;

        Announcement__c ann = TestHelper.getAnnouncement(true);
        Application__c application = TestHelper.getApplication(ann.Id, true);

        String formName = 'TestForm1';
        
        Test.startTest();
            GrantsGovApplicationForm grantsGovApplForm = new GrantsGovApplicationForm(application.Id,application.Id,formName);
        Test.stopTest();
    }*/
    
    
}