UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>- In Progress - The information within the annoucement is incomplete. Such records shall not be avaiable for other users to view or edit.
- Review In Progress - Annoucements that are currently in the process of undergoing review shall have this status. Such records shall not be avaiable for other users to view or edit.
- Inactive - Approved annoucements whose Posting Date is in the future shall have this status. Such annoucements shall not be made available to recipient users.
- Active - Approved annoucements whose Posting Date is equal to the current date or is in the past and the Closing Date is in the future shall have this status. System shall make such annoucements available to recipients.
- Expired - Approved annoucements whose closing date is the current date or is in the past shall have this status. When an annoucement status changes from Active to Expired, it should no longer be made available to the recipient users.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Converted to Application</fullName>
                </value>
                <value>
                    <fullName>Converted to Pre-Application</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Approved</fullName>
                </value>
                <value>
                    <fullName>RFA Published</fullName>
                </value>
                <value>
                    <fullName>RFA Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>PreApplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre Application</label>
        <referenceTo>PreApplication__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Review Initiated</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Submitted For Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Sent for Review</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision Completed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Rejection Initiated</fullName>
                </value>
                <value>
                    <fullName>Internally Reviewed</fullName>
                </value>
                <value>
                    <fullName>Converted to Award</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Converted to Grant</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Revision Initiated</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Approved Internally</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PreApplication__c.object
<CustomObject>
    <description>[Business] Pre-Application is a trimmed version of the Application with limited information</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Awarded</fullName>
                </value>
                <value>
                    <fullName>Not Awarded</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pre-Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pre-Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewGroup__c.object
<CustomObject>
    <description>[Business] This object summarizes number of Applications/Pre-Applications and number of Review Steps. As discussed with Shiva, Shah, Davinder , this object can not removed sometime later when possible.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Submit for Approve</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Review Group</label>
    <nameField>
        <displayFormat>RG-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Groups</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStep__c.object
<CustomObject>
    <description>[Business] Defines all the details of Review Step defined in the Review of Application/Pre-Application</description>
    <fields>
        <fullName>OGMNotifiedOfRejections__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OGM Notified of Rejections</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Review Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Steps</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStepApplication__c.object
<CustomObject>
    <description>[Business] Connects the Application/Pre-Application with the User and Review Step via this object</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Review Step Applications</relationshipLabel>
        <relationshipName>Review_Step_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Decision__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsAppPromoted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the application is promoted to next reviewStep</description>
        <label>IsAppPromoted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsOGMPromoted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Overruled By OGM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MaximumAwardAmount__c</fullName>
        <label>Maximum Award Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MinimumAwardAmount__c</fullName>
        <label>Minimum Award Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Preapplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preapplication</label>
        <referenceTo>PreApplication__c</referenceTo>
        <relationshipLabel>Review Step Applications</relationshipLabel>
        <relationshipName>Review_Step_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewStatus__c</fullName>
        <inlineHelpText>This field holds the record id and status of the review records for the app / preapp in the format as  id:status#id:status</inlineHelpText>
        <label>Reviewer Recommendation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReviewStep__c</fullName>
        <label>Review Step</label>
        <referenceTo>ReviewStep__c</referenceTo>
        <relationshipName>ReviewStepApplications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reviewers Not Assigned</fullName>
                    <default>true</default>
                    <label>Reviewers Not Assigned</label>
                </value>
                <value>
                    <fullName>Reviewers Assigned</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Reviews Complete</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Review Step Application</label>
    <nameField>
        <displayFormat>RSA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Step Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/PromoteApplicationHelper.cls
global with sharing class PromoteApplicationHelper extends GNT.DynamicLayoutActionRedirect {
    
    global override PageReference whenClicked(){
        SavePoint sp = Database.setSavepoint();
        Map<String,Object> resultMap = new Map<String,Object> ();      
        Id reviewStepId = apexpages.currentpage().getparameters().get('id');
        Boolean preventNotification = false;
        Boolean appsRejected = false;
        Id nextReviewStepId;
        List<ReviewStepApplication__c> rsaList = [select Id,IsOGMPromoted__c,ReviewStatus__c,PreApplication__c,Application__c,IsAppPromoted__c,Decision__c,MinimumAwardAmount__c,MaximumAwardAmount__c FROM ReviewStepApplication__c where ReviewStep__c =: reviewStepId];
        ReviewStep__c revStp = [Select id,OGMNotifiedOfRejections__c,NoofApplicationsPending__c,Status__c from ReviewStep__c where id =: reviewStepId limit 1];
        Boolean ogmMessage = false;
        system.debug('RSA LIST ' +rsaList.size());      
        for(ReviewStepApplication__c rsa: rsaList) {
        system.debug('rsa is ' +rsa.id);
            /*if(rsa.Decision__c == 'Pending') {
                preventNotification = true;
                break;    
            }*/
            if(rsa.IsAppPromoted__c == True){
            preventNotification = true;
            }
            if(rsa.Decision__c == 'Rejected') {
                appsRejected = true;
            }
        }
        if(preventNotification == true ) {
           //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Decisions(Approved/Rejected) should be made on all the applications listed!!'));
           ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-31006')));
       
        }
        else if(revStp.Status__c =='Not Started') {
          //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Applications can not be promoted now!'));
          ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-67990')));
           
        }
        else if(revStp.Status__c =='Completed') {
            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Applications have already been promoted to Next Step!'));
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-07920')));
        }
        
        else if(preventNotification == false) {
           try{
                ReviewStep__c revStep = [select RecordType.Name, RecordType.DeveloperName,NoofApplicationsPending__c,ReviewGroup__c,StepNumber__c,OGMNotifiedOfRejections__c,ReviewGroup__r.Announcement__r.Name, Name From ReviewStep__c Where id = :reviewStepId ];
                Integer currentStep = Integer.valueOf(revStep.StepNumber__c);
                Integer nextStep = currentStep + 1;
                system.debug('nexTStep is*****' + nextStep);
                ReviewStep__c nextRevStep;
                
                Set<Id> userIdSet = new Set<Id>();
                List<ReviewStep__c> nextReviewSteps = [SELECT Id,Name,ReviewGroup__c FROM ReviewStep__c 
                                                        WHERE StepNumber__c >=: nextStep 
                                                        AND ReviewGroup__c =: revStep.ReviewGroup__c 
                                                        Order by StepNumber__c LIMIT 1 ];
                system.debug('-- debugging 16 -nextReviewSteps--'+nextReviewSteps);                                                        
                    
                List<ReviewStepApplication__c> promotedApplications = new List<ReviewStepApplication__c>();
                if(nextReviewSteps.size() > 0){
                        nextReviewStepId = nextReviewSteps.get(0).Id;
                        nextRevStep=nextReviewSteps.get(0);
                        ReviewGroup__c reviewGroup = [Select Id, Announcement__c from ReviewGroup__c where id =:nextRevStep.ReviewGroup__c ];
                        reviewGroup.CurrentReviewStep__c=nextRevStep.name;
                        reviewGroup.CurrentReviewStepId__c=nextRevStep.Id;
                        update reviewGroup;                        
                        Announcement__c announcement = [Select Id from Announcement__c where id =:reviewGroup.Announcement__c ];
                        announcement.CurrentReviewStep__c=nextRevStep.name;
                        update announcement;
                        for(ReviewStepApplication__c rsApp : rsaList) {
                             if(rsApp.Decision__c == 'Approved' && rsApp.IsOGMPromoted__c == false) {
                                ReviewStepApplication__c promotedApp = new ReviewStepApplication__c();
                                if(revStep.RecordType.Name == 'Application'){
                                    promotedApp.Application__c = rsApp.Application__c;   
                                    promotedApp.RecordTypeId=Schema.SobjectType.ReviewStepApplication__c.getRecordTypeInfosByName().get('Application').getRecordTypeId();
                                    promotedApp.MinimumAwardAmount__c=rsApp.MinimumAwardAmount__c;
                                    promotedApp.MaximumAwardAmount__c=rsApp.MaximumAwardAmount__c;
                                }
                                rsApp.IsAppPromoted__c = True;
                                promotedApp.ReviewStep__c = nextReviewStepId;
                                promotedApplications.add(promotedApp);    
                            }                        
                        }   
                    if(promotedApplications!=null && promotedApplications.size()>0)
                    insert promotedApplications;
                    update rsaList;   
                    revStep.OGMNotifiedOfRejections__c = true;
                    if(revStep.NoofApplicationsPending__c == 0){
                    revStep.Status__c='Completed';
                    }
                    update revStep;
                 }
             }catch(Exception e){
                resultMap.put('Message',e.getMessage()); Database.rollBack(sp);
            }
        }
          if(preventNotification == false && appsRejected == false) {
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-53478')));
      
        }   
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-78792')));
            PageReference  pageref = Page.ReviewStepView;
            pageref.getParameters().put('id',nextReviewStepId);
            pageref.setRedirect(true);
            return pageref; 
      

    }
}