UtahLiveDataTest/src/objects/Announcement__c.object
<CustomObject>
    <description>[Business] All the details for the Announcements are stored in this object ,It used two different recordTypes for Grantee and Grantor</description>
    <fields>
        <fullName>ApplicationDeadlineWithDateTime__c</fullName>
        <label>Application Deadline</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ExtensionDays__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Defines extension days for application deadline</description>
        <inlineHelpText>Defines extension days for application deadline</inlineHelpText>
        <label>ExtensionDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NumberOfApplications__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Applications</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PointofContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Key POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Announcement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A unique id to relate the announcement to the program.</description>
        <label>Program ID</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Opportunities</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>- In Progress - The information within the annoucement is incomplete. Such records shall not be avaiable for other users to view or edit.
- Review In Progress - Annoucements that are currently in the process of undergoing review shall have this status. Such records shall not be avaiable for other users to view or edit.
- Inactive - Approved annoucements whose Posting Date is in the future shall have this status. Such annoucements shall not be made available to recipient users.
- Active - Approved annoucements whose Posting Date is equal to the current date or is in the past and the Closing Date is in the future shall have this status. System shall make such annoucements available to recipients.
- Expired - Approved annoucements whose closing date is the current date or is in the past shall have this status. When an annoucement status changes from Active to Expired, it should no longer be made available to the recipient users.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Converted to Application</fullName>
                </value>
                <value>
                    <fullName>Converted to Pre-Application</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Approved</fullName>
                </value>
                <value>
                    <fullName>RFA Published</fullName>
                </value>
                <value>
                    <fullName>RFA Rejected</fullName>
                </value>
                <value>
                    <fullName>RFA Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TimeExtensionAllowed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Time Extension allowed for announcement to eligible applications?</description>
        <inlineHelpText>Is Time Extension allowed for announcement to eligible applications?</inlineHelpText>
        <label>Time Extension Allowed</label>
        <type>Checkbox</type>
    </fields>
    <label>Funding Opportunity</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AnnouncementFundingAccount__c.object
<CustomObject>
    <description>[Business]  Funding Accounts associated with the opportunity</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>Announcement</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Opportunity Funding Account</label>
    <nameField>
        <displayFormat>AFA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Opportunity Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Announcement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApplicationDeadlineWithDateTime__c</fullName>
        <description>This field is created because the current field is a Formula fild , Need to delete one of them later on</description>
        <label>Application Deadline</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The internal approver for the application</description>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applicationsap2u</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Review Initiated</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Submitted For Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Sent for Review</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision Completed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Rejection Initiated</fullName>
                </value>
                <value>
                    <fullName>Internally Reviewed</fullName>
                </value>
                <value>
                    <fullName>Converted to Award</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Converted to Grant</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Revision Initiated</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Approved Internally</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WaiveWithdraw__c</fullName>
        <label>WaiveWithdraw</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Waive</fullName>
                </value>
                <value>
                    <fullName>Withdraw</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ApplicationWaiver.cls
global class ApplicationWaiver extends GNT.ApprovalDecisionActionHandler {
    public class NotWaivedWithdrawnException extends Exception {}
    public class NullContactIdException extends Exception {}
    Map<String,Object> resultMap = new Map<String,Object>();
    PageReference pageRef = null;

    global override String execute(){
        Savepoint savestate = Database.setSavepoint();
            String actionType; //Application Waived or Withdrawn
            EmailTemplate templateEmail;
            system.debug('Connecting...!');
            if(selectedAction == 'Approve'){
            
            Id appId = selectedRecordId;
            system.debug('id is' +appId);
            
            try{

            Application__c app = [SELECT Id, Announcement__c, Announcement__r.Program__c, Announcement__r.Program__r.OwnerId, Status__c, WaiveWithdraw__c, Approver__c from Application__c where id = :appId Limit 1];
            //List<Announcement__c> ann = [Select NumberOfApplications__c, ApplicationDeadlineWithDateTime__c, ExtensionDays__c, TimeExtensionAllowed__c from Announcement__c where Id = :app.Announcement__c];   
            

            if (app.WaiveWithdraw__c  == 'Waive') {
                actionType = 'waived';
                templateEmail = [SELECT Id FROM EmailTemplate WHERE Name = 'Award ready for subrecipient approval' LIMIT 1]; //Email template is application waived template
                app.Status__c = 'Waived';
            }
            else 
            {
                throw new NotWaivedWithdrawnException('You cannot do this unless the application was waived. '); //This can be changed later if we want to add more functionality to it
            }

            ApplicationTriggerHelper.skipTrigger = true;
            update app;
            ApplicationTriggerHelper.skipTrigger = false;
            User programOwner = [SELECT Id, ContactId, Email FROM User WHERE Id=:app.Announcement__r.Program__r.OwnerId];
            System.debug('MANUALDEBUG >>> program owner = ' + programOwner);
            System.debug('MANUALDEBUG >>> program owner email = ' + programOwner.Email);


            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTemplateId(templateEmail.Id);
            if (programOwner.ContactId != null) {
                mail.setTargetObjectId(programOwner.ContactId);
            }
            else {
                mail.setTargetObjectId('00535000000XfXGAA0');
                //throw new NullContactIdException('The program owner does not have a contactId associated with them. Email cannot be sent.');
                System.debug('Email sent to user with contactId 00535000000XfXGAA0');
            }
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail}, false);
            
            List<Task> taskList = [Select Id, Status, WhatId from Task where WhatId = :app.Id AND OwnerId=:app.Approver__c AND Status='In Progress'];
            if(taskList != null && taskList.size()>0){
                for(Task task: taskList){
                    task.Status='Completed';
                }                   
                update taskList;
            }
           

           }
           catch(NotWaivedWithdrawnException e) {
            Database.rollback(savestate);
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.Severity.ERROR, ''+e);
            ApexPages.addMessage(errorMessage );
            return null;
        }
        //catch(NullContactIdException e) {
        //    Database.rollback(savestate);
        //    ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.Severity.ERROR, ''+e);
        //    ApexPages.addMessage(errorMessage );
        //    return null;
        //}
        catch(Exception e){
            Database.rollback(savestate);
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.Severity.ERROR, ''+e);
            ApexPages.addMessage(errorMessage );
            return null;
        }
        return ('Waiving Application');
            }
        return ('Waiving failed. Internal approval required.');
             
        }
}