UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>PreApplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre Application</label>
        <referenceTo>PreApplication__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Review Initiated</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Submitted For Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Sent for Review</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision Completed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Rejection Initiated</fullName>
                </value>
                <value>
                    <fullName>Internally Reviewed</fullName>
                </value>
                <value>
                    <fullName>Converted to Award</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Converted to Grant</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Revision Initiated</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Approved Internally</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FormBudgetInformation__c.object
<CustomObject>
    <description>[Business] This object is used for Budget Information forms.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Overflow Budget Information</label>
    <nameField>
        <displayFormat>BI-{00000}</displayFormat>
        <label>Budget Information</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Overflow Budget Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PreApplication__c.object
<CustomObject>
    <description>[Business] Pre-Application is a trimmed version of the Application with limited information</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Awarded</fullName>
                </value>
                <value>
                    <fullName>Not Awarded</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pre-Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pre-Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewGroup__c.object
<CustomObject>
    <description>[Business] This object summarizes number of Applications/Pre-Applications and number of Review Steps. As discussed with Shiva, Shah, Davinder , this object can not removed sometime later when possible.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Submit for Approve</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Review Group</label>
    <nameField>
        <displayFormat>RG-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Groups</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStep__c.object
<CustomObject>
    <description>[Business] Defines all the details of Review Step defined in the Review of Application/Pre-Application</description>
    <fields>
        <fullName>ApprovalEmailTemplate__c</fullName>
        <inlineHelpText>This field is used to store the developer name of the email template to notify the Applicant upon Approval/Promotion</inlineHelpText>
        <label>Approval Email Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastStep__c</fullName>
        <formula>If( ReviewGroup__r.NumberOfReviewSteps__c == StepNumber__c , true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Step</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReviewGroup__c</fullName>
        <label>Review Group</label>
        <referenceTo>ReviewGroup__c</referenceTo>
        <relationshipLabel>Review Steps</relationshipLabel>
        <relationshipName>Review_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReviewStepExpired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When the Today Date Exceeds End Date of the Review Step, A workflow rule triggers an update on this field to Checked</description>
        <inlineHelpText>When the Today Date Exceeds End Date of the Review Step, A workflow rule triggers an update on this field to Checked</inlineHelpText>
        <label>Review Step Expired ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StepNumber__c</fullName>
        <label>Step Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Review Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Steps</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStepApplication__c.object
<CustomObject>
    <description>[Business] Connects the Application/Pre-Application with the User and Review Step via this object</description>
    <fields>
        <fullName>ApplicantNotifiedOn__c</fullName>
        <inlineHelpText>When Applicant was notified by email upon Approval/Rejection?</inlineHelpText>
        <label>Applicant Notified On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ApplicantNotified__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When Applicant was notified by Email upon Approval/Rejection?</inlineHelpText>
        <label>Applicant Notified?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Review Step Applications</relationshipLabel>
        <relationshipName>Review_Step_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DecidedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Decided By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Review_Step_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DecidedOn__c</fullName>
        <inlineHelpText>When Approval/Rejection decision was made by the Chair/Review Step Owner?</inlineHelpText>
        <label>Decided On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Decision__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preapplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preapplication</label>
        <referenceTo>PreApplication__c</referenceTo>
        <relationshipLabel>Review Step Applications</relationshipLabel>
        <relationshipName>Review_Step_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewStep__c</fullName>
        <label>Review Step</label>
        <referenceTo>ReviewStep__c</referenceTo>
        <relationshipName>ReviewStepApplications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reviewers Not Assigned</fullName>
                    <default>true</default>
                    <label>Reviewers Not Assigned</label>
                </value>
                <value>
                    <fullName>Reviewers Assigned</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Reviews Complete</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Review Step Application</label>
    <nameField>
        <displayFormat>RSA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Step Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ReviewApplicationPromoteHelper.cls
global with sharing class ReviewApplicationPromoteHelper extends GNT.FlexTableActionHandler {
    
    public ReviewApplicationPromoteHelper (){}
    
    global override Map<String,Object> clickHandler(){
        
        Map<String,Object> resultMap = new Map<String,Object>(); 
                        system.debug('-inside clickHandler');
                        Savepoint sp = Database.setSavepoint();
        
        String ns = AppUtils.getNamespacePrefix(); 
        Id reviewStepId = urlParams.get('reviewStepId');
        String action = urlParams.get('action');
        
     //   List<Id> selectedRecords = new List<Id>();
        
        // GET THE CURRENT REVIEW STEP
        System.debug('revstepid '+reviewStepId);
        ReviewStep__c reviewStep = [Select Id,Name,StepNumber__c,ReviewGroup__c,LastStep__c,ReviewStepExpired__c,
                                    RecordType.Name, RecordType.DeveloperName 
                                    from ReviewStep__c where Id =: reviewStepId];
        
        
        /*if(reviewStep.RecordType.DeveloperName == 'Application'){
            selectedRecords = GNT.RecordIdStorageHelper.getRecordIds('RSApplicationSelectedForPromotion');
        }else{
            selectedRecords = GNT.RecordIdStorageHelper.getRecordIds('RSPreapplicationSelectedForPromotion');
        }*/
        Id targetObjectId ;
        Map<Id,Id> appOwnerIdToAppIdMap = new Map<Id,Id>();
        Id nextReviewStepId;
        Integer currentStep = Integer.valueOf(reviewStep.StepNumber__c);
        Integer nextStep = currentStep + 1;
        try{
            List<ReviewStep__c> nextReviewSteps = [SELECT Id,Name,ReviewGroup__c FROM ReviewStep__c 
                                                    WHERE StepNumber__c >=: nextStep 
                                                    AND ReviewGroup__c =: reviewStep.ReviewGroup__c 
                                                    Order by StepNumber__c LIMIT 1 ];
           
                                                    
            //CHECK IF THE NEXT STEP EXISTS                                     
            if(nextReviewSteps.size() > 0){
                
                Id reviewApplications;
                nextReviewStepId = nextReviewSteps.get(0).Id;
                //GET THE CURRENTLY SELECTED REVIEW STEP APPLICATIONS
                List<ReviewStepApplication__c> selectedReviewStepApps = [SELECT Id,Name,RecordType.Name,Decision__c, DecidedOn__c,
                                                                         application__r.OwnerId, preapplication__r.OwnerId,
                                                                         Application__c,PreApplication__c, ReviewStep__r.ApprovalEmailTemplate__c 
                                                                         FROM ReviewStepApplication__c 
                                                                         WHERE Id IN :selectedRecordIds
                                                                         LIMIT :GNT.AppUtils.SOQL_LIMIT]; // AND Status__c = 'Promoted'
                
                
                List<ReviewStepApplication__c> lstPromotedApps = new List<ReviewStepApplication__c>();
                
                if(nextReviewStepId != null && selectedReviewStepApps != null){
                    for(ReviewStepApplication__c app: selectedReviewStepApps) {
                        if(app.Decision__c != 'Promoted'){
                            ReviewStepApplication__c promotedApp = new ReviewStepApplication__c();
                            if(reviewStep.RecordType.Name == 'Application'){
                                promotedApp.Application__c = app.Application__c;   
                                promotedApp.RecordTypeId=Schema.SobjectType.ReviewStepApplication__c.getRecordTypeInfosByName().get('Application').getRecordTypeId();
                            }else{
                                promotedApp.PreApplication__c = app.PreApplication__c;
                                promotedApp.RecordTypeId=Schema.SobjectType.ReviewStepApplication__c.getRecordTypeInfosByName().get('Pre-Application').getRecordTypeId();
                            }
                            promotedApp.ReviewStep__c = nextReviewStepId;
                            lstPromotedApps.add(promotedApp);   
                            
                            app.Status__c = 'Approved';
                            app.Decision__c = 'Promoted';
                            app.DecidedOn__c = System.now();
                            app.DecidedBy__c = UserInfo.getUserId();
                        }
                        for(Id selectedId :selectedRecordIds){
                            if(selectedId == app.id){
                                if(app.RecordTypeId == Schema.SObjectType.ReviewStepApplication__c.getRecordTypeInfosByName().get('Application').getRecordTypeId()) {
                                    targetObjectId = app.application__r.OwnerId;
                                    appOwnerIdToAppIdMap.put(targetObjectId,app.Application__c);
                                }else{
                                    targetObjectId = app.preapplication__r.OwnerId;
                                    appOwnerIdToAppIdMap.put(targetObjectId,app.PreApplication__c);
                                }
                                app.ApplicantNotifiedOn__c = System.now();
                                app.ApplicantNotified__c = true;
                                
                                break;
                            }
                        }
                        lstPromotedApps.add(app);
                    }   
                }
                // update old RSA to Promoted and create new RSA for next Review Step
                if(lstPromotedApps.size()>0){
                    //upsert lstPromotedApps;
                    Database.UpsertResult[] results = Database.upsert(lstPromotedApps, false);
                    
                    if(reviewStep.RecordType.DeveloperName == 'Application'){
                        GNT.RecordIdStorageHelper.deleteRecordIds('RSApplicationSelectedForPromotion');
                    }else{
                        GNT.RecordIdStorageHelper.deleteRecordIds('RSPreapplicationSelectedForPromotion');
                    }
                    
                    String templateName = selectedReviewStepApps[0].ReviewStep__r.ApprovalEmailTemplate__c;
                    List<EmailTemplate> template = [SELECT id FROM EmailTemplate WHERE DeveloperName = :templateName LIMIT 1];
                    if( templateName !=null && template.size() > 0){
                        List<User> lstUser = [SELECT u.ContactId FROM User u WHERE u.Id IN :appOwnerIdToAppIdMap.keySet()];
                        Map<Id,Id> appIdToContIdMap = new Map<Id,Id>();
                        for(User u : lstUser){
                            appIdToContIdMap.put(appOwnerIdToAppIdMap.get(u.id),u.contactId);
                        }
                        GNT.AppUtils.sendEmailUsingTemplate(template[0].id,appIdToContIdMap,true); 
                    }
                }else{
                    ApexPages.Message myMsg;
                    if(reviewStep.RecordType.Name == 'Application'){
                        //myMsg = new ApexPages.Message(ApexPages.Severity.WARNING,'Please select atleast one application to promote.');
                        myMsg = new ApexPages.Message(ApexPages.Severity.WARNING,GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-74690'));
                    }else{
                        //myMsg = new ApexPages.Message(ApexPages.Severity.WARNING,'Please select atleast one pre-application to promote.');
                        myMsg = new ApexPages.Message(ApexPages.Severity.WARNING,GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-45294'));
                    }
                    ApexPages.addMessage(myMsg);
                    return null;
                }                 
            }else if(reviewStep.LastStep__c){            
               
                    approveAppOrPreApp(selectedRecordIds);
                
            }
        }catch(DMLException e) {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, e.getMessage());
            ApexPages.addMessage(myMsg);
            return null;
        }        
        String PageReferenceURL = '/apex/'+ns+'ReviewStepView?id=' + reviewStepId;
        resultMap.put('PageReference',PageReferenceURL);
        return resultMap;
    }
    
    private void approveAppOrPreApp(List<Id> selectedRecords){
        Id targetObjectId ;
        Map<Id,Id> appOwnerIdToAppIdMap = new Map<Id,Id>();
        system.debug('**selectedRecords**'+selectedRecords);
        
        List<ReviewStepApplication__c> selectedReviewStepApps = [SELECT Id,Name,RecordType.Name,Decision__c, DecidedOn__c,
                         application__r.OwnerId, preapplication__r.OwnerId, Application__c,PreApplication__c, PreApplication__r.status__c,
                         ReviewStep__r.ApprovalEmailTemplate__c 
                         FROM ReviewStepApplication__c 
                         WHERE Id IN :selectedRecords  
                         LIMIT :GNT.AppUtils.SOQL_LIMIT];
                         
        Set<Id> preAppIds = new Set<Id>();
        Set<Id> appIds = new Set<Id>();
        
        for(ReviewStepApplication__c rsa : selectedReviewStepApps){

            rsa.Status__c = 'Approved';
            rsa.Decision__c = 'Promoted';
            rsa.DecidedOn__c = System.now();
            for(Id selectedId : selectedRecordIds){
                
                
                if(selectedId == rsa.id){
                    if(rsa.RecordTypeId == Schema.SObjectType.ReviewStepApplication__c.getRecordTypeInfosByName().get('Application').getRecordTypeId()) {
                        targetObjectId = rsa.application__r.OwnerId;
                        appOwnerIdToAppIdMap.put(targetObjectId,rsa.Application__c);
                        
                        appIds.add(rsa.Application__c);
                    }else{
                        targetObjectId = rsa.preapplication__r.OwnerId;
                        appOwnerIdToAppIdMap.put(targetObjectId,rsa.PreApplication__c);
                        preAppIds.add(rsa.PreApplication__c);
                    }
                    rsa.ApplicantNotifiedOn__c = System.now();
                    rsa.ApplicantNotified__c = true;
                    
                    break;
                }
            }
        }
        
        
        

        if(preAppIds.size() > 0){
            List<PreApplication__c> preAppList = [select status__c from PreApplication__C where id in :preAppIds];
            
            for(PreApplication__c preApp :preAppList){
                preApp.status__c = 'Approved';
            }           
            update preAppList;
        }
        if(appIds.size() > 0){
            List<Application__c> appList = [select status__c from Application__C where id in :appIds];
            
            for(Application__c app :appList){
                app.status__c = 'Approved';
            }           
            update appList;
        }
        
        update selectedReviewStepApps;
        
        String templateName = selectedReviewStepApps[0].ReviewStep__r.ApprovalEmailTemplate__c;
        List<EmailTemplate> template = [SELECT id FROM EmailTemplate WHERE DeveloperName = :templateName LIMIT 1];
        if( templateName !=null && template.size() > 0){
            List<User> lstUser = [SELECT u.ContactId FROM User u WHERE u.Id IN :appOwnerIdToAppIdMap.keySet()];
            Map<Id,Id> appIdToContIdMap = new Map<Id,Id>();
            for(User u : lstUser){
                appIdToContIdMap.put(appOwnerIdToAppIdMap.get(u.id),u.contactId);
            }
            GNT.AppUtils.sendEmailUsingTemplate(template[0].id,appIdToContIdMap,true); 
        }
    }
}