UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>PreApplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre Application</label>
        <referenceTo>PreApplication__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Review Initiated</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Submitted For Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Sent for Review</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision Completed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Rejection Initiated</fullName>
                </value>
                <value>
                    <fullName>Internally Reviewed</fullName>
                </value>
                <value>
                    <fullName>Converted to Award</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Converted to Grant</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Revision Initiated</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Approved Internally</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The grantee entered title for the application.</description>
        <label>Project Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FormBudgetInformation__c.object
<CustomObject>
    <description>[Business] This object is used for Budget Information forms.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Overflow Budget Information</label>
    <nameField>
        <displayFormat>BI-{00000}</displayFormat>
        <label>Budget Information</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Overflow Budget Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PanelApplication__c.object
<CustomObject>
    <description>[Business] Defines a review Panel for an Application /Pre-Application</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Panel Applications</relationshipLabel>
        <relationshipName>Panel_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreApplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Application</label>
        <referenceTo>PreApplication__c</referenceTo>
        <relationshipLabel>Panel Applications</relationshipLabel>
        <relationshipName>Panel_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewPanel__c</fullName>
        <label>Review Panel</label>
        <referenceTo>ReviewPanel__c</referenceTo>
        <relationshipLabel>Panel Applications</relationshipLabel>
        <relationshipName>Panel_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Added to Step</fullName>
                    <default>true</default>
                    <label>Added to Step</label>
                </value>
                <value>
                    <fullName>Reviewers Assigned</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Reviews Complete</fullName>
                </value>
                <value>
                    <fullName>Promoted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Panel Application</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Panel Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panel Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PanelUser__c.object
<CustomObject>
    <description>[Business]  Association of a User to a Review panel</description>
    <fields>
        <fullName>ReviewPanel__c</fullName>
        <label>Review Panel</label>
        <referenceTo>ReviewPanel__c</referenceTo>
        <relationshipName>Review_Panel_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Review_Panel_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Panel User</label>
    <nameField>
        <displayFormat>PU-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panel Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PreApplication__c.object
<CustomObject>
    <description>[Business] Pre-Application is a trimmed version of the Application with limited information</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Awarded</fullName>
                </value>
                <value>
                    <fullName>Not Awarded</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The grantee entered title for the application.</description>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pre-Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pre-Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Review__c.object
<CustomObject>
    <description>[Business] Defines the Review object (Need more Details / Need to revisit for the Description)</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PanelApplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Panel Application</label>
        <referenceTo>PanelApplication__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PanelUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Panel User</label>
        <referenceTo>PanelUser__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreApplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Application</label>
        <referenceTo>PreApplication__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewPanel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review Panel</label>
        <referenceTo>ReviewPanel__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewer(Obsolete)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Sent for Review</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Review Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewPanel__c.object
<CustomObject>
    <description>[Business] Defines the Review Panel to review the Applications</description>
    <fields>
        <fullName>DueDateOffset__c</fullName>
        <inlineHelpText>Offset is used to decide the due date when the Task Due Date is selected as Today + Offset</inlineHelpText>
        <label>Due Date Offset</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>Review Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ReviewerAssignNotificationTemplate__c</fullName>
        <inlineHelpText>This email template is used to send email notification to the reviewer to review the Application or PreApplication</inlineHelpText>
        <label>Reviewer Assign Notification Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaskDueDate__c</fullName>
        <inlineHelpText>Specify due date for the review tasks created under this review panel</inlineHelpText>
        <label>Task Due Date</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Panel End Date</fullName>
                    <default>true</default>
                    <label>Panel End Date</label>
                </value>
                <value>
                    <fullName>Today + Offset Days</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Review Panel</label>
    <nameField>
        <displayFormat>Panel-{000}</displayFormat>
        <label>Review Panel ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Panels</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/AssignPanelAppAndNotifyReviewersHelper.cls
global with sharing class AssignPanelAppAndNotifyReviewersHelper extends GNT.FlexTableActionHandler {
    
    global override Map<String,Object> clickHandler(){
        Map<String,Object> resultMap = new Map<String,Object>();        
        if(selectedRecordIds != null && selectedRecordIds.size() > 0){            
            String ns = AppUtils.getNamespacePrefix(); 
            Id panelId = urlParams.get('panelId');
            String tabName = urlParams.get('tabName');
            Id panelAppId = urlParams.get('id');
                        
            try{
                ReviewPanel__c reviewPanel = [SELECT Id, RecordTypeId, ReviewerAssignNotificationTemplate__c,
                        EndDate__c, TaskDueDate__c, DueDateOffset__c FROM ReviewPanel__c WHERE Id=:panelId];
                PanelApplication__c panelApp = [Select Id, Application__c, PreApplication__c From PanelApplication__c Where Id = :panelAppId];
                
                Id rpAppRecTypeId = Schema.SObjectType.ReviewPanel__c.getRecordTypeInfosByName().get('Application').getRecordTypeId();
                Id rpPreAppRecTypeId = Schema.SObjectType.ReviewPanel__c.getRecordTypeInfosByName().get('Pre-Application').getRecordTypeId();
                
                List<PanelUser__c> panelUserList = [Select id, Reviewer__c From PanelUser__c Where Id IN : selectedRecordIds];
                
                Map<Id, Id> pUserToUserIdMap = new Map<Id, Id>();
                for(PanelUser__c puser : panelUserList){
                    pUserToUserIdMap.put(puser.Id, puser.Reviewer__c);
                }
                
                Date dueDate;
                if(!String.isEmpty(reviewPanel.TaskDueDate__c) && reviewPanel.TaskDueDate__c == 'Today + Offset Days'){
                    if(reviewPanel.DueDateOffset__c != null){
                        dueDate = Date.today();
                        dueDate = dueDate.addDays(Integer.valueOf(reviewPanel.DueDateOffset__c));
                    }
                }else{
                    if(reviewPanel.EndDate__c != null){
                        dueDate = reviewPanel.EndDate__c;
                    }
                }
                
                List<Review__c> reviewsList = new List<Review__c>();
                for(String selectedId : selectedRecordIds){
                    Review__c review = new Review__c();
                    if(reviewPanel.RecordTypeId == rpAppRecTypeId){
                        review.Application__c = panelApp.Application__c;
                    }else{
                        review.PreApplication__c = panelApp.PreApplication__c;
                    }
                    review.PanelApplication__c = panelApp.Id;
                    review.PanelUser__c = selectedId;            
                    review.ReviewPanel__c = panelId;
                    reviewsList.add(review);
                }
                                                
                if(Schema.sObjectType.Review__c.isCreateable()){
                    Database.saveResult [] saveResult = Database.insert(reviewsList, true);
                    List<Id> reviewIds = new List<Id>();
                    for (Database.SaveResult sr : saveResult ) {
                        reviewIds.add(sr.getId());
                    }
                    
                    Map<Id,Id> targetObjIdToWhatIdMap = new Map<Id,Id>();
                
                    if(reviewIds.size() > 0){
                        Map<Id,Review__c> reviewsMap = new Map<Id,Review__c>([SELECT Id,Name,Status__c,Application__c,PreApplication__c ,
                                                                      Application__r.Title__c,PreApplication__r.Title__c,
                                                                      Application__r.OwnerId,PreApplication__r.OwnerId, OwnerId
                                                                      FROM Review__c WHERE Id IN :reviewIds]);
                
                        List<Review__c> reviewsToBeUpdatedList = new List<Review__c>();
                        List<Task> taskList = new List<Task>();
                        Map<Id, List<Sobject>> srcIdToTargetSobjectsMap = new Map<Id, List<Sobject>>();
                        for(Review__c review : reviewsMap.values()){
                            review.Status__c = 'Sent for Review';
                            reviewsToBeUpdatedList.add(review);
                            //Create a Task for the Reviewer of the Application
                            Task taskInstance = new Task();                            
                            if(review.Application__c != null){                                
                                //taskInstance = GNT.TaskCreationHandler.createTasks(review.OwnerId, review.Id , 'Review Application', review.Application__r.Title__c, null, false, dueDate, 'Review', false).get(0);
                                taskInstance = GNT.TaskCreationHandler.createTasks(review.OwnerId, review.Id , 'Review Application', review.Application__r.Title__c, null, false, dueDate, 'Review', review.Name, false).get(0);
                            }else{                                
                                //taskInstance = GNT.TaskCreationHandler.createTasks(review.OwnerId, review.Id , 'Review Pre-Application', review.PreApplication__r.Title__c, null, false, dueDate, 'Review', false).get(0);
                                taskInstance = GNT.TaskCreationHandler.createTasks(review.OwnerId, review.Id , 'Review Pre-Application', review.PreApplication__r.Title__c, null, false, dueDate, 'Review', review.Name, false).get(0);
                            }
                            targetObjIdToWhatIdMap.put(review.OwnerId, review.Id);                            
                            List<Task> tasks = srcIdToTargetSobjectsMap.get(review.id);
                            if(tasks == null){
                                tasks = new List<Task>(); 
                            }
                            if(taskInstance != null){
                                tasks.add(taskInstance);
                            }
                            srcIdToTargetSobjectsMap.put(review.id ,tasks);    
                        }
                        taskList = GNT.AppUtils.copyRecords(AppUtils.getNamespacePrefix()+'Review__c','Task',srcIdToTargetSobjectsMap,false);                        
                        
                        if(Schema.sObjectType.Review__c.isUpdateable()){
                            update reviewsToBeUpdatedList ;
                            insert taskList;
                            
                            String templateName = reviewPanel.ReviewerAssignNotificationTemplate__c;
                            if(!String.isEmpty(templateName)){
                                List<EmailTemplate> template = [SELECT id, Body FROM EmailTemplate WHERE DeveloperName = :templateName LIMIT 1];
                                if(template.size() > 0){
                                    
                                    List<User> userList = [SELECT u.Email FROM User u WHERE u.Id IN :targetObjIdToWhatIdMap.keySet()];
                                    Map<Id, String[]> userIdToAddress = new Map<Id, String[]>();
                                    for(User userObj : userList){
                                        String[] toAddressTemp = userIdToAddress.get(userObj.Id);
                                        if(toAddressTemp == null){
                                            toAddressTemp = new String[] {};
                                        }
                                        toAddressTemp.add(userObj.Email);
                                        userIdToAddress.put(userObj.Id, toAddressTemp);
                                    }
                                    
                                    Map<Id, String[]> recIdToAddressMap = new Map<Id, String[]> ();
                                    
                                    for(Id userId : userIdToAddress.keySet()){
                                        Id reviewId = targetObjIdToWhatIdMap.get(userId);
                                        recIdToAddressMap.put(reviewId, userIdToAddress.get(userId));
                                    }
                                    
                                    Contact cont = [select id, Email from Contact where email <> null limit 1];
                                    
                                    AppUtils.sendEmailUsingTemplate(template[0].Id, recIdToAddressMap, cont.Id, false);
                                    // resultMap.put('Message','Applications are sent for review');
                                    resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-42215'));
                                }
                            }
                        }
                    }
                }
            }catch(Exception e){
                throw new GNT.AppUtils.ValidationException(e.getMessage());
            }
            String PageReferenceURL = '/apex/'+ns+'ReviewPanelView?id=' + panelId;
            if(!String.isEmpty(tabName)){
                PageReferenceURL+='&tabName='+tabName;
            }
            resultMap.put('PageReference',PageReferenceURL);
            return resultMap;
        }else{
            //throw new GNT.AppUtils.ValidationException('Please select one or more records');
             throw new GNT.AppUtils.ValidationException(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-85230'));
        }
        return null;
    }
}