UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Review Initiated</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Submitted For Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Sent for Review</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision Completed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Rejection Initiated</fullName>
                </value>
                <value>
                    <fullName>Internally Reviewed</fullName>
                </value>
                <value>
                    <fullName>Converted to Award</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Converted to Grant</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Revision Initiated</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Approved Internally</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent to Grantee Review</fullName>
                </value>
                <value>
                    <fullName>Grantee Accepted</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>FINOPS Completed</fullName>
                </value>
                <value>
                    <fullName>Sent to FINOPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ChangeRequest__c.object
<CustomObject>
    <description>[Business]  Currently used to track pre-award negotiation requests for application only. In the future this can be enhanced for other objects like award or something else.</description>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Negotiation Requests</relationshipLabel>
        <relationshipName>Change_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                    <default>true</default>
                    <label>Not Initiated</label>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Negotiation Request</label>
    <nameField>
        <displayFormat>CR-{000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Negotiation Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed/Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PanelApplication__c.object
<CustomObject>
    <description>[Business] Defines a review Panel for an Application /Pre-Application</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Panel Applications</relationshipLabel>
        <relationshipName>Panel_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewPanel__c</fullName>
        <label>Review Panel</label>
        <referenceTo>ReviewPanel__c</referenceTo>
        <relationshipLabel>Panel Applications</relationshipLabel>
        <relationshipName>Panel_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Added to Step</fullName>
                    <default>true</default>
                    <label>Added to Step</label>
                </value>
                <value>
                    <fullName>Reviewers Assigned</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Reviews Complete</fullName>
                </value>
                <value>
                    <fullName>Promoted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Panel Application</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Panel Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panel Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PanelUser__c.object
<CustomObject>
    <description>[Business]  Association of a User to a Review panel</description>
    <fields>
        <fullName>ReviewPanel__c</fullName>
        <label>Review Panel</label>
        <referenceTo>ReviewPanel__c</referenceTo>
        <relationshipName>Review_Panel_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Panel User</label>
    <nameField>
        <displayFormat>PU-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panel Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Review__c.object
<CustomObject>
    <description>[Business] Defines the Review object (Need more Details / Need to revisit for the Description)</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChangeRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Negotiation Request</label>
        <referenceTo>ChangeRequest__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PanelApplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Panel Application</label>
        <referenceTo>PanelApplication__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PanelUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Panel User</label>
        <referenceTo>PanelUser__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewPanel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review Panel</label>
        <referenceTo>ReviewPanel__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewer(Obsolete)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Sent for Review</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Review Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStepApplication__c.object
<CustomObject>
    <description>[Business] Connects the Application/Pre-Application with the User and Review Step via this object</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Review Step Applications</relationshipLabel>
        <relationshipName>Review_Step_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review Step Application</label>
    <nameField>
        <displayFormat>RSA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Step Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/USBEAmendApplicationInReviewHelper.cls
//Reset Helper
global with sharing class USBEAmendApplicationInReviewHelper {
    global static void process(Set<Id> appIdSet){

        Map<String, Set<Id>> appIdMap = resolveApplicationIds(appIdSet);

        /*
        List<ChangeRequest__c> changeReqList = new List<ChangeRequest__c>([SELECT Id, Name FROM ChangeRequest__c WHERE Application__c IN :appIdSet]);
        delete changeReqList;
        */
        List<PanelApplication__c> panelAppList = new List<PanelApplication__c>([SELECT Id, Name, (SELECT Id, ReviewPanel__c, PanelUser__c FROM Reviews__r WHERE Status__c != 'Assigned') FROM PanelApplication__c WHERE Application__c IN :appIdMap.get('noAwardAppIdSet')]);
        Map<Id, Integer> panelUserIdCountMap = new Map<Id, Integer>();
        for(PanelApplication__c panelApp : panelAppList){
            for(Review__c review : panelApp.Reviews__r){
                if(!panelUserIdCountMap.containsKey(review.PanelUser__c)){
                    panelUserIdCountMap.put(review.PanelUser__c, 0);
                }
                panelUserIdCountMap.put(review.PanelUser__c, panelUserIdCountMap.get(review.PanelUser__c) + 1);
            }
        }

        List<PanelUser__c> panelUserList = [SELECT Id, NoOfApplicationsAssigned__c FROM PanelUser__c WHERE Id IN :panelUserIdCountMap.keySet()];
        for(PanelUser__c panelUser : panelUserList){
            panelUser.NoOfApplicationsAssigned__c = (panelUser.NoOfApplicationsAssigned__c == null ? 0 : panelUser.NoOfApplicationsAssigned__c) - panelUserIdCountMap.get(panelUser.Id);
        }
        update panelUserList;

        delete panelAppList;

        List<ReviewStepApplication__c> rsaList = new List<ReviewStepApplication__c>([SELECT Id, Name FROM ReviewStepApplication__c WHERE Application__c IN :appIdMap.get('noAwardAppIdSet')]);
        delete rsaList;

        List<Application__c> appNeedUpdate = new List<Application__c>([SELECT Id, Name, Status__c, AwardDecisionStatus__c, ChangeRequestStatus__c, 
                                                                            FinalApproverComments__c, FinalGrantAmountNegotiated__c, LastReviewDecision__c, 
                                                                            LastReviewStep__c, MgmtRecAmount__c, ObligatedAmount__c, OwnerId 
                                                                            FROM Application__c WHERE Id IN :appIdMap.get('noAwardAppIdSet')]);
        
        for(Application__c app : appNeedUpdate){
            app.Status__c = 'Created';
            app.AwardDecisionStatus__c = null;
            app.ChangeRequestStatus__c = null;
            app.FinalApproverComments__c = null;
            app.FinalGrantAmountNegotiated__c = null;
            app.LastReviewDecision__c = null;
            app.LastReviewStep__c = null;
            app.MgmtRecAmount__c = 0;
            app.ObligatedAmount__c = 0;
        }
        
         ApplicationTriggerHelperUSBE.skipTrigger = true;
        update appNeedUpdate;
        ApplicationTriggerHelperUSBE.skipTrigger = false;
        
        /*
        List<Task> appTaskList = new List<Task>();
        for(Application__c app : appNeedUpdate){
            appTaskList.add(GNT.TaskCreationHandler.createTasks(app.OwnerId,
                app.Id,'Modify Application',
                'Modify Application ' + app.Name, null, false, null,
                'Review', 'Modify Application ' + app.Name, false
            )[0]);
        }

        insert appTaskList;
        */
        List<GNT.TaskCreationHandler.TaskBulkClass> tasksList = new List<GNT.TaskCreationHandler.TaskBulkClass>();
        for(Application__c app : appNeedUpdate){
            if(app.OwnerId.getSObjectType() == User.SObjectType) {
                GNT.TaskCreationHandler.TaskBulkClass task = new GNT.TaskCreationHandler.TaskBulkClass();
                task.ownerUserId = app.OwnerId;
                task.recordId = app.Id;
                task.action = 'Modify Application';
                task.recordName = app.Name;
                task.subject = 'Modify Application ' + app.Name;
                tasksList.add(task);
            }
        }
        List<Task> insertedTaskList = GNT.TaskCreationHandler.createBulkTasks(tasksList, true);         
        
        List<GNT.EmailFeeder> emails = new List<GNT.EmailFeeder>();
        for(Application__c app : appNeedUpdate){
            emails.add(new GNT.EmailFeeder().contextRecordId(app.Id).subject('test').plainTextBody('test').TargetObjectId(app.OwnerId));
        }

        GNT.EmailFeeder.SendEmails(emails);
        

    }

    global static Map<String, Set<Id>> resolveApplicationIds(Set<Id> appIdSet){
        List<Award__c> awardList = new List<Award__c>([SELECT Id, Name, Application__c FROM Award__c WHERE Application__c IN :appIdSet]);
        Set<Id> awardAppIdSet = new Set<Id>();
        Set<Id> noAwardAppIdSet = new Set<Id>();

        for(Award__c award : awardList){
            if(!awardAppIdSet.contains(award.Application__c)){
                awardAppIdSet.add(award.Application__c);
            }
        }
        for(Id appId : appIdSet){
            if(!awardAppIdSet.contains(appId)){
                noAwardAppIdSet.add(appId);
            }
        }

        Map<String, Set<Id>> result = new Map<String, Set<Id>>();
        result.put('awardAppIdSet', awardAppIdSet);
        result.put('noAwardAppIdSet', noAwardAppIdSet);
        return result;
    }
    
    global static void updateAwardAllocatedAmounts (Map<Id, Decimal> applications){
        //Get Awards that are active, are in active grants, and are for the applications passed to it (thus of the correct type for USBE) 
        List<Award__c> awards = new List<Award__c>([
            SELECT Id, Name, Application__c, Status__c, AllocatedAmount__c, Grant__c, Grant__r.Status__c 
            FROM Award__c 
            WHERE Application__c IN: applications.keySet() AND Status__c = 'Activated']);
        //Set active Award allocated amounts from appIdMapAllocation
        List<Award__c> results = new List<Award__c>();
        for(Award__c award : awards) {
            //Doublecheck the applications passed and if the allocations actually changed
            if (applications.containsKey(award.Application__c) && award.AllocatedAmount__c != applications.get(award.Application__c)) {
                award.AllocatedAmount__c = applications.get(award.Application__c); 
                results.add(award);
            }
        }
        if (results.size() > 0) {
            update results;
        }   
    }
    
}