UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>RequestedAmount__c</fullName>
        <description>Roll up Summary of all the Application Budget Categories</description>
        <label>Requested Amount</label>
        <summarizedField>ApplicationBudgetCategory2__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>ApplicationBudgetCategory2__c.IsFirstBudgetPeriodRelated__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>ApplicationBudgetCategory2__c.Application__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ApplicationBudgetCategory2__c.object
<CustomObject>
    <description>[Business] Stores the Budget related information associated with an Application</description>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application_Budget_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BudgetCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Category</label>
        <referenceTo>BudgetCategory__c</referenceTo>
        <relationshipName>Application_Budget_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestedAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Requested Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ServiceArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Area</label>
        <referenceTo>ApplicationServiceArea__c</referenceTo>
        <relationshipName>Application_Budget_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Budget Category</label>
    <nameField>
        <displayFormat>AC-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Budget Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ApplicationServiceArea__c.object
<CustomObject>
    <description>[Business] Associates a Service area with an Application</description>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application_Service_Areas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RequestedAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Requested Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ServiceArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity Project Area</label>
        <referenceTo>AnnouncementServiceArea__c</referenceTo>
        <relationshipLabel>Application Project Areas</relationshipLabel>
        <relationshipName>Application_Service_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Project Area</label>
    <nameField>
        <displayFormat>ASA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Project Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BudgetCategory__c.object
<CustomObject>
    <description>[Business] This object stores the Master List of all the Budget categories</description>
    <label>MST: Budget Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Category</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ServiceArea__c.object
<CustomObject>
    <description>[Business] Master list of all the Service Area information is stored in this object , Service areas are also applicable to the Announcements ,Programs,Application via Junction objects</description>
    <label>Project/Service Area</label>
    <nameField>
        <displayFormat>PSA-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ApplicationServiceAreaTriggerHelper.cls
global with sharing class ApplicationServiceAreaTriggerHelper extends GNT.TriggerHelper {
    global override void processAfterInsert() {
    //    addBudgetCategories(Trigger.new);
    }
    global override void processAfterDelete() {
        deleteBudgetCategories(Trigger.oldMap.keySet());
    }
    // commented out because method is not used in the processAfterInsert at the time of changes(6/16/17)-Charan
    /*private static void addBudgetCategories(List<ApplicationServiceArea__c> asas) {
        List<ApplicationBudgetCategory2__c> abcs = new List<ApplicationBudgetCategory2__c>();
        ApplicationBudgetCategory2__c abc;
        List<BudgetCategory__c> bcs = [SELECT Id FROM BudgetCategory__c];
        for(ApplicationServiceArea__c asa: asas) {
            for(BudgetCategory__c bc: bcs) {
                abc = new ApplicationBudgetCategory2__c();
                abc.ServiceArea__c = asa.Id;
                abc.BudgetCategory__c = bc.Id;
                abc.Application__c = asa.Application__c;
                abc.RequestedAmount__c = 0;
                abcs.add(abc);
            }
        }
        if(abcs.size() > 0) {
            insert abcs;
        }
    }
*/    private static void deleteBudgetCategories(Set<Id> asas) {
        List<ApplicationBudgetCategory2__c> abcs = [SELECT Id FROM ApplicationBudgetCategory2__c WHERE ServiceArea__c IN: asas];
        delete abcs;
    }
}