UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ChangeRequest__c.object
<CustomObject>
    <description>[Business]  Currently used to track pre-award negotiation requests for application only. In the future this can be enhanced for other objects like award or something else.</description>
    <fields>
        <fullName>ApplicantComments__c</fullName>
        <description>Comments by the Applicant</description>
        <label>Applicant Comments</label>
        <length>130000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Negotiation Requests</relationshipLabel>
        <relationshipName>Change_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Negotiation Request</label>
    <nameField>
        <displayFormat>CR-{000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Negotiation Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FormBudgetInformation__c.object
<CustomObject>
    <description>[Business] This object is used for Budget Information forms.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Overflow Budget Information</label>
    <nameField>
        <displayFormat>BI-{00000}</displayFormat>
        <label>Budget Information</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Overflow Budget Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ApplicantSRComments.cls
public with sharing class ApplicantSRComments {


    public String comments{get;set;}
    public string namespace {get;set;}
    public List<ChangeRequest__c> changeReqList ;
    public ChangeRequest__c changeReq;
    public Id crId;
    public Id appId;
    public String page{get;set;}
    
    public ApplicantSRComments() {
        namespace = AppUtils.getNamespacePrefix();
        crId = ApexPages.currentPage().getParameters().get('id');
        changeReqList = [Select Id, Application__r.Id, ApplicantComments__c from ChangeRequest__c where id=:crId Limit 1];
        changeReq = changeReqList[0];
        appId = changeReq.Application__r.Id;
    }

    public PageReference save(){
        
        changeReq.ApplicantComments__c = comments;
        update changeReq;
        page='/apex/'+namespace+'ApplicationView?id='+appId;
        return null;
        //return new PageReference('/apex/'+namespace+'ApplicationView?id='+appId);
    } 

}