UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>AllocatedAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>AllocatedAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalGrantAwardAmount__c</fullName>
        <formula>PriorAwardedAmount__c +   AwardedAmountthisAction__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Awarded Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Stores the award amendment</description>
        <formula>if (AmendmentSequence__c==0,&apos;NEW&apos;,&apos;Amendment&apos;+TEXT(AmendmentSequence__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>YTDReimbursementPaid__c</fullName>
        <label>YTD Reimbursement Paid</label>
        <summarizedField>AwardBudgetCategory__c.TotalYTDReimbursementPaid__c</summarizedField>
        <summaryForeignKey>AwardBudgetCategory__c.Award__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Form__c.object
<CustomObject>
    <description>[Business] object represents forms on grants.gov1</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GoalObjectiveIndicator__c</fullName>
        <label>Goal Objective Indicator</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other__c</fullName>
        <description>This field is used in Application for Federal Assistance form as Other, SF-424 RR Multi-Project Cover form.</description>
        <label>Other</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Application Detail (FORMS)</label>
    <nameField>
        <displayFormat>FN-{00000}</displayFormat>
        <label>Form</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/GoalObjective__c.object
<CustomObject>
    <description>Goals and Objectives object for Performance management</description>
    <fields>
        <fullName>AchievedQComments__c</fullName>
        <label>AchievedQComments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>AchievedQ__c</fullName>
        <label>AchievedQ</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ActivitiesAndMethods__c</fullName>
        <label>ACTIVITIES AND METHODS</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>AllocatedAmount__c</fullName>
        <description>Allocated Amount for Goal/Objective</description>
        <label>Allocated Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Allocated %</description>
        <label>Allocated %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Goals Objectives</relationshipLabel>
        <relationshipName>Goals_Objectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AwardQ1Comments__c</fullName>
        <label>AwardQ1Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AwardQ1__c</fullName>
        <description>This is entered in award phase</description>
        <label>AwardQ1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AwardQ2Comments__c</fullName>
        <label>AwardQ2Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AwardQ2__c</fullName>
        <label>AwardQ2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AwardQ3Comments__c</fullName>
        <label>AwardQ3Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AwardQ3__c</fullName>
        <label>AwardQ3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AwardQ4Comments__c</fullName>
        <label>AwardQ4Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AwardQ4__c</fullName>
        <label>AwardQ4</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AwardTotalQuantitative__c</fullName>
        <formula>AwardQ1__c+AwardQ2__c+AwardQ3__c+AwardQ4__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AwardTotalQuantitative</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Award to which the Goal is associated</description>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Goals_and_Objectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CombineTextQuestions__c</fullName>
        <label>CombineTextQuestions</label>
        <length>131000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description for Goals and Objectives</description>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ExpenditureAmount__c</fullName>
        <label>Expenditure Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Detail (FORMS)</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Goals Objectives</relationshipLabel>
        <relationshipName>Goals_Objectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsParent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this Goal a Parent ?</description>
        <inlineHelpText>Is this Goal a Parent ?</inlineHelpText>
        <label>Is Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MeasureEffectiveness__c</fullName>
        <label>Measure Effectiveness</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Other__c</fullName>
        <label>Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentGoal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Goal and Objective Object. This acts as a self lookup.</description>
        <inlineHelpText>Lookup to Goal and Objective Object. This acts as a self lookup.</inlineHelpText>
        <label>Parent Goal</label>
        <referenceTo>GoalObjective__c</referenceTo>
        <relationshipLabel>Goals Objectives</relationshipLabel>
        <relationshipName>Goals_and_Objectives2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Goals Objectives</relationshipLabel>
        <relationshipName>Goals_Objectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Q1__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Q1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q2__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Q2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q3__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Q3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q4__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Q4</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuantitativeNumberMeasures__c</fullName>
        <label>Quantitative number measures</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Number of trainings provided</fullName>
                </value>
                <value>
                    <fullName>Number of people trained</fullName>
                </value>
                <value>
                    <fullName>Number of victims served</fullName>
                </value>
                <value>
                    <fullName>Meetings</fullName>
                </value>
                <value>
                    <fullName>Brochures</fullName>
                </value>
                <value>
                    <fullName>Manuals</fullName>
                </value>
                <value>
                    <fullName>Training curricula</fullName>
                </value>
                <value>
                    <fullName>Training materials</fullName>
                </value>
                <value>
                    <fullName>Evaluations</fullName>
                </value>
                <value>
                    <fullName>Interpreters</fullName>
                </value>
                <value>
                    <fullName>Safety audits</fullName>
                </value>
                <value>
                    <fullName>Security personnel or equipment</fullName>
                </value>
                <value>
                    <fullName>Victim services provided</fullName>
                </value>
                <value>
                    <fullName>Law enforcement services provided</fullName>
                </value>
                <value>
                    <fullName>Prosecution victim services provided</fullName>
                </value>
                <value>
                    <fullName>Court services provided</fullName>
                </value>
                <value>
                    <fullName>Probation &amp; Parole (offender accountability) Services provided</fullName>
                </value>
                <value>
                    <fullName>Batterer Intervention Services provided</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TargetedQ__c</fullName>
        <description>populated in goaltriggerhelper</description>
        <label>TargetedQ</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>if(IsParent__c==false,&apos;Objective&apos;,&apos;Goal&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Goal Objective</label>
    <nameField>
        <displayFormat>GOB-{0000}</displayFormat>
        <label>Goals and Objectives Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals Objectives</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <recordTypes>
        <fullName>Award</fullName>
        <active>true</active>
        <description>Award RecordType for Goal and Objective</description>
        <label>Award</label>
    </recordTypes>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <description>Program RecordType for Goal and Objective</description>
        <label>Program</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/GoalObjectiveTriggerHelper.cls
/*
    This class has methods to execute methods related to Goal Objective Trigger
    **********************************************************
    Audit History
    **********************************************************
    10-05-2016             Davinder Singh     Created 
    **********************************************************  
*/

public class GoalObjectiveTriggerHelper extends GNT.TriggerHelper{
    
    public static boolean skipTrigger = false;  

    public override void processBeforeInsert() {
        if(skipTrigger==false){                
           updateRecord(trigger.new);                 
        }
    }

    public override void processAfterInsert() {
        if(skipTrigger==false){                
           validateAllocation(trigger.new);      
           populateGoalObjectiveData(trigger.new);
           updateGoalObjectiveIndicator(trigger.new);
        }
    }
    
    public override void processAfterUpdate() {
        if(skipTrigger==false){       
           validateAllocation(trigger.new);               
           populateGoalObjectiveData(trigger.new);
        }
    }

    public override void processBeforeUpdate() {
        if(skipTrigger==false){
          for(GoalObjective__c goal : (List<GoalObjective__c>)Trigger.new){
            if(goal.AwardQ1__c!=null && goal.AwardQ1Comments__c == null){
              goal.addError('Please add comments for Achieved Q1');
            }else if(goal.AwardQ2__c!=null && goal.AwardQ2Comments__c == null){
              goal.addError('Please add comments for Achieved Q2');
            }else if(goal.AwardQ3__c!=null && goal.AwardQ3Comments__c == null){
              goal.addError('Please add comments for Achieved Q3');
            }else if(goal.AwardQ4__c!=null && goal.AwardQ4Comments__c == null){
              goal.addError('Please add comments for Achieved Q4');
            }
          }
        }
    }

    public override void processBeforeDelete() {
        if(skipTrigger==false){       
           deleteObjectives(trigger.old);                          
        }
    }

    public override void processAfterDelete() {
        if(skipTrigger==false){       
           updateGoalObjectiveIndicator(trigger.old);                          
        }
    }
    
    // Based on the Allocation % , allocation $ is calculated and updated in Record
    // This applies only for Grant/Award Record
    private void populateGoalObjectiveData(List<GoalObjective__c> termConditionList){
        List<Id> goalIds = new List<Id>();
        List<GoalObjective__c> tConditionList = new List<GoalObjective__c>();
        Boolean isObjectiveFlag=false;
        for(GoalObjective__c tc : termConditionList) {
         if(tc.recordtypeId==Schema.SObjectType.GoalObjective__c.getRecordTypeInfosByName().get('Program').getRecordTypeId())
         return;
         else{ 
          goalIds.add(tc.Id);
          isObjectiveFlag=tc.isParent__c==true?false:true;            
          }
        } 
        
        if(isObjectiveFlag){
          //tConditionList = [select Id, Award__r.YTDReimbursementPaid__c, Allocated__c,type__c,Award__r.TotalGrantAwardAmount__c, ParentGoal__r.Award__r.TotalGrantAwardAmount__c,ParentGoal__r.ExpenditureAmount__c,ParentGoal__r.AllocatedAmount__c FROM GoalObjective__c where ID in : goalIds];
          tConditionList = [select Id, Award__r.YTDReimbursementPaid__c, Allocated__c,type__c,Award__r.TotalGrantAwardAmount__c, ParentGoal__r.Award__r.TotalGrantAwardAmount__c,ParentGoal__r.ExpenditureAmount__c,ParentGoal__r.AllocatedAmount__c, QuantitativeNumberMeasures__c, Other__c, Description__c, ActivitiesAndMethods__c, MeasureEffectiveness__c, CombineTextQuestions__c,TargetedQ__c,Q1__c,Q2__c,Q3__c,Q4__c,AwardTotalQuantitative__c,AchievedQComments__c,AwardQ1__c,AwardQ2__c,AwardQ3__c,AwardQ4__c,AwardQ1Comments__c,AwardQ2Comments__c,AwardQ3Comments__c,AwardQ4Comments__c FROM GoalObjective__c where ID in : goalIds];     
        }
        else{        
          tConditionList = [select Id, ParentGoal__r.ExpenditureAmount__c, ParentGoal__r.AllocatedAmount__c, Allocated__c,type__c,Award__r.TotalGrantAwardAmount__c,ExpenditureAmount__c,Award__r.YTDReimbursementPaid__c,AllocatedAmount__c  FROM GoalObjective__c where ID in : goalIds];
        }
        
        for(GoalObjective__c obj : tConditionList) {
          if(obj.type__c=='Goal') {  // This is Goal Record
                  Decimal allocatedPercent = obj.Allocated__c==null?0:obj.Allocated__c;
                  Decimal totalAmount = obj.Award__r.TotalGrantAwardAmount__c == null ? 0 : obj.Award__r.TotalGrantAwardAmount__c;
                  Decimal totalExpenditure = obj.Award__r.YTDReimbursementPaid__c == null ? 0 : obj.Award__r.YTDReimbursementPaid__c;
                  Decimal allocatedAmount = (allocatedPercent*totalAmount)/100;
                  obj.AllocatedAmount__c=allocatedAmount;
                  Decimal expenditureAmount = (allocatedPercent*totalExpenditure)/100; 
                  obj.ExpenditureAmount__c=expenditureAmount;
              
            }
            else {  // This is Objective Record
                  Decimal allocatedPercent = obj.Allocated__c==null?0:obj.Allocated__c;
                  Decimal totalParentAmount = obj.ParentGoal__r.AllocatedAmount__c == null ? 0 : obj.ParentGoal__r.AllocatedAmount__c;
                  Decimal totalParentExpenditureAmount = obj.ParentGoal__r.ExpenditureAmount__c == null ? 0 : obj.ParentGoal__r.ExpenditureAmount__c;
                  Decimal allocatedAmount = (allocatedPercent*totalParentAmount )/100;
                  Decimal expenditureAmount = (allocatedPercent*totalParentExpenditureAmount )/100;
                  obj.AllocatedAmount__c=allocatedAmount;
                  obj.ExpenditureAmount__c=expenditureAmount;
            }
            
            //Consolidates the text questions for use in print to pdf, since formula fields don't support rich text fields
            obj.CombineTextQuestions__c = 'Quantitative Number Measures: ' + ((obj.QuantitativeNumberMeasures__c == null)? 'N/A' : obj.QuantitativeNumberMeasures__c) + '<br><br>' + 'Other: ' + ((obj.Other__c == null)? 'N/A' : obj.Other__c) + '<br><br>' + 'Objective Description: ' + ((obj.Description__c == null)? 'N/A' : obj.Description__c) + '<br><br>' + 'Activities And Methods: ' + ((obj.ActivitiesAndMethods__c == null)? 'N/A' : obj.ActivitiesAndMethods__c) + '<br><br>' + 'Indicate How You Will Measure The Effectiveness Of This Goal: ' + ((obj.MeasureEffectiveness__c == null)? 'N/A' : obj.MeasureEffectiveness__c);
            obj.AchievedQComments__c = 'Comments on Achieved Q1 :' + ((obj.AwardQ1Comments__c == null)? 'N/A' : obj.AwardQ1Comments__c) + '<br><br>' + 'Comments on Achieved Q2 :' + ((obj.AwardQ2Comments__c == null)? 'N/A' : obj.AwardQ2Comments__c) + '<br><br>' + 'Comments on Achieved Q3 :' + ((obj.AwardQ3Comments__c == null)? 'N/A' : obj.AwardQ3Comments__c) + '<br><br>' + 'Comments on Achieved Q4 :' + ((obj.AwardQ4Comments__c == null)? 'N/A' : obj.AwardQ4Comments__c) ;
            //system.debug('Targeted Q1 is ' +obj.Q1__c);
            //obj.TargetedQ__c = 'Q1:' +((obj.Q1__c == null)? 'N/A' : obj.Q1__c.format()) + '<br><br>' + 'Q2:' +((obj.Q2__c == null)? 'N/A' : obj.Q2__c.format()) + '<br><br>' +'Q3:' +((obj.Q3__c == null)? 'N/A' : obj.Q3__c.format()) + '<br><br>' +'Q4:' +((obj.Q4__c == null)? 'N/A' : obj.Q4__c.format()) ;
            //obj.AchievedQ__c = 'Q1:' +((obj.AwardQ1__c == null)? 'N/A' : obj.AwardQ1__c.format()) + '<br><br>' + 'Q2:' +((obj.AwardQ2__c == null)? 'N/A' : obj.AwardQ2__c.format()) + '<br><br>' +'Q3:' +((obj.AwardQ3__c == null)? 'N/A' : obj.AwardQ3__c.format()) + '<br><br>' +'Q4:' +((obj.AwardQ4__c == null)? 'N/A' : obj.AwardQ4__c.format()) ;
            obj.AchievedQ__c = 'Q1:' +((obj.AwardQ1__c == null)? 'N/A' : obj.AwardQ1__c.format()) + '<br><br>' + 'Q2:' +((obj.AwardQ2__c == null)? 'N/A' : obj.AwardQ2__c.format()) + '<br><br>' +'Q3:' +((obj.AwardQ3__c == null)? 'N/A' : obj.AwardQ3__c.format()) + '<br><br>' +'Q4:' +((obj.AwardQ4__c == null)? 'N/A' : obj.AwardQ4__c.format()) + '<br><br>' + 'Total Quantitative:'+((obj.AwardTotalQuantitative__c == null)? 'N/A' : obj.AwardTotalQuantitative__c.format())+ '<br><br>';
        }
        skipTrigger =true;
        update tConditionList; 

        //update Objective allocation if goal Allocation is changed
        if(Trigger.isUpdate && !isObjectiveFlag)
        updateObjectiveAllocation((Map<Id,GoalObjective__c>)Trigger.oldMap,(Map<Id,GoalObjective__c>)Trigger.newMap);       
    }
    
    // Validate Sum Total of Allocation % never exceeds 100%
    private void validateAllocation(List<GoalObjective__c> termConditionList){
        List<Id> targetIds = new List<Id>();
        List<Id> goalIds = new List<Id>();
        List<GoalObjective__c> tConditionList = new List<GoalObjective__c>();
        Boolean isObjectiveFlag=false;
        
        for(GoalObjective__c tc : termConditionList) {// looping over tigger.new  
         if(tc.recordtypeId==Schema.SObjectType.GoalObjective__c.getRecordTypeInfosByName().get('Program').getRecordTypeId())
         return;  
          else{
            goalIds.add(tc.Id);       
            if(tc.type__c=='Goal'){
                isObjectiveFlag=false;
                targetIds.add(tc.Award__c);
            }else if(tc.type__c=='Objective'){
                isObjectiveFlag=true;
                targetIds.add(tc.ParentGoal__c);
            }
          }
        } 
        
        if(!isObjectiveFlag){// select from goals, all child objectives
          tConditionList = [select Id,Allocated__c,type__c,ParentGoal__c FROM GoalObjective__c where Award__c in : targetIds and isParent__c=true and Id Not in :goalIds ];   
        }
        else{        // select award and then all goals
          tConditionList = [select Id,Allocated__c,type__c,Award__c FROM GoalObjective__c where ParentGoal__c in : targetIds and isParent__c=false and Id Not in :goalIds ];
        }
                
        Decimal totalAllocation=0;
        // Find Sum total of existing allocation % 
        for(GoalObjective__c obj : tConditionList ){
            totalAllocation+=obj.Allocated__c==null?0:obj.Allocated__c;                   
        }        
        
        for(GoalObjective__c tc : termConditionList) {// Trigger.new        
            totalAllocation+=tc.Allocated__c==null?0:tc.Allocated__c;            
             if(totalAllocation>100){
                 // tc.addError('Total Allocation can not exceed 100%');
                 //tc.addError(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTE-67740'));                                           
              }        
        }            
    }

    // update Record Type based on if Award/Program is mapped
    private void updateRecord(List<GoalObjective__c> lstGoals){
      for(GoalObjective__c gobj : lstGoals){
        if(gobj.Program__c!=null){
          gobj.RecordTypeId = Schema.SObjectType.GoalObjective__c.getRecordTypeInfosByName().get('Program').getRecordTypeId();
          }else if(gobj.Award__c!=null){
          gobj.RecordTypeId = Schema.SObjectType.GoalObjective__c.getRecordTypeInfosByName().get('Award').getRecordTypeId();
          }else if(gobj.Application__c!=null){
          gobj.RecordTypeId = Schema.SObjectType.GoalObjective__c.getRecordTypeInfosByName().get('Application').getRecordTypeId();
        }
      }
    }

    private void updateObjectiveAllocation(Map<Id,GoalObjective__c> oldMap,Map<Id,GoalObjective__c> newMap){
      Set<Id> goalIds = new Set<Id>();
       for(Id goalId : newMap.keySet()){
            if(oldMap.get(goalId).Allocated__c != newMap.get(goalId).Allocated__c){
              System.debug('Different Values ');
              goalIds.add(goalId);
            }
          }

    // Query Objective Table
      List<GoalObjective__c>  ObjectivesList = [select Id,Name,Allocated__c,type__c,ParentGoal__r.Award__r.TotalGrantAwardAmount__c,ParentGoal__r.ExpenditureAmount__c,ParentGoal__r.AllocatedAmount__c FROM GoalObjective__c where ParentGoal__c in : goalIds];     
     
         for(GoalObjective__c obj : ObjectivesList) {    
                  System.debug('*obj*'+obj);                     
                  Decimal totalParentAmount = obj.ParentGoal__r.AllocatedAmount__c == null ? 0 : obj.ParentGoal__r.AllocatedAmount__c;
                  Decimal totalParentExpenditureAmount = obj.ParentGoal__r.ExpenditureAmount__c == null ? 0 : obj.ParentGoal__r.ExpenditureAmount__c ;
                  Decimal allocatedAmount = (obj.Allocated__c==null?0:obj.Allocated__c*totalParentAmount )/100;
                  Decimal expenditureAmount = (obj.Allocated__c==null?0:obj.Allocated__c*totalParentExpenditureAmount )/100;
                  obj.AllocatedAmount__c=allocatedAmount;
                  obj.ExpenditureAmount__c=expenditureAmount;         
        }

        skipTrigger =true;
        update ObjectivesList; 
    }  

    // When Goal is deleted, delete all child objectives
     private void deleteObjectives(List<GoalObjective__c> lstGoals){
      Set<Id> goalIds  = new Set<Id>();
       for(GoalObjective__c obj : lstGoals) {
          if(obj.type__c=='Goal') {
             goalIds.add(obj.Id);
          }
        }
        List<GoalObjective__c>  ObjectivesList = [select Id,Name FROM GoalObjective__c where ParentGoal__c in : goalIds];     
        if(ObjectivesList.size()>0)
        delete ObjectivesList;

     }

     private void updateGoalObjectiveIndicator(List<GoalObjective__c> lstGoals){
      Set<Id> formIds = new Set<Id>();
      for(GoalObjective__c goal : lstGoals){
        if(goal.Form__c != null && !formIds.contains(goal.Form__c)){
          formIds.add(goal.Form__c);
        }
      }

      if(formIds.size() == 0){
        return;
      }

      Map<Id, Form__c> formMap = new Map<Id, Form__c>([Select Id, GoalObjectiveIndicator__c from Form__c where Id In :formIds]);
      List<Form__c> checkGoal = [Select Id, (Select Id from Goals_Objectives__r where IsParent__c = true) from Form__c where Id In :formIds];

      List<GoalObjective__c> goodGoals = new List<GoalObjective__c>();

      Set<Id> updateForm = new Set<Id>();

      for(Form__c f : checkGoal){
        if(f.Goals_Objectives__r.size() > 0){
          for(GoalObjective__c g : f.Goals_Objectives__r){
            goodGoals.add(g);
          }
        }
      }

      List<GoalObjective__c> checkObjective = [Select Id, (Select Id from Goals_and_Objectives2__r), Form__c from GoalObjective__c where Id IN :goodGoals];
      for(GoalObjective__c g : checkObjective){
        if(g.Goals_and_Objectives2__r.size() > 2){
          if(!updateForm.contains(g.Form__c)){
            updateForm.add(g.Form__c);
          }
        }
      }

      for(Id i : formMap.keySet()){
        if(updateForm.contains(i)){
          formMap.get(i).GoalObjectiveIndicator__c = 'Yes';
        }else{
          formMap.get(i).GoalObjectiveIndicator__c = null;
        }
      }

      System.debug('FormMap-------------->' + formMap);

      update formMap.values();

     }
    
}