UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>ExternalOrganization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Orgnanization which owns the Application This field is also used on the Forms as well</description>
        <inlineHelpText>Which organization owns the application?</inlineHelpText>
        <label>Applicant Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Review Initiated</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Submitted For Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Sent for Review</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision In Progress</fullName>
                </value>
                <value>
                    <fullName>Revision Completed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Rejection Initiated</fullName>
                </value>
                <value>
                    <fullName>Internally Reviewed</fullName>
                </value>
                <value>
                    <fullName>Converted to Award</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Converted to Grant</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Revision Initiated</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Approved Internally</fullName>
                </value>
                <value>
                    <fullName>Snapshot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Grantee</fullName>
        <active>true</active>
        <description>Application Created by the user in State as Grantee App</description>
        <label>Grantee</label>
    </recordTypes>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <description>Application Created by the user in State as Grantor App</description>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ChangeRequest__c.object
<CustomObject>
    <description>[Business]  Currently used to track pre-award negotiation requests for application only. In the future this can be enhanced for other objects like award or something else.</description>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Negotiation Requests</relationshipLabel>
        <relationshipName>Change_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExternalOrganization__c</fullName>
        <formula>Application__r.ExternalOrganization__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>External Organization</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GranteeNotified__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Grantee notified of pending negotiation</description>
        <label>Grantee Notified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                    <default>true</default>
                    <label>Not Initiated</label>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Negotiation Request</label>
    <nameField>
        <displayFormat>CR-{000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Negotiation Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FormBudgetInformation__c.object
<CustomObject>
    <description>[Business] This object is used for Budget Information forms.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Overflow Budget Information</label>
    <nameField>
        <displayFormat>BI-{00000}</displayFormat>
        <label>Budget Information</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Overflow Budget Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/NegotiationTasksHandler.cls
/* This class runs everyday to check the Negotiation Tasks
* 1. Send a mail to Grantee POC for responding to Negotiation requests
* 2. After due date if negotiation is not completed, mark it to failed state
*/
global class NegotiationTasksHandler extends GNT.BatchApexHandler{ //implements Database.Batchable<sObject> ,Schedulable, Database.Stateful{
 
  Integer recordCount;    
//   global Database.QueryLocator start(Database.BatchableContext BC){
    global override String getQuery() {
    String query='Select Id,Name, DueDate__c,Application__c,Application__r.ExternalOrganization__c from ChangeRequest__c where GranteeNotified__c=false and DueDate__c =NEXT_N_DAYS:7 and Application__r.RecordType.DeveloperName=\'Grantor\'';   
   // return Database.getQueryLocator(query);
    return query;
   }
  
  //global void execute(Database.BatchableContext BC, List<ChangeRequest__c> scope){   
     global override void execute(List<SObject> scope){
     try{     
       notifyGrantee(scope);
       invalidateExpiredNegotiations(scope);   
       
       }catch(Exception exc)  { System.debug('An exception Occured while running the batch  '+exc); }
    }
 
 // In the Finish method, the list of notification users and batch runner (user) is sent a status mail 
   // global void finish(Database.BatchableContext BC){
       global override void finish(){
     //  AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id =
     //       :BC.getJobId()];
       //List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();    
       String msgDetails = 'Task Completed for '+Date.today();
       msgDetails+='\n  Total number of Reports created : '+ recordCount==null? 0 : recordCount;
             /*Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
              mail.setTargetObjectId(UserInfo.getUserId());
              mail.saveAsActivity = false;            
              mail.setSubject(' ProgressReportsTasksHandler has completed');
              system.debug(msgDetails);
              mail.setPlainTextBody(msgDetails);
              mails.add(mail);
              Messaging.sendEmail(mails); 
              */
              new GNT.EmailFeeder().Subject(' ProgressReportsTasksHandler has completed').TargetObjectId(UserInfo.getUserId()).htmlBody(msgDetails).send();
       }
   
   // This is the schedulable method which will be run as daily schedule.
   global void execute(SchedulableContext sc) 
    {
    ID BatchId = Database.executeBatch(new ProgressReportsTasksHandler());
    }  
    
    private void notifyGrantee(List<ChangeRequest__c> crList){
    
        Set<Id> accIdSet = new Set<Id>();
        
        for(ChangeRequest__c cr: crList){
        accIdSet.add(cr.Application__r.ExternalOrganization__c);
        }
    
                String[] toAddresses = new String[] {};
                List<User> userList = [SELECT Id,Email FROM User WHERE IsActive = true AND AccountId IN: accIdSet LIMIT 2 ];
                for(User u: userList){  
                    toAddresses.add(u.Email);
                }
                if(toAddresses.size() > 0){ 
                    Map<Id, String[]> recIdToAddressMap = new Map<Id, String[]> ();
                   // recIdToAddressMap.put(changeReq.Id, toAddresses);
                    List<EmailTemplate> emailTemplate = [Select id From EmailTemplate Where DeveloperName = 'PreAwardRequestAssigned' Limit 1];// TODO, get new email name
                    Contact cont = [select id, Email from Contact where email <> null limit 1];
                    AppUtils.sendEmailUsingTemplate(emailTemplate[0].Id, recIdToAddressMap, cont.Id, false);// 
                }  
    
    }
     private void invalidateExpiredNegotiations(List<ChangeRequest__c> crList){
     
     Set<Id> appIdSet = new Set<Id>();
        
        for(ChangeRequest__c cr: crList){
           if(cr.DueDate__c<System.Today()){
           appIdSet.add(cr.Application__c);
           }
        
        }
        
        List<Application__c> appList = [Select Id, Name, Status__c from Application__c where Id IN : appIdSet];
        
        for(Application__c app :applist){
        app.Status__c='Revision Failed';
        }
        update appList;
        
     }
  
   }