UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/USBEForm__c.object
<CustomObject>
    <description>This object is basically the main form object to be used to build the USBE forms</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>USBEForms</relationshipLabel>
        <relationshipName>USBEForms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>USBEForm</label>
    <nameField>
        <label>USBEForm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>USBEForms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/LEAPrivateSchoolEditCtrl.cls
public with sharing class LEAPrivateSchoolEditCtrl{
    public ID recordId {get;set;}
    public ID formId {get;set;}
    public ID appId {get;set;}
    public String pageTemplateName {get;set;}
    public String savePage{get;set;}
    public String cancelPage{get;set;}
    public List<GNT.DynamicLayoutDefaultValueHelper> listDefaultValues {get;set;}
    
    public LEAPrivateSchoolEditCtrl(ApexPages.StandardController stdController){
        formId = ApexPages.CurrentPage().getParameters().get('formId');
        appId = ApexPages.CurrentPage().getParameters().get('appId');
        pageTemplateName = 'LEAPrivateSchool';

        listDefaultValues = new List<GNT.DynamicLayoutDefaultValueHelper>();
        if (formId != null) {
            GNT.DynamicLayoutDefaultValueHelper formdv = new GNT.DynamicLayoutDefaultValueHelper('USBEForm__c',formId, true);
            listDefaultValues.add(formdv);
        }

        if (appId != null) {
            GNT.DynamicLayoutDefaultValueHelper appdv = new GNT.DynamicLayoutDefaultValueHelper('Application__c',appId, true);
            listDefaultValues.add(appdv);
        }
    }
    
    public string getKeyValueMap(){
        Map<String,String> keyValueMap = new Map<String,String>();
        keyValueMap.put('formId',formId);
        keyValueMap.put('appId',appId);
        return JSON.serialize(keyValueMap);
    }
    
    

}