UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>ExternalOrganization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Orgnanization which owns the Application This field is also used on the Forms as well</description>
        <inlineHelpText>Which organization owns the application?</inlineHelpText>
        <label>Applicant Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ApplicationMapHelper.cls
global with sharing class ApplicationMapHelper implements GNT.MapInterface{
    public List<GNT.MapPin> getPins(Map<String, String> urlParams){
        Id applicationId = urlParams.get('id');  
        List<Application__c> applicationList = [Select Id,ExternalOrganization__r.ShippingLongitude,ExternalOrganization__r.ShippingLatitude 
                                                        From Application__c 
                                                            Where Id = :applicationId LIMIT :GNT.AppUtils.SOQL_LIMIT];
        
        List<GNT.MapPin> pinsList = new List<GNT.MapPin>();
        for(Application__c a:applicationList){
         GNT.MapPin pin = new GNT.MapPin();
            pin.longitude = a.ExternalOrganization__r.ShippingLongitude;    
            pin.latitude = a.ExternalOrganization__r.ShippingLatitude;      
            pinsList.add(pin);  
        }          
        return pinsList;        
    }    
}