UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <fields>
        <fullName>FinalApproverComments__c</fullName>
        <description>Field used by the Final Approver to make comments on the Application during the Application Approval or Rejection Process</description>
        <inlineHelpText>Field used by the Final Approver to make comments on the Application during the Application Approval or Rejection Process</inlineHelpText>
        <label>Final Approver Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ApplicationAddCommentCtrl.cls
public with sharing class ApplicationAddCommentCtrl {
    public Application__c selectedApp {get;set;}
    
    public ApplicationAddCommentCtrl(){
        selectedApp = new Application__c();
        Id recordId = ApexPages.CurrentPage().getParameters().get('id');
        
        if(recordId != null){
            List<Application__c> appList = [Select Id, FinalApproverComments__c From Application__c where Id = :recordId];
            if(appList.isEmpty() != true){
                selectedApp = appList.get(0);
            }
        }
    }
    
    public void btnAddComment (){
        if(selectedApp != null){
            try{
                if(Schema.sObjectType.Application__c.isUpdateable()){
                    update selectedApp;
                }
            }
            catch(Exception e){
                selectedApp.addError('Exception Occured - ' + e );
            }
        }
    }
    
    public void btnCancel(){
        
    }
    
}