UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/WBSTaskSchedule__c.object
<CustomObject>
    <description>[Business] Used to Store the Schedule of of Task in WBS Grid</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>WBS Task Schedule</relationshipLabel>
        <relationshipName>WBS_Task_Schedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Award to which WBS Task is associated</description>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>WBS Task Schedule</relationshipLabel>
        <relationshipName>WBS_Task_Schedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>WBS Task Schedule</relationshipLabel>
        <relationshipName>WBS_Task_Schedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WBS Task Schedule</label>
    <nameField>
        <label>WBSTaskSchedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WBS Task Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/WBSTaskViewCtrl.cls
public  class WBSTaskViewCtrl {
    
    //Properties
    public ID recordId{get;set;}
    public WBSTaskSchedule__c WBSTaskScheduleObj{get;set;}
    
    public WBSTaskViewCtrl ( ){
        recordId = ApexPages.CurrentPage().getParameters().get('id'); 
        system.debug('recordId------>>>>'+recordId);               
    }
    public PageReference redirect(){
    PageReference  p = null;
        if (recordId != null){
            WBSTaskScheduleObj = [SELECT Id,Program__c,Application__c,Award__c from WBSTaskSchedule__c  where id=:recordId];
            System.debug('===WBSTaskScheduleObj==='+WBSTaskScheduleObj);
                if(WBSTaskScheduleObj.Program__c  != null){
                     p = new PageReference('/'+WBSTaskScheduleObj.Program__c);
                     return p;
                }
                else if (WBSTaskScheduleObj.Application__c  != null){
                     p = new PageReference('/'+WBSTaskScheduleObj.Application__c);
                     return p;
                }
                else if(WBSTaskScheduleObj.Award__c  != null){
                     p = new PageReference('/'+WBSTaskScheduleObj.Award__c);
                     return p;
                }
        }
    return p;
        
    }
    
 
   
}