UtahLiveDataTest/src/objects/Application__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Applications</description>
    <label>Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Review__c.object
<CustomObject>
    <description>[Business] Defines the Review object (Need more Details / Need to revisit for the Description)</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewPanel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review Panel</label>
        <referenceTo>ReviewPanel__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review Step</label>
        <referenceTo>ReviewStep__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewPanel__c.object
<CustomObject>
    <description>[Business] Defines the Review Panel to review the Applications</description>
    <fields>
        <fullName>AnnoucementId__c</fullName>
        <formula>ReviewStep__r.AnnouncementId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Funding Opportunity ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Chair__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Headed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Review_Panels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GroupName__c</fullName>
        <inlineHelpText>When Announcement deadline reaches all the applications will be assigned to the users under this group.</inlineHelpText>
        <label>Group Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReviewPackage__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Review Form</label>
        <referenceTo>GNT__Package__c</referenceTo>
        <relationshipLabel>Review Panels</relationshipLabel>
        <relationshipName>Review_Panels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewStep__c</fullName>
        <label>Review Step</label>
        <referenceTo>ReviewStep__c</referenceTo>
        <relationshipLabel>Review Panels</relationshipLabel>
        <relationshipName>Review_Panels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Review Panel</label>
    <nameField>
        <displayFormat>Panel-{000}</displayFormat>
        <label>Review Panel ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStep__c.object
<CustomObject>
    <description>[Business] Defines all the details of Review Step defined in the Review of Application/Pre-Application</description>
    <fields>
        <fullName>ReviewPackage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review Package</label>
        <referenceTo>GNT__Package__c</referenceTo>
        <relationshipLabel>Review Steps</relationshipLabel>
        <relationshipName>Review_Rounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestReviewPanelTriggerHelper.cls
@isTest
private with sharing class TestReviewPanelTriggerHelper {

    private static Review__c review;
    private static  ReviewPanel__c rPanel;
    private static  Application__c app;
    private static ReviewStep__c reviewStep;    

    private static void setup(Boolean create){   
        UserTriggerHelper.skipTrigger=true; 
        ReviewStepTriggerHelper.SkipTrigger=true;
        AppUtils.skipStepReviewTrigger = true;              
        Testhelper.createCustomSettings(true);             
        review = TestHelper.getReview(create);  
        rPanel = [Select Id, AnnoucementId__c, ReviewStep__c, ReviewPackage__c From ReviewPanel__c Where Id = : review.ReviewPanel__c];            
    }

   /* @isTest
    private static void testMethodSetGroupId(){
        UserTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(false);
        System.runAs(u){     
            Test.startTest();
            setup(true);
            
            Group testGroup = new Group(Name = 'Queue', Type = 'Queue');
            insert testGroup;
            
            rPanel.GroupName__c = 'Queue';
            update rPanel;
            Test.stopTest();
        }
    }
    
    @isTest
    private static void testUpdateMethod(){        
        UserTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(false);       
        System.runAs(u){    
            Test.startTest();    
            setup(true);      
            rPanel.Chair__c = TestHelper.getStandardPlatformUser(true).Id;
            update rPanel;
            Test.stopTest();
        }
    }*/

}