UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>BudgetStartEndDate__c</fullName>
        <formula>IF(AND(NOT(ISBLANK(BudgetPeriod__r.BudgetStartDate__c )),NOT(ISBLANK(BudgetPeriod__r.BudgetEndDate__c))),TEXT(MONTH( BudgetPeriod__r.BudgetStartDate__c ))+&quot;/&quot; +TEXT(DAY(BudgetPeriod__r.BudgetStartDate__c))+&quot;/&quot; +TEXT(YEAR(BudgetPeriod__r.BudgetStartDate__c))+&quot;--&quot;+ TEXT(MONTH( BudgetPeriod__r.BudgetEndDate__c ))+&quot;/&quot; +TEXT(DAY(BudgetPeriod__r.BudgetEndDate__c))+&quot;/&quot; +TEXT(YEAR(BudgetPeriod__r.BudgetEndDate__c)),&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Budget Period</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent to Grantee Review</fullName>
                </value>
                <value>
                    <fullName>Grantee Accepted</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>FINOPS Completed</fullName>
                </value>
                <value>
                    <fullName>Sent to FINOPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Closeout__c.object
<CustomObject>
    <description>[Business] All the close out information is stored on this object</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Closeouts</relationshipLabel>
        <relationshipName>Closeouts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Closeouts</relationshipLabel>
        <relationshipName>Closeouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Notified</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Notification Accepted</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closeout</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closeouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed/Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RiskAssessment__c.object
<CustomObject>
    <description>[Business] This will be part of Grant Making Module.</description>
    <fields>
        <fullName>CurrentBudgetPeriod__c</fullName>
        <label>Current Budget Period</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FiscalRating__c</fullName>
        <formula>IF(ISNUMBER(TotalDollarAmount__c),VALUE(TotalDollarAmount__c), 0)+IF(ISNUMBER(PreviousGrantExperience__c),VALUE(PreviousGrantExperience__c), 0)+
IF(ISNUMBER(FinancialComplianceMonitoring__c),VALUE(FinancialComplianceMonitoring__c), 0)+IF(ISNUMBER(FiscalReviewQ1__c),VALUE(FiscalReviewQ1__c), 0)+
IF(ISNUMBER(FiscalReviewQ2__c),VALUE(FiscalReviewQ2__c), 0)+IF(ISNUMBER(FiscalReviewQ3__c),VALUE(FiscalReviewQ3__c), 0)+
IF(ISNUMBER(FiscalReviewQ5__c),VALUE(FiscalReviewQ5__c), 0)+IF(ISNUMBER(FiscalReviewQ4__c),VALUE(FiscalReviewQ4__c), 0)+IF(ISNUMBER(FiscalReviewQ6__c),VALUE(FiscalReviewQ6__c), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FiscalRating</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GrantRating__c</fullName>
        <formula>IF(ISNUMBER(ActivityRisk1__c),VALUE(ActivityRisk1__c), 0)+IF(ISNUMBER(ActivityRisk2__c),VALUE(ActivityRisk2__c), 0)+
IF(ISNUMBER(ActivityRisk3__c),VALUE(ActivityRisk3__c), 0)+IF(ISNUMBER(ActivityRisk4__c),VALUE(ActivityRisk4__c), 0)+
IF(ISNUMBER(ActivityRisk5__c),VALUE(ActivityRisk5__c), 0)+IF(ISNUMBER(ActivityRisk6__c),VALUE(ActivityRisk6__c), 0)+
IF(ISNUMBER(ActivityRisk7__c),VALUE(ActivityRisk7__c), 0)+IF(ISNUMBER(ActivityRisk8__c),VALUE(ActivityRisk8__c), 0)+IF(ISNUMBER(ActivityRisk9__c),VALUE(ActivityRisk9__c), 0)+IF(ISNUMBER(ActivityRisk10__c),VALUE(ActivityRisk10__c), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Grant Rating</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Risk Assessment</relationshipLabel>
        <relationshipName>Risk_Assessment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OverAll_Risk__c</fullName>
        <label>Overall Risk</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProgramRating__c</fullName>
        <formula>IF(ISNUMBER(ProgramQuestion1__c),VALUE(ProgramQuestion1__c), 0)+IF(ISNUMBER(ProgramQuestion2__c),VALUE(ProgramQuestion2__c), 0)+
IF(ISNUMBER(ProgramQuestion3__c),VALUE(ProgramQuestion3__c), 0)+IF(ISNUMBER(ProgramQuestion4__c),VALUE(ProgramQuestion4__c), 0)+
IF(ISNUMBER(ProgramQuestion5__c),VALUE(ProgramQuestion5__c), 0)+IF(ISNUMBER(ProgramQuestion6__c),VALUE(ProgramQuestion6__c), 0)+
IF(ISNUMBER(ProgramQuestion7__c),VALUE(ProgramQuestion7__c), 0)+IF(ISNUMBER(ProgramQuestion8__c),VALUE(ProgramQuestion8__c), 0)+IF(ISNUMBER(ProgramQuestion9__c),VALUE(ProgramQuestion9__c), 0)+IF(ISNUMBER(ProgramQuestion10__c),VALUE(ProgramQuestion10__c), 0)+IF(ISNUMBER(ProgramQuestion11__c),VALUE(ProgramQuestion11__c), 0)+IF(ISNUMBER(ProgramQuestion12__c),VALUE(ProgramQuestion12__c), 0)+IF(ISNUMBER(ProgramQuestion13__c),VALUE(ProgramQuestion13__c), 0)+IF(ISNUMBER(ProgramQuestion14__c),VALUE(ProgramQuestion14__c), 0)+IF(ISNUMBER(ProgramQuestion15__c),VALUE(ProgramQuestion15__c), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Rating</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SumRating1__c</fullName>
        <formula>IF(ISNUMBER(ActivityRisk1__c),VALUE(ActivityRisk1__c), 0)+IF(ISNUMBER(ActivityRisk2__c),VALUE(ActivityRisk2__c), 0)+
IF(ISNUMBER(ActivityRisk3__c),VALUE(ActivityRisk3__c), 0)+IF(ISNUMBER(ActivityRisk4__c),VALUE(ActivityRisk4__c), 0)+
IF(ISNUMBER(ActivityRisk5__c),VALUE(ActivityRisk5__c), 0)+IF(ISNUMBER(ActivityRisk6__c),VALUE(ActivityRisk6__c), 0)+
IF(ISNUMBER(ActivityRisk7__c),VALUE(ActivityRisk7__c), 0)+IF(ISNUMBER(ActivityRisk8__c),VALUE(ActivityRisk8__c), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SumRating1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SumRating2__c</fullName>
        <formula>IF(ISNUMBER(ActivityRisk9__c),VALUE(ActivityRisk9__c), 0)+IF(ISNUMBER(ActivityRisk10__c),VALUE(ActivityRisk10__c), 0)+
IF(ISNUMBER(ActivityRisk11__c),VALUE(ActivityRisk11__c), 0)+IF(ISNUMBER(ActivityRisk12__c),VALUE(ActivityRisk12__c), 0)+
IF(ISNUMBER(ActivityRisk13__c),VALUE(ActivityRisk13__c), 0)+IF(ISNUMBER(ActivityRisk14__c),VALUE(ActivityRisk14__c), 0)+
IF(ISNUMBER(ActivityRisk15__c),VALUE(ActivityRisk15__c), 0)+IF(ISNUMBER(ActivityRisk16__c),VALUE(ActivityRisk16__c), 0)+
IF(ISNUMBER(ActivityRisk17__c),VALUE(ActivityRisk17__c), 0)+IF(ISNUMBER(ActivityRisk18__c),VALUE(ActivityRisk18__c), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SumRating2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalSumofRating__c</fullName>
        <label>Sum of Rating</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Risk Assessment</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk Assessment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/RiskAssessmentTriggerHelper.cls
global with sharing class RiskAssessmentTriggerHelper extends GNT.TriggerHelper {
    global override void processAfterInsert() {
      //  updateGrantToPointToLatestRiskOnInsert();
      updateBudgetPeriod(Trigger.new);
    }
    
    global override void processBeforeInsert() {
       // lockRiskAssessmentForCloseout(Trigger.new);   
  //       GNT.NameTemplateTriggerHelper.beforeInsert(); 
    }

    global override void processBeforeDelete(){
     //   updateGrantToPointToLatestRiskOnDelete();       
    }

    global override void processBeforeUpdate() {

          if(trigger.isBefore && trigger.isUpdate){        
        calculateRating(); 
    }
        //lockRiskAssessmentForCloseout(Trigger.new);
    }


 private void updateBudgetPeriod(List<RiskAssessment__c> raList){
        Set<Id> grantSet = new Set<Id>();
        Set<Id> raSet = new Set<Id>();
        List<RiskAssessment__c> lstRA = new List<RiskAssessment__c>();

        system.debug('Inside updateBudgetPeriod');

        for(RiskAssessment__c ra : raList){

            grantSet.add(ra.Grant__c);
            raSet.add(ra.Id);
        }
        List<Award__c> awardList = [SELECT Id, BudgetStartEndDate__c FROM Award__c WHERE Grant__c IN :grantSet and Status__c ='Activated' Limit 1];
        
        system.debug('Inside updateBudgetPeriod--grantSet--'+grantSet);

        for(RiskAssessment__c ra : [Select Id, name, CurrentBudgetPeriod__c from RiskAssessment__c where Id IN : raSet]){
            if(awardList != null && !awardList.isEmpty() ){
                ra.CurrentBudgetPeriod__c=awardList[0].BudgetStartEndDate__c;

            }
            lstRA.add(ra);
        }
          system.debug('Inside updateBudgetPeriod');


        if(lstRa!=null && lstRa.size()>0)
        update lstRA;

    }

    /*
    private void lockRiskAssessmentForCloseout(List<RiskAssessment__c> raList){
        Set<Id> grantSet = new Set<Id>();
        Map<Id, Id> grantCloseoutMap = new Map<Id, Id>();
        for(RiskAssessment__c ra : raList){
            grantSet.add(ra.Grant__c);
        }
        List<Closeout__c> closeoutList = [SELECT Id, Grant__c, Status__c FROM Closeout__c WHERE Status__c IN ('Initiated By PM', 'Under PM Review', 'Approved By PM') AND Grant__c IN :grantSet];
        for(Closeout__c ct : closeoutList){
            grantCloseoutMap.put(ct.Grant__c, ct.Id);
        }
        for(RiskAssessment__c ra : raList){
            if(grantCloseoutMap != null && !grantCloseoutMap.isEmpty() && grantCloseoutMap.containsKey(ra.Grant__c)){
                //ra.addError('Closout is in progress for the Grant. Unable to complete request');
                ra.addError(GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-71821'));
            }
        }
    }
    

    private void updateGrantToPointToLatestRiskOnDelete(){
        Map<Id,Id> grantRiskMap =  new Map<Id,Id>();
        for(RiskAssessment__c ra : (List<RiskAssessment__c>)Trigger.old){            
              grantRiskMap.put(ra.Grant__c,ra.id);                  
        }
        
        List<Grant__c> grants = [SELECT Id,Name,(SELECT Id FROM Risk_Assessment__r ORDER BY CreatedDate LIMIT 1) 
            FROM Grant__c WHERE Id in :grantRiskMap.keySet()];
        
        List<Grant__c> grantsToBeUpdated = new List<Grant__c>();
        for(Grant__c grant :grants){
            if(grant.Risk_Assessment__r.size() > 0){
                system.debug('grant.Risk_Assessment__r[0]-----'+grant.Risk_Assessment__r[0]);
                //grant.LatestRiskAssessment__c = grant.Risk_Assessment__r[0].Id;
            }
            grantsToBeUpdated.add(grant);
            system.debug('grant-----'+grant);
        }
        
        if(grantsToBeUpdated.size() > 0){
            SystemContextMethodsHelper sc = new SystemContextMethodsHelper();
            system.debug('grantsToBeUpdated-----'+grantsToBeUpdated);
            sc.updateGrants(grantsToBeUpdated);
        }
    }

    private void updateGrantToPointToLatestRiskOnInsert(){
        Map<Id,Id> grantRiskMap =  new Map<Id,Id>();
        for(RiskAssessment__c ra : (List<RiskAssessment__c>)Trigger.new ){            
              grantRiskMap.put(ra.Grant__c,ra.id);                  
        }
        
        List<Grant__c> grants = [SELECT Id,Name FROM Grant__c WHERE Id in :grantRiskMap.keySet()];
        
        List<Grant__c> grantsToBeUpdated = new List<Grant__c>();
        
        for(Grant__c grant :grants){
            //grant.LatestRiskAssessment__c = grantRiskMap.get(grant.Id);
            grantsToBeUpdated.add(grant);
            system.debug('grant-----'+grant);
        }
        
        if(grantsToBeUpdated.size() > 0){
            system.debug('grantsToBeUpdated-----'+grantsToBeUpdated);
            SystemContextMethodsHelper sc = new SystemContextMethodsHelper();
            sc.updateGrants(grantsToBeUpdated);
        }
    }
*/

      private void calculateRating(){
        system.debug('Inside calculateRating---');

        for(RiskAssessment__c ra : (List<RiskAssessment__c>)Trigger.new ){
            RiskAssessment__c oldRisk = (RiskAssessment__c)Trigger.oldMap.get(ra.Id);
            system.debug('ra.FiscalRating__c is ---' +ra.FiscalRating__c);  
            system.debug(' ra.SumRating1__c---'+ra.SumRating1__c);
            system.debug('ra.SumRating2__c---'+ra.SumRating2__c);
            system.debug('ra.ProgramRating__c---'+ra.ProgramRating__c);
            system.debug('ra.GrantRating__c---'+ra.GrantRating__c);
            system.debug('oldRisk.ProgramRating__c---'+oldRisk.ProgramRating__c);
            system.debug('oldRisk.GrantRating__c---'+oldRisk.GrantRating__c);
            system.debug('ra.TotalSumofRating__c---'+ra.TotalSumofRating__c);
            if(ra.FiscalRating__c != oldRisk.FiscalRating__c){
            //if(ra.ProgramRating__c != oldRisk.ProgramRating__c || ra.GrantRating__c != oldRisk.GrantRating__c){
                //ra.TotalSumofRating__c = ra.ProgramRating__c + ra.GrantRating__c;
                ra.TotalSumofRating__c = ra.FiscalRating__c;        
            }            
           system.debug('**ra.TotalSumofRating__c---'+ra.TotalSumofRating__c);
           

            if(ra.TotalSumofRating__c >= 0 && ra.TotalSumofRating__c <= 25){
                ra.OverAll_Risk__c = 'Low';
            }else if(ra.TotalSumofRating__c >= 26 && ra.TotalSumofRating__c <= 50){
                ra.OverAll_Risk__c = 'Medium';
            }else if(ra.TotalSumofRating__c >= 51 && ra.TotalSumofRating__c <= 73){
                ra.OverAll_Risk__c = 'High';
            }   
        }
    }
    

       
        
}