UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingSource__c.object
<CustomObject>
    <description>[Business] Details of the Funding sources which further creates Funding accounts</description>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Funding Sources</relationshipLabel>
        <relationshipName>Funding_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <recordTypes>
        <fullName>External</fullName>
        <active>true</active>
        <description>This is used in Grantee side of Applicaion</description>
        <label>External</label>
    </recordTypes>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>This is used in grantor side of Applicaion</description>
        <label>Internal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>CurrentAward__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the current year award lookup field and is used to refer to latest award details</description>
        <inlineHelpText>This show the latest award details</inlineHelpText>
        <label>Current Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestFundingSourceEdit.cls
@isTest
public class TestFundingSourceEdit {

    static testMethod void myUnitTest() {
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          GrantTriggerHelper.skipTrigger = true;
          AwardTriggerHelper.skipTrigger = true;
          RolesandResponsibilitiesTriggerHelper.skipTrigger = true;
          Grant__c grant = TestHelper.getGrant(true);
          Award__c award = TestHelper.getAwards(grant.id,true);
          grant.CurrentAward__c = award.id;
          update grant;
          System.runAs(u){
             FundingSource__c funsource = TestHelper.getFundingSource(true);
             Test.startTest();
             ApexPages.StandardController sc = new ApexPages.standardController(funsource);
             ApexPages.currentPage().getParameters().put('Id',funsource.id);
             ApexPages.currentPage().getParameters().put('grantId',grant.id);
             ApexPages.currentPage().getParameters().put('RecordType','External');
             FundingSourceEditCtrl ctrl = new FundingSourceEditCtrl(sc);
             ctrl.getKeyValueMap();
             Test.stopTest();
        }
        
    }
     static testMethod void myUnitTest1() {
           UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          System.runAs(u){
             FundingSource__c funsource = TestHelper.getFundingSource(true);
             Test.startTest();
             ApexPages.StandardController sc = new ApexPages.standardController(funsource);
             ApexPages.currentPage().getParameters().put('Id',funsource.id);
             ApexPages.currentPage().getParameters().put('RecordType','Internal');
             FundingSourceEditCtrl ctrl = new FundingSourceEditCtrl(sc);
             ctrl.getKeyValueMap();
             Test.stopTest();
        }
        
    }
}