UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>BudgetPeriodEndDate__c</fullName>
        <description>Budget Period End Date for the award.</description>
        <label>Budget Period End Date(obsolete)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BudgetPeriodStartDate__c</fullName>
        <description>Budget Period Start Date for the award.</description>
        <label>Budget Period Start Date (Obsolete)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent to Grantee Review</fullName>
                </value>
                <value>
                    <fullName>Grantee Accepted</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>FINOPS Completed</fullName>
                </value>
                <value>
                    <fullName>Sent to FINOPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>BudgetPeriodEndDate__c</fullName>
        <label>Current Budget Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BudgetPeriodStartDate__c</fullName>
        <label>Current Budget Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed/Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/TermCondition__c.object
<CustomObject>
    <description>[Business] Terms and Conditions for Grants ,Awards (The lookup to Package may not be required in this case )</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Active, Inactive. If the Effective Date is current or in the past and if the Inactive On date is in the future, the Term is Active. If the Inactive Date is in the past, the term is Inactive. Prepopulated. Read Only.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MST:Term and Condition</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <recordTypes>
        <fullName>Condition</fullName>
        <active>true</active>
        <label>Condition</label>
    </recordTypes>
    <recordTypes>
        <fullName>ProgressReport</fullName>
        <active>true</active>
        <label>Progress Report</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/NewProgressReportConditionHandler.cls
global with sharing class NewProgressReportConditionHandler extends GNT.FlexTableActionHandler {
    public NewProgressReportConditionHandler() {
        
    }

    global override Map<String,Object> clickHandler(){
        Map<String,Object> resultMap = new Map<String,Object>();
        String ns = AppUtils.getNamespacePrefix(); 
        Id awardId = urlParams.get('id');
        Award__c award = [select id,Grant__c,BudgetPeriodStartDate__c,BudgetPeriodEndDate__c,Status__c from Award__c where id =: awardId limit 1];
        system.debug('award: '+award+' awardId: '+awardId);
        Integer tc = [SELECT COUNT() FROM TermCondition__c WHERE RecordType.Name = 'Progress Report' AND Award__c =: awardId];
        system.debug('TC: '+tc);
        //if(award != null && (award.Status__c != 'In Progress' && award.Status__c != 'Drafted')) {
             //resultMap.put('Message','The Cycle cannot be set/edit because the Award is:'+award.Status__c);
        //}
        if(award.BudgetPeriodStartDate__c == null || award.BudgetPeriodEndDate__c == null) {
            resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-11385'));
            return resultMap;
        }
        /*if(award != null && award.Status__c != 'Drafted') {
             resultMap.put('Message','The cycle cannot be modified because the Award is in:'+award.Status__c);
             return resultMap;
        }*/
        if(tc > 0) {
            //resultMap.put('Message','A Progress Report Condition has already been created !');
            TermCondition__c termCondition = [SELECT id FROM TermCondition__c WHERE RecordType.Name = 'Progress Report' AND Award__c =: awardId limit 1];                                      
            Id termConditionId = termCondition.Id;
            //Id termConditionId = tcSchedule.TermAndCondition__c;                                      
            String PageReferenceURL = '/apex/'+ns+'TermConditionEdit?customHeader=Create Progress Report Condition&recordType=ProgressReport&isProgram=false&awardId='+awardId+'&id='+termConditionId+'&grantId='+award.Grant__c;
            resultMap.put('PageReference',PageReferenceURL); 
        }
        else {
            String PageReferenceURL = '/apex/'+ns+'TermConditionEdit?customHeader=Create Progress Report Condition&recordType=ProgressReport&isProgram=false&awardId='+awardId+'&grantId='+award.Grant__c;
            resultMap.put('PageReference',PageReferenceURL); 
        }
                                                
        return resultMap;
    }    
}