UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Final Approver for the Award</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awards4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent to Grantee Review</fullName>
                </value>
                <value>
                    <fullName>Grantee Accepted</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>FINOPS Completed</fullName>
                </value>
                <value>
                    <fullName>Sent to FINOPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PaymentRequest__c.object
<CustomObject>
    <description>[Business] Defines the details of for the Payment request.Payment request is done when award is already awarded and the Grantee wants to make use of the funds</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Payment_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Payment_Requests5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>PaymentRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Approval 1</fullName>
                </value>
                <value>
                    <fullName>Approval 2</fullName>
                </value>
                <value>
                    <fullName>Approval 3</fullName>
                </value>
                <value>
                    <fullName>Approval 4</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Sent to FINET</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Payment Request</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/InternalPaymentWaiverSubmissionHelper.cls
global with sharing class InternalPaymentWaiverSubmissionHelper extends GNT.DynamicLayoutActionRedirect{
    
    global override PageReference whenClicked(){
        Savepoint sp = Database.setSavepoint();
        List<String> errors = new List<String>();
        try{
                Id recordId = apexpages.currentpage().getparameters().get('id');
                PaymentRequest__c paymentreq = [SELECT Id,Award__c,Status__c,Name,Title__c,Applicant__c,Approver__c FROM PaymentRequest__c WHERE Id =: recordId LIMIT 1];
                
                if(paymentreq.Approver__c == null){
                    errors.add('Assign an Internal Approver');
                }
                
                if(errors.size() > 0){
                  for(String error: errors){
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, error));
                  } 
                } else{
	                GNT.TaskCreationHandler.createApprovalProcessTasks(paymentreq.Id, 'Recipient Review Payment Waiver', paymentreq.Name, null, System.TODAY() + 7, paymentreq.Title__c, true); 
	                
	                List<Task> taskList = [SELECT WhatId,Status,OwnerId FROM Task where WhatId=:paymentreq.Id and Status IN ('In Progress', 'Not Started')];
	                if (!taskList.isEmpty()) {
	                    for (Task t : taskList) {
	                        if (t.OwnerId == paymentreq.Applicant__c) {
	                            t.Status = 'Completed';
	                        }
	                    }
	                    update taskList;
	                }
	                PageReference p = Page.PaymentRequestView;
	                p.getParameters().put('id', paymentreq.Id);
	                p.setRedirect(true);
	                return p;
                }
                return null;
        }catch(Exception e){
            Database.rollback(sp);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            return null;
        }
    }
}