UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent to Grantee Review</fullName>
                </value>
                <value>
                    <fullName>Grantee Accepted</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>FINOPS Completed</fullName>
                </value>
                <value>
                    <fullName>Sent to FINOPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BusinessPackage__c.object
<CustomObject>
    <description>[Business]  This object associates the Package with the Program or Opportunity</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>BusinessPackages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Grants</description>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PackageConfig__c</fullName>
        <label>Package Config</label>
        <referenceTo>GNT__Package__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PackageType__c</fullName>
        <label>Package Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Pre-Application</fullName>
                </value>
                <value>
                    <fullName>App-Review</fullName>
                </value>
                <value>
                    <fullName>Award</fullName>
                </value>
                <value>
                    <fullName>Amendment Request</fullName>
                </value>
                <value>
                    <fullName>Progress Report</fullName>
                </value>
                <value>
                    <fullName>Site Visit</fullName>
                </value>
                <value>
                    <fullName>Payment Request</fullName>
                </value>
                <value>
                    <fullName>Closeout</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Risk Assessment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Business Package</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Closeout__c.object
<CustomObject>
    <description>[Business] All the close out information is stored on this object</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Closeouts</relationshipLabel>
        <relationshipName>Closeouts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Closeouts</relationshipLabel>
        <relationshipName>Closeouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Notified</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Notification Accepted</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closeout</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closeouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed/Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestCloseoutRequestEditCtrl.cls
@isTest
public with sharing class TestCloseoutRequestEditCtrl {
    
    @isTest
    static void editTest() {
    /*
        UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
        
        System.runAs(u) {
            AccountTriggerHelper.skipTrigger = true;
            GrantTriggerHelper.skipTrigger = true;
            Grant__c grant = TestHelper.getGrant(true);
            
            
            AwardTriggerHelper.skipTrigger = true;
            Award__c award = TestHelper.getAwards(grant.Id, true);
            award.Status__c = 'Activated';
            update award;
            
            BusinessPackage__c bp=new BusinessPackage__c();
            GNT__PageTemplate__c pt = TestHelper.getPageTemplateConfig(true);
            GNT__Package__c pack = TestHelper.getPackage(false, pt);
            pack.name='test';
            pack.GNT__SubmissionType__c = 'Application';
            pack.GNT__LatestVersion__c = true;
            pack.GNT__Status__c = 'Active';
            insert pack;
            bp.PackageConfig__c=pack.Id;
            bp.PackageType__c = 'Closeout';
            bp.Grant__c = grant.Id;
            insert bp;
            
            Closeout__c closeout = new Closeout__c();
            closeout.Grant__c = grant.Id;
            insert closeout;
            
            Test.startTest();
            ApexPages.standardController sc = new ApexPages.standardController(closeout);
            ApexPages.currentPage().getParameters().put('grantId',grant.Id);
            ApexPages.currentPage().getParameters().put('id',closeout.Id);
            CloseoutRequestEditCtrl ctrl = new CloseoutRequestEditCtrl(sc);
            ctrl.getKeyValueMap();
            Test.stopTest();
        }
        */
    }

    @isTest
    static void nullIdTest() {
    /*
        UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
        
        System.runAs(u) {
            AccountTriggerHelper.skipTrigger = true;
            GrantTriggerHelper.skipTrigger = true;
            Grant__c grant = TestHelper.getGrant(true);
            
            
            AwardTriggerHelper.skipTrigger = true;
            Award__c award = TestHelper.getAwards(grant.Id, true);
            award.Status__c = 'Activated';
            update award;
            
            BusinessPackage__c bp=new BusinessPackage__c();
            GNT__PageTemplate__c pt = TestHelper.getPageTemplateConfig(true);
            GNT__Package__c pack = TestHelper.getPackage(false, pt);
            pack.name='test';
            pack.GNT__SubmissionType__c = 'Application';
            pack.GNT__LatestVersion__c = true;
            pack.GNT__Status__c = 'Active';
            insert pack;
            bp.PackageConfig__c=pack.Id;
            bp.PackageType__c = 'Closeout';
            bp.Grant__c = grant.Id;
            insert bp;
            
            Closeout__c closeout = new Closeout__c();
            closeout.Grant__c = grant.Id;
            insert closeout;
            
            Test.startTest();
            ApexPages.standardController sc = new ApexPages.standardController(closeout);
            ApexPages.currentPage().getParameters().put('grantId',grant.Id);
            CloseoutRequestEditCtrl ctrl = new CloseoutRequestEditCtrl(sc);
            ctrl.getKeyValueMap();
            Test.stopTest();
        }
        */
    }
}