UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AwardBudgetCategory__c.object
<CustomObject>
    <description>[Business] Defines the Budget categories on the Award</description>
    <fields>
        <fullName>Award__c</fullName>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award Budget Categories</relationshipLabel>
        <relationshipName>Award_Budget_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award Budget Category</label>
    <nameField>
        <displayFormat>AC-{00}</displayFormat>
        <label>Award Budget Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Award Budget Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingSource__c.object
<CustomObject>
    <description>[Business] Details of the Funding sources which further creates Funding accounts</description>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Funding Sources</relationshipLabel>
        <relationshipName>Funding_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <recordTypes>
        <fullName>External</fullName>
        <active>true</active>
        <description>This is used in Grantee side of Applicaion</description>
        <label>External</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingSourceBudgetCategory__c.object
<CustomObject>
    <description>[Business] This is junction object for Funding Sources and Budget Categories</description>
    <fields>
        <fullName>AwardBudgetCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award Budget Category</label>
        <referenceTo>AwardBudgetCategory__c</referenceTo>
        <relationshipLabel>Funding Source Budget Category</relationshipLabel>
        <relationshipName>Funding_Source_Budget_Category</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FundingSource__c</fullName>
        <label>Funding Source</label>
        <referenceTo>FundingSource__c</referenceTo>
        <relationshipLabel>Funding Source Budget Category</relationshipLabel>
        <relationshipName>Funding_Source_Budget_Category</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TotalAmountAllocated__c</fullName>
        <description>Amount which is allocated to each line item on Award Level( Populated through Trigger)</description>
        <label>Awarded Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Funding Source Budget Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Source Budget Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestFundingSourceBudCatTriggerHelper.cls
@isTest
public class TestFundingSourceBudCatTriggerHelper {

    static TestMethod void testTrigger(){
        
        FundingSourceBudgetCategory__c fundSrcCatBud = null;
        FundingSourceBudgetCategory__C fundSrcCatBud2=null;
        FundingSource__c fsource = null;
        UserTriggerHelper.skipTrigger = true; 
        User u = TestHelper.getAdminUser(true);
        
        System.runAs(u){
            fsource=TestHelper.getFundingSource(true);
            fundSrcCatBud = new FundingSourceBudgetCategory__c(FundingSource__c=fsource.Id);
            insert fundSrcCatBud;
            fundSrcCatBud.TotalAmountAllocated__c=0;
            update fundSrcCatBud;
            delete fundSrcCatBud;
        }
    }
    
    static TestMethod void testTrigger2(){
        FundingSourceBudgetCategory__c fundSrcBudCat = null;
        FundingSource__c fsource = null;
        Grant__c grants = null;
        Award__c award = null;
        UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
        
        System.runAs(u){
        
            GrantTriggerHelper.skipTrigger=true;
            AwardTriggerHelper.skipTrigger=true;
            
            fsource=TestHelper.getFundingSource(true);
          //  fsource.RecordType.DeveloperName='External';
            update fsource;
            
            grants = TestHelper.getGrant(true);
            award = TestHelper.getAwards(grants.Id,true);
            
            AwardBudgetCategory__c awardbudCat = new AwardBudgetCategory__c();
            awardbudCat.Award__c=award.Id;
            insert awardbudCat;
            
            fundSrcBudCat = new FundingSourceBudgetCategory__c(FundingSource__c=fsource.Id);
            insert fundSrcBudCat;
            fundSrcBudCat.TotalAmountAllocated__c=5000;
            fundSrcBudCat.AwardBudgetCategory__c = awardbudCat.Id;
            update fundSrcBudCat;
           
        }
        
    }
}