UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>InternalOrganization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Grants (Internal Organization)</relationshipLabel>
        <relationshipName>Grants1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/AwardInternalApproverEditCtrl.cls
public with sharing class AwardInternalApproverEditCtrl{
    public ID recordId{get;set;}
    public PageReference savePage {get;set;}
    public PageReference cancelPage {get;set;}
    public String pageTemplateName {get;set;}
    public List<GNT.DynamicLayoutDefaultValueHelper> listDefaultValues {get;set;}
    
    Award__c awd;
    public AwardInternalApproverEditCtrl(ApexPages.StandardController stdController){
        recordId = ApexPages.CurrentPage().getParameters().get('id');     
        awd = [SELECT Id, Grant__c, Grant__r.InternalOrganization__c FROM Award__c WHERE Id=:recordId]; 
         
        savePage = Page.AwardView;
        savePage.getParameters().put('id', recordId);
           
        pageTemplateName = 'AwardInternalApproverEdit';        
    }
    
    public string getKeyValueMap(){
        Map<String,String> keyValueMap = new Map<String,String>();
        keyValueMap.put('id', recordId);
        keyValueMap.put('AccountId', awd.Grant__r.InternalOrganization__c);
        return JSON.serialize(keyValueMap);
    }    
}