UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GranteePOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grantee POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awards_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent to Grantee Review</fullName>
                </value>
                <value>
                    <fullName>Grantee Accepted</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>FINOPS Completed</fullName>
                </value>
                <value>
                    <fullName>Sent to FINOPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Closeout__c.object
<CustomObject>
    <description>[Business] All the close out information is stored on this object</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Closeouts</relationshipLabel>
        <relationshipName>Closeouts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FOApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FO Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Closeouts6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Closeouts</relationshipLabel>
        <relationshipName>Closeouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GranteePOC__c</fullName>
        <formula>Grant__r.GranteePOC__r.FirstName &amp; &apos; &apos; &amp;  Grant__r.GranteePOC__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Grantee POC</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PO Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Closeouts5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Notified</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Notification Accepted</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Closeout</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closeouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>GranteePOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grantee POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Grants1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed/Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RolesAndResponsibilities__c.object
<CustomObject>
    <description>[Business] Roles and Responsibilities defined for all the objects like Opportunity ,Application etc</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closeout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closeout</label>
        <referenceTo>Closeout__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>RolesandResponsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Sent For Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Roles and Responsibilities</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles and Responsibilities</pluralLabel>
    <recordTypes>
        <fullName>Closeout</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Closeout.</description>
        <label>Closeout</label>
    </recordTypes>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Program.</description>
        <label>Program</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/CloseoutNotificationHelper.cls
global with sharing class CloseoutNotificationHelper extends GNT.DynamicLayoutActionRedirect{ 
    public  CloseoutNotificationHelper() {}
    List<String> errors = new List<String>(); 
    
    
    global override PageReference whenClicked(){
        String recordId = apexpages.currentpage().getparameters().get('id');
        Closeout__c req = [Select Id, Name, Title__c, Award__c, Grant__c,FOApprover__c, POApprover__c,Grant__r.GranteePOC__c from Closeout__c where Id=:recordId limit 1];            
        
        if(req.FOApprover__c==null ||req.POApprover__c ==null){
        // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select Program Approver and Fiscal Approver before sending a Notification')); 
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-28828')));                                 
        return null;    
        }
        notifyUsers(req);
        // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Notification has been sent to Internal Users and External Recipient/Sub-Awardee')); 
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-57777')));                                  
        PageReference pf = Page.CloseoutRequestView;
        pf.getParameters().put('id', recordId);
        pf.setRedirect(true);
        return pf;
    }    
    
      global Boolean notifyUsers(Closeout__c closeout)
      {

       If(!Test.isrunningtest()){
          List<Task> closeoutTasks = GNT.TaskCreationHandler.createTasks(closeout.Grant__r.GranteePOC__c,
                                                                        closeout.Id, 'Accept Closeout Request',
                                                                        closeout.Title__c, null, false, null,
                                                                        'Approval', closeout.Title__c, false); 


       /*  List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();    
         Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
         String[] toAddresses = new String[] {};
         EmailTemplate templateId = [Select id from EmailTemplate where developername = 'NotificationofGrantCloseoutSubmission'];
         Contact cont = [select id, Email from Contact where email <> null limit 1];
         mail.saveAsActivity = false;  
         mail.setTargetObjectId(UserInfo.getuserId());
         mail.setTemplateID(templateId.Id); 
         mails.add(mail);
         Map<Id, String[]> recIdToAddressMap = new Map<Id, String[]> ();
         for(RolesAndResponsibilities__c resp : [Select Id, Name,Name__c from RolesAndResponsibilities__c where Closeout__c =: closeout.Id]){
           toAddresses.add(resp.Name__c);
         }        
         toAddresses.add(UserInfo.getuserId());
         toAddresses.add(closeout.Grant__r.GranteePOC__c);
         recIdToAddressMap.put(closeout.Id, toAddresses);
         try{
         GNT.AppUtils.sendEmailUsingTemplate(templateId.Id, recIdToAddressMap, cont.Id, false);            
         }
         catch(Exception exc){
            system.debug(exc);
         } */
         insert closeoutTasks;
         }
         closeout.Status__c='Notified';
         update closeout;
         return false;
    
  }
}