UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>BudgetPeriodEndDate__c</fullName>
        <description>Budget Period End Date for the award.</description>
        <label>Budget Period End Date(obsolete)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BudgetPeriodStartDate__c</fullName>
        <description>Budget Period Start Date for the award.</description>
        <label>Budget Period Start Date (Obsolete)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>BudgetPeriodEndDate__c</fullName>
        <label>Current Budget Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BudgetPeriodStartDate__c</fullName>
        <label>Current Budget Period Start Date</label>
        <type>Date</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/TermCondition__c.object
<CustomObject>
    <description>[Business] Terms and Conditions for Grants ,Awards (The lookup to Package may not be required in this case )</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MST:Term and Condition</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <recordTypes>
        <fullName>Term</fullName>
        <active>true</active>
        <description>Related to Awards ( Ramu to rename this object appropriately)</description>
        <label>Term</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestNewProgressReportConditionHandler.cls
@isTest
private with sharing class TestNewProgressReportConditionHandler{
    static testMethod void testclickHandler() {
       
          User u = TestHelper.getAdminUser(true);
          System.runAs(u){
              
              GrantTriggerHelper.skipTrigger = true;
              AwardTriggerHelper.skipTrigger = true;
              AccountTriggerHelper.skipAll=true;
              
              Grant__c grant = TestHelper.getGrant(true);
              Award__c awards = TestHelper.getAwards(grant.Id,true);
              TermCondition__c termCond = TestHelper.getTermCondition(false,'Progress Report');
              termCond.Award__c= awards.Id;
              insert termCond;
              
              Test.startTest();
              NewProgressReportConditionHandler ctrl = new NewProgressReportConditionHandler();
              ctrl.urlParams.put('id',awards.Id);
              ctrl.clickHandler();
              Test.stopTest();
          }
        
    }
    
     static testMethod void testclickHandler2() {
       
          User u = TestHelper.getAdminUser(true);
          System.runAs(u){
              
              GrantTriggerHelper.skipTrigger = true;
              AwardTriggerHelper.skipTrigger = true;
              AccountTriggerHelper.skipAll=true;
              
              Grant__c grant = TestHelper.getGrant(true);
              Award__c awards = TestHelper.getAwards(grant.Id,false);
              awards.BudgetPeriodStartDate__c=Date.newInstance(2016,03,03);
              awards.BudgetPeriodEndDate__c= Date.newInstance(2016,12,12);
              insert awards;
              TermCondition__c termCond = TestHelper.getTermCondition(false,'Progress Report');
              termCond.Award__c= awards.Id;
              insert termCond;
              
              Test.startTest();
              NewProgressReportConditionHandler ctrl = new NewProgressReportConditionHandler();
              ctrl.urlParams.put('id',awards.Id);
              ctrl.clickHandler();
              Test.stopTest();
          }
        
    }
    
     static testMethod void testclickHandler3() {
       
          User u = TestHelper.getAdminUser(true);
          System.runAs(u){
              
              GrantTriggerHelper.skipTrigger = true;
              AwardTriggerHelper.skipTrigger = true;
              AccountTriggerHelper.skipAll=true;
              
              Grant__c grant = TestHelper.getGrant(true);
              Award__c awards = TestHelper.getAwards(grant.Id,false);
              awards.BudgetPeriodStartDate__c=Date.newInstance(2016,03,03);
              awards.BudgetPeriodEndDate__c= Date.newInstance(2016,12,12);
              insert awards;
              TermCondition__c termCond = TestHelper.getTermCondition(false,'Term');
              termCond.Award__c= awards.Id;
              insert termCond;
              
              Test.startTest();
              NewProgressReportConditionHandler ctrl = new NewProgressReportConditionHandler();
              ctrl.urlParams.put('id',awards.Id);
              ctrl.clickHandler();
              Test.stopTest();
          }
        
    }
}