UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>GrantAwardName__c</fullName>
        <label>Award Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/WaiveRemainingFunds.cls
global with sharing class WaiveRemainingFunds extends GNT.DynamicLayoutActionRedirect {
    global override PageReference whenClicked(){      
        String ns = AppUtils.getNamespacePrefix(); 
        List<String> errors = new List<String>();  
        Id recordId = apexpages.currentpage().getparameters().get('id');
        Award__c award = [SELECT Id FROM Award__c WHERE id =: recordId];
        GNT.TaskCreationHandler.createApprovalProcessTasks(award.Id, 'Approve Waive Remaining Funds', award.Name, null, System.TODAY() + 7, award.GrantAwardName__c, true);
        PageReference returnPage = Page.AwardView;
        returnPage.getParameters().put('Id', award.Id);
        returnPage.setRedirect(true);
        return returnPage;
    }
}