UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent to Grantee Review</fullName>
                </value>
                <value>
                    <fullName>Grantee Accepted</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>FINOPS Completed</fullName>
                </value>
                <value>
                    <fullName>Sent to FINOPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AwardFINETCode__c.object
<CustomObject>
    <fields>
        <fullName>AwardStatus__c</fullName>
        <label>Award Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award FINET Codes</relationshipLabel>
        <relationshipName>Award_FINET_Codes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award FINET Code</label>
    <nameField>
        <label>Award FINET Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award FINET Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed/Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/MSPAwardTriggerHelper.cls
global with sharing class MSPAwardTriggerHelper extends GNT.TriggerHelper{
	public override void processAfterInsert(){
		updateOtherAwardsStatus((List<Award__c>)Trigger.new);
	}

	public override void processAfterUpdate(){
		updateOtherAwardsStatus((List<Award__c>)Trigger.new);
		updateAwardFinetCodeStatus((List<Award__c>)Trigger.new);
	}

    private void updateOtherAwardsStatus(List<Award__c> awards){
        List<Award__c> activeAwardList = new List<Award__c>();
        List<Id> grantIdList = new List<Id>();
        for(Award__c award : awards){
            if(award.Status__c == 'Activated'){
                activeAwardList.add(award);
                grantIdList.add(award.Grant__c);
            }
        }

        List<Award__c> amendedAwardList = new List<Award__c>([SELECT Id, Status__c FROM Award__c WHERE Grant__c IN :grantIdList AND Id NOT IN :activeAwardList AND Status__c = 'Activated']);
        for(Award__c awd : amendedAwardList){
            awd.Status__c = 'Amended';
        }

        update amendedAwardList;
    }   
    private void updateAwardFinetCodeStatus(List<Award__c> awards){
        List<AwardFINETCode__c> afcs = [SELECT Id, Award__r.Status__c, AwardStatus__c FROM AwardFINETCode__c WHERE Award__c IN :awards];
        for(AwardFINETCode__c afc : afcs){
            afc.AwardStatus__c = afc.Award__r.Status__c;
        }
        update afcs;
    }
}