UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AwardFundingAccount__c.object
<CustomObject>
    <description>[Business] Associates all the Funding accounts with the Grant/Award</description>
    <fields>
        <fullName>Award__c</fullName>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award Funding Accounts</relationshipLabel>
        <relationshipName>Award_Funding_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FundingAccount__c</fullName>
        <label>Funding Account</label>
        <referenceTo>FundingAccount__c</referenceTo>
        <relationshipLabel>Award Funding Accounts</relationshipLabel>
        <relationshipName>Award_Funding_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award Funding Account</label>
    <nameField>
        <displayFormat>AFA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Award Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingAccount__c.object
<CustomObject>
    <description>[Business] Funding account details Funding accounts are created from Funding sources</description>
    <fields>
        <fullName>FundingSource__c</fullName>
        <label>Funding Source</label>
        <referenceTo>FundingSource__c</referenceTo>
        <relationshipLabel>Funding Accounts</relationshipLabel>
        <relationshipName>Funding_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Funding Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingSource__c.object
<CustomObject>
    <description>[Business] Details of the Funding sources which further creates Funding accounts</description>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Funding Sources</relationshipLabel>
        <relationshipName>Funding_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestAwardFundingAccountsActionHandler.cls
@isTest
private class TestAwardFundingAccountsActionHandler {

    static testMethod void myUnitTest() {
        
        GrantTriggerHelper.skipTrigger = true;
        AwardTriggerHelper.skipTrigger = true;
        FundingAccountTriggerHelper.skipTrigger = true;
        UserTriggerHelper.skipTrigger = true; 
        User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
            Grant__c grant = TestHelper.getGrant(true);
            Award__c award= TestHelper.getAwards(grant.Id,true);
            FundingSource__c fundSrc = TestHelper.getFundingSource(true);
            FundingAccount__c fundAcc = TestHelper.getFundingAccount(true,fundSrc.Id);
            AwardFundingAccount__c awdfndaccnt = new AwardFundingAccount__c(Award__c = award.id,FundingAccount__c = fundAcc.id);
            insert awdfndaccnt;
            List<String> selectedRecordIds = new List<String>();
            selectedRecordIds.add(fundAcc.id);
            ApexPages.currentPage().getParameters().put('Id', award.Id);
            PageReference p = Page.StrategicPlanView;
            Map<String,String> urlParams = new Map<String,String>();
            AwardFundingAccountsActionHandler awardfaactionhandler = new AwardFundingAccountsActionHandler();
            awardfaactionhandler.selectedRecordIds = selectedRecordIds;
            urlParams.put('awardId',award.Id);
            awardfaactionhandler.urlParams = urlParams;
            awardfaactionhandler.clickHandler();           
        }
    }
}