UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>GrantAwardName__c</fullName>
        <label>Award Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GranteePOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grantee POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awards_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent to Grantee Review</fullName>
                </value>
                <value>
                    <fullName>Grantee Accepted</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>FINOPS Completed</fullName>
                </value>
                <value>
                    <fullName>Sent to FINOPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <recordTypes>
        <fullName>Grantee</fullName>
        <active>true</active>
        <description>This Classifies whether it is Grantor or Grantee</description>
        <label>Grantee</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>GranteePOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grantee POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Grants1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InternalOrganization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Grants (Internal Organization)</relationshipLabel>
        <relationshipName>Grants1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProgramCode</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed/Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <recordTypes>
        <fullName>Grantee</fullName>
        <active>true</active>
        <label>Grantee</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/SubAwardeeReviewHelper.cls
global with sharing class SubAwardeeReviewHelper extends GNT.DynamicLayoutActionRedirect {
    global override PageReference whenClicked(){      
        String ns = AppUtils.getNamespacePrefix(); 
        List<String> errors = new List<String>();  
        Id recordId = apexpages.currentpage().getparameters().get('id');
        Award__c award = [SELECT Id,Name,CreatedbyId,Status__c,Grant__r.GranteePOC__c,Grant__r.Id,GrantAwardName__c,
                          Grant__r.InternalOrganization__r.status__c, Grant__r.Program__r.AwardLetterRequired__c
                          FROM Award__c WHERE id =: recordId];
        if (award.Status__c == 'Approved'){
            if(award.Grant__r.InternalOrganization__r.status__c !='Debarred'){
                    award.Status__c = 'Sent to Grantee Review';
                    update award;
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Sent to Sub-Awardee Review'));
                    //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('P26-GRNTR-82257')));
                    //GNT.TaskCreationHandler.createTasks(award.Grant__r.GranteePOC__c, recordId, 'Grantee POC Award Review',award.Name, null, false, System.TODAY() + 7, null, true); 
                    GNT.TaskCreationHandler.createTasks(award.Grant__r.GranteePOC__c, recordId, 'Grantee POC Award Review',award.Name, null, false, System.TODAY() + 7, null, award.GrantAwardName__c, true); 
                    system.debug('record id is ' +recordId + ' and GranteePOC is ' +award.Grant__r.GranteePOC__c);
                    //new GNT.EmailFeeder().TargetObjectID(award.Grant__r.GranteePOC__c).template('AwardReadyForApprovalSub').contextRecordId(recordId).send();
                    PageReference  returnPage = Page.AwardView;
                    returnPage.getParameters().put('Id', award.Id);
                    returnPage.setRedirect(true);
                    return returnPage;
            }else{
                  //errors.add ('The award cannot be sent for Grantee Review as for this Grantee Organization debarment process has been initiated');
                  errors.add (GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-57029'));
            }
       
        }
        if (award.Status__c == 'Sent to Grantee Review'){
            if(award.Grant__r.InternalOrganization__r.status__c !='Debarred'){
                award.Status__c = 'Grantee Accepted';
                update award;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Award Accepted'));
                // Sai Teja - To change the status of the task to completed so it wont show up in sub recp pending tasks anymore; after he accepts the award.
                List<Task> taskList = [Select Id, Status, WhatId,lastModifieddate from Task where WhatId = :award.Id AND OwnerId=:award.Grant__r.GranteePOC__c AND Status='In Progress'];
                if(taskList!=null && taskList.size()>0){
                    for(Task task : taskList){
                        task.Status='Completed';
                    }
                    update taskList;
                }
                //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('P26-GRNTR-12611')));
                //GNT.TaskCreationHandler.createTasks(award.CreatedbyId, recordId, 'Accepted Award Review',award.Name, null, false, System.TODAY() + 7, null, true);
                GNT.TaskCreationHandler.createTasks(award.CreatedbyId, recordId, 'Accepted Award Review',award.Name, null, false, System.TODAY() + 7, null, award.GrantAwardName__c, true);
                PageReference  returnPage = Page.AwardView;
                returnPage.getParameters().put('Id', award.Id);
                returnPage.setRedirect(true);
                return returnPage;
        }else{
            //errors.add ('The award cannot be accepted as for this Grantee Organization debarment process has been initiated');
            errors.add (GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-88866'));
        }

        }
        if (award.Status__c == 'Grantee Accepted'){
        if(award.Grant__r.InternalOrganization__r.status__c !='Debarred'){
                award.Status__c = 'Activated';
                update award;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Award Activated'));
                system.debug('Grantee poc is '+award.Grant__r.GranteePOC__c);
                //new GNT.EmailFeeder().TargetObjectID(award.Grant__r.GranteePOC__c).template('AwardActivated').contextRecordId(recordId).send();
                if (award.Grant__r.Program__r.AwardLetterRequired__c == 'Yes') {
                    System.debug('AwardLetterRequired: ' + award.Grant__r.Program__r.AwardLetterRequired__c);
                    //new GNT.EmailFeeder().TargetObjectID(award.Grant__r.GranteePOC__c).template('AwardActivated').contextRecordId(recordId).send();
                }
                //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('P26-GRNTR-12611')));  
                PageReference  returnPage = Page.AwardView;
                returnPage.getParameters().put('Id', award.Id);
                returnPage.setRedirect(true);
                return returnPage;
        }else{
                //errors.add ('The award cannot be activated as for this Grantee Organization debarment process has been initiated');
                errors.add (GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-88866'));
        }

        }
        PageReference  returnPage = Page.AwardView;
        returnPage.getParameters().put('Id', award.Id);
        returnPage.setRedirect(true);
        return returnPage;
        
    }
}