UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Deliverable__c.object
<CustomObject>
    <description>[Business] Deliverable for a Grant/Award</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Deliverables</relationshipLabel>
        <relationshipName>Deliverables</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deliverable</label>
    <nameField>
        <displayFormat>DEL-{0000}</displayFormat>
        <label>Deliverable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliverables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/GoalObjective__c.object
<CustomObject>
    <description>Goals and Objectives object for Performance management</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Award to which the Goal is associated</description>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Goals_and_Objectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Goal Objective</label>
    <nameField>
        <displayFormat>GOB-{0000}</displayFormat>
        <label>Goals and Objectives Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PerformanceMeasure__c.object
<CustomObject>
    <description>Performance Measure as part of Performance Management</description>
    <fields>
        <fullName>Deliverable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deliverable</label>
        <referenceTo>Deliverable__c</referenceTo>
        <relationshipLabel>Performance Measures</relationshipLabel>
        <relationshipName>Performance_Measures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI</label>
        <referenceTo>KeyOutcome__c</referenceTo>
        <relationshipLabel>Performance Measures</relationshipLabel>
        <relationshipName>Performance_Measures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Objective__c</fullName>
        <label>Goal and Objective</label>
        <referenceTo>GoalObjective__c</referenceTo>
        <relationshipLabel>Performance Measures</relationshipLabel>
        <relationshipName>Performance_Measures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReportingRequirement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MST:Term and Condition</label>
        <referenceTo>TermCondition__c</referenceTo>
        <relationshipLabel>Performance Measures</relationshipLabel>
        <relationshipName>Performance_Measures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WBSTask__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WBS Task</label>
        <referenceTo>WBSTaskSchedule__c</referenceTo>
        <relationshipLabel>Performance Measures</relationshipLabel>
        <relationshipName>Performance_Measures</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Performance Measure</label>
    <nameField>
        <displayFormat>PMM-{0000}</displayFormat>
        <label>Performance Measure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performance Measures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/PerformanceMeasureViewCtrl.cls
public with sharing class PerformanceMeasureViewCtrl {
    //Properties
    public ID recordId{get;set;}
    public PageReference deleteURL{get;set;}
    private String awardId;
    public String pageTemplateName {get;set;}
    
    public PerformanceMeasureViewCtrl (ApexPages.StandardController stdController){
        recordId = ApexPages.CurrentPage().getParameters().get('id'); 
        String type= ApexPages.CurrentPage().getParameters().get('type'); 
        PerformanceMeasure__c perfMeasure = [Select Id, Name, Objective__r.Award__c,KPI__c,Deliverable__c,ReportingRequirement__c,WBSTask__c from PerformanceMeasure__c where Id=:recordId];
        awardId=perfMeasure.Objective__r.Award__c;          
        pageTemplateName='PerformanceMeasure KPI';   
        if(perfMeasure.KPI__c!=null){
          pageTemplateName='PerformanceMeasure KPI';   
        }else if(perfMeasure.Deliverable__c!=null){
          pageTemplateName='PerformanceMeasure Deliverable';   
        }else if(perfMeasure.ReportingRequirement__c!=null){
          pageTemplateName='PerformanceMeasure Reporting Requirement';   
        }else if(perfMeasure.WBSTask__c!=null){
          pageTemplateName='PerformanceMeasure WBSTask';   
        }           
    } 
    
    public string getKeyValueMap(){
        Map<String,String> keyValueMap = new Map<String,String>();
        keyValueMap.put('awardId',awardId);        
        return JSON.serialize(keyValueMap);
    }

}