UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Final Approver for the Award</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awards4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AwardedAmount__c</fullName>
        <formula>ObligatedAwardAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Awarded Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BudgetRevisionInitiatedByUSBE__c</fullName>
        <label>BudgetRevisionInitiatedByUSBE</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated By USBE</fullName>
                    <default>true</default>
                    <label>Not Initiated By USBE</label>
                </value>
                <value>
                    <fullName>Indirect Change</fullName>
                </value>
                <value>
                    <fullName>Allocation Change</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BudgetRevisionInitiated__c</fullName>
        <label>BudgetRevisionInitiated</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CurrentAllocatedAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>CurrentAllocatedAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CurrentRevisionStatus__c</fullName>
        <defaultValue>&quot;Not Started&quot;</defaultValue>
        <label>CurrentRevisionStatus</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WaiveAllocationStatus__c</fullName>
        <label>WaiveAllocationStatus</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                    <default>true</default>
                    <label>N/A</label>
                </value>
                <value>
                    <fullName>Sent For Internal Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Sent For Internal Acceptance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>UserReference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This filed will hold information of the User object to which it is referenced. A batch job will then use this field information to map its corresponding User</description>
        <label>UserReference</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/GrantContact__c.object
<CustomObject>
    <description>[Business]  Stores all the information related toe the Award Contact</description>
    <fields>
        <fullName>Award__c</fullName>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Grant_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Grant_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award Contact</label>
    <nameField>
        <displayFormat>GC-{0000}</displayFormat>
        <label>Grant Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ReviseBudgetForAllocationChange.cls
global with sharing class ReviseBudgetForAllocationChange extends GNT.DynamicLayoutActionRedirect{
    global override PageReference whenClicked() {
        Savepoint sp = Database.setSavePoint();
        Id awardId = layoutHolder.getPrimarySObject().Id;       
        
        try {
            Award__c currentAward = [
                SELECT Id, Name, Approver__c, AwardedAmount__c 
                FROM Award__c 
                WHERE Id =: awardId];
            if (currentAward.Approver__c != null) {
                //currentAward.CurrentAllocatedAmount__c = currentAward.AwardedAmount__c;
                currentAward.WaiveAllocationStatus__c = 'Sent For Internal Acceptance';
                USBEAwardTriggerHelper.skipTrigger = true;
                USBEAwardTriggerHelper.skipTriggers = true;
                update currentAward;
                USBEAwardTriggerHelper.skipTrigger = false;
                USBEAwardTriggerHelper.skipTriggers = false;
                
                //List<Task> taskList = [SELECT Id, Status, WhatId, GNT__TaskAction__c FROM Task WHERE WhatId =: awardId AND Status='In Progress' AND GNT__TaskAction__c = 'Accept Or Waive Allocation Amount'];
                List<Task> taskList = [SELECT Id, Status, WhatId, GNT__TaskAction__c FROM Task WHERE WhatId =: awardId AND GNT__TaskAction__c = 'Accept Or Waive Allocation Amount'];
                if(taskList != null && taskList.size()>0){
                    for(Task task: taskList){
                        task.Status='Completed';
                    }                   
                    update taskList;
                }
                
                //Create internal approval process task (which automatically has the email functionality in place)
                System.debug('Internal approval task creation');
                GNT.TaskCreationHandler.createApprovalProcessTasks(currentAward.Id, 'Accept Award Allocation Update Internal Approval', currentAward.Name, null, System.TODAY() + 7, currentAward.Name, true); 
                System.debug('***Task successfully sent ***');              
    
                //Redirect to the AwardView page
                PageReference pf = Page.ApproveRejectAwardAllocationChange;
                pf.getParameters().put('id', awardId);
                pf.setRedirect(true);
                return pf;
            }
            else {
                System.debug('You need to assign an internal approver to the award');
                return null;            
            }
        }
        /*
        try {
            //They have accepted the allocation change, so close the task that told them to do so or waive it
            //List<Task> taskList = [SELECT Id, Status, WhatId, GNT__TaskAction__c FROM Task WHERE WhatId =: awardId AND Status='In Progress' AND GNT__TaskAction__c = 'Accept Or Waive Allocation Amount'];
            List<Task> taskList = [SELECT Id, Status, WhatId, GNT__TaskAction__c FROM Task WHERE WhatId =: awardId AND GNT__TaskAction__c = 'Accept Or Waive Allocation Amount'];
            if(taskList != null && taskList.size()>0){
                for(Task task: taskList){
                    task.Status='Completed';
                }                   
                update taskList;
            }
            
            List<GrantContact__c> grantContactList = [
                SELECT Id, Award__c, Contact__c, Contact__r.UserReference__c, Contact__r.Email 
                FROM GrantContact__c
                WHERE Award__c =: awardId AND Contact__r.UserReference__c != null];
            System.debug('MANUALDEBUG >>> grantContactList: ' + grantContactList);
            List<Id> contactIdList = new List<Id>();
            Map<Id, Id> awardMapContact = new Map<Id, Id>();
            List<String> mailTo;
            Map<Id, String[]> recIdMapEmail;
            Map<Id, Map<Id, String[]>> awardIdMapRecIdMapEmail = new Map<Id,Map<Id, String[]>>();
            //Map<Id, Email> contactMapEmail = new Map<Id, Email>();
            System.debug('>>> ' + grantContactList.size());
            for (GrantContact__c grantContactIterator : grantContactList) {
                System.debug('MANUALDEBUG >>> ' + grantContactIterator.Contact__r.UserReference__c);
                System.debug('MANUALDEBUG >>> gcia: ' + grantContactIterator.Award__c + ' gci: ' + grantContactIterator.Contact__c);
                contactIdList.add(grantContactIterator.Contact__c);
                awardMapContact.put(grantContactIterator.Award__c, grantContactIterator.Contact__c); //Maps the AwardId to the ContactId
                //contactMapEmail.put(grantContactIterator.Contact__c, grantContactIterator.Contact__r.Email);
                mailTo = new List<String>();
                mailTo.add(grantContactIterator.Contact__r.Email);
                recIdMapEmail = new Map<Id, String[]>();
                recIdMapEmail.put(grantContactIterator.Award__c, mailTo);
                awardIdMapRecIdMapEmail.put(grantContactIterator.Award__c, recIdMapEmail);
            }
            System.debug('MANUALDEBUG >>> awardMapContact: ' + awardMapContact + ' size ' + awardMapContact.size());
            
            //List<Contact> contactList = [SELECT Id, UserReference__c, OwnerId FROM Contact WHERE Id IN: contactIdList];
            List<User> userList = [
                SELECT Id, ContactId 
                FROM User 
                WHERE ContactId IN: contactIdList];
            Map<Id, Id> contactMapUser = new Map<Id, Id>(); //Map User to Contact
            for (User userIterator : userList) {
                contactMapUser.put(userIterator.ContactId, userIterator.Id);
            }
            System.debug('MANUALDEBUG >>> contactMapUser: ' + contactMapUser);
            
           
            List<Task> budgetRevisionTaskList = new List<Task>();
            EmailTemplate emailTemplate = [
                SELECT Id, Name 
                FROM EmailTemplate 
                WHERE Name = 'Award ready for subrecipient approval' LIMIT 1];
            
            Award__c currentAward = [SELECT Id FROM Award__c WHERE Id =: awardId];
            currentAward.BudgetRevisionInitiated__c = 'In Progress';//Automatically initiate revision for the awards
            currentAward.BudgetRevisionInitiatedByUSBE__c = 'Allocation Change';
            currentAward.CurrentRevisionStatus__c = 'Created';
            //Create task and email to modify the budget
            for (GrantContact__c grantContactIterator : grantContactList) {
                List<Task> budgetRevisionTask = GNT.TaskCreationHandler.createTasks(contactMapUser.get(awardMapContact.get(currentAward.Id)), currentAward.Id, 'Complete Budget Revision', currentAward.Name, null, false, System.TODAY() + 7, 'Other', currentAward.Name, false);
                System.debug('MANUALDEBUG >>> budgetRevisionTask: ' + budgetRevisionTask);
                System.debug('MANUALDEBUG >>> ' + contactMapUser.get(awardMapContact.get(currentAward.Id)));
                budgetRevisionTaskList.addAll(budgetRevisionTask);
                
                Id currentContact = awardMapContact.get(currentAward.Id);
                AppUtils.sendEmailUsingTemplate(emailTemplate.Id, awardIdMapRecIdMapEmail.get(currentAward.Id), currentContact, false);
                System.debug('MANUALDEBUG >>> emailTemplateId, awardIdMapRecIdMapEmail, currentContactId: ' + emailTemplate.Id + ', ' + awardIdMapRecIdMapEmail.get(currentAward.Id) + ', ' + currentContact);                          
            }
            if (!budgetRevisionTaskList.isEmpty()) { insert budgetRevisionTaskList; } //Creates tasks for the grant contacts
            USBEAwardTriggerHelper.skipTrigger = true;
            USBEAwardTriggerHelper.skipTriggers = true;
            update currentAward;
            USBEAwardTriggerHelper.skipTrigger = false;
            USBEAwardTriggerHelper.skipTriggers = false;
            
            //Redirect to the award view page
            PageReference pf = Page.AwardView;
            pf.getParameters().put('id', awardId);
            pf.setRedirect(true);
            return pf;
        }
        */
        catch (Exception e) {
            Database.rollback(sp);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, e.getMessage())); 
            return null;
        }
    }
}