UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>AwardType__c</fullName>
        <description>From App = New / Supplemental / Renewal
From Progress Report = Non-Competing Continuation
From Amendment Request = Administrative
From Grant = All Others</description>
        <inlineHelpText>Type of Award</inlineHelpText>
        <label>Award Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Continuation</fullName>
                </value>
                <value>
                    <fullName>Close Out/Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AwardedAmountthisAction__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Awarded Amount this Action</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BudgetPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Period</label>
        <referenceTo>BudgetPeriod__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FederalGrantAwardIdFAIN__c</fullName>
        <inlineHelpText>This is Federal Award Identification Number.</inlineHelpText>
        <label>Federal Grant Award Id (FAIN)</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GrantAwardName__c</fullName>
        <label>Award Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GranteePOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grantee POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awards_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodStartDate__c</fullName>
        <description>Project Period Start Date for the award.</description>
        <label>Project Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TotalObligateAmount__c</fullName>
        <label>Total Obligated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Stores the award amendment</description>
        <formula>if (AmendmentSequence__c==0,&apos;NEW&apos;,&apos;Amendment&apos;+TEXT(AmendmentSequence__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <recordTypes>
        <fullName>Grantee</fullName>
        <active>true</active>
        <description>This Classifies whether it is Grantor or Grantee</description>
        <label>Grantee</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AwardBudgetCategory__c.object
<CustomObject>
    <description>[Business] Defines the Budget categories on the Award</description>
    <fields>
        <fullName>Award__c</fullName>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award Budget Categories</relationshipLabel>
        <relationshipName>Award_Budget_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BudgetPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Period</label>
        <referenceTo>BudgetPeriod__c</referenceTo>
        <relationshipLabel>Award Budget Categories</relationshipLabel>
        <relationshipName>Award_Budget_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT(BudgetCategory__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Award Budget Category</label>
    <nameField>
        <displayFormat>AC-{00}</displayFormat>
        <label>Award Budget Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Award Budget Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BudgetCategory__c.object
<CustomObject>
    <description>[Business] This object stores the Master List of all the Budget categories</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Personnel</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Occupancy</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Supplies</fullName>
                </value>
                <value>
                    <fullName>Publication</fullName>
                </value>
                <value>
                    <fullName>IDC</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Fringe Benefits</fullName>
                </value>
                <value>
                    <fullName>Contracted Fees</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MST: Budget Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Category</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BudgetPeriod__c.object
<CustomObject>
    <description>[Business] This object stores all Budget Period Details.</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Budget Periods</relationshipLabel>
        <relationshipName>Budget_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BudgetPeriod__c</fullName>
        <formula>IF(AND(NOT(ISBLANK(BudgetStartDate__c )),NOT(ISBLANK(BudgetEndDate__c))),TEXT(MONTH( BudgetStartDate__c ))+&quot;/&quot; +TEXT(DAY(BudgetStartDate__c))+&quot;/&quot; +TEXT(YEAR(BudgetStartDate__c))+&quot;--&quot;+ TEXT(MONTH( BudgetEndDate__c ))+&quot;/&quot; +TEXT(DAY(BudgetEndDate__c))+&quot;/&quot; +TEXT(YEAR(BudgetEndDate__c)),&apos;&apos;)</formula>
        <label>Budget Period</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Budget Periods</relationshipLabel>
        <relationshipName>Budget_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget Period</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Budget Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingAccount__c.object
<CustomObject>
    <description>[Business] Funding account details Funding accounts are created from Funding sources</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Funding Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingSource__c.object
<CustomObject>
    <description>[Business] Details of the Funding sources which further creates Funding accounts</description>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Funding Sources</relationshipLabel>
        <relationshipName>Funding_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Funder Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Federal</fullName>
                    <default>true</default>
                    <label>Federal</label>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>NGO</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>AwardedAmountthisAction__c</fullName>
        <label>Awarded Amount this Action</label>
        <summarizedField>Award__c.AwardedAmountthisAction__c</summarizedField>
        <summaryForeignKey>Award__c.Grant__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>BudgetPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Period</label>
        <referenceTo>BudgetPeriod__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GranteePOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grantee POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Grants1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodStartDate__c</fullName>
        <label>Project Period Start Date</label>
        <type>Date</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <recordTypes>
        <fullName>Grantee</fullName>
        <active>true</active>
        <label>Grantee</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RolesAndResponsibilities__c.object
<CustomObject>
    <description>[Business] Roles and Responsibilities defined for all the objects like Opportunity ,Application etc</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>Roles_and_Responsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BusinessRole__c</fullName>
        <description>This is a picklist which will be displayed in RR table in all phases.</description>
        <label>Business Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BusinessRole</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>RolesandResponsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Roles and Responsibilities</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles and Responsibilities</pluralLabel>
    <recordTypes>
        <fullName>Award</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Award.</description>
        <label>Award</label>
    </recordTypes>
    <recordTypes>
        <fullName>Grant</fullName>
        <active>true</active>
        <label>Grant</label>
    </recordTypes>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <description>This record type can be used for Roles and Responsibilities on Grantee Program.</description>
        <label>Program</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/SpendPlan__c.object
<CustomObject>
    <description>[Business]  Spend Plan is how the dollars are spend. Is it Sub Award,Internal Spend, ISA and Contracts.</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Spend Plans</relationshipLabel>
        <relationshipName>Spend_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Spend Plan</label>
    <nameField>
        <displayFormat>SPLN-{0000}</displayFormat>
        <label>Spend Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spend Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestFundingSourceTriggerHelper.cls
/**
* Copyright REI Systems 2014 - 2016 
* Test Class for FundingSourceTriggerHelper
* Negative test case -  
* Positive test case - 
* @author smahavratayajula 
*/
@isTest
public class TestFundingSourceTriggerHelper {
    
    static testMethod void populateReferenceNo() {
        Grant__c grants =null;
        UserTriggerHelper.skipTrigger = true; 
        User u = TestHelper.getAdminUser(true);
        system.debug('***Entering test coverage***');
        
        System.runAs(u){
            //GNT.TriggerHelper.skipTrigger=true;
            RolesAndResponsibilitiesTriggerHelper.skipTrigger=true;
            GrantTriggerHelper.skipTrigger=true;
            AwardTriggerHelper.skipTrigger=true;
            
            grants = TestHelper.getGrant(true);
            /*
            grants.recordTypeId = TestHelper.getRecordType(Schema.SObjectType.Grant__c, 'Grantee');
            grants.GranteePOC__c = u.Id;
            grants.Name='abcd';
            grants.ProjectPeriodStartDate__c=System.today();
            system.debug('***Trying to insert grant***');
            insert grants;
            system.debug('Grant Id : ' + grants.Id);
            
            BudgetPeriod__c budgetPeriod = new BudgetPeriod__c();
            budgetPeriod.Name = 'Test budget period name';
            insert budgetPeriod;
            
            System.debug('Budget period id : ' + budgetPeriod);
            
            Award__c award = new Award__c();
            award.Grant__c = grants.Id;
            award.GrantAwardName__c = 'Test title';
            award.FederalGrantAwardIdFAIN__c = 'test federal grant';
            award.BudgetPeriod__c = budgetPeriod.Id; 
            award.AwardType__c = 'New';
            award.TotalObligateAmount__c = 1000;
            // validation rule - AwardedAmountthisAction__c < TotalObligateAmount__c
            award.AwardedAmountthisAction__c = 100;
            insert award;*/
            
           /* RolesAndResponsibilities__c rolesAndResponsibilities = new RolesAndResponsibilities__c(Award__c = award.Id,
                                                                           BusinessRole__c='Program Approver');
            insert rolesAndResponsibilities;*/
            
           /* AwardBudgetCategory__c awardBudgetCategory = new AwardBudgetCategory__c();
            awardBudgetCategory.Award__c = award.Id;
            insert awardBudgetCategory;*/
            
         //   System.debug('Award budget category id : ' + awardBudgetCategory);
            
           /* FundingSource__c fsource = new FundingSource__c();
            fsource.Grant__c = grants.Id;
            fsource.SpendPlan__c = 'Awards';
            fsource.Title__c = 'Test Funding source';
            //fsource.StartDate__c = System.today() + 1 ;
            //fsource.EndDate__c = System.today() + 30;
            insert fsource;*/
            
            
            
            Award__c award = TestHelper.getAwards(grants.Id,true);
            award.IndirectCostRateDecision__c='Explicit';
            update award;
            
            AwardBudgetCategory__c awardbudCat = new AwardBudgetCategory__c();
            awardbudCat.Award__c=award.Id;
            insert awardbudCat;
            
            grants.LatestAwardId__c = award.Id;
            update grants;
          
            
            FundingSource__c fsource = new FundingSource__c(OrganizationName__c ='TestOrganization'+System.today(), FundingSourceID__c=''+System.today(), 
                    Type__c='State', Status__c = 'Active');
            fsource.Grant__c = grants.Id;
            fsource.Type__c='Federal';
            fsource.SpendPlan__c = 'Awards';
            fsource.Title__c = 'Test Funding source';
            fsource.StartDate__c = System.today() + 1 ;
            fsource.EndDate__c = System.today() + 30;
            fsource.Name='Fund1';
            insert fsource;
            
            FundingSource__c fsource2= new FundingSource__c();
            insert fsource2;
            delete fsource2;
           
            system.debug('FSource Grant ID:'+fsource.Grant__c);
            FundingAccount__c fundAcc = TestHelper.getFundingAccount(true,fsource.Id);
            
           // system.debug('Funding Source : ' + fsource.Id);
       }
             
    }
    
    /*static testMethod void someTest2() {
        Grant__c grants =null;
        User u = TestHelper.getAdminUser(true);
        system.debug('***Entering test coverage***');
        
        System.runAs(u){
            //GNT.TriggerHelper.skipTrigger=true;
            RolesAndResponsibilitiesTriggerHelper.skipTrigger=true;
            GrantTriggerHelper.skipTrigger=true;
            AwardTriggerHelper.skipTrigger=true;
            
            grants = TestHelper.getGrant(true);
            
            Award__c award = TestHelper.getAwards(grants.Id,true);
            award.IndirectCostRateDecision__c='Implicit';
            award.ApprovedIndirectCostRate__c=2.1;
            update award;
            
            BudgetCategory__c budCategory = new BudgetCategory__c();
            insert budCategory;
            
            AwardBudgetCategory__c awardbudCat = new AwardBudgetCategory__c();
            awardbudCat.Award__c=award.Id;
            awardbudCat.BudgetCategory__c=budCategory.Id;
            awardbudCat.Amount1__c= 5000;
            insert awardbudCat;
            
            grants.LatestAwardId__c = award.Id;
            update grants;
            
          
            
            FundingSource__c fsource = new FundingSource__c(OrganizationName__c ='TestOrganization'+System.today(), FundingSourceID__c=''+System.today(), 
                    Type__c='State', Status__c = 'Active');
            fsource.Grant__c = grants.Id;
            fsource.Type__c='Federal';
            fsource.SpendPlan__c = 'Awards';
            fsource.Title__c = 'Test Funding source';
            fsource.StartDate__c = System.today() + 1 ;
            fsource.EndDate__c = System.today() + 30;
            fsource.Name='Fund1';
            insert fsource;
            
            FundingAccount__c fundAcc = TestHelper.getFundingAccount(true,fsource.Id);
            
            FundingSourceBudgetCategory__c fundsrcbudCat = new FundingSourceBudgetCategory__c();
            fundsrcbudCat.FundingSource__c= fsource.Id;
            fundsrcbudCat.BudgetCategory__c=budCategory.Id;
            insert fundsrcbudCat;
            
            
      }      
             
    }*/
    
    
}