UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AwardBudgetCategory__c.object
<CustomObject>
    <description>[Business] Defines the Budget categories on the Award</description>
    <fields>
        <fullName>Award__c</fullName>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award Budget Categories</relationshipLabel>
        <relationshipName>Award_Budget_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award Budget Category</label>
    <nameField>
        <displayFormat>AC-{00}</displayFormat>
        <label>Award Budget Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Award Budget Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/DeleteBudgetCategoriesActionHandler.cls
global with sharing class DeleteBudgetCategoriesActionHandler extends GNT.FlexTableActionHandler{

  global override Map<String,Object> clickHandler(){
    Map<String,Object> resultMap = new Map<String,Object>();
    ID parentId = urlParams.get('parentid');   
    String parentObjName = parentId.getSObjectType().getDescribe().getName();
    parentObjName = GNT.AppUtils.removeNamespacePrefix(parentObjName);
      
     List<AwardBudgetCategory__c> objs = new List<AwardBudgetCategory__c>();
     if(selectedRecordIds != null && !selectedRecordIds.isEmpty()){
    
       for(Id recordId: selectedRecordIds){
         AwardBudgetCategory__c obj = new AwardBudgetCategory__c();
        if(parentObjName == 'Award__c'){
           obj.id = recordId;
           //obj.Award__c = parentId;
        }
         objs.add(obj);
       }
      delete(objs);
      
      if(parentObjName == 'Award__c'){
        resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-79709'));
        //resultMap.put('Message','Budget Categories deleted succesfully.');
      } 
      
     }else{
       resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-58429'));
       //resultMap.put('Message','No records are selected.');
     }
    
    return resultMap;  
  }
  
}