UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ProgramFundingAccount__c.object
<CustomObject>
    <description>[Business] Junction object between Funding Account and Program</description>
    <fields>
        <fullName>LatestActiveAward__c</fullName>
        <description>This field holds ID for latest award for funding account -&gt; funding source-&gt;grant</description>
        <formula>FundingAccount__r.FundingSource__r.Grant__r.LatestAwardId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Latest Active Award</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Funding Accounts</relationshipLabel>
        <relationshipName>Program_Funding_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Funding Account</label>
    <nameField>
        <displayFormat>PFA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/TermCondition__c.object
<CustomObject>
    <description>[Business] Terms and Conditions for Grants ,Awards (The lookup to Package may not be required in this case )</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CopiedFrom__c</fullName>
        <description>ID value of field from where Term &amp;  Condition Record is created</description>
        <label>Copied From</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MST:Term and Condition</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <recordTypes>
        <fullName>Term</fullName>
        <active>true</active>
        <description>Related to Awards ( Ramu to rename this object appropriately)</description>
        <label>Term</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/SelectTermRecordsPopUpCtrl.cls
public with sharing class SelectTermRecordsPopUpCtrl{
    
    public String templateName{get;set;}
    private String reqType;
    private Map<Id,TermCondition__c> termConditionMap;

    public SelectTermRecordsPopUpCtrl(){
        templateName = ApexPages.CurrentPage().getParameters().get('flextable');
        Id parentId  = ApexPages.CurrentPage().getParameters().get('parentid');

		reqType      = ApexPages.CurrentPage().getParameters().get('reqType');
		List<Id> addedTerms =new List<Id>();
		if(reqType=='Program'){
			for(TermCondition__c term :[Select Id,CopiedFrom__c from TermCondition__c where Program__c =: parentId]){
				addedTerms.add(term.CopiedFrom__c);
			}
			termConditionMap = new Map<Id,TermCondition__c>([Select Id, Name from TermCondition__c where recordType.Name='Term' and Program__c=null and Award__c=null and Id Not in :addedTerms]);			
		}
		else if (reqType=='Award'){
			for(TermCondition__c term :[Select Id,CopiedFrom__c from TermCondition__c where Award__c =: parentId]){
				addedTerms.add(term.CopiedFrom__c);
			}
			Id programId=ApexPages.CurrentPage().getParameters().get('programId');
			termConditionMap = new Map<Id,TermCondition__c> ([Select Id, Name from TermCondition__c where Program__c=: programId and Award__c=null and Id Not in :addedTerms]);
		}
		else if(reqType=='Federal'){
		  Set<String> setProgramFAId = new Set<String>();
		   for(ProgramFundingAccount__c progFA : [select Id,Name, LatestActiveAward__c from ProgramFundingAccount__c where Program__c =: parentId] )
		   {
		   	if(progFA.LatestActiveAward__c!=null)
		   	setProgramFAId.add(progFA.LatestActiveAward__c);
		   }
		  for(TermCondition__c term :[Select Id,CopiedFrom__c from TermCondition__c where Program__c =: parentId ])	{
				addedTerms.add(term.CopiedFrom__c);
			}
			termConditionMap = new Map<Id,TermCondition__c> ([Select Id, Name from TermCondition__c where Award__c IN: setProgramFAId and Id Not in :addedTerms]);
		}
		else{
			termConditionMap = new Map<Id,TermCondition__c> ([Select Id, Name from TermCondition__c where Program__c=null and Award__c=null]);
		}
    }

    public string getKeyValueMap(){
        Map<String,String> keyValueMap = new Map<String,String>();
        keyValueMap.put('parentid',ApexPages.CurrentPage().getParameters().get('parentid'));
        return JSON.serialize(keyValueMap);
    }

      public string getListParameters(){
      	Map<String,Set<String>> listParams = new Map<String,Set<String>>();     
      	Set<String> termConditionIdSet = (Set<String>)JSON.deserialize(JSON.serialize(termConditionMap.keyset()), Set<String>.class);
      	listParams.put('termConditionIdSet',termConditionIdSet);
      	 return JSON.serialize(listParams);
      }
}