UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/AwardBudgetCategory__c.object
<CustomObject>
    <description>[Business] Defines the Budget categories on the Award</description>
    <fields>
        <fullName>Award__c</fullName>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award Budget Categories</relationshipLabel>
        <relationshipName>Award_Budget_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award Budget Category</label>
    <nameField>
        <displayFormat>AC-{00}</displayFormat>
        <label>Award Budget Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Award Budget Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestAwardBudgetCategoryEditCtrl.cls
@isTest
private with sharing class TestAwardBudgetCategoryEditCtrl{

     static testMethod void testController() { 
         
         UserTriggerHelper.skipTrigger = true;
         User u = TestHelper.getAdminUser(true);
         AwardBudgetCategory__c awardbudCat = null;
         Grant__c grant = null;
         Award__c awards= null;
         PageReference pageRef = null;
         
         System.runAs(u){
             GrantTriggerHelper.skipTrigger = true;
             AwardTriggerHelper.skipTrigger = true;
             RolesAndResponsibilitiesTriggerHelper.skipTrigger=true;
             grant = TestHelper.getGrant(true);
             awards = TestHelper.getAwards(grant.Id, true);
             awardbudCat = new AwardBudgetCategory__c(Award__c=awards.Id);
             insert awardbudCat;
             pageRef = Page.AwardBudgetCategoryView;    
            
         }
         
         Test.startTest();
         ApexPages.StandardController sc = new ApexPages.standardController(awardbudCat);
         ApexPages.currentPage().getParameters().put('id',awardbudCat.Id);
         ApexPages.currentPage().getParameters().put('awardId',awards.id);
         AwardBudgetCategoryEditCtrl ctrl = new AwardBudgetCategoryEditCtrl(sc);
         ctrl.getKeyValueMap();
         Test.stopTest();
         
         system.assertNotEquals(null,pageRef);
     }
      
}