UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingAccount__c.object
<CustomObject>
    <description>[Business] Funding account details Funding accounts are created from Funding sources</description>
    <fields>
        <fullName>FundingSource__c</fullName>
        <label>Funding Source</label>
        <referenceTo>FundingSource__c</referenceTo>
        <relationshipLabel>Funding Accounts</relationshipLabel>
        <relationshipName>Funding_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Funding Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingSource__c.object
<CustomObject>
    <description>[Business] Details of the Funding sources which further creates Funding accounts</description>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Funding Sources</relationshipLabel>
        <relationshipName>Funding_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Funding Sources</relationshipLabel>
        <relationshipName>Funding_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>LatestAwardId__c</fullName>
        <label>Latest Award Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProgramCode</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ProgramFundingAccount__c.object
<CustomObject>
    <description>[Business] Junction object between Funding Account and Program</description>
    <fields>
        <fullName>FundingAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Account</label>
        <referenceTo>FundingAccount__c</referenceTo>
        <relationshipLabel>Program Funding Accounts</relationshipLabel>
        <relationshipName>Program_Funding_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FundingSource__c</fullName>
        <formula>HYPERLINK(&apos;/apex/FundingSourceView?id=&apos;+  FundingAccount__r.FundingSource__c  ,   FundingAccount__r.FundingSource__r.Name   , &apos;_self&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Funding Source</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Funding Accounts</relationshipLabel>
        <relationshipName>Program_Funding_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Funding Account</label>
    <nameField>
        <displayFormat>PFA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/TermCondition__c.object
<CustomObject>
    <description>[Business] Terms and Conditions for Grants ,Awards (The lookup to Package may not be required in this case )</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MST:Term and Condition</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <recordTypes>
        <fullName>Term</fullName>
        <active>true</active>
        <description>Related to Awards ( Ramu to rename this object appropriately)</description>
        <label>Term</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestSelectTermRecordsPopUpCtrl.cls
@isTest
private with sharing class TestSelectTermRecordsPopUpCtrl{
  
    static testMethod void testController() {
    /*
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          Account acct = null;
          Program__c pgm = null;
          TermCondition__c termCond = null;
          
          
          System.runAs(u){
            GrantTriggerHelper.skipTrigger = true;
            ProgramTriggerHelper.skipTrigger=true;
            AccountTriggerHelper.skipTrigger = true;
            GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
            
            acct = TestHelper.getAccount(true);
            pgm = TestHelper.getProgram(acct.Id,true);
            termCond = TestHelper.getTermcondition(false,'Term');
            termCond.Program__c=pgm.Id;
            insert termCond;
            
            Test.startTest();
            ApexPages.currentPage().getParameters().put('parentid',pgm.id);
            ApexPages.currentPage().getParameters().put('reqType','Program');
            SelectTermRecordsPopUpCtrl ctrl = new SelectTermRecordsPopUpCtrl();
            ctrl.getKeyValueMap();
            ctrl.getListParameters();
            Test.stopTest();
            
        }
        */
    }
    
    static testMethod void testController2(){
    /*
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          Account acct = null;
          Award__c award = null;
          Grant__c grant = null;
          TermCondition__c termCond = null;
          
          
          System.runAs(u){
            GrantTriggerHelper.skipTrigger = true;
            AwardTriggerHelper.skipTrigger=true;
            AccountTriggerHelper.skipTrigger = true;
            GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
            
            acct = TestHelper.getAccount(true);
            grant = TestHelper.getGrant(true);
            award = TestHelper.getAwards(grant.Id,true);
            termCond = TestHelper.getTermcondition(false,'Term');
            termCond.Award__c=award.Id;
            insert termCond;
            
            Test.startTest();
            ApexPages.currentPage().getParameters().put('parentid',award.id);
            ApexPages.currentPage().getParameters().put('reqType','Award');
            SelectTermRecordsPopUpCtrl ctrl = new SelectTermRecordsPopUpCtrl();
            ctrl.getKeyValueMap();
            ctrl.getListParameters();
            Test.stopTest();
            
        }
        */
    }
    
     static testMethod void testController3() {
     /*
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          Account acct = null;
          Program__c pgm = null;
          FundingSource__c fsrc = null;
          FundingAccount__c fundAcc = null;
          ProgramFundingAccount__c pgmFundAcc= null;
          TermCondition__c termCond = null;
          Award__c award = null;
          Grant__c grant = null;
          
          
          System.runAs(u){
            GrantTriggerHelper.skipTrigger = true;
            ProgramTriggerHelper.skipTrigger=true;
            AccountTriggerHelper.skipTrigger = true;
            AwardTriggerHelper.skipTrigger = true;
            GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
            
            acct = TestHelper.getAccount(true);
            pgm = TestHelper.getProgram(acct.Id,true);
            grant = TestHelper.getGrant(false);
            grant.LatestAwardId__c='Test123';
            insert grant;
            award = TestHelper.getAwards(grant.Id,true);
            fsrc = TestHelper.getFundingSource(false);
            fsrc.Grant__c = grant.Id;
            insert fsrc;
            fundAcc = TestHelper.getFundingAccount(true,fsrc.Id);
            pgmFundAcc= new ProgramFundingAccount__c(Program__c=pgm.Id,Fundingaccount__c=fundAcc.Id);
            insert pgmFundAcc;
            
            termCond = TestHelper.getTermcondition(false,'Term');
            termCond.Program__c=pgm.Id;
            insert termCond;
            
            Test.startTest();
            ApexPages.currentPage().getParameters().put('parentid',pgm.id);
            ApexPages.currentPage().getParameters().put('reqType','Federal');
            SelectTermRecordsPopUpCtrl ctrl = new SelectTermRecordsPopUpCtrl();
            ctrl.getKeyValueMap();
            ctrl.getListParameters();
            Test.stopTest();
            
        }
      */  
    }
    
        static testMethod void testController4() {
        /*
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          Account acct = null;
          Program__c pgm = null;
          TermCondition__c termCond = null;
          
          
          System.runAs(u){
            GrantTriggerHelper.skipTrigger = true;
            ProgramTriggerHelper.skipTrigger=true;
            AccountTriggerHelper.skipTrigger = true;
            GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
            
            acct = TestHelper.getAccount(true);
            pgm = TestHelper.getProgram(acct.Id,true);
            termCond = TestHelper.getTermcondition(false,'Term');
            termCond.Program__c=pgm.Id;
            insert termCond;
            
            Test.startTest();
            ApexPages.currentPage().getParameters().put('parentid',pgm.id);
            ApexPages.currentPage().getParameters().put('reqType','State');
            SelectTermRecordsPopUpCtrl ctrl = new SelectTermRecordsPopUpCtrl();
            ctrl.getKeyValueMap();
            ctrl.getListParameters();
            Test.stopTest();
           
        }
        
        */
        
    }
    
}