UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/GrantContact__c.object
<CustomObject>
    <description>[Business]  Stores all the information related toe the Award Contact</description>
    <fields>
        <fullName>Award__c</fullName>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Grant_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award Contact</label>
    <nameField>
        <displayFormat>GC-{0000}</displayFormat>
        <label>Grant Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestGrantContactViewCtrl.cls
@isTest
private with sharing class TestGrantContactViewCtrl{
    static testMethod void testController() {
        UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
        GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c','StateasGrantee');
        Award__c award = null;
        Grant__c grant = null;
        GrantContact__c grantContact = null;
        
     
        System.runAs(u){
            GrantTriggerHelper.skipTrigger = true;
            AwardTriggerHelper.skipTrigger = true;
            RolesandResponsibilitiesTriggerHelper.skipTrigger = true;
            AccountTriggerHelper.skipTrigger = true;
            grant = TestHelper.getGrant(true);
            award= TestHelper.getAwards(grant.Id,true);
            grantContact = new GrantContact__c(Award__c=award.Id);
            insert grantContact;
            
        }      
            Test.startTest();
            ApexPages.StandardController sc = new ApexPages.standardController(grant);
            ApexPages.currentPage().getParameters().put('id',grantContact.id);
            GrantContactViewCtrl ctrl = new GrantContactViewCtrl(sc);
            ctrl.getKeyValueMap();
            Test.stopTest();
        }
        
        
        static testMethod void testController2() {
        UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
        GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c','StateasGrantor');
        Award__c award = null;
        Grant__c grant = null;
        GrantContact__c grantContact = null;
        
     
        System.runAs(u){
            GrantTriggerHelper.skipTrigger = true;
            AwardTriggerHelper.skipTrigger = true;
            RolesandResponsibilitiesTriggerHelper.skipTrigger = true;
            AccountTriggerHelper.skipTrigger = true;
            grant = TestHelper.getGrant(true);
            award= TestHelper.getAwards(grant.Id,true);
            grantContact = new GrantContact__c(Award__c=award.Id);
            insert grantContact;
            
        }      
            Test.startTest();
            ApexPages.StandardController sc = new ApexPages.standardController(grant);
            ApexPages.currentPage().getParameters().put('id',grantContact.id);
            GrantContactViewCtrl ctrl = new GrantContactViewCtrl(sc);
            ctrl.getKeyValueMap();
            Test.stopTest();
        }
    }