UtahLiveDataTest/src/objects/Award__c.object
<CustomObject>
    <description>[Business] Stores the information related to the Award</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ProgressReports__c.object
<CustomObject>
    <description>[Business] Progress Report on the Grant/Award</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Progress Report</relationshipLabel>
        <relationshipName>Progress_Report</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Progress Report</relationshipLabel>
        <relationshipName>Progress_Report</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TermandCondition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Term and Condition</label>
        <referenceTo>TermCondition__c</referenceTo>
        <relationshipLabel>Progress Report</relationshipLabel>
        <relationshipName>Progress_Report</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Progress Report</label>
    <nameField>
        <label>Progress Report ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Report</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/TermCondition__c.object
<CustomObject>
    <description>[Business] Terms and Conditions for Grants ,Awards (The lookup to Package may not be required in this case )</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MST:Term and Condition</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestSF425FormEditCtrl.cls
@isTest
private with sharing class TestSF425FormEditCtrl{
    static testMethod void testController() {
    /*
          Account acct = null;
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          
          System.runAs(u){
            GrantTriggerHelper.skipTrigger = true;
            AwardTriggerHelper.skipTrigger = true;
            AccountTriggerHelper.skipTrigger = true;
            
            Grant__c grant = TestHelper.getGrant(true);
            Award__c award = TestHelper.getAwards(grant.Id,true);
            TermCondition__c termCond = TestHelper.getTermCondition(true,'Progress Report');
            ProgressReports__c progRep = new ProgressReports__c(Award__c = award.Id, TermandCondition__c=termCond.Id);
            insert progRep;
            
            Test.startTest();
            ApexPages.StandardController sc = new ApexPages.standardController(progRep);
            ApexPages.currentPage().getParameters().put('Id',progRep.id);
            SF425FormEditCtrl ctrl = new SF425FormEditCtrl(sc);
            ctrl.getKeyValueMap(); 
            Test.stopTest();
        
         }
        */
    }
    
}