UtahLiveDataTest/src/objects/AWS_Keys__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>AWS_Keys</description>
    <fields>
        <fullName>AWS_AccessKey_Id__c</fullName>
        <label>AWS_AccessKey_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AWS_Secret_Key__c</fullName>
        <label>AWS_Secret_Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AWS_URL__c</fullName>
        <label>AWS_URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bucket_Name__c</fullName>
        <label>Bucket Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AWS_Keys</label>
</CustomObject>

UtahLiveDataTest/src/objects/FileBatch__c.object
<CustomObject>
    <fields>
        <fullName>ExternalFileName__c</fullName>
        <label>External File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FileName__c</fullName>
        <label>File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>File Batch</label>
    <nameField>
        <label>File Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>File Batches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/AWSDownload.cls
global with sharing class AWSDownload extends GNT.FlexTableActionHandler {

    global override Map<String, Object> clickHandler() {
        Map<String, Object> resultMap = new Map<String, Object>();
    	AWS_Keys__c awsKeySet =  AWS_Keys__c.getInstance('govgrantsassets');

        List<FileBatch__c> appList = new List<FileBatch__c>([SELECT Id, ExternalFileName__c, FileName__c FROM FileBatch__c WHERE Id IN :selectedRecordIds]);


        String filename = EncodingUtil.urlEncode(appList[0].FileName__c, 'UTF-8');
 
        String BucketName=awsKeySet.Bucket_Name__c;
        String AccessKey= awsKeySet.AWS_AccessKey_Id__c;
        String SecretKey=awsKeySet.AWS_Secret_Key__c;
        String awsUrl = awsKeySet.AWS_URL__c;
        
        Datetime now = DateTime.now();
        Datetime expireson = now.AddSeconds(60); // Lifespan of the link
        Long Lexpires = expireson.getTime()/1000;
        
        String stringtosign = 'GET\n\n\n'+Lexpires+'\n/'+BucketName+'/'+filename;
        System.debug('redirectToS3Key stringstosign: ' + stringtosign);
        
        String signingKey = EncodingUtil.base64Encode(Blob.valueOf(SecretKey));
        Blob mac = Crypto.generateMac('HMacSHA1', blob.valueof(stringtosign),blob.valueof(SecretKey)); 
        String signed= EncodingUtil.base64Encode(mac);     
        String codedsigned = EncodingUtil.urlEncode(signed,'UTF-8');
        String url = awsUrl + '/' + BucketName + '/'+filename+'?AWSAccessKeyId='+AccessKey+
                              '&Expires='+Lexpires+'&Signature='+signed;

        resultMap.put('PageReference',url);
       // resultMap.put('PageReference','http://www.oracle.com/technetwork/developer-tools/apex/overview/apex41-new-features-487382.ppt');





        resultMap.put('Message', 'Successfully moved the application to review. '+appList.size()); 
        return resultMap;
    }




}