UtahLiveDataTest/src/objects/BudgetCategory__c.object
<CustomObject>
    <description>[Business] This object stores the Master List of all the Budget categories</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Personnel</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Occupancy</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Supplies</fullName>
                </value>
                <value>
                    <fullName>Publication</fullName>
                </value>
                <value>
                    <fullName>IDC</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Fringe Benefits</fullName>
                </value>
                <value>
                    <fullName>Contracted Fees</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MST: Budget Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Category</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/BudgetCategoryMapping__c.object
<CustomObject>
    <description>[Business]  Mapping of the Budget Category to Budget Category Mapping</description>
    <fields>
        <fullName>SourceBudgetCategory__c</fullName>
        <label>Source Budget Category</label>
        <referenceTo>BudgetCategory__c</referenceTo>
        <relationshipName>Budget_Category_Mapping</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MST: Budget Category Mapping</label>
    <nameField>
        <displayFormat>BCM-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Category Mapping</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingAccount__c.object
<CustomObject>
    <description>[Business] Funding account details Funding accounts are created from Funding sources</description>
    <fields>
        <fullName>AllocatedAmount__c</fullName>
        <label>Allocated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FundingSource__c</fullName>
        <label>Funding Source</label>
        <referenceTo>FundingSource__c</referenceTo>
        <relationshipLabel>Funding Accounts</relationshipLabel>
        <relationshipName>Funding_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingSource__c.object
<CustomObject>
    <description>[Business] Details of the Funding sources which further creates Funding accounts</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Funder Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Federal</fullName>
                    <default>true</default>
                    <label>Federal</label>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>NGO</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingSourceBudgetCategory__c.object
<CustomObject>
    <description>[Business] This is junction object for Funding Sources and Budget Categories</description>
    <fields>
        <fullName>AllocatedAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Allocated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BudgetCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Category</label>
        <referenceTo>BudgetCategory__c</referenceTo>
        <relationshipLabel>Funding Source Budget Category</relationshipLabel>
        <relationshipName>Funding_Source_Budget_Category</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FundingSource__c</fullName>
        <label>Funding Source</label>
        <referenceTo>FundingSource__c</referenceTo>
        <relationshipLabel>Funding Source Budget Category</relationshipLabel>
        <relationshipName>Funding_Source_Budget_Category</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Source Budget Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Source Budget Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestFundingAccountTriggerHelper.cls
@isTest
public class TestFundingAccountTriggerHelper {
    
    static testMethod void testFundingAccTrigger() {
        FundingSource__c fundSrc = TestHelper.getFundingSource(true);
       
        
        
        BudgetCategory__c budCat = new BudgetCategory__c();
        insert budCat;
        
        BudgetCategoryMapping__c budCatMapping = new BudgetCategoryMapping__c();
        budCatMapping.SourceBudgetCategory__c= budCat.Id;
        insert budCatMapping;
        
        FundingSourceBudgetCategory__c fundSrcBudCat = new FundingSourceBudgetCategory__c();
        fundSrcBudCat.FundingSource__c=fundSrc.Id;
        fundSrcBudCat.BudgetCategory__c=budCat.Id;
        fundSrcBudCat.AllocatedAmount__c=5000;
        insert fundSrcBudCat;
        
        
        FundingAccount__c fundAcc = TestHelper.getFundingAccount(true,fundSrc.Id);
        fundAcc.AllocatedAmount__c=5000;
        update fundAcc;
        delete fundAcc;
    }
    
    static testMethod void testFundingAccTrigger2() {
        FundingSource__c fundSrc = TestHelper.getFundingSource(true);
        fundSrc.Type__c='Federal';
        update fundSrc;
        
        
        BudgetCategory__c budCat = new BudgetCategory__c();
        insert budCat;
        
        BudgetCategoryMapping__c budCatMapping = new BudgetCategoryMapping__c();
        budCatMapping.SourceBudgetCategory__c= budCat.Id;
        insert budCatMapping;
        
        FundingSourceBudgetCategory__c fundSrcBudCat = new FundingSourceBudgetCategory__c();
        fundSrcBudCat.FundingSource__c=fundSrc.Id;
        fundSrcBudCat.BudgetCategory__c=budCat.Id;
        fundSrcBudCat.AllocatedAmount__c=5000;
        insert fundSrcBudCat;
        
        
        FundingAccount__c fundAcc = TestHelper.getFundingAccount(true,fundSrc.Id);
        fundAcc.AllocatedAmount__c=5000;
        update fundAcc;
        delete fundAcc;
    }
}