UtahLiveDataTest/src/objects/BudgetCategory__c.object
<CustomObject>
    <description>[Business] This object stores the Master List of all the Budget categories</description>
    <label>MST: Budget Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Category</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ProgramBudgetCategory__c.object
<CustomObject>
    <description>Junction Object for Program and Budget Category</description>
    <fields>
        <fullName>BudgetCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Budget Category</description>
        <label>Budget Category</label>
        <referenceTo>BudgetCategory__c</referenceTo>
        <relationshipLabel>Program Budget Categories</relationshipLabel>
        <relationshipName>ProgramBudgetCategories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Budget Categories</relationshipLabel>
        <relationshipName>ProgramBudgetCategories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Budget Category</label>
    <nameField>
        <displayFormat>PB-{0000}</displayFormat>
        <label>Program Budget Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Budget Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ProgramBudgetCategoryActionHandler.cls
global with sharing class ProgramBudgetCategoryActionHandler extends GNT.FlexTableActionHandler {
   global override Map<String,Object> clickHandler(){
        Map<String,Object> resultMap = new Map<String,Object>();
         Id parentId = urlParams.get('parentid');     
         
         List<ProgramBudgetCategory__c> pgmBCs= new List<ProgramBudgetCategory__c>();
         if(selectedRecordIds != null && !selectedRecordIds.isEmpty()){
            for(Id recordId: selectedRecordIds){
                ProgramBudgetCategory__c progBC= new ProgramBudgetCategory__c();
                progBC.BudgetCategory__c = recordId;
                progBC.Program__c = parentId;
                pgmBCs.add(progBC);
            }
            insert(pgmBCs);           
            //resultMap.put('Message','Budget Category added succesfully.');
            resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-31176'));
         }else{
            //resultMap.put('Message','No records are selected.');
            resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-58429'));
         }
        
        return resultMap;   
    }
}