UtahLiveDataTest/src/objects/BusinessPackage__c.object
<CustomObject>
    <description>[Business]  This object associates the Package with the Program or Opportunity</description>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Grants</description>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PackageConfig__c</fullName>
        <label>Package Config</label>
        <referenceTo>GNT__Package__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PackageType__c</fullName>
        <label>Package Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Pre-Application</fullName>
                </value>
                <value>
                    <fullName>App-Review</fullName>
                </value>
                <value>
                    <fullName>Award</fullName>
                </value>
                <value>
                    <fullName>Amendment Request</fullName>
                </value>
                <value>
                    <fullName>Progress Report</fullName>
                </value>
                <value>
                    <fullName>Site Visit</fullName>
                </value>
                <value>
                    <fullName>Payment Request</fullName>
                </value>
                <value>
                    <fullName>Closeout</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Risk Assessment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Package</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Closeout__c.object
<CustomObject>
    <description>[Business] All the close out information is stored on this object</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Closeouts</relationshipLabel>
        <relationshipName>Closeouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Notified</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Notification Accepted</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Termination</fullName>
                </value>
                <value>
                    <fullName>Annual Closeout</fullName>
                </value>
                <value>
                    <fullName>Grant Closeout</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closeout</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closeouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProgramCode</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RiskAssessmentPackage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk Assessment Package</label>
        <referenceTo>GNT__Package__c</referenceTo>
        <relationshipLabel>Grants (Risk Assessment Package)</relationshipLabel>
        <relationshipName>Grants2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed/Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isClosedOut__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field identifies if the Grant is eligible for Closeout</description>
        <label>isClosedOut</label>
        <type>Checkbox</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RiskAssessment__c.object
<CustomObject>
    <description>[Business] This will be part of Grant Making Module.</description>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Risk Assessment</relationshipLabel>
        <relationshipName>Risk_Assessment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Risk Assessment</relationshipLabel>
        <relationshipName>Risk_Assessment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Grantee</fullName>
                </value>
                <value>
                    <fullName>Grant Award</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Risk Assessment</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk Assessment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/RiskAssessmentEditCtrl.cls
global with sharing class RiskAssessmentEditCtrl extends GNT.MasterCtrl {
    
    //Properties
    public ID recordId{get;set;}
    public ID grantId{get;set;}
    public ID programId{get;set;}
    public PageReference savePage {get;set;}
    public PageReference cancelPage {get;set;}
    public List<GNT.DynamicLayoutDefaultValueHelper> listDefaultValues {get;set;}
    public String templateName {get;set;}
    public Boolean hideCancelBtn {get;set;}
    public String packageId {get;set;}
    private  RiskAssessment__c riskObj;
    
    public RiskAssessmentEditCtrl (ApexPages.StandardController stdController){
        
        recordId  = ApexPages.CurrentPage().getParameters().get('id');  
        grantId   = ApexPages.CurrentPage().getParameters().get('grantid');  
        programId = ApexPages.CurrentPage().getParameters().get('programId');         
        String requestType= ApexPages.CurrentPage().getParameters().get('requestType');  
        savePage = Page.RiskAssessmentView; 
        savePage.getParameters().put('id', recordId);
       // hideCancelBtn = true;
        cancelPage = Page.GrantView;
        if(grantId!=null){
        cancelPage = Page.GrantView;
        cancelPage.getParameters().put('id', grantId);
        }        
        else{
        cancelPage = Page.RiskAssessmentView;
        cancelPage.getParameters().put('id', recordId);    
        }        
        List<BusinessPackage__c> bizPkg = [Select Id,Name,PackageConfig__c from BusinessPackage__c where PackageType__c ='Risk Assessment' and Grant__c=:grantId limit 1];
        if(bizPkg!=null && bizPkg.size()>0){
            packageId=bizPkg[0].PackageConfig__c;            
        }
 
        if(recordId!=null){
        savePage.getParameters().put('id', recordId);       
            List<RiskAssessment__c> raList = [SELECT Id,Name,Grant__r.RiskAssessmentPackage__r.GNT__PageTemplateConfig__r.Name,CreatedDate,LastModifiedDate 
                                                FROM RiskAssessment__c  WHERE Id =:recordId];
            System.debug('raList ---'+raList );
            if(raList.size() > 0){
                templateName = raList[0].Grant__r.RiskAssessmentPackage__r.GNT__PageTemplateConfig__r.Name;       
        }
        
      }
      listDefaultValues = new List<GNT.DynamicLayoutDefaultValueHelper>();
        if (grantId != null){
            GNT.DynamicLayoutDefaultValueHelper dv = new GNT.DynamicLayoutDefaultValueHelper(AppUtils.getNamespacePrefix()+'Grant__c',grantId,true);            
            listDefaultValues.add(dv);            
            savePage.getParameters().put('grantid', grantId);
            savePage.getParameters().put('programId', programId);
            checkCloseout(grantId);
        }
        if (programId != null){
            GNT.DynamicLayoutDefaultValueHelper dv1 = new GNT.DynamicLayoutDefaultValueHelper(AppUtils.getNamespacePrefix()+'Program__c',programId,true);            
            listDefaultValues.add(dv1);            
            savePage.getParameters().put('programId', programId);
        }        
        GNT.DynamicLayoutDefaultValueHelper dv2 = new GNT.DynamicLayoutDefaultValueHelper('Type__c',requestType,true);
            listDefaultValues.add(dv2);
             
            templateName='Risk Assessment Report';
             
    }
    
    private void checkCloseout(Id grantId){
        List<Closeout__c> closeout = new List<Closeout__c>([SELECT Id, Grant__c, Grant__r.isClosedOut__c FROM Closeout__c WHERE Grant__c =: grantId LIMIT 1]);
        if(!closeout.isEmpty() && closeout[0].Grant__r.isClosedOut__c != null && closeout[0].Grant__r.isClosedOut__c){
            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'The selected Grant has been Closed Out. Please return to the previous screen.'));
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-56207')));                                
        }
        else if(closeout.size() > 0){
            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Closeout is in process for the Grant. Please return to the previous screen.'));
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-95188')));                
        }
    }

    public string getKeyValueMap(){
        Map<String,String> keyValueMap = new Map<String,String>();
        keyValueMap.put('id',recordId);
        if (grantId != null){
            keyValueMap.put('grantid',grantId);
        }
        if (programId != null){
            keyValueMap.put('programId',programId);
        }

        keyValueMap.put('riskAssessmentId',ApexPages.currentPage().getParameters().get('Id'));  
        
        return JSON.serialize(keyValueMap);
    }

    public PageReference redirect(){

        PageReference pageRef = null;
        RiskAssessment__c riskObj = [Select Status__c from RiskAssessment__c where id=:recordId];
        if(riskObj.Status__c.equalsIgnorecase('In Progress') ){
            //pageRef = new PageReference('/apex/'+AppUtils.getNamespacePrefix()+'RiskAssessmentView?id='+recordId);

        }else{
            pageRef = new PageReference('/apex/'+AppUtils.getNamespacePrefix()+'RiskAssessmentView?id='+recordId);            
        }
        return pageRef;
    }
}