UtahLiveDataTest/src/objects/BusinessPackage__c.object
<CustomObject>
    <description>[Business]  This object associates the Package with the Program or Opportunity</description>
    <fields>
        <fullName>PackageConfig__c</fullName>
        <label>Package Config</label>
        <referenceTo>GNT__Package__c</referenceTo>
        <relationshipLabel>Business Packages</relationshipLabel>
        <relationshipName>Business_Packages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Business Package</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/PreviewPackageCtrl.cls
public with sharing class PreviewPackageCtrl {
    
    //Properties
    public ID recordId{get;set;}
    public ID businessPackageId{get;set;}
            
    public PreviewPackageCtrl(ApexPages.StandardController stdController) {
        recordId = ApexPages.CurrentPage().getParameters().get('id');
        businessPackageId = ApexPages.CurrentPage().getParameters().get('businessPackageId');
        if( businessPackageId != null ){
        	recordId = [select packageConfig__c from BusinessPackage__c where id=:businessPackageId].packageConfig__c;
        }
    }
    
    /*
        Method to populate the parameters for the FlexTable
    */
    public string getKeyValueMap(){
        Map<String,String> keyValueMap = new Map<String,String>();
        if(recordId != null){
            keyValueMap.put('packageId',recordId);
        }
        return JSON.serialize(keyValueMap);
    }
}