UtahLiveDataTest/src/objects/Case__c.object
<CustomObject>
    <description>Business - Use to create case.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Tier1 Support</fullName>
                </value>
                <value>
                    <fullName>Tier2 Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GG Case</label>
    <nameField>
        <label>Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/CaseAssignToMeActionHelper.cls
global with sharing class CaseAssignToMeActionHelper  extends GNT.DynamicLayoutActionRedirect {
    global override Pagereference whenClicked() {
    	try {
    		String recordId = ApexPages.CurrentPage().getParameters().get('id');
    		Case__c caseObj = [Select Id,OwnerId,Status__c from Case__c where id=:recordId]; 
    		caseObj.OwnerId = UserInfo.getUserId();
    		if(caseObj.Status__c == 'New') {
    			caseObj.Status__c = 'In Progress';
    		}
    		update caseObj;
    		PageReference p = Page.CaseView;
	        p.getParameters().put('id', recordId);
	        p.setRedirect(true);
	        return p;
    	} catch(Exception ex) {
    		ApexPages.Message msg =new Apexpages.Message(ApexPages.Severity.ERROR, ex.getMessage());
    		ApexPages.addmessage(msg);
    		return null;
    	}
    }
}