UtahLiveDataTest/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current status of the issue.</description>
        <inlineHelpText>The current status of the issue.</inlineHelpText>
        <label>Internal Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Case__c.object
<CustomObject>
    <description>Business - Use to create case.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Tier1 Support</fullName>
                </value>
                <value>
                    <fullName>Tier2 Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GG Case</label>
    <nameField>
        <label>Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/CaseAssignToUser.cls
global with sharing class CaseAssignToUser extends GNT.FlexTableActionHandler{
    global override Map<String, Object> clickHandler() {
    	Map<String, Object> resultMap = new Map<String, Object>();
    	if(selectedRecordIds.size() == 0) {
    		resultMap.put('Message','Please select one record.');	
    	} else {
    		String caseId = urlParams.get('caseId');
    		Case__c caseObj = [Select Id,OwnerId,Status__c from Case__c where id=:caseId]; 
    		caseObj.OwnerId = selectedRecordIds.get(0);
    		if(caseObj.Status__c == 'New') {
    			caseObj.Status__c = 'In Progress';
    		}
    		update caseObj;
    		//resultMap.put('Message','Case Assigned successfully.');
            resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-53060'));
    	}
    	
    	return resultMap;
    }
}