UtahLiveDataTest/src/objects/Closeout__c.object
<CustomObject>
    <description>[Business] All the close out information is stored on this object</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Closeouts</relationshipLabel>
        <relationshipName>Closeouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Closeout</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closeouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/CloseoutInventory__c.object
<CustomObject>
    <description>[Business] Object to Store the Close out Request Details</description>
    <fields>
        <fullName>Closeout__c</fullName>
        <label>Closeout</label>
        <referenceTo>Closeout__c</referenceTo>
        <relationshipLabel>Closeout Inventory</relationshipLabel>
        <relationshipName>Closeout_Inventory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Closeout Inventory</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Closeout Inventory Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closeout Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestCloseoutInventoryEditCtrl.cls
@isTest
private with sharing class TestCloseoutInventoryEditCtrl{
    static testMethod void testController() {
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          System.runAs(u){
          
              GrantTriggerHelper.skipTrigger = true;
              Grant__c grant = TestHelper.getGrant(true);
              Closeout__c closeOut = TestHelper.getCloseout(grant.Id,true);
              CloseoutInventory__c closeOutInv = new CloseoutInventory__c(Closeout__c=closeOut.Id);
              insert closeOutInv;

              Test.startTest();
              ApexPages.StandardController sc = new ApexPages.standardController(closeOutInv);
              ApexPages.currentPage().getParameters().put('id',closeOutInv.id);
              ApexPages.CurrentPage().getParameters().put('closeoutId',closeOut.Id); 
              CloseoutInventoryEditCtrl ctrl = new CloseoutInventoryEditCtrl(sc);
              ctrl.getKeyValueMap();
              Test.stopTest();
          }
        
    }
    
    static testMethod void testController2() {
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          System.runAs(u){
          
              GrantTriggerHelper.skipTrigger = true;
              Grant__c grant = TestHelper.getGrant(true);
              Closeout__c closeOut = TestHelper.getCloseout(grant.Id,true);
              CloseoutInventory__c closeOutInv = new CloseoutInventory__c(Closeout__c=closeOut.Id);
              insert closeOutInv;

              Test.startTest();
              ApexPages.StandardController sc = new ApexPages.standardController(closeOutInv);
              ApexPages.CurrentPage().getParameters().put('closeoutId',closeOut.Id); 
              CloseoutInventoryEditCtrl ctrl = new CloseoutInventoryEditCtrl(sc);
              ctrl.getKeyValueMap();
              Test.stopTest();
          }
        
    }
    
}