UtahLiveDataTest/src/objects/CommunityRegistrationConfig__c.object
<CustomObject>
    <description>[Framework] Defines the configuration for the Community registration</description>
    <label>Community Registration Config</label>
    <nameField>
        <displayFormat>CRC-{0000}</displayFormat>
        <label>Community Registration Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Registration Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/CommunityRegistrationConfigDetail__c.object
<CustomObject>
    <description>[Framework] Defines the details of the configuration for the Community registration</description>
    <fields>
        <fullName>CommunityRegistrationConfig__c</fullName>
        <label>Community Registration Config</label>
        <referenceTo>CommunityRegistrationConfig__c</referenceTo>
        <relationshipLabel>Community Registration Config Details</relationshipLabel>
        <relationshipName>Community_Registration_Config_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Community Registration Config Detail</label>
    <nameField>
        <label>Community Registration Config Detail Nam</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Registration Config Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestCommunityRegistConfigDetailTrigger.cls
@isTest
private class TestCommunityRegistConfigDetailTrigger {
	
	@isTest static void test_method_one() {
		CommunityRegistrationConfig__c cmr = new CommunityRegistrationConfig__c();
        insert cmr;
		CommunityRegistrationConfigDetail__c c = new CommunityRegistrationConfigDetail__c(CommunityRegistrationConfig__c = cmr.Id);
		insert c;
	}
	
	@isTest static void test_method_two() {
		// Implement test code
	}
	
}