UtahLiveDataTest/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ApplicantType__c</fullName>
        <formula>if (ISPICKVAL( UserRole__c ,&apos;Primary&apos;) ,&apos;AdditionalApplicant&apos;,&apos;AdditionalApplicantSecondary&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Applicant Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserRegistration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Registration</label>
        <referenceTo>UserRegistration__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserRole__c</fullName>
        <description>This fields need to get updated as per the Formula Values  Vinayak 11/20/2015</description>
        <label>User Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>LEA BA</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ApplicantType__c</fullName>
        <formula>TEXT(Contact.Account.ApplicantType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Applicant Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/UserRegistration__c.object
<CustomObject>
    <description>[Business] Need more Detailed info from Swati Singh</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>User_Registration2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Contact record associated with the community user record.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>User_Registration</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryRepPhone__c</fullName>
        <inlineHelpText>Point of Contact’s Official Phone number. Format is XXX-XXX-XXXX.</inlineHelpText>
        <label>Primary Rep Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UserRole__c</fullName>
        <label>User Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Project Admin</fullName>
                </value>
                <value>
                    <fullName>Project Director</fullName>
                </value>
                <value>
                    <fullName>Project Staff</fullName>
                </value>
                <value>
                    <fullName>Reviewer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>External Registration</label>
    <nameField>
        <displayFormat>RG-{000000}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Registration</pluralLabel>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <label>Applicant</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/DirectlyRegisterActivateUserFromContact.cls
global with sharing class DirectlyRegisterActivateUserFromContact extends GNT.DynamicLayoutActionRedirect{
    
    global override PageReference whenClicked(){ 
        Savepoint savestate = Database.setSavepoint();
        Map<String,Object> retVal = new Map<String,Object>();
        Id recordId = layoutHolder.getPrimarySObject().Id;  //Current Contact Id
        
        try{
            System.debug('MANUALDEBUG >>> recordId: ' + recordId);
            Contact currentContact = [SELECT Id, AccountId, ApplicantType__c, UserRole__c, Name, Phone FROM Contact WHERE Id =: recordId];
            System.debug('MANUALDEBUG >>> currentContact: ' + currentContact);
            
            /*
            String contactType;
            if (currentContact.ApplicantType__c == '') {
                contactType = 'Additional Applicant';
            }
            else if (currentContact.ApplicantType__c == '') {
                contactType = '';
            }
            */
            RecordType currentRecordType = [SELECT Id, Name, DeveloperName FROM RecordType WHERE DeveloperName =: currentContact.ApplicantType__c];
            System.debug('MANUALDEBUG >>> currentRecordType : ' + currentRecordType);
            
            System.debug('MANUALDEBUG >>> Creating UserRegistration');
            UserRegistration__c userToActivate = new UserRegistration__c();  
            userToActivate.Account__c = currentContact.AccountId;
            userToActivate.Contact__c = currentContact.Id;
            userToActivate.RecordTypeId = currentRecordType.Id;
            userToActivate.PrimaryRepPhone__c = currentContact.Phone;
            insert userToActivate;
            System.debug('MANUALDEBUG >>> userToActivate: ' + userToActivate);
            
            System.debug('MANUALDEBUG >>> Updating Contact with UserRegistration');
            currentContact.UserRegistration__c = userToActivate.Id;
            update currentContact;
            System.debug('MANUALDEBUG >>> currentContact: ' + currentContact);
            
            System.debug('MANUALDEBUG >>> Initiating User Registration');
            userToActivate.Status__c = 'Approved';
            update userToActivate;
            System.debug('MANUALDEBUG >>> userToActivate: ' + userToActivate);
            
            PageReference pf = Page.OrganizationView;
            pf.getParameters().put('id', currentContact.AccountId);
            pf.setRedirect(true);
            return pf;
        }
        catch(Exception e){
            Database.rollback(savestate);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, e.getMessage())); 
            return null;
        }   
    }
}