UtahLiveDataTest/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SecurityToken__c</fullName>
        <label>Security Token</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UserRegistration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Registration</label>
        <referenceTo>UserRegistration__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/UserRegistration__c.object
<CustomObject>
    <description>[Business] Need more Detailed info from Swati Singh</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Contact record associated with the community user record.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>User_Registration</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NDADate__c</fullName>
        <label>NDA Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NDALookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NDA Lookup</label>
        <referenceTo>MasterAgreement__c</referenceTo>
        <relationshipLabel>External Registration</relationshipLabel>
        <relationshipName>External_Registration</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NDAStatus__c</fullName>
        <label>NDA Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>External Registration</label>
    <nameField>
        <displayFormat>RG-{000000}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Registration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ExternalRegistrationNDADisagreeHelper.cls
global with sharing class ExternalRegistrationNDADisagreeHelper extends GNT.DynamicLayoutActionRedirect{
    private String securityToken;
    
    global override PageReference whenClicked(){ 
         Savepoint sp = Database.setSavePoint();
          try{
             securityToken= ApexPages.CurrentPage().getParameters().get('SecurityToken');
             List<Contact> contactList = [SELECT ID FROM Contact WHERE SecurityToken__c =: SecurityToken limit 1];
             Id recordId = apexpages.currentpage().getparameters().get('id');
              
              if(securityToken != NULL && securityToken != ''){
                  UserRegistration__c userReg = [Select Id, Name,NDADate__c,NDAStatus__c,NDALookup__c from UserRegistration__c where Contact__c = :contactList[0].Id Limit 1];
                  userReg.NDADate__c= System.today();
                  userReg.NDAStatus__c= 'Rejected';
                  UserRegistrationTriggerHelper.skipTrigger = true;
                  update userReg ;
                  //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Registration process is terminated please close the broswer window to exit'));
                  //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, GNT.ErrorMessageHelper.fetchMessage('P01-GRNTR-55811')));
                   PageReference pf = Page.ApplicantLogin4;
                  //pf.getParameters().put('id', userReg.Id);
                  pf.setRedirect(true);
                  return pf;
              }else{
                  UserRegistration__c userReg = [Select Id, Name,NDADate__c,NDAStatus__c,NDALookup__c from UserRegistration__c where id =:recordId Limit 1];
                  userReg.NDADate__c= System.today();
                  userReg.NDAStatus__c= 'Rejected';
                  UserRegistrationTriggerHelper.skipTrigger = true;
                  update userReg ;
                  //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Registration process is terminated please close the broswer window to exit'));
                  //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, GNT.ErrorMessageHelper.fetchMessage('P01-GRNTR-55811')));
                    
                   PageReference pf = Page.ApplicantLogin4;
                  //pf.getParameters().put('id', userReg.Id);
                  pf.setRedirect(true);
                  return pf;
                  //return null;
                  
              }
            
              
          }catch(Exception ex){
            Database.rollback(sp);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, ex.getMessage())); 
            return null;
          }
    }

}