UtahLiveDataTest/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>UserName__c</fullName>
        <label>User Name</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>UserRegistration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Registration</label>
        <referenceTo>UserRegistration__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/UserRegistration__c.object
<CustomObject>
    <description>[Business] Need more Detailed info from Swati Singh</description>
    <fields>
        <fullName>EINo__c</fullName>
        <inlineHelpText>An Employee Identification Number (EIN) is a nine-digit number provided by  Internal Revenue Service (IRS) which is often used by a business to open bank accounts, applying for business licenses, filing tax reports, filing electronic returns and taxes.</inlineHelpText>
        <label>Ob_Employee Identification Number (EIN)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <inlineHelpText>Enter valid email address.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <inlineHelpText>Registered Name as listed in DUN and BradStreet</inlineHelpText>
        <label>Organization Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <inlineHelpText>The Username must be in email format but the email format does not need to be a valid email address. For example xyz@abc.com</inlineHelpText>
        <label>User Name</label>
        <type>Email</type>
    </fields>
    <label>External Registration</label>
    <nameField>
        <displayFormat>RG-{000000}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Registration</pluralLabel>
    <recordTypes>
        <fullName>Reviewer</fullName>
        <active>true</active>
        <label>Reviewer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestCommunityUserProfileEditCtrl.cls
@isTest
private with sharing class TestCommunityUserProfileEditCtrl {

      static testMethod void testController(){
          UserTriggerHelper.skipTrigger = true; 
          User u = TestHelper.getAdminUser(true);
         System.runAs(u) {
         TestHelper.CreateCustomSettings(true);
        UserRegistration__c uReg = new UserRegistration__c();
        uReg.OrganizationName__c ='TestORG';
        uReg.LastName__c = 'Betty';
        uReg.username__c = System.now().millisecond() + 'test@123test.com';
        uReg.EINo__c = Math.Random();
        uReg.Email__c = 'test15@test.com';
        //uReg.RecordType.DeveloperName = 'Reviewer';
        insert uReg;
        Contact con = TestHelper.getContact(true);
          Test.startTest();
         ApexPages.currentPage().getParameters().put('id', con.Id);
          CommunityUserProfileEditCtrl ctrl = new CommunityUserProfileEditCtrl(new ApexPages.StandardController(con));
          ctrl.isFirstLogin();
          //ctrl.login();
          Test.stopTest();
      }
}

 
    
  
      
}