UtahLiveDataTest/src/objects/Drawdown__c.object
<CustomObject>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Drawdowns</relationshipLabel>
        <relationshipName>Drawdowns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Drawdown</label>
    <nameField>
        <label>Drawdown Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/DrawdownDetail__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Drawdown__c</fullName>
        <label>Drawdown</label>
        <referenceTo>Drawdown__c</referenceTo>
        <relationshipLabel>Drawdown Details</relationshipLabel>
        <relationshipName>Drawdown_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RequestAdvanceOrReimburse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MST: Request Advance Or Reimburse</label>
        <referenceTo>RequestAdvanceOrReimburse__c</referenceTo>
        <relationshipLabel>Drawdown Details</relationshipLabel>
        <relationshipName>Drawdown_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project/Service Area</label>
        <referenceTo>ServiceArea__c</referenceTo>
        <relationshipLabel>Drawdown Details</relationshipLabel>
        <relationshipName>Drawdown_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Drawdown Detail</label>
    <nameField>
        <displayFormat>DDD-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdown Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/GrantServiceArea__c.object
<CustomObject>
    <description>[Business] Association of Grant with the service area</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipName>GrantServiceAreas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Area</label>
        <referenceTo>ServiceArea__c</referenceTo>
        <relationshipName>GrantServiceAreas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grant Project Area</label>
    <nameField>
        <displayFormat>GSA-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Project Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RequestAdvanceOrReimburse__c.object
<CustomObject>
    <description>[Business] This object stores the Master List of all Drawdown categories used for SF270 form.</description>
    <label>MST: Request Advance Or Reimburse</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Advance Or Reimburse</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ServiceArea__c.object
<CustomObject>
    <description>[Business] Master list of all the Service Area information is stored in this object , Service areas are also applicable to the Announcements ,Programs,Application via Junction objects</description>
    <label>Project/Service Area</label>
    <nameField>
        <displayFormat>PSA-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/DrawdownTriggerHelper.cls
global with sharing class DrawdownTriggerHelper extends GNT.TriggerHelper{
     
     private String appName = GNT.UserPreferenceHelper.getStringValue('ActiveAppName__c');
     public static Boolean skipTrigger = false;
     public override void processAfterInsert() {
        if(skipTrigger == false){
            if(appName == 'StateasGrantee'){
                buildAdvanceOrReimburseGrid();
            }
          }
     }
     
     private void buildAdvanceOrReimburseGrid(){
        List<RequestAdvanceOrReimburse__c> paymentCat = [SELECT Id FROM RequestAdvanceOrReimburse__c];

        Set<Id> grantIds = new Set<Id>();
        for(Drawdown__c draw : (List<Drawdown__c>) Trigger.New) {
            grantIds.add(draw.Grant__c);
        }

        Map<Id, List<GrantServiceArea__c>> drawServArea = new  Map<Id, List<GrantServiceArea__c>>();  //key->grant id
        List<GrantServiceArea__c> servAreaLst = [SELECT Id, Grant__c, ServiceArea__c FROM GrantServiceArea__c WHERE Grant__c in :grantIds];
        for (GrantServiceArea__c gsa : servAreaLst) {
            List<GrantServiceArea__c> innerList = drawServArea.get(gsa.Grant__c);
            if (innerList == null) {
                innerList = new List<GrantServiceArea__c>();
                drawServArea.put(gsa.Grant__c, innerList);
            }
            innerList.add(gsa);
        }

        List<DrawdownDetail__c> drawReports = new List<DrawdownDetail__c>();
        for(Drawdown__c draw : (List<Drawdown__c>) Trigger.New){
            List<GrantServiceArea__c> saList = drawServArea.get(draw.Grant__c);
            for (GrantServiceArea__c sa : saList) {
                for (RequestAdvanceOrReimburse__c ra : paymentCat) {
                    DrawdownDetail__c drawReport = new DrawdownDetail__c();
                    drawReport.Drawdown__c= draw.Id;
                    drawReport.ServiceArea__c = sa.ServiceArea__c;
                    drawReport.RequestAdvanceOrReimburse__c = ra.Id;
                    drawReport.Amount__c = 0.0;
                    drawReports.add(drawReport);
                }
            }
        }

        insert drawReports;

     }
}