UtahLiveDataTest/src/objects/EventRelation__c.object
<CustomObject>
    <fields>
        <fullName>EventId__c</fullName>
        <label>EventId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventRelationId__c</fullName>
        <label>EventRelationId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelationId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EventRelations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tentative</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>EventRelation</label>
    <nameField>
        <label>EventRelation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EventRelations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/AddInviteesActionHelper.cls
global with sharing class AddInviteesActionHelper extends GNT.FlexTableActionHandler {
       global Id eventId {get;set;}
       global String flexTableName {get;set;}
       global override Map<String,Object> clickHandler(){ 
        Map<String,Object> resultMap = new Map<String,Object>();
        eventId = urlParams.get('id');     
        flexTableName = urlParams.get('flexTableName');     
        System.debug('===> selectedRecordIds  '+selectedRecordIds);
        
         if(selectedRecordIds != null && !selectedRecordIds.isEmpty()){
            List<User> usrList = [Select Id,Email from User where Id IN :selectedRecordIds];
            //List<EventRelation> iErelation = new List<EventRelation>();
            List<EventRelation__c> custErelation = new List<EventRelation__c>();
            System.debug('===> UserList '+usrList);
            System.debug('===> parentId '+eventId);
            Event eve = [Select Id,EventRelationId__c from Event where Id =: eventId];
            
            /*code to send notification to selected user*/
            for(User user : usrList){
                //EventRelation er = new EventRelation();
                //er.EventId = eventId;
                //er.RelationId = user.Id;
                //iErelation.add(er);
                EventRelation__c eveRel = new EventRelation__c();
                eveRel.EventId__c = eventId;
                eveRel.RelationId__c = user.Id;
                eveRel.Status__c = 'Tentative';
                //eveRel.EventRelationId__c = er.Id;
                custErelation.add(eveRel);
            }
            /*Database.DMLOptions dmo = new Database.DMLOptions(); 
            dmo.EmailHeader.triggerUserEmail = true; 
            dmo.EmailHeader.triggerAutoResponseEmail = true;
            dmo.EmailHeader.triggerOtherEmail= true;*/
            //insert iErelation;
            insert custErelation;
            //System.debug('====> iErelation  '+iErelation);
            System.debug('====> custErelation '+custErelation);
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-24961'));
            ApexPages.addMessage(myMsg);       
            // resultMap.put('Message','Funding Accounts added succesfully.');
            //resultMap.put('Warning','Funding Accounts added succesfully.');
            //resultMap.put('Message',myMsg);
            //resultMap.put('Success','Notification send successfully.');
            resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-24961'));
            resultMap.put('PageReference','/apex/AddInviteesView?id='+ eventId +'&flexTableName='+flexTableName);
            
         }else{
            System.debug('No records found');
            //resultMap.put('Error','Please select atleast one record.');
            resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-72161'));
         }
        
        return resultMap;   
    }
    
}