UtahLiveDataTest/src/objects/FileBatch__c.object
<CustomObject>
    <fields>
        <fullName>FirstApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>First Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>File_Batches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
                <value>
                    <fullName>2036</fullName>
                </value>
                <value>
                    <fullName>2037</fullName>
                </value>
                <value>
                    <fullName>2038</fullName>
                </value>
                <value>
                    <fullName>2039</fullName>
                </value>
                <value>
                    <fullName>2040</fullName>
                </value>
                <value>
                    <fullName>2041</fullName>
                </value>
                <value>
                    <fullName>2042</fullName>
                </value>
                <value>
                    <fullName>2043</fullName>
                </value>
                <value>
                    <fullName>2044</fullName>
                </value>
                <value>
                    <fullName>2045</fullName>
                </value>
                <value>
                    <fullName>2046</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SecondApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Second Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>File_Batches1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Uploaded</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Sent for Activation</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>File Batch</label>
    <nameField>
        <label>File Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>File Batches</pluralLabel>
    <recordTypes>
        <fullName>MSP</fullName>
        <active>true</active>
        <label>MSP</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FiscalYear__c.object
<CustomObject>
    <description>[Business] Stores the Fiscal Year information (Need to revisit)</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Passive</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MST: Fiscal Year</label>
    <nameField>
        <label>Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/MSPPaymentSchedule__c.object
<CustomObject>
    <fields>
        <fullName>FinalApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Final Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MSP_Payment_Schedules1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FirstApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>First Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MSP_Payment_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MSPFileBatch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MSP File Batch</label>
        <referenceTo>FileBatch__c</referenceTo>
        <relationshipLabel>MSP Payment Schedules</relationshipLabel>
        <relationshipName>MSP_Payment_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pathway__c</fullName>
        <label>Pathway</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MSP</fullName>
                </value>
                <value>
                    <fullName>1-12th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ScheduleDate__c</fullName>
        <label>Schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Payment Requests Created</fullName>
                </value>
                <value>
                    <fullName>First Approved</fullName>
                </value>
                <value>
                    <fullName>Final Approved</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Sent to FINET</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Final Approval</fullName>
                </value>
                <value>
                    <fullName>First Approval</fullName>
                </value>
                <value>
                    <fullName>Payments Created</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MSP Payment Schedule</label>
    <nameField>
        <label>MSP Payment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MSP Payment Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ProfileName__c</fullName>
        <inlineHelpText>Logged in user profile name</inlineHelpText>
        <label>Profile Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/RecreateMSPPaymentRequestsActionHandler.cls
global with sharing class RecreateMSPPaymentRequestsActionHandler extends GNT.FlexTableActionHandler{
    global override Map<String,Object> clickHandler() {
        Map<String,Object> resultMap = new Map<String,Object>();
        //Group mspGroup = [SELECT Id, Name FROM Group WHERE Type = 'Regular' AND Name = 'USBEFINOPS'];
        //List<GroupMember> mspGroupMembers = [SELECT Id, UserOrGroupId FROM GroupMember WHERE GroupId = :mspGroup.Id];
        List<User> mspGroupMembers = [SELECT Id FROM User WHERE ProfileName__c = 'EXE'];
        Set<String> mspGroupMemberIds = new Set<String>();
        for(User gm : mspGroupMembers){
            //mspGroupMemberIds.add(gm.UserOrGroupId);
            mspGroupMemberIds.add(gm.Id);
        }
        /*
        if(!mspGroupMemberIds.contains(UserInfo.getUserId())){
            resultMap.put('Error','You cannot create MSP payments request');
            return resultMap;
        }
        */
        MSPPaymentSchedule__c currentMps = [SELECT Id, FiscalYear__c, Status__c, ScheduleDate__c, FirstApprover__c, FinalApprover__c, Pathway__c FROM MSPPaymentSchedule__c WHERE Id IN :selectedRecordIds LIMIT 1];
        currentMps.Status__c = 'Processing';
        FileBatch__c fb = [SELECT Id, Status__c, FirstApprover__c, SecondApprover__c FROM FileBatch__c WHERE RecordType.Name = 'MSP' AND Status__c = 'Active' AND FiscalYear__c = :currentMps.FiscalYear__c];
        currentMps.MSPFileBatch__c = fb.Id;
        currentMps.FirstApprover__c = fb.FirstApprover__c;
        currentMps.FinalApprover__c = fb.SecondApprover__c;
        update currentMps;
        Database.executeBatch(new MSPPaymentsRecreateBatch(currentMps), 200);
        PageReference returnPage = Page.PhaseView;
        returnPage.getParameters().put('t','Monitoring'); 
        resultMap.put('PageReference',returnPage);
        return resultMap;
    }
}