UtahLiveDataTest/src/objects/FINETProgram__c.object
<CustomObject>
    <description>This is the object for the FINET program creation</description>
    <label>FINET Program</label>
    <nameField>
        <label>FINETProgram Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FINET Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RolesAndResponsibilities__c.object
<CustomObject>
    <description>[Business] Roles and Responsibilities defined for all the objects like Opportunity ,Application etc</description>
    <fields>
        <fullName>FINETProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FINETProgram</label>
        <referenceTo>r_prog__c</referenceTo>
        <relationshipLabel>Roles and Responsibilities</relationshipLabel>
        <relationshipName>RolesandResponsibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Roles and Responsibilities</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles and Responsibilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/FINETProgramRolesandRespCtrl.cls
public with sharing class FINETProgramRolesandRespCtrl{
    
    public String recordId{get;set;}
    public String pageTemplateName {get;set;}
    //public String savePage{get;set;}
    //public String cancelPage{get;set;}
    public List<GNT.DynamicLayoutDefaultValueHelper> listDefaultValues {get;set;}

    public FINETProgramRolesandRespCtrl(ApexPages.StandardController stdController) {
        recordId = ApexPages.CurrentPage().getParameters().get('id');
        pageTemplateName = 'Roles and Responsibilities 12';
        String recordTypeName = ApexPages.CurrentPage().getParameters().get('RecordType');
        System.debug('recordTypeName = '+recordTypeName);
        RecordType recordType = [
                    SELECT Id, DeveloperName 
                    FROM RecordType 
                    WHERE DeveloperName =: recordTypeName AND sObjectType =: AppUtils.getNamespacePrefix()+'RolesAndResponsibilities__c'];
         System.debug('recordType = ' + recordType);
                
        listDefaultValues = new List<GNT.DynamicLayoutDefaultValueHelper>();
         
        Id finetprogID = ApexPages.CurrentPage().getParameters().get('finetprogramid');
              
        if (finetprogID != null){
            GNT.DynamicLayoutDefaultValueHelper dv = new GNT.DynamicLayoutDefaultValueHelper(AppUtils.getNamespacePrefix()+'FINETProgram__c',finetprogID,true);            
            GNT.DynamicLayoutDefaultValueHelper dv1 = new GNT.DynamicLayoutDefaultValueHelper('RecordTypeId',recordType.Id,true);  
            listDefaultValues.add(dv);
            listDefaultValues.add(dv1);
        }
            
    }

    public string getKeyValueMap(){
        Map<String,String> keyValueMap = new Map<String,String>(); 
        return JSON.serialize(keyValueMap);
    }
}