UtahLiveDataTest/src/objects/FiscalYear__c.object
<CustomObject>
    <description>[Business] Stores the Fiscal Year information (Need to revisit)</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Passive</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MST: Fiscal Year</label>
    <nameField>
        <label>Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/MSPPaymentSchedule__c.object
<CustomObject>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pathway__c</fullName>
        <label>Pathway</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MSP</fullName>
                </value>
                <value>
                    <fullName>1-12th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ScheduleDate__c</fullName>
        <label>Schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Payment Requests Created</fullName>
                </value>
                <value>
                    <fullName>First Approved</fullName>
                </value>
                <value>
                    <fullName>Final Approved</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Sent to FINET</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Final Approval</fullName>
                </value>
                <value>
                    <fullName>First Approval</fullName>
                </value>
                <value>
                    <fullName>Payments Created</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MSP Payment Schedule</label>
    <nameField>
        <label>MSP Payment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MSP Payment Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/CreatePaymentScheduleHelper.cls
global with sharing class CreatePaymentScheduleHelper {
    
    global void createPaymentSchedule(String fiscalYear){
        List<MSPPaymentSchedule__c> mpss = new List<MSPPaymentSchedule__c>();
        Date paymentStartDate = Date.newInstance(Integer.valueOf(fiscalYear) - 1, 7, 15);
        for(Integer i = 0; i < 12; i++){
            MSPPaymentSchedule__c temp = new MSPPaymentSchedule__c(
                FiscalYear__c = fiscalYear,
                ScheduleDate__c = paymentStartDate.addMonths(i),
                Pathway__c = 'App12',
                Status__c = 'Created'
            );
            mpss.add(temp);
        }
        insert mpss;
    }
}