UtahLiveDataTest/src/objects/FOALead__c.object
<CustomObject>
    <description>[Business] Opportunities imported from Grants.gov in to this object for Grantee Functionality</description>
    <label>FOA Lead</label>
    <nameField>
        <displayFormat>LD-{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FOA Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/UserRegistration__c.object
<CustomObject>
    <description>[Business] Need more Detailed info from Swati Singh</description>
    <fields>
        <fullName>EINo__c</fullName>
        <inlineHelpText>An Employee Identification Number (EIN) is a nine-digit number provided by  Internal Revenue Service (IRS) which is often used by a business to open bank accounts, applying for business licenses, filing tax reports, filing electronic returns and taxes.</inlineHelpText>
        <label>Ob_Employee Identification Number (EIN)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <inlineHelpText>Enter valid email address.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <inlineHelpText>Registered Name as listed in DUN and BradStreet</inlineHelpText>
        <label>Organization Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <inlineHelpText>The Username must be in email format but the email format does not need to be a valid email address. For example xyz@abc.com</inlineHelpText>
        <label>User Name</label>
        <type>Email</type>
    </fields>
    <label>External Registration</label>
    <nameField>
        <displayFormat>RG-{000000}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Registration</pluralLabel>
    <recordTypes>
        <fullName>Reviewer</fullName>
        <active>true</active>
        <label>Reviewer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestExternalRegistrationCOIAgreeHelper.cls
@isTest
private class TestExternalRegistrationCOIAgreeHelper {

    static testMethod void testWhenClicked() {
        ExternalRegistrationCOIAgreeHelper extReg= new ExternalRegistrationCOIAgreeHelper();  
        //Test.startTest();
       // FOALead__c fOALead = TestHelper.getFOALead(true);
        UserRegistration__c uReg = new UserRegistration__c();
        uReg.OrganizationName__c ='TestORG';
        uReg.LastName__c = 'Betty';
        uReg.username__c = System.now().millisecond() + 'test@123test.com';
        uReg.EINo__c = Math.Random();
        uReg.Email__c = 'test15@test.com';
        //uReg.RecordType.DeveloperName = 'Reviewer';
        insert uReg;
         Test.startTest();
        
     
         
         ApexPages.StandardController sc = new ApexPages.standardController(uReg);
         ApexPages.currentPage().getParameters().put('Id',uReg.Id);
       
         
    
        extReg.whenClicked();
        Test.stopTest();      
    }
}