UtahLiveDataTest/src/objects/FOALead__c.object
<CustomObject>
    <description>[Business] Opportunities imported from Grants.gov in to this object for Grantee Functionality</description>
    <fields>
        <fullName>CFDANumber__c</fullName>
        <label>CFDA Number</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FundingOpportunityNumber__c</fullName>
        <label>Funding Opportunity Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>FOA Lead</label>
    <nameField>
        <displayFormat>LD-{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FOA Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/STGFOALead__c.object
<CustomObject>
    <description>[Business]  All the Opportunities migrated from the Grant.gov are stored in this staging table</description>
    <fields>
        <fullName>CFDANumber__c</fullName>
        <label>CFDA Number</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FundingOpportunityNumber__c</fullName>
        <externalId>true</externalId>
        <label>Funding Opportunity Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>STG: FOA Lead</label>
    <nameField>
        <displayFormat>STGLEAD-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>STG FOA Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestStagingLeadsToLeadsBatch.cls
@isTest
private class TestStagingLeadsToLeadsBatch{

    static testMethod void myUnitTest() {
        /*
        User u = TestHelper.getAdminUser(true);
        STGFOALead__c stgfoLead = null;
        FOALead__c foaLead = null;
        
        system.runAs(u) {
            // skip unwanted triggers
            AccountTriggerHelper.skipAll = true;
            ContactTriggerHelper.skiptrigger = true;
            UserRegistrationTriggerHelper.skipTrigger = true;
            UserTriggerHelper.skipTrigger = true;
            
            stgfoLead = new STGFOALead__c(FundingOpportunityNumber__c = 'Test - 123',CFDANumber__c='12.300');
            insert stgfoLead;
            
            foaLead = TestHelper.getFOALead(true);
            GNT.KeyValueStoreHelper.setTextValue('IntegrationSupportEmailAddress','abc@gmail',true);
            Test.startTest();
         
            StagingLeadsToLeadsBatch ctrl= new StagingLeadsToLeadsBatch();
            Database.executeBatch(ctrl);

            Test.stopTest();
        }
    */
    }
    
    static testMethod void myUnitTest2() {
        /*
        User u = TestHelper.getAdminUser(true);
        STGFOALead__c stgfoLead = null;
        FOALead__c foaLead = null;
        
        system.runAs(u) {
            // skip unwanted triggers
            AccountTriggerHelper.skipAll = true;
            ContactTriggerHelper.skiptrigger = true;
            UserRegistrationTriggerHelper.skipTrigger = true;
            UserTriggerHelper.skipTrigger = true;
            
            stgfoLead = new STGFOALead__c(FundingOpportunityNumber__c = 'Test - 123',CFDANumber__c='12.300');
            insert stgfoLead;
            
            foaLead = TestHelper.getFOALead(true);
            foaLead.FundingOpportunityNumber__c=stgfoLead.FundingOpportunityNumber__c;
            update foaLead;
            
            Test.startTest();
            StagingLeadsToLeadsBatch ctrl= new StagingLeadsToLeadsBatch();
            Database.executeBatch(ctrl);
            Test.stopTest();
        }
    */
    }
}