UtahLiveDataTest/src/objects/FOALead__c.object
<CustomObject>
    <description>[Business] Opportunities imported from Grants.gov in to this object for Grantee Functionality</description>
    <fields>
        <fullName>DaysLeft__c</fullName>
        <formula>IF( ApplicationsDueDate__c &gt; TODAY() ,ApplicationsDueDate__c - TODAY(),0)</formula>
        <label>Days Left</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Lead</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Qualified Lead</fullName>
                </value>
                <value>
                    <fullName>Rejected Lead</fullName>
                </value>
                <value>
                    <fullName>Converted to Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FOA Lead</label>
    <nameField>
        <displayFormat>LD-{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FOA Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ConvertToQualifiedLeadHelper.cls
global with sharing class ConvertToQualifiedLeadHelper extends GNT.DynamicLayoutActionRedirect {
    
    global override PageReference whenClicked(){      
        String ns = AppUtils.getNamespacePrefix();
        List<String> errors = new List<String>(); 
        Id recordId = apexpages.currentpage().getparameters().get('id');
        FOALead__c objFoaLead = [SELECT Id,DaysLeft__c,Status__c FROM FOALead__c WHERE id =: recordId];
        if(objFoaLead.DaysLeft__c == 0){
            errors.add('Lead cannot be Qualified if Application deadline is less than Today');
            errors.add(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-59900'));
        }
        if(errors.size() > 0){
            for(String error: errors){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, error));
             }
        } else{
        	objFoaLead.Status__c = 'Qualified Lead';
        	update objFoaLead;
        //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Converted to Qualified Lead'));
        	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('P02-GRNTR-13701')));  
       	 	PageReference  returnPage = new PageReference('/apex/FOALeadView?id='+recordId); 
        	returnPage.setRedirect(true);
        	return returnPage;
        }
        return null;    
    }
}