UtahLiveDataTest/src/objects/Form__c.object
<CustomObject>
    <description>[Business] object represents forms on grants.gov1</description>
    <fields>
        <fullName>TemplateName__c</fullName>
        <label>Template Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Application Detail (FORMS)</label>
    <nameField>
        <displayFormat>FN-{00000}</displayFormat>
        <label>Form</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/SF425FormViewCtrl.cls
public with sharing class SF425FormViewCtrl {
    
    public ID recordId{get;set;}
    public String pageTemplateName {get;set;}
    //Form__c frmobj {get;set;}
    
    public SF425FormViewCtrl (ApexPages.StandardController stdController){
        recordId = ApexPages.CurrentPage().getParameters().get('id'); 
        pageTemplateName = ApexPages.CurrentPage().getParameters().get('templateName');
        //frmobj.TemplateName__c=pageTemplateName;
    }
     
    public string getKeyValueMap(){
        Map<String,String> keyValueMap = new Map<String,String>();
        keyValueMap.put('SF425FormId',recordId);
        keyValueMap.put('SF425FormTemplate',pageTemplateName);
        return JSON.serialize(keyValueMap);
    }
}