UtahLiveDataTest/src/objects/FundingAccount__c.object
<CustomObject>
    <description>[Business] Funding account details Funding accounts are created from Funding sources</description>
    <fields>
        <fullName>FundingSource__c</fullName>
        <label>Funding Source</label>
        <referenceTo>FundingSource__c</referenceTo>
        <relationshipLabel>Funding Accounts</relationshipLabel>
        <relationshipName>Funding_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Funding Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingSource__c.object
<CustomObject>
    <description>[Business] Details of the Funding sources which further creates Funding accounts</description>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingSourceBudgetCategory__c.object
<CustomObject>
    <description>[Business] This is junction object for Funding Sources and Budget Categories</description>
    <fields>
        <fullName>FundingSource__c</fullName>
        <label>Funding Source</label>
        <referenceTo>FundingSource__c</referenceTo>
        <relationshipLabel>Funding Source Budget Category</relationshipLabel>
        <relationshipName>Funding_Source_Budget_Category</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Source Budget Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Source Budget Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/FundingSourceSubmissionHelper.cls
global with sharing class FundingSourceSubmissionHelper extends GNT.DynamicLayoutActionRedirect {
    global override PageReference whenClicked(){
        Savepoint sp = Database.setSavepoint();
        List<String> errors = new List<String>();   
        try{
            Id recordId = apexpages.currentpage().getparameters().get('id');
            FundingSource__c funsource = [select id,Name,Title__c from FundingSource__c where Id =:recordId];
            List<FundingAccount__c> funaccnt = [SELECT id,FundingSource__c FROM FundingAccount__c WHERE FundingSource__c =: recordId];
            List<FundingSourceBudgetCategory__c> funsourcbc = [SELECT id,FundingSource__c FROM FundingSourceBudgetCategory__c WHERE FundingSource__c =: recordId];
            if(funaccnt.size() < 1){
                    // errors.add ('Please add atleast one Funding Account to Submit for Approval');
                    errors.add (GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTE-80329'));
                    
                }
            if(funsourcbc.size() < 1){
                    // errors.add ('Add atleast one Funding Source Budget Category to Submit for Approval');
                    errors.add (GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-95122'));
                    
                }
            if(errors.size() > 0){
                for(String error: errors){
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, error));
                } 
            }
            else{
            GNT.TaskCreationHandler.createApprovalProcessTasks(funsource.Id, 'Review Funding Source', funsource.Title__c, null, System.TODAY() + 7,funsource.Title__c,true);         
            // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Funding Source has been submitted successfully.'));
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-48767')));
            PageReference  pageref = Page.FundingSourceView;   
            pageref.getParameters().put('Id',recordId);
            pageref.setRedirect(true);  
            return pageref;
          }
          return null;
       }
         catch(Exception e){
         Database.rollback(sp);
         ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
         return null;   
        }
    }

}