UtahLiveDataTest/src/objects/FundingAccount__c.object
<CustomObject>
    <description>[Business] Funding account details Funding accounts are created from Funding sources</description>
    <fields>
        <fullName>FundingSource__c</fullName>
        <label>Funding Source</label>
        <referenceTo>FundingSource__c</referenceTo>
        <relationshipLabel>Funding Accounts</relationshipLabel>
        <relationshipName>Funding_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Funded</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Funding Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingSource__c.object
<CustomObject>
    <description>[Business] Details of the Funding sources which further creates Funding accounts</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted For Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingSourceBudgetCategory__c.object
<CustomObject>
    <description>[Business] This is junction object for Funding Sources and Budget Categories</description>
    <fields>
        <fullName>FundingSource__c</fullName>
        <label>Funding Source</label>
        <referenceTo>FundingSource__c</referenceTo>
        <relationshipLabel>Funding Source Budget Category</relationshipLabel>
        <relationshipName>Funding_Source_Budget_Category</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Source Budget Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Source Budget Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestFundingSourceSubmissionHelper.cls
@isTest
public class TestFundingSourceSubmissionHelper {

    static testMethod void myUnitTest() {
         User u = new User(Id=UserInfo.getUserId());
         FundingSource__c funsource = null;
         System.runAs(u){
         	funsource = TestHelper.getFundingSource(true);
         	funsource.Status__c = 'Created';
         	funsource.Title__c = 'funding source1';
         	update funsource;
         	FundingAccount__c funaccnt = Testhelper.getFundingAccount(true,funsource.id);
         	FundingSourceBudgetCategory__c fsourcebc = new FundingSourceBudgetCategory__c(Name='fsbc',FundingSource__c=funsource.id);
         	insert fsourcebc;
         }
         Test.startTest();         
         FundingSourceSubmissionHelper Fs = new FundingSourceSubmissionHelper();
         ApexPages.currentPage().getParameters().put('id',funsource.Id);  
         Fs.whenClicked();
         Test.stopTest(); 
    }
    static testMethod void myUnitTest1() {
         User u = new User(Id=UserInfo.getUserId());
         FundingSource__c funsource = null;
         System.runAs(u){
         	funsource = TestHelper.getFundingSource(true);
         	funsource.Status__c = 'Created';
         	funsource.Title__c = 'funding source1';
         	update funsource;
         }
         Test.startTest();         
         FundingSourceSubmissionHelper Fs = new FundingSourceSubmissionHelper();
         ApexPages.currentPage().getParameters().put('id',funsource.Id);  
         Fs.whenClicked();
         Test.stopTest(); 
    }
}