UtahLiveDataTest/src/objects/FundingSource__c.object
<CustomObject>
    <description>[Business] Details of the Funding sources which further creates Funding accounts</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Funder Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Federal</fullName>
                    <default>true</default>
                    <label>Federal</label>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>NGO</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestFundingSourceViewCtrl.cls
@isTest
public class TestFundingSourceViewCtrl {

    static testMethod void myUnitTest1() {
          
          User u = TestHelper.getAdminUser(true);
          System.runAs(u){
          	 FundingSource__c funsource = TestHelper.getFundingSource(true);
          	 funsource.Type__c = 'Federal';
          	 update funsource;
             Test.startTest();
             ApexPages.StandardController sc = new ApexPages.standardController(funsource);
             ApexPages.currentPage().getParameters().put('Id',funsource.id);
             FundingSourceViewCtrl ctrl = new FundingSourceViewCtrl(sc);
             ctrl.getKeyValueMap();
             Test.stopTest();
        }
        
    }
    static testMethod void myUnitTest2() {
          
          User u = TestHelper.getAdminUser(true);
          System.runAs(u){
          	 FundingSource__c funsource = TestHelper.getFundingSource(true);
          	 funsource.Type__c = 'State';
          	 update funsource;
             Test.startTest();
             ApexPages.StandardController sc = new ApexPages.standardController(funsource);
             ApexPages.currentPage().getParameters().put('Id',funsource.id);
             FundingSourceViewCtrl ctrl = new FundingSourceViewCtrl(sc);
             ctrl.getKeyValueMap();
             Test.stopTest();
        }
        
    }
}