UtahLiveDataTest/src/objects/FundingAccount__c.object
<CustomObject>
    <description>[Business] Funding account details Funding accounts are created from Funding sources</description>
    <fields>
        <fullName>FundingSource__c</fullName>
        <label>Funding Source</label>
        <referenceTo>FundingSource__c</referenceTo>
        <relationshipLabel>Funding Accounts</relationshipLabel>
        <relationshipName>Funding_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingSource__c.object
<CustomObject>
    <description>[Business] Details of the Funding sources which further creates Funding accounts</description>
    <label>Funding Source</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/FundingAccountEditCtrlTest.cls
@isTest
public class FundingAccountEditCtrlTest {
    static testMethod void someTest() {
        
        FundingSource__c fundSource = null;
        FundingAccount__c fundAcc = null;
        
        fundSource = TestHelper.getFundingsource(true);
        fundAcc = TestHelper.getFundingAccount(true,fundSource.Id);     
         
         Test.startTest();
         ApexPages.StandardController sc = new ApexPages.standardController(fundAcc);
         ApexPages.currentPage().getParameters().put('id',fundAcc.Id);
         ApexPages.currentPage().getParameters().put('fundingSourceId',fundSource.Id);
         FundingAccountEditCtrl e = new FundingAccountEditCtrl(sc);
         e.getKeyValueMap();
         Test.stopTest();
    }

}