UtahLiveDataTest/src/objects/FundingAccount__c.object
<CustomObject>
    <description>[Business] Funding account details Funding accounts are created from Funding sources</description>
    <fields>
        <fullName>FundingSource__c</fullName>
        <label>Funding Source</label>
        <referenceTo>FundingSource__c</referenceTo>
        <relationshipLabel>Funding Accounts</relationshipLabel>
        <relationshipName>Funding_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingAccountBudgetCategory__c.object
<CustomObject>
    <description>[Business] Mapping Object for Funding Sources and Budget Categories</description>
    <fields>
        <fullName>AmountAllocated__c</fullName>
        <description>Amount Allocated from Funding Source for each line item of category</description>
        <label>Allocated Amount(Obsolete)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FundingAccount__c</fullName>
        <label>Funding Account</label>
        <referenceTo>FundingAccount__c</referenceTo>
        <relationshipLabel>Funding Account Budget Category</relationshipLabel>
        <relationshipName>Funding_Account_Budget_Category</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FundingSourceBudgetCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Source Budget Category</label>
        <referenceTo>FundingSourceBudgetCategory__c</referenceTo>
        <relationshipLabel>Funding Account Budget Category</relationshipLabel>
        <relationshipName>Funding_Account_Budget_Category</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Account Budget Category</label>
    <nameField>
        <displayFormat>FABC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Account Budget Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingSource__c.object
<CustomObject>
    <description>[Business] Details of the Funding sources which further creates Funding accounts</description>
    <label>Funding Source</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/FundingSourceBudgetCategory__c.object
<CustomObject>
    <description>[Business] This is junction object for Funding Sources and Budget Categories</description>
    <fields>
        <fullName>AmountAllocated__c</fullName>
        <description>This is to calculate Total Allocated Amount * Allocated Percentage</description>
        <formula>AllocationPercentage__c  *  TotalAmountAllocated__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Allocated(Obsolete)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FundingSource__c</fullName>
        <label>Funding Source</label>
        <referenceTo>FundingSource__c</referenceTo>
        <relationshipLabel>Funding Source Budget Category</relationshipLabel>
        <relationshipName>Funding_Source_Budget_Category</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Source Budget Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Source Budget Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestFundingAccntBudCatTriggerHelper.cls
@isTest
public class TestFundingAccntBudCatTriggerHelper {

      static testMethod void testFundingAccntBudCatTrigger() {
      
          FundingSource__c fundSrc = TestHelper.getFundingSource(true);
          FundingAccount__c fundAcc = TestHelper.getFundingAccount(true,fundSrc.Id);
         
          
          FundingSourceBudgetCategory__c fundSrcBudCat = new FundingSourceBudgetCategory__c(FundingSource__c=fundSrc.Id);
          FundingAccountBudgetCategory__c fundAccBudCat = new FundingAccountBudgetCategory__c(FundingAccount__c=fundAcc.Id);
          insert fundAccBudCat;
          fundAccBudCat.AmountAllocated__c=5000;
          fundAccBudCat.FundingSourceBudgetCategory__c=fundSrcBudCat.Id;
          update fundAccBudCat;
      }
}