UtahLiveDataTest/src/objects/GoalObjective__c.object
<CustomObject>
    <description>Goals and Objectives object for Performance management</description>
    <label>Goal Objective</label>
    <nameField>
        <displayFormat>GOB-{0000}</displayFormat>
        <label>Goals and Objectives Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PerformanceMeasure__c.object
<CustomObject>
    <description>Performance Measure as part of Performance Management</description>
    <fields>
        <fullName>Objective__c</fullName>
        <label>Goal and Objective</label>
        <referenceTo>GoalObjective__c</referenceTo>
        <relationshipLabel>Performance Measures</relationshipLabel>
        <relationshipName>Performance_Measures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Performance Measure</label>
    <nameField>
        <displayFormat>PMM-{0000}</displayFormat>
        <label>Performance Measure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performance Measures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestPerformanceMeasureTrigger.cls
@isTest
private class TestPerformanceMeasureTrigger {
	
	@isTest static void test_method_one() {
		PerformanceMeasureTriggerHelper.skipTrigger = true;
		GoalObjectiveTriggerHelper.skipTrigger = true;
		GoalObjective__c g = new GoalObjective__c();
		insert g;



		PerformanceMeasure__c p = new PerformanceMeasure__c(Objective__c = g.Id);
		insert p;
	}
	
	@isTest static void test_method_two() {
		// Implement test code
	}
	
}