UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/GrantServiceArea__c.object
<CustomObject>
    <description>[Business] Association of Grant with the service area</description>
    <fields>
        <fullName>Grant__c</fullName>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipName>GrantServiceAreas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grant Project Area</label>
    <nameField>
        <displayFormat>GSA-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Project Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestGrantProjectAreaViewCtrl.cls
@isTest
private with sharing class TestGrantProjectAreaViewCtrl{
    static testMethod void testController() {
        UserTriggerHelper.skipTrigger = true; 
        GrantTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(true);
        GrantServiceArea__c grantServArea= null;
        Grant__c grant = null;
        
     
        System.runAs(u){
            AwardTriggerHelper.skipTrigger=true;
            grant = TestHelper.getGrant(true);
            grantServArea = new GrantServiceArea__c(Grant__c=grant.Id);
            insert grantServArea;
            
        }      
            Test.startTest();
            ApexPages.StandardController sc = new ApexPages.standardController(grant);
            ApexPages.currentPage().getParameters().put('Id',grantServArea.id);
            GrantProjectAreaViewCtrl ctrl = new GrantProjectAreaViewCtrl(sc);
            ctrl.getKeyValueMap();
            Test.stopTest();
        }
        
    }