UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>InternalOrganization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Grants (Internal Organization)</relationshipLabel>
        <relationshipName>Grants1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ObjectCode__c</fullName>
        <label>Object Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramCode__c</fullName>
        <label>Program Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProgramCode</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed/Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/MSPPaymentSchedule__c.object
<CustomObject>
    <fields>
        <fullName>FinalApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Final Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MSP_Payment_Schedules1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FirstApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>First Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MSP_Payment_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ScheduleDate__c</fullName>
        <label>Schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Payment Requests Created</fullName>
                </value>
                <value>
                    <fullName>First Approved</fullName>
                </value>
                <value>
                    <fullName>Final Approved</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Sent to FINET</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Final Approval</fullName>
                </value>
                <value>
                    <fullName>First Approval</fullName>
                </value>
                <value>
                    <fullName>Payments Created</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MSP Payment Schedule</label>
    <nameField>
        <label>MSP Payment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MSP Payment Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/PaymentRequest__c.object
<CustomObject>
    <description>[Business] Defines the details of for the Payment request.Payment request is done when award is already awarded and the Grantee wants to make use of the funds</description>
    <fields>
        <fullName>CatchUp__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Catch Up</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MSPPaymentSchedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MSP Payment Schedule</label>
        <referenceTo>MSPPaymentSchedule__c</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MSPTotal__c</fullName>
        <formula>PaymentAmount__c + CatchUp__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MSPTotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PaymentAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProgramName__c</fullName>
        <formula>Grant__r.Program__r.ProgramName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Approval 1</fullName>
                </value>
                <value>
                    <fullName>Approval 2</fullName>
                </value>
                <value>
                    <fullName>Approval 3</fullName>
                </value>
                <value>
                    <fullName>Approval 4</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Sent to FINET</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Request</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/MSPPaymentScheduleCtrl.cls
public with sharing class MSPPaymentScheduleCtrl {
    public String recordId{get;set;}
    public String packageId{get;set;}
    public PageReference deleteURL{get;set;}
    public String paymentJSON{get;set;}
    public Boolean renderForFirstApprover{get;set;}
    public Boolean renderForFinalApprover{get;set;}
    public Boolean renderForSendToFinet{get;set;}

    public MSPPaymentScheduleCtrl(ApexPages.StandardController stdController) {
        recordId = ApexPages.CurrentPage().getParameters().get('id');
        packageId = null;
        deleteURL = null;
        MSPPaymentSchedule__c mps = [SELECT Id, Status__c, FinalApprover__c, FirstApprover__c, ScheduleDate__c FROM MSPPaymentSchedule__c WHERE Id = :recordId];

        if(mps.Status__c == 'Payment Requests Created' && mps.FirstApprover__c == UserInfo.getUserId()){
            renderForFirstApprover = true;
        }else{
            renderForFirstApprover = false;
        }

        if(mps.Status__c == 'First Approved' && mps.FinalApprover__c == UserInfo.getUserId()){
            renderForFinalApprover = true;
        }else{
            renderForFinalApprover = false;
        }

        if(mps.Status__c == 'Final Approved' && mps.FinalApprover__c == UserInfo.getUserId()){
            renderForSendToFinet = true;
        }else{
            renderForSendToFinet = false;
        }

        List<PaymentRequest__c> mpas = [SELECT Id, MSPTotal__c, PaymentAmount__c, CatchUp__c, Grant__r.Program__r.ProgramName__c, Grant__r.InternalOrganization__r.Name, Grant__r.InternalOrganization__r.LEA_Id__c, Grant__r.ProgramCode__c, Grant__r.ObjectCode__c FROM PaymentRequest__c WHERE MSPPaymentSchedule__c = :recordId ORDER BY Grant__r.InternalOrganization__r.LEA_Id__c, Grant__r.Program__r.ProgramKey__c];
        List<PaymentWrapper> mpsWrapper = new List<PaymentWrapper>();
        
        for(PaymentRequest__c mp : mpas){
            PaymentWrapper temp = new PaymentWrapper();
        	temp.programName = mp.Grant__r.Program__r.ProgramName__c;
        	temp.subRecipientName = mp.Grant__r.InternalOrganization__r.Name;
            temp.paymentAmount = mp.PaymentAmount__c;
            temp.catchUp = mp.CatchUp__c;
            temp.objectCode = mp.Grant__r.ObjectCode__c;
            temp.programCode = mp.Grant__r.ProgramCode__c;
            temp.leaId = mp.Grant__r.InternalOrganization__r.LEA_Id__c;
            temp.total = mp.MSPTotal__c;
            mpsWrapper.add(temp);
        }
        paymentJSON = JSON.serialize(mpsWrapper);
    }

    public PageReference approve(){
        MSPPaymentSchedule__c mps = [SELECT Id, Status__c, FinalApprover__c, FirstApprover__c, ScheduleDate__c FROM MSPPaymentSchedule__c WHERE Id = :recordId];
        if(mps.Status__c == 'Payment Requests Created' && UserInfo.getUserId() == mps.FirstApprover__c){
            firstApprove(mps);
        }else if(mps.Status__c == 'First Approved' && UserInfo.getUserId() == mps.FinalApprover__c){
            finalApprove(mps);
        }else{
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please refresh page'));
            return null;
        }
        PageReference pageref = Page.PhaseView;
        pageref.getParameters().put('t','Monitoring');
        pageref.setRedirect(true);
        return pageref; 
    }
    
    public PageReference reject(){
        MSPPaymentSchedule__c mps = [SELECT Id, Status__c, FinalApprover__c, FirstApprover__c, ScheduleDate__c FROM MSPPaymentSchedule__c WHERE Id = :recordId];
        if(mps.Status__c == 'Payment Requests Created' && UserInfo.getUserId() == mps.FirstApprover__c){
            updateFirstApprovalTask();
        }else if(mps.Status__c == 'First Approved' && UserInfo.getUserId() == mps.FinalApprover__c){
            updateFinalApprovalTask();
        }else{
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please refresh page'));
            return null;            
        }
        mps.Status__c = 'Rejected ';
        update mps;
        PageReference pageref = Page.PhaseView;
        pageref.getParameters().put('t','Monitoring');
        pageref.setRedirect(true);
        return pageref; 
    }    
    

    public PageReference cancel(){
        PageReference pageref = Page.PhaseView;
        pageref.getParameters().put('t','Monitoring');
        pageref.setRedirect(true);
        return pageref; 
    }

    public PageReference sendToFinet(){
        MSPPaymentSchedule__c mps = [SELECT Id, Status__c, FinalApprover__c, FirstApprover__c, ScheduleDate__c FROM MSPPaymentSchedule__c WHERE Id = :recordId];
        mps.Status__c = 'Processing';
        update mps;
        Database.executeBatch(new MSPPaymentSendToFinetActionBatch(mps), 200);
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Sent to FINET'));
        PageReference pageref = Page.PhaseView;
        pageref.getParameters().put('t','Monitoring');
        pageref.setRedirect(true);
        return pageref; 
    }

    private void firstApprove(MSPPaymentSchedule__c mps){
        mps.Status__c = 'First Approved';
        update mps;
        updateFirstApprovalTask();
        List<Task> finalApprovalTask = GNT.TaskCreationHandler.createTasks(mps.FinalApprover__c,
            mps.Id,'MSP Payment Final Approval',
            String.valueOf(mps.ScheduleDate__c) + ' MSP Payments Final Approval', null, false, null,
            'Approval', String.valueOf(mps.ScheduleDate__c) + ' MSP Payments Final Approval', false
        );

        if(finalApprovalTask != null && finalApprovalTask.size() > 0) {
            insert finalApprovalTask[0];
        }
    }

    private void finalApprove(MSPPaymentSchedule__c mps){
        updateFinalApprovalTask();
        mps.Status__c = 'Final Approved';
        update mps;

    }

    private void updateFirstApprovalTask(){
        List<Task> creationTaskList = [SELECT Id, Status FROM Task WHERE WhatId = :recordId AND OwnerId = :UserInfo.getUserId() AND GNT__TaskAction__c = 'MSP Payment First Approval'];
        if(creationTaskList != null && creationTaskList.size() > 0){
            for(Task t : creationTaskList){
                t.Status = 'Completed';
            }
        }

        update creationTaskList;
    }

    private void updateFinalApprovalTask(){
        List<Task> creationTaskList = [SELECT Id, Status FROM Task WHERE WhatId = :recordId AND OwnerId = :UserInfo.getUserId() AND GNT__TaskAction__c = 'MSP Payment Final Approval'];
        if(creationTaskList != null && creationTaskList.size() > 0){
            for(Task t : creationTaskList){
                t.Status = 'Completed';
            }
        }

        update creationTaskList;
    }

    class PaymentWrapper{
    	public String programName{get;set;}
    	public String subRecipientName{get;set;}
        public Decimal paymentAmount{get;set;}
        public Decimal catchUp{get;set;}
        public String programCode{get;set;}
        public String objectCode{get;set;}
        public String leaId{get;set;}
        public Decimal total{get;set;}
    }
}