UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/RiskAssessment__c.object
<CustomObject>
    <description>[Business] This will be part of Grant Making Module.</description>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Risk Assessment</relationshipLabel>
        <relationshipName>Risk_Assessment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Risk Assessment</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk Assessment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestRiskAssessmentRatingEditCtrl.cls
@isTest
private with sharing class TestRiskAssessmentRatingEditCtrl{
    static testMethod void testController() {
        UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
        
        System.runAs(u){
        
            GrantTriggerHelper.skipTrigger = true;
            RiskAssessment__c riskAssess = new RiskAssessment__c();
            insert riskAssess;
        
            Grant__c grant = TestHelper.getGrant(true);
            
            Test.startTest();
            ApexPages.StandardController sc = new ApexPages.standardController(riskAssess);
            ApexPages.currentPage().getParameters().put('Id',riskAssess.id);
            ApexPages.currentPage().getParameters().put('grantid',grant.id);
            RiskAssessmentRatingEditCtrl ctrl = new RiskAssessmentRatingEditCtrl(sc);
            ctrl.getKeyValueMap();
            Test.stopTest();
        
        }
        
    }
}