UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>AssignedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Grants4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GranteePOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grantee POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Grants1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectDirector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed/Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/SiteVisit__c.object
<CustomObject>
    <description>[Business] This object is used to store all the information related to the Site Visits which is a Post Award Activity.</description>
    <fields>
        <fullName>AssignedTo__c</fullName>
        <formula>Grant__r.AssignedTo__r.FirstName &amp; &quot; &quot; &amp; Grant__r.AssignedTo__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Grant Assigned To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipLabel>Site Visits</relationshipLabel>
        <relationshipName>Site_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GranteePOC__c</fullName>
        <formula>Grant__r.GranteePOC__r.FirstName &amp; &apos;&apos; &amp;  Grant__r.GranteePOC__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Grantee POC</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsSiteVisitFinalized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Site Visit Finalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectDirector__c</fullName>
        <formula>Grant__r.ProjectDirector__r.FirstName &amp; &quot; &quot; &amp; Grant__r.ProjectDirector__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Director</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SiteVisitor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Visitor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Site_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Report Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Planned and Submitted to Subrecipient</fullName>
                </value>
                <value>
                    <fullName>Visited</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Report Submitted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Reviewed by Grantor</fullName>
                </value>
                <value>
                    <fullName>Sent to Subrecipient</fullName>
                </value>
                <value>
                    <fullName>Feedback from Subrecipient</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VisitDateandTime__c</fullName>
        <description>Visit Start Date and Time</description>
        <inlineHelpText>Visit Start Date and Time</inlineHelpText>
        <label>Visit Start Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/SiteVisitSchedule__c.object
<CustomObject>
    <description>[Business] Site Visit Schedule is stored on this specific object</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Site Visit Schedule</label>
    <nameField>
        <displayFormat>S-{YYYY}-{0000}</displayFormat>
        <label>Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visit Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/FinalizeScheduleCtrl.cls
global with sharing class FinalizeScheduleCtrl extends GNT.DynamicLayoutActionRedirect{

    
    global override PageReference whenClicked(){
        Savepoint sp = Database.setSavepoint();
        Id recordId = layoutHolder.getPrimarySObject().Id;        
        SiteVisitSchedule__c siteSchedule = (SiteVisitSchedule__c)layoutHolder.recordMap.get(AppUtils.getNamespacePrefix() + 'SiteVisitSchedule__c');
        try{
            siteSchedule.status__c = 'Finalized';
            update siteSchedule;
            List <SiteVisit__c> siteVisits = [SELECT Id,Name, IsSiteVisitFinalized__c,SiteVisitor__r.email,SiteVisitor__r.name,grant__r.Name,SiteVisitor__c,
                                                   grant__r.GranteePOC__r.email,grant__r.AssignedTo__r.email,grant__r.ProjectDirector__r.email,VisitDateandTime__c
                                                       FROM SiteVisit__c];            
        
        }catch(Exception e){
            Database.rollback(sp);
            //errorMsg = e.getMessage();
            return null;
        }
        
        PageReference  p = Page.SiteVisitScheduleView;
        p.getParameters().put('id',recordId);
        p.setRedirect(true);
        return p;
     }
      
      /* Pranjali : The below method is not used in this class hence commenting it */
      /*
      private void sendEmailNUpdateSiteVisit(List<SiteVisit__c> siteVisits){
          //Create a master list to hold the emails we'll send
          List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
          List<SiteVisit__c> siteVisitList  =  new List<SiteVisit__c>();
          List<GNT.TaskCreationHandler.TaskBulkClass> taskBulkList =  new List<GNT.TaskCreationHandler.TaskBulkClass> ();
          for(SiteVisit__c siteVisit : siteVisits){
             if(!siteVisit.IsSiteVisitFinalized__c){
                  Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                  List<String> sendTo = new List<String>();
                  if(siteVisit.SiteVisitor__r.email != null)
                      sendTo.add(siteVisit.SiteVisitor__r.email);
                  List<String>sendCC = new List<String>();
                  if(siteVisit.grant__r.GranteePOC__r.email != null)
                      sendCC.add(siteVisit.grant__r.GranteePOC__r.email);
                  if(siteVisit.grant__r.AssignedTo__r.email != null)
                      sendCC.add(siteVisit.grant__r.AssignedTo__r.email);
                  if(siteVisit.grant__r.ProjectDirector__r.email != null)
                      sendCC.add(siteVisit.grant__r.ProjectDirector__r.email);
                  mail.setToAddresses(sendTo); 
                  mail.setCCAddresses(sendCC);     
                  mail.setSubject('Site Visit finalized for Grant '+siteVisit.grant__r.Name);
                  mail.setHTMLBody('Hello '+ siteVisit.SiteVisitor__r.name +', <br/> Site visit scheduled at '+ siteVisit.VisitDateandTime__c + '<br/> Thank You');
                  mails.add(mail);
                  
                  // Check isSiteVisitFinalized to true
                  siteVisit.IsSiteVisitFinalized__c = true;
                  siteVisitList.add(siteVisit);
                  
                  GNT.TaskCreationHandler.TaskBulkClass taskBulkInstance = new GNT.TaskCreationHandler.TaskBulkClass();
                  taskBulkInstance.ownerUserId = siteVisit.SiteVisitor__c;
                  taskBulkInstance.recordId = siteVisit.Id;
                  taskBulkInstance.action = 'Submit Site Visit Report';
                  taskBulkInstance.recordName = siteVisit.Name;
                  taskBulkList.add(taskBulkInstance);              
              }  
          }
          // Send email
           if(mails != null && mails.size() > 0){
               Messaging.sendEmail(mails);
           }
          //update SiteVisit
          if(siteVisitList != null && siteVisitList.size() > 0){
              if(Schema.sObjectType.SiteVisit__c.isUpdateable()){
                 update siteVisitList;
              }
          }

          //Create Tasks
          GNT.TaskCreationHandler.createBulkTasks(taskBulkList, true);
      }    */
}