UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/TermCondition__c.object
<CustomObject>
    <description>[Business] Terms and Conditions for Grants ,Awards (The lookup to Package may not be required in this case )</description>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MST:Term and Condition</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestViewPaymentTermCondition.cls
@isTest
private class TestViewPaymentTermCondition {
	
	@isTest static void test_method_one() {
		PageReference pageRef = Page.TermConditionView;
		Test.setCurrentPage(pageRef);
		GrantTriggerHelper.skipTrigger = true;
		Grant__c grant = TestHelper.getGrant(true);
		TermCondition__c tc = new TermCondition__c();
		insert tc;
		ApexPages.currentPage().getParameters().put('grantId', grant.Id);
		ApexPages.currentPage().getParameters().put('gId', tc.Id);
		ViewPaymentTermConditionHandler v = new ViewPaymentTermConditionHandler();
		v.clickHandler();
	}
	
	@isTest static void test_method_two() {
		// Implement test code
	}
	
}