UtahLiveDataTest/src/objects/Grant__c.object
<CustomObject>
    <description>[Business] Stores all the grant related information a Grant can have multiple Awards only one award is active at any given point of time</description>
    <fields>
        <fullName>IssueDate__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodEndDate__c</fullName>
        <label>Project Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectPeriodStartDate__c</fullName>
        <label>Project Period Start Date</label>
        <type>Date</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/TermCondition__c.object
<CustomObject>
    <description>[Business] Terms and Conditions for Grants ,Awards (The lookup to Package may not be required in this case )</description>
    <fields>
        <fullName>DueDateDays__c</fullName>
        <inlineHelpText>How many days after the end of the reporting period?</inlineHelpText>
        <label>Due Date Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                    <default>true</default>
                    <label>Fixed</label>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant</label>
        <referenceTo>Grant__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReportStartDate__c</fullName>
        <description>Used for Post Award Submission Report creation</description>
        <inlineHelpText>Budget Period Start Date - The reporting cycle should start from current Budget Period Start Date
Fixed Date - start from a fixed date</inlineHelpText>
        <label>Beginning Date</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget Period Start Date</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TaskAvailability__c</fullName>
        <description>The task will be made available to the grantee &apos;X&apos; number of days before the due date, based on the number entered here.</description>
        <inlineHelpText>Enter number of days prior to Due Date</inlineHelpText>
        <label>Task Availability</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>MST:Term and Condition</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <recordTypes>
        <fullName>Condition</fullName>
        <active>true</active>
        <label>Condition</label>
    </recordTypes>
    <recordTypes>
        <fullName>Term</fullName>
        <active>true</active>
        <description>Related to Awards ( Ramu to rename this object appropriately)</description>
        <label>Term</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestTermConditionViewCtrl.cls
@isTest
private class  TestTermConditionViewCtrl{
    
    static TermCondition__c obj; 
    static TermConditionViewCtrl tcViewCtrl;
        
    private static void setupData(boolean create, String recordType){
       UserTriggerHelper.skipTrigger=true;
       Grant__c grant = TestHelper.getGrant (false);
       grant.ProjectPeriodStartDate__c = Date.newInstance(2015,7,22);
       grant.ProjectPeriodEndDate__c = Date.newInstance(2015,9,24);
       grant.IssueDate__c=Date.newInstance(2015,6,14);
       insert grant;
       
       obj = TestHelper.getTermCondition(false, recordType);  
       obj.Grant__c = grant.Id;
       obj.ReportStartDate__c = 'Project Period Start Date';
       obj.Frequency__c = 'Monthly';
     //  obj.DueDateType__c = 'After';
       obj.DueDateDays__c = 5;
       obj.TaskAvailability__c = 5;
       insert obj;     
       Test.setCurrentPageReference(new PageReference('Page.BlankPage')); 
       System.currentPageReference().getParameters().put('recordType', recordType);
       ApexPages.CurrentPage().getParameters().put('id',obj.id);
       ApexPages.Standardcontroller sc123 = New ApexPages.StandardController(obj);
       tcViewCtrl = new TermConditionViewCtrl(sc123);
       tcViewCtrl.getKeyValueMap(); 
       tcViewCtrl.getListParams();
       
    }
    
    @isTest
    public static void testGetterSetter(){
    /*
        UserTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(true);
        System.runAs(u){
            GrantTriggerHelper.skipTrigger = true;
            AccountTriggerHelper.skipTrigger = true;
            Test.startTest();
            setupData(true, 'Term');
            Test.stopTest();
        }
        system.assertNotEquals(tcViewCtrl.getKeyValueMap(),null);
        */
    }
    @isTest
    public static void testGetterSetterCondition(){
    /*
        UserTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(true);
        System.runAs(u){
            GrantTriggerHelper.skipTrigger = true;
             AccountTriggerHelper.skipTrigger = true;
            Test.startTest();
            setupData(true, 'Condition');
            Test.stopTest();
        }
        system.assertNotEquals(tcViewCtrl.getKeyValueMap(),null);
        */
    }
    
    @isTest
    public static void testConditionApp(){
    /*
        UserTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(true);
        GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c','StateasGrantee');
        System.runAs(u){
            GrantTriggerHelper.skipTrigger = true;
             AccountTriggerHelper.skipTrigger = true;
             GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c','StateasGrantee');
             
             Grant__c grant = TestHelper.getGrant (false);
             grant.ProjectPeriodStartDate__c = Date.newInstance(2015,7,22);
             grant.ProjectPeriodEndDate__c = Date.newInstance(2015,9,24);
             grant.IssueDate__c=Date.newInstance(2015,6,14);
             insert grant;
       
             obj = TestHelper.getTermCondition(true,'Condition');  
             obj.Grant__c = grant.Id;
             update obj;   
       
             Test.startTest();
                GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c','StateasGrantee');
               System.currentPageReference().getParameters().put('recordType', 'Condition');
               ApexPages.CurrentPage().getParameters().put('id',obj.id);
               ApexPages.Standardcontroller sc123 = New ApexPages.StandardController(obj);
               tcViewCtrl = new TermConditionViewCtrl(sc123);
               tcViewCtrl.getKeyValueMap(); 
               Test.stopTest();
        }
        system.assertNotEquals(tcViewCtrl.getKeyValueMap(),null);
        */
    }
     @isTest
    public static void testGetterSetterConditionreporting (){
    /*
        UserTriggerHelper.skipTrigger=true;
        User u = TestHelper.getAdminUser(true);
        System.runAs(u){
            GrantTriggerHelper.skipTrigger = true;
             AccountTriggerHelper.skipTrigger = true;
            Test.startTest();
            setupData(true, 'Reporting Requirement');
            Test.stopTest();
        }
        system.assertNotEquals(tcViewCtrl.getKeyValueMap(),null);
        */
    }
    
    
    
}