UtahLiveDataTest/src/objects/IntegrationConfig__c.object
<CustomObject>
    <description>[Business] Stores Integration configuration</description>
    <fields>
        <fullName>Delimiter__c</fullName>
        <label>Delimiter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Comma</fullName>
                    <default>true</default>
                    <label>Comma</label>
                </value>
                <value>
                    <fullName>Tab</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProcessName__c</fullName>
        <description>Unique Process Name</description>
        <inlineHelpText>Unique Process Name</inlineHelpText>
        <label>Process Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CFG: CSV Integration</label>
    <nameField>
        <displayFormat>INTC-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/IntegrationDetail__c.object
<CustomObject>
    <description>[Business] Stores detail records of integration file</description>
    <fields>
        <fullName>DetailRecord__c</fullName>
        <label>Detail Record</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IntegrationHeader__c</fullName>
        <label>Integration Header</label>
        <referenceTo>IntegrationHeader__c</referenceTo>
        <relationshipName>IntegrationDetails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Re-Process</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IST: Integration Detail</label>
    <nameField>
        <displayFormat>INTD-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/IntegrationDetailConfig__c.object
<CustomObject>
    <description>[Business]  Integration Details Config contains the details of the Integration config</description>
    <fields>
        <fullName>FieldConfig__c</fullName>
        <inlineHelpText>Provide Json conffiguration. Ex: {&quot;&lt;InputFieldName&gt;&quot;:{&quot;targetFieldName&quot;:&quot;&lt;outputFileName&gt;&quot;}
Make sure to test with JSON.deserializeUntyped(jsonStr) to verify the validity of json</inlineHelpText>
        <label>FieldConfig</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IntegrationConfig__c</fullName>
        <label>Integration Config</label>
        <referenceTo>IntegrationConfig__c</referenceTo>
        <relationshipName>IntegrationDetailsConfig</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>Sort Order</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TargetObject__c</fullName>
        <label>TargetObject</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CFG: CSV Integration Detail</label>
    <nameField>
        <displayFormat>INTCD-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSV Integration Details Config</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/IntegrationHeader__c.object
<CustomObject>
    <description>[Business] Stores header record of integration file [ Need to Decide with Shah and Shiva if required and also if its is a Business or a Framework object]</description>
    <fields>
        <fullName>Filename__c</fullName>
        <label>Filename</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HeaderRecord__c</fullName>
        <label>Header Record</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IntegrationConfig__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Integration Config</label>
        <referenceTo>IntegrationConfig__c</referenceTo>
        <relationshipLabel>Integration Headers</relationshipLabel>
        <relationshipName>IntegrationHeaders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Partial</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Re-Process</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IST: Integration Header</label>
    <nameField>
        <displayFormat>INTH-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestIntegrationProcessHandler.cls
/*
* @author: SMahavratayajula - 07/26/2016
* Note: Actual class(IntegrationProcessHandler) is actively used in DCDOH code and 
* Tray is POC for this class. Assuming this class belongs to DOH, all related 
* classes are considered for deletion. To get samplet data from DB, check with Tray.
* IntegrationProcessDetailRedirectCtrl, IntegrationProcessRedirectCtrl and
* IntegrationProcessHandler. This test class can be used when we decide that we require
* this class in GovGrants
*/
@isTest
private class TestIntegrationProcessHandler {
	
	/*@isTest static void test_method_one() {

		IntegrationConfig__c integrationConfig = new IntegrationConfig__c(ProcessName__c='Test',
													Delimiter__c='Tab');
		insert integrationConfig;

		IntegrationDetailConfig__c integrationDetailConfig = new IntegrationDetailConfig__c(
																IntegrationConfig__c=integrationConfig.Id,
																SortOrder__c=1.0,TargetObject__c='Test',
																FieldConfig__c='{"<InputFieldName>":{"targetFieldName":"<outputFileName>"}'
																);
		insert integrationDetailConfig;

		IntegrationHeader__c integrationHeader = new IntegrationHeader__c(FileName__c='User Registration',
													Status__c='New',HeaderRecord__c='sometext area',
													IntegrationConfig__c=integrationConfig.Id);
		insert integrationHeader;

		IntegrationDetail__c integrationDetail = new IntegrationDetail__c(
													IntegrationHeader__c=integrationHeader.Id,
													DetailRecord__c='Some test detail');
		insert integrationDetail;

		Test.startTest();
			IntegrationProcessHandler integrationProcessHandler = new IntegrationProcessHandler(integrationHeader.Id,null);
			Database.executeBatch(integrationProcessHandler);
		Test.stopTest();

	}	*/
}