UtahLiveDataTest/src/objects/InterfaceConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>API_Key__c</fullName>
        <label>API Key</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Id__c</fullName>
        <label>Product Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>Purpose</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <label>Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isEnabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Interface Config</label>
</CustomObject>

UtahLiveDataTest/src/classes/TestManageInterfaceViewCtrl.cls
@isTest
private class TestManageInterfaceViewCtrl{

  @isTest static void testController() {

    List<InterfaceConfig__c> interfaceConfigs = new List<InterfaceConfig__c>();

    InterfaceConfig__c interfaceConfig1 = new InterfaceConfig__c();
    interfaceConfig1.Name = 'GuideStar/Simplify Interface';
    interfaceConfig1.isEnabled__c = true;  
    interfaceConfig1.Password__c = 'somepassword';
    interfaceConfig1.Product_Id__c = '/products';
    interfaceConfig1.Purpose__c = 'some purpose';
    interfaceConfig1.Url__c = 'https://Sometest.guidestar.org/';
    interfaceConfig1.Username__c = 'someUserName1';
    interfaceConfig1.Version__c = 'v1/charitycheck/';
    interfaceConfig1.API_Key__c = '4b6dv37fq3cbq147a591a11038029c20';

    InterfaceConfig__c interfaceConfig2 = new InterfaceConfig__c();
    interfaceConfig2.Name = 'Dun and Bradstreet Interface';
    interfaceConfig2.isEnabled__c = false;  
    interfaceConfig2.Password__c = 'somepassword2';
    interfaceConfig2.Product_Id__c = '/DCP_STD';
    interfaceConfig2.Purpose__c = 'some purpose 2';
    interfaceConfig2.Url__c = 'https://someservice.dnb.com/';
    interfaceConfig2.Username__c = 'someUserName2';
    interfaceConfig2.Version__c = 'V5.0/organizations/';
    interfaceConfig1.API_Key__c = '6b1dv37fq3cbq147a591a11036722c20';

    interfaceConfigs.add(interfaceConfig1);
    interfaceConfigs.add(interfaceConfig2);

    insert interfaceConfigs;

    Test.startTest();     
      ManageInterfaceViewCtrl ctrl= new ManageInterfaceViewCtrl();
    Test.stopTest();
  }

}