UtahLiveDataTest/src/objects/JXPrograms__c.object
<CustomObject>
    <description>[Business] Used for mapping the Federal/State Announcements with the program</description>
    <fields>
        <fullName>FederalProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Federal Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Junction_For_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StateProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Junction_For_Programs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Junction</label>
    <nameField>
        <displayFormat>JXPROG-{0000}</displayFormat>
        <label>Junction For Programs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/FederalProgramsActionHandler.cls
global with sharing class FederalProgramsActionHandler extends GNT.FlexTableActionHandler {
  global override Map<String,Object> clickHandler(){
    Map<String,Object> resultMap = new Map<String,Object>();
     Id parentId = urlParams.get('parentid');     
     String FedPrograms = urlParams.get('type');
     List<JXPrograms__c> fedpgms = new List<JXPrograms__c>();
     if(selectedRecordIds != null && !selectedRecordIds.isEmpty()){
       for(Id recordId: selectedRecordIds){
         JXPrograms__c fedpgm = new JXPrograms__c();
         fedpgm.FederalProgram__c = recordId;
         fedpgm.StateProgram__c = parentId;
         fedpgms.add(fedpgm);
       }
      insert(fedpgms);
      PageReference pageRef = new PageReference('/apex/SelectRecordsPopUp?parentid='+parentId+'&flextable=SelectFederalPrograms&type='+FedPrograms); 
      pageRef.getParameters().put('id',parentId);
     // resultMap.put('PageReference',pageRef);       
      //resultMap.put('Message','Federal Programs added succesfully.');
      resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-88469'));
     }else{
       //resultMap.put('Message','No records are selected.');
       resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-58429'));
     }
    
    return resultMap;  
  }

}