UtahLiveDataTest/src/objects/JXPrograms__c.object
<CustomObject>
    <description>[Business] Used for mapping the Federal/State Announcements with the program</description>
    <fields>
        <fullName>FederalProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Federal Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Junction_For_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StateProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Junction_For_Programs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Junction</label>
    <nameField>
        <displayFormat>JXPROG-{0000}</displayFormat>
        <label>Junction For Programs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestFederalProgramsActionHandler.cls
@isTest
private class TestFederalProgramsActionHandler {

    static testMethod void myUnitTest() {
        /*
        AccountTriggerHelper.skipTrigger = true;
        ProgramTriggerhelper.skipTrigger = true;
        UserTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
            Account acc = TestHelper.getAccount(true);
            Program__c prg = TestHelper.getProgram(acc.Id, true);
            JXPrograms__c fedpgm = new JXPrograms__c(FederalProgram__c = prg.id,StateProgram__c = prg.id);
            insert fedpgm;
            List<String> selectedRecordIds = new List<String>();
            selectedRecordIds.add(prg.id);
            ApexPages.currentPage().getParameters().put('Id', prg.Id);
            Map<String,String> urlParams = new Map<String,String>();
            FederalProgramsActionHandler pgmactionhandler = new FederalProgramsActionHandler();
            pgmactionhandler.selectedRecordIds = selectedRecordIds;
            urlParams.put('parentid',prg.Id);
            pgmactionhandler.urlParams = urlParams;
            pgmactionhandler.clickHandler();           
        }
    */
    
    }
}