UtahLiveDataTest/src/objects/KnowledgeArticle__c.object
<CustomObject>
    <description>This object is created for FAQs for GovGrants Tech Support Application</description>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Knowledge Article</label>
    <nameField>
        <displayFormat>KB-{000}</displayFormat>
        <label>Knowledge Article Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/FAQCtrl.cls
public with sharing class FAQCtrl {
    
    //Properties
    public ID recordId{get;set;}
    public String recordType {get;set;}
    public KnowledgeArticle__c articleRecord; 
     
    public FAQCtrl(){
        recordId = SFDCEncoder.SFDC_JSENCODE(ApexPages.CurrentPage().getParameters().get('id'));   
       // articleRecord =[Select Id, Question__c, Answer__c from KnowledgeArticle__c where id =: recordId limit 1];
    }
    
     public KnowledgeArticle__c getRecords(){
        if(KnowledgeArticle__c.sObjectType.getDescribe().isAccessible() == true){
            articleRecord =[Select Id, Question__c, Answer__c from KnowledgeArticle__c where id =: recordId limit 1];
        }
        return articleRecord;
    } 
    
    public string getKeyValueMap(){   
        Map<String,String> keyValueMap = new Map<String,String>();
        keyValueMap.put('recordId',SFDCEncoder.SFDC_JSENCODE(ApexPages.currentPage().getParameters().get('id')));      
        return JSON.serialize(keyValueMap);
    }   
}