UtahLiveDataTest/src/objects/OpportunityQualification__c.object
<CustomObject>
    <description>[Business] This is for a Sub Recipient to Mark an Announcement so that after some days he or she can create an application for the same announcement. This is created because there might be lots of announcement but sub recipient might be interested with only few announcement so he/she can mark it as qualified and later convert into an application</description>
    <fields>
        <fullName>FundingOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Opportunity</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipName>Opportunity_Sub_Recipient_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Qualified Announcements</label>
    <nameField>
        <displayFormat>FO-{0000}</displayFormat>
        <label>Qualified Announcement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualified Announcements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/QualifiedAnnouncementViewHelper.cls
global with sharing class QualifiedAnnouncementViewHelper extends GNT.FlexTableActionHandler{
       
       global override Map<String,Object> clickHandler(){
             PageReference pageRef = null;
             String ns = AppUtils.getNamespacePrefix();
             Map<String,Object> resultMap = new Map<String,Object>();
             List<OpportunityQualification__c> oppQualifyObjList = [Select id, FundingOpportunity__c from OpportunityQualification__c where id in :selectedRecordIds];
                   if(oppQualifyObjList != null && oppQualifyObjList.size() > 0){
                         OpportunityQualification__c oppQualifyObj = oppQualifyObjList[0];
                         if(oppQualifyObj != null && oppQualifyObj.FundingOpportunity__c != null){
                          pageRef = new PageReference('/apex/'+ns+'QualifiedOpportunityView?id='+oppQualifyObj.Id+'&announcementid='+oppQualifyObj.FundingOpportunity__c);
                    }
             }
             resultMap.put('PageReference',pageRef);
             return resultMap;
       }
}