UtahLiveDataTest/src/objects/PaymentRequest__c.object
<CustomObject>
    <description>[Business] Defines the details of for the Payment request.Payment request is done when award is already awarded and the Grantee wants to make use of the funds</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Approval 1</fullName>
                </value>
                <value>
                    <fullName>Approval 2</fullName>
                </value>
                <value>
                    <fullName>Approval 3</fullName>
                </value>
                <value>
                    <fullName>Approval 4</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Sent to FINET</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Request</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestPayPaymentRequestHelper.cls
@isTest
public with sharing class TestPayPaymentRequestHelper {
    static testMethod void testMethod0() {
		User u = TestHelper.getAdminUser(true);
		System.runAs(u){
			PaymentRequest__c payreq = TestHelper.getPaymentRequest(false);
			payreq.Status__c = 'Approved';
			insert payreq;
			
			Test.startTest();
			ApexPages.CurrentPage().getParameters().put('id',payreq.Id);   
			PayPaymentRequestHelper ctrl = new PayPaymentRequestHelper();
			ctrl.whenClicked();
			Test.stopTest();
		}
	}
}