UtahLiveDataTest/src/objects/PaymentRequest__c.object
<CustomObject>
    <description>[Business] Defines the details of for the Payment request.Payment request is done when award is already awarded and the Grantee wants to make use of the funds</description>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Payment_Requests5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Payment Request</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestPaymentSubmissionHelper.cls
@isTest(SeeAllData=true)
private class TestPaymentSubmissionHelper {

    static testMethod void myUnitTest() {
        
        User u = TestHelper.getAdminUser(true);
        User u1 =TestHelper.getAdminUser(true); 
        PaymentRequest__c pmntreq = null;
        System.runAs(u){
            pmntreq = TestHelper.getPaymentRequest(false);
            pmntreq.approver__c = u1.Id;
            pmntreq.Title__c = 'Test';
            insert pmntreq;
            Attachment att = new Attachment(Name = 'paymentreq.pdf',Parentid = pmntreq.id,Body= Blob.valueOf('xyz'));
            insert att;
            Test.setCurrentPageReference(new PageReference('Page.PaymentRequestView'));        
        }
        
        Test.startTest();
        PaymentSubmissionHelper pmntHelper = new PaymentSubmissionHelper();
        ApexPages.currentPage().getParameters().put('id', pmntreq.Id);
        pmntHelper.whenClicked();
        Test.stopTest();
    
    }
}