UtahLiveDataTest/src/objects/PaymentRequest__c.object
<CustomObject>
    <description>[Business] Defines the details of for the Payment request.Payment request is done when award is already awarded and the Grantee wants to make use of the funds</description>
    <fields>
        <fullName>ExternalOrgName__c</fullName>
        <label>External Organization</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UOVC</fullName>
                </value>
                <value>
                    <fullName>USBE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FINETAmount__c</fullName>
        <label>FINET Amount</label>
        <summarizedField>PaymentFINETCode__c.RequestedAmount__c</summarizedField>
        <summaryForeignKey>PaymentFINETCode__c.PaymentRequest__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Payment Request</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/PaymentSubmissionHelper.cls
global with sharing class PaymentSubmissionHelper extends GNT.DynamicLayoutActionRedirect {
	
    global override PageReference whenClicked(){
    	Savepoint sp = Database.setSavepoint();
        List<String> errors = new List<String>();
        try{
	        Id recordId = apexpages.currentpage().getparameters().get('id');
	        PaymentRequest__c paymentreq = [SELECT Id,Name,Title__c,FINETAmount__c,ExternalOrgName__c FROM PaymentRequest__c WHERE Id =: recordId LIMIT 1];
	        GNT.TaskCreationHandler.createApprovalProcessTasks(paymentreq.Id, 'Review Payment Request', paymentreq.Name, null, System.TODAY() + 7, paymentreq.Title__c, true); 
	        
	        PageReference p = Page.PaymentRequestView;
	        p.getParameters().put('id', paymentreq.Id);
	        p.setRedirect(true);
	        return p;
        }catch(Exception e){
            Database.rollback(sp);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            return null;
        }
    }
}