UtahLiveDataTest/src/objects/PreApplication__c.object
<CustomObject>
    <description>[Business] Pre-Application is a trimmed version of the Application with limited information</description>
    <fields>
        <fullName>FinalApproverComments__c</fullName>
        <inlineHelpText>Field used by the Final Approver to make comments on the Pre-Application during the Pre-Application Approval or Rejection Process</inlineHelpText>
        <label>Final Approver Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Pre-Application</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pre-Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/PreApplicationAddCommentCtrl.cls
public with sharing class PreApplicationAddCommentCtrl {
    public Preapplication__c selectedPreApp {get;set;}
    
    public PreApplicationAddCommentCtrl(){
        selectedPreApp = new Preapplication__c();
        Id recordId = ApexPages.CurrentPage().getParameters().get('id');
        
        if(recordId != null){
            List<Preapplication__c> preAppList = [Select Id, FinalApproverComments__c From Preapplication__c where Id = :recordId];
            if(preAppList.isEmpty() != true){
                selectedPreApp = preAppList.get(0);
            }
        }
    }
    
    public void btnAddComment (){
        if(selectedPreApp != null){
            try{
                update selectedPreApp;
            }
            catch(Exception e){
                selectedPreApp.addError('Exception Occured - ' + e );
                //selectedPreApp.addError(GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTE-59415') + e );
            }
        }
    }
    
    public void btnCancel(){
        
    }
}