UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ServiceArea__c.object
<CustomObject>
    <description>[Business] Master list of all the Service Area information is stored in this object , Service areas are also applicable to the Announcements ,Programs,Application via Junction objects</description>
    <fields>
        <fullName>StrategicPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Strategic Plan</label>
        <referenceTo>StrategicPlan__c</referenceTo>
        <relationshipName>Service_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project/Service Area</label>
    <nameField>
        <displayFormat>PSA-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/StrategicPlan__c.object
<CustomObject>
    <description>[Business] Defines the Strategic plan for an Organization which owns the Application</description>
    <label>Strategic Plan</label>
    <nameField>
        <displayFormat>SPN-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/StrategicPlanServiceArea__c.object
<CustomObject>
    <description>[Business] Association of a Strategic Plan with the Service Area</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>StrategicPlanServiceArea</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceArea__c</fullName>
        <label>Service Area</label>
        <referenceTo>ServiceArea__c</referenceTo>
        <relationshipName>StrategicPlanServiceArea</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StrategicPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Strategic Plan</label>
        <referenceTo>StrategicPlan__c</referenceTo>
        <relationshipName>StrategicPlanServiceArea</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Strategic Plan Project Area</label>
    <nameField>
        <displayFormat>SPSR-{000}</displayFormat>
        <label>Strategic Plan Service Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Plan Project Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/StrategicPlanServiceAreaActionHandler.cls
global with sharing class StrategicPlanServiceAreaActionHandler extends GNT.FlexTableActionHandler{

  global override Map<String,Object> clickHandler(){
    Map<String,Object> resultMap = new Map<String,Object>();
    ID parentId = urlParams.get('parentid');   
    String parentObjName = parentId.getSObjectType().getDescribe().getName();
    parentObjName = GNT.AppUtils.removeNamespacePrefix(parentObjName);
      
     List<StrategicPlanServiceArea__c> objs = new List<StrategicPlanServiceArea__c>();
     if(selectedRecordIds != null && !selectedRecordIds.isEmpty()){
       for(Id recordId: selectedRecordIds){
         StrategicPlanServiceArea__c obj = new StrategicPlanServiceArea__c();
        if(parentObjName == 'ServiceArea__c'){
           obj.StrategicPlan__c = recordId;
           obj.ServiceArea__c = parentId;
        }else if(parentObjName == 'StrategicPlan__c'){
           obj.ServiceArea__c = recordId;
           obj.StrategicPlan__c = parentId;
        }else if(parentObjName == 'Program__c'){
           obj.ServiceArea__c = recordId;
           obj.Program__c = parentId;
        }
         objs.add(obj);
       }
      insert(objs);
      
      if(parentObjName == 'ServiceArea__c'){
        //resultMap.put('Message','Strategic Plans added succesfully.');
        resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-87154'));
      } 
      if(parentObjName == 'StrategicPlan__c'){
        //resultMap.put('Message','Service Areas added succesfully.');
        resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-65684'));
      } 
     }else{
       //resultMap.put('Message','No records are selected.');
       resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-58429'));
     }
    
    return resultMap;  
  }
  
}