UtahLiveDataTest/src/objects/ProgressReports__c.object
<CustomObject>
    <description>[Business] Progress Report on the Grant/Award</description>
    <fields>
        <fullName>DateReportSubmitted__c</fullName>
        <label>Date Report Submitted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EmailAddress__c</fullName>
        <label>EmailAddress</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FormsValidated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for validation of form depends upon percentage of form filled.</description>
        <label>Forms Validated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NameAndTitleOfACO__c</fullName>
        <label>NameAndTitleOfACO</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signature__c</fullName>
        <label>Signature</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Internally Approved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubmittedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitted By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Progress_Report6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubmittedOn__c</fullName>
        <label>Submitted On</label>
        <type>Date</type>
    </fields>
    <label>Progress Report</label>
    <nameField>
        <label>Progress Report ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Report</pluralLabel>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/SubmitProgressReportCtrl.cls
global with sharing class SubmitProgressReportCtrl extends GNT.DynamicLayoutActionRedirect {
  
    global override Pagereference whenClicked()
    {
        String recordId = ApexPages.CurrentPage().getParameters().get('id');
        Pagereference pg = null;
        Id rptId;
        String appName = GNT.UserPreferenceHelper.getStringValue('ActiveAppName__c');
        List<ProgressReports__c> listReport = [SELECT Id, Name, Status__c,OwnerId,FormsValidated__c FROM ProgressReports__c WHERE Id=:recordId  LIMIT 1];
        String userName = UserInfo.getUserName();
        User activeUser = [Select Name, Email From User where Username = : userName limit 1];
        if(listReport!=null && listReport.size()>0){
            ProgressReports__c rpt = listReport[0];
            if(!rpt.FormsValidated__c){
                ApexPages.addmessage(new Apexpages.Message(ApexPages.Severity.INFO,'Please validate the forms before submitting the progress report'));
                return null;
            }
            system.debug('AppName is ' +appName);
            
        if(appName == 'StateasGrantee'){
            system.debug('inside');            
            rpt.status__c='Submitted to Grantor';
            rpt.SubmittedBy__c=UserInfo.getUserId();
            rpt.SubmittedOn__c=System.Today();
            rpt.NameAndTitleOfACO__c=activeUser.Name;
            rpt.DateReportSubmitted__c=Date.today();
            rpt.EmailAddress__c=activeUser.Email;
            rpt.Signature__c = activeUser.Name;
            rptId=rpt.Id;
            update rpt;
            //ApexPages.addmessage(new Apexpages.Message(ApexPages.Severity.INFO,'Progress Report is submitted to Grantor Succesfully'));
            
            ApexPages.addmessage(new Apexpages.Message(ApexPages.Severity.INFO,GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-40127')));
        }
        else if(appName == 'Recipient'){
            system.debug('inside '+appName);
            rpt.Status__c = 'Submitted to Grantor';
            rpt.SubmittedBy__c=UserInfo.getUserId();
            rpt.SubmittedOn__c=System.Today();
            rpt.NameAndTitleOfACO__c=activeUser.Name;
            rpt.DateReportSubmitted__c=Date.today();
            rpt.EmailAddress__c=activeUser.Email;
            rpt.Signature__c = activeUser.Name;
            rptId=rpt.Id;
            update rpt;

            GNT.TaskCreationHandler.createApprovalProcessTasks(rpt.Id, 'Review Grantor ProgressReport', rpt.Name, null, System.TODAY() + 7, rpt.Name, true);
            List<Task> taskList = [Select Id, Status, WhatId,lastModifieddate from Task where WhatId = :recordId AND OwnerId=:rpt.OwnerId AND Status='In Progress'];
            if(taskList!=null && taskList.size()>0){
                for(Task task : taskList){
                    task.Status='Completed';
                }
                update taskList;
            }
            EmailTemplate emailTemplate = [Select Id from EmailTemplate where Name = 'Notify Applicant Progress Report Submitted' limit 1];
            Map<Id, String[]> recIdToAddressMap = new Map<Id, String[]>();
            List<String> mailTo = new List<String>();
            mailTo.add(activeUser.Email);
            recIdToAddressMap.put(rptId, mailTo);
            Contact cont = [select id, Email from Contact where email <> null limit 1];
            //AppUtils.sendEmailUsingTemplate(emailTemplate.Id, recIdToAddressMap, cont.Id, false);

            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'The Progress Report has been submitted successfully.'));
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-40127')));
          
        }
       }
    PageReference p = Page.ProgressReportView;
    p.getParameters().put('Id', rptId);
    p.setRedirect(true);
    return p; 
    }
 }