UtahLiveDataTest/src/objects/ProgressReports__c.object
<CustomObject>
    <description>[Business] Progress Report on the Grant/Award</description>
    <fields>
        <fullName>DateReportSubmitted__c</fullName>
        <label>Date Report Submitted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FormsValidated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for validation of form depends upon percentage of form filled.</description>
        <label>Forms Validated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Internally Approved</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubmittedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitted By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Progress_Report6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubmittedOn__c</fullName>
        <label>Submitted On</label>
        <type>Date</type>
    </fields>
    <label>Progress Report</label>
    <nameField>
        <label>Progress Report ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Report</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ApproveProgressReportCtrl.cls
global with sharing class ApproveProgressReportCtrl extends GNT.DynamicLayoutActionRedirect {
  
    global override Pagereference whenClicked()
    {
        String recordId = ApexPages.CurrentPage().getParameters().get('id');
        Pagereference pg = null;
        Id rptId;
        String appName = GNT.UserPreferenceHelper.getStringValue('ActiveAppName__c');
        List<ProgressReports__c> listReport = [SELECT Id, Name,FormsValidated__c, SubmittedBy__c,SubmittedOn__c,Status__c FROM ProgressReports__c WHERE Id=:recordId  LIMIT 1];   
        
        if(listReport!=null && listReport.size()>0){
            ProgressReports__c rpt = listReport[0];
        
            if(rpt.FormsValidated__c == false){
                // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Forms needs to be validated before the Progress Report can be submitted.')); 
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-55105')));
                return null;
            }            
        
            
            rptId=rpt.Id;
            
            if(appName == 'StateasGrantee' || appName == 'Recipient'){    
                rpt.Status__c = 'Submitted for Approval';
                update rpt;     
                GNT.TaskCreationHandler.createApprovalProcessTasks(rpt.Id, 'Internal Approval', rpt.Name, null, System.TODAY() + 7, rpt.Name, true);
                
                // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'The Progress Report has been submitted for Approval successfully.')); 
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-72631')));                   
            }
            else if(appName == 'StateasGrantor'){
                rpt.SubmittedBy__c=UserInfo.getUserId();
                rpt.SubmittedOn__c=System.Today();
                rpt.DateReportSubmitted__c=System.Today();
                update rpt;
            }
       }
        PageReference p = Page.ProgressReportView;
        p.getParameters().put('Id', rptId);
        p.setRedirect(true);
        return p; 
    }
 }