UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/TermCondition__c.object
<CustomObject>
    <description>[Business] Terms and Conditions for Grants ,Awards (The lookup to Package may not be required in this case )</description>
    <fields>
        <fullName>CopiedFrom__c</fullName>
        <description>ID value of field from where Term &amp;  Condition Record is created</description>
        <label>Copied From</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>EffectiveFrom__c</fullName>
        <description>Allow user to enter a date. Prepopulated current date by default. This date cannot be in the past. Has to be current or future. The term can be added to grants/awards starting from the effective date. Required.</description>
        <label>Effective From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SequenceNo__c</fullName>
        <description>Sequence Number of how Terms&amp;Conditions are listed</description>
        <label>Print Sequence No.</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Active, Inactive. If the Effective Date is current or in the past and if the Inactive On date is in the future, the Term is Active. If the Inactive Date is in the past, the term is Inactive. Prepopulated. Read Only.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title of the term</description>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MST:Term and Condition</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <recordTypes>
        <fullName>Condition</fullName>
        <active>true</active>
        <label>Condition</label>
    </recordTypes>
    <recordTypes>
        <fullName>Term</fullName>
        <active>true</active>
        <description>Related to Awards ( Ramu to rename this object appropriately)</description>
        <label>Term</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/AddProgramTermConditionCtrl.cls
global with sharing class AddProgramTermConditionCtrl extends GNT.FlexTableActionHandler{
    
    public List<id> selectedIds{get; set;}
    
    global override Map<String,Object> clickHandler(){
        Map<String,Object> resultMap = new Map<String,Object>();
        String programId= urlParams.get('parentid');
        Integer sequence=0;
        System.debug('>>>>>>>>>>>>>>'); 
        system.debug('----'+programId);
        System.debug('>>>>>>>>>>>>>');
        Map<Id,TermCondition__c> termConditionsMap= new Map<Id,TermCondition__c>([select id,Name,Description__c,Status__c,Title__c,EffectiveFrom__c from TermCondition__c where id in :selectedRecordIds]); 
        List<TermCondition__c> programTermConditions =  new  List<TermCondition__c>();

        if(selectedRecordIds==null||selectedRecordIds.size()<1)
        {
        resultMap.put('PageReference',null);// Message will be shown on Popup window itself
        //resultMap.put('Message','Please select a record.');
        resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-67180'));
        return resultMap;
        }

        List<TermCondition__c> tcList = [Select id,SequenceNo__c,Description__c,Status__c,Title__c,EffectiveFrom__c from TermCondition__c where Program__c =:programId];

        if(tcList!=null)
        sequence= tcList.size();

        for(Id selectedId : selectedRecordIds){ 
            TermCondition__c relatedtermCondition = new TermCondition__c ();
            sequence=sequence+1;
            relatedtermCondition.Description__c   = termConditionsMap.get(selectedId).Description__c;
            relatedtermCondition.Status__c        = termConditionsMap.get(selectedId).Status__c;
            relatedtermCondition.Title__c         = termConditionsMap.get(selectedId).Title__c;            
            relatedtermCondition.EffectiveFrom__c = termConditionsMap.get(selectedId).EffectiveFrom__c;   
            relatedtermCondition.SequenceNo__c    = sequence;
            relatedtermCondition.CopiedFrom__c    = selectedId;   
            relatedtermCondition.Program__c       = programId;


            programTermConditions.add(relatedtermCondition);
             system.debug('--relatedtermCondition--'+relatedtermCondition);
        }
        try{
            insert programTermConditions;
            system.debug('--programTermConditions--'+programTermConditions);
        }catch(Exception e){
            System.debug('The Excpetion is '+e);
            resultMap.put('PageReference',null);// Message will be shown on Popup window itself
            //resultMap.put('Message','Error in associating selected Term/Condition.');
            resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-53982'));
            return resultMap;
        } 
        
        PageReference pageRef = Page.ProgramView;
        pageRef.getParameters().put('id',programId);
        resultMap.put('PageReference',null);// Message will be shown on Popup window itself
        //resultMap.put('Message','Terms associated successfully to Program.');
        resultMap.put('Message',GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-14350'));
        return resultMap;
    }
}