UtahLiveDataTest/src/objects/Program__c.object
<CustomObject>
    <description>[Business] Programs are announced by the Agencies to publish the Announcements against which applications can be submitted to apply for Grants</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>GNT__OrganizationId__c</fullName>
        <description>Organization to which a user is tied to. It is applicable for both internal and external users</description>
        <label>Organization Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ProgramViewCtrlTest.cls
@isTest(SeeAllData=false)
private with sharing class ProgramViewCtrlTest {
    static testMethod void testController() {
    /*
          Account acct = null;
          User u = TestHelper.getAdminUser(true);
                 
        
          System.runAs(u){
              GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
              AccountTriggerHelper.skipTrigger=true;
              ProgramTriggerHelper.skipTrigger=true;
              acct = TestHelper.getAccount(true);
              UserTriggerHelper.skipTrigger=true;
              u= [select GNT__OrganizationId__c from User where Id=:UserInfo.getUserId()];
              u.GNT__OrganizationId__c=acct.Id;
              update u;
              Program__c prog = TestHelper.getProgram(acct.Id,true);
          
             Test.startTest();
             ApexPages.StandardController sc = new ApexPages.standardController(prog);
             ApexPages.currentPage().getParameters().put('Id',prog.id);
             ProgramViewCtrl ctrl = new ProgramViewCtrl(sc);
             ctrl.getKeyValueMap();
             ctrl.getChartParameters();
             Test.stopTest();
        }
        */
    }
}