UtahLiveDataTest/src/objects/ProjectCostByFundingSource__c.object
<CustomObject>
    <description>Project Cost By Funding Source : Details of Funding Sources</description>
    <fields>
        <fullName>SecuredAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Secured Amount</description>
        <label>Secured Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UnsecuredAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Unsecured Amount</description>
        <inlineHelpText>Unsecured Amount</inlineHelpText>
        <label>Unsecured Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project Cost By Funding Source</label>
    <nameField>
        <label>Project Cost Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Cost By Funding Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ProjectCostsTriggerHelper.cls
/*
    All code for Trigger on ProjectCostByFundingSource__c  Object
    ***********************************************************
    Audit History
    ***********************************************************
    Apr-11-2017      Davinder Singh         Created
    *********************************************************** 
*/
global with sharing class ProjectCostsTriggerHelper extends GNT.TriggerHelper {
    global override void processBeforeInsert() {
        populateZeroValues();
        validateName();
    }
           
    global override void processBeforeUpdate() {
        populateZeroValues();
        validateName();
    }
         
    private void populateZeroValues(){
        List<ProjectCostByFundingSource__c> projectCosts = (List<ProjectCostByFundingSource__c>)Trigger.new;
        for(ProjectCostByFundingSource__c pfs : projectCosts){
            if(pfs.SecuredAmount__c == null){
                pfs.SecuredAmount__c = 0;
            }
            if(pfs.UnsecuredAmount__c == null){
                pfs.UnsecuredAmount__c = 0;
            }
        }        
    }

    private void validateName(){
        List<ProjectCostByFundingSource__c> projectCosts = (List<ProjectCostByFundingSource__c>)Trigger.new;
        Profile p = [Select Name from Profile where Id = :UserInfo.getProfileId()];
        for(ProjectCostByFundingSource__c pfs : projectCosts){
            if(pfs.Name == null){
                if(p.Name != 'SPI' && p.Name != 'SPA' && p.Name != 'SME'){    
                    pfs.addError('Please input Financial Source');
                }else{
                    pfs.addError('Please input Project Cost Name');
                }
            }
        }
    }
}