UtahLiveDataTest/src/objects/r_prog__c.object
<CustomObject>
    <description>This is the object for the FINET program creation</description>
    <fields>
        <fullName>BILL_AGREE_DT__c</fullName>
        <label>Billing Agreement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EFBGN_DT__c</fullName>
        <label>Effective From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EFEND_DT__c</fullName>
        <label>Effective To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FINETMajorProgram__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>FINET Major Program</label>
        <referenceTo>r_mjr_prog__c</referenceTo>
        <relationshipLabel>r_progs</relationshipLabel>
        <relationshipName>FINETPrograms1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PROG_NM__c</fullName>
        <label>ProgramName</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>r_prog</label>
    <nameField>
        <label>r_prog</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>r_progs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/FINETProgCreatHelper.cls
global with sharing class FINETProgCreatHelper extends GNT.DynamicLayoutActionRedirect {
    String appName = GNT.UserPreferenceHelper.getStringValue('ActiveAppName__c');
    global override PageReference whenClicked(){
        Savepoint sp = Database.setSavepoint();
        Boolean isError = false;
        
        try{
                    Id recordId = apexpages.currentpage().getparameters().get('id');
                    r_prog__c prog=[SELECT Id,PROG_NM__c,BILL_AGREE_DT__c,EFBGN_DT__c,EFEND_DT__c,FINETMajorProgram__c FROM r_prog__c WHERE Id =: recordId LIMIT 1 ];
                
                      if ((prog.BILL_AGREE_DT__c<prog.EFBGN_DT__c)||(prog.BILL_AGREE_DT__c>prog.EFEND_DT__c))
                    {
                        isError=true;
                        //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'The Billing agreement date should be between the Effective From and Effective To dates under General information tab'));
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-56125')));
                    }

                    if (iserror==false){
                    GNT.TaskCreationHandler.createApprovalProcessTasks(prog.Id, 'Create FINET Program', prog.PROG_NM__c, null, System.TODAY() + 7, prog.PROG_NM__c, true); 
                    //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('M01-GRNTR-57523')));
                    
                    
                    PageReference p = Page.FINETProgramView;
                    p.getParameters().put('Id', prog.Id);
                    p.setRedirect(true);
                    return p;
                }
                else
                return null;
                   
                
              } 
              catch(Exception e){
                Database.rollback(sp);
                 
                 ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
                return null;
            }
            
      
       
        } 
    

     }