UtahLiveDataTest/src/objects/ReviewGroup__c.object
<CustomObject>
    <description>[Business] This object summarizes number of Applications/Pre-Applications and number of Review Steps. As discussed with Shiva, Shah, Davinder , this object can not removed sometime later when possible.</description>
    <fields>
        <fullName>CurrentReviewStep__c</fullName>
        <label>Current Review Step</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Review Group</label>
    <nameField>
        <displayFormat>RG-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewPanel__c.object
<CustomObject>
    <description>[Business] Defines the Review Panel to review the Applications</description>
    <fields>
        <fullName>ReviewStepName__c</fullName>
        <formula>ReviewStep__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Review Step Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReviewStep__c</fullName>
        <label>Review Step</label>
        <referenceTo>ReviewStep__c</referenceTo>
        <relationshipLabel>Review Panels</relationshipLabel>
        <relationshipName>Review_Panels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Review Panel</label>
    <nameField>
        <displayFormat>Panel-{000}</displayFormat>
        <label>Review Panel ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStep__c.object
<CustomObject>
    <description>[Business] Defines all the details of Review Step defined in the Review of Application/Pre-Application</description>
    <fields>
        <fullName>ReviewGroup__c</fullName>
        <label>Review Group</label>
        <referenceTo>ReviewGroup__c</referenceTo>
        <relationshipLabel>Review Steps</relationshipLabel>
        <relationshipName>Review_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Review Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStepApplication__c.object
<CustomObject>
    <description>[Business] Connects the Application/Pre-Application with the User and Review Step via this object</description>
    <fields>
        <fullName>Decision__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReviewStepName__c</fullName>
        <label>Review Step Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReviewStep__c</fullName>
        <label>Review Step</label>
        <referenceTo>ReviewStep__c</referenceTo>
        <relationshipName>ReviewStepApplications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Review Step Application</label>
    <nameField>
        <displayFormat>RSA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Step Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/PanelUserAddHelper.cls
global with sharing class PanelUserAddHelper extends GNT.FlexTableActionHandler {
    global override Map<String,Object> clickHandler(){
        Map<String,Object> resultMap = new Map<String,Object>();
        Boolean allowReview = false;

        system.debug('inside PanelUserAddHelper---');

        Id panelId = urlParams.get('id');

          system.debug('inside PanelUserAddHelper---panelId--'+panelId);

        ReviewPanel__c revPanel = [Select Id,ReviewStep__c,ReviewStepName__c,ReviewStep__r.ReviewGroup__r.CurrentReviewStep__c FROM ReviewPanel__c where id =: panelId limit 1];
        
  system.debug('inside PanelUserAddHelper---revPanel--'+revPanel);

        List<ReviewStepApplication__c> rsApplications = [Select id,Decision__c FROM ReviewStepApplication__c where ReviewStep__c =: revPanel.ReviewStep__c and Decision__c = 'Pending' ];
     system.debug('inside PanelUserAddHelper---rsApplications--'+rsApplications);


        if(rsApplications.size() > 0) {
            allowReview = true;
        }
        if(revPanel.ReviewStepName__c != revPanel.ReviewStep__r.ReviewGroup__r.CurrentReviewStep__c) {
            resultMap.put('Message','Applications have been sent to '+revPanel.ReviewStep__r.ReviewGroup__r.CurrentReviewStep__c+' Step, you cannot add Reviewers now');
        }
        else if(allowReview == true || (revPanel.ReviewStepName__c == revPanel.ReviewStep__r.ReviewGroup__r.CurrentReviewStep__c)) {
            String pageReferenceUrl = '/apex/PanelUserAdd?id='+panelId+'&tabName=Reviewers';
            resultMap.put('PageReference',pageReferenceUrl);
        }
        return resultMap;
    }
}