UtahLiveDataTest/src/objects/ReviewStep__c.object
<CustomObject>
    <description>[Business] Defines all the details of Review Step defined in the Review of Application/Pre-Application</description>
    <label>Review Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStepApplication__c.object
<CustomObject>
    <description>[Business] Connects the Application/Pre-Application with the User and Review Step via this object</description>
    <fields>
        <fullName>ReviewStep__c</fullName>
        <label>Review Step</label>
        <referenceTo>ReviewStep__c</referenceTo>
        <relationshipName>ReviewStepApplications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Review Step Application</label>
    <nameField>
        <displayFormat>RSA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Step Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestNotifyNonWinnersHelper.cls
/**
 
    **********************************************************
    Audit History
    **********************************************************
    4/27/2014   swati singh    Created
 
    **********************************************************  
*/
@isTest
private with sharing class TestNotifyNonWinnersHelper {


    @IsTest(OnInstall=false)
    public static void test_ctrl() {
        User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
        TestHelper.CreateCustomSettings(true);
        Test.startTest();
         NotifyNonWinnersHelper ctrl = new NotifyNonWinnersHelper();
        ctrl.clickHandler();

        Test.stopTest();

        //assert
        System.assertEquals(ctrl, ctrl);
        
        
        }
    }
    
     @IsTest(OnInstall=false)
    public static void test_ctrl1() {
        User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
        ApplicationTriggerHelper.skiptrigger = true;
        AnnouncementTriggerHelper.skipTrigger = true;
        UserTriggerHelper.skipTrigger = true;
        ReviewPanelTemplateTriggerHelper.skipTrigger = true;
        TestHelper.CreateCustomSettings(true);
       
        Test.startTest();
       ReviewStep__c rs = TestHelper.getReviewStep(true);
       ApexPages.currentPage().getParameters().put('Id', rs.Id);
       ReviewStepApplication__c rsa = TestHelper.getReviewStepApplication(true);
       List<String> selectedRecordIds = new List<String>();
       selectedRecordIds.add(rsa.id);
       Map<String,String> urlParams = new Map<String,String>();
            NotifyNonWinnersHelper ctrl = new NotifyNonWinnersHelper();
            ctrl.selectedRecordIds = selectedRecordIds;
            urlParams.put('id',rs.Id);
            ctrl.urlParams = urlParams;
            ctrl.clickHandler();   
            Test.stopTest();

        //assert
        System.assertEquals(rs.Id, rs.Id);
        
        
        }
    }
  }