UtahLiveDataTest/src/objects/ReviewStep__c.object
<CustomObject>
    <description>[Business] Defines all the details of Review Step defined in the Review of Application/Pre-Application</description>
    <label>Review Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStepUser__c.object
<CustomObject>
    <description>[Business] Association of a user with the Review Step</description>
    <fields>
        <fullName>ReviewStep__c</fullName>
        <label>Review Step</label>
        <referenceTo>ReviewStep__c</referenceTo>
        <relationshipLabel>Review Step Users</relationshipLabel>
        <relationshipName>Review_Step_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Review Step User</label>
    <nameField>
        <displayFormat>RSU-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Step Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ReviewStepUserCopyCtrl.cls
/**
* Controller class to copy the ReviewStepUsers from Previous Step to Next step
*
* CHANGE HISTORY
*================================================================ 
* 05/02/2014	Kunal Shah		      Created 
*================================================================
*/
public with sharing class ReviewStepUserCopyCtrl {
	
	public Id reviewStepId {get;set;}
	public ReviewStep__c reviewStep {get;set;}
	public List<ReviewStepUser__c> oldStepUsers {get;set;}
	public List<ReviewStepUser__c> newStepUsers {get;set;}
	
	public ReviewStepUserCopyCtrl() {
	}
	
	/*
		METHOD TO GET ALL THE REVIEWERS IN THE PREVIOUS STEP
	*/
	public void getOldStepUsers(){							
	}
	
	/*
		METHOD TO COPY ALL THE STEP USERS FROM PREVIOUS STEP TO CURRENT STEP 
	*/
	public PageReference copyUsersToNextStep(){

		return null;
	}
	
	/*
        METHOD TO CANCEL COPYING REVIEWERS
    */ 
    public PageReference Cancel(){

        return null;
    }
	
}