UtahLiveDataTest/src/objects/Review__c.object
<CustomObject>
    <description>[Business] Defines the Review object (Need more Details / Need to revisit for the Description)</description>
    <fields>
        <fullName>AcceptanceStatus__c</fullName>
        <label>Do you accept your Review Assignment?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Declined Without Conflict</fullName>
                </value>
                <value>
                    <fullName>Declined Due To Conflict</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReviewPanel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review Panel</label>
        <referenceTo>ReviewPanel__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review Step</label>
        <referenceTo>ReviewStep__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Sent for Review</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Review Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewPanel__c.object
<CustomObject>
    <description>[Business] Defines the Review Panel to review the Applications</description>
    <fields>
        <fullName>ReviewStep__c</fullName>
        <label>Review Step</label>
        <referenceTo>ReviewStep__c</referenceTo>
        <relationshipLabel>Review Panels</relationshipLabel>
        <relationshipName>Review_Panels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Review Panel</label>
    <nameField>
        <displayFormat>Panel-{000}</displayFormat>
        <label>Review Panel ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStep__c.object
<CustomObject>
    <description>[Business] Defines all the details of Review Step defined in the Review of Application/Pre-Application</description>
    <fields>
        <fullName>ReviewLevelAcceptance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Review Level Acceptance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Review Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ReviewRedirectCtrl.cls
public with sharing class ReviewRedirectCtrl{
    
    Boolean reviewLevelAcceptance;
    Id recordId;
    
    public ReviewRedirectCtrl(){
        recordId = ApexPages.CurrentPage().getParameters().get('id');
    }
    
    public PageReference redirect() {
        reviewLevelAcceptance = true;
        PageReference p = null;


        Review__c review = [Select id, AcceptanceStatus__c,status__c, 
            ReviewPanel__r.ReviewStep__r.ReviewLevelAcceptance__c From Review__c where Id = :recordId ];
        
        if(review != null && review.ReviewPanel__r.ReviewStep__r.ReviewLevelAcceptance__c != null){
            reviewLevelAcceptance = review.ReviewPanel__r.ReviewStep__r.ReviewLevelAcceptance__c;
        }
        system.debug('reviewLevelAcceptance ----'+reviewLevelAcceptance);
        if(reviewLevelAcceptance){
            if(review.AcceptanceStatus__c == null){
                p = Page.ReviewAssignmentAcceptance;
                p.getParameters().put('id', recordId);
            }else if(review.AcceptanceStatus__c == 'Accepted'){
                p = Page.ReviewAssignmentEdit;
                p.getParameters().put('id', recordId);
            }else{
                p = Page.reviewassignmentview;
                p.getParameters().put('id', recordId);
            }
        }else{
            if(review.AcceptanceStatus__c == null){
                review.AcceptanceStatus__c = 'Accepted';
                update review;
                p = Page.ReviewAssignmentEdit;
                p.getParameters().put('id', recordId);
            }else if(review.status__c =='Review Completed'){
                p= Page.reviewassignmentview;
                p.getParameters().put('id', recordId);
            }else{
                p = Page.ReviewAssignmentEdit;
                p.getParameters().put('id', recordId);
            }
        }
        return p;
    }
}