UtahLiveDataTest/src/objects/ReviewStep__c.object
<CustomObject>
    <description>[Business] Defines all the details of Review Step defined in the Review of Application/Pre-Application</description>
    <label>Review Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStepUser__c.object
<CustomObject>
    <description>[Business] Association of a user with the Review Step</description>
    <fields>
        <fullName>ReviewStep__c</fullName>
        <label>Review Step</label>
        <referenceTo>ReviewStep__c</referenceTo>
        <relationshipLabel>Review Step Users</relationshipLabel>
        <relationshipName>Review_Step_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Review Step User</label>
    <nameField>
        <displayFormat>RSU-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Step Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ReviewStepUserAddCtrl.cls
/**
* Controller class for the Adding Reviewers to a Review Step
*
* CHANGE HISTORY
*================================================================ 
* 04/30/2014	Kunal Shah		      Created 
*================================================================
*/

public with sharing class ReviewStepUserAddCtrl {
	
	//PROPERTIES
	public Id reviewStepId {get;set;}  
    public List<ReviewStepUsersWrapper> lstReviewStepUsersWrapper {get;set;}
    public ReviewStep__c reviewStep {get;set;}
	
	public ReviewStepUserAddCtrl(){

	}
	
	/*
		METHOD TO FIND ALL ACTIVE USERS IN THE ORG
	*/
	public void getUsers(){

	}
	
	/*
		METHOD TO FIND ALL USERS WHO ARE ALREADY ADDED TO A REVIEW STEP
	*/	
	public List<Id> findAddedUsers(){

		return null;
	}
	
	/*
		METHOD TO ADD REVIEWERS TO A REVIEW STEP (OBJECT: REVIEWSTEPUSER__C)
	*/
	public PageReference addToReviewStep(){

        return null;
    }
    
    /*
    	METHOD TO CANCEL ADDING A REVIEWER TO REVIEW STEP
    */ 
    public PageReference Cancel(){

        return null;    }
  	
	/*INNER CLASS*/
    private class ReviewStepUsersWrapper{
 
    }
}