UtahLiveDataTest/src/objects/ReviewStep__c.object
<CustomObject>
    <description>[Business] Defines all the details of Review Step defined in the Review of Application/Pre-Application</description>
    <fields>
        <fullName>LastStep__c</fullName>
        <formula>If( ReviewGroup__r.NumberOfReviewSteps__c == StepNumber__c , true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Step</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReviewStepExpired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When the Today Date Exceeds End Date of the Review Step, A workflow rule triggers an update on this field to Checked</description>
        <inlineHelpText>When the Today Date Exceeds End Date of the Review Step, A workflow rule triggers an update on this field to Checked</inlineHelpText>
        <label>Review Step Expired ?</label>
        <type>Checkbox</type>
    </fields>
    <label>Review Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Steps</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestReviewApplicationPromoteHelper.cls
@isTest
private with sharing class TestReviewApplicationPromoteHelper {

	static testMethod void testclickHandler() {
		AnnouncementTriggerHelper.skipTrigger=true;

		ReviewStep__c revStep=TestHelper.getReviewStep(true);
		revStep.RecordType=[SELECT Id,name,DeveloperName FROM RecordType WHERE SobjectType = 'ReviewStep__c' and name='Application' Limit 1];
		//revStep.RecordType.DeveloperName='Application';
		revStep.ReviewStepExpired__c=false;
		//revStep.LastStep__c=false;
		update revStep;
		Map<String,String> urlParams = new Map<String,String>();
		ReviewApplicationPromoteHelper revapppromohelper=new ReviewApplicationPromoteHelper();
		
		Test.startTest();
		//ReviewS
		//ApexPages.currentPage().getParameters().put('Id', revStep.Id);
		//urlParams.put('reviewStepId',revStep.Id);
		//urlParams.put('action','');

		//revapppromohelper.clickHandler();

		test.stopTest();
	}
}