UtahLiveDataTest/src/objects/ReviewStep__c.object
<CustomObject>
    <description>[Business] Defines all the details of Review Step defined in the Review of Application/Pre-Application</description>
    <fields>
        <fullName>NumberOfAssignedReviewers__c</fullName>
        <inlineHelpText>Calculated field. Used to calculate the number of unassigned reviewers</inlineHelpText>
        <label>Number of Assigned Reviewers</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Review Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStepUser__c.object
<CustomObject>
    <description>[Business] Association of a user with the Review Step</description>
    <fields>
        <fullName>ReviewStep__c</fullName>
        <label>Review Step</label>
        <referenceTo>ReviewStep__c</referenceTo>
        <relationshipLabel>Review Step Users</relationshipLabel>
        <relationshipName>Review_Step_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Review_Step_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review Step User</label>
    <nameField>
        <displayFormat>RSU-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Step Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ReviewStepUserTriggerHelper.cls
/*
	All trigger logic on Review Step User Object
	**********************************************************
	Audit History
	**********************************************************
	2014-05-01		Vinayak Sharma		 Created 
	**********************************************************  
*/

public with sharing class ReviewStepUserTriggerHelper extends GNT.TriggerHelper {
	
	public override void processAfterInsert(){
		countNumberOfReviewers(Trigger.new);
	}
	
	public override void processAfterUpdate(){
		countNumberOfReviewers(Trigger.new); 
	} 
	
	public override void processAfterDelete(){
	} 
	
	private void countNumberOfReviewers(List<ReviewStepUser__c> lstUsers){
		
		// Select list of the review step users with step review  of the incoming user who is added to the project  
		List<ReviewStepUser__c> lstReviewStepUsers = [Select Id,ReviewStep__c,Reviewer__c  from ReviewStepUser__c where Id in : lstUsers];
		
		Set<String> reviewStepsSet = new Set<String>();
		
		for(ReviewStepUser__c stepReview  :lstReviewStepUsers){
			reviewStepsSet.add(stepReview.ReviewStep__c);			
		}
		  
		List<ReviewStep__c> lstReviewSteps = [Select Id,NumberOfAssignedReviewers__c from ReviewStep__c where Id in : reviewStepsSet];   
								 		
	    Map<String, Set<String>> userIdMap = new Map<String, Set<String>>();  //key->Step Review id, value->set of user id      
	    
	    for(ReviewStepUser__c reviewStep: lstReviewStepUsers){
			Set<String> innerList = userIdmap.get(reviewStep.ReviewStep__c);  
			if(innerList == null){  	
				innerList = new Set<String>(); 	    					
				userIdMap.put(reviewStep.ReviewStep__c,innerList);		  								     	
			} 
	    	 innerList.add(reviewStep.Reviewer__c);  	  
	    }
	    
	    List<ReviewStep__c> updateReviewStepLst = new List<ReviewStep__c>();
	     
	    for(String reviewId :  userIdMap.keyset()){	    	 
	    	 Set<String> reviewers = userIdMap.get(reviewId);	    	 
	    	 
	    	 updateReviewStepLst.add(new ReviewStep__c( Id =reviewId, NumberOfAssignedReviewers__c = reviewers.size()));	    	  
	    } 
	    update updateReviewStepLst;      
	    	
	}

}