UtahLiveDataTest/src/objects/Review__c.object
<CustomObject>
    <description>[Business] Defines the Review object (Need more Details / Need to revisit for the Description)</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Sent for Review</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Review Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/RatingAndRecommendationCtrl.cls
public with sharing class RatingAndRecommendationCtrl{
    public ID recordId{get;set;}
    public PageReference savePage {get;set;}
    public PageReference cancelPage {get;set;}
    public String pageTemplateName {get;set;}
    public List<GNT.DynamicLayoutDefaultValueHelper> listDefaultValues {get;set;}
    
    public RatingAndRecommendationCtrl(ApexPages.StandardController stdController){
        recordId = ApexPages.CurrentPage().getParameters().get('id');
         
        Review__c reviewCaller = [SELECT Id,Status__c,name FROM Review__c WHERE id =: recordId];
        
        pageTemplateName = 'RatingAndRecommendation';
        
    }
    public string getKeyValueMap(){
        Map<String,String> keyValueMap = new Map<String,String>();

        return JSON.serialize(keyValueMap);
    }    
}