UtahLiveDataTest/src/objects/ReviewStep__c.object
<CustomObject>
    <description>[Business] Defines all the details of Review Step defined in the Review of Application/Pre-Application</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Review Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/ReviewStepApplication__c.object
<CustomObject>
    <description>[Business] Connects the Application/Pre-Application with the User and Review Step via this object</description>
    <fields>
        <fullName>ReviewStep__c</fullName>
        <label>Review Step</label>
        <referenceTo>ReviewStep__c</referenceTo>
        <relationshipName>ReviewStepApplications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reviewers Not Assigned</fullName>
                    <default>true</default>
                    <label>Reviewers Not Assigned</label>
                </value>
                <value>
                    <fullName>Reviewers Assigned</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Reviews Complete</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Review Step Application</label>
    <nameField>
        <displayFormat>RSA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Step Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestApplicationReviewHelper.cls
@isTest
private class TestApplicationReviewHelper {

    static testMethod void testWhenClicked() {
    PreapplicationTriggerHelper.skipTrigger = true;
    ApplicationTriggerHelper.skipTrigger = true;
    AnnouncementTriggerHelper.skipTrigger = true;
    PanelUserTriggerHelper.skipAll= true;
    UserTriggerHelper.skipTrigger = true;
    
    ApplicationReviewHelper extReg= new ApplicationReviewHelper();  
         User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
        Test.startTest();
        TestHelper.CreateCustomSettings(true);
        ReviewStep__c rs = TestHelper.getReviewStep(false);
        rs.status__c= 'In Progress';
        insert rs;
        ReviewStepApplication__c rsa = TestHelper.getReviewStepApplication(true);
        // ApexPages.StandardController sc = new ApexPages.standardController(uReg);
         ApexPages.currentPage().getParameters().put('Id',rs.Id);
             
      
            Map<String,String> urlParams = new Map<String,String>();
            urlParams.put('id',rs.Id);
            extReg.urlParams = urlParams;
           
       
         
    
        extReg.clickHandler();
         Test.stopTest();    
    }
   }
   
    static testMethod void testWhenClicked2() {
    PreapplicationTriggerHelper.skipTrigger = true;
    ApplicationTriggerHelper.skipTrigger = true;
    AnnouncementTriggerHelper.skipTrigger = true;
    PanelUserTriggerHelper.skipAll= true;
    UserTriggerHelper.skipTrigger = true;
    
    ApplicationReviewHelper extReg= new ApplicationReviewHelper();  
         User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
        Test.startTest();
        TestHelper.CreateCustomSettings(true);
        ReviewStep__c rs = TestHelper.getReviewStep(false);
        rs.status__c= 'Completed';
        insert rs;
        ReviewStepApplication__c rsa = TestHelper.getReviewStepApplication(true);
        // ApexPages.StandardController sc = new ApexPages.standardController(uReg);
         ApexPages.currentPage().getParameters().put('Id',rs.Id);
             
      
            Map<String,String> urlParams = new Map<String,String>();
            urlParams.put('id',rs.Id);
            extReg.urlParams = urlParams;
           
       
         
    
        extReg.clickHandler();
         Test.stopTest();    
    }
   }
    
    static testMethod void testWhenClicked1() {
    PreapplicationTriggerHelper.skipTrigger = true;
    ApplicationTriggerHelper.skipTrigger = true;
    AnnouncementTriggerHelper.skipTrigger = true;
    PanelUserTriggerHelper.skipAll= true;
    UserTriggerHelper.skipTrigger = true;
    
    ApplicationReviewHelper extReg= new ApplicationReviewHelper();  
         User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
        Test.startTest();
        TestHelper.CreateCustomSettings(true);
        ReviewStep__c rs = TestHelper.getReviewStep(true);
     
        ReviewStepApplication__c rsa = TestHelper.getReviewStepApplication(false);
        rsa.ReviewStep__c = rs.Id;
        insert rsa;
        // ApexPages.StandardController sc = new ApexPages.standardController(uReg);
         ApexPages.currentPage().getParameters().put('Id',rs.Id);
             
      
            Map<String,String> urlParams = new Map<String,String>();
            urlParams.put('id',rs.Id);
            extReg.urlParams = urlParams;
           
       
         
    
        extReg.clickHandler();
         Test.stopTest();    
    }
    }
    
    
}