UtahLiveDataTest/src/objects/SiteVisit__c.object
<CustomObject>
    <description>[Business] This object is used to store all the information related to the Site Visits which is a Post Award Activity.</description>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/SiteVisitActivity__c.object
<CustomObject>
    <description>[Business] Site Visit Activity information is stored in this object it provides the detailed information about the Site Visits Activities</description>
    <fields>
        <fullName>SiteVisit__c</fullName>
        <label>Site Visit</label>
        <referenceTo>SiteVisit__c</referenceTo>
        <relationshipLabel>Site Visit Activities</relationshipLabel>
        <relationshipName>Site_Visit_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Site Visit Activity</label>
    <nameField>
        <displayFormat>SVA-{000}</displayFormat>
        <label>Site Visit Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visit Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestSendToSubrecipientHelper.cls
@isTest
private class TestSendToSubrecipientHelper {
    @isTest static void test_method_one(){
        SiteVisitTriggerHelper.skipTrigger= true;
        GrantTriggerHelper.skipTrigger=true;
        AwardTriggerHelper.skipTrigger=true;
        UserTriggerHelper.skipTrigger=true;
        SiteVisit__c sv= TestHelper.getSiteVisit(true);
        SiteVisitActivity__c sva= TestHelper.getSiteVisitActivity(true);
       Test.startTest();
        	System.debug('Started test');
            ApexPages.currentPage().getParameters().put('id',sv.Id);
            SendToSubrecipientHelper sendtosubrecipienthelper = new SendToSubrecipientHelper();
            sendtosubrecipienthelper.whenClicked();
            ApexPages.currentPage().getParameters().put('id',sva.SiteVisit__c);
            sendtosubrecipienthelper.whenClicked();
            System.debug('Ended test');
        Test.stopTest();
    }
    
}