UtahLiveDataTest/src/objects/SiteVisit__c.object
<CustomObject>
    <description>[Business] This object is used to store all the information related to the Site Visits which is a Post Award Activity.</description>
    <fields>
        <fullName>DocumentDueDate__c</fullName>
        <label>DocumentDueDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>GrantAdministrator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grant Administrator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Site_VisitsdG0V</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SiteVisitName__c</fullName>
        <label>Site Visit Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Report Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Planned and Submitted to Subrecipient</fullName>
                </value>
                <value>
                    <fullName>Visited</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Report Submitted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Submitted to Grantor</fullName>
                </value>
                <value>
                    <fullName>Reviewed by Grantor</fullName>
                </value>
                <value>
                    <fullName>Sent to Subrecipient</fullName>
                </value>
                <value>
                    <fullName>Feedback from Subrecipient</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubAwardee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub-Awardee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Site_Visits6</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <recordTypes>
        <fullName>Grantor</fullName>
        <active>true</active>
        <description>Grantor</description>
        <label>Grantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/SiteVisitActivity__c.object
<CustomObject>
    <description>[Business] Site Visit Activity information is stored in this object it provides the detailed information about the Site Visits Activities</description>
    <fields>
        <fullName>SiteVisit__c</fullName>
        <label>Site Visit</label>
        <referenceTo>SiteVisit__c</referenceTo>
        <relationshipLabel>Site Visit Activities</relationshipLabel>
        <relationshipName>Site_Visit_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SubRecipientResponse__c</fullName>
        <label>SubRecipientResponse</label>
        <type>TextArea</type>
    </fields>
    <label>Site Visit Activity</label>
    <nameField>
        <displayFormat>SVA-{000}</displayFormat>
        <label>Site Visit Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visit Activities</pluralLabel>
    <recordTypes>
        <fullName>External</fullName>
        <active>true</active>
        <description>This is Site Visit Findings for Applicant.</description>
        <label>External</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/UserRegistration__c.object
<CustomObject>
    <description>[Business] Need more Detailed info from Swati Singh</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>External Registration</label>
    <nameField>
        <displayFormat>RG-{000000}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Registration</pluralLabel>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <label>Applicant</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestSubmitSiteVisitCtrl.cls
@isTest
public with sharing class TestSubmitSiteVisitCtrl {

    @isTest 
    static void plannedTest() {
        UserTriggerHelper.skipTrigger=true;
        User admin = TestHelper.getAdminUser(true);
        User suser = TestHelper.getStandardUser(true);
        System.runAs(admin) {
            GrantTriggerHelper.skipTrigger = true;
            AwardTriggerHelper.skipTrigger = true;
            RolesAndResponsibilitiesTriggerHelper.skipTrigger = true;
            AccountTriggerHelper.skipTrigger = true;
            TaskTriggerHelper.skipTrigger=true;
            SiteVisitTriggerHelper.skipTrigger = true;
        }
            SiteVisit__c sv = TestHelper.getSiteVisit(true);
            sv.Status__c = 'Planned and Submitted to Subrecipient';
            sv.GrantAdministrator__c = admin.Id;
            sv.Subawardee__c = suser.Id;
            sv.DocumentDueDate__c = System.TODAY() + 7;
        
            
        System.runAs(admin) {
            GNT__AttachmentExtension__c attach1 = new GNT__AttachmentExtension__c();
            
            attach1.GNT__Classification__c = 'Test';
            attach1.GNT__ParentId__c = sv.Id;
            insert attach1;
            attach1.OwnerId = admin.Id;
            update attach1;
        }

        System.runAs(suser) {

            GNT__AttachmentExtension__c attach2 = new GNT__AttachmentExtension__c();
            
            attach2.GNT__Classification__c = 'Test';
            attach2.GNT__ParentId__c = sv.Id;
            insert attach2;
            attach2.OwnerId = suser.Id;
            update attach2;
        }
        update sv;

        Test.startTest();
        ApexPages.currentPage().getParameters().put('id',sv.Id);
        SubmitSiteVisitCtrl ctrl = new SubmitSiteVisitCtrl();
        ctrl.whenClicked();
        SiteVisit__c status = [SELECT Status__c from SiteVisit__c where Id =: sv.Id LIMIT 1];
        //System.assertEquals('Submitted to Grantor', status.Status__c);
        Test.stopTest();
        }
    

    @isTest 
    static void sentTest() {
        UserTriggerHelper.skipTrigger=true;
        User admin = TestHelper.getAdminUser(true);
        System.runAs(admin) {
            GrantTriggerHelper.skipTrigger = true;
            AwardTriggerHelper.skipTrigger = true;
            RolesAndResponsibilitiesTriggerHelper.skipTrigger = true;
            AccountTriggerHelper.skipTrigger = true;
            TaskTriggerHelper.skipTrigger=true;
            SiteVisitTriggerHelper.skipTrigger = true;
        
            SiteVisit__c sv = TestHelper.getSiteVisit(true);
            sv.Status__c = 'Sent to Subrecipient';
            sv.GrantAdministrator__c = admin.Id;
            sv.DocumentDueDate__c = System.TODAY() + 7;
            sv.SiteVisitName__c = 'Test Name';
            update sv;

            SiteVisitActivity__c svact = new SiteVisitActivity__c();
            
            svact.SiteVisit__c = sv.Id;
            svact.SubRecipientResponse__c = 'Test Response';
            RecordType externalRT = [select id from recordtype where name = 'External' and sobjecttype = 'SiteVisitActivity__c' limit 1];
            // uReg.RecordTypeId = Schema.SObjectType.UserRegistration__c.getRecordTypeInfosByName().get('Applicant').getRecordTypeId(); 
            svact.RecordTypeId = externalRT.Id;
            insert svact;
            
            //svact.RecordType.Name = 'External';
            //update svact;
           // System.debug('RecordName: ' + svact.RecordType.Name);
            System.debug('TestClassObj: '+svact);

            Test.startTest();
            ApexPages.currentPage().getParameters().put('id',sv.Id);
            SubmitSiteVisitCtrl ctrl = new SubmitSiteVisitCtrl();
            ctrl.whenClicked();
            SiteVisit__c status = [SELECT Status__c from SiteVisit__c where Id =: sv.Id LIMIT 1];
            //System.assertEquals('Feedback from Subrecipient', status.Status__c);

            Test.stopTest();
        }
    }

}