UtahLiveDataTest/src/objects/SiteVisit__c.object
<CustomObject>
    <description>[Business] This object is used to store all the information related to the Site Visits which is a Post Award Activity.</description>
    <fields>
        <fullName>VisitEndDateTime__c</fullName>
        <description>Visit End Date and Time</description>
        <inlineHelpText>Visit End Date and Time</inlineHelpText>
        <label>Visit End Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/SiteVisitActivity__c.object
<CustomObject>
    <description>[Business] Site Visit Activity information is stored in this object it provides the detailed information about the Site Visits Activities</description>
    <fields>
        <fullName>SiteVisit__c</fullName>
        <label>Site Visit</label>
        <referenceTo>SiteVisit__c</referenceTo>
        <relationshipLabel>Site Visit Activities</relationshipLabel>
        <relationshipName>Site_Visit_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Site Visit Activity</label>
    <nameField>
        <displayFormat>SVA-{000}</displayFormat>
        <label>Site Visit Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visit Activities</pluralLabel>
    <recordTypes>
        <fullName>External</fullName>
        <active>true</active>
        <description>This is Site Visit Findings for Applicant.</description>
        <label>External</label>
    </recordTypes>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>This is Site Visit Activity for Grantor</description>
        <label>Internal</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestSiteVisitActivityAddEditCtrl.cls
@isTest
private with sharing class TestSiteVisitActivityAddEditCtrl{
    static testMethod void testController() {
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          
          System.runAs(u){
            GrantTriggerHelper.skipTrigger = true;
            
            SiteVisit__c sv = TestHelper.getSiteVisit(false);
            //Date myDate = Date.newInstance(2016, 11, 18);
            //Time myTime = Time.newInstance(3, 3, 3, 0);
            DateTime dt = DateTime.now();
            sv.VisitEndDateTime__c = dt;
            insert sv;
            
            SiteVisitActivity__c sva = new SiteVisitActivity__c(SiteVisit__c=sv.Id);
            insert sva;
            
            Test.startTest();
            ApexPages.StandardController sc = new ApexPages.standardController(sva);
            ApexPages.currentPage().getParameters().put('Id',sva.id);
            ApexPages.currentPage().getParameters().put('siteVisitId',sv.id);
            ApexPages.CurrentPage().getParameters().put('requestType','External');
            
            SiteVisitActivityAddEditCtrl ctrl = new SiteVisitActivityAddEditCtrl(sc);
            ctrl.resultType = 'Test';
            ctrl.getKeyValueMap();
            Test.stopTest();
            
        }
        
    }
    
        static testMethod void testController2() {
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          
          System.runAs(u){
            GrantTriggerHelper.skipTrigger = true;
            
            SiteVisit__c sv = TestHelper.getSiteVisit(false);
            //Date myDate = Date.newInstance(2016, 11, 18);
            //Time myTime = Time.newInstance(3, 3, 3, 0);
            DateTime dt = DateTime.now();
            sv.VisitEndDateTime__c = dt;
            insert sv;
            
            SiteVisitActivity__c sva = new SiteVisitActivity__c(SiteVisit__c=sv.Id);
            insert sva;
            
            Test.startTest();
            ApexPages.StandardController sc = new ApexPages.standardController(sva);
            ApexPages.currentPage().getParameters().put('Id',sva.id);
            ApexPages.currentPage().getParameters().put('siteVisitId',sv.id);
            ApexPages.CurrentPage().getParameters().put('requestType','Internal');
            
            SiteVisitActivityAddEditCtrl ctrl = new SiteVisitActivityAddEditCtrl(sc);
            ctrl.getKeyValueMap();
            Test.stopTest();
            
        }
        
    }
}