UtahLiveDataTest/src/objects/TermCondition__c.object
<CustomObject>
    <description>[Business] Terms and Conditions for Grants ,Awards (The lookup to Package may not be required in this case )</description>
    <fields>
        <fullName>SubmissionType__c</fullName>
        <label>Submission Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Progress Report</fullName>
                </value>
                <value>
                    <fullName>Financial Report</fullName>
                </value>
                <value>
                    <fullName>Payment Request</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MST:Term and Condition</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/TermConditionSchedule__c.object
<CustomObject>
    <description>[Business] Schedule for the Terms and Conditions</description>
    <fields>
        <fullName>TermAndCondition__c</fullName>
        <label>Term and Condition</label>
        <referenceTo>TermCondition__c</referenceTo>
        <relationshipLabel>Term Condition Schedules</relationshipLabel>
        <relationshipName>Term_Condition_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Term Condition Schedule</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Term Condition Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Term Condition Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ExpenseReportScheduleViewCtrl.cls
public with sharing class ExpenseReportScheduleViewCtrl {
    //Properties
    //public String phaseId{get;set;}
    public String flexTableHeader {get;set;}
    public String termConditionId {get;set;}
    public ExpenseReportScheduleViewCtrl(){
        //phaseId = ApexPages.CurrentPage().getParameters().get('id');        
        flexTableHeader  = 'Expense Report Schedule';
    }
    
    public string getKeyValueMap(){
        Map<String,String> keyValueMap = new Map<String,String>(); 
       TermConditionSchedule__c tcs = [SELECT Id,TermAndCondition__c 
                                        FROM TermConditionSchedule__c 
                                        WHERE TermAndCondition__r.SubmissionType__c = 'Payment Request' LIMIT  1];
        system.debug('tcs: '+termConditionId);
        termConditionId = tcs.TermAndCondition__c;                              
        keyValueMap.put('termConditionId', termConditionId);    
        return JSON.serialize(keyValueMap);
    }
    
   /* public string getListParameters(){
        Map<String,Set<String>> listParams = new Map<String,Set<String>>();
        Set<String> flexTableIdSet = new Set<String>();
        List<Id> flexTableIds = new List<Id>();
        if(phaseId != null && phaseId != '') {
            Map<Id,GNT__SearchConfig__c> flexTableMap = new Map<Id,GNT__SearchConfig__c>([SELECT Id,FlexTableConfig__c
                                                                                FROM GNT__SearchConfig__c 
                                                                                WHERE PhaseConfig__r.Id =: phaseId]);           
            Set<String> fTabIdSet = new Set<String>();
            for(GNT__SearchConfig__c ftab: flexTableMap.values()){
                fTabIdSet.add((String)ftab.FlexTableConfig__c);    
            }
            listParams.put('searchFlexTables',fTabIdSet);               
        }
        return JSON.serialize(listParams);        
    }*/
}