UtahLiveDataTest/src/objects/TermConditionSchedule__c.object
<CustomObject>
    <description>[Business] Schedule for the Terms and Conditions</description>
    <fields>
        <fullName>TermAndCondition__c</fullName>
        <label>Term and Condition</label>
        <referenceTo>TermCondition__c</referenceTo>
        <relationshipLabel>Term Condition Schedules</relationshipLabel>
        <relationshipName>Term_Condition_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Term Condition Schedule</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Term Condition Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Term Condition Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TermConditionScheduleNewCtrl.cls
/**
* Edit page controller for the TermConditionSchedule__c object
* 
* CHANGE HISTORY
* =============================================================================
* Date          Name            Description
* 02/26/2015    Nishit Babaria   Created
* =============================================================================
*/

public with sharing class TermConditionScheduleNewCtrl{

    //properties
    public PageReference savePage {get;set;}
    public PageReference cancelPage {get;set;}
    public String pageTemplateName {get;set;}
    public ID termConditionId {get;set;}
    public List<GNT.DynamicLayoutDefaultValueHelper> listDefaultValues {get;set;}
    
    
    public TermConditionScheduleNewCtrl(){
        pageTemplateName = ApexPages.CurrentPage().getParameters().get('template');
        termConditionId = ApexPages.CurrentPage().getParameters().get('termConditionId'); 
        savePage = Page.TermConditionView;
        savePage.getParameters().put('id', termConditionId);
        if(termConditionId != null){
            cancelPage = Page.TermConditionView;
            cancelPage.getParameters().put('id', termConditionId);
        }
		
		listDefaultValues = new List<GNT.DynamicLayoutDefaultValueHelper>();
        if(termConditionId != null){
            GNT.DynamicLayoutDefaultValueHelper dv = new GNT.DynamicLayoutDefaultValueHelper(AppUtils.getNamespacePrefix()+'TermAndCondition__c',termConditionId,true);
            listDefaultValues.add(dv);  
        }
    }
    
    public string getKeyValueMap(){
        Map<String,String> keyValueMap = new Map<String,String>();
        if(termConditionId != null){
            keyValueMap.put('termConditionId',termConditionId);
        }
        return JSON.serialize(keyValueMap);
    }
}