UtahLiveDataTest/src/objects/TermConditionSchedule__c.object
<CustomObject>
    <description>[Business] Schedule for the Terms and Conditions</description>
    <fields>
        <fullName>DueDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TaskCreationDate__c</fullName>
        <label>Task Creation Date</label>
        <type>DateTime</type>
    </fields>
    <label>Term Condition Schedule</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Term Condition Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Term Condition Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestTermConditionScheduleTrigger.cls
@isTest(SeeAllData=false)
private class TestTermConditionScheduleTrigger {
    @isTest(onInstall=false)
    public static void testAll() {                            
        Date startDate = System.today();
        Date endDate = startDate.addMonths(1);
        Date dueDate = endDate - 2 ; 
        Date taskDate = dueDate - 1;  
        TermConditionSchedule__c tcs = new TermConditionSchedule__c(StartDate__c = startDate, EndDate__c = endDate, 
                                                                    TaskCreationDate__c = taskDate, DueDate__c = dueDate);
        
        Test.startTest();
            
            try {

                insert tcs;
                tcs.EndDate__c =startDate.addMonths(2);
                update tcs;
            }
            catch (DmlException e) {
                system.debug(e.getMessage());
            }
            
        Test.stopTest();
    }
}