UtahLiveDataTest/src/objects/TermCondition__c.object
<CustomObject>
    <description>[Business] Terms and Conditions for Grants ,Awards (The lookup to Package may not be required in this case )</description>
    <fields>
        <fullName>SubmissionType__c</fullName>
        <label>Submission Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Progress Report</fullName>
                </value>
                <value>
                    <fullName>Financial Report</fullName>
                </value>
                <value>
                    <fullName>Payment Request</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MST:Term and Condition</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

UtahLiveDataTest/src/objects/TermConditionSchedule__c.object
<CustomObject>
    <description>[Business] Schedule for the Terms and Conditions</description>
    <fields>
        <fullName>TermAndCondition__c</fullName>
        <label>Term and Condition</label>
        <referenceTo>TermCondition__c</referenceTo>
        <relationshipLabel>Term Condition Schedules</relationshipLabel>
        <relationshipName>Term_Condition_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Term Condition Schedule</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Term Condition Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Term Condition Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/TestEditTermConditionScheduleHandler.cls
@isTest
private with sharing class TestEditTermConditionScheduleHandler{
    static testMethod void testclickHandler() {
       
          User u = TestHelper.getAdminUser(true);
          System.runAs(u){

              AccountTriggerHelper.skipAll=true;
              TermCondition__c termCond = TestHelper.getTermCondition(false,'Payment Request');
              termCond.SubmissionType__c='Payment Request';
              insert termCond;
              
              TermConditionSchedule__c termCondSch = new TermConditionSchedule__c();
              termCondSch.TermAndCondition__c = termCond.Id;
              insert termCondSch;

               
              Test.startTest();
              EditTermConditionScheduleHandler ctrl = new EditTermConditionScheduleHandler();
              ctrl.clickHandler();
              Test.stopTest();
          }
        
    }
    
}