UtahLiveDataTest/src/objects/UserRegistration__c.object
<CustomObject>
    <description>[Business] Need more Detailed info from Swati Singh</description>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>External Registration</label>
    <nameField>
        <displayFormat>RG-{000000}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Registration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/UserRegistrationRejectionHelper.cls
global with sharing class UserRegistrationRejectionHelper extends GNT.DynamicLayoutActionRedirect{
    
    
    global override PageReference whenClicked(){ 
         Savepoint sp = Database.setSavepoint();
        // Id recordId = layoutHolder.getPrimarySObject().Id;
         Id recordId = apexpages.currentpage().getparameters().get('id');
         UserRegistration__c uReg = [Select id, Comments__c
                                     from UserRegistration__c where id = :recordId];
        try{
            if(uReg.Comments__c == null){
                //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Please click the edit button and enter the Approval comments'));
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, GNT.ErrorMessageHelper.fetchMessage('GEN-GRNTR-95308')));
                return null;
            }
            uReg.Status__c='Rejected';
            update uReg;
                        
        }catch(Exception e){
            Database.rollback(sp);
            //System.Debug('UserRegistrationHelper whenClicked...'+e.getMessage());
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, e.getMessage())); 
        }   
        PageReference pageRef= new PageReference('/apex/InternalUserRegistrationView?id='+recordId);
        pageRef.setRedirect(true);
        return pageRef;                      
    }   
}