UtahLiveDataTest/src/objects/UserRegistration__c.object
<CustomObject>
    <description>[Business] Need more Detailed info from Swati Singh</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Review In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>External Registration</label>
    <nameField>
        <displayFormat>RG-{000000}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Registration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/UserRegPurgeHandler.cls
global with sharing class UserRegPurgeHandler extends GNT.BatchApexHandler{ /*Database.Batchable<sObject> {*/
    
 //global Database.QueryLocator start(Database.BatchableContext BC){
 global override String getQuery() {
    String query = 'Select id,name from UserRegistration__c ' +
                    'where Status__c IN(\'In Progress\',\'New\')'; 
                
    
    //return Database.getQueryLocator(query);
    return query;
 }
 
 //global void execute(Database.BatchableContext BC, List<UserRegistration__c> records) {
   global override void execute(List<SObject> scope){
    List<UserRegistration__c> records = (List<UserRegistration__c>)scope;
    List<UserRegistration__c> uRegToDelete = new List<UserRegistration__c>();
   
    
   
    Savepoint sp = Database.setSavepoint();
    try{
        for(UserRegistration__c uReg : records){
            
            uRegToDelete.add(uReg);
            }
            
     if(uRegToDelete.size()>0){
            delete uRegToDelete;
        }
            
           
   }catch(Exception ex){
        Database.rollback(sp);
        System.debug('UserRegPurgeHandler >>>execute Exception ' + ex.getMessage());
    }
    
 }
 
// global void finish(Database.BatchableContext BC) {
      global override void finish(){
      
 }
 

     global static void scheduleMe() {
        UserRegPurgeHandler  batch = new UserRegPurgeHandler();
        String cronExpression = GNT.BatchApexJobScheduler.prepareJobsSchTime(System.now(), 2);
        String jobName = GNT.BatchApexJobScheduler.getUniqueJobName('UserRegPurgeHandler');
        if (!Test.isRunningTest()) {
            System.schedule(jobName, cronExpression, new GNT.BatchApexJobScheduler(batch, 1));
        }
    } 
 
}