UtahLiveDataTest/src/objects/UserRegistration__c.object
<CustomObject>
    <description>[Business] Need more Detailed info from Swati Singh</description>
    <fields>
        <fullName>COIDate__c</fullName>
        <label>COI Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>COIStatus__c</fullName>
        <label>COI Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NDADate__c</fullName>
        <label>NDA Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NDALookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NDA Lookup</label>
        <referenceTo>MasterAgreement__c</referenceTo>
        <relationshipLabel>External Registration</relationshipLabel>
        <relationshipName>External_Registration</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NDAStatus__c</fullName>
        <label>NDA Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>External Registration</label>
    <nameField>
        <displayFormat>RG-{000000}</displayFormat>
        <label>User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Registration</pluralLabel>
    <recordTypes>
        <fullName>AdditionalApplicant</fullName>
        <active>true</active>
        <label>Additional Applicant</label>
    </recordTypes>
    <recordTypes>
        <fullName>AdditionalApplicantSecondary</fullName>
        <active>true</active>
        <label>Additional Applicant Secondary</label>
    </recordTypes>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <label>Applicant</label>
    </recordTypes>
    <recordTypes>
        <fullName>IndApplicant</fullName>
        <active>true</active>
        <description>This is an individual applicant</description>
        <label>Ind Applicant</label>
    </recordTypes>
    <recordTypes>
        <fullName>Reviewer</fullName>
        <active>true</active>
        <label>Reviewer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UtahLiveDataTest/src/classes/ExternalRegistrationCOIAgreeHelper.cls
global with sharing class ExternalRegistrationCOIAgreeHelper extends GNT.DynamicLayoutActionRedirect{
    private String securityToken;
    
    global override PageReference whenClicked(){ 
         Savepoint sp = Database.setSavePoint();
          try{
             Id recordId = apexpages.currentpage().getparameters().get('id');
             UserRegistration__c userReg = [Select Id, Name,NDADate__c,NDAStatus__c,NDALookup__c,RecordType.DeveloperName from UserRegistration__c 
             where id =:recordId Limit 1];
              //system.debug('--Inside ApplicationSubmissionHelper--'+app);
              userReg.COIDate__c= System.today();
              userReg.COIStatus__c= 'Accepted';
              UserRegistrationTriggerHelper.skipTrigger = true;
              update userReg ;
              if(userReg.RecordType.DeveloperName == 'Reviewer'){
	               PageReference pf = Page.ExternalRegProfileEdit;
	               pf.getParameters().put('id', userReg.Id);
	               pf.setRedirect(true);
	               return pf;
              } else if(userReg.RecordType.DeveloperName == 'IndApplicant'){
	              PageReference pf = Page.ExtRegIndApplicantSearch;
	              pf.getParameters().put('id', userReg.Id);
	              pf.setRedirect(true);
	              return pf;
              }else if(userReg.RecordType.DeveloperName == 'Applicant'){
	              PageReference pf = Page.ApplicantRegistrationPage2;
	              pf.getParameters().put('id', userReg.Id);
	              pf.setRedirect(true);
	              return pf;
              }else if(userReg.RecordType.DeveloperName == 'AdditionalApplicant') {
              	  PageReference pf = Page.ExternalRegProfileEdit;
	              pf.getParameters().put('id', userReg.Id);
	              pf.setRedirect(true);
	              return pf;
              }
              else if(userReg.RecordType.DeveloperName == 'AdditionalApplicantSecondary') {
                  PageReference pf = Page.ExternalRegProfileEdit;
                pf.getParameters().put('id', userReg.Id);
                pf.setRedirect(true);
                return pf;
              }
               else{
              	return null;}
             
            
              
          }catch(Exception ex){
            Database.rollback(sp);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, ex.getMessage())); 
            return null;
          }
    }

}